/** Presentation contracts only. Lifecycle, eligibility, validation, and ranks come from governed backend read models. */
export type BlogView="pipeline"|"review"|"approved"|"publishing"|"published"|"revision";
export interface BlogWorkspaceQuery{businessPackageId:string;view:BlogView;page:number;pageSize:number;search?:string;status?:string;language?:string;market?:string;date?:string;sort?:string}
export interface BlogListItemView{id:string;businessPackageId:string;h1:string;canonicalQuestion:string;language:string;market:string;draftVersion:number;validationState:string;primaryBook:string;created:string;priority:string;status:string;approvedAt?:string;packageStatus?:string;publishingStatus?:string;publishedAt?:string;canonicalUrl?:string;promotionStatus?:string}
export interface ArticleBlockView{type:"h1"|"h2"|"h3"|"paragraph"|"link"|"book-link"|"primary-cta";text:string;url?:string}
export interface ValidationFindingView{label:string;state:"PASS"|"WARN"|"FAIL";issues:readonly {severity:string;explanation:string;section?:string;nextAction?:string}[]}
export interface BlogDetailView extends BlogListItemView{eligibleForApproval:boolean;staleVersion:boolean;supersededByVersion?:number;article:readonly ArticleBlockView[];headings:readonly {level:"H1"|"H2"|"H3";text:string;lineage?:string}[];requiredCoverage:readonly string[];validations:readonly ValidationFindingView[];books:readonly {role:"Primary Book"|"Related Book 1"|"Related Book 2";title:string;url:string;linkStatus:string;placement:string;ctaText?:string}[];knowledgeSources:readonly {title:string;sourceType:string;language:string;version:string;status:string;reference:string}[];knowledgeGap?:string;recommendation:{questionStrength:string;sourceDiversity:string;trend:string;coverageGap:string;opportunity:string;objective:string};history:readonly {at:string;event:string;version?:number;note?:string}[];publication?:{packageStatus:string;metaTitle:string;metaDescription:string;slug:string;canonicalUrlPreview:string;structuredDataSummary:string;searchValidation:string;aiValidation:string};wordpress?:{status:string;site:string;attempt:number;authenticationState:string;postId?:string;canonicalUrl?:string;started?:string;updated:string};promotion?:{state:string;target:number;targetLabel:string;lineage:readonly {headingLevel:string;heading:string;pin:string;state:string;previewId?:string}[]};performance?:{blogVisits:number|null;searchClicks:number|null;pinterestReferrals:number|null;primaryBookCtaClicks:number|null;relatedBookClicks:number|null;aiDiscoveryObservations:number|null};previousReviewedVersion?:number;revisionNote?:string}
export interface BlogWorkspaceReadModel{businessPackageId:string;items:readonly BlogListItemView[];total:number;page:number;pageSize:number;counts:Readonly<Record<string,number>>;pipeline:readonly {state:string;count:number}[]}
export type BlogDecision="Approve"|"ReturnForRevision"|"Reject"|"Delete"|"Defer"|"HoldPinterestPromotion"|"ResumePinterestPromotion";
export type BlogActionState="Submitting"|"Succeeded"|"Failed"|"Conflict"|"AuthorizationDenied"|"StaleVersion";
export interface BlogWorkspaceGateway{read(query:BlogWorkspaceQuery):Promise<BlogWorkspaceReadModel>;detail(query:{businessPackageId:string;blogId:string;version?:number}):Promise<BlogDetailView>;decide(command:{businessPackageId:string;blogId:string;draftVersion:number;decision:BlogDecision;instructions?:string;note?:string}):Promise<{state:BlogActionState}>}
