/** GUI-005 presentation contract. Ranking, health, timing, eligibility, and analytics are backend authority. */
export type PinterestView="overview"|"queue"|"all"|"timing"|"scheduled"|"published"|"performance"|"attention";
export type PinterestPeriod="7D"|"30D"|"90D"|"12M"|"ALL";
export type QueueHealth="Healthy"|"BelowTarget"|"BelowMinimum"|"Empty"|"OverTarget"|"Paused"|"AttentionRequired";
export type PinterestAttentionState="AuthenticationRequired"|"InvalidCredential"|"PermissionDenied"|"RateLimited"|"VerificationRequired"|"RebalanceRequired"|"PublisherFailure"|"QueueBelowMinimum"|"ScheduleConflict"|"ValidationFailure";
export type PinterestAction="MoveToTop"|"Hold"|"Release"|"Cancel"|"Reschedule"|"SendBackForRevision"|"SetMinimumPublicationInterval"|"ApplyCadenceRecommendation";
export type ActionState="Submitting"|"Succeeded"|"Failed"|"Conflict"|"ValidationFailed"|"AuthorizationDenied"|"StaleVersion";
export interface PinListItem {id:string;businessPackageId:string;title:string;topic:string;previewUrl?:string;status:string;sourceType:string;headingLevel?:"H1"|"H2"|"H3";headingText?:string;blogId?:string;blogTitle?:string;language:string;market:string;destination:string;priority:string;queueOrder?:number;recommendedTime?:string;scheduledTime?:string;publishedTime?:string;timezone?:string;freshness:string;performance?:{impressions:number|null;outboundClicks:number|null;saves:number|null;ctr:number|null};executionReadiness?:string;conflicts?:readonly string[];timingDeviationMinutes?:number|null}
export interface PinDetail extends PinListItem {description:string;cta:string;visualReference:string;creationPlanVersion:string;copyVersion:string;visualVersion:string;publishingCandidateVersion:string;scheduledPublicationVersion?:string;publishedPinVersion?:string;validation:{state:"PASS"|"WARN"|"FAIL";issues:readonly {field:string;message:string}[]};history:readonly {at:string;event:string;state?:string}[];measurementWindows:readonly {from:string;to:string;impressions:number|null;outboundClicks:number|null;saves:number|null;ctr:number|null}[];canonicalQuestion?:string;staleVersion?:boolean}
export interface PinterestWorkspaceReadModel {businessPackageId:string;view:PinterestView;items:readonly PinListItem[];total:number;page:number;pageSize:number;counts:{ready:number;scheduled:number;held:number;publishedToday:number};queue:{health:QueueHealth;currentCount:number;targetBuffer:number;minimumBuffer:number;coverage:string};nextPublication?:PinListItem;timing:{mode:string;adaptiveTiming:string;adaptiveTimezone:string;resolvedTimezone:string;marketContext:string;minimumPublicationIntervalMinutes:number;recommendedWindows:readonly {rank:number;window:string;explanation?:string}[];confidence:string;confidenceExplanation?:string;cadenceRecommendationMinutes?:number;learningState:string};publisher:{state:string;providerState:string;authenticationState:string};performance:{period:PinterestPeriod;summary:{impressions:number|null;outboundClicks:number|null;saves:number|null;ctr:number|null;publishedPins:number|null};comparison?:Readonly<Record<string,number|null>>;points:readonly {at:string;impressions:number;outboundClicks:number;saves:number;ctr:number|null}[];topPerformers:readonly PinListItem[]};attention:readonly {id:string;state:PinterestAttentionState;title:string;detail:string;retryAt?:string;route?:string}[];promotions:readonly {blogId:string;blogTitle:string;ready:number;target:number;state:string;pins:readonly PinListItem[]}[]}
export interface PinterestWorkspaceGateway {read(query:{businessPackageId:string;view:PinterestView;page:number;pageSize:number;search?:string;status?:string;source?:string;language?:string;market?:string;topic?:string;date?:string;sort?:string;period?:PinterestPeriod}):Promise<PinterestWorkspaceReadModel>;detail(query:{businessPackageId:string;pinId:string}):Promise<PinDetail>;command(command:{businessPackageId:string;pinId?:string;version?:string;action:PinterestAction;minimumPublicationIntervalMinutes?:number}):Promise<{state:ActionState;message?:string}>}
