import { Confidence, Evidence, Freshness, FreshnessStatus, MarketObservation } from "../../../intelligence/market/MarketIntelligenceDomain.ts";
import { CrossMarketValidation, CrossMarketValidationResult, MarketPattern, PatternCandidate, PatternConfidence, PatternDecay, PatternDirection, PatternEvidence, PatternEvidenceRole, PatternId, PatternStability, PatternStatus, PatternWindow } from "./PatternIntelligenceDomain.ts";
import type { PatternQuery } from "./PatternRepository.ts";
import { PatternIntelligenceException } from "./PatternIntelligenceException.ts";
import { PatternRepository } from "./PatternRepository.ts";

export type EvidenceRoles=ReadonlyMap<string,PatternEvidenceRole>;
export class PatternIntelligenceService {
 constructor(readonly patterns:PatternRepository){}
 registerCandidate(candidate:PatternCandidate):PatternCandidate{return this.patterns.createCandidate(candidate);}
 evaluateIndependence(observations:readonly MarketObservation[]):readonly MarketObservation[]{const seenIds=new Set<string>(),seenGroups=new Set<string>(),result:MarketObservation[]=[];for(const observation of [...observations].sort((a,b)=>a.observedAt.getTime()-b.observedAt.getTime()||a.id.value.localeCompare(b.id.value))){if(seenIds.has(observation.id.value))continue;seenIds.add(observation.id.value);const day=observation.observedAt.toISOString().slice(0,10);const group=`${observation.sourceId.value}|${observation.provenance.origin}|${day}`;if(!seenGroups.has(group)){seenGroups.add(group);result.push(observation);}}return Object.freeze(result);}
 aggregateEvidence(candidate:PatternCandidate,roles:EvidenceRoles=new Map()):PatternEvidence{const unique=new Map(candidate.evidence.map(e=>[e.id.value,e]));const support:Evidence[]=[],contradict:Evidence[]=[],neutral:Evidence[]=[];for(const evidence of unique.values()){const role=roles.get(evidence.id.value)??PatternEvidenceRole.Supporting;(role===PatternEvidenceRole.Supporting?support:role===PatternEvidenceRole.Contradicting?contradict:neutral).push(evidence);}const independent=this.evaluateIndependence(candidate.observations);return new PatternEvidence(support,contradict,neutral,Math.min(independent.length,unique.size),new Set([...unique.values()].map(e=>e.provenance.sourceId.value)).size);}
 evaluateFreshness(latest:Date,at:Date):Freshness{const days=(at.getTime()-latest.getTime())/86400000;if(days<0)throw new PatternIntelligenceException("Evaluation cannot precede latest observation","INVALID_EVALUATION_TIME");return new Freshness(days<=30?FreshnessStatus.Current:days<=90?FreshnessStatus.Ageing:days<=180?FreshnessStatus.Stale:FreshnessStatus.Expired,at);}
 evaluateStability(window:PatternWindow,evidence:PatternEvidence):PatternStability{if(evidence.contradicting.length>evidence.supporting.length)return PatternStability.Unstable;if(evidence.contradicting.length>0)return PatternStability.Weakening;if(window.independentObservationCount<2)return PatternStability.Emerging;if(window.independentObservationCount<4)return PatternStability.Developing;return PatternStability.Stable;}
 evaluateDecay(freshness:Freshness,evidence:PatternEvidence):PatternDecay{if(freshness.status===FreshnessStatus.Expired)return PatternDecay.Expired;if(freshness.status===FreshnessStatus.Stale)return PatternDecay.High;if(evidence.contradicting.length>=evidence.supporting.length&&evidence.contradicting.length>0)return PatternDecay.High;if(freshness.status===FreshnessStatus.Ageing)return PatternDecay.Moderate;if(evidence.contradicting.length>0)return PatternDecay.Low;return PatternDecay.None;}
 evaluateCrossMarketSupport(candidate:PatternCandidate,evidence:PatternEvidence,at:Date):CrossMarketValidation{const contexts=[...new Set(candidate.observations.map(o=>o.marketContext))].sort(),groups=[...new Set(candidate.observations.map(o=>o.sourceId.value))].sort();let result=CrossMarketValidationResult.InsufficientEvidence;if(contexts.length===1)result=CrossMarketValidationResult.SingleContext;if(contexts.length>1&&groups.length>1)result=evidence.contradicting.length?CrossMarketValidationResult.ConflictingContexts:CrossMarketValidationResult.MultiContextSupported;return new CrossMarketValidation(contexts,groups,evidence.supporting,new Confidence(result===CrossMarketValidationResult.MultiContextSupported?.9:result===CrossMarketValidationResult.ConflictingContexts?.3:.4),at,result);}
 evaluateConfidence(evidence:PatternEvidence,freshness:Freshness,cross:CrossMarketValidation):PatternConfidence{const total=Math.max(1,evidence.evidenceCount),consistency=(evidence.supporting.length-evidence.contradicting.length)/total,raw=.1+Math.min(evidence.independentEvidenceCount,4)*.12+Math.min(evidence.sourceCount,3)*.08+Math.max(-.25,consistency*.25)+(freshness.status===FreshnessStatus.Current?.12:freshness.status===FreshnessStatus.Ageing?.05:-.1)+(cross.result===CrossMarketValidationResult.MultiContextSupported?.08:cross.result===CrossMarketValidationResult.ConflictingContexts?-.12:0);const value=Math.max(0,Math.min(1,Number(raw.toFixed(3))));return new PatternConfidence(new Confidence(value),[{name:"independence",contribution:Math.min(evidence.independentEvidenceCount,4)*.12,explanation:`${evidence.independentEvidenceCount} independent evidence groups`},{name:"source-diversity",contribution:Math.min(evidence.sourceCount,3)*.08,explanation:`${evidence.sourceCount} sources`},{name:"consistency",contribution:Number((consistency*.25).toFixed(3)),explanation:`${evidence.supporting.length} supporting and ${evidence.contradicting.length} contradicting`},{name:"freshness",contribution:freshness.status===FreshnessStatus.Current?.12:freshness.status===FreshnessStatus.Ageing?.05:-.1,explanation:freshness.status},{name:"cross-market",contribution:cross.result===CrossMarketValidationResult.MultiContextSupported?.08:cross.result===CrossMarketValidationResult.ConflictingContexts?-.12:0,explanation:cross.result}]);}
 evaluateCandidate(candidate:PatternCandidate,direction:PatternDirection,roles:EvidenceRoles,at:Date):MarketPattern{const evidence=this.aggregateEvidence(candidate,roles),independent=this.evaluateIndependence(candidate.observations),window=new PatternWindow(candidate.firstObservedAt,candidate.latestObservedAt,candidate.observations.length,Math.max(1,independent.length)),freshness=this.evaluateFreshness(candidate.latestObservedAt,at),cross=this.evaluateCrossMarketSupport(candidate,evidence,at),confidence=this.evaluateConfidence(evidence,freshness,cross);return this.patterns.store(new MarketPattern({id:candidate.id,version:1,type:candidate.type,direction,status:PatternStatus.Observed,description:candidate.description,businessPackageId:candidate.businessPackageId,evidence,confidence,window,freshness,stability:this.evaluateStability(window,evidence),decay:this.evaluateDecay(freshness,evidence),crossMarketValidation:cross,createdAt:at,evaluatedAt:at,provenance:(evidence.supporting[0]??evidence.neutral[0]??evidence.contradicting[0]).provenance}));}
 verifyEligible(id:PatternId,businessPackageId:PatternCandidate["businessPackageId"],at:Date):MarketPattern{const current=this.required(id,businessPackageId);if(current.window.independentObservationCount<2||current.evidence.independentEvidenceCount<2)throw new PatternIntelligenceException("Verification requires multiple independent observations","INSUFFICIENT_INDEPENDENCE");return this.reEvaluate(current,{status:PatternStatus.Verified},at);}
 attachContradictoryEvidence(id:PatternId,businessPackageId:PatternCandidate["businessPackageId"],evidence:Evidence,at:Date):MarketPattern{const current=this.required(id,businessPackageId),aggregate=new PatternEvidence(current.evidence.supporting,[...current.evidence.contradicting,evidence],current.evidence.neutral,current.evidence.independentEvidenceCount,current.evidence.sourceCount);return this.reEvaluate(current,{evidence:aggregate,direction:PatternDirection.Contradictory,status:PatternStatus.Weakening,stability:PatternStability.Unstable},at);}
 createBusinessMemoryCandidate(id:PatternId,businessPackageId:PatternCandidate["businessPackageId"],at:Date):MarketPattern{const current=this.required(id,businessPackageId);if(current.status!==PatternStatus.Verified||current.evidence.independentEvidenceCount<2||current.confidence.value<.6||current.freshness.status!==FreshnessStatus.Current)throw new PatternIntelligenceException("Pattern does not meet Business Memory candidacy criteria","INELIGIBLE_CANDIDACY");return this.reEvaluate(current,{status:PatternStatus.BusinessMemoryCandidate},at);}
 reEvaluate(current:MarketPattern,changes:Partial<Pick<MarketPattern,"direction"|"status"|"evidence"|"freshness"|"stability"|"decay"|"crossMarketValidation">>,at:Date):MarketPattern{const evidence=changes.evidence??current.evidence,freshness=changes.freshness??current.freshness,cross=changes.crossMarketValidation??current.crossMarketValidation;return this.patterns.store(new MarketPattern({id:current.id,version:current.version+1,type:current.type,direction:changes.direction??current.direction,status:changes.status??current.status,description:current.description,businessPackageId:current.businessPackageId,evidence,confidence:this.evaluateConfidence(evidence,freshness,cross),window:current.window,freshness,stability:changes.stability??this.evaluateStability(current.window,evidence),decay:changes.decay??this.evaluateDecay(freshness,evidence),crossMarketValidation:cross,createdAt:current.createdAt,evaluatedAt:at,provenance:current.provenance}));}
 retrieve(id:PatternId,businessPackageId:PatternCandidate["businessPackageId"]):MarketPattern|undefined{return this.patterns.current(id,businessPackageId);} query(filter:PatternQuery={}):readonly MarketPattern[]{return this.patterns.query(filter);} private required(id:PatternId,pkg:PatternCandidate["businessPackageId"]):MarketPattern{const found=this.patterns.current(id,pkg);if(!found)throw new PatternIntelligenceException("Pattern was not found","PATTERN_NOT_FOUND");return found;}
}
