import { CompetitiveAnalysis } from "../competitive/CompetitiveIntelligenceDomain.ts";
import { BusinessPackageId, Confidence, Evidence, Freshness, MarketObservation, Provenance } from "../../../intelligence/market/MarketIntelligenceDomain.ts";
import { PatternIntelligenceException } from "./PatternIntelligenceException.ts";

function required(value:string, field:string):string { if(typeof value!=="string"||value.trim()==="") throw new PatternIntelligenceException(`${field} must not be empty`,"INVALID_PATTERN"); return value; }
function instant(value:Date,field:string):number { const result=value instanceof Date?value.getTime():NaN; if(!Number.isFinite(result)) throw new PatternIntelligenceException(`${field} must be a valid date`,"INVALID_PATTERN"); return result; }
function frozen<T>(items:readonly T[]):readonly T[]{ return Object.freeze([...items]); }

export class PatternId { readonly #value:string; constructor(value:string){this.#value=required(value,"Pattern identifier");Object.freeze(this);} get value():string{return this.#value;} equals(other:PatternId):boolean{return other instanceof PatternId&&other.value===this.value;} toString():string{return this.value;} }
export enum PatternType { Search="Search",Content="Content",Visual="Visual",Audience="Audience",Engagement="Engagement",Publishing="Publishing",Seasonal="Seasonal",Behavioural="Behavioural",Conversion="Conversion",Competitive="Competitive" }
export enum PatternDirection { Positive="Positive",Negative="Negative",Neutral="Neutral",Contradictory="Contradictory" }
export enum PatternStatus { Candidate="Candidate",Observed="Observed",Verified="Verified",Weakening="Weakening",Deprecated="Deprecated",Archived="Archived",BusinessMemoryCandidate="BusinessMemoryCandidate" }
export enum PatternStability { Emerging="Emerging",Developing="Developing",Stable="Stable",Weakening="Weakening",Unstable="Unstable" }
export enum PatternDecay { None="None",Low="Low",Moderate="Moderate",High="High",Expired="Expired" }
export enum CrossMarketValidationResult { NotEvaluated="NotEvaluated",SingleContext="SingleContext",MultiContextSupported="MultiContextSupported",ConflictingContexts="ConflictingContexts",InsufficientEvidence="InsufficientEvidence" }
export enum PatternEvidenceRole { Supporting="Supporting",Contradicting="Contradicting",Neutral="Neutral" }

export class PatternCandidate {
 readonly evidence:readonly Evidence[]; readonly observations:readonly MarketObservation[]; readonly competitiveAnalyses:readonly CompetitiveAnalysis[]; readonly #first:number; readonly #latest:number;
 constructor(readonly id:PatternId,readonly type:PatternType,readonly description:string,readonly businessPackageId:BusinessPackageId,evidence:readonly Evidence[],observations:readonly MarketObservation[],competitiveAnalyses:readonly CompetitiveAnalysis[],firstObservedAt:Date,latestObservedAt:Date){
  required(description,"Pattern description"); if(evidence.length===0||observations.length===0)throw new PatternIntelligenceException("Candidate requires evidence and observations","MISSING_EVIDENCE"); this.#first=instant(firstObservedAt,"First observed timestamp");this.#latest=instant(latestObservedAt,"Latest observed timestamp");if(this.#latest<this.#first)throw new PatternIntelligenceException("Latest observation cannot precede first observation","INVALID_WINDOW");
  if(observations.some(o=>o.businessPackageId?.value!==businessPackageId.value)||competitiveAnalyses.some(a=>a.businessPackageId?.value!==businessPackageId.value))throw new PatternIntelligenceException("Candidate references must remain in one Business Package","PACKAGE_MISMATCH");
  const observationIds=new Set(observations.map(o=>o.id.value)); if(evidence.some(e=>!e.observationIds.some(id=>observationIds.has(id.value))))throw new PatternIntelligenceException("Candidate evidence must reference a candidate observation","UNLINKED_EVIDENCE");
  this.evidence=frozen(evidence);this.observations=frozen(observations);this.competitiveAnalyses=frozen(competitiveAnalyses);Object.freeze(this);
 } get firstObservedAt():Date{return new Date(this.#first);} get latestObservedAt():Date{return new Date(this.#latest);}
}
export class PatternWindow { readonly #start:number;readonly #end:number;constructor(start:Date,end:Date,readonly observationCount:number,readonly independentObservationCount:number){this.#start=instant(start,"Window start");this.#end=instant(end,"Window end");if(this.#end<this.#start||!Number.isInteger(observationCount)||!Number.isInteger(independentObservationCount)||observationCount<1||independentObservationCount<1||independentObservationCount>observationCount)throw new PatternIntelligenceException("Pattern observation window is invalid","INVALID_WINDOW");Object.freeze(this);}get start():Date{return new Date(this.#start);}get end():Date{return new Date(this.#end);} }
export class PatternEvidence {
 readonly supporting:readonly Evidence[];readonly contradicting:readonly Evidence[];readonly neutral:readonly Evidence[];readonly provenances:readonly Provenance[];
 constructor(supporting:readonly Evidence[],contradicting:readonly Evidence[],neutral:readonly Evidence[],readonly independentEvidenceCount:number,readonly sourceCount:number){this.supporting=frozen(supporting);this.contradicting=frozen(contradicting);this.neutral=frozen(neutral);const all=[...supporting,...contradicting,...neutral];if(!Number.isInteger(independentEvidenceCount)||independentEvidenceCount<0||independentEvidenceCount>all.length||!Number.isInteger(sourceCount)||sourceCount<0)throw new PatternIntelligenceException("Pattern evidence counts are invalid","INVALID_EVIDENCE");this.provenances=frozen(all.map(e=>e.provenance));Object.freeze(this);}get evidenceCount():number{return this.supporting.length+this.contradicting.length+this.neutral.length;}
}
export interface ConfidenceFactor { readonly name:string;readonly contribution:number;readonly explanation:string; }
export class PatternConfidence { readonly factors:readonly ConfidenceFactor[];constructor(readonly confidence:Confidence,factors:readonly ConfidenceFactor[]){this.factors=Object.freeze(factors.map(f=>Object.freeze({...f})));Object.freeze(this);}get value():number{return this.confidence.value;} }
export class CrossMarketValidation { readonly contexts:readonly string[];readonly independentSourceGroups:readonly string[];readonly supportingEvidence:readonly Evidence[];readonly #at:number;constructor(contexts:readonly string[],sourceGroups:readonly string[],evidence:readonly Evidence[],readonly confidence:Confidence,validatedAt:Date,readonly result:CrossMarketValidationResult){this.contexts=frozen(contexts);this.independentSourceGroups=frozen(sourceGroups);this.supportingEvidence=frozen(evidence);this.#at=instant(validatedAt,"Validation timestamp");Object.freeze(this);}get validatedAt():Date{return new Date(this.#at);} }
export interface MarketPatternProperties { id:PatternId;version:number;type:PatternType;direction:PatternDirection;status:PatternStatus;description:string;businessPackageId:BusinessPackageId;evidence:PatternEvidence;confidence:PatternConfidence;window:PatternWindow;freshness:Freshness;stability:PatternStability;decay:PatternDecay;crossMarketValidation:CrossMarketValidation;createdAt:Date;evaluatedAt:Date;provenance:Provenance; }
export class MarketPattern { readonly #created:number;readonly #evaluated:number;readonly id;readonly version;readonly type;readonly direction;readonly status;readonly description;readonly businessPackageId;readonly evidence;readonly confidence;readonly window;readonly freshness;readonly stability;readonly decay;readonly crossMarketValidation;readonly provenance;constructor(p:MarketPatternProperties){if(!Number.isInteger(p.version)||p.version<1)throw new PatternIntelligenceException("Pattern version must be positive","INVALID_VERSION");required(p.description,"Pattern description");this.#created=instant(p.createdAt,"Creation timestamp");this.#evaluated=instant(p.evaluatedAt,"Evaluation timestamp");if(this.#evaluated<this.#created)throw new PatternIntelligenceException("Evaluation cannot precede creation","INVALID_PATTERN");this.id=p.id;this.version=p.version;this.type=p.type;this.direction=p.direction;this.status=p.status;this.description=p.description;this.businessPackageId=p.businessPackageId;this.evidence=p.evidence;this.confidence=p.confidence;this.window=p.window;this.freshness=p.freshness;this.stability=p.stability;this.decay=p.decay;this.crossMarketValidation=p.crossMarketValidation;this.provenance=p.provenance;Object.freeze(this);}get createdAt():Date{return new Date(this.#created);}get evaluatedAt():Date{return new Date(this.#evaluated);} }
