import {AuditEvent} from "../../core/platform/AuditEvent.ts";
import {AuditEventType} from "../../core/platform/AuditEventType.ts";
import type {AuditRecorder} from "../../core/platform/AuditRecorder.ts";
import {Event} from "../../core/platform/Event.ts";
import type {EventBus} from "../../core/platform/EventBus.ts";
import {EventContext} from "../../core/platform/EventContext.ts";
import {EventId} from "../../core/platform/EventId.ts";
import type {EventListener} from "../../core/platform/EventListener.ts";
import {EventType} from "../../core/platform/EventType.ts";
import type {SystemEvent} from "../../core/platform/SystemEvent.ts";
import {BusinessPackageId} from "../../intelligence/market/MarketIntelligenceDomain.ts";
import {PinterestContentIntent,PinterestDestinationContext,PinterestDestinationType} from "./PinterestCreationPlanningDomain.ts";

const required=(value:string,name:string)=>{if(!value?.trim())throw new BlogPinterestPromotionException(`${name} is required`);return value;};
const frozen=<T>(items:readonly T[])=>Object.freeze([...items]);
const normalized=(value:string)=>value.toLocaleLowerCase().normalize("NFKD").replace(/[^\p{L}\p{N}\s]/gu," ").replace(/\s+/g," ").trim();
const generic=/^(inhalt|einleitung|fazit|zusammenfassung|referenzen|quellen|rechtliches|disclaimer|weiterlesen|mehr erfahren|jetzt kaufen|introduction|contents|conclusion|references|sources|legal)$/i;

export class BlogPinterestPromotionException extends Error{constructor(message:string,readonly code="BLOG_PINTEREST_PROMOTION_FAILURE"){super(message);this.name="BlogPinterestPromotionException";}}
export class BlogPinterestPromotionId{constructor(readonly value:string){required(value,"Promotion identifier");Object.freeze(this);}}
export enum BlogPinterestPromotionState{Requested="Requested",CandidateExtraction="CandidateExtraction",CandidateEvaluation="CandidateEvaluation",DiversityValidation="DiversityValidation",ReadyForPinterestPlanning="ReadyForPinterestPlanning",PartiallyReady="PartiallyReady",CreativeDiversityInsufficient="CreativeDiversityInsufficient",Disabled="Disabled",Held="Held",Completed="Completed",Failed="Failed"}
export enum BlogPinterestCandidateSourceType{H1="H1",H2="H2",H3="H3",RelatedQuestion="RelatedQuestion",PublishedArticleInsight="PublishedArticleInsight",OtherApprovedSource="OtherApprovedSource"}
export type BlogHeadingLevel="H1"|"H2"|"H3";
export interface PublishedBlogPromotionSource{publishedBlogReference:string;actualCanonicalUrl:string;businessPackageId:BusinessPackageId;language:string;market:string;h1:string;headings:readonly {headingId:string;level:BlogHeadingLevel;text:string;sectionReference:string;evidenceReferences:readonly string[]}[];draftId:string;draftVersion:number;publicationPackageId:string;publicationPackageVersion:number;recommendationId:string;recommendationVersion:number;opportunityReferences:readonly string[];canonicalQuestionId:string;publishedAt:Date;relatedQuestions?:readonly {id:string;text:string;answeredInArticle:boolean;sectionReference:string;evidenceReferences:readonly string[]}[];articleInsights?:readonly {id:string;text:string;groundedInArticle:boolean;sectionReference:string;evidenceReferences:readonly string[]}[];}
export class BlogPinterestPromotionRequest{constructor(readonly promotionId:BlogPinterestPromotionId,readonly source:PublishedBlogPromotionSource,readonly configuredMinimumPins:number,readonly correlationIdentifier:string,readonly workflowReference:string,readonly requestedAt:Date){if(!Number.isInteger(configuredMinimumPins)||configuredMinimumPins<1)throw new BlogPinterestPromotionException("Configured minimum Pins must be positive","INVALID_CONFIGURATION");required(source.actualCanonicalUrl,"Actual Blog URL");required(correlationIdentifier,"Correlation identifier");Object.freeze(this);}}
export class BlogPinterestHeadingCandidate{readonly evidenceReferences;constructor(readonly candidateId:string,readonly sourceType:BlogPinterestCandidateSourceType,readonly headingId:string,readonly headingLevel:BlogHeadingLevel|undefined,readonly headingText:string,readonly sectionReference:string,evidenceReferences:readonly string[],readonly eligible:boolean,readonly eligibilityExplanation:string){required(headingId,"Heading/source identifier");required(headingText,"Heading/source text");this.evidenceReferences=frozen(evidenceReferences);Object.freeze(this);}}
export class BlogPinterestPromotionCandidateScore{readonly factors;constructor(readonly value:number,factors:readonly string[]){this.factors=frozen(factors);Object.freeze(this);}}
export type PinterestCreativeType="StaticPin"|"VideoPin";
export class BlogPinterestPromotionCandidate{constructor(readonly heading:BlogPinterestHeadingCandidate,readonly score:BlogPinterestPromotionCandidateScore,readonly destination:PinterestDestinationContext,readonly creativeType:PinterestCreativeType="StaticPin"){Object.freeze(this);}}
export class BlogPinterestCreativeDiversityAssessment{readonly explanations;readonly rejectedCandidateIds;constructor(readonly sufficient:boolean,explanations:readonly string[],rejectedCandidateIds:readonly string[]){this.explanations=frozen(explanations);this.rejectedCandidateIds=frozen(rejectedCandidateIds);Object.freeze(this);}}
export class BlogPinterestPromotionAuthorization{readonly allowedCandidateIds;constructor(readonly authorityReference:string,readonly publishedBlogReference:string,readonly destinationUrl:string,readonly businessPackageId:BusinessPackageId,readonly configuredPromotionCount:number,allowedCandidateIds:readonly string[],readonly channel="Pinterest"){required(authorityReference,"Promotion authority");this.allowedCandidateIds=frozen(allowedCandidateIds);Object.freeze(this);}}
export interface BlogPinterestCreationPlanDemand{promotionId:BlogPinterestPromotionId;candidate:BlogPinterestPromotionCandidate;authorization:BlogPinterestPromotionAuthorization;businessPackageId:BusinessPackageId;language:string;market:string;publishedBlogReference:string;draftId:string;draftVersion:number;publicationPackageId:string;publicationPackageVersion:number;recommendationId:string;recommendationVersion:number;opportunityReferences:readonly string[];canonicalQuestionId:string;contentIntent:PinterestContentIntent;destination:PinterestDestinationContext;pipeline:readonly ["PinterestCreationPlan","PinterestCopyProduction","PinterestVisualProduction","PinterestCreativeAssembly","PinterestPrePublishValidation","PinterestQueue","PinterestTimingIntelligence","PinterestScheduler","PinterestPublisher","PinterestPerformanceLearning"];}
export interface BlogPinterestCreationPlanHandoff{request(demand:BlogPinterestCreationPlanDemand):"Accepted"|"WaitingForQueueCapacity"|"RequiresApproval";}
export class BlogPinterestPromotionPlan{readonly selected;readonly remainingCandidates;constructor(selected:readonly BlogPinterestPromotionCandidate[],remaining:readonly BlogPinterestPromotionCandidate[],readonly diversity:BlogPinterestCreativeDiversityAssessment){this.selected=frozen(selected);this.remainingCandidates=frozen(remaining);Object.freeze(this);}}
export class BlogPinterestPromotionResult{readonly planningStatuses;constructor(readonly request:BlogPinterestPromotionRequest,readonly state:BlogPinterestPromotionState,readonly plan:BlogPinterestPromotionPlan|undefined,planningStatuses:readonly string[]){this.planningStatuses=frozen(planningStatuses);Object.freeze(this);}}
export class BlogPinterestPromotionSummary{constructor(readonly publishedBlogReference:string,readonly blogUrl:string,readonly state:BlogPinterestPromotionState,readonly configuredMinimumPins:number,readonly candidatesFound:number,readonly selected:number,readonly produced:number,readonly queued:number,readonly published:number){Object.freeze(this);}}

export interface BlogPinterestPromotionPolicy{businessPackageId:BusinessPackageId;channel:"Pinterest";enabled:boolean;minimumPinsPerPublishedBlog:number;initialPinsPerPublishedBlog?:number;authorityReference:string;heldPublishedBlogReferences:readonly string[];}
export class BlogPinterestPromotionPolicyRepository{readonly #policies=new Map<string,BlogPinterestPromotionPolicy>();readonly #changes:{packageId:string;minimum:number;authority:string;changedAt:Date}[]=[];constructor(alivoAuthorityReference="ceo:implementation-056"){this.#policies.set("ALIVO:Pinterest",Object.freeze({businessPackageId:new BusinessPackageId("ALIVO"),channel:"Pinterest",enabled:true,minimumPinsPerPublishedBlog:3,authorityReference:alivoAuthorityReference,heldPublishedBlogReferences:Object.freeze([])}));}get(id:BusinessPackageId){return this.#policies.get(`${id.value}:Pinterest`);}set(policy:BlogPinterestPromotionPolicy,actor:{role:string;authorityReference:string},at=new Date()){if(actor.role!=="CEO"||!actor.authorityReference.trim())throw new BlogPinterestPromotionException("CEO authority is required to change promotion configuration","CEO_AUTHORITY_REQUIRED");if(!Number.isInteger(policy.minimumPinsPerPublishedBlog)||policy.minimumPinsPerPublishedBlog<1)throw new BlogPinterestPromotionException("Minimum Pins configuration is invalid","INVALID_CONFIGURATION");this.#policies.set(`${policy.businessPackageId.value}:Pinterest`,Object.freeze({...policy,heldPublishedBlogReferences:frozen(policy.heldPublishedBlogReferences)}));this.#changes.push({packageId:policy.businessPackageId.value,minimum:policy.minimumPinsPerPublishedBlog,authority:actor.authorityReference,changedAt:new Date(at)});}changes(){return frozen(this.#changes);}}
export class BlogPinterestPromotionRepository{readonly #results=new Map<string,BlogPinterestPromotionResult>();get(id:BlogPinterestPromotionId){return this.#results.get(id.value);}save(result:BlogPinterestPromotionResult){this.#results.set(result.request.promotionId.value,result);return result;}all(){return frozen([...this.#results.values()]);}}

export class BlogPinterestPromotionService{
 #sequence=0;constructor(private readonly policies:BlogPinterestPromotionPolicyRepository,private readonly handoff:BlogPinterestCreationPlanHandoff,readonly repository=new BlogPinterestPromotionRepository(),private readonly events?:EventBus,private readonly audit?:AuditRecorder,private readonly clock=()=>new Date()){}
 promote(source:PublishedBlogPromotionSource,correlationIdentifier:string,workflowReference="BlogPublished"){const id=new BlogPinterestPromotionId(`blog-pinterest:${source.publishedBlogReference}:v${source.publicationPackageVersion}`),prior=this.repository.get(id);if(prior)return prior;const policy=this.policies.get(source.businessPackageId);if(!policy||!policy.enabled)return this.finish(new BlogPinterestPromotionRequest(id,source,policy?.minimumPinsPerPublishedBlog??1,correlationIdentifier,workflowReference,this.clock()),BlogPinterestPromotionState.Disabled,undefined,[]);const request=new BlogPinterestPromotionRequest(id,source,policy.minimumPinsPerPublishedBlog,correlationIdentifier,workflowReference,this.clock());this.report("BlogPinterestPromotionRequested",request);if(policy.heldPublishedBlogReferences.includes(source.publishedBlogReference))return this.finish(request,BlogPinterestPromotionState.Held,undefined,[]);
  this.report("BlogPinterestCandidateExtractionStarted",request);const extracted=this.extract(source);for(const candidate of extracted)this.report("BlogPinterestHeadingCandidateCreated",request,{candidateId:candidate.candidateId,sourceType:candidate.sourceType,eligible:String(candidate.eligible)});const ranked=extracted.filter(x=>x.eligible).map(x=>new BlogPinterestPromotionCandidate(x,this.score(x),new PinterestDestinationContext(PinterestDestinationType.ExistingArticle,source.publishedBlogReference,source.actualCanonicalUrl))).sort((a,b)=>b.score.value-a.score.value);const {selected,rejected,explanations}=this.diverse(ranked,policy.initialPinsPerPublishedBlog??policy.minimumPinsPerPublishedBlog);const diversity=new BlogPinterestCreativeDiversityAssessment(selected.length>=policy.minimumPinsPerPublishedBlog,explanations,rejected);const plan=new BlogPinterestPromotionPlan(selected,ranked.filter(x=>!selected.includes(x)&&!rejected.includes(x.heading.candidateId)),diversity);if(!diversity.sufficient)this.report("BlogPinterestCreativeDiversityInsufficient",request,{selected:String(selected.length),minimum:String(policy.minimumPinsPerPublishedBlog)});if(!selected.length)return this.finish(request,BlogPinterestPromotionState.CreativeDiversityInsufficient,plan,[]);
  const authorization=new BlogPinterestPromotionAuthorization(policy.authorityReference,source.publishedBlogReference,source.actualCanonicalUrl,source.businessPackageId,selected.length,selected.map(x=>x.heading.candidateId));const statuses=selected.map(candidate=>{this.report("BlogPinterestCandidateSelected",request,{candidateId:candidate.heading.candidateId});this.report("BlogPinterestPromotionPlanningRequested",request,{candidateId:candidate.heading.candidateId});return this.handoff.request({promotionId:id,candidate,authorization,businessPackageId:source.businessPackageId,language:source.language,market:source.market,publishedBlogReference:source.publishedBlogReference,draftId:source.draftId,draftVersion:source.draftVersion,publicationPackageId:source.publicationPackageId,publicationPackageVersion:source.publicationPackageVersion,recommendationId:source.recommendationId,recommendationVersion:source.recommendationVersion,opportunityReferences:source.opportunityReferences,canonicalQuestionId:source.canonicalQuestionId,contentIntent:PinterestContentIntent.ArticleDiscovery,destination:candidate.destination,pipeline:["PinterestCreationPlan","PinterestCopyProduction","PinterestVisualProduction","PinterestCreativeAssembly","PinterestPrePublishValidation","PinterestQueue","PinterestTimingIntelligence","PinterestScheduler","PinterestPublisher","PinterestPerformanceLearning"]});});const partial=!diversity.sufficient||statuses.some(x=>x!=="Accepted");return this.finish(request,partial?BlogPinterestPromotionState.PartiallyReady:BlogPinterestPromotionState.ReadyForPinterestPlanning,plan,statuses);
 }
 summary(id:BlogPinterestPromotionId){const result=this.repository.get(id);if(!result)return undefined;return new BlogPinterestPromotionSummary(result.request.source.publishedBlogReference,result.request.source.actualCanonicalUrl,result.state,result.request.configuredMinimumPins,result.plan?.selected.length??0+(result.plan?.remainingCandidates.length??0),result.plan?.selected.length??0,result.planningStatuses.filter(x=>x==="Accepted").length,result.planningStatuses.filter(x=>x==="WaitingForQueueCapacity").length,0);}
 private extract(source:PublishedBlogPromotionSource){const headings=source.headings.map((h,index)=>{const isH1=h.level==="H1",eligible=isH1||(!generic.test(h.text.trim())&&normalized(h.text).split(" ").length>=3);return new BlogPinterestHeadingCandidate(`heading:${h.headingId}`,BlogPinterestCandidateSourceType[h.level],h.headingId,h.level,h.text,h.sectionReference,h.evidenceReferences,eligible,isH1?"Canonical H1 is the mandatory direct article angle":eligible?"Heading is a meaningful article discovery angle":"Heading is navigational, generic, or insufficiently informative");});const fallback=[...(source.relatedQuestions??[]).filter(x=>x.answeredInArticle).map(x=>new BlogPinterestHeadingCandidate(`related:${x.id}`,BlogPinterestCandidateSourceType.RelatedQuestion,x.id,undefined,x.text,x.sectionReference,x.evidenceReferences,true,"Approved related question is answered by the published article")),...(source.articleInsights??[]).filter(x=>x.groundedInArticle).map(x=>new BlogPinterestHeadingCandidate(`insight:${x.id}`,BlogPinterestCandidateSourceType.PublishedArticleInsight,x.id,undefined,x.text,x.sectionReference,x.evidenceReferences,true,"Insight is grounded in published article evidence"))];return frozen([...headings,...fallback]);}
 private score(candidate:BlogPinterestHeadingCandidate){const question=/\?|^(warum|wie|was|welche|wann|why|how|what|which)\b/i.test(candidate.headingText),level=candidate.headingLevel==="H1"?100:candidate.headingLevel==="H2"?70:candidate.headingLevel==="H3"?75:55;return new BlogPinterestPromotionCandidateScore(level+(question?15:0)+Math.min(candidate.evidenceReferences.length,5),[candidate.headingLevel==="H1"?"mandatory canonical-question priority":"useful article subfocus",question?"distinct question intent":"explanatory discovery intent",candidate.evidenceReferences.length?"published evidence relationship preserved":"published section relationship preserved"]);}
 private diverse(ranked:readonly BlogPinterestPromotionCandidate[],target:number){const selected:BlogPinterestPromotionCandidate[]=[],rejected:string[]=[],explanations:string[]=[];for(const candidate of ranked){const words=new Set(normalized(candidate.heading.headingText).split(" ").filter(x=>x.length>3));const near=selected.find(other=>{const otherWords=new Set(normalized(other.heading.headingText).split(" ").filter(x=>x.length>3)),intersection=[...words].filter(x=>otherWords.has(x)).length,union=new Set([...words,...otherWords]).size;return normalized(candidate.heading.headingText)===normalized(other.heading.headingText)||(union>0&&intersection/union>=.72);});if(near){rejected.push(candidate.heading.candidateId);explanations.push(`${candidate.heading.candidateId} rejected as near-duplicate of ${near.heading.candidateId}`);}else{selected.push(candidate);explanations.push(`${candidate.heading.candidateId} is distinct by source context, intent, and topic subfocus`);if(selected.length===target)break;}}return {selected,rejected,explanations};}
 private finish(request:BlogPinterestPromotionRequest,state:BlogPinterestPromotionState,plan:BlogPinterestPromotionPlan|undefined,statuses:readonly string[]){const result=this.repository.save(new BlogPinterestPromotionResult(request,state,plan,statuses));this.report(state===BlogPinterestPromotionState.Disabled?"BlogPinterestPromotionDisabled":state===BlogPinterestPromotionState.Held?"BlogPinterestPromotionHeld":state===BlogPinterestPromotionState.PartiallyReady?"BlogPinterestPromotionPartiallyReady":state===BlogPinterestPromotionState.ReadyForPinterestPlanning?"BlogPinterestPromotionReady":"BlogPinterestPromotionFailed",request);return result;}
 private report(name:string,request:BlogPinterestPromotionRequest,extra:Record<string,string>={}){const at=this.clock(),context={promotionId:request.promotionId.value,publishedBlogReference:request.source.publishedBlogReference,businessPackageId:request.source.businessPackageId.value,blogUrl:request.source.actualCanonicalUrl,...extra};this.events?.publish(new Event({id:new EventId(`blog-pinterest:${++this.#sequence}`),type:new EventType(name),timestamp:at,source:"BlogPinterestPromotionService",correlationId:request.correlationIdentifier,context:new EventContext(context)}));this.audit?.append(new AuditEvent({id:`blog-pinterest-audit:${++this.#sequence}`,timestamp:at,type:AuditEventType.WorkflowEvent,source:"BlogPinterestPromotionService",action:name,result:"Recorded",responsibleIdentity:"TCO",relatedTaskOrWorkflowId:request.workflowReference,context}));}
}

/** Event-system adapter. Non-BlogPublished states never resolve or create demand. */
export class BlogPublishedPinterestPromotionListener implements EventListener{constructor(private readonly resolve:(event:SystemEvent)=>PublishedBlogPromotionSource|undefined,private readonly service:BlogPinterestPromotionService){}handle(event:SystemEvent){if(event.name!=="BlogPublished")return;const source=this.resolve(event);if(source)this.service.promote(source,event.correlationId,event.id.value);}}
