import { BusinessPackageId, Freshness } from "../../intelligence/market/MarketIntelligenceDomain.ts";
import type { MarketObservation, Provenance } from "../../intelligence/market/MarketIntelligenceDomain.ts";
import type { MarketCollectionResult, MarketSourceCapability, MarketSourceRateLimit } from "../../intelligence/market/integration/MarketSourceIntegrationDomain.ts";
import type { MarketDataValidationResult } from "../../intelligence/market/quality/MarketDataQualityDomain.ts";
import { MarketSourceAdapterId } from "../../intelligence/market/integration/MarketSourceIntegrationDomain.ts";
import { CredentialId } from "../../security/credentials/CredentialVault.ts";

export class PinterestObservationWorkflowException extends Error { constructor(message:string,readonly code="PINTEREST_OBSERVATION_WORKFLOW_FAILURE"){super(message);this.name="PinterestObservationWorkflowException";} }
const required=(value:string,name:string)=>{if(typeof value!=="string"||!value.trim())throw new PinterestObservationWorkflowException(`${name} is required`);return value;};
const validDate=(value:Date,name:string)=>{if(!(value instanceof Date)||!Number.isFinite(value.getTime()))throw new PinterestObservationWorkflowException(`${name} is invalid`);return new Date(value);};

export class PinterestObservationWorkflowId { constructor(readonly value:string){required(value,"Workflow identifier");Object.freeze(this);} }
export enum PinterestObservationCollectionScope { OwnedPins="OwnedPins",OwnedBoards="OwnedBoards",OwnedAnalytics="OwnedAnalytics",TopPins="TopPins",PublicPins="PublicPins",PublicBoards="PublicBoards",Trends="Trends",OtherReadOnly="OtherReadOnly" }
export enum PinterestObservationWorkflowState { Requested="Requested",ValidatingConfiguration="ValidatingConfiguration",VerifyingCapability="VerifyingCapability",AuthenticationRequired="AuthenticationRequired",Ready="Ready",Collecting="Collecting",PartiallyCollected="PartiallyCollected",Normalizing="Normalizing",ValidatingData="ValidatingData",RegisteringObservations="RegisteringObservations",WaitingForCredentialCorrection="WaitingForCredentialCorrection",WaitingForReauthorization="WaitingForReauthorization",RateLimited="RateLimited",Paused="Paused",Completed="Completed",CompletedWithWarnings="CompletedWithWarnings",NoData="NoData",Failed="Failed",Cancelled="Cancelled" }

export interface PinterestObservationWorkflowRequestProperties { id:PinterestObservationWorkflowId;businessPackageId:BusinessPackageId;adapterId:MarketSourceAdapterId;credentialId:CredentialId;capability:MarketSourceCapability;scope:PinterestObservationCollectionScope;queryOrSubjectReference?:string;marketContext?:string;languageContext?:string;windowStart?:Date;windowEnd?:Date;freshness?:Freshness;maximumPages?:number;maximumRecords?:number;correlationIdentifier:string;requestingAuthorityReference:string;requestedAt:Date;manual?:boolean; }
export class PinterestObservationWorkflowRequest {
  readonly requestedAt:Date;readonly windowStart?:Date;readonly windowEnd?:Date;
  constructor(readonly properties:PinterestObservationWorkflowRequestProperties){if(!(properties.id instanceof PinterestObservationWorkflowId)||!(properties.businessPackageId instanceof BusinessPackageId)||!(properties.adapterId instanceof MarketSourceAdapterId)||!(properties.credentialId instanceof CredentialId)||!Object.values(PinterestObservationCollectionScope).includes(properties.scope))throw new PinterestObservationWorkflowException("Workflow request references are invalid");required(properties.capability?.value,"Requested capability");required(properties.correlationIdentifier,"Correlation identifier");required(properties.requestingAuthorityReference,"Requesting authority");this.requestedAt=validDate(properties.requestedAt,"Request timestamp");this.windowStart=properties.windowStart&&validDate(properties.windowStart,"Window start");this.windowEnd=properties.windowEnd&&validDate(properties.windowEnd,"Window end");if(this.windowStart&&this.windowEnd&&this.windowStart>this.windowEnd)throw new PinterestObservationWorkflowException("Collection window is invalid");for(const [value,name] of [[properties.maximumPages,"Maximum pages"],[properties.maximumRecords,"Maximum records"]] as const)if(value!==undefined&&(!Number.isInteger(value)||value<1))throw new PinterestObservationWorkflowException(`${name} must be a positive finite integer`);Object.freeze(this);}
  get id(){return this.properties.id;}
}

export interface PinterestObservationCollectionSummaryProperties { requestedPages:number;requestedItems:number;rawRecordsCollected:number;normalizedRecords:number;acceptedObservations:number;acceptedWithWarningObservations:number;quarantinedObservations:number;rejectedObservations:number;historicalOnlyObservations:number;duplicatesDetected:number;noDataResults:number;providerFailures:number;normalizationFailures:number;validationFailures:number; }
export class PinterestObservationCollectionSummary { constructor(readonly properties:PinterestObservationCollectionSummaryProperties){if(Object.values(properties).some(x=>!Number.isInteger(x)||x<0))throw new PinterestObservationWorkflowException("Collection summary counts must be non-negative integers");Object.freeze(properties);Object.freeze(this);} }
export interface PinterestObservationDisposition { readonly observation?:MarketObservation;readonly validation?:MarketDataValidationResult;readonly reason:string; }
export interface PinterestObservationWorkflowResultProperties { workflowId:PinterestObservationWorkflowId;businessPackageId:BusinessPackageId;sourceReference:string;capability:MarketSourceCapability;scope:PinterestObservationCollectionScope;finalState:PinterestObservationWorkflowState;summary:PinterestObservationCollectionSummary;collectionResults:readonly MarketCollectionResult[];acceptedObservations:readonly MarketObservation[];quarantined:readonly PinterestObservationDisposition[];rejected:readonly PinterestObservationDisposition[];historicalOnly:readonly PinterestObservationDisposition[];warnings:readonly string[];failures:readonly string[];rateLimit?:MarketSourceRateLimit;startedAt:Date;completedAt:Date;correlationIdentifier:string;provenance:Provenance; }
export class PinterestObservationWorkflowResult {
  readonly collectionResults:readonly MarketCollectionResult[];readonly acceptedObservations:readonly MarketObservation[];readonly quarantined:readonly PinterestObservationDisposition[];readonly rejected:readonly PinterestObservationDisposition[];readonly historicalOnly:readonly PinterestObservationDisposition[];readonly warnings:readonly string[];readonly failures:readonly string[];readonly startedAt:Date;readonly completedAt:Date;
  constructor(readonly properties:PinterestObservationWorkflowResultProperties){required(properties.sourceReference,"Source reference");required(properties.correlationIdentifier,"Correlation identifier");this.collectionResults=Object.freeze([...properties.collectionResults]);this.acceptedObservations=Object.freeze([...properties.acceptedObservations]);this.quarantined=Object.freeze(properties.quarantined.map(x=>Object.freeze({...x})));this.rejected=Object.freeze(properties.rejected.map(x=>Object.freeze({...x})));this.historicalOnly=Object.freeze(properties.historicalOnly.map(x=>Object.freeze({...x})));this.warnings=Object.freeze([...properties.warnings]);this.failures=Object.freeze([...properties.failures]);this.startedAt=validDate(properties.startedAt,"Start timestamp");this.completedAt=validDate(properties.completedAt,"Completion timestamp");Object.freeze(this);}
  get finalState(){return this.properties.finalState;}get summary(){return this.properties.summary;}get workflowId(){return this.properties.workflowId;}
}
