import { AuditEvent } from "../../core/platform/AuditEvent.ts";import { AuditEventType } from "../../core/platform/AuditEventType.ts";import type { AuditRecorder } from "../../core/platform/AuditRecorder.ts";import { Event } from "../../core/platform/Event.ts";import type { EventBus } from "../../core/platform/EventBus.ts";import { EventContext } from "../../core/platform/EventContext.ts";import { EventId } from "../../core/platform/EventId.ts";import { EventType } from "../../core/platform/EventType.ts";
import { OpportunityCandidate,OpportunityEffort,OpportunityId,OpportunityScope,OpportunityStatus } from "../../business/market/opportunities/OpportunityIntelligenceDomain.ts";import type { OpportunityIntelligenceService } from "../../business/market/opportunities/OpportunityIntelligenceService.ts";import { PatternDecay,PatternDirection,PatternStatus } from "../../business/market/patterns/PatternIntelligenceDomain.ts";import { Confidence,FreshnessStatus } from "../../intelligence/market/MarketIntelligenceDomain.ts";
import { PinterestAssetFit,PinterestBusinessRelevance,PinterestEvidenceGap,PinterestOpportunityCandidateInput,PinterestOpportunityEvaluationException,PinterestOpportunityEvaluationRequest,PinterestOpportunityEvaluationResult,PinterestOpportunityEvaluationState,PinterestOpportunityEvaluationSummary,PinterestOpportunityEvidenceSet,PinterestOpportunityRejectionReason } from "./PinterestOpportunityEvaluationDomain.ts";import { PinterestOpportunityEvaluationRepository } from "./PinterestOpportunityEvaluationRepository.ts";

/** TCO-invoked intelligence boundary. It has no recommendation, generation, network, scheduling, or publishing dependency. */
export class PinterestOpportunityEvaluationWorkflow {
 #sequence=0;
 constructor(private readonly intelligence:OpportunityIntelligenceService,readonly repository=new PinterestOpportunityEvaluationRepository(),private readonly events?:EventBus,private readonly audit?:AuditRecorder,private readonly clock=()=>new Date()){}
 evaluate(request:PinterestOpportunityEvaluationRequest,unordered:readonly PinterestOpportunityCandidateInput[]):PinterestOpportunityEvaluationResult{
  if(this.repository.result(request.id))throw new PinterestOpportunityEvaluationException("Evaluation already completed","IMMUTABLE_EVALUATION_RESULT");const started=this.clock();this.transition(request,PinterestOpportunityEvaluationState.Requested,"PinterestOpportunityEvaluationRequested");this.transition(request,PinterestOpportunityEvaluationState.Started,"PinterestOpportunityEvaluationStarted");
  try {const inputs=[...unordered].sort((a,b)=>a.pattern.id.value.localeCompare(b.pattern.id.value));if(inputs.some(x=>x.pattern.businessPackageId.value!==request.properties.businessPackageId.value))throw new PinterestOpportunityEvaluationException("Patterns cross Business Package boundary","PACKAGE_MISMATCH");
   const opportunities=[];const sets:PinterestOpportunityEvidenceSet[]=[];const statuses:string[]=[];const relevanceStates=[];const assetStates=[];const gaps:PinterestEvidenceGap[]=[];const warnings:string[]=[];const rejections:PinterestOpportunityRejectionReason[]=[];let eligible=0,created=0,qualified=0,emerging=0,weak=0,stale=0,contradicted=0,assetGaps=0;
   for(const input of inputs){const pattern=input.pattern,ref=pattern.id.value;relevanceStates.push(input.properties.businessRelevance);assetStates.push(input.properties.assetFit);if(input.properties.assetFit===PinterestAssetFit.RelevantAssetMissing)assetGaps++;const explicitGaps=[...input.evidenceGaps];if(!input.performanceContextEvidence.length&&!explicitGaps.includes(PinterestEvidenceGap.UnknownPerformance))explicitGaps.push(PinterestEvidenceGap.UnknownPerformance);if(input.properties.assetFit===PinterestAssetFit.Unknown&&!explicitGaps.includes(PinterestEvidenceGap.UnknownAssetFit))explicitGaps.push(PinterestEvidenceGap.UnknownAssetFit);if(pattern.crossMarketValidation.contexts.length<2&&!explicitGaps.includes(PinterestEvidenceGap.UnknownCrossMarketValidity))explicitGaps.push(PinterestEvidenceGap.UnknownCrossMarketValidity);gaps.push(...explicitGaps);
    const support=[...pattern.evidence.supporting,...pattern.evidence.neutral,...input.relevanceEvidence,...input.assetContextEvidence,...input.performanceContextEvidence,...input.competitiveGaps.flatMap(g=>g.evidence),...input.saturationEvidence],conflict=[...pattern.evidence.contradicting];sets.push(new PinterestOpportunityEvidenceSet([ref],input.competitiveGaps.map((_,i)=>`${ref}:gap:${i}`),support,conflict,input.relevanceEvidence,input.assetContextEvidence,input.performanceContextEvidence,pattern.evidence.independentEvidenceCount,new Confidence(pattern.confidence.value),pattern.freshness,pattern.crossMarketValidation.contexts,[pattern.provenance,...support.map(e=>e.provenance),...conflict.map(e=>e.provenance)]));
    let rejection:PinterestOpportunityRejectionReason|undefined;if(!request.patternReferences.includes(ref))rejection=PinterestOpportunityRejectionReason.UnsupportedContext;else if(pattern.status!==PatternStatus.Verified)rejection=PinterestOpportunityRejectionReason.PatternTooWeak;else if(pattern.direction===PatternDirection.Contradictory||pattern.decay===PatternDecay.High){rejection=PinterestOpportunityRejectionReason.PatternContradicted;contradicted++;}else if(pattern.decay===PatternDecay.Expired||pattern.freshness.status===FreshnessStatus.Expired){rejection=PinterestOpportunityRejectionReason.EvidenceTooStale;stale++;}else if(input.properties.businessRelevance===PinterestBusinessRelevance.Irrelevant||input.properties.businessRelevance===PinterestBusinessRelevance.Unknown||input.relevanceEvidence.length===0)rejection=PinterestOpportunityRejectionReason.InsufficientBusinessRelevance;else if(pattern.evidence.independentEvidenceCount<2||support.length<2)rejection=PinterestOpportunityRejectionReason.InsufficientEvidence;
    if(rejection){rejections.push(rejection);statuses.push(OpportunityStatus.Rejected);warnings.push(`${ref}: ${rejection}`);this.report("PinterestOpportunityRejected",request,{patternReference:ref,reason:rejection});continue;}eligible++;
    const candidate=new OpportunityCandidate({id:new OpportunityId(`pinterest-opportunity:${request.properties.businessPackageId.value}:${request.id.value}:${ref}`),type:input.properties.opportunityType,title:`Opportunity supported by ${ref}`,description:"Evidence-supported Business Package opportunity candidate",businessPackageId:request.properties.businessPackageId,scope:new OpportunityScope(request.properties.businessPackageId,{market:request.properties.marketContext,language:request.properties.languageContext,geographicContext:request.properties.regionContext}),supportingEvidence:support,contradictingEvidence:conflict,competitiveGaps:input.competitiveGaps,patterns:[pattern],firstDetectedAt:pattern.window.start,latestEvidenceAt:pattern.window.end,provenance:pattern.provenance});this.intelligence.registerCandidate(candidate);const opportunity=this.intelligence.evaluateCandidate(candidate,this.clock(),{effort:OpportunityEffort.Unknown,strategicRelevance:input.properties.businessRelevance===PinterestBusinessRelevance.Relevant?1:.5});opportunities.push(opportunity);created++;statuses.push(opportunity.status);this.report("PinterestOpportunityCandidateCreated",request,{patternReference:ref,opportunityId:opportunity.id.value});if(opportunity.status===OpportunityStatus.Qualified){qualified++;this.report("PinterestOpportunityQualified",request,{opportunityId:opportunity.id.value});}else if(opportunity.status===OpportunityStatus.Weakening){weak++;this.report("PinterestOpportunityWeak",request,{opportunityId:opportunity.id.value});}else {emerging++;this.report("PinterestOpportunityEmerging",request,{opportunityId:opportunity.id.value});}
   }
   const confidence=new Confidence(opportunities.length?Number((opportunities.reduce((n,o)=>n+o.confidence.value,0)/opportunities.length).toFixed(3)):0),summary=new PinterestOpportunityEvaluationSummary(inputs.length,eligible,created,qualified,emerging,weak,rejections.length,stale,contradicted,assetGaps,gaps.length),state=warnings.length?PinterestOpportunityEvaluationState.CompletedWithWarnings:PinterestOpportunityEvaluationState.Completed,result=new PinterestOpportunityEvaluationResult({evaluationId:request.id,businessPackageId:request.properties.businessPackageId,state,evaluatedPatternReferences:inputs.map(x=>x.pattern.id.value),opportunities,statuses,confidence,evidenceSets:sets,relevanceStates,assetFitStates:assetStates,evidenceGaps:[...new Set(gaps)].sort(),warnings,rejectionReasons:rejections,summary,startedAt:started,completedAt:this.clock(),correlationIdentifier:request.properties.correlationIdentifier,provenance:inputs.map(x=>x.pattern.provenance)});this.repository.store(result);this.transition(request,state,"PinterestOpportunityEvaluationCompleted");return result;
  }catch(error){this.transition(request,PinterestOpportunityEvaluationState.Failed,"PinterestOpportunityEvaluationFailed");throw error instanceof PinterestOpportunityEvaluationException?error:new PinterestOpportunityEvaluationException("Opportunity evaluation failed","PINTEREST_OPPORTUNITY_EVALUATION_FAILURE",{cause:error});}
 }
 private transition(request:PinterestOpportunityEvaluationRequest,state:PinterestOpportunityEvaluationState,name:string){this.repository.transition(request.id,state,this.clock());this.report(name,request,{state});}
 private report(name:string,request:PinterestOpportunityEvaluationRequest,extra:Record<string,string>){const at=this.clock(),context={evaluationId:request.id.value,businessPackageId:request.properties.businessPackageId.value,...extra};this.events?.publish(new Event({id:new EventId(`pinterest-opportunity-${++this.#sequence}`),type:new EventType(name),timestamp:at,source:"PinterestOpportunityEvaluationWorkflow",correlationId:request.properties.correlationIdentifier,context:new EventContext(context)}));this.audit?.append(new AuditEvent({id:`pinterest-opportunity-audit-${++this.#sequence}`,timestamp:at,type:AuditEventType.WorkflowEvent,source:"PinterestOpportunityEvaluationWorkflow",action:name,result:extra.state??extra.reason??"Recorded",responsibleIdentity:request.properties.requestingAuthorityReference,relatedTaskOrWorkflowId:request.id.value,context}));}
}
