import { AuditEvent } from "../../core/platform/AuditEvent.ts";
import { AuditEventType } from "../../core/platform/AuditEventType.ts";
import type { AuditRecorder } from "../../core/platform/AuditRecorder.ts";
import { Event } from "../../core/platform/Event.ts";
import type { EventBus } from "../../core/platform/EventBus.ts";
import { EventContext } from "../../core/platform/EventContext.ts";
import { EventId } from "../../core/platform/EventId.ts";
import { EventType } from "../../core/platform/EventType.ts";
import { MarketSourceId, Provenance } from "../../intelligence/market/MarketIntelligenceDomain.ts";
import { MarketSourceAvailability, MarketSourceCapability, MarketSourceHealth, MarketSourceHealthState, MarketSourceRateLimit, MarketSourceState } from "../../intelligence/market/integration/MarketSourceIntegrationDomain.ts";
import { MarketSourceRegistry } from "../../intelligence/market/integration/MarketSourceIntegrationService.ts";
import { ExternalAuthenticationFailureType } from "../../security/authentication/ExternalAuthenticationDomain.ts";
import type { CredentialMetadata } from "../../security/credentials/CredentialVault.ts";
import { PinterestMarketSourceAdapter, PinterestTimeoutError } from "./PinterestMarketSourceAdapter.ts";
import { PinterestAccessMetadata, PinterestCapabilityState, PinterestCapabilityUnavailableReason, PinterestCapabilityVerification, PinterestConnectionProbe, PinterestConnectionState, PinterestConnectionVerificationRequest, PinterestConnectionVerificationResult, PinterestAuthenticationVerificationState } from "./PinterestConnectionVerificationDomain.ts";
import { PinterestConnectionVerificationRepository } from "./PinterestConnectionVerificationRepository.ts";

export interface PinterestCredentialMetadataBoundary { metadata(credentialId:string):CredentialMetadata|undefined; }
const PRIVATE=new Set(["CompetitorClicks","CompetitorCTR","CompetitorConversions","CompetitorPrivateAnalytics"]);

export class PinterestConnectionVerifier {
  #sequence=0;
  constructor(private readonly registry:MarketSourceRegistry,private readonly credentials:PinterestCredentialMetadataBoundary,private readonly repository:PinterestConnectionVerificationRepository,private readonly events?:EventBus,private readonly audit?:AuditRecorder,private readonly clock=()=>new Date()){}
  async verify(request:PinterestConnectionVerificationRequest):Promise<PinterestConnectionVerificationResult>{
    this.report("PinterestVerificationRequested",request);this.report("PinterestVerificationStarted",request);
    const descriptor=this.registry.descriptor(request.properties.adapterId),adapter=this.registry.adapter(request.properties.adapterId);
    const configurationFailure=this.configurationFailure(request,descriptor,adapter);
    if(configurationFailure){const result=this.failedConfiguration(request,descriptor?.health,configurationFailure);this.complete(request,result,"PinterestVerificationFailed");return result;}
    const probe=adapter as PinterestMarketSourceAdapter & PinterestConnectionProbe;
    let authentication:Awaited<ReturnType<PinterestConnectionProbe["verifyAuthentication"]>>;
    try{authentication=await probe.verifyAuthentication(request);}catch{const result=this.authenticationFailure(request,descriptor!.health,"TemporaryFailure",PinterestCapabilityUnavailableReason.ProviderUnavailable,"Pinterest authentication is temporarily unavailable");this.complete(request,result,"PinterestVerificationFailed");return result;}
    if(!authentication.successful){const state=this.authenticationState(authentication.failure);this.report("PinterestAuthenticationFailed",request,{authenticationState:state});const result=this.authenticationFailure(request,descriptor!.health,state,PinterestCapabilityUnavailableReason.AuthenticationRequired,"Pinterest authentication requires recovery");this.complete(request,result,"PinterestVerificationCompleted");return result;}
    this.report("PinterestAuthenticationVerified",request);const verified: PinterestCapabilityVerification[]=[];
    for(const capability of request.requestedCapabilities){let result:PinterestCapabilityVerification;if(PRIVATE.has(capability.value))result=this.capability(request,capability,PinterestCapabilityState.NotSupported,PinterestCapabilityUnavailableReason.PrivateCompetitorMetric,"Private competitor metrics are not supplied by an authorized provider");else if(!descriptor!.supports(capability))result=this.capability(request,capability,PinterestCapabilityState.NotImplemented,PinterestCapabilityUnavailableReason.NotImplemented,"Capability is not implemented by this adapter");else result=await this.probe(request,probe,capability,authentication.session);verified.push(result);this.report(result.state===PinterestCapabilityState.Available?"PinterestCapabilityVerified":"PinterestCapabilityUnavailable",request,{capability:capability.value,state:result.state});}
    const state=this.overall(verified),rateLimit=verified.find(x=>x.rateLimit)?.rateLimit,at=this.clock();const healthy=verified.some(x=>x.state===PinterestCapabilityState.Available);const result=new PinterestConnectionVerificationResult({id:request.id,adapterId:request.properties.adapterId,sourceReference:descriptor!.source.id.value,businessPackageId:request.properties.businessPackageId,credentialId:request.properties.credentialId,state,authenticationState:"Authenticated",capabilities:verified,sourceHealth:new MarketSourceHealth(healthy?MarketSourceHealthState.Healthy:MarketSourceHealthState.Degraded,at,healthy?0:1,healthy?at:undefined,healthy?undefined:at),availability:state===PinterestConnectionState.Available?MarketSourceAvailability.Available:state===PinterestConnectionState.PartiallyAvailable?MarketSourceAvailability.Partial:MarketSourceAvailability.Unavailable,rateLimit,accessMetadata:probe.verificationMetadata(at),verifiedAt:at,warnings:verified.filter(x=>x.reason===PinterestCapabilityUnavailableReason.NoData).map(x=>`${x.capability.value}: NoData`),correlationIdentifier:request.properties.correlationIdentifier});this.complete(request,result,"PinterestVerificationCompleted");return result;
  }
  async reverify(request:PinterestConnectionVerificationRequest){if(!request.properties.reverificationOf||!this.repository.get(request.properties.reverificationOf))throw new Error("Re-verification must reference an existing result");this.report("PinterestReverificationRequested",request);return this.verify(request);}
  private configurationFailure(request:PinterestConnectionVerificationRequest,descriptor:ReturnType<MarketSourceRegistry["descriptor"]>,adapter:ReturnType<MarketSourceRegistry["adapter"]>){if(!descriptor||!adapter)return "Pinterest adapter/source is not registered";if(!(adapter instanceof PinterestMarketSourceAdapter)||!("verifyAuthentication" in adapter))return "Registered adapter does not support Pinterest verification";if([MarketSourceState.Registered,MarketSourceState.Disabled,MarketSourceState.Retired,MarketSourceState.OnHold].includes(descriptor.state))return `Pinterest source state disallows verification: ${descriptor.state}`;if(descriptor.state===MarketSourceState.Maintenance)return "Pinterest source is in maintenance";if(descriptor.properties.credentialId?.value!==request.properties.credentialId.value)return "Configured CredentialId does not match";const credential=this.credentials.metadata(request.properties.credentialId.value);if(!credential)return "CredentialId is not configured";if(!credential.businessPackageScopes.includes(request.properties.businessPackageId.value))return "Credential is not scoped to this Business Package";return undefined;}
  private async probe(request:PinterestConnectionVerificationRequest,probe:PinterestConnectionProbe,capability:MarketSourceCapability,session:any){try{const response=await probe.probeCapability(capability,session);if(response.status>=200&&response.status<300)return this.capability(request,capability,PinterestCapabilityState.Available,response.noData?PinterestCapabilityUnavailableReason.NoData:PinterestCapabilityUnavailableReason.None,response.noData?"Capability is available; provider returned NoData":"Capability is available",undefined,response.provenance);if(response.status===401)return this.capability(request,capability,PinterestCapabilityState.AuthenticationRequired,PinterestCapabilityUnavailableReason.AuthenticationRequired,"Pinterest reauthorization is required");if(response.status===403)return this.capability(request,capability,PinterestCapabilityState.PermissionRequired,PinterestCapabilityUnavailableReason.PermissionDenied,"Pinterest permission is required");if(response.status===429){const at=this.clock(),seconds=Number(response.headers?.["retry-after"]),rate=new MarketSourceRateLimit(true,at,new Provenance("Pinterest verification",at,new MarketSourceId("Pinterest"),[request.id.value]),Number.isFinite(seconds)?new Date(at.getTime()+seconds*1000):undefined,response.headers?.["x-ratelimit-reset"]);return this.capability(request,capability,PinterestCapabilityState.RateLimited,PinterestCapabilityUnavailableReason.RateLimited,"Pinterest rate limit is active",rate);}return this.capability(request,capability,PinterestCapabilityState.TemporarilyUnavailable,PinterestCapabilityUnavailableReason.ProviderUnavailable,"Pinterest provider is temporarily unavailable");}catch(error){return this.capability(request,capability,PinterestCapabilityState.TemporarilyUnavailable,PinterestCapabilityUnavailableReason.ProviderUnavailable,error instanceof PinterestTimeoutError?"Pinterest verification timed out":"Pinterest network verification failed");}}
  private capability(request:PinterestConnectionVerificationRequest,capability:MarketSourceCapability,state:PinterestCapabilityState,reason:PinterestCapabilityUnavailableReason,safe:string,rateLimit?:MarketSourceRateLimit,provenance:Readonly<Record<string,string>>={}){return new PinterestCapabilityVerification(capability,state,reason,safe,this.clock(),request.properties.adapterId,"Pinterest",{verificationId:request.id.value,...provenance},rateLimit);}
  private overall(values:readonly PinterestCapabilityVerification[]){const available=values.filter(x=>x.state===PinterestCapabilityState.Available).length;if(available===values.length)return PinterestConnectionState.Available;if(available>0)return PinterestConnectionState.PartiallyAvailable;if(values.every(x=>x.state===PinterestCapabilityState.RateLimited))return PinterestConnectionState.RateLimited;if(values.some(x=>x.state===PinterestCapabilityState.PermissionRequired))return PinterestConnectionState.PermissionLimited;return PinterestConnectionState.Unavailable;}
  private authenticationState(failure:ExternalAuthenticationFailureType):PinterestAuthenticationVerificationState {if([ExternalAuthenticationFailureType.InvalidCredential,ExternalAuthenticationFailureType.InvalidPassword,ExternalAuthenticationFailureType.InvalidUsername,ExternalAuthenticationFailureType.ExpiredCredential].includes(failure))return "CredentialCorrectionRequired";if([ExternalAuthenticationFailureType.ReauthorizationRequired,ExternalAuthenticationFailureType.ExpiredToken].includes(failure))return "ReauthorizationRequired";if(failure===ExternalAuthenticationFailureType.MFARequired)return "MFARequired";if(failure===ExternalAuthenticationFailureType.PermissionDenied)return "PermissionDenied";if([ExternalAuthenticationFailureType.AuthenticationUnavailable,ExternalAuthenticationFailureType.NetworkUnavailable,ExternalAuthenticationFailureType.ProviderMaintenance,ExternalAuthenticationFailureType.RateLimited].includes(failure))return "TemporaryFailure";return "NonRecoverableFailure";}
  private failedConfiguration(request:PinterestConnectionVerificationRequest,health:MarketSourceHealth|undefined,message:string){const at=this.clock();return new PinterestConnectionVerificationResult({id:request.id,adapterId:request.properties.adapterId,sourceReference:"Pinterest",businessPackageId:request.properties.businessPackageId,credentialId:request.properties.credentialId,state:message.includes("maintenance")?PinterestConnectionState.Maintenance:PinterestConnectionState.NotConfigured,authenticationState:"AuthenticationRequired",capabilities:request.requestedCapabilities.map(c=>this.capability(request,c,PinterestCapabilityState.Unavailable,PinterestCapabilityUnavailableReason.SourceUnavailable,message)),sourceHealth:health??new MarketSourceHealth(MarketSourceHealthState.Unknown,at),availability:MarketSourceAvailability.Unavailable,verifiedAt:at,failures:[message],correlationIdentifier:request.properties.correlationIdentifier});}
  private authenticationFailure(request:PinterestConnectionVerificationRequest,health:MarketSourceHealth,state:PinterestAuthenticationVerificationState,reason:PinterestCapabilityUnavailableReason,message:string){const at=this.clock();return new PinterestConnectionVerificationResult({id:request.id,adapterId:request.properties.adapterId,sourceReference:"Pinterest",businessPackageId:request.properties.businessPackageId,credentialId:request.properties.credentialId,state:PinterestConnectionState.AuthenticationRequired,authenticationState:state,capabilities:request.requestedCapabilities.map(c=>this.capability(request,c,PinterestCapabilityState.AuthenticationRequired,reason,message)),sourceHealth:health,availability:MarketSourceAvailability.Unavailable,verifiedAt:at,failures:[message],correlationIdentifier:request.properties.correlationIdentifier});}
  private complete(request:PinterestConnectionVerificationRequest,result:PinterestConnectionVerificationResult,event:string){this.repository.store(result);const connection=result.state===PinterestConnectionState.Available?"PinterestConnectionAvailable":result.state===PinterestConnectionState.PartiallyAvailable?"PinterestConnectionPartiallyAvailable":"PinterestConnectionUnavailable";this.report(connection,request,{state:result.state});this.report(event,request,{state:result.state});}
  private report(action:string,request:PinterestConnectionVerificationRequest,extra:Record<string,string>={}){const at=this.clock(),context={verificationId:request.id.value,adapterId:request.properties.adapterId.value,businessPackageId:request.properties.businessPackageId.value,credentialId:request.properties.credentialId.value,...extra},sequence=++this.#sequence;this.events?.publish(new Event({id:new EventId(`pinterest-verification-${sequence}`),type:new EventType(action),timestamp:at,source:"PinterestConnectionVerifier",correlationId:request.properties.correlationIdentifier,context:new EventContext(context)}));this.audit?.append(new AuditEvent({id:`pinterest-verification-audit-${sequence}`,timestamp:at,type:AuditEventType.ExternalIntegration,source:"PinterestConnectionVerifier",action,result:extra.state??"Recorded",responsibleIdentity:request.properties.requestingAuthorityReference,relatedTaskOrWorkflowId:request.properties.requestingAuthorityReference,context}));}
}
