import type {BusinessPackageId,Provenance} from "../../intelligence/market/MarketIntelligenceDomain.ts";
import type {PinterestCopyArtifact} from "./PinterestCopyProductionDomain.ts";
import type {PinterestCreationPlan} from "./PinterestCreationPlanningDomain.ts";
import type {PinterestVisualArtifact} from "./PinterestVisualProductionDomain.ts";

const nonempty=(value:string,name:string)=>{if(!value?.trim())throw new PinterestCreativeAssemblyException(`${name} is required`,"INVALID_REQUEST");};
const freeze=<T>(values:readonly T[])=>Object.freeze([...values]);
export class PinterestCreativeAssemblyException extends Error{constructor(message:string,readonly code="PINTEREST_CREATIVE_ASSEMBLY_FAILURE",options?:ErrorOptions){super(message,options);this.name="PinterestCreativeAssemblyException";}}
export class PinterestCreativeAssemblyId{constructor(readonly value:string){nonempty(value,"Assembly identifier");Object.freeze(this);}}
export class PinterestCreativeCandidateVersion{constructor(readonly value:number){if(!Number.isInteger(value)||value<1)throw new PinterestCreativeAssemblyException("Candidate version must be positive","INVALID_VERSION");Object.freeze(this);}}
export enum PinterestCreativeReadiness{AssemblyPending="AssemblyPending",ValidationRequired="ValidationRequired",ValidationFailed="ValidationFailed",ReadyForPublishing="ReadyForPublishing",Superseded="Superseded",Cancelled="Cancelled",Invalidated="Invalidated"}
export enum PinterestDestinationValidation{Validated="Validated",Unvalidated="Unvalidated",Unavailable="Unavailable",Invalid="Invalid"}
export enum PinterestCreativeValidationSeverity{Info="Info",Warning="Warning",Blocking="Blocking"}
export enum PinterestCreativeValidationIssueType{MissingRequiredField="MissingRequiredField",VersionMismatch="VersionMismatch",BusinessPackageMismatch="BusinessPackageMismatch",LanguageMismatch="LanguageMismatch",DestinationMismatch="DestinationMismatch",DestinationUnvalidated="DestinationUnvalidated",DestinationInvalid="DestinationInvalid",CopyVisualConflict="CopyVisualConflict",UnsupportedMediaType="UnsupportedMediaType",InvalidDimensions="InvalidDimensions",InvalidAspectRatio="InvalidAspectRatio",PlatformCapabilityUnknown="PlatformCapabilityUnknown",PlatformConstraintViolation="PlatformConstraintViolation",BusinessRuleViolation="BusinessRuleViolation",ProhibitedClaim="ProhibitedClaim",FactualConflict="FactualConflict",AccessibilityIncomplete="AccessibilityIncomplete",ExperimentMismatch="ExperimentMismatch",OriginalityConcern="OriginalityConcern",StaleApproval="StaleApproval",SupersededArtifact="SupersededArtifact",Other="Other"}
export class PinterestCreativeValidationIssue{constructor(readonly type:PinterestCreativeValidationIssueType,readonly severity:PinterestCreativeValidationSeverity,readonly message:string,readonly correctionRoute?:"CopyProduction"|"VisualProduction"|"CreationPlanning"|"CEOReview"){nonempty(message,"Validation issue message");Object.freeze(this);}}
export class PinterestCreativeValidationResult{readonly issues;constructor(issues:readonly PinterestCreativeValidationIssue[],readonly validatedAt:Date){this.issues=freeze(issues);Object.freeze(this);}get blocking(){return this.issues.some(x=>x.severity===PinterestCreativeValidationSeverity.Blocking);}get warnings(){return Object.freeze(this.issues.filter(x=>x.severity===PinterestCreativeValidationSeverity.Warning));}}
export interface PinterestPlatformCreativeCapabilities{maximumTitleLength?:number;maximumDescriptionLength?:number;supportedMediaTypes?:readonly string[];allowedDimensions?:readonly {width:number;height:number}[];allowedAspectRatios?:readonly string[];}
export interface PinterestBusinessCreativePolicy{accessibilityTextRequired?:boolean;allowResearchOnlyDestination?:boolean;validate(candidate:PinterestCreativeCandidate):readonly PinterestCreativeValidationIssue[];}
export class PinterestCreativeAssemblyRequest{constructor(readonly assemblyId:PinterestCreativeAssemblyId,readonly candidateId:string,readonly candidateVersion:PinterestCreativeCandidateVersion,readonly plan:PinterestCreationPlan,readonly copyArtifact:PinterestCopyArtifact,readonly visualArtifact:PinterestVisualArtifact,readonly businessPackageId:BusinessPackageId,readonly destinationValidation:PinterestDestinationValidation,readonly correlationIdentifier:string,readonly requestedBy:string){nonempty(candidateId,"Candidate identifier");nonempty(correlationIdentifier,"Correlation identifier");nonempty(requestedBy,"Requesting authority");Object.freeze(this);}}
export class PinterestCreativeAssemblyContext{constructor(readonly request:PinterestCreativeAssemblyRequest,readonly capabilities:PinterestPlatformCreativeCapabilities|undefined,readonly policy:PinterestBusinessCreativePolicy|undefined){Object.freeze(this);}}
export interface PinterestCreativeLineage{planId:string;planVersion:number;copyArtifactId:string;copyArtifactVersion:number;visualArtifactId:string;visualArtifactVersion:number;recommendationId:string;recommendationVersion:number;ceoDecisionId:string;opportunityReferences:readonly string[];patternReferences:readonly string[];evidenceReferences:readonly string[];}
export class PinterestCreativeCandidate{
 readonly lineage;readonly issues;readonly #created:number;
 constructor(readonly id:string,readonly version:PinterestCreativeCandidateVersion,readonly readiness:PinterestCreativeReadiness,readonly businessPackageId:BusinessPackageId,readonly destination:unknown,readonly destinationUrl:string|undefined,readonly destinationValidation:PinterestDestinationValidation,readonly title:string|undefined,readonly description:string|undefined,readonly cta:string|undefined,readonly accessibilityText:string|undefined,readonly visualAssetReference:string,readonly language:string,readonly market:string|undefined,readonly region:string|undefined,readonly experiment:unknown,readonly measurementContext:unknown,lineage:PinterestCreativeLineage,issues:readonly PinterestCreativeValidationIssue[],readonly correlationIdentifier:string,readonly provenance:Provenance|unknown,createdAt:Date){this.lineage=Object.freeze({...lineage,opportunityReferences:freeze(lineage.opportunityReferences),patternReferences:freeze(lineage.patternReferences),evidenceReferences:freeze(lineage.evidenceReferences)});this.issues=freeze(issues);this.#created=createdAt.getTime();Object.freeze(this);}get createdAt(){return new Date(this.#created);}
}
export class PinterestCreativeAssemblyResult{constructor(readonly candidate:PinterestCreativeCandidate,readonly validation:PinterestCreativeValidationResult){Object.freeze(this);}}
