import {PinterestCopyStatus} from "./PinterestCopyProductionDomain.ts";import {PinterestCreationPlanState,PinterestDestinationType} from "./PinterestCreationPlanningDomain.ts";import {PinterestVisualStatus} from "./PinterestVisualProductionDomain.ts";
import {PinterestCreativeAssemblyContext,PinterestCreativeAssemblyException,PinterestCreativeAssemblyRequest,PinterestCreativeAssemblyResult,PinterestCreativeCandidate,PinterestCreativeReadiness,PinterestCreativeValidationIssue,PinterestCreativeValidationIssueType as T,PinterestCreativeValidationResult,PinterestCreativeValidationSeverity as S,PinterestDestinationValidation} from "./PinterestCreativeAssemblyDomain.ts";import {PinterestCreativeAssemblyRepository} from "./PinterestCreativeAssemblyRepository.ts";
const value=(x:unknown):string|undefined=>typeof x==="string"?x:(x as {value?:string}|undefined)?.value;
export class PinterestCreativeAssemblyWorkflow{constructor(readonly repository=new PinterestCreativeAssemblyRepository(),private readonly clock=()=>new Date()){}
 assemble(request:PinterestCreativeAssemblyRequest,capabilities?:PinterestCreativeAssemblyContext["capabilities"],policy?:PinterestCreativeAssemblyContext["policy"]){const p=request.plan as any,c=request.copyArtifact,v=request.visualArtifact,copy=c.drafts.at(-1)?.copy,visual=v.drafts.at(-1)?.visual,issues:PinterestCreativeValidationIssue[]=[];const add=(type:T,message:string,route?:PinterestCreativeValidationIssue["correctionRoute"],severity=S.Blocking)=>issues.push(new PinterestCreativeValidationIssue(type,severity,message,route));
  if(p.state!==PinterestCreationPlanState.ReadyForProduction)add(T.StaleApproval,"Creation Plan is not current and ReadyForProduction","CreationPlanning");if(c.status!==PinterestCopyStatus.ReadyForCreativeAssembly)add(T.SupersededArtifact,"Copy Artifact is not ReadyForCreativeAssembly","CopyProduction");if(v.status!==PinterestVisualStatus.ReadyForCreativeAssembly)add(T.SupersededArtifact,"Visual Artifact is not ReadyForCreativeAssembly","VisualProduction");
  for(const [name,lineage] of [["Copy",c.lineage],["Visual",v.lineage]] as const)if(lineage.planId!==p.id.value||lineage.planVersion!==p.version.value)add(T.VersionMismatch,`${name} Artifact does not reference the exact Creation Plan version`,name==="Copy"?"CopyProduction":"VisualProduction");
  const pkg=value(request.businessPackageId);for(const [name,x] of [["Plan",p.businessPackageId],["Copy",c.lineage.businessPackageId],["Visual",v.lineage.businessPackageId]] as const)if(value(x)!==pkg)add(T.BusinessPackageMismatch,`${name} Business Package mismatch`,`CreationPlanning`);
  if(p.recommendation?.version!==p.decision?.recommendationVersion||p.learningTrace?.recommendationVersion!==p.recommendation?.version)add(T.StaleApproval,"CEO approval lineage is stale","CEOReview");
  if(c.lineage.recommendationVersion!==p.learningTrace.recommendationVersion||v.lineage.recommendationVersion!==p.learningTrace.recommendationVersion)add(T.VersionMismatch,"Recommendation version mismatch","CreationPlanning");
  if(!copy?.title)add(T.MissingRequiredField,"Title is required","CopyProduction");if(!copy?.description)add(T.MissingRequiredField,"Description is required","CopyProduction");if(!visual?.assetReference)add(T.MissingRequiredField,"Visual asset is required","VisualProduction");
  const language=p.contentDirection?.language;if(copy?.language!==language||visual?.language&&visual.language!==language)add(T.LanguageMismatch,"Plan, copy, and visible visual language must match",visual?.language!==language?"VisualProduction":"CopyProduction");
  const destination=p.destination,ref=destination?.assetReference;if(copy?.destinationReference&&copy.destinationReference!==ref||visual?.destinationReference&&visual.destinationReference!==ref)add(T.DestinationMismatch,"Creative destination conflicts with approved Plan destination","CreationPlanning");
  if(request.destinationValidation===PinterestDestinationValidation.Invalid||request.destinationValidation===PinterestDestinationValidation.Unavailable)add(T.DestinationInvalid,"Approved destination is invalid or unavailable","CreationPlanning");else if(request.destinationValidation===PinterestDestinationValidation.Unvalidated)add(T.DestinationUnvalidated,"Destination remains explicitly unvalidated",undefined,S.Warning);
  if(destination?.type===PinterestDestinationType.ResearchOnly&&!policy?.allowResearchOnlyDestination)add(T.DestinationInvalid,"ResearchOnly is not a publishable destination","CreationPlanning");
  if(!capabilities)add(T.PlatformCapabilityUnknown,"Pinterest platform capability is unknown",undefined,S.Warning);else{if(capabilities.maximumTitleLength&&typeof copy?.title==="string"&&copy.title.length>capabilities.maximumTitleLength)add(T.PlatformConstraintViolation,"Title exceeds configured platform limit","CopyProduction");if(capabilities.maximumDescriptionLength&&typeof copy?.description==="string"&&copy.description.length>capabilities.maximumDescriptionLength)add(T.PlatformConstraintViolation,"Description exceeds configured platform limit","CopyProduction");if(capabilities.supportedMediaTypes&&typeof visual?.mediaType==="string"&&!capabilities.supportedMediaTypes.includes(visual.mediaType))add(T.UnsupportedMediaType,"Visual media type is unsupported","VisualProduction");if(capabilities.allowedDimensions&&!capabilities.allowedDimensions.some(d=>d.width===visual?.width&&d.height===visual?.height))add(T.InvalidDimensions,"Visual dimensions are invalid","VisualProduction");if(capabilities.allowedAspectRatios&&typeof visual?.aspectRatio==="string"&&!capabilities.allowedAspectRatios.includes(visual.aspectRatio))add(T.InvalidAspectRatio,"Visual aspect ratio is invalid","VisualProduction");}
  if(visual?.visibleText&&copy?.title&&visual.visibleText!==copy.title&&visual.visibleText!==copy.description)add(T.CopyVisualConflict,"Visible visual text is not supported by approved copy","VisualProduction");if(copy?.cta&&p.copyDirection?.ctaObjective&&!copy.ctaObjective?.includes?.(p.copyDirection.ctaObjective))add(T.CopyVisualConflict,"CTA does not match approved objective","CopyProduction");if(policy?.accessibilityTextRequired&&!copy?.accessibilityText)add(T.AccessibilityIncomplete,"Accessibility text is required","CopyProduction");
  if(visual?.originalBusinessCreative===false||visual?.prohibitedTreatments?.length)add(T.OriginalityConcern,"Never Copy governance check failed","VisualProduction");if(c.variantId!==v.variantId)add(T.ExperimentMismatch,"Copy and Visual experiment variants differ","CreationPlanning");if(p.experiment&&(c.lineage.hypothesis!==p.experiment.hypothesis||v.lineage.hypothesis!==p.experiment.hypothesis))add(T.ExperimentMismatch,"Experiment lineage differs from Plan","CreationPlanning");
  const at=this.clock(),lineage={planId:p.id.value,planVersion:p.version.value,copyArtifactId:c.id.value,copyArtifactVersion:c.version.value,visualArtifactId:v.id.value,visualArtifactVersion:v.version.value,recommendationId:p.learningTrace.recommendationId,recommendationVersion:p.learningTrace.recommendationVersion,ceoDecisionId:p.learningTrace.ceoDecisionId,opportunityReferences:p.learningTrace.opportunityReferences,patternReferences:p.learningTrace.patternReferences,evidenceReferences:p.learningTrace.evidenceReferences};
  const candidate=(readiness:PinterestCreativeReadiness,currentIssues:readonly PinterestCreativeValidationIssue[])=>new PinterestCreativeCandidate(request.candidateId,request.candidateVersion,readiness,request.businessPackageId,destination,destination?.canonicalUrl,request.destinationValidation,copy?.title,copy?.description,copy?.cta,copy?.accessibilityText,visual?.assetReference??"",language??copy?.language??"",p.contentDirection?.market,p.contentDirection?.region,p.experiment,p.measurementPlan,lineage,currentIssues,request.correlationIdentifier,p.provenance,at);
  if(policy)issues.push(...policy.validate(candidate(PinterestCreativeReadiness.ValidationRequired,[])));const validation=new PinterestCreativeValidationResult(issues,at),result=candidate(validation.blocking?PinterestCreativeReadiness.ValidationFailed:PinterestCreativeReadiness.ReadyForPublishing,issues);this.repository.store(result);return new PinterestCreativeAssemblyResult(result,validation);
 }
}
