import type {BusinessPackageId} from "../../intelligence/market/MarketIntelligenceDomain.ts";
import type {PinterestCreationPlan} from "./PinterestCreationPlanningDomain.ts";

const required=(value:string,name:string)=>{if(!value?.trim())throw new PinterestCopyProductionException(`${name} is required`,"INVALID_REQUEST");return value;};
const frozen=<T>(items:readonly T[])=>Object.freeze([...items]);

export class PinterestCopyProductionException extends Error{constructor(message:string,readonly code="PINTEREST_COPY_PRODUCTION_FAILURE",options?:ErrorOptions){super(message,options);this.name="PinterestCopyProductionException";}}
export class PinterestCopyArtifactId{constructor(readonly value:string){required(value,"Copy artifact identifier");Object.freeze(this);}}
export class PinterestCopyArtifactVersion{constructor(readonly value:number){if(!Number.isInteger(value)||value<1)throw new PinterestCopyProductionException("Artifact version must be positive","INVALID_VERSION");Object.freeze(this);}}
export enum PinterestCopyStatus{Requested="Requested",Generating="Generating",Draft="Draft",ValidationRequired="ValidationRequired",AdditionalResearchRequired="AdditionalResearchRequired",ValidationFailed="ValidationFailed",ReadyForCreativeAssembly="ReadyForCreativeAssembly",Superseded="Superseded",Cancelled="Cancelled",Failed="Failed"}
export type PinterestCopyField="title"|"description"|"cta"|"accessibilityText";
export interface PinterestCopyCapabilities{supportedFields:readonly PinterestCopyField[];maximumLengths:Partial<Record<PinterestCopyField,number>>;}
export interface PinterestKnowledgeContext{reference:string;businessPackageId:BusinessPackageId;facts:readonly string[];requiredResearch?:readonly string[];}
export interface PinterestBusinessWritingRules{reference:string;businessPackageId:BusinessPackageId;instructions:readonly string[];requiredTerminology?:readonly string[];}
export class PinterestCopyProductionRequest{constructor(readonly artifactId:PinterestCopyArtifactId,readonly planId:string,readonly planVersion:number,readonly businessPackageId:BusinessPackageId,readonly correlationIdentifier:string,readonly authorityReference:string,readonly requestedComponents:readonly PinterestCopyField[],readonly knowledgeContext:PinterestKnowledgeContext,readonly writingRules:PinterestBusinessWritingRules,readonly variantCount=1){required(planId,"Creation Plan identifier");required(correlationIdentifier,"Correlation identifier");required(authorityReference,"Authority reference");if(!Number.isInteger(planVersion)||planVersion<1)throw new PinterestCopyProductionException("Exact Plan version is required","PLAN_VERSION_MISMATCH");if(!requestedComponents.length)throw new PinterestCopyProductionException("Copy components are required","MISSING_COMPONENTS");if(!Number.isInteger(variantCount)||variantCount<1)throw new PinterestCopyProductionException("Variant count must be positive","INVALID_VARIANTS");Object.freeze(requestedComponents);Object.freeze(this);}}
export interface PinterestGeneratedCopy{title?:string;description?:string;cta?:string;accessibilityText?:string;language:string;topic:string;destinationReference?:string;ctaObjective:string;originalExpression:boolean;usedKnowledgeReferences:readonly string[];usedKeywordTerms:readonly string[];unsupportedClaims?:readonly string[];providerFields?:readonly string[];}
export interface PinterestGenerationProvenance{capabilityReference:string;configurationReference?:string;generatedAt:Date;}
export interface PinterestCopyWriterResult{copy:PinterestGeneratedCopy;provenance:PinterestGenerationProvenance;}
export interface PinterestCopyWriter{generate(context:PinterestCopyProductionContext):PinterestCopyWriterResult;}
export class PinterestCopyProductionContext{constructor(readonly plan:PinterestCreationPlan,readonly request:PinterestCopyProductionRequest,readonly variantId:string,readonly revision:number){Object.freeze(this);}}
export class PinterestCopyDraft{readonly copy:PinterestGeneratedCopy;constructor(readonly draftId:string,readonly revision:number,readonly variantId:string,copy:PinterestGeneratedCopy,readonly provenance:PinterestGenerationProvenance,readonly createdAt:Date){this.copy=Object.freeze({...copy,usedKnowledgeReferences:frozen(copy.usedKnowledgeReferences),usedKeywordTerms:frozen(copy.usedKeywordTerms),unsupportedClaims:frozen(copy.unsupportedClaims??[]),providerFields:frozen(copy.providerFields??[])});Object.freeze(this);}}
export class PinterestCopyValidationResult{readonly reasons;constructor(readonly valid:boolean,reasons:readonly string[],readonly originalityValid:boolean,readonly validatedAt:Date){this.reasons=frozen(reasons);Object.freeze(this);}}
export interface PinterestCopyLineage{planId:string;planVersion:number;recommendationId:string;recommendationVersion:number;ceoDecisionId:string;businessPackageId:string;opportunityReferences:readonly string[];patternReferences:readonly string[];evidenceReferences:readonly string[];correlationIdentifier:string;hypothesis?:string;}
export class PinterestCopyArtifact{readonly drafts;readonly lineage;constructor(readonly id:PinterestCopyArtifactId,readonly version:PinterestCopyArtifactVersion,readonly status:PinterestCopyStatus,readonly variantId:string,drafts:readonly PinterestCopyDraft[],readonly validation:PinterestCopyValidationResult|undefined,lineage:PinterestCopyLineage){this.drafts=frozen(drafts);this.lineage=Object.freeze({...lineage,opportunityReferences:frozen(lineage.opportunityReferences),patternReferences:frozen(lineage.patternReferences),evidenceReferences:frozen(lineage.evidenceReferences)});Object.freeze(this);}}
export class PinterestCopyProductionResult{readonly artifacts;constructor(artifacts:readonly PinterestCopyArtifact[]){this.artifacts=frozen(artifacts);Object.freeze(this);}}
