import {AuditEvent} from "../../core/platform/AuditEvent.ts";import {AuditEventType} from "../../core/platform/AuditEventType.ts";import type {AuditRecorder} from "../../core/platform/AuditRecorder.ts";import {Event} from "../../core/platform/Event.ts";import type {EventBus} from "../../core/platform/EventBus.ts";import {EventContext} from "../../core/platform/EventContext.ts";import {EventId} from "../../core/platform/EventId.ts";import {EventType} from "../../core/platform/EventType.ts";
import {OpportunityStatus} from "../../business/market/opportunities/OpportunityIntelligenceDomain.ts";
import {BusinessRecommendation,RecommendationCandidate,RecommendationId,RecommendationStatus,RecommendationType} from "../../business/recommendations/RecommendationDomain.ts";import type {RecommendationEngine} from "../../business/recommendations/RecommendationEngine.ts";
import {PinterestRecommendationCandidateInput,PinterestRecommendationEvaluationException,PinterestRecommendationEvaluationRequest,PinterestRecommendationEvaluationResult,PinterestRecommendationEvaluationState,PinterestRecommendationEvaluationSummary,PinterestRecommendationEvidenceGap,PinterestRecommendationEvidenceSet} from "./PinterestRecommendationEvaluationDomain.ts";import {PinterestRecommendationEvaluationRepository} from "./PinterestRecommendationEvaluationRepository.ts";

/** TCO-invoked advisory boundary. It reads supplied context and never generates content, publishes, schedules, or executes a workflow. */
export class PinterestRecommendationEvaluationWorkflow{
 #sequence=0;
 constructor(private readonly engine:RecommendationEngine,readonly repository=new PinterestRecommendationEvaluationRepository(),private readonly events?:EventBus,private readonly audit?:AuditRecorder,private readonly clock=()=>new Date()){}
 evaluate(request:PinterestRecommendationEvaluationRequest,unordered:readonly PinterestRecommendationCandidateInput[]):PinterestRecommendationEvaluationResult{
  if(this.repository.result(request.id))throw new PinterestRecommendationEvaluationException("Evaluation already completed","IMMUTABLE_EVALUATION_RESULT");const started=this.clock();this.transition(request,PinterestRecommendationEvaluationState.Requested,"PinterestRecommendationEvaluationRequested");this.transition(request,PinterestRecommendationEvaluationState.Started,"PinterestRecommendationEvaluationStarted");
  try{const inputs=[...unordered].sort((a,b)=>a.opportunities.map(x=>x.id.value).join("|").localeCompare(b.opportunities.map(x=>x.id.value).join("|")));const recommendations:BusinessRecommendation[]=[],sets:PinterestRecommendationEvidenceSet[]=[],gaps:PinterestRecommendationEvidenceGap[]=[],warnings:string[]=[];let evaluated=0,eligible=0,candidates=0,ready=0,research=0,experiments=0,insufficient=0,rejected=0,contradicted=0,deferred=0;
   for(const input of inputs){evaluated+=input.opportunities.length;const refs=input.opportunities.map(x=>x.id.value);if(input.opportunities.some(x=>x.businessPackageId.value!==request.businessPackageId.value)||input.properties.objective.businessPackageId.value!==request.businessPackageId.value)throw new PinterestRecommendationEvaluationException("Intelligence crosses Business Package boundary","PACKAGE_MISMATCH");if(refs.some(x=>!request.opportunityReferences.includes(x))){rejected++;warnings.push(`${refs.join(",")}: Unsupported Opportunity reference`);continue;}const eligibleItems=input.opportunities.filter(x=>[OpportunityStatus.Qualified,OpportunityStatus.RecommendationCandidate].includes(x.status));eligible+=eligibleItems.length;if(eligibleItems.length!==input.opportunities.length){rejected++;warnings.push(`${refs.join(",")}: Opportunity is not eligible`);continue;}
    const set=new PinterestRecommendationEvidenceSet(input);sets.push(set);gaps.push(...input.evidenceGaps);if(set.contradicting.length>=set.supporting.length){contradicted++;rejected++;warnings.push(`${refs.join(",")}: Strongly contradicted`);continue;}let type=input.properties.type;if(input.evidenceGaps.length&&type!==RecommendationType.StrategicExperiment)type=RecommendationType.ResearchOpportunity;if(input.evidenceGaps.length){insufficient++;this.report("PinterestRecommendationInsufficientEvidence",request,{opportunityReferences:refs.join(",")});}
    const id=new RecommendationId(`pinterest-recommendation:${request.businessPackageId.value}:${request.id.value}:${candidates+1}`),candidate=new RecommendationCandidate({id,type,objective:input.properties.objective,businessPackageId:request.businessPackageId,evidence:input.properties.evidence,relatedOpportunities:input.opportunities,relatedPatterns:input.patterns,relatedPerformanceEvaluations:input.performanceEvaluations,relatedBusinessMemory:input.businessMemoryReferences,provenance:input.properties.provenance,createdAt:started});this.engine.registerCandidate(candidate);candidates++;this.report("PinterestRecommendationCandidateCreated",request,{recommendationId:id.value});
    const evaluation=this.engine.evaluateCandidate(candidate,{value:input.properties.estimatedValue,effort:input.properties.estimatedEffort,strategicRelevance:input.properties.strategicRelevance,timingSensitive:input.properties.timingSensitive});let recommendation=this.engine.createRecommendation(candidate,evaluation,this.clock());if(input.properties.recommendedWorkflow){recommendation=this.engine.repository.store(new BusinessRecommendation({...recommendation.properties,version:recommendation.version+1,recommendedWorkflow:input.properties.recommendedWorkflow,supersedesVersion:recommendation.version,supersessionReason:"Approved workflow reference attached"}));}
    if(type===RecommendationType.ResearchOpportunity){research++;this.report("PinterestResearchRecommendationCreated",request,{recommendationId:id.value});}if(type===RecommendationType.StrategicExperiment){experiments++;this.report("PinterestExperimentRecommendationCreated",request,{recommendationId:id.value});}
    if(evaluation.readyForCEOReview&&!input.evidenceGaps.length){recommendation=this.engine.markReadyForCEOReview(recommendation,`tco-review:${request.id.value}`,this.clock());ready++;this.report("PinterestRecommendationReadyForCEOReview",request,{recommendationId:id.value});}else deferred++;recommendations.push(recommendation);
   }
   const summary=new PinterestRecommendationEvaluationSummary(evaluated,eligible,candidates,ready,research,experiments,insufficient,rejected,contradicted,deferred),state=warnings.length?PinterestRecommendationEvaluationState.CompletedWithWarnings:PinterestRecommendationEvaluationState.Completed,result=new PinterestRecommendationEvaluationResult({evaluationId:request.id,businessPackageId:request.businessPackageId,state,opportunityReferences:request.opportunityReferences,recommendations,evidenceSets:sets,evidenceGaps:[...new Set(gaps)].sort(),warnings,summary,startedAt:started,completedAt:this.clock(),correlationIdentifier:request.properties.correlationIdentifier,provenance:inputs.map(x=>x.properties.provenance)});this.repository.store(result);this.transition(request,state,"PinterestRecommendationEvaluationCompleted");return result;
  }catch(error){this.transition(request,PinterestRecommendationEvaluationState.Failed,"PinterestRecommendationEvaluationFailed");throw error instanceof PinterestRecommendationEvaluationException?error:new PinterestRecommendationEvaluationException("Recommendation evaluation failed","PINTEREST_RECOMMENDATION_EVALUATION_FAILURE",{cause:error});}
 }
 private transition(request:PinterestRecommendationEvaluationRequest,state:PinterestRecommendationEvaluationState,name:string){this.repository.transition(request.id,state,this.clock());this.report(name,request,{state});}
 private report(name:string,request:PinterestRecommendationEvaluationRequest,extra:Record<string,string>){const at=this.clock(),context={evaluationId:request.id.value,businessPackageId:request.businessPackageId.value,...extra};this.events?.publish(new Event({id:new EventId(`pinterest-recommendation-${++this.#sequence}`),type:new EventType(name),timestamp:at,source:"PinterestRecommendationEvaluationWorkflow",correlationId:request.properties.correlationIdentifier,context:new EventContext(context)}));this.audit?.append(new AuditEvent({id:`pinterest-recommendation-audit-${++this.#sequence}`,timestamp:at,type:AuditEventType.WorkflowEvent,source:"PinterestRecommendationEvaluationWorkflow",action:name,result:extra.state??"Recorded",responsibleIdentity:request.properties.requestingAuthorityReference,relatedTaskOrWorkflowId:request.id.value,context}));}
}
