import type {BusinessRecommendation} from "../../business/recommendations/RecommendationDomain.ts";
import type {CEORecommendationDecisionRecord} from "../../business/recommendations/CEORecommendationReviewDomain.ts";
import {BusinessPackageId,Provenance} from "../../intelligence/market/MarketIntelligenceDomain.ts";

const required=(value:string,field:string)=>{if(typeof value!=="string"||!value.trim())throw new PinterestCreationPlanningException(`${field} is required`,"INVALID_PLAN");return value;};
const frozen=<T>(values:readonly T[])=>Object.freeze([...values]);
const instant=(value:Date,field:string)=>{const result=value instanceof Date?value.getTime():NaN;if(!Number.isFinite(result))throw new PinterestCreationPlanningException(`${field} is invalid`,"INVALID_PLAN");return result;};
export class PinterestCreationPlanningException extends Error{constructor(message:string,readonly code="PINTEREST_CREATION_PLANNING_FAILURE",options?:ErrorOptions){super(message,options);this.name="PinterestCreationPlanningException";}}
export class PinterestCreationPlanId{constructor(readonly value:string){required(value,"Creation Plan identifier");Object.freeze(this);}}
export class PinterestCreationPlanVersion{constructor(readonly value:number){if(!Number.isInteger(value)||value<1)throw new PinterestCreationPlanningException("Plan version must be positive","INVALID_VERSION");Object.freeze(this);}}
export enum PinterestCreationPlanState{Draft="Draft",Validated="Validated",ReadyForProduction="ReadyForProduction",Superseded="Superseded",Cancelled="Cancelled",Invalidated="Invalidated"}
export enum PinterestContentIntent{Educational="Educational",Discovery="Discovery",ProblemAwareness="ProblemAwareness",QuestionAnswer="QuestionAnswer",BookDiscovery="BookDiscovery",ArticleDiscovery="ArticleDiscovery",ProductDiscovery="ProductDiscovery",ResearchExperiment="ResearchExperiment",Other="Other"}
export enum PinterestDestinationType{ExistingArticle="ExistingArticle",ExistingBook="ExistingBook",ExistingProduct="ExistingProduct",ExistingLandingPage="ExistingLandingPage",FutureApprovedAsset="FutureApprovedAsset",ResearchOnly="ResearchOnly",Other="Other"}
export enum PinterestCTAObjective{ReadArticle="ReadArticle",ExploreBook="ExploreBook",ViewProduct="ViewProduct",LearnMore="LearnMore",DiscoverTopic="DiscoverTopic",VisitDestination="VisitDestination",ResearchExperiment="ResearchExperiment"}
export enum PinterestCreationConstraintType{CEOAuthorizedScope="CEOAuthorizedScope",Originality="Originality",NeverCopy="NeverCopy",Factual="Factual",ProhibitedClaim="ProhibitedClaim",BrandRule="BrandRule",LanguageRule="LanguageRule",AssetRule="AssetRule"}
export const NEVER_COPY=Object.freeze(["CopyCompetitorTitle","CloselyParaphraseCompetitorTitle","CopyCompetitorDescription","ReproduceCompetitorVisualComposition","ReproduceCompetitorBranding","ReproduceDistinctiveCompetitorWording","CloneCompetitorPin","UseCompetitorContentAsDirectTemplate"] as const);
export const ORIGINALITY_DIRECTION=Object.freeze(["CreateOriginalExpression","UseBusinessPackageVoice","UseEvidenceBackedTopic","UsePatternAsAbstractGuidance","DifferentiateFromObservedCompetitors"] as const);
export class PinterestCreationObjective{constructor(readonly recommendationObjectiveId:string,readonly description:string){required(recommendationObjectiveId,"Recommendation objective reference");required(description,"Creation objective");Object.freeze(this);}}
export interface PinterestKeywordDirection{primaryTopicTerm?:string;supportingTerms?:readonly string[];observedPhrases?:readonly string[];searchIntentContext?:string;trendContext?:string;searchVolume?:number;ctr?:number;competitionScore?:number;}
export class PinterestContentDirection{readonly supportingTerms;readonly observedPhrases;constructor(readonly topic:string,readonly keywords:PinterestKeywordDirection,readonly audience?:string,readonly market?:string,readonly region?:string,readonly language?:string){required(topic,"Topic");this.supportingTerms=frozen(keywords.supportingTerms??[]);this.observedPhrases=frozen(keywords.observedPhrases??[]);Object.freeze(keywords);Object.freeze(this);}}
export class PinterestDestinationContext{constructor(readonly type:PinterestDestinationType,readonly assetReference?:string,readonly canonicalUrl?:string){if(type!==PinterestDestinationType.ResearchOnly&&!assetReference)throw new PinterestCreationPlanningException("Destination asset reference is required","INVALID_DESTINATION");if(assetReference!==undefined)required(assetReference,"Destination asset reference");if(canonicalUrl!==undefined)required(canonicalUrl,"Canonical destination URL");Object.freeze(this);}}
export class PinterestCreationConstraint{constructor(readonly type:PinterestCreationConstraintType,readonly value:string,readonly sourceReference:string,readonly executable:boolean){required(value,"Constraint");required(sourceReference,"Constraint source");Object.freeze(this);}}
export class PinterestCopyDirection{readonly factualConstraints;readonly prohibitedClaims;readonly brandRuleReferences;constructor(readonly objective:string,readonly topic:string,readonly ctaObjective:PinterestCTAObjective,readonly destination:PinterestDestinationContext,readonly voiceReference?:string,readonly searchIntent?:string,factualConstraints:readonly string[]=[],prohibitedClaims:readonly string[]=[],brandRuleReferences:readonly string[]=[]){required(objective,"Copy objective");required(topic,"Copy topic");this.factualConstraints=frozen(factualConstraints);this.prohibitedClaims=frozen(prohibitedClaims);this.brandRuleReferences=frozen(brandRuleReferences);Object.freeze(this);}}
export class PinterestVisualDirection{readonly patternReferences;constructor(readonly mediaType?:string,readonly aspectRatio?:string,readonly compositionObjective?:string,readonly contentHierarchyObjective?:string,readonly brandReference?:string,readonly textOverlayAllowed?:boolean,readonly experimental=false,patternReferences:readonly string[]=[]){this.patternReferences=frozen(patternReferences);Object.freeze(this);}}
export class PinterestSuccessMeasurementPlan{readonly dimensions;constructor(dimensions:readonly string[],readonly baselineReference?:string,readonly targetReference?:string){if(!dimensions.length)throw new PinterestCreationPlanningException("Success measurement dimensions are required","INVALID_MEASUREMENT");this.dimensions=frozen(dimensions);Object.freeze(this);}}
export interface PinterestExperimentPlan{hypothesis:string;variableUnderTest:string;baselineReference?:string;successMetric:string;uncertainty?:string;evidenceReferences:readonly string[];}
export interface PinterestCreationPlanRequestProperties{id:PinterestCreationPlanId;businessPackageId:BusinessPackageId;recommendationId:string;recommendationVersion:number;ceoDecisionId:string;contentIntent:PinterestContentIntent;contentDirection:PinterestContentDirection;destination:PinterestDestinationContext;copyDirection:PinterestCopyDirection;visualDirection:PinterestVisualDirection;constraints?:readonly PinterestCreationConstraint[];measurementPlan:PinterestSuccessMeasurementPlan;competitiveEvidenceReferences?:readonly string[];performanceEvidenceReferences?:readonly string[];brandRuleReferences?:readonly string[];experiment?:PinterestExperimentPlan;machineReadableCEONoteConstraints?:readonly string[];correlationIdentifier:string;requestingAuthorityReference:string;requestedAt:Date;}
export class PinterestCreationPlanRequest{readonly constraints;readonly competitiveEvidenceReferences;readonly performanceEvidenceReferences;readonly brandRuleReferences;readonly machineReadableCEONoteConstraints;readonly #at:number;constructor(readonly properties:PinterestCreationPlanRequestProperties){required(properties.recommendationId,"Recommendation reference");required(properties.ceoDecisionId,"CEO decision reference");required(properties.correlationIdentifier,"Correlation identifier");required(properties.requestingAuthorityReference,"Requesting authority");this.#at=instant(properties.requestedAt,"Request timestamp");this.constraints=frozen(properties.constraints??[]);this.competitiveEvidenceReferences=frozen(properties.competitiveEvidenceReferences??[]);this.performanceEvidenceReferences=frozen(properties.performanceEvidenceReferences??[]);this.brandRuleReferences=frozen(properties.brandRuleReferences??[]);this.machineReadableCEONoteConstraints=frozen(properties.machineReadableCEONoteConstraints??[]);Object.freeze(this);}get id(){return this.properties.id;}get businessPackageId(){return this.properties.businessPackageId;}get requestedAt(){return new Date(this.#at);}}
export interface PinterestPatternGuidance{reference:string;version:number;status:string;confidence:number;stability:string;description:string;}
export interface PinterestLearningTrace{recommendationId:string;recommendationVersion:number;ceoDecisionId:string;opportunityReferences:readonly string[];patternReferences:readonly string[];evidenceReferences:readonly string[];creationHypothesis?:string;}
export class PinterestCreationPlan{readonly opportunityReferences;readonly patternGuidance;readonly evidenceReferences;readonly competitiveEvidenceReferences;readonly performanceEvidenceReferences;readonly constraints;readonly warnings;readonly learningTrace;readonly #created:number;constructor(readonly id:PinterestCreationPlanId,readonly version:PinterestCreationPlanVersion,readonly state:PinterestCreationPlanState,readonly businessPackageId:BusinessPackageId,readonly recommendation:BusinessRecommendation,readonly decision:CEORecommendationDecisionRecord,readonly objective:PinterestCreationObjective,readonly contentIntent:PinterestContentIntent,readonly contentDirection:PinterestContentDirection,readonly destination:PinterestDestinationContext,readonly copyDirection:PinterestCopyDirection,readonly visualDirection:PinterestVisualDirection,readonly measurementPlan:PinterestSuccessMeasurementPlan,constraints:readonly PinterestCreationConstraint[],competitive:readonly string[],performance:readonly string[],readonly experiment:PinterestExperimentPlan|undefined,readonly ambiguousCEONoteContext:string|undefined,readonly previousVersion:number|undefined,readonly versionReason:string|undefined,readonly correlationIdentifier:string,readonly provenance:Provenance,createdAt:Date,warnings:readonly string[]=[]){this.opportunityReferences=frozen(recommendation.relatedOpportunities.map(x=>x.id.value));this.patternGuidance=frozen(recommendation.relatedPatterns.map(x=>Object.freeze({reference:x.id.value,version:x.version,status:x.status,confidence:x.confidence.value,stability:x.stability,description:x.description})));this.evidenceReferences=frozen(recommendation.evidence.items.map(x=>x.evidence.id.value));this.competitiveEvidenceReferences=frozen(competitive);this.performanceEvidenceReferences=frozen(performance);this.constraints=frozen(constraints);this.warnings=frozen(warnings);this.learningTrace=Object.freeze({recommendationId:recommendation.id.value,recommendationVersion:recommendation.version,ceoDecisionId:decision.decisionId,opportunityReferences:this.opportunityReferences,patternReferences:this.patternGuidance.map(x=>x.reference),evidenceReferences:this.evidenceReferences,creationHypothesis:experiment?.hypothesis});this.#created=instant(createdAt,"Plan creation timestamp");Object.freeze(this);}get createdAt(){return new Date(this.#created);}}
export class PinterestCreationPlanResult{constructor(readonly plan:PinterestCreationPlan){Object.freeze(this);}get planIdentifier(){return this.plan.id;}get planVersion(){return this.plan.version;}get state(){return this.plan.state;}}
