import type { CompetitiveAnalysis, CompetitiveGap } from "../../business/market/competitive/CompetitiveIntelligenceDomain.ts";
import type { MarketOpportunity, OpportunityType } from "../../business/market/opportunities/OpportunityIntelligenceDomain.ts";
import type { MarketPattern } from "../../business/market/patterns/PatternIntelligenceDomain.ts";
import { BusinessPackageId, Confidence, Evidence, Freshness, Provenance } from "../../intelligence/market/MarketIntelligenceDomain.ts";

export class PinterestOpportunityEvaluationException extends Error { constructor(message:string,readonly code="PINTEREST_OPPORTUNITY_EVALUATION_FAILURE",options?:ErrorOptions){super(message,options);this.name="PinterestOpportunityEvaluationException";} }
const required=(v:string,n:string)=>{if(typeof v!=="string"||!v.trim())throw new PinterestOpportunityEvaluationException(`${n} is required`,"INVALID_REQUEST");return v;};
const instant=(v:Date,n:string)=>{if(!(v instanceof Date)||!Number.isFinite(v.getTime()))throw new PinterestOpportunityEvaluationException(`${n} is invalid`,"INVALID_REQUEST");return v.getTime();};
const frozen=<T>(v:readonly T[])=>Object.freeze([...v]);
export class PinterestOpportunityEvaluationId { constructor(readonly value:string){required(value,"Evaluation identifier");Object.freeze(this);} }
export enum PinterestOpportunityEvaluationState { Requested="Requested",Started="Started",Completed="Completed",CompletedWithWarnings="CompletedWithWarnings",Failed="Failed" }
export enum PinterestBusinessRelevance { Relevant="Relevant",Partial="Partial",Irrelevant="Irrelevant",Unknown="Unknown" }
export enum PinterestAssetFit { RelevantAssetExists="RelevantAssetExists",RelevantAssetPartial="RelevantAssetPartial",RelevantAssetMissing="RelevantAssetMissing",Unknown="Unknown" }
export enum PinterestEvidenceGap { UnknownDemand="UnknownDemand",UnknownPerformance="UnknownPerformance",InsufficientCompetitiveEvidence="InsufficientCompetitiveEvidence",UnknownAssetFit="UnknownAssetFit",InsufficientFreshness="InsufficientFreshness",UnknownCrossMarketValidity="UnknownCrossMarketValidity" }
export enum PinterestOpportunityRejectionReason { InsufficientEvidence="InsufficientEvidence",InsufficientBusinessRelevance="InsufficientBusinessRelevance",PatternTooWeak="PatternTooWeak",PatternContradicted="PatternContradicted",EvidenceTooStale="EvidenceTooStale",NoMarketGap="NoMarketGap",AlreadyAddressed="AlreadyAddressed",UnsupportedContext="UnsupportedContext",Other="Other" }

export interface PinterestOpportunityEvaluationRequestProperties { id:PinterestOpportunityEvaluationId;businessPackageId:BusinessPackageId;patternReferences:readonly string[];competitiveGapReferences?:readonly string[];competitiveAnalysisReferences?:readonly string[];marketContext:string;regionContext?:string;languageContext:string;windowStart:Date;windowEnd:Date;correlationIdentifier:string;requestingAuthorityReference:string;requestedAt:Date; }
export class PinterestOpportunityEvaluationRequest { readonly patternReferences;readonly competitiveGapReferences;readonly competitiveAnalysisReferences;readonly #start;readonly #end;readonly #at;constructor(readonly properties:PinterestOpportunityEvaluationRequestProperties){required(properties.marketContext,"Market context");required(properties.languageContext,"Language context");required(properties.correlationIdentifier,"Correlation identifier");required(properties.requestingAuthorityReference,"Requesting authority");if(!properties.patternReferences.length)throw new PinterestOpportunityEvaluationException("At least one Pattern reference is required","INVALID_REQUEST");this.#start=instant(properties.windowStart,"Window start");this.#end=instant(properties.windowEnd,"Window end");this.#at=instant(properties.requestedAt,"Request timestamp");if(this.#end<this.#start)throw new PinterestOpportunityEvaluationException("Evaluation window is invalid","INVALID_REQUEST");this.patternReferences=frozen([...new Set(properties.patternReferences)].sort());this.competitiveGapReferences=frozen([...new Set(properties.competitiveGapReferences??[])].sort());this.competitiveAnalysisReferences=frozen([...new Set(properties.competitiveAnalysisReferences??[])].sort());Object.freeze(this);}get id(){return this.properties.id;}get windowStart(){return new Date(this.#start);}get windowEnd(){return new Date(this.#end);}get requestedAt(){return new Date(this.#at);} }

export interface PinterestOpportunityCandidateInputProperties { pattern:MarketPattern;opportunityType:OpportunityType;businessRelevance:PinterestBusinessRelevance;relevanceEvidence:readonly Evidence[];assetFit:PinterestAssetFit;assetContextEvidence?:readonly Evidence[];performanceContextEvidence?:readonly Evidence[];competitiveGaps?:readonly CompetitiveGap[];competitiveAnalyses?:readonly CompetitiveAnalysis[];saturationEvidence?:readonly Evidence[];evidenceGaps?:readonly PinterestEvidenceGap[]; }
export class PinterestOpportunityCandidateInput { readonly relevanceEvidence;readonly assetContextEvidence;readonly performanceContextEvidence;readonly competitiveGaps;readonly competitiveAnalyses;readonly saturationEvidence;readonly evidenceGaps;constructor(readonly properties:PinterestOpportunityCandidateInputProperties){this.relevanceEvidence=frozen(properties.relevanceEvidence);this.assetContextEvidence=frozen(properties.assetContextEvidence??[]);this.performanceContextEvidence=frozen(properties.performanceContextEvidence??[]);this.competitiveGaps=frozen(properties.competitiveGaps??[]);this.competitiveAnalyses=frozen(properties.competitiveAnalyses??[]);this.saturationEvidence=frozen(properties.saturationEvidence??[]);this.evidenceGaps=frozen(properties.evidenceGaps??[]);Object.freeze(this);}get pattern(){return this.properties.pattern;} }
export class PinterestOpportunityEvidenceSet { readonly patternReferences;readonly competitiveGapReferences;readonly supportingEvidence;readonly contradictingEvidence;readonly relevanceEvidence;readonly assetContextEvidence;readonly performanceContextEvidence;readonly marketContexts;readonly provenances;constructor(patternReferences:readonly string[],gapReferences:readonly string[],supporting:readonly Evidence[],contradicting:readonly Evidence[],relevance:readonly Evidence[],asset:readonly Evidence[],performance:readonly Evidence[],readonly independentObservationCount:number,readonly evidenceQuality:Confidence,readonly freshness:Freshness,contexts:readonly string[],provenances:readonly Provenance[]){this.patternReferences=frozen(patternReferences);this.competitiveGapReferences=frozen(gapReferences);this.supportingEvidence=frozen(supporting);this.contradictingEvidence=frozen(contradicting);this.relevanceEvidence=frozen(relevance);this.assetContextEvidence=frozen(asset);this.performanceContextEvidence=frozen(performance);this.marketContexts=frozen([...new Set(contexts)].sort());this.provenances=frozen(provenances);Object.freeze(this);} }
export class PinterestOpportunityEvaluationSummary { constructor(readonly patternsEvaluated:number,readonly patternsEligible:number,readonly candidatesCreated:number,readonly qualifiedOpportunities:number,readonly emergingOpportunities:number,readonly weakOpportunities:number,readonly rejectedCandidates:number,readonly staleCandidates:number,readonly contradictedCandidates:number,readonly assetGapsDetected:number,readonly evidenceGapsDetected:number){Object.freeze(this);} }
export interface PinterestOpportunityEvaluationResultProperties { evaluationId:PinterestOpportunityEvaluationId;businessPackageId:BusinessPackageId;state:PinterestOpportunityEvaluationState;evaluatedPatternReferences:readonly string[];opportunities:readonly MarketOpportunity[];statuses:readonly string[];confidence:Confidence;evidenceSets:readonly PinterestOpportunityEvidenceSet[];relevanceStates:readonly PinterestBusinessRelevance[];assetFitStates:readonly PinterestAssetFit[];evidenceGaps:readonly PinterestEvidenceGap[];warnings:readonly string[];rejectionReasons:readonly PinterestOpportunityRejectionReason[];summary:PinterestOpportunityEvaluationSummary;startedAt:Date;completedAt:Date;correlationIdentifier:string;provenance:readonly Provenance[]; }
export class PinterestOpportunityEvaluationResult { readonly evaluatedPatternReferences;readonly opportunities;readonly statuses;readonly evidenceSets;readonly relevanceStates;readonly assetFitStates;readonly evidenceGaps;readonly warnings;readonly rejectionReasons;readonly provenance;readonly #started;readonly #completed;constructor(readonly properties:PinterestOpportunityEvaluationResultProperties){this.#started=instant(properties.startedAt,"Start timestamp");this.#completed=instant(properties.completedAt,"Completion timestamp");this.evaluatedPatternReferences=frozen(properties.evaluatedPatternReferences);this.opportunities=frozen(properties.opportunities);this.statuses=frozen(properties.statuses);this.evidenceSets=frozen(properties.evidenceSets);this.relevanceStates=frozen(properties.relevanceStates);this.assetFitStates=frozen(properties.assetFitStates);this.evidenceGaps=frozen(properties.evidenceGaps);this.warnings=frozen(properties.warnings);this.rejectionReasons=frozen(properties.rejectionReasons);this.provenance=frozen(properties.provenance);Object.freeze(properties);Object.freeze(this);}get summary(){return this.properties.summary;}get confidence(){return this.properties.confidence;}get startedAt(){return new Date(this.#started);}get completedAt(){return new Date(this.#completed);} }
