import { AuditEvent } from "../../core/platform/AuditEvent.ts";
import { AuditEventType } from "../../core/platform/AuditEventType.ts";
import type { AuditRecorder } from "../../core/platform/AuditRecorder.ts";
import { Event } from "../../core/platform/Event.ts";
import type { EventBus } from "../../core/platform/EventBus.ts";
import { EventContext } from "../../core/platform/EventContext.ts";
import { EventId } from "../../core/platform/EventId.ts";
import { EventType } from "../../core/platform/EventType.ts";
import { PatternCandidate, PatternDecay, PatternDirection, PatternEvidenceRole, PatternId, PatternStatus } from "../../business/market/patterns/PatternIntelligenceDomain.ts";
import type { PatternIntelligenceService } from "../../business/market/patterns/PatternIntelligenceService.ts";
import { FreshnessStatus } from "../../intelligence/market/MarketIntelligenceDomain.ts";
import { MarketDuplicateAssessment } from "../../intelligence/market/quality/MarketDataQualityDomain.ts";
import { PinterestPatternCandidateInput, PinterestPatternEvaluationException, PinterestPatternEvaluationRequest, PinterestPatternEvaluationResult, PinterestPatternEvaluationState, PinterestPatternEvaluationSummary, PinterestPatternEvidenceSet, PinterestPerformanceAssociation } from "./PinterestPatternEvaluationDomain.ts";
import { PinterestPatternEvaluationRepository } from "./PinterestPatternEvaluationRepository.ts";

/** TCO-invoked, synchronous evaluation only; this workflow performs no collection, scheduling or promotion. */
export class PinterestPatternEvaluationWorkflow {
 #sequence=0;
 constructor(private readonly intelligence:PatternIntelligenceService,readonly repository=new PinterestPatternEvaluationRepository(),private readonly events?:EventBus,private readonly audit?:AuditRecorder,private readonly clock=()=>new Date()){}
 evaluate(request:PinterestPatternEvaluationRequest,inputs:readonly PinterestPatternCandidateInput[]):PinterestPatternEvaluationResult{
  if(this.repository.result(request.id))throw new PinterestPatternEvaluationException("Evaluation already completed","IMMUTABLE_EVALUATION_RESULT");const started=this.clock();this.transition(request,PinterestPatternEvaluationState.Requested,"PinterestPatternEvaluationRequested");this.transition(request,PinterestPatternEvaluationState.Started,"PinterestPatternEvaluationStarted");
  try {const eligible=inputs.filter(input=>{const p=input.properties;return request.requestedDimensions.includes(p.dimension)&&p.observation.businessPackageId?.value===request.properties.businessPackageId.value&&(!p.analysis||p.analysis.businessPackageId?.value===request.properties.businessPackageId.value)&&p.observedAt>=request.windowStart&&p.observedAt<=request.windowEnd;});if(eligible.length!==inputs.length&&inputs.some(x=>x.properties.observation.businessPackageId?.value!==request.properties.businessPackageId.value))throw new PinterestPatternEvaluationException("Inputs cross Business Package boundary","PACKAGE_MISMATCH");
   const groups=new Map<string,PinterestPatternCandidateInput[]>();for(const input of eligible){const key=`${input.properties.dimension}|${input.properties.characteristic.trim().toLocaleLowerCase("en-US")}`;const group=groups.get(key)??[];group.push(input);groups.set(key,group);}const patterns=[];const sets:PinterestPatternEvidenceSet[]=[];const associations:PinterestPerformanceAssociation[]=[];const references:string[]=[];const warnings:string[]=[];let insufficient=0,duplicates=0,negative=0,contradicted=0,decaying=0,supported=0;
   for(const [key,unordered] of [...groups].sort(([a],[b])=>a.localeCompare(b))){const items=[...unordered].sort((a,b)=>a.observedAt.getTime()-b.observedAt.getTime()||a.properties.observation.id.value.localeCompare(b.properties.observation.id.value)||a.properties.evidence.id.value.localeCompare(b.properties.evidence.id.value));const reference=`pinterest-pattern:${request.properties.businessPackageId.value}:${request.id.value}:${key}`;references.push(reference);this.report("PinterestPatternCandidateDetected",request,{candidateReference:reference});
    const seen=new Set<string>();let independent=0,duplicateCount=0,probable=false;for(const item of items){const p=item.properties;if(p.duplicateAssessment===MarketDuplicateAssessment.ExactDuplicate){duplicateCount++;continue;}if(p.duplicateAssessment===MarketDuplicateAssessment.ProbableDuplicate)probable=true;const identity=p.duplicateGroupReference??p.observation.marketObservation.id.value;if(!seen.has(identity)){seen.add(identity);independent++;}else duplicateCount++;}duplicates+=duplicateCount;
    const pos=items.filter(x=>x.properties.performanceAssociation===PinterestPerformanceAssociation.Positive),neg=items.filter(x=>x.properties.performanceAssociation===PinterestPerformanceAssociation.Negative),unknown=items.filter(x=>x.properties.performanceAssociation===PinterestPerformanceAssociation.UnknownPerformanceAssociation);let direction=PatternDirection.Neutral;if(pos.length&&neg.length)direction=PatternDirection.Contradictory;else if(pos.length)direction=PatternDirection.Positive;else if(neg.length)direction=PatternDirection.Negative;const roles=new Map<string,PatternEvidenceRole>();for(const item of items)roles.set(item.properties.evidence.id.value,direction===PatternDirection.Contradictory&&item.properties.performanceAssociation===PinterestPerformanceAssociation.Negative?PatternEvidenceRole.Contradicting:item.properties.performanceAssociation===PinterestPerformanceAssociation.UnknownPerformanceAssociation?PatternEvidenceRole.Neutral:PatternEvidenceRole.Supporting);
    const observations=[...new Map(items.map(x=>[x.properties.observation.marketObservation.id.value,x.properties.observation.marketObservation])).values()],evidence=[...new Map(items.map(x=>[x.properties.evidence.id.value,x.properties.evidence])).values()],analyses=[...new Map(items.flatMap(x=>x.properties.analysis?[[x.properties.analysis.id.value,x.properties.analysis] as const]:[])).values()];const candidate=new PatternCandidate(new PatternId(reference),items[0].properties.patternType,`${items[0].properties.dimension}: ${items[0].properties.characteristic}`,request.properties.businessPackageId,evidence,observations,analyses,items[0].observedAt,items.at(-1)!.observedAt);this.intelligence.registerCandidate(candidate);let pattern=this.intelligence.evaluateCandidate(candidate,direction,roles,this.clock());
    const supporting=items.filter(x=>roles.get(x.properties.evidence.id.value)===PatternEvidenceRole.Supporting).map(x=>x.properties.evidence),conflicting=items.filter(x=>roles.get(x.properties.evidence.id.value)===PatternEvidenceRole.Contradicting).map(x=>x.properties.evidence);sets.push(new PinterestPatternEvidenceSet(reference,evidence.length,independent,duplicateCount,supporting,conflicting,pattern.freshness,items.map(x=>x.properties.duplicateAssessment),items.map(x=>x.properties.marketContext),items.map(x=>x.properties.provenance),probable));associations.push(direction===PatternDirection.Positive?PinterestPerformanceAssociation.Positive:direction===PatternDirection.Negative?PinterestPerformanceAssociation.Negative:PinterestPerformanceAssociation.UnknownPerformanceAssociation);
    if(independent<2){insufficient++;warnings.push(`${reference}: insufficient independent evidence`);this.report("PinterestPatternInsufficientEvidence",request,{candidateReference:reference});}else {try{pattern=this.intelligence.verifyEligible(pattern.id,request.properties.businessPackageId,this.clock());supported++;this.report("PinterestPatternConfirmed",request,{candidateReference:reference});}catch{this.report("PinterestPatternEmerging",request,{candidateReference:reference});}}if(direction===PatternDirection.Negative){negative++;this.report("PinterestNegativePatternDetected",request,{candidateReference:reference});}if(direction===PatternDirection.Contradictory){contradicted++;this.report("PinterestPatternContradicted",request,{candidateReference:reference});}if(pattern.decay!==PatternDecay.None){decaying++;this.report("PinterestPatternDecaying",request,{candidateReference:reference});}patterns.push(pattern);
   }
   const uniqueObservations=new Set(eligible.map(x=>x.properties.observation.id.value)).size,uniqueAnalyses=new Set(eligible.flatMap(x=>x.properties.analysis?[x.properties.analysis.id.value]:[])).size;const summary=new PinterestPatternEvaluationSummary({competitiveObservationsEvaluated:uniqueObservations,analysesEvaluated:uniqueAnalyses,candidateCharacteristicsFound:groups.size,candidatesRejected:inputs.length-eligible.length,emergingPatterns:patterns.filter(x=>x.status===PatternStatus.Observed).length,supportedOrConfirmedPatterns:supported,negativePatterns:negative,contradictedPatterns:contradicted,decayingPatterns:decaying,duplicateEvidenceExcludedFromIndependenceCount:duplicates,insufficientEvidenceCandidates:insufficient});const state=warnings.length?PinterestPatternEvaluationState.CompletedWithWarnings:PinterestPatternEvaluationState.Completed;const result=new PinterestPatternEvaluationResult({evaluationId:request.id,businessPackageId:request.properties.businessPackageId,state,evaluatedCandidateReferences:references,patterns,statuses:patterns.map(x=>x.status),evidenceSets:sets,associations,summary,warnings,failures:[],startedAt:started,completedAt:this.clock(),correlationIdentifier:request.properties.correlationIdentifier});this.repository.store(result);this.transition(request,state,"PinterestPatternEvaluationCompleted");return result;
  } catch(error){this.transition(request,PinterestPatternEvaluationState.Failed,"PinterestPatternEvaluationFailed");throw error instanceof PinterestPatternEvaluationException?error:new PinterestPatternEvaluationException("Pattern evaluation failed","PINTEREST_PATTERN_EVALUATION_FAILURE",{cause:error});}
 }
 private transition(request:PinterestPatternEvaluationRequest,state:PinterestPatternEvaluationState,name:string){const at=this.clock();this.repository.transition(request.id,state,at);this.report(name,request,{state});}
 private report(name:string,request:PinterestPatternEvaluationRequest,extra:Record<string,string>={}){const at=this.clock(),context={evaluationId:request.id.value,businessPackageId:request.properties.businessPackageId.value,...extra};this.events?.publish(new Event({id:new EventId(`pinterest-pattern-evaluation-${++this.#sequence}`),type:new EventType(name),timestamp:at,source:"PinterestPatternEvaluationWorkflow",correlationId:request.properties.correlationIdentifier,context:new EventContext(context)}));this.audit?.append(new AuditEvent({id:`pinterest-pattern-evaluation-audit-${++this.#sequence}`,timestamp:at,type:AuditEventType.WorkflowEvent,source:"PinterestPatternEvaluationWorkflow",action:name,result:extra.state??"Recorded",responsibleIdentity:request.properties.requestingAuthorityReference,relatedTaskOrWorkflowId:request.id.value,context}));}
}
