import { AuditEvent } from "../../core/platform/AuditEvent.ts";
import { AuditEventType } from "../../core/platform/AuditEventType.ts";
import type { AuditRecorder } from "../../core/platform/AuditRecorder.ts";
import { Event } from "../../core/platform/Event.ts";
import type { EventBus } from "../../core/platform/EventBus.ts";
import { EventContext } from "../../core/platform/EventContext.ts";
import { EventId } from "../../core/platform/EventId.ts";
import { EventType } from "../../core/platform/EventType.ts";
import { MarketSourceId, Provenance } from "../../intelligence/market/MarketIntelligenceDomain.ts";
import type { MarketIntelligenceService } from "../../intelligence/market/MarketIntelligenceService.ts";
import { MarketCollectionRequest, MarketCollectionResultStatus, MarketNormalizationStatus, MarketSourceCapability, MarketSourceFailureCategory, MarketSourceState } from "../../intelligence/market/integration/MarketSourceIntegrationDomain.ts";
import type { MarketSourceRegistry } from "../../intelligence/market/integration/MarketSourceIntegrationService.ts";
import { MarketDataAcceptanceDecision, MarketDataValidationId, MarketDataValidationRequest, MarketDuplicateAssessment } from "../../intelligence/market/quality/MarketDataQualityDomain.ts";
import type { MarketDataQualityPolicy, MarketDataValidationResult } from "../../intelligence/market/quality/MarketDataQualityDomain.ts";
import type { FieldValue, MarketDataQualityService } from "../../intelligence/market/quality/MarketDataQualityService.ts";
import { PinterestCapabilityState, PinterestConnectionVerificationId, PinterestConnectionVerificationRequest, PinterestConnectionState } from "./PinterestConnectionVerificationDomain.ts";
import type { PinterestConnectionVerificationResult } from "./PinterestConnectionVerificationDomain.ts";
import type { PinterestConnectionVerifier } from "./PinterestConnectionVerifier.ts";
import type { PinterestMarketSourceAdapter } from "./PinterestMarketSourceAdapter.ts";
import { PinterestObservationCollectionScope, PinterestObservationCollectionSummary, PinterestObservationWorkflowException, PinterestObservationWorkflowRequest, PinterestObservationWorkflowResult, PinterestObservationWorkflowState } from "./PinterestObservationWorkflowDomain.ts";
import type { PinterestObservationDisposition } from "./PinterestObservationWorkflowDomain.ts";
import { PinterestObservationWorkflowRepository } from "./PinterestObservationWorkflowRepository.ts";

const SCOPE_CAPABILITIES:Readonly<Record<PinterestObservationCollectionScope,readonly string[]>>=Object.freeze({
  [PinterestObservationCollectionScope.OwnedPins]:["OwnPins","MarketObservation"],
  [PinterestObservationCollectionScope.OwnedBoards]:["OwnBoards"],
  [PinterestObservationCollectionScope.OwnedAnalytics]:["AnalyticsObservation","PerformanceObservation"],
  [PinterestObservationCollectionScope.TopPins]:["OwnPins","AnalyticsObservation","PerformanceObservation"],
  [PinterestObservationCollectionScope.PublicPins]:["MarketObservation"],
  [PinterestObservationCollectionScope.PublicBoards]:["MarketObservation"],
  [PinterestObservationCollectionScope.Trends]:["TrendObservation"],
  [PinterestObservationCollectionScope.OtherReadOnly]:[],
});
type ExecutionOutcome=PinterestObservationWorkflowResult|PinterestObservationWorkflowState;

/** Governed integration workflow. Scheduling, retry and fallback decisions remain with TCO. */
export class PinterestObservationWorkflow {
  #sequence=0;
  constructor(private readonly registry:MarketSourceRegistry,private readonly verifier:Pick<PinterestConnectionVerifier,"verify">,private readonly quality:MarketDataQualityService,private readonly qualityPolicy:(request:PinterestObservationWorkflowRequest)=>MarketDataQualityPolicy,private readonly intelligence:MarketIntelligenceService,readonly repository=new PinterestObservationWorkflowRepository(),private readonly events?:EventBus,private readonly audit?:AuditRecorder,private readonly clock=()=>new Date()){}
  request(request:PinterestObservationWorkflowRequest){if(this.repository.history(request.id).length)throw new PinterestObservationWorkflowException("Workflow already exists");this.transition(request,PinterestObservationWorkflowState.Requested,"PinterestObservationWorkflowRequested");return request.id;}
  run(request:PinterestObservationWorkflowRequest):Promise<ExecutionOutcome>{if(!this.repository.history(request.id).length)this.request(request);return this.execute(request,false);}
  manualRun(request:PinterestObservationWorkflowRequest):Promise<ExecutionOutcome>{if(!request.properties.manual)throw new PinterestObservationWorkflowException("Manual run requires explicit CEO/TCO authorization");return this.run(request);}
  resume(request:PinterestObservationWorkflowRequest):Promise<ExecutionOutcome>{const current=this.repository.history(request.id).at(-1)?.state;if(current!==PinterestObservationWorkflowState.WaitingForCredentialCorrection&&current!==PinterestObservationWorkflowState.WaitingForReauthorization&&current!==PinterestObservationWorkflowState.Paused&&current!==PinterestObservationWorkflowState.RateLimited)throw new PinterestObservationWorkflowException("Workflow is not resumable");this.transition(request,PinterestObservationWorkflowState.ValidatingConfiguration,"PinterestObservationWorkflowResumed");return this.execute(request,true);}
  pause(request:PinterestObservationWorkflowRequest){this.transition(request,PinterestObservationWorkflowState.Paused,"PinterestObservationWorkflowPaused");}
  cancel(request:PinterestObservationWorkflowRequest){this.transition(request,PinterestObservationWorkflowState.Cancelled,"PinterestObservationWorkflowCancelled");}

  private async execute(request:PinterestObservationWorkflowRequest,resuming:boolean):Promise<ExecutionOutcome>{
    const started=this.clock();if(!resuming)this.transition(request,PinterestObservationWorkflowState.ValidatingConfiguration,"PinterestObservationWorkflowStarted");
    const descriptor=this.registry.descriptor(request.properties.adapterId),adapter=this.registry.adapter(request.properties.adapterId) as PinterestMarketSourceAdapter|undefined;
    const allowed=SCOPE_CAPABILITIES[request.properties.scope];
    if(!descriptor||!adapter||descriptor.source.id.value!=="Pinterest"||descriptor.state!==MarketSourceState.Available)return this.finishFailure(request,started,"Pinterest source is not available");
    if(descriptor.properties.credentialId?.value!==request.properties.credentialId.value||!descriptor.authorized(request.properties.businessPackageId,request.properties.capability))return this.finishFailure(request,started,"Credential or capability is not scoped to this Business Package");
    if(!allowed.includes(request.properties.capability.value))return this.finishFailure(request,started,"Collection scope does not map to the requested adapter capability");
    this.transition(request,PinterestObservationWorkflowState.VerifyingCapability,"PinterestObservationCapabilityVerificationStarted");
    const verification=await this.verifier.verify(new PinterestConnectionVerificationRequest({id:new PinterestConnectionVerificationId(`workflow-verification:${request.id.value}:${this.repository.history(request.id).length}`),adapterId:request.properties.adapterId,credentialId:request.properties.credentialId,businessPackageId:request.properties.businessPackageId,requestedCapabilities:[request.properties.capability],requestingAuthorityReference:request.properties.requestingAuthorityReference,correlationIdentifier:request.properties.correlationIdentifier,requestedAt:this.clock()}));
    const blocked=this.preflightState(verification);
    if(blocked){this.transition(request,blocked,blocked===PinterestObservationWorkflowState.WaitingForCredentialCorrection?"PinterestObservationWaitingForCredentialCorrection":blocked===PinterestObservationWorkflowState.RateLimited?"PinterestObservationRateLimited":"PinterestObservationWorkflowFailed");return blocked;}
    this.transition(request,PinterestObservationWorkflowState.Ready,"PinterestObservationWorkflowReady");this.transition(request,PinterestObservationWorkflowState.Collecting,"PinterestObservationCollectionStarted");
    const collectionRequest=new MarketCollectionRequest({id:`pinterest-workflow-collection:${request.id.value}`,capability:request.properties.capability,businessPackageId:request.properties.businessPackageId,marketContext:request.properties.marketContext??"global",languageContext:request.properties.languageContext,subjectReference:request.properties.queryOrSubjectReference,windowStart:request.windowStart,windowEnd:request.windowEnd,freshness:request.properties.freshness,correlationId:request.properties.correlationIdentifier,workflowOrTcoReference:request.id.value,requestedAt:this.clock()});
    const collection=await adapter.collect(collectionRequest);const results=[collection];
    if(collection.status===MarketCollectionResultStatus.NoData){this.transition(request,PinterestObservationWorkflowState.NoData,"PinterestObservationNoData");return this.finish(request,started,PinterestObservationWorkflowState.NoData,results,[],[],[],[],[],[],0,0);}
    if(collection.status===MarketCollectionResultStatus.Failed&&collection.failure?.category===MarketSourceFailureCategory.AuthenticationFailure){const state=PinterestObservationWorkflowState.WaitingForReauthorization;this.transition(request,state,"PinterestObservationWaitingForCredentialCorrection");return state;}
    const partial=collection.status===MarketCollectionResultStatus.Partial,rateLimited=collection.status===MarketCollectionResultStatus.RateLimited||collection.failure?.category===MarketSourceFailureCategory.RateLimited;
    if(partial)this.transition(request,PinterestObservationWorkflowState.PartiallyCollected,"PinterestObservationCollectionPartial");
    const raw=collection.rawRecords.slice(0,request.properties.maximumRecords);if(!raw.length&&collection.status!==MarketCollectionResultStatus.Success)return this.finishFailure(request,started,collection.failure?.message??"Pinterest collection failed",results,collection.rateLimit);
    this.transition(request,PinterestObservationWorkflowState.Normalizing,"PinterestObservationNormalizationStarted");
    const accepted=[];const quarantined:PinterestObservationDisposition[]=[];const rejected:PinterestObservationDisposition[]=[];const historical:PinterestObservationDisposition[]=[];const warnings:string[]=[];const failures:string[]=[];let normalized=0,normalizationFailures=0,validationFailures=0,duplicates=0,acceptedWarning=0;
    for(const record of raw){const normalization=await adapter.normalize(record);if(!normalization.observation||![MarketNormalizationStatus.Normalized,MarketNormalizationStatus.PartiallyNormalized].includes(normalization.status)){normalizationFailures++;rejected.push({reason:normalization.validationFailures.join("; ")||"Normalization failed"});continue;}normalized++;this.transition(request,PinterestObservationWorkflowState.ValidatingData,"PinterestObservationValidationStarted");let validation:MarketDataValidationResult;try{const fields:Record<string,FieldValue>={subject:{state:"Value",value:normalization.observation.subject},payloadReference:{state:"Value",value:normalization.observation.payloadReference}};validation=this.quality.validate(new MarketDataValidationRequest({id:new MarketDataValidationId(`pinterest-workflow-validation:${request.id.value}:${record.id}`),normalization,observation:normalization.observation,rawRecord:record,source:descriptor.source,businessPackageId:request.properties.businessPackageId,policy:this.qualityPolicy(request),requestedAt:this.clock(),correlationId:request.properties.correlationIdentifier,provenance:normalization.provenance,adapterReference:descriptor.adapterId.value,collectionRequestReference:collection.requestId,collectionResultReference:`${request.id.value}:${collection.collectedAt.toISOString()}`}),fields,request.properties.requestingAuthorityReference);}catch(error){validationFailures++;failures.push(error instanceof Error?error.message:"Validation failed");continue;}if(validation.duplicateAssessment!==MarketDuplicateAssessment.IndependentRecord)duplicates++;
      const disposition={observation:normalization.observation,validation,reason:validation.acceptance};
      if(validation.acceptance===MarketDataAcceptanceDecision.Accepted||validation.acceptance===MarketDataAcceptanceDecision.AcceptedWithWarnings){if(validation.duplicateAssessment===MarketDuplicateAssessment.IndependentRecord){this.transition(request,PinterestObservationWorkflowState.RegisteringObservations,"PinterestObservationAccepted");this.intelligence.registerObservation(normalization.observation);accepted.push(normalization.observation);if(validation.acceptance===MarketDataAcceptanceDecision.AcceptedWithWarnings)acceptedWarning++;}else warnings.push(`Duplicate observation was not registered: ${normalization.observation.id.value}`);}
      else if(validation.acceptance===MarketDataAcceptanceDecision.Quarantined){quarantined.push(disposition);this.report("PinterestObservationQuarantined",request,{recordId:record.id});}
      else if(validation.acceptance===MarketDataAcceptanceDecision.Rejected){rejected.push(disposition);this.report("PinterestObservationRejected",request,{recordId:record.id});}
      else historical.push(disposition);
    }
    if(collection.failure)warnings.push(collection.failure.message);if(rateLimited)this.report("PinterestObservationRateLimited",request);
    const final=rateLimited&&!raw.length?PinterestObservationWorkflowState.RateLimited:partial||rateLimited||warnings.length||failures.length||quarantined.length||rejected.length||historical.length||normalizationFailures||validationFailures?PinterestObservationWorkflowState.CompletedWithWarnings:PinterestObservationWorkflowState.Completed;
    return this.finish(request,started,final,results,accepted,quarantined,rejected,historical,warnings,failures,normalized,normalizationFailures,validationFailures,duplicates,acceptedWarning,collection.rateLimit);
  }
  private preflightState(result:PinterestConnectionVerificationResult){if(result.properties.authenticationState==="CredentialCorrectionRequired")return PinterestObservationWorkflowState.WaitingForCredentialCorrection;if(result.properties.authenticationState==="ReauthorizationRequired"||result.properties.authenticationState==="MFARequired")return PinterestObservationWorkflowState.WaitingForReauthorization;const capability=result.capabilities[0];if(result.state===PinterestConnectionState.RateLimited||capability?.state===PinterestCapabilityState.RateLimited)return PinterestObservationWorkflowState.RateLimited;if(result.state!==PinterestConnectionState.Available||capability?.state!==PinterestCapabilityState.Available)return PinterestObservationWorkflowState.Failed;return undefined;}
  private finishFailure(request:PinterestObservationWorkflowRequest,started:Date,message:string,collections:any[]=[],rateLimit?:any){return this.finish(request,started,PinterestObservationWorkflowState.Failed,collections,[],[],[],[],[],[message],0,0,0,0,0,rateLimit);}
  private finish(request:PinterestObservationWorkflowRequest,started:Date,state:PinterestObservationWorkflowState,collections:any[],accepted:any[],quarantined:PinterestObservationDisposition[],rejected:PinterestObservationDisposition[],historical:PinterestObservationDisposition[],warnings:string[],failures:string[],normalized:number,normalizationFailures:number,validationFailures=0,duplicates=0,acceptedWarning=0,rateLimit?:any){const at=this.clock(),raw=collections.reduce((n,c)=>n+c.rawRecords.length,0);const summary=new PinterestObservationCollectionSummary({requestedPages:request.properties.maximumPages??1,requestedItems:request.properties.maximumRecords??0,rawRecordsCollected:raw,normalizedRecords:normalized,acceptedObservations:accepted.length-acceptedWarning,acceptedWithWarningObservations:acceptedWarning,quarantinedObservations:quarantined.length,rejectedObservations:rejected.length,historicalOnlyObservations:historical.length,duplicatesDetected:duplicates,noDataResults:state===PinterestObservationWorkflowState.NoData?1:0,providerFailures:collections.filter(c=>c.failure).length,normalizationFailures,validationFailures});const provenance=new Provenance("PinterestObservationWorkflow",started,collections[0]?.sourceId??new MarketSourceId("Pinterest"),[request.id.value,...collections.map(c=>c.requestId)]);const result=new PinterestObservationWorkflowResult({workflowId:request.id,businessPackageId:request.properties.businessPackageId,sourceReference:"Pinterest",capability:request.properties.capability,scope:request.properties.scope,finalState:state,summary,collectionResults:collections,acceptedObservations:accepted,quarantined,rejected,historicalOnly:historical,warnings,failures,rateLimit,startedAt:started,completedAt:at,correlationIdentifier:request.properties.correlationIdentifier,provenance});this.transition(request,state,state===PinterestObservationWorkflowState.Completed||state===PinterestObservationWorkflowState.CompletedWithWarnings?"PinterestObservationWorkflowCompleted":"PinterestObservationWorkflowFailed");this.repository.store(result);return result;}
  private transition(request:PinterestObservationWorkflowRequest,state:PinterestObservationWorkflowState,event:string){this.repository.transition(request.id,state,this.clock());this.report(event,request,{state});}
  private report(name:string,request:PinterestObservationWorkflowRequest,extra:Record<string,string>={}){const at=this.clock(),context={workflowId:request.id.value,businessPackageId:request.properties.businessPackageId.value,credentialId:request.properties.credentialId.value,scope:request.properties.scope,capability:request.properties.capability.value,...extra};this.events?.publish(new Event({id:new EventId(`pinterest-observation-workflow-${++this.#sequence}`),type:new EventType(name),timestamp:at,source:"PinterestObservationWorkflow",correlationId:request.properties.correlationIdentifier,context:new EventContext(context)}));this.audit?.append(new AuditEvent({id:`pinterest-observation-workflow-audit-${++this.#sequence}`,timestamp:at,type:AuditEventType.ExternalIntegration,source:"PinterestObservationWorkflow",action:name,result:extra.state??"Recorded",responsibleIdentity:request.properties.requestingAuthorityReference,relatedTaskOrWorkflowId:request.id.value,context}));}
}
