import type {BusinessPackageId} from "../../intelligence/market/MarketIntelligenceDomain.ts";
import type {PinterestCopyArtifact} from "./PinterestCopyProductionDomain.ts";
import type {PinterestCreationPlan} from "./PinterestCreationPlanningDomain.ts";

const required=(value:string,name:string)=>{if(!value?.trim())throw new PinterestVisualProductionException(`${name} is required`,"INVALID_REQUEST");return value;};
const frozen=<T>(values:readonly T[])=>Object.freeze([...values]);

export class PinterestVisualProductionException extends Error{constructor(message:string,readonly code="PINTEREST_VISUAL_PRODUCTION_FAILURE",options?:ErrorOptions){super(message,options);this.name="PinterestVisualProductionException";}}
export class PinterestVisualArtifactId{constructor(readonly value:string){required(value,"Visual artifact identifier");Object.freeze(this);}}
export class PinterestVisualArtifactVersion{constructor(readonly value:number){if(!Number.isInteger(value)||value<1)throw new PinterestVisualProductionException("Artifact version must be positive","INVALID_VERSION");Object.freeze(this);}}
export enum PinterestVisualStatus{Requested="Requested",Generating="Generating",Draft="Draft",ValidationRequired="ValidationRequired",RequiredAssetMissing="RequiredAssetMissing",ValidationFailed="ValidationFailed",ReadyForCreativeAssembly="ReadyForCreativeAssembly",Superseded="Superseded",Cancelled="Cancelled",Failed="Failed"}
export enum PinterestVisualType{StaticImage="StaticImage",BrandedGraphic="BrandedGraphic",LifestyleCreative="LifestyleCreative",EditorialGraphic="EditorialGraphic",ProductCreative="ProductCreative",BookCreative="BookCreative",TextLedCreative="TextLedCreative",ExperimentCreative="ExperimentCreative",Other="Other"}
export interface PinterestApprovedAsset{reference:string;businessPackageId:BusinessPackageId;available:boolean;provenanceReference:string;}
export interface PinterestBusinessVisualRules{reference:string;businessPackageId:BusinessPackageId;instructions:readonly string[];prohibitedTreatments:readonly string[];approvedAssets:readonly PinterestApprovedAsset[];}
export interface PinterestVisualCapabilities{supportedMediaTypes:readonly string[];allowedDimensions:readonly {width:number;height:number}[];allowedAspectRatios:readonly string[];maximumVariants:number;}
export interface PinterestCopyArtifactReference{artifact:PinterestCopyArtifact;title?:string;textOverlay?:string;cta?:string;language:string;destinationReference?:string;}
export interface PinterestVisualExperiment{hypothesis:string;controlledVariable:string;variantIdentity:string;baselineReference?:string;successMeasurementReference:string;}
export class PinterestVisualProductionRequest{constructor(readonly artifactId:PinterestVisualArtifactId,readonly planId:string,readonly planVersion:number,readonly businessPackageId:BusinessPackageId,readonly correlationIdentifier:string,readonly authorityReference:string,readonly visualType:PinterestVisualType,readonly visualRules:PinterestBusinessVisualRules,readonly requiredAssetReferences:readonly string[],readonly copy?:PinterestCopyArtifactReference,readonly variantCount=1){required(planId,"Creation Plan identifier");required(correlationIdentifier,"Correlation identifier");required(authorityReference,"Authority reference");if(!Number.isInteger(planVersion)||planVersion<1)throw new PinterestVisualProductionException("Exact Plan version is required","PLAN_VERSION_MISMATCH");if(!Number.isInteger(variantCount)||variantCount<1)throw new PinterestVisualProductionException("Variant count must be positive","INVALID_VARIANTS");Object.freeze(requiredAssetReferences);Object.freeze(this);}}
export class PinterestVisualProductionContext{readonly approvedAssets;readonly patternGuidance;constructor(readonly plan:PinterestCreationPlan,readonly request:PinterestVisualProductionRequest,readonly variantId:string,readonly revision:number,approvedAssets:readonly PinterestApprovedAsset[],patternGuidance:readonly unknown[],readonly experiment?:PinterestVisualExperiment){this.approvedAssets=frozen(approvedAssets);this.patternGuidance=frozen(patternGuidance);Object.freeze(this);}}
export interface PinterestRenderedVisual{assetReference:string;mediaType:string;width:number;height:number;aspectRatio:string;visibleText?:string;language?:string;destinationReference?:string;usedAssetReferences:readonly string[];appliedRuleReferences:readonly string[];originalBusinessCreative:boolean;prohibitedTreatments?:readonly string[];changedDimensions?:readonly string[];factualDescription?:string;}
export interface PinterestVisualGenerationProvenance{designerCapabilityReference:string;providerReference?:string;renderEngineReference?:string;generatedAt:Date;}
export interface PinterestVisualDesignerResult{visual:PinterestRenderedVisual;provenance:PinterestVisualGenerationProvenance;}
/** Provider-neutral visual generation boundary. It receives governed constraints, never strategy or imitation inputs. */
export interface PinterestVisualDesigner{generate(context:PinterestVisualProductionContext):PinterestVisualDesignerResult;}
export class PinterestVisualDraft{readonly visual;constructor(readonly draftId:string,readonly revision:number,readonly variantId:string,visual:PinterestRenderedVisual,readonly provenance:PinterestVisualGenerationProvenance,readonly createdAt:Date){this.visual=Object.freeze({...visual,usedAssetReferences:frozen(visual.usedAssetReferences),appliedRuleReferences:frozen(visual.appliedRuleReferences),prohibitedTreatments:frozen(visual.prohibitedTreatments??[]),changedDimensions:frozen(visual.changedDimensions??[])});Object.freeze(this);}}
export class PinterestVisualValidationResult{readonly reasons;constructor(readonly valid:boolean,reasons:readonly string[],readonly originalityValid:boolean,readonly validatedAt:Date){this.reasons=frozen(reasons);Object.freeze(this);}}
export interface PinterestVisualLineage{planId:string;planVersion:number;recommendationId:string;recommendationVersion:number;ceoDecisionId:string;businessPackageId:string;opportunityReferences:readonly string[];patternReferences:readonly string[];evidenceReferences:readonly string[];correlationIdentifier:string;copyArtifactId?:string;copyArtifactVersion?:number;hypothesis?:string;controlledVariable?:string;}
export class PinterestVisualArtifact{readonly drafts;readonly lineage;constructor(readonly id:PinterestVisualArtifactId,readonly version:PinterestVisualArtifactVersion,readonly status:PinterestVisualStatus,readonly variantId:string,drafts:readonly PinterestVisualDraft[],readonly validation:PinterestVisualValidationResult|undefined,lineage:PinterestVisualLineage,readonly missingAssetReferences:readonly string[]=[]){this.drafts=frozen(drafts);this.missingAssetReferences=frozen(missingAssetReferences);this.lineage=Object.freeze({...lineage,opportunityReferences:frozen(lineage.opportunityReferences),patternReferences:frozen(lineage.patternReferences),evidenceReferences:frozen(lineage.evidenceReferences)});Object.freeze(this);}}
export class PinterestVisualProductionResult{readonly artifacts;constructor(artifacts:readonly PinterestVisualArtifact[]){this.artifacts=frozen(artifacts);Object.freeze(this);}}
