import { CompetitiveAnalysis, CompetitiveAnalysisId, CompetitiveContentProfile, CompetitiveObservation, CompetitiveObservationId, CompetitiveSubject, CompetitiveSubjectType, ContentStructureAnalysis, EngagementAvailability, EngagementSignal, KeywordAnalysis, SearchIntent, SearchIntentAnalysis, VisualAnalysis } from "../../business/market/competitive/CompetitiveIntelligenceDomain.ts";
import type { CompetitiveIntelligenceService } from "../../business/market/competitive/CompetitiveIntelligenceService.ts";
import { AuditEvent } from "../../core/platform/AuditEvent.ts";import { AuditEventType } from "../../core/platform/AuditEventType.ts";import type { AuditRecorder } from "../../core/platform/AuditRecorder.ts";
import { Event } from "../../core/platform/Event.ts";import type { EventBus } from "../../core/platform/EventBus.ts";import { EventContext } from "../../core/platform/EventContext.ts";import { EventId } from "../../core/platform/EventId.ts";import { EventType } from "../../core/platform/EventType.ts";
import { Confidence, Evidence, EvidenceId, EvidenceStatus, MarketObservation, Provenance } from "../../intelligence/market/MarketIntelligenceDomain.ts";
import { MarketDataAcceptanceDecision, MarketDuplicateAssessment } from "../../intelligence/market/quality/MarketDataQualityDomain.ts";
import { PinterestOwnership, PinterestValueState } from "./PinterestMarketSourceAdapter.ts";
import { PinterestCompetitiveIntakeException, PinterestCompetitiveIntakeRequest, PinterestCompetitiveIntakeResult, PinterestCompetitiveIntakeStatus, PinterestCompetitiveSkipReason } from "./PinterestCompetitiveIntakeDomain.ts";
import type { PinterestCompetitiveDisposition, PinterestCompetitiveInput } from "./PinterestCompetitiveIntakeDomain.ts";

type Payload={resourceId?:string;resourceType?:string;ownership?:PinterestOwnership;title?:string;description?:string;link?:string;media?:unknown;keyword?:string;analytics?:{metric?:string;value?:number};competitorPrivateMetrics?:Record<string,PinterestValueState>};
const payload=(o:MarketObservation):Payload=>{try{const value=JSON.parse(o.payloadReference);if(value&&typeof value==="object")return value;}catch{}throw new PinterestCompetitiveIntakeException("Observation payload is malformed","MALFORMED_OBSERVATION");};
const tokens=(text?:string)=>text?.toLocaleLowerCase().match(/[\p{L}\p{N}]+/gu)??[];
export class PinterestCompetitiveEligibility { decide(input:PinterestCompetitiveInput,request:PinterestCompetitiveIntakeRequest,seen:Set<string>){const {observation,validation}=input;if(observation.businessPackageId?.value!==request.properties.businessPackageId.value)return PinterestCompetitiveSkipReason.Other;if(![MarketDataAcceptanceDecision.Accepted,MarketDataAcceptanceDecision.AcceptedWithWarnings].includes(validation.acceptance))return validation.acceptance===MarketDataAcceptanceDecision.HistoricalOnly?PinterestCompetitiveSkipReason.HistoricalOnly:PinterestCompetitiveSkipReason.NotDataQualityAccepted;if(validation.duplicateAssessment!==MarketDuplicateAssessment.IndependentRecord)return PinterestCompetitiveSkipReason.DuplicateUnderlyingArtefact;const p=payload(observation),key=`${p.resourceType}:${p.resourceId}`;if(seen.has(key))return PinterestCompetitiveSkipReason.DuplicateUnderlyingArtefact;seen.add(key);if(!["pin","board","analytics"].includes(p.resourceType??""))return PinterestCompetitiveSkipReason.UnsupportedObservationType;if(p.ownership===PinterestOwnership.UnknownOwnership)return PinterestCompetitiveSkipReason.UnknownOwnership;if(p.ownership===PinterestOwnership.OwnedAuthorizedResource&&!request.properties.includeOwned)return PinterestCompetitiveSkipReason.OwnedResourceNotRequested;return undefined;} }
export class PinterestContentProfileMapper { map(o:MarketObservation,p:Payload){const combined=[p.title,p.description].filter(Boolean).join(" ");return new CompetitiveContentProfile({title:p.title,description:p.description,contentLength:combined.length,contentStructure:p.description?.includes("\n")?"Multi-line description":p.description?"Single description":"Unavailable",publicationTimestamp:o.observedAt,freshness:o.freshness,callToAction:p.link?"Destination link present":undefined});} }
export class PinterestKeywordEvidenceMapper { map(p:Payload,e:Evidence){const title=tokens(p.title),description=tokens(p.description),all=[...title,...description],counts=new Map<string,number>();for(const t of all)counts.set(t,(counts.get(t)??0)+1);const explicit=p.keyword?tokens(p.keyword):[];return new KeywordAnalysis({keywords:[...new Set([...all,...explicit])].sort(),titleKeywordUsage:[...new Set(title)].sort(),descriptionKeywordUsage:[...new Set(description)].sort(),repeatedTerminology:[...counts].filter(([,n])=>n>1).map(([t])=>t).sort(),topicTerms:explicit,evidence:[e]});} }
export class PinterestVisualMetadataMapper { map(p:Payload){const m=p.media&&typeof p.media==="object"?p.media as Record<string,unknown>:undefined;const width=typeof m?.width==="number"?m.width:undefined,height=typeof m?.height==="number"?m.height:undefined;return new VisualAnalysis({imagePresence:!!m,imageType:typeof m?.type==="string"?m.type:undefined,visualComposition:width&&height?`${width}x${height}; aspect ${(width/height).toFixed(3)}`:undefined,layoutCharacteristics:typeof m?.layout==="string"?m.layout:undefined});} }
export class PinterestEngagementSignalMapper { map(o:MarketObservation,p:Payload){const confidence=o.confidence??new Confidence(.5),owned=p.ownership===PinterestOwnership.OwnedAuthorizedResource,signals:EngagementSignal[]=[];if(p.analytics?.metric&&Number.isFinite(p.analytics.value)&&owned)signals.push(new EngagementSignal(p.analytics.metric,p.analytics.value,o.sourceId,o.observedAt,confidence,EngagementAvailability.Available,o.provenance,p.ownership));for(const metric of ["clicks","ctr","conversions","revenue"]){if(!owned)signals.push(new EngagementSignal(metric,undefined,o.sourceId,o.observedAt,confidence,EngagementAvailability.Unavailable,o.provenance,p.ownership));}return Object.freeze(signals);} }
export class PinterestCompetitiveObservationMapper { constructor(private profiles=new PinterestContentProfileMapper(),private keywords=new PinterestKeywordEvidenceMapper(),private visuals=new PinterestVisualMetadataMapper(),private engagement=new PinterestEngagementSignalMapper()){}map(o:MarketObservation,at:Date){const p=payload(o),e=new Evidence(new EvidenceId(`pinterest-competitive-evidence:${o.id.value}`),[o.id],o.provenance,at,o.confidence??new Confidence(.5),o.freshness,EvidenceStatus.Active),subject=new CompetitiveSubject(p.resourceId!,p.resourceType==="board"?CompetitiveSubjectType.PublicPage:CompetitiveSubjectType.PublicPost,p.title??p.resourceId!);const observation=new CompetitiveObservation(new CompetitiveObservationId(`pinterest-competitive:${o.id.value}`),o,subject,p.resourceType!,p.ownership!,o.businessPackageId,[e]);return {observation,profile:this.profiles.map(o,p),keywords:this.keywords.map(p,e),intent:new SearchIntentAnalysis(SearchIntent.Unknown,[e],new Confidence(0),"Observable Pinterest metadata does not establish search intent"),visual:this.visuals.map(p),structure:new ContentStructureAnalysis({headlineStructure:p.title?"Title present":"Title unavailable",sectionStructure:p.description?.includes("\n")?"Multi-line description":"Single description",callToActionPlacement:p.link?"Destination link present":undefined,contentDepth:`${[p.title,p.description].filter(Boolean).join(" ").length} observed characters`}),engagement:this.engagement.map(o,p),evidence:e,ownership:p.ownership!};} }
export class PinterestCompetitiveIntakeService {
  #sequence=0;constructor(private intelligence:CompetitiveIntelligenceService,private events?:EventBus,private audit?:AuditRecorder,private clock=()=>new Date(),private eligibility=new PinterestCompetitiveEligibility(),private mapper=new PinterestCompetitiveObservationMapper()){}
  process(request:PinterestCompetitiveIntakeRequest){const started=this.clock();this.report("PinterestCompetitiveIntakeRequested",request);const observations:CompetitiveObservation[]=[],analyses:CompetitiveAnalysis[]=[],dispositions:PinterestCompetitiveDisposition[]=[],warnings:string[]=[],failures:string[]=[],seen=new Set<string>();let duplicates=0;
    for(const input of [...request.observations].sort((a,b)=>a.observation.id.value.localeCompare(b.observation.id.value))){try{const reason=this.eligibility.decide(input,request,seen);if(reason){if(reason===PinterestCompetitiveSkipReason.DuplicateUnderlyingArtefact)duplicates++;dispositions.push({observationId:input.observation.id.value,skipReason:reason});this.report("PinterestCompetitiveObservationSkipped",request,{observationId:input.observation.id.value,reason});continue;}this.report("PinterestCompetitiveObservationAccepted",request,{observationId:input.observation.id.value});const mapped=this.mapper.map(input.observation,this.clock());this.intelligence.registerObservation(mapped.observation);const id=new CompetitiveAnalysisId(`pinterest-analysis:${input.observation.id.value}`),analysis=new CompetitiveAnalysis({id,subject:mapped.observation.subject,businessPackageId:request.properties.businessPackageId,sourceObservations:[mapped.observation],contentProfile:mapped.profile,keywordAnalysis:mapped.keywords,searchIntentAnalysis:mapped.intent,visualAnalysis:mapped.visual,contentStructureAnalysis:mapped.structure,engagementSignals:mapped.engagement,competitiveGaps:[],confidence:input.observation.confidence??new Confidence(.5),provenance:input.observation.provenance,analysisTimestamp:this.clock()});this.intelligence.analyse(mapped.observation.subject,request.properties.businessPackageId,analysis);observations.push(mapped.observation);analyses.push(analysis);dispositions.push({observationId:input.observation.id.value,ownership:mapped.ownership,competitiveObservationId:mapped.observation.id.value,analysisId:id.value});this.report("PinterestCompetitiveObservationMapped",request,{observationId:input.observation.id.value});this.report("PinterestCompetitiveAnalysisCreated",request,{analysisId:id.value});}catch(error){const message=error instanceof Error?error.message:"Observation intake failed";failures.push(`${input.observation.id.value}: ${message}`);dispositions.push({observationId:input.observation.id.value,skipReason:PinterestCompetitiveSkipReason.Other,warning:message});this.report("PinterestCompetitiveObservationSkipped",request,{observationId:input.observation.id.value,reason:PinterestCompetitiveSkipReason.Other});}}
    const completed=this.clock(),eligible=observations.length,skipped=request.observations.length-eligible,status=failures.length&&eligible?PinterestCompetitiveIntakeStatus.Partial:failures.length?PinterestCompetitiveIntakeStatus.Failed:skipped?PinterestCompetitiveIntakeStatus.CompletedWithWarnings:PinterestCompetitiveIntakeStatus.Completed;const provenance=new Provenance("PinterestCompetitiveIntake",started,request.observations[0]?.observation.sourceId??(()=>{throw new PinterestCompetitiveIntakeException("At least one observation is required")})(),[request.properties.collectionWorkflowReference,...request.observations.map(x=>x.validation.id.value)]);const result=new PinterestCompetitiveIntakeResult({intakeId:request.id,businessPackageId:request.properties.businessPackageId,inputObservationCount:request.observations.length,eligibleCount:eligible,skippedCount:skipped,duplicateRelatedSkipCount:duplicates,competitiveObservations:observations,competitiveAnalyses:analyses,dispositions,warnings,failures,startedAt:started,completedAt:completed,correlationIdentifier:request.properties.correlationIdentifier,provenance,status});this.report("PinterestCompetitiveIntakeCompleted",request,{status});return result;}
  private report(name:string,request:PinterestCompetitiveIntakeRequest,extra:Record<string,string>={}){const at=this.clock(),context={intakeId:request.id.value,businessPackageId:request.properties.businessPackageId.value,...extra};this.events?.publish(new Event({id:new EventId(`pinterest-competitive-intake-${++this.#sequence}`),type:new EventType(name),timestamp:at,source:"PinterestCompetitiveIntakeService",correlationId:request.properties.correlationIdentifier,context:new EventContext(context)}));this.audit?.append(new AuditEvent({id:`pinterest-competitive-intake-audit-${++this.#sequence}`,timestamp:at,type:AuditEventType.ExternalIntegration,source:"PinterestCompetitiveIntakeService",action:name,result:extra.status??extra.reason??"Recorded",responsibleIdentity:request.properties.requestingAuthorityReference,relatedTaskOrWorkflowId:request.properties.collectionWorkflowReference,context}));}
}
