import type {ExpectedOutcome,MetricAvailability,PerformanceEvaluation,PerformanceMetric,PerformanceObservation,ObservedOutcome} from "../../business/market/performance/PerformanceIntelligenceDomain.ts";
import type {LearningDirection,LearningEpisode,ConfidenceAdjustment,PatternReevaluationProposal} from "../../business/learning/ContinuousLearningDomain.ts";
import type {BusinessPackageId} from "../../intelligence/market/MarketIntelligenceDomain.ts";
import type {PinterestPublishResult} from "./PinterestPublisher.ts";

const required=(value:string,name:string)=>{if(!value?.trim())throw new PinterestPerformanceFeedbackException(`${name} is required`,"INVALID_REQUEST");return value;};
const frozen=<T>(values:readonly T[])=>Object.freeze([...values]);
export class PinterestPerformanceFeedbackException extends Error{constructor(message:string,readonly code:string){super(message);this.name="PinterestPerformanceFeedbackException";}}
export enum PinterestPerformanceResourceClassification{OwnedAuthorizedResource="OwnedAuthorizedResource"}
export enum PinterestMeasurementMaturity{Provisional="Provisional",Mature="Mature"}
export enum PinterestAnalyticsCollectionState{Collected="Collected",NoData="NoData",AuthenticationRequired="AuthenticationRequired",RateLimited="RateLimited",Failed="Failed",Duplicate="Duplicate"}
export type PinterestMetricName="Impressions"|"Reach"|"Engagement"|"Saves"|"OutboundClicks"|"Clicks"|"EngagementRate"|"OutboundClickRate"|"VideoViews";
export class PinterestMeasurementWindowPolicy{constructor(readonly name:string,readonly durationMilliseconds:number,readonly mature:boolean){required(name,"Measurement window name");if(!Number.isFinite(durationMilliseconds)||durationMilliseconds<=0)throw new PinterestPerformanceFeedbackException("Measurement duration must be positive","INVALID_WINDOW");Object.freeze(this);}}
export interface PinterestExperimentLineage{hypothesis:string;variant:string;controlledVariable:string;baseline?:string;measurementWindow:string;}
export interface PinterestPublicationLineage{scheduledPublicationId:string;publishingCandidateId:string;publishingCandidateVersion:number;copyArtifactId:string;copyArtifactVersion:number;visualArtifactId:string;visualArtifactVersion:number;creationPlanId:string;creationPlanVersion:number;recommendationId:string;recommendationVersion:number;ceoDecisionReference:string;opportunityReferences:readonly string[];patternReferences:readonly string[];businessPackageId:BusinessPackageId;market:string;language:string;channel:"Pinterest";experiment?:PinterestExperimentLineage;}
export interface PinterestTimingSnapshot{recommendationId:string;recommendationVersion:number;recommendedWindow:string;confidence:number;scheduledTimestamp:Date;actualPublicationTimestamp:Date;timezone:string;timingDeviationMinutes:number;dayOfWeek:number;localPublicationTime:string;normalizedPublicationInstant:Date;}
export interface PinterestCadenceSnapshot{minimumPublicationIntervalMinutes:number;intervalSincePreviousMinutes?:number;intervalUntilNextMinutes?:number;recentPublishedPins:number;analysisWindowMinutes:number;queueContext:string;cadenceRecommendationReference?:string;}
export interface PinterestContentSnapshot{topic:string;contentIntent:string;destinationType:string;creativeType:string;}
export class PinterestPerformanceSubject{readonly lineage;readonly timing;readonly cadence;readonly content;constructor(readonly publication:PinterestPublishResult,lineage:PinterestPublicationLineage,timing:PinterestTimingSnapshot,cadence:PinterestCadenceSnapshot,content:PinterestContentSnapshot){if(publication.businessPackageId.value!==lineage.businessPackageId.value||lineage.channel!=="Pinterest")throw new PinterestPerformanceFeedbackException("Publication lineage scope does not match","SCOPE_MISMATCH");this.lineage=Object.freeze({...lineage,opportunityReferences:frozen(lineage.opportunityReferences),patternReferences:frozen(lineage.patternReferences),experiment:lineage.experiment&&Object.freeze({...lineage.experiment})});this.timing=Object.freeze({...timing});this.cadence=Object.freeze({...cadence});this.content=Object.freeze({...content});Object.freeze(this);}}
export class PinterestPerformanceCollectionRequest{readonly requestedMetrics;constructor(readonly subject:PinterestPerformanceSubject,requestedMetrics:readonly PinterestMetricName[],readonly window:PinterestMeasurementWindowPolicy,readonly correlationIdentifier:string,readonly workflowReference:string,readonly requestedAt:Date){required(correlationIdentifier,"Correlation identifier");required(workflowReference,"Workflow reference");if(!requestedMetrics.length)throw new PinterestPerformanceFeedbackException("At least one metric must be requested","INVALID_REQUEST");this.requestedMetrics=frozen(requestedMetrics);Object.freeze(this);}}
export interface PinterestRawMetric{providerName:string;value?:number;availability:MetricAvailability;unit:string;}
export class PinterestRawAnalyticsRecord{readonly metrics;constructor(readonly providerRecordId:string,readonly providerPinId:string,readonly providerWindowStart:Date,readonly providerWindowEnd:Date,readonly providerObservedAt:Date,readonly collectedAt:Date,metrics:readonly PinterestRawMetric[],readonly source="Pinterest Official Analytics API",readonly classification=PinterestPerformanceResourceClassification.OwnedAuthorizedResource){required(providerRecordId,"Provider record identifier");required(providerPinId,"Provider Pin identifier");if(providerWindowEnd<providerWindowStart||!metrics.length||metrics.some(x=>!x.providerName.trim()||!x.unit.trim()||x.value!==undefined&&!Number.isFinite(x.value)))throw new PinterestPerformanceFeedbackException("Provider analytics payload is malformed","MALFORMED_ANALYTICS");this.metrics=frozen(metrics.map(x=>Object.freeze({...x})));Object.freeze(this);}}
export type PinterestAnalyticsOutcome={kind:"Collected";record:PinterestRawAnalyticsRecord}|{kind:"NoData"}|{kind:"AuthenticationRequired";safeMessage:string}|{kind:"RateLimited";retryAfter:Date;safeMessage:string}|{kind:"Failed";safeMessage:string;retryAfter?:Date};
export interface PinterestAuthorizedAnalyticsTransport{collect(request:PinterestPerformanceCollectionRequest):Promise<PinterestAnalyticsOutcome>;}
export interface PinterestAnalyticsAuthenticationRecovery{requestRecovery(request:PinterestPerformanceCollectionRequest):Promise<void>|void;}
export interface PinterestPerformanceRetry{state:PinterestAnalyticsCollectionState;retryAfter?:Date;correlationIdentifier:string;workflowReference:string;}
export interface PinterestTimingLearningInput{observation:PerformanceObservation;timing:PinterestTimingSnapshot;content:PinterestContentSnapshot;market:string;language:string;channel:"Pinterest";measurementWindow:PinterestMeasurementWindowPolicy;evidenceQuality:number;}
export interface PinterestCadenceLearningInput{observation:PerformanceObservation;cadence:PinterestCadenceSnapshot;content:PinterestContentSnapshot;market:string;language:string;channel:"Pinterest";measurementWindow:PinterestMeasurementWindowPolicy;evidenceQuality:number;}
export interface PinterestContinuousLearningResult{direction:LearningDirection;episode?:LearningEpisode;patternReevaluationProposal?:PatternReevaluationProposal;confidenceAdjustmentProposal?:ConfidenceAdjustment;}
export interface PinterestPerformanceMeasurement{request:PinterestPerformanceCollectionRequest;raw:PinterestRawAnalyticsRecord;observation:PerformanceObservation;observedOutcome:ObservedOutcome;expectedOutcome?:ExpectedOutcome;evaluation:PerformanceEvaluation;timingLearningInput:PinterestTimingLearningInput;cadenceLearningInput:PinterestCadenceLearningInput;learning?:PinterestContinuousLearningResult;maturity:PinterestMeasurementMaturity;revision:number;duplicate:boolean;}
export interface PinterestPerformanceReadModel{publicationId:string;providerPinId:string;publishedAt:Date;recommendedTime:string;actualTime:Date;intervalSincePreviousMinutes?:number;measurements:readonly {window:string;maturity:PinterestMeasurementMaturity;metrics:readonly PerformanceMetric[];outcome:string;measuredAt:Date}[];learningStatus:string;}
export interface PinterestTimingAnalysisReadModel{businessPackageId:string;channel:"Pinterest";market:string;language:string;topic:string;weekday:number;localTime:string;publicationIntervalBand:string;evidenceCount:number;confidence:number;freshness:string;}
export interface PinterestCadenceAnalysisReadModel{businessPackageId:string;channel:"Pinterest";market:string;currentMinimumIntervalMinutes:number;performanceByIntervalBand:Readonly<Record<string,number>>;dailyPublishingDensity:number;recommendedIntervalMinutes?:number;confidence:number;evidenceCount:number;contradictoryEvidence:number;learningStatus:string;}
