import {AuditEvent} from "../../core/platform/AuditEvent.ts";
import {AuditEventType} from "../../core/platform/AuditEventType.ts";
import type {AuditRecorder} from "../../core/platform/AuditRecorder.ts";
import {Event} from "../../core/platform/Event.ts";
import type {EventBus} from "../../core/platform/EventBus.ts";
import {EventContext} from "../../core/platform/EventContext.ts";
import {EventId} from "../../core/platform/EventId.ts";
import {EventType} from "../../core/platform/EventType.ts";
import type {BusinessPackageId} from "../../intelligence/market/MarketIntelligenceDomain.ts";
import {PinterestCreativeReadiness,type PinterestCreativeCandidate} from "./PinterestCreativeAssemblyDomain.ts";
import {intervalCompatible,type PinterestTimingRecommendation,type PinterestTimingWindow} from "./PinterestTimingDomain.ts";

const required=(v:string,n:string)=>{if(!v?.trim())throw new PinterestSchedulingException(`${n} is required`,"INVALID_REQUEST");return v;};
const activeQueue=new Set(["Queued","TimingEvaluationRequired","TimingEvaluated","SchedulingRequired","Scheduled"]);
const activeSchedule=new Set(["Reserved","Confirmed","RebalanceRequired","ExecutionPending","ExecutionClaimed"]);
export class PinterestSchedulingException extends Error{constructor(message:string,readonly code="PINTEREST_SCHEDULING_FAILURE"){super(message);this.name="PinterestSchedulingException";}}
export class PinterestQueueItemId{constructor(readonly value:string){required(value,"Queue item identifier");Object.freeze(this);}}
export class PinterestQueueItemVersion{constructor(readonly value:number){if(!Number.isInteger(value)||value<1)throw new PinterestSchedulingException("Queue version must be positive","INVALID_VERSION");Object.freeze(this);}}
export enum PinterestQueueState{Queued="Queued",TimingEvaluationRequired="TimingEvaluationRequired",TimingEvaluated="TimingEvaluated",SchedulingRequired="SchedulingRequired",Scheduled="Scheduled",Held="Held",ReevaluationRequired="ReevaluationRequired",RevisionRequired="RevisionRequired",Cancelled="Cancelled",Superseded="Superseded",Published="Published",Failed="Failed"}
export enum PinterestQueuePriority{Normal="Normal",High="High",Urgent="Urgent",Held="Held"}
export enum PinterestQueueHealth{Empty="Empty",Critical="Critical",Low="Low",Healthy="Healthy",AboveTarget="AboveTarget",Full="Full",Paused="Paused"}
export enum PinterestProductionStatus{Active="Active",Reduced="Reduced",Paused="Paused",AttentionRequired="AttentionRequired"}
export enum PinterestScheduleStatus{Reserved="Reserved",Confirmed="Confirmed",RebalanceRequired="RebalanceRequired",Held="Held",Cancelled="Cancelled",ExecutionPending="ExecutionPending",ExecutionClaimed="ExecutionClaimed",Executed="Executed",ExecutionFailed="ExecutionFailed"}
export class PinterestQueuePolicy{constructor(readonly targetBufferPins:number,readonly minimumBufferPins:number,readonly maximumBufferPins:number|undefined=undefined,readonly paused=false){if(!Number.isInteger(targetBufferPins)||!Number.isInteger(minimumBufferPins)||targetBufferPins<1||minimumBufferPins<0||minimumBufferPins>targetBufferPins||maximumBufferPins!==undefined&&maximumBufferPins<targetBufferPins)throw new PinterestSchedulingException("Queue buffer policy is invalid","INVALID_POLICY");Object.freeze(this);}}
export class PinterestSchedulingPolicy{constructor(readonly minimumPublicationIntervalMinutes:number,readonly similarContentSpacingMinutes?:number){if(!Number.isInteger(minimumPublicationIntervalMinutes)||minimumPublicationIntervalMinutes<1)throw new PinterestSchedulingException("Minimum publication interval is invalid","INVALID_POLICY");Object.freeze(this);}}
export class PinterestQueueCoverage{constructor(readonly eligibleInventory:number,readonly expectedPinsPerDay:number|undefined){Object.freeze(this);}get days(){return this.expectedPinsPerDay&&this.expectedPinsPerDay>0?this.eligibleInventory/this.expectedPinsPerDay:undefined;}}
export interface PinterestQueueLineage{publishingCandidateId:string;publishingCandidateVersion:number;creationPlanId:string;creationPlanVersion:number;copyArtifactId:string;copyArtifactVersion:number;visualArtifactId:string;visualArtifactVersion:number;recommendationId:string;recommendationVersion:number;ceoDecision:string;opportunityReferences:readonly string[];patternReferences:readonly string[];evidenceReferences:readonly string[];provenance:unknown;}
export interface PinterestQueuePresentation{thumbnailReference?:string;title?:string;description?:string;cta?:string;topic?:string;destinationType?:string;destination:unknown;timingStatus?:string;freshnessState:string;experiment?:unknown;variant?:string;}
export class PinterestQueueItem{readonly lineage;readonly presentation;constructor(readonly id:PinterestQueueItemId,readonly version:PinterestQueueItemVersion,readonly candidate:PinterestCreativeCandidate,readonly businessPackageId:BusinessPackageId,readonly channel:string,readonly market:string,readonly language:string,readonly priority:PinterestQueuePriority,readonly state:PinterestQueueState,readonly queueOrder:number,readonly correlationIdentifier:string,lineage:PinterestQueueLineage,presentation:PinterestQueuePresentation,readonly queuedAt:Date,readonly updatedAt:Date,readonly holdReason?:string,readonly heldAt?:Date,readonly explanation="Current validated candidate is buffered for governed scheduling."){this.lineage=Object.freeze({...lineage,opportunityReferences:Object.freeze([...lineage.opportunityReferences]),patternReferences:Object.freeze([...lineage.patternReferences]),evidenceReferences:Object.freeze([...lineage.evidenceReferences])});this.presentation=Object.freeze({...presentation});Object.freeze(this);}}
export class PinterestScheduledPublication{constructor(readonly id:string,readonly queueItemId:PinterestQueueItemId,readonly queueItemVersion:PinterestQueueItemVersion,readonly publishingCandidateId:string,readonly publishingCandidateVersion:number,readonly businessPackageId:BusinessPackageId,readonly channel:string,readonly market:string,readonly timezone:string,readonly recommendedWindow:PinterestTimingWindow|undefined,readonly selectedLocalTimestamp:string,readonly selectedNormalizedInstant:Date,readonly minimumIntervalPolicyUsed:number,readonly priority:PinterestQueuePriority,readonly status:PinterestScheduleStatus,readonly correlationIdentifier:string,readonly provenance:unknown,readonly createdAt:Date,readonly scheduledAt:Date,readonly deviationMinutes:number,readonly requestedTimestamp?:Date,readonly requestedTimezone?:string,readonly requestedBy?:string,readonly requestReason?:string,readonly validationResult="Valid"){required(id,"Schedule identifier");Object.freeze(this);}}
export interface PinterestQueueQuery{businessPackageId:string;channel:string;states?:readonly PinterestQueueState[];language?:string;market?:string;topic?:string;destinationType?:string;priority?:PinterestQueuePriority;scheduled?:boolean;minimumTimingConfidence?:number;maximumTimingConfidence?:number;freshnessState?:string;createdFrom?:Date;createdTo?:Date;variant?:string;sortBy?:"queueOrder"|"scheduledTime"|"priority"|"creationTime"|"freshness"|"timingConfidence";direction?:"asc"|"desc";}
export interface PinterestQueueReadModel{id:string;version:number;thumbnailReference?:string;title?:string;topic?:string;language:string;market:string;destination:unknown;destinationType?:string;status:PinterestQueueState;priority:PinterestQueuePriority;timingStatus?:string;recommendedWindow?:PinterestTimingWindow;scheduledTimestamp?:Date;queueAgeMilliseconds:number;freshnessState:string;creationPlanReference:string;publishingCandidateReference:string;explanation:string;}
export interface PinterestPinDetailReadModel extends PinterestQueueReadModel{description?:string;cta?:string;visualReference?:string;copyArtifactReference:string;visualArtifactReference:string;validationStatus:PinterestCreativeReadiness;opportunityReferences:readonly string[];patternReferences:readonly string[];recommendationReference:string;ceoDecision:string;timingRecommendation?:PinterestTimingRecommendation;timingEvidence:readonly string[];experiment?:unknown;lineage:PinterestQueueLineage;provenance:unknown;}
export interface PinterestQueueSummary{readyForPublishing:number;scheduled:number;held:number;targetBufferPins:number;minimumBufferPins:number;maximumBufferPins?:number;coverageDays?:number;production:PinterestProductionStatus;nextScheduledPin?:Date;queueHealth:PinterestQueueHealth;timingMode:string;minimumPublicationIntervalMinutes:number;viewAllPins:true;}
export type PinterestQueueCommand={type:"Hold"|"Release"|"Cancel"|"MoveToTop"|"SendBackForRevision"|"ReevaluationRequired";itemId:string;actor:string;reason?:string};
export class PinterestSchedulingRequest{constructor(readonly requestId:string,readonly queueItemId:PinterestQueueItemId,readonly recommendation:PinterestTimingRecommendation,readonly correlationIdentifier:string,readonly manual?:{timestamp:Date;timezone:string;actor:string;reason?:string}){required(requestId,"Scheduling request identifier");Object.freeze(this);}}
export class PinterestScheduleCandidate{constructor(readonly item:PinterestQueueItem,readonly recommendation:PinterestTimingRecommendation){Object.freeze(this);}}
export class PinterestSchedulingResult{constructor(readonly publication:PinterestScheduledPublication|undefined,readonly conflicts:readonly string[]){Object.freeze(this);}}

export class PinterestQueueRepository{
 readonly #items=new Map<string,PinterestQueueItem>();readonly #candidateKeys=new Map<string,string>();readonly #schedules=new Map<string,PinterestScheduledPublication>();readonly #requests=new Map<string,string>();
 insert(item:PinterestQueueItem){const key=`${item.businessPackageId.value}|${item.channel}|${item.lineage.publishingCandidateId}|${item.lineage.publishingCandidateVersion}`,prior=this.#candidateKeys.get(key);if(prior)return this.#items.get(prior)!;this.#items.set(item.id.value,item);this.#candidateKeys.set(key,item.id.value);return item;}
 get(id:string){return this.#items.get(id);}save(item:PinterestQueueItem){if(!this.#items.has(item.id.value))throw new PinterestSchedulingException("Queue item was not found","NOT_FOUND");this.#items.set(item.id.value,item);return item;}list(){return [...this.#items.values()];}schedules(){return [...this.#schedules.values()];}
 scheduledForRequest(requestId:string){const id=this.#requests.get(requestId);return id?this.#schedules.get(id):undefined;}
 reserve(requestId:string,schedule:PinterestScheduledPublication){const existing=this.#requests.get(requestId);if(existing)return this.#schedules.get(existing)!;if(this.schedules().some(x=>activeSchedule.has(x.status)&&x.businessPackageId.value===schedule.businessPackageId.value&&x.channel===schedule.channel&&x.publishingCandidateId===schedule.publishingCandidateId&&x.publishingCandidateVersion===schedule.publishingCandidateVersion))throw new PinterestSchedulingException("Candidate version already has an active schedule","DUPLICATE_SCHEDULE");this.#schedules.set(schedule.id,schedule);this.#requests.set(requestId,schedule.id);return schedule;}
 replaceSchedule(value:PinterestScheduledPublication){this.#schedules.set(value.id,value);}
}

export class PinterestQueueManagementService{
 #sequence=0;constructor(readonly repository:PinterestQueueRepository,private readonly events?:EventBus,private readonly audit?:AuditRecorder,private readonly clock=()=>new Date()){}
 add(candidate:PinterestCreativeCandidate,options:{itemId:string;channel:string;market:string;language:string;priority?:PinterestQueuePriority;topic?:string;destinationType?:string;variant?:string}){if(candidate.readiness!==PinterestCreativeReadiness.ReadyForPublishing)throw new PinterestSchedulingException("Only a current ReadyForPublishing candidate may enter the queue","NOT_READY");const l=candidate.lineage,item=new PinterestQueueItem(new PinterestQueueItemId(options.itemId),new PinterestQueueItemVersion(1),candidate,candidate.businessPackageId,required(options.channel,"Channel"),options.market,options.language,options.priority??PinterestQueuePriority.Normal,PinterestQueueState.Queued,this.repository.list().length,candidate.correlationIdentifier,{publishingCandidateId:candidate.id,publishingCandidateVersion:candidate.version.value,creationPlanId:l.planId,creationPlanVersion:l.planVersion,copyArtifactId:l.copyArtifactId,copyArtifactVersion:l.copyArtifactVersion,visualArtifactId:l.visualArtifactId,visualArtifactVersion:l.visualArtifactVersion,recommendationId:l.recommendationId,recommendationVersion:l.recommendationVersion,ceoDecision:l.ceoDecisionId,opportunityReferences:l.opportunityReferences,patternReferences:l.patternReferences,evidenceReferences:l.evidenceReferences,provenance:candidate.provenance},{thumbnailReference:candidate.visualAssetReference,title:candidate.title,description:candidate.description,cta:candidate.cta,topic:options.topic,destinationType:options.destinationType,destination:candidate.destination,freshnessState:"Current",experiment:candidate.experiment,variant:options.variant},this.clock(),this.clock());const stored=this.repository.insert(item);if(stored===item)this.report("PinterestQueueItemAdded",item);return stored;}
 command(command:PinterestQueueCommand){const old=this.require(command.itemId),now=this.clock();let state=old.state,priority=old.priority,reason=old.holdReason,heldAt=old.heldAt,event="PinterestQueueItemMoved";if(command.type==="Hold"){state=PinterestQueueState.Held;priority=PinterestQueuePriority.Held;reason=command.reason;heldAt=now;event="PinterestQueueItemHeld";}else if(command.type==="Release"){state=old.presentation.freshnessState==="Current"?PinterestQueueState.Queued:PinterestQueueState.ReevaluationRequired;priority=PinterestQueuePriority.Normal;reason=undefined;heldAt=undefined;event="PinterestQueueItemReleased";}else if(command.type==="Cancel"){state=PinterestQueueState.Cancelled;event="PinterestQueueItemCancelled";}else if(command.type==="MoveToTop"){priority=PinterestQueuePriority.Urgent;}else if(command.type==="SendBackForRevision"){state=PinterestQueueState.RevisionRequired;event="PinterestQueueItemRevisionRequired";}else{state=PinterestQueueState.ReevaluationRequired;event="PinterestQueueItemReevaluationRequired";}const updated=new PinterestQueueItem(old.id,new PinterestQueueItemVersion(old.version.value+1),old.candidate,old.businessPackageId,old.channel,old.market,old.language,priority,state,command.type==="MoveToTop"?-1:old.queueOrder,old.correlationIdentifier,old.lineage,old.presentation,old.queuedAt,now,reason,heldAt,command.reason??old.explanation);this.repository.save(updated);this.report(event,updated,{actor:command.actor,reason:command.reason??""});return updated;}
 coverage(policy:PinterestQueuePolicy,pinsPerDay?:number){return new PinterestQueueCoverage(this.eligible().length,pinsPerDay);}
 health(policy:PinterestQueuePolicy){const n=this.eligible().length;if(policy.paused)return PinterestQueueHealth.Paused;if(n===0)return PinterestQueueHealth.Empty;if(policy.maximumBufferPins!==undefined&&n>=policy.maximumBufferPins)return PinterestQueueHealth.Full;if(n>policy.targetBufferPins)return PinterestQueueHealth.AboveTarget;if(n<policy.minimumBufferPins)return n<=Math.floor(policy.minimumBufferPins/2)?PinterestQueueHealth.Critical:PinterestQueueHealth.Low;return PinterestQueueHealth.Healthy;}
 demand(policy:PinterestQueuePolicy,itemScope?:PinterestQueueItem){const n=this.eligible().length,quantity=Math.max(0,policy.targetBufferPins-n);if(n<policy.minimumBufferPins){if(itemScope)this.report("PinterestQueueRefillRequired",itemScope,{quantity:String(quantity)});return{required:true,quantity,production:PinterestProductionStatus.AttentionRequired};}if(n>=policy.targetBufferPins){if(itemScope)this.report("PinterestQueueTargetReached",itemScope);return{required:false,quantity:0,production:n>policy.targetBufferPins?PinterestProductionStatus.Paused:PinterestProductionStatus.Reduced};}return{required:false,quantity,production:PinterestProductionStatus.Active};}
 query(q:PinterestQueueQuery):PinterestQueueReadModel[]{let rows=this.repository.list().filter(x=>x.businessPackageId.value===q.businessPackageId&&x.channel===q.channel);rows=rows.filter(x=>(!q.states||q.states.includes(x.state))&&(!q.language||x.language===q.language)&&(!q.market||x.market===q.market)&&(!q.topic||x.presentation.topic===q.topic)&&(!q.destinationType||x.presentation.destinationType===q.destinationType)&&(!q.priority||x.priority===q.priority)&&(!q.freshnessState||x.presentation.freshnessState===q.freshnessState)&&(!q.variant||x.presentation.variant===q.variant)&&(!q.createdFrom||x.queuedAt>=q.createdFrom)&&(!q.createdTo||x.queuedAt<=q.createdTo));if(q.scheduled!==undefined)rows=rows.filter(x=>(x.state===PinterestQueueState.Scheduled)===q.scheduled);const weight={Urgent:0,High:1,Normal:2,Held:3},sort=q.sortBy??"queueOrder";rows.sort((a,b)=>sort==="priority"?weight[a.priority]-weight[b.priority]:sort==="creationTime"?a.queuedAt.getTime()-b.queuedAt.getTime():a.queueOrder-b.queueOrder);if(q.direction==="desc")rows.reverse();return rows.map(x=>this.read(x));}
 detail(id:string,timingRecommendation?:PinterestTimingRecommendation):PinterestPinDetailReadModel{const x=this.require(id),base=this.read(x),schedule=this.schedule(x);return{...base,description:x.presentation.description,cta:x.presentation.cta,visualReference:x.presentation.thumbnailReference,copyArtifactReference:`${x.lineage.copyArtifactId}:${x.lineage.copyArtifactVersion}`,visualArtifactReference:`${x.lineage.visualArtifactId}:${x.lineage.visualArtifactVersion}`,validationStatus:x.candidate.readiness,opportunityReferences:x.lineage.opportunityReferences,patternReferences:x.lineage.patternReferences,recommendationReference:`${x.lineage.recommendationId}:${x.lineage.recommendationVersion}`,ceoDecision:x.lineage.ceoDecision,timingRecommendation,timingEvidence:timingRecommendation?.windows.flatMap(w=>w.evidenceReferences)??[],experiment:x.presentation.experiment,lineage:x.lineage,provenance:x.lineage.provenance,scheduledTimestamp:schedule?.selectedNormalizedInstant};}
 summary(pkg:string,channel:string,queuePolicy:PinterestQueuePolicy,schedulingPolicy:PinterestSchedulingPolicy,pinsPerDay?:number,timingMode="Adaptive"):PinterestQueueSummary{const scoped=this.repository.list().filter(x=>x.businessPackageId.value===pkg&&x.channel===channel),schedules=this.repository.schedules().filter(x=>x.businessPackageId.value===pkg&&x.channel===channel&&activeSchedule.has(x.status));return{readyForPublishing:scoped.filter(x=>activeQueue.has(x.state)).length,scheduled:schedules.length,held:scoped.filter(x=>x.state===PinterestQueueState.Held).length,targetBufferPins:queuePolicy.targetBufferPins,minimumBufferPins:queuePolicy.minimumBufferPins,maximumBufferPins:queuePolicy.maximumBufferPins,coverageDays:this.coverage(queuePolicy,pinsPerDay).days,production:this.demand(queuePolicy).production,nextScheduledPin:schedules.sort((a,b)=>a.selectedNormalizedInstant.getTime()-b.selectedNormalizedInstant.getTime())[0]?.selectedNormalizedInstant,queueHealth:this.health(queuePolicy),timingMode,minimumPublicationIntervalMinutes:schedulingPolicy.minimumPublicationIntervalMinutes,viewAllPins:true};}
 private eligible(){return this.repository.list().filter(x=>activeQueue.has(x.state)&&x.candidate.readiness===PinterestCreativeReadiness.ReadyForPublishing);}
 private schedule(x:PinterestQueueItem){return this.repository.schedules().find(s=>s.queueItemId.value===x.id.value&&activeSchedule.has(s.status));}private require(id:string){const x=this.repository.get(id);if(!x)throw new PinterestSchedulingException("Queue item was not found","NOT_FOUND");return x;}
 private read(x:PinterestQueueItem):PinterestQueueReadModel{const schedule=this.schedule(x);return{id:x.id.value,version:x.version.value,thumbnailReference:x.presentation.thumbnailReference,title:x.presentation.title,topic:x.presentation.topic,language:x.language,market:x.market,destination:x.presentation.destination,destinationType:x.presentation.destinationType,status:x.state,priority:x.priority,timingStatus:x.presentation.timingStatus,recommendedWindow:schedule?.recommendedWindow,scheduledTimestamp:schedule?.selectedNormalizedInstant,queueAgeMilliseconds:this.clock().getTime()-x.queuedAt.getTime(),freshnessState:x.presentation.freshnessState,creationPlanReference:`${x.lineage.creationPlanId}:${x.lineage.creationPlanVersion}`,publishingCandidateReference:`${x.lineage.publishingCandidateId}:${x.lineage.publishingCandidateVersion}`,explanation:x.explanation};}
 private report(name:string,item:PinterestQueueItem,extra:Record<string,string>={}){const at=this.clock(),id=++this.#sequence,context={queueItemId:item.id.value,businessPackageId:item.businessPackageId.value,channel:item.channel,...extra};this.events?.publish(new Event({id:new EventId(`pinterest-queue-${id}`),type:new EventType(name),timestamp:at,source:"PinterestQueueManagement",correlationId:item.correlationIdentifier,context:new EventContext(context)}));this.audit?.append(new AuditEvent({id:`pinterest-queue-audit-${id}`,timestamp:at,type:AuditEventType.WorkflowEvent,source:"PinterestQueueManagement",action:name,result:"Recorded",responsibleIdentity:extra.actor??"TCO",relatedTaskOrWorkflowId:item.id.value,context}));}
}

export class PinterestSchedulingService{
 #sequence=0;constructor(readonly repository:PinterestQueueRepository,private readonly events?:EventBus,private readonly audit?:AuditRecorder,private readonly clock=()=>new Date()){}
 schedule(request:PinterestSchedulingRequest,policy:PinterestSchedulingPolicy){const prior=this.repository.scheduledForRequest(request.requestId);if(prior)return new PinterestSchedulingResult(prior,[]);const item=this.repository.get(request.queueItemId.value);if(!item)throw new PinterestSchedulingException("Queue item was not found","NOT_FOUND");this.report("PinterestSchedulingRequested",item);if(!activeQueue.has(item.state)||item.state===PinterestQueueState.ReevaluationRequired||item.candidate.readiness!==PinterestCreativeReadiness.ReadyForPublishing)throw new PinterestSchedulingException("Candidate is not eligible for scheduling","INELIGIBLE");const windows=request.recommendation.windows.filter(x=>x.policyCompatible),manual=request.manual;let window:PinterestTimingWindow|undefined,selected:Date|undefined;if(manual){try{new Intl.DateTimeFormat("en",{timeZone:manual.timezone}).format(manual.timestamp);}catch{throw new PinterestSchedulingException("Manual timezone is invalid","INVALID_TIMEZONE");}selected=manual.timestamp;}else for(const candidate of windows){if(this.available(candidate.utcStart,item,policy)){window=candidate;selected=candidate.utcStart;break;}}if(!selected||!this.available(selected,item,policy)){this.report("PinterestScheduleConflictDetected",item);return new PinterestSchedulingResult(undefined,["No ranked timing window satisfies the current normalized minimum interval."]);}const local=new Intl.DateTimeFormat("sv-SE",{timeZone:manual?.timezone??window!.properties.timezone,dateStyle:"short",timeStyle:"medium",hourCycle:"h23"}).format(selected),base=window?.utcStart??selected,schedule=new PinterestScheduledPublication(`schedule-${request.requestId}`,item.id,item.version,item.lineage.publishingCandidateId,item.lineage.publishingCandidateVersion,item.businessPackageId,item.channel,item.market,manual?.timezone??window!.properties.timezone,window,local,selected,policy.minimumPublicationIntervalMinutes,item.priority,PinterestScheduleStatus.Reserved,item.correlationIdentifier,item.lineage.provenance,this.clock(),this.clock(),Math.round((selected.getTime()-base.getTime())/60000),manual?.timestamp,manual?.timezone,manual?.actor,manual?.reason);const stored=this.repository.reserve(request.requestId,schedule);this.report("PinterestScheduleReserved",item,{scheduleId:stored.id,minimumIntervalMinutes:String(policy.minimumPublicationIntervalMinutes)});return new PinterestSchedulingResult(stored,[]);}
 reschedule(scheduleId:string,request:PinterestSchedulingRequest,policy:PinterestSchedulingPolicy){const old=this.repository.schedules().find(x=>x.id===scheduleId);if(!old)throw new PinterestSchedulingException("Schedule was not found","NOT_FOUND");this.repository.replaceSchedule(new PinterestScheduledPublication(old.id,old.queueItemId,old.queueItemVersion,old.publishingCandidateId,old.publishingCandidateVersion,old.businessPackageId,old.channel,old.market,old.timezone,old.recommendedWindow,old.selectedLocalTimestamp,old.selectedNormalizedInstant,old.minimumIntervalPolicyUsed,old.priority,PinterestScheduleStatus.Cancelled,old.correlationIdentifier,old.provenance,old.createdAt,old.scheduledAt,old.deviationMinutes));return this.schedule(request,policy);}
 evaluatePolicyChange(pkg:string,channel:string,policy:PinterestSchedulingPolicy){const rows=this.repository.schedules().filter(x=>x.businessPackageId.value===pkg&&x.channel===channel&&activeSchedule.has(x.status)).sort((a,b)=>a.selectedNormalizedInstant.getTime()-b.selectedNormalizedInstant.getTime());const changed:string[]=[];for(let i=1;i<rows.length;i++)if(!intervalCompatible(rows[i-1].selectedNormalizedInstant,rows[i].selectedNormalizedInstant,policy.minimumPublicationIntervalMinutes)){const x=rows[i];this.repository.replaceSchedule(new PinterestScheduledPublication(x.id,x.queueItemId,x.queueItemVersion,x.publishingCandidateId,x.publishingCandidateVersion,x.businessPackageId,x.channel,x.market,x.timezone,x.recommendedWindow,x.selectedLocalTimestamp,x.selectedNormalizedInstant,x.minimumIntervalPolicyUsed,x.priority,PinterestScheduleStatus.RebalanceRequired,x.correlationIdentifier,x.provenance,x.createdAt,x.scheduledAt,x.deviationMinutes));changed.push(x.id);}return Object.freeze(changed);}
 claim(scheduleId:string){const x=this.repository.schedules().find(s=>s.id===scheduleId);if(!x||x.status!==PinterestScheduleStatus.ExecutionPending)throw new PinterestSchedulingException("Schedule is not eligible for execution claim","CLAIM_CONFLICT");const claimed=new PinterestScheduledPublication(x.id,x.queueItemId,x.queueItemVersion,x.publishingCandidateId,x.publishingCandidateVersion,x.businessPackageId,x.channel,x.market,x.timezone,x.recommendedWindow,x.selectedLocalTimestamp,x.selectedNormalizedInstant,x.minimumIntervalPolicyUsed,x.priority,PinterestScheduleStatus.ExecutionClaimed,x.correlationIdentifier,x.provenance,x.createdAt,x.scheduledAt,x.deviationMinutes);this.repository.replaceSchedule(claimed);return claimed;}
 private available(at:Date,item:PinterestQueueItem,policy:PinterestSchedulingPolicy){return this.repository.schedules().filter(x=>activeSchedule.has(x.status)&&x.businessPackageId.value===item.businessPackageId.value&&x.channel===item.channel).every(x=>intervalCompatible(x.selectedNormalizedInstant,at,policy.minimumPublicationIntervalMinutes));}
 private report(name:string,item:PinterestQueueItem,extra:Record<string,string>={}){const at=this.clock(),id=++this.#sequence,context={queueItemId:item.id.value,businessPackageId:item.businessPackageId.value,channel:item.channel,...extra};this.events?.publish(new Event({id:new EventId(`pinterest-scheduling-${id}`),type:new EventType(name),timestamp:at,source:"PinterestScheduling",correlationId:item.correlationIdentifier,context:new EventContext(context)}));this.audit?.append(new AuditEvent({id:`pinterest-scheduling-audit-${id}`,timestamp:at,type:AuditEventType.WorkflowEvent,source:"PinterestScheduling",action:name,result:"Recorded",responsibleIdentity:"TCO",relatedTaskOrWorkflowId:item.id.value,context}));}
}
