import {AuditEvent} from "../../core/platform/AuditEvent.ts";
import {AuditEventType} from "../../core/platform/AuditEventType.ts";
import type {AuditRecorder} from "../../core/platform/AuditRecorder.ts";
import {Event} from "../../core/platform/Event.ts";
import type {EventBus} from "../../core/platform/EventBus.ts";
import {EventContext} from "../../core/platform/EventContext.ts";
import {EventId} from "../../core/platform/EventId.ts";
import {EventType} from "../../core/platform/EventType.ts";
import type {BusinessPackageId} from "../../intelligence/market/MarketIntelligenceDomain.ts";
import {CredentialId,type CredentialMetadata,CredentialStatus} from "../../security/credentials/CredentialVault.ts";
import type {ControlledCredentialMaterial} from "../../security/authentication/ExternalAuthenticationDomain.ts";
import {PinterestCreativeReadiness,PinterestDestinationValidation,type PinterestCreativeCandidate} from "./PinterestCreativeAssemblyDomain.ts";
import {PinterestQueueState,PinterestScheduleStatus,type PinterestQueueItem,type PinterestQueueRepository,type PinterestScheduledPublication} from "./PinterestSchedulingQueue.ts";

const required=(value:string|undefined,name:string)=>{if(!value?.trim())throw new PinterestPublishingException(`${name} is required`,PinterestPublishFailureType.InvalidRequest);return value;};
const clean=(value:string)=>value.replace(/(?:authorization|access[_ -]?token|refresh[_ -]?token|client[_ -]?secret|password|session[_ -]?cookie)\s*[:=]\s*\S+/gi,"[redacted]");
export class PinterestPublicationId{constructor(readonly value:string){required(value,"Publication identifier");Object.freeze(this);}}
export enum PinterestPublishState{Pending="Pending",Claimed="Claimed",Authenticating="Authenticating",Ready="Ready",Publishing="Publishing",Published="Published",DryRun="DryRun",AuthenticationRecoveryRequired="AuthenticationRecoveryRequired",PermissionDenied="PermissionDenied",RateLimited="RateLimited",RetryPending="RetryPending",VerificationRequired="VerificationRequired",ExecutionWindowMissed="ExecutionWindowMissed",Failed="Failed",Cancelled="Cancelled"}
export enum PinterestPublishFailureType{InvalidRequest="InvalidRequest",NotEligible="NotEligible",AuthenticationRequired="AuthenticationRequired",PermissionDenied="PermissionDenied",RateLimited="RateLimited",ProviderTemporary="ProviderTemporary",NetworkBeforeWrite="NetworkBeforeWrite",UnknownOutcome="UnknownOutcome",InvalidResponse="InvalidResponse",RetryLimit="RetryLimit",ExecutionWindowMissed="ExecutionWindowMissed",DuplicatePrevented="DuplicatePrevented",ClaimUnavailable="ClaimUnavailable"}
export enum PinterestExecutionClaimState{Available="Available",Claimed="Claimed",Executing="Executing",Released="Released",Completed="Completed",Failed="Failed",RecoveryPending="RecoveryPending"}
export enum PinterestPublishingEnvironment{Production="Production",Sandbox="Sandbox"}
export class PinterestPublishingException extends Error{constructor(message:string,readonly failureType:PinterestPublishFailureType){super(clean(message));this.name="PinterestPublishingException";}}
export class PinterestPublishFailure{constructor(readonly type:PinterestPublishFailureType,readonly safeMessage:string,readonly providerReference?:string,readonly retryAfter?:Date){required(safeMessage,"Safe failure message");Object.freeze(this);}}
export class PinterestPublishedPinReference{constructor(readonly pinId:string,readonly providerReference:string,readonly publishedAt:Date){required(pinId,"Pinterest Pin identifier");required(providerReference,"Provider reference");Object.freeze(this);}}
export class PinterestPublishRequest{constructor(readonly publicationId:PinterestPublicationId,readonly scheduledPublicationId:string,readonly businessPackageId:BusinessPackageId,readonly accountReference:string,readonly credentialId:CredentialId,readonly boardReference:string,readonly title:string,readonly description:string,readonly destinationUrl:string,readonly visualAssetReference:string,readonly accessibilityText:string|undefined,readonly correlationIdentifier:string,readonly executionTimestamp:Date,readonly idempotencyKey:string,readonly environment:PinterestPublishingEnvironment){for(const [v,n] of [[scheduledPublicationId,"Schedule"],[accountReference,"Account"],[boardReference,"Board"],[title,"Title"],[description,"Description"],[destinationUrl,"Destination"],[visualAssetReference,"Visual asset"],[correlationIdentifier,"Correlation"],[idempotencyKey,"Idempotency key"]] as const)required(v,n);Object.freeze(this);}}
export class PinterestExecutionClaim{constructor(readonly scheduleId:string,readonly publicationId:PinterestPublicationId,readonly claimId:string,readonly state:PinterestExecutionClaimState,readonly claimedAt:Date){Object.freeze(this);}}
export class PinterestPublishAttempt{constructor(readonly publicationId:PinterestPublicationId,readonly attemptId:string,readonly number:number,readonly state:PinterestPublishState,readonly startedAt:Date,readonly completedAt:Date|undefined,readonly providerCorrelation:string,readonly failure: PinterestPublishFailure|undefined,readonly pinReference?:PinterestPublishedPinReference){Object.freeze(this);}}
export class PinterestPublishResult{readonly failures;constructor(readonly publicationId:PinterestPublicationId,readonly scheduledPublicationId:string,readonly candidateReference:string,readonly businessPackageId:BusinessPackageId,readonly attemptCount:number,readonly state:PinterestPublishState,readonly pinReference:PinterestPublishedPinReference|undefined,readonly actualPublicationTime:Date|undefined,readonly providerMetadata:Readonly<Record<string,string>>,failures:readonly PinterestPublishFailure[],readonly timingDeviationMilliseconds:number|undefined,readonly correlationIdentifier:string,readonly provenance:unknown,readonly dryRunRequest?:PinterestPublishRequest){this.failures=Object.freeze([...failures]);Object.freeze(this);}}

export type PinterestProviderOutcome=
 |{kind:"Published";pinId:string;providerReference:string;publishedAt?:Date;metadata?:Readonly<Record<string,string>>}
 |{kind:"AuthenticationRequired"|"PermissionDenied"|"RateLimited"|"TemporaryFailure"|"NetworkBeforeWrite"|"UnknownOutcome"|"InvalidResponse";safeMessage:string;providerReference?:string;retryAfter?:Date};
export interface PinterestOfficialWriteTransport{readonly environment:PinterestPublishingEnvironment;createPin(request:PinterestPublishRequest,credential:ControlledCredentialMaterial):Promise<PinterestProviderOutcome>;}
export interface PinterestPublishAuthentication{authorize(credentialId:CredentialId,businessPackageId:BusinessPackageId,accountReference:string,capability:"pins:write",correlationIdentifier:string):Promise<{metadata:CredentialMetadata;credential:ControlledCredentialMaterial}>;reauthorizationRequired(credentialId:CredentialId,publicationId:PinterestPublicationId,correlationIdentifier:string):Promise<void>|void;}
export interface PinterestPublicationReconciler{verify(request:PinterestPublishRequest):Promise<{status:"Found";pin:PinterestPublishedPinReference}|{status:"Absent"}|{status:"Unknown"}>;}
export interface PinterestPublishingHandoff{published(scheduleId:string,queueItemId:string,pin:PinterestPublishedPinReference,actualTime:Date):void;executionFailed?(scheduleId:string,state:PinterestPublishState):void;}
export interface PinterestCurrentIntervalPolicy{allows(schedule:PinterestScheduledPublication,at:Date):boolean;}
export interface PinterestPublisherStatus{nextPublication?:Date;status:"Scheduled"|"ExecutionPending"|"Publishing"|"Published"|"Failed"|"AuthenticationRequired"|"RateLimited"|"VerificationRequired";lastPublication?:"Success"|"Failed";authentication:"OK"|"Attention Required";publisher:"Online"|"Degraded"|"Paused";}

export class PinterestPublishingRepository{
 readonly #publications=new Map<string,PinterestPublishResult>();readonly #attempts=new Map<string,PinterestPublishAttempt[]>();readonly #claims=new Map<string,PinterestExecutionClaim>();
 claim(scheduleId:string,publicationId:PinterestPublicationId,claimId:string,at:Date){const existing=this.#claims.get(scheduleId);if(existing&&![PinterestExecutionClaimState.Released,PinterestExecutionClaimState.Failed].includes(existing.state))return undefined;const claim=new PinterestExecutionClaim(scheduleId,publicationId,claimId,PinterestExecutionClaimState.Claimed,at);this.#claims.set(scheduleId,claim);return claim;}
 transitionClaim(claim:PinterestExecutionClaim,state:PinterestExecutionClaimState){if(this.#claims.get(claim.scheduleId)?.claimId!==claim.claimId)throw new PinterestPublishingException("Execution claim is no longer valid",PinterestPublishFailureType.ClaimUnavailable);const next=new PinterestExecutionClaim(claim.scheduleId,claim.publicationId,claim.claimId,state,claim.claimedAt);this.#claims.set(claim.scheduleId,next);return next;}
 claimFor(scheduleId:string){return this.#claims.get(scheduleId);}result(id:PinterestPublicationId){return this.#publications.get(id.value);}save(result:PinterestPublishResult){this.#publications.set(result.publicationId.value,result);return result;}addAttempt(value:PinterestPublishAttempt){const list=this.#attempts.get(value.publicationId.value)??[];list.push(value);this.#attempts.set(value.publicationId.value,list);}attempts(id:PinterestPublicationId){return Object.freeze([...(this.#attempts.get(id.value)??[])]);}results(){return Object.freeze([...this.#publications.values()]);}
}

export class PinterestPublisher{constructor(private readonly transport:PinterestOfficialWriteTransport){}get environment(){return this.transport.environment;}publish(request:PinterestPublishRequest,credential:ControlledCredentialMaterial){return this.transport.createPin(request,credential);}}

export class PinterestPublishingService{
 #sequence=0;constructor(private readonly schedules:PinterestQueueRepository,private readonly repository:PinterestPublishingRepository,private readonly authentication:PinterestPublishAuthentication,private readonly publisher:PinterestPublisher,private readonly environment:PinterestPublishingEnvironment,private readonly accountReference:string,private readonly boardReference:string,private readonly toleranceMilliseconds:number,private readonly retryLimit:number,private readonly handoff:PinterestPublishingHandoff,private readonly intervalPolicy?:PinterestCurrentIntervalPolicy,private readonly reconciler?:PinterestPublicationReconciler,private readonly events?:EventBus,private readonly audit?:AuditRecorder,private readonly clock=()=>new Date()){if(toleranceMilliseconds<0||retryLimit<1)throw new PinterestPublishingException("Publishing policy is invalid",PinterestPublishFailureType.InvalidRequest);}
 async execute(scheduleId:string,credentialId:CredentialId,options:{publicationId?:PinterestPublicationId;dryRun?:boolean}={}){const now=this.clock(),schedule=this.schedules.schedules().find(x=>x.id===scheduleId),publicationId=options.publicationId??new PinterestPublicationId(`publication-${scheduleId}`);if(!schedule)throw new PinterestPublishingException("Scheduled publication was not found",PinterestPublishFailureType.NotEligible);const prior=this.repository.result(publicationId);if(prior?.state===PinterestPublishState.Published||prior?.state===PinterestPublishState.VerificationRequired)return prior;const item=this.schedules.get(schedule.queueItemId.value);this.eligible(schedule,item,now);if(this.repository.attempts(publicationId).length>=this.retryLimit)return this.failure(schedule,item!,publicationId,PinterestPublishState.Failed,new PinterestPublishFailure(PinterestPublishFailureType.RetryLimit,"Retry limit reached"));const claim=this.repository.claim(schedule.id,publicationId,`claim-${++this.#sequence}`,now);if(!claim)throw new PinterestPublishingException("Scheduled publication already has an active execution claim",PinterestPublishFailureType.ClaimUnavailable);this.report("PinterestExecutionClaimed",schedule,publicationId);let auth;try{auth=await this.authentication.authorize(credentialId,schedule.businessPackageId,this.accountReference,"pins:write",schedule.correlationIdentifier);this.verifyCredential(auth.metadata,schedule);}catch(error){this.repository.transitionClaim(claim,PinterestExecutionClaimState.RecoveryPending);await this.authentication.reauthorizationRequired(credentialId,publicationId,schedule.correlationIdentifier);return this.failure(schedule,item!,publicationId,PinterestPublishState.AuthenticationRecoveryRequired,new PinterestPublishFailure(PinterestPublishFailureType.AuthenticationRequired,clean(error instanceof Error?error.message:"Authentication required")));}const request=this.request(schedule,item!,publicationId,credentialId,now);if(this.publisher.environment!==this.environment)throw new PinterestPublishingException("Publishing environment configuration does not match transport",PinterestPublishFailureType.InvalidRequest);if(options.dryRun){this.repository.transitionClaim(claim,PinterestExecutionClaimState.Released);return this.result(schedule,item!,publicationId,PinterestPublishState.DryRun,undefined,undefined,{},[],request);}
 this.eligible(schedule,this.schedules.get(schedule.queueItemId.value),this.clock());this.repository.transitionClaim(claim,PinterestExecutionClaimState.Executing);this.report("PinterestPublishingStarted",schedule,publicationId);const number=this.repository.attempts(publicationId).length+1,started=this.clock();let outcome:PinterestProviderOutcome;try{outcome=await this.publisher.publish(request,auth.credential);}catch(error){outcome={kind:"UnknownOutcome",safeMessage:clean(error instanceof Error?error.message:"Provider outcome is unknown")};}const completed=this.clock();if(outcome.kind==="Published"){const pin=new PinterestPublishedPinReference(outcome.pinId,outcome.providerReference,outcome.publishedAt??completed);this.repository.addAttempt(new PinterestPublishAttempt(publicationId,`attempt-${publicationId.value}-${number}`,number,PinterestPublishState.Published,started,completed,request.idempotencyKey,undefined,pin));this.repository.transitionClaim(claim,PinterestExecutionClaimState.Completed);const result=this.result(schedule,item!,publicationId,PinterestPublishState.Published,pin,pin.publishedAt,outcome.metadata??{},[]);this.handoff.published(schedule.id,item!.id.value,pin,pin.publishedAt);this.report("PinterestPublished",schedule,publicationId);return result;}return await this.providerFailure(schedule,item!,publicationId,claim,request,number,started,completed,outcome,credentialId);
 }
 async reconcile(publicationId:PinterestPublicationId,credentialId:CredentialId){const current=this.repository.result(publicationId);if(!current||current.state!==PinterestPublishState.VerificationRequired||!current.dryRunRequest)throw new PinterestPublishingException("Publication does not require verification",PinterestPublishFailureType.InvalidRequest);if(!this.reconciler) return current;const verified=await this.reconciler.verify(current.dryRunRequest);if(verified.status==="Unknown")return current;if(verified.status==="Absent"){const schedule=this.schedules.schedules().find(x=>x.id===current.scheduledPublicationId)!,item=this.schedules.get(schedule.queueItemId.value)!;this.result(schedule,item,publicationId,PinterestPublishState.RetryPending,undefined,undefined,{},current.failures);this.repository.transitionClaim(this.repository.claimFor(schedule.id)!,PinterestExecutionClaimState.Released);return this.execute(schedule.id,credentialId,{publicationId});}const schedule=this.schedules.schedules().find(x=>x.id===current.scheduledPublicationId)!,item=this.schedules.get(schedule.queueItemId.value)!;this.repository.transitionClaim(this.repository.claimFor(schedule.id)!,PinterestExecutionClaimState.Completed);const result=this.result(schedule,item,publicationId,PinterestPublishState.Published,verified.pin,verified.pin.publishedAt,{},current.failures);this.handoff.published(schedule.id,item.id.value,verified.pin,verified.pin.publishedAt);return result;}
 status():PinterestPublisherStatus{const results=this.repository.results(),last=results.at(-1),next=this.schedules.schedules().filter(x=>[PinterestScheduleStatus.Confirmed,PinterestScheduleStatus.ExecutionPending].includes(x.status)).sort((a,b)=>a.selectedNormalizedInstant.getTime()-b.selectedNormalizedInstant.getTime())[0];const map:Partial<Record<PinterestPublishState,PinterestPublisherStatus["status"]>>={[PinterestPublishState.Publishing]:"Publishing",[PinterestPublishState.Published]:"Published",[PinterestPublishState.AuthenticationRecoveryRequired]:"AuthenticationRequired",[PinterestPublishState.RateLimited]:"RateLimited",[PinterestPublishState.VerificationRequired]:"VerificationRequired",[PinterestPublishState.Failed]:"Failed"};return{nextPublication:next?.selectedNormalizedInstant,status:map[last?.state??PinterestPublishState.Pending]??(next?"Scheduled":"ExecutionPending"),lastPublication:last?.state===PinterestPublishState.Published?"Success":last?"Failed":undefined,authentication:last?.state===PinterestPublishState.AuthenticationRecoveryRequired?"Attention Required":"OK",publisher:last&&![PinterestPublishState.Published,PinterestPublishState.DryRun].includes(last.state)?"Degraded":"Online"};}
 private eligible(schedule:PinterestScheduledPublication,item:PinterestQueueItem|undefined,now:Date){if(!item||schedule.channel!=="Pinterest"||item.channel!=="Pinterest"||schedule.businessPackageId.value!==item.businessPackageId.value||schedule.queueItemVersion.value!==item.version.value||schedule.publishingCandidateId!==item.candidate.id||schedule.publishingCandidateVersion!==item.candidate.version.value||item.state!==PinterestQueueState.Scheduled||item.candidate.readiness!==PinterestCreativeReadiness.ReadyForPublishing||item.candidate.destinationValidation!==PinterestDestinationValidation.Validated||item.lineage.ceoDecision.trim()===""||schedule.status!==PinterestScheduleStatus.Confirmed&&schedule.status!==PinterestScheduleStatus.ExecutionPending)throw new PinterestPublishingException("Scheduled creative is not execution-eligible",PinterestPublishFailureType.NotEligible);const c=item.candidate,l=item.lineage;if(l.creationPlanId!==c.lineage.planId||l.creationPlanVersion!==c.lineage.planVersion||l.copyArtifactId!==c.lineage.copyArtifactId||l.copyArtifactVersion!==c.lineage.copyArtifactVersion||l.visualArtifactId!==c.lineage.visualArtifactId||l.visualArtifactVersion!==c.lineage.visualArtifactVersion)throw new PinterestPublishingException("Exact creative versions are no longer valid",PinterestPublishFailureType.NotEligible);const deviation=now.getTime()-schedule.selectedNormalizedInstant.getTime();if(deviation<0)throw new PinterestPublishingException("Publication execution time has not arrived",PinterestPublishFailureType.NotEligible);if(deviation>this.toleranceMilliseconds)throw new PinterestPublishingException("Publication execution window was missed",PinterestPublishFailureType.ExecutionWindowMissed);if(this.intervalPolicy&&!this.intervalPolicy.allows(schedule,now))throw new PinterestPublishingException("Current hard publication interval blocks execution",PinterestPublishFailureType.NotEligible);required(this.boardReference,"Board");required(c.title,"Title");required(c.description,"Description");required(c.destinationUrl,"Destination");required(c.visualAssetReference,"Visual asset");}
 private verifyCredential(m:CredentialMetadata,s:PinterestScheduledPublication){if(m.status!==CredentialStatus.Active||!m.businessPackageScopes.includes(s.businessPackageId.value)||m.accountReference!==this.accountReference||!m.capabilityScopes.includes("pins:write"))throw new PinterestPublishingException("Pinterest write authorization is unavailable",PinterestPublishFailureType.AuthenticationRequired);}
 private request(s:PinterestScheduledPublication,i:PinterestQueueItem,p:PinterestPublicationId,c:CredentialId,at:Date){return new PinterestPublishRequest(p,s.id,s.businessPackageId,this.accountReference,c,this.boardReference,i.candidate.title!,i.candidate.description!,i.candidate.destinationUrl!,i.candidate.visualAssetReference,i.candidate.accessibilityText,s.correlationIdentifier,at,p.value,this.environment);}
 private async providerFailure(s:PinterestScheduledPublication,i:PinterestQueueItem,p:PinterestPublicationId,claim:PinterestExecutionClaim,request:PinterestPublishRequest,n:number,started:Date,completed:Date,o:Exclude<PinterestProviderOutcome,{kind:"Published"}>,credentialId:CredentialId){const mapping={AuthenticationRequired:[PinterestPublishState.AuthenticationRecoveryRequired,PinterestPublishFailureType.AuthenticationRequired,"PinterestPublishAuthenticationRequired",PinterestExecutionClaimState.RecoveryPending],PermissionDenied:[PinterestPublishState.PermissionDenied,PinterestPublishFailureType.PermissionDenied,"PinterestPublishPermissionDenied",PinterestExecutionClaimState.Failed],RateLimited:[PinterestPublishState.RateLimited,PinterestPublishFailureType.RateLimited,"PinterestPublishRateLimited",PinterestExecutionClaimState.RecoveryPending],TemporaryFailure:[PinterestPublishState.RetryPending,PinterestPublishFailureType.ProviderTemporary,"PinterestPublishFailed",PinterestExecutionClaimState.RecoveryPending],NetworkBeforeWrite:[PinterestPublishState.RetryPending,PinterestPublishFailureType.NetworkBeforeWrite,"PinterestPublishRetryRequested",PinterestExecutionClaimState.Released],UnknownOutcome:[PinterestPublishState.VerificationRequired,PinterestPublishFailureType.UnknownOutcome,"PinterestPublishVerificationRequired",PinterestExecutionClaimState.RecoveryPending],InvalidResponse:[PinterestPublishState.VerificationRequired,PinterestPublishFailureType.InvalidResponse,"PinterestPublishVerificationRequired",PinterestExecutionClaimState.RecoveryPending]} as const;const [state,type,event,claimState]=mapping[o.kind];if(o.kind==="AuthenticationRequired")await this.authentication.reauthorizationRequired(credentialId,p,s.correlationIdentifier);const failure=new PinterestPublishFailure(type,clean(o.safeMessage),o.providerReference,o.retryAfter);this.repository.addAttempt(new PinterestPublishAttempt(p,`attempt-${p.value}-${n}`,n,state,started,completed,request.idempotencyKey,failure));this.repository.transitionClaim(claim,claimState);const result=this.result(s,i,p,state,undefined,undefined,{},[failure],state===PinterestPublishState.VerificationRequired?request:undefined);this.handoff.executionFailed?.(s.id,state);this.report(event,s,p);return result;}
 private failure(s:PinterestScheduledPublication,i:PinterestQueueItem,p:PinterestPublicationId,state:PinterestPublishState,f:PinterestPublishFailure){return this.result(s,i,p,state,undefined,undefined,{},[f]);}
 private result(s:PinterestScheduledPublication,i:PinterestQueueItem,p:PinterestPublicationId,state:PinterestPublishState,pin:PinterestPublishedPinReference|undefined,actual:Date|undefined,metadata:Readonly<Record<string,string>>,failures:readonly PinterestPublishFailure[],preview?:PinterestPublishRequest){return this.repository.save(new PinterestPublishResult(p,s.id,`${i.candidate.id}:${i.candidate.version.value}`,s.businessPackageId,this.repository.attempts(p).length,state,pin,actual,metadata,failures,actual?actual.getTime()-s.selectedNormalizedInstant.getTime():undefined,s.correlationIdentifier,{schedule:s.provenance,lineage:i.lineage,experiment:i.candidate.experiment},preview));}
 private report(action:string,s:PinterestScheduledPublication,p:PinterestPublicationId){const at=this.clock(),context={publicationId:p.value,scheduledPublicationId:s.id,businessPackageId:s.businessPackageId.value,correlationIdentifier:s.correlationIdentifier};this.events?.publish(new Event({id:new EventId(`pinterest-publish-${++this.#sequence}`),type:new EventType(action),timestamp:at,source:"PinterestPublisher",correlationId:s.correlationIdentifier,context:new EventContext(context)}));this.audit?.append(new AuditEvent({id:`pinterest-publish-audit-${this.#sequence}`,timestamp:at,type:AuditEventType.ExternalIntegration,source:"PinterestPublisher",action,result:"Recorded",responsibleIdentity:"TCO",context}));}
}
