import type {MarketOpportunity} from "../../business/market/opportunities/OpportunityIntelligenceDomain.ts";
import type {MarketPattern} from "../../business/market/patterns/PatternIntelligenceDomain.ts";
import type {PerformanceEvaluation} from "../../business/market/performance/PerformanceIntelligenceDomain.ts";
import {BusinessPackageId,Provenance} from "../../intelligence/market/MarketIntelligenceDomain.ts";
import {BusinessRecommendation,RecommendationEffort,RecommendationEvidence,RecommendationObjective,RecommendationPriority,RecommendationRisk,RecommendationType,RecommendationValue,RecommendedWorkflowReference,StrategicRelevance} from "../../business/recommendations/RecommendationDomain.ts";

export class PinterestRecommendationEvaluationException extends Error{constructor(message:string,readonly code="PINTEREST_RECOMMENDATION_EVALUATION_FAILURE",options?:ErrorOptions){super(message,options);this.name="PinterestRecommendationEvaluationException";}}
const required=(value:string,field:string)=>{if(typeof value!=="string"||!value.trim())throw new PinterestRecommendationEvaluationException(`${field} is required`,"INVALID_REQUEST");return value;};
const time=(value:Date,field:string)=>{if(!(value instanceof Date)||!Number.isFinite(value.getTime()))throw new PinterestRecommendationEvaluationException(`${field} is invalid`,"INVALID_REQUEST");return value.getTime();};
const frozen=<T>(values:readonly T[])=>Object.freeze([...values]);
export class PinterestRecommendationEvaluationId{constructor(readonly value:string){required(value,"Evaluation identifier");Object.freeze(this);}}
export enum PinterestRecommendationEvaluationState{Requested="Requested",Started="Started",Completed="Completed",CompletedWithWarnings="CompletedWithWarnings",Failed="Failed"}
export enum PinterestRecommendationEvidenceGap{UnknownPerformance="UnknownPerformance",UnknownDemand="UnknownDemand",UnknownAssetFit="UnknownAssetFit",UnknownAudienceFit="UnknownAudienceFit",InsufficientCrossMarketEvidence="InsufficientCrossMarketEvidence",InsufficientFreshness="InsufficientFreshness",MissingStrategicContext="MissingStrategicContext"}

export interface PinterestRecommendationEvaluationRequestProperties{id:PinterestRecommendationEvaluationId;businessPackageId:BusinessPackageId;opportunityReferences:readonly string[];patternReferences?:readonly string[];performanceEvaluationReferences?:readonly string[];strategicContextReference?:string;approvedCEOPreferenceContext?:readonly string[];correlationIdentifier:string;requestingAuthorityReference:string;requestedAt:Date;}
export class PinterestRecommendationEvaluationRequest{readonly opportunityReferences;readonly patternReferences;readonly performanceEvaluationReferences;readonly approvedCEOPreferenceContext;readonly #at:number;constructor(readonly properties:PinterestRecommendationEvaluationRequestProperties){if(!properties.opportunityReferences.length)throw new PinterestRecommendationEvaluationException("At least one Opportunity reference is required","INVALID_REQUEST");required(properties.correlationIdentifier,"Correlation identifier");required(properties.requestingAuthorityReference,"Requesting authority");if(properties.strategicContextReference!==undefined)required(properties.strategicContextReference,"Strategic context reference");this.opportunityReferences=frozen([...new Set(properties.opportunityReferences)].sort());this.patternReferences=frozen([...new Set(properties.patternReferences??[])].sort());this.performanceEvaluationReferences=frozen([...new Set(properties.performanceEvaluationReferences??[])].sort());this.approvedCEOPreferenceContext=frozen([...new Set(properties.approvedCEOPreferenceContext??[])].sort());this.#at=time(properties.requestedAt,"Request timestamp");Object.freeze(this);}get id(){return this.properties.id;}get businessPackageId(){return this.properties.businessPackageId;}get requestedAt(){return new Date(this.#at);}}

export interface PinterestRecommendationCandidateInputProperties{opportunities:readonly MarketOpportunity[];objective:RecommendationObjective;type:RecommendationType;evidence:RecommendationEvidence;patterns?:readonly MarketPattern[];performanceEvaluations?:readonly PerformanceEvaluation[];businessMemoryReferences?:readonly string[];knowledgeContextReferences?:readonly string[];existingAssetReferences?:readonly string[];evidenceGaps?:readonly PinterestRecommendationEvidenceGap[];estimatedValue?:RecommendationValue;estimatedEffort?:RecommendationEffort;strategicRelevance?:StrategicRelevance;timingSensitive?:boolean;recommendedWorkflow?:RecommendedWorkflowReference;provenance:Provenance;}
export class PinterestRecommendationCandidateInput{readonly opportunities;readonly patterns;readonly performanceEvaluations;readonly businessMemoryReferences;readonly knowledgeContextReferences;readonly existingAssetReferences;readonly evidenceGaps;constructor(readonly properties:PinterestRecommendationCandidateInputProperties){if(!properties.opportunities.length)throw new PinterestRecommendationEvaluationException("Candidate input requires Opportunities","INVALID_CANDIDATE");this.opportunities=frozen(properties.opportunities);this.patterns=frozen(properties.patterns??[]);this.performanceEvaluations=frozen(properties.performanceEvaluations??[]);this.businessMemoryReferences=frozen(properties.businessMemoryReferences??[]);this.knowledgeContextReferences=frozen(properties.knowledgeContextReferences??[]);this.existingAssetReferences=frozen(properties.existingAssetReferences??[]);this.evidenceGaps=frozen(properties.evidenceGaps??[]);Object.freeze(this);}}
export class PinterestRecommendationEvidenceSet{readonly supporting;readonly contradicting;readonly opportunityReferences;readonly patternReferences;readonly performanceReferences;readonly businessMemoryReferences;readonly knowledgeContextReferences;readonly existingAssetReferences;readonly provenance;constructor(input:PinterestRecommendationCandidateInput){this.supporting=input.properties.evidence.supporting;this.contradicting=input.properties.evidence.contradicting;this.opportunityReferences=frozen(input.opportunities.map(x=>x.id.value));this.patternReferences=frozen(input.patterns.map(x=>x.id.value));this.performanceReferences=frozen(input.performanceEvaluations.map((x:any)=>x.id?.value??x.properties?.id?.value??"Unavailable"));this.businessMemoryReferences=input.businessMemoryReferences;this.knowledgeContextReferences=input.knowledgeContextReferences;this.existingAssetReferences=input.existingAssetReferences;this.provenance=frozen(input.properties.evidence.items.map(x=>x.evidence.provenance));Object.freeze(this);}}
export class PinterestRecommendationEvaluationSummary{constructor(readonly opportunitiesEvaluated:number,readonly eligibleOpportunities:number,readonly recommendationCandidatesCreated:number,readonly readyForCEOReview:number,readonly researchRecommendations:number,readonly experimentRecommendations:number,readonly insufficientEvidenceCases:number,readonly rejectedCandidates:number,readonly contradictedCandidates:number,readonly deferredEvaluationCases:number){Object.freeze(this);}}
export interface PinterestRecommendationEvaluationResultProperties{evaluationId:PinterestRecommendationEvaluationId;businessPackageId:BusinessPackageId;state:PinterestRecommendationEvaluationState;opportunityReferences:readonly string[];recommendations:readonly BusinessRecommendation[];evidenceSets:readonly PinterestRecommendationEvidenceSet[];evidenceGaps:readonly PinterestRecommendationEvidenceGap[];warnings:readonly string[];summary:PinterestRecommendationEvaluationSummary;startedAt:Date;completedAt:Date;correlationIdentifier:string;provenance:readonly Provenance[];}
export class PinterestRecommendationEvaluationResult{readonly opportunityReferences;readonly recommendations;readonly evidenceSets;readonly evidenceGaps;readonly warnings;readonly provenance;readonly #started;readonly #completed;constructor(readonly properties:PinterestRecommendationEvaluationResultProperties){this.#started=time(properties.startedAt,"Start timestamp");this.#completed=time(properties.completedAt,"Completion timestamp");this.opportunityReferences=frozen(properties.opportunityReferences);this.recommendations=frozen(properties.recommendations);this.evidenceSets=frozen(properties.evidenceSets);this.evidenceGaps=frozen(properties.evidenceGaps);this.warnings=frozen(properties.warnings);this.provenance=frozen(properties.provenance);Object.freeze(properties);Object.freeze(this);}get state(){return this.properties.state;}get summary(){return this.properties.summary;}get startedAt(){return new Date(this.#started);}get completedAt(){return new Date(this.#completed);}}
