import { BusinessPackageId } from "../../intelligence/market/MarketIntelligenceDomain.ts";
import { MarketSourceAdapterId, MarketSourceAvailability, MarketSourceCapability, MarketSourceHealth, MarketSourceRateLimit } from "../../intelligence/market/integration/MarketSourceIntegrationDomain.ts";
import { AuthenticationSessionReference, ExternalAuthenticationFailureType } from "../../security/authentication/ExternalAuthenticationDomain.ts";
import { CredentialId } from "../../security/credentials/CredentialVault.ts";

export class PinterestConnectionVerificationException extends Error { constructor(message:string,readonly code="PINTEREST_VERIFICATION_FAILURE"){super(message);this.name="PinterestConnectionVerificationException";} }
const required=(value:string,name:string)=>{if(typeof value!=="string"||!value.trim())throw new PinterestConnectionVerificationException(`${name} is required`);return value;};
const date=(value:Date,name:string)=>{if(!(value instanceof Date)||!Number.isFinite(value.getTime()))throw new PinterestConnectionVerificationException(`${name} is invalid`);return new Date(value);};

export class PinterestConnectionVerificationId { readonly value:string;constructor(value:string){this.value=required(value,"Verification identifier");Object.freeze(this);} }
export enum PinterestConnectionState { NotConfigured="NotConfigured",Configured="Configured",AuthenticationRequired="AuthenticationRequired",Authenticating="Authenticating",Authenticated="Authenticated",PartiallyAvailable="PartiallyAvailable",Available="Available",Degraded="Degraded",PermissionLimited="PermissionLimited",RateLimited="RateLimited",Maintenance="Maintenance",Unavailable="Unavailable",Failed="Failed",Unknown="Unknown" }
export enum PinterestCapabilityState { Available="Available",Unavailable="Unavailable",PermissionRequired="PermissionRequired",NotImplemented="NotImplemented",NotSupported="NotSupported",AuthenticationRequired="AuthenticationRequired",RateLimited="RateLimited",TemporarilyUnavailable="TemporarilyUnavailable",Unknown="Unknown" }
export enum PinterestCapabilityUnavailableReason { None="None",NoData="NoData",PermissionDenied="PermissionDenied",MissingScope="MissingScope",NotImplemented="NotImplemented",ProviderNotSupported="ProviderNotSupported",AuthenticationRequired="AuthenticationRequired",RateLimited="RateLimited",ProviderUnavailable="ProviderUnavailable",SourceUnavailable="SourceUnavailable",PrivateCompetitorMetric="PrivateCompetitorMetric",Unknown="Unknown" }

export interface PinterestConnectionVerificationRequestProperties { id:PinterestConnectionVerificationId;adapterId:MarketSourceAdapterId;credentialId:CredentialId;businessPackageId:BusinessPackageId;requestedCapabilities:readonly MarketSourceCapability[];requestingAuthorityReference:string;correlationIdentifier:string;requestedAt:Date;reverificationOf?:PinterestConnectionVerificationId; }
export class PinterestConnectionVerificationRequest { readonly requestedCapabilities:readonly MarketSourceCapability[];readonly requestedAt:Date;constructor(readonly properties:PinterestConnectionVerificationRequestProperties){if(!(properties.id instanceof PinterestConnectionVerificationId)||!(properties.adapterId instanceof MarketSourceAdapterId)||!(properties.credentialId instanceof CredentialId)||!(properties.businessPackageId instanceof BusinessPackageId)||!properties.requestedCapabilities.length)throw new PinterestConnectionVerificationException("Verification request references are invalid");required(properties.requestingAuthorityReference,"Requesting authority");required(properties.correlationIdentifier,"Correlation identifier");this.requestedCapabilities=Object.freeze([...properties.requestedCapabilities]);this.requestedAt=date(properties.requestedAt,"Request timestamp");Object.freeze(this);}get id(){return this.properties.id;} }

export class PinterestAccessMetadata { readonly authorizedScopeReferences:readonly string[];readonly verifiedAt:Date;constructor(readonly accessEnvironment:string,readonly accessTier:string|undefined,scopes:readonly string[],verifiedAt:Date,readonly providerApiReference:string,readonly adapterVersion:string){required(accessEnvironment,"Access environment");required(providerApiReference,"Provider API reference");required(adapterVersion,"Adapter version");this.authorizedScopeReferences=Object.freeze([...scopes]);this.verifiedAt=date(verifiedAt,"Access verification timestamp");Object.freeze(this);} }
export class PinterestCapabilityVerification { readonly verifiedAt:Date;readonly provenance:Readonly<Record<string,string>>;constructor(readonly capability:MarketSourceCapability,readonly state:PinterestCapabilityState,readonly reason:PinterestCapabilityUnavailableReason,readonly safeReason:string,verifiedAt:Date,readonly adapterId:MarketSourceAdapterId,readonly sourceReference:string,provenance:Record<string,string>={},readonly rateLimit?:MarketSourceRateLimit){if(!(capability instanceof MarketSourceCapability))throw new PinterestConnectionVerificationException("Capability is invalid");required(safeReason,"Safe capability reason");this.verifiedAt=date(verifiedAt,"Capability verification timestamp");this.provenance=Object.freeze({...provenance});Object.freeze(this);} }
export type PinterestAuthenticationVerificationState="Authenticated"|"CredentialCorrectionRequired"|"ReauthorizationRequired"|"MFARequired"|"PermissionDenied"|"TemporaryFailure"|"NonRecoverableFailure"|"AuthenticationRequired";
export interface PinterestConnectionVerificationResultProperties { id:PinterestConnectionVerificationId;adapterId:MarketSourceAdapterId;sourceReference:string;businessPackageId:BusinessPackageId;credentialId:CredentialId;state:PinterestConnectionState;authenticationState:PinterestAuthenticationVerificationState;capabilities:readonly PinterestCapabilityVerification[];sourceHealth:MarketSourceHealth;availability:MarketSourceAvailability;rateLimit?:MarketSourceRateLimit;accessMetadata?:PinterestAccessMetadata;verifiedAt:Date;failures?:readonly string[];warnings?:readonly string[];correlationIdentifier:string; }
export class PinterestConnectionVerificationResult { readonly capabilities:readonly PinterestCapabilityVerification[];readonly failures:readonly string[];readonly warnings:readonly string[];readonly verifiedAt:Date;constructor(readonly properties:PinterestConnectionVerificationResultProperties){if(!(properties.id instanceof PinterestConnectionVerificationId))throw new PinterestConnectionVerificationException("Result identifier is invalid");required(properties.correlationIdentifier,"Correlation identifier");this.capabilities=Object.freeze([...properties.capabilities]);this.failures=Object.freeze([...(properties.failures??[])]);this.warnings=Object.freeze([...(properties.warnings??[])]);this.verifiedAt=date(properties.verifiedAt,"Verification timestamp");Object.freeze(this);}get id(){return this.properties.id;}get state(){return this.properties.state;} }

export interface PinterestVerificationAuthenticationOutcome { successful:true;session:AuthenticationSessionReference }
export interface PinterestVerificationAuthenticationFailure { successful:false;failure:ExternalAuthenticationFailureType }
export interface PinterestCapabilityProbeResult { readonly status:number;readonly noData?:boolean;readonly headers?:Readonly<Record<string,string>>;readonly provenance?:Readonly<Record<string,string>> }
export interface PinterestConnectionProbe { verifyAuthentication(request:PinterestConnectionVerificationRequest):Promise<PinterestVerificationAuthenticationOutcome|PinterestVerificationAuthenticationFailure>;probeCapability(capability:MarketSourceCapability,session:AuthenticationSessionReference):Promise<PinterestCapabilityProbeResult>;verificationMetadata(at:Date):PinterestAccessMetadata; }
