import type { CompetitiveAnalysis, CompetitiveObservation, EngagementAvailability } from "../../business/market/competitive/CompetitiveIntelligenceDomain.ts";
import type { MarketPattern, PatternDirection, PatternStatus, PatternType } from "../../business/market/patterns/PatternIntelligenceDomain.ts";
import { BusinessPackageId, Evidence, Freshness, Provenance } from "../../intelligence/market/MarketIntelligenceDomain.ts";
import { MarketDuplicateAssessment } from "../../intelligence/market/quality/MarketDataQualityDomain.ts";

export class PinterestPatternEvaluationException extends Error { constructor(message:string,readonly code="PINTEREST_PATTERN_EVALUATION_FAILURE",options?:ErrorOptions){super(message,options);this.name="PinterestPatternEvaluationException";} }
const required=(v:string,n:string)=>{if(typeof v!=="string"||!v.trim())throw new PinterestPatternEvaluationException(`${n} is required`);return v;};
const instant=(v:Date,n:string)=>{if(!(v instanceof Date)||!Number.isFinite(v.getTime()))throw new PinterestPatternEvaluationException(`${n} is invalid`);return v.getTime();};
const count=(v:number,n:string)=>{if(!Number.isInteger(v)||v<0)throw new PinterestPatternEvaluationException(`${n} is invalid`);};
export class PinterestPatternEvaluationId { constructor(readonly value:string){required(value,"Evaluation identifier");Object.freeze(this);} }
export enum PinterestPatternEvaluationState { Requested="Requested",Started="Started",Completed="Completed",CompletedWithWarnings="CompletedWithWarnings",Failed="Failed" }
export enum PinterestPatternDimension { Keyword="Keyword",Phrase="Phrase",SearchIntent="SearchIntent",ContentTopic="ContentTopic",ContentStructure="ContentStructure",HeadlineStructure="HeadlineStructure",DescriptionStructure="DescriptionStructure",CTACharacteristic="CTACharacteristic",VisualMetadata="VisualMetadata",MediaType="MediaType",AspectRatio="AspectRatio",EngagementSignal="EngagementSignal",FreshnessCharacteristic="FreshnessCharacteristic",Other="Other" }
export enum PinterestPerformanceAssociation { Positive="Positive",Negative="Negative",UnknownPerformanceAssociation="UnknownPerformanceAssociation" }
export enum PinterestEvidenceOwnership { OwnedAuthorized="OwnedAuthorized",PublicObservable="PublicObservable",Unavailable="Unavailable" }

export interface PinterestPatternEvaluationRequestProperties { id:PinterestPatternEvaluationId;businessPackageId:BusinessPackageId;competitiveObservationReferences:readonly string[];competitiveAnalysisReferences:readonly string[];requestedDimensions:readonly PinterestPatternDimension[];marketContexts:readonly string[];regionContext?:string;languageContexts?:readonly string[];windowStart:Date;windowEnd:Date;minimumEvidencePolicyReference:string;correlationIdentifier:string;requestingAuthorityReference:string;requestedAt:Date; }
export class PinterestPatternEvaluationRequest { readonly competitiveObservationReferences:readonly string[];readonly competitiveAnalysisReferences:readonly string[];readonly requestedDimensions:readonly PinterestPatternDimension[];readonly marketContexts:readonly string[];readonly languageContexts:readonly string[];readonly #start:number;readonly #end:number;readonly #at:number;constructor(readonly properties:PinterestPatternEvaluationRequestProperties){required(properties.minimumEvidencePolicyReference,"Minimum evidence policy reference");required(properties.correlationIdentifier,"Correlation identifier");required(properties.requestingAuthorityReference,"Requesting authority reference");if(!properties.requestedDimensions.length)throw new PinterestPatternEvaluationException("At least one pattern dimension is required");this.#start=instant(properties.windowStart,"Window start");this.#end=instant(properties.windowEnd,"Window end");this.#at=instant(properties.requestedAt,"Request timestamp");if(this.#end<this.#start)throw new PinterestPatternEvaluationException("Evaluation window is invalid");this.competitiveObservationReferences=Object.freeze([...new Set(properties.competitiveObservationReferences)].sort());this.competitiveAnalysisReferences=Object.freeze([...new Set(properties.competitiveAnalysisReferences)].sort());this.requestedDimensions=Object.freeze([...new Set(properties.requestedDimensions)].sort());this.marketContexts=Object.freeze([...new Set(properties.marketContexts)].sort());this.languageContexts=Object.freeze([...new Set(properties.languageContexts??[])].sort());Object.freeze(this);}get id(){return this.properties.id;}get windowStart(){return new Date(this.#start);}get windowEnd(){return new Date(this.#end);}get requestedAt(){return new Date(this.#at);} }

export interface PinterestPatternCandidateInputProperties { dimension:PinterestPatternDimension;characteristic:string;patternType:PatternType;direction:PatternDirection;observation:CompetitiveObservation;analysis?:CompetitiveAnalysis;evidence:Evidence;duplicateAssessment:MarketDuplicateAssessment;duplicateGroupReference?:string;performanceAssociation:PinterestPerformanceAssociation;evidenceOwnership:PinterestEvidenceOwnership;marketContext:string;languageContext?:string;provenance:Provenance;observedAt:Date;engagementAvailability?:EngagementAvailability; }
export class PinterestPatternCandidateInput { readonly #at:number;constructor(readonly properties:PinterestPatternCandidateInputProperties){required(properties.characteristic,"Characteristic");required(properties.marketContext,"Market context");if(properties.observation.businessPackageId?.value!==properties.analysis?.businessPackageId?.value&&properties.analysis)throw new PinterestPatternEvaluationException("Analysis crosses Business Package boundary");this.#at=instant(properties.observedAt,"Observation timestamp");Object.freeze(properties);Object.freeze(this);}get observedAt(){return new Date(this.#at);} }

export class PinterestPatternEvidenceSet { readonly supportingEvidence:readonly Evidence[];readonly contradictingEvidence:readonly Evidence[];readonly qualityMetadata:readonly MarketDuplicateAssessment[];readonly sourceContexts:readonly string[];readonly provenances:readonly Provenance[];constructor(readonly candidateReference:string,readonly totalEvidenceCount:number,readonly independentObservationCount:number,readonly duplicateRelatedEvidenceCount:number,supporting:readonly Evidence[],contradicting:readonly Evidence[],readonly freshness:Freshness,quality:readonly MarketDuplicateAssessment[],contexts:readonly string[],provenances:readonly Provenance[],readonly probableDuplicateUncertainty:boolean){count(totalEvidenceCount,"Total evidence count");count(independentObservationCount,"Independent observation count");count(duplicateRelatedEvidenceCount,"Duplicate evidence count");this.supportingEvidence=Object.freeze([...supporting]);this.contradictingEvidence=Object.freeze([...contradicting]);this.qualityMetadata=Object.freeze([...quality]);this.sourceContexts=Object.freeze([...new Set(contexts)].sort());this.provenances=Object.freeze([...provenances]);Object.freeze(this);} }

export interface PinterestPatternEvaluationSummaryProperties { competitiveObservationsEvaluated:number;analysesEvaluated:number;candidateCharacteristicsFound:number;candidatesRejected:number;emergingPatterns:number;supportedOrConfirmedPatterns:number;negativePatterns:number;contradictedPatterns:number;decayingPatterns:number;duplicateEvidenceExcludedFromIndependenceCount:number;insufficientEvidenceCandidates:number; }
export class PinterestPatternEvaluationSummary { constructor(readonly properties:PinterestPatternEvaluationSummaryProperties){for(const [k,v] of Object.entries(properties))count(v,k);Object.freeze(properties);Object.freeze(this);} }
export interface PinterestPatternEvaluationResultProperties { evaluationId:PinterestPatternEvaluationId;businessPackageId:BusinessPackageId;state:PinterestPatternEvaluationState;evaluatedCandidateReferences:readonly string[];patterns:readonly MarketPattern[];statuses:readonly PatternStatus[];evidenceSets:readonly PinterestPatternEvidenceSet[];associations:readonly PinterestPerformanceAssociation[];summary:PinterestPatternEvaluationSummary;warnings:readonly string[];failures:readonly string[];startedAt:Date;completedAt:Date;correlationIdentifier:string; }
export class PinterestPatternEvaluationResult { readonly evaluatedCandidateReferences:readonly string[];readonly patterns:readonly MarketPattern[];readonly statuses:readonly PatternStatus[];readonly evidenceSets:readonly PinterestPatternEvidenceSet[];readonly associations:readonly PinterestPerformanceAssociation[];readonly warnings:readonly string[];readonly failures:readonly string[];readonly #started:number;readonly #completed:number;constructor(readonly properties:PinterestPatternEvaluationResultProperties){this.#started=instant(properties.startedAt,"Start timestamp");this.#completed=instant(properties.completedAt,"Completion timestamp");required(properties.correlationIdentifier,"Correlation identifier");this.evaluatedCandidateReferences=Object.freeze([...properties.evaluatedCandidateReferences]);this.patterns=Object.freeze([...properties.patterns]);this.statuses=Object.freeze([...properties.statuses]);this.evidenceSets=Object.freeze([...properties.evidenceSets]);this.associations=Object.freeze([...properties.associations]);this.warnings=Object.freeze([...properties.warnings]);this.failures=Object.freeze([...properties.failures]);Object.freeze(properties);Object.freeze(this);}get startedAt(){return new Date(this.#started);}get completedAt(){return new Date(this.#completed);}get summary(){return this.properties.summary;} }
