import type {BusinessPackageId} from "../../intelligence/market/MarketIntelligenceDomain.ts";
import type {PinterestCreativeCandidate} from "./PinterestCreativeAssemblyDomain.ts";

const required=(value:string,field:string)=>{if(!value?.trim())throw new PinterestTimingException(`${field} is required`,"INVALID_TIMING_REQUEST");return value;};
const frozen=<T>(value:readonly T[])=>Object.freeze([...value]);
export class PinterestTimingException extends Error{constructor(message:string,readonly code="PINTEREST_TIMING_FAILURE",options?:ErrorOptions){super(message,options);this.name="PinterestTimingException";}}
export class PinterestTimingEvaluationId{constructor(readonly value:string){required(value,"Timing evaluation identifier");Object.freeze(this);}}
export class PinterestTimingRecommendationVersion{constructor(readonly value:number){if(!Number.isInteger(value)||value<1)throw new PinterestTimingException("Recommendation version must be positive","INVALID_VERSION");Object.freeze(this);}}
export enum PinterestTimingMode{Adaptive="Adaptive",Fixed="Fixed"}
export enum PinterestTimezoneMode{Adaptive="Adaptive",Fixed="Fixed"}
export enum PinterestTimingEvidenceState{Learned="Learned",ColdStart="ColdStart",TimezoneAmbiguous="TimezoneAmbiguous"}
export enum PinterestTimingWindowRank{Best="Best",Alternative="Alternative",Fallback="Fallback"}
export enum PinterestTimingLearningState{Active="Active",InsufficientData="InsufficientData",Paused="Paused"}
export enum PinterestCadenceRecommendationStatus{InsufficientEvidence="InsufficientEvidence",Advisory="Advisory",ReadyForCEOReview="ReadyForCEOReview",Accepted="Accepted",Rejected="Rejected",Superseded="Superseded"}
export enum PinterestTimingGeneralization{ContentContext="ContentContext",Topic="Topic",MarketLanguage="MarketLanguage",BusinessPackageChannel="BusinessPackageChannel",BaselinePolicy="BaselinePolicy"}
export class PinterestTimingConfidence{constructor(readonly value:number,readonly evidenceCount:number,readonly independentObservationCount:number,readonly explanation:string){if(!Number.isFinite(value)||value<0||value>1||!Number.isInteger(evidenceCount)||evidenceCount<0||!Number.isInteger(independentObservationCount)||independentObservationCount<0)throw new PinterestTimingException("Timing confidence is invalid","INVALID_CONFIDENCE");required(explanation,"Confidence explanation");Object.freeze(this);}}
export interface PinterestFixedWindow{weekday?:number;startMinute:number;endMinute:number;}
export class PinterestTimingPolicy{readonly fixedWindows;constructor(readonly enabled=true,readonly mode=PinterestTimingMode.Adaptive,readonly timezoneMode=PinterestTimezoneMode.Adaptive,readonly fixedTimezone:string|undefined=undefined,fixedWindows:readonly PinterestFixedWindow[]=[],readonly granularityMinutes=60,readonly baselineWindows:readonly PinterestFixedWindow[]=[{startMinute:19*60,endMinute:20*60}],readonly marketTimezones:Readonly<Record<string,readonly string[]>>={}){if(!Number.isInteger(granularityMinutes)||granularityMinutes<1||granularityMinutes>1440)throw new PinterestTimingException("Timing granularity is invalid","INVALID_GRANULARITY");this.fixedWindows=frozen(fixedWindows);if(mode===PinterestTimingMode.Fixed&&!fixedWindows.length)throw new PinterestTimingException("Fixed timing mode requires fixed windows","MISSING_FIXED_WINDOWS");if(timezoneMode===PinterestTimezoneMode.Fixed&&!fixedTimezone)throw new PinterestTimingException("Fixed timezone mode requires a timezone","MISSING_TIMEZONE");if(fixedTimezone)assertIanaTimezone(fixedTimezone);Object.freeze(this);}}
export class PinterestCadencePolicy{constructor(readonly minimumPublicationIntervalMinutes:number){if(!Number.isInteger(minimumPublicationIntervalMinutes)||minimumPublicationIntervalMinutes<1)throw new PinterestTimingException("Minimum publication interval is invalid","INVALID_INTERVAL");Object.freeze(this);}}
export interface PinterestTimingContext{topic?:string;contentIntent?:string;creativeType?:string;destinationType?:string;audienceContext?:string;recentPublicationInstants?:readonly Date[];plannedPublicationInstants?:readonly Date[];recentTopics?:readonly {topic:string;publishedAt:Date}[];seasonalContextReference?:string;trendContextReference?:string;metricWeights?:Readonly<Record<string,number>>;}
export interface PinterestTimingLineage{copyArtifactReference:string;visualArtifactReference:string;creationPlanReference:string;ceoDecisionReference:string;recommendationReference:string;opportunityReferences:readonly string[];patternReferences:readonly string[];evidenceReferences:readonly string[];experiment?:{hypothesis:string;timingVariable:string;variantIdentity:string;measurementPlan:string;baseline?:string;outcomeReference?:string};}
export class PinterestTimingEvaluationRequest{constructor(readonly id:PinterestTimingEvaluationId,readonly candidate:PinterestCreativeCandidate,readonly candidateVersion:number,readonly businessPackageId:BusinessPackageId,readonly channel:string,readonly market:string,readonly language:string,readonly timezoneContext:string|undefined,readonly timingPolicy:PinterestTimingPolicy,readonly cadencePolicy:PinterestCadencePolicy,readonly context:PinterestTimingContext,readonly lineage:PinterestTimingLineage,readonly correlationIdentifier:string,readonly requestedAt:Date){required(channel,"Channel");required(market,"Market");required(language,"Language");required(correlationIdentifier,"Correlation identifier");if(candidate.businessPackageId.value!==businessPackageId.value||candidate.version.value!==candidateVersion)throw new PinterestTimingException("Candidate scope or version mismatch","SCOPE_MISMATCH");Object.freeze(this);}}
export interface PinterestTimingEvidenceProperties{id:string;businessPackageId:string;channel:string;market:string;language:string;timezone:string;occurredAt:Date;windowStartMinute:number;windowEndMinute:number;metrics:Readonly<Record<string,number|undefined>>;topic?:string;contentIntent?:string;creativeType?:string;destinationType?:string;audienceContext?:string;observationId:string;quality:number;freshness:number;associationDirection?:"Supporting"|"Contradicting";publicationIntervalMinutes?:number;topicRepetitionObserved?:boolean;cannibalizationObserved?:boolean;experimentReference?:string;}
export class PinterestTimingEvidence{readonly metrics;constructor(readonly properties:PinterestTimingEvidenceProperties){required(properties.id,"Evidence identifier");assertIanaTimezone(properties.timezone);if(!(properties.occurredAt instanceof Date)||!Number.isFinite(properties.occurredAt.getTime())||properties.windowEndMinute<=properties.windowStartMinute)throw new PinterestTimingException("Timing evidence is invalid","INVALID_EVIDENCE");if(properties.quality<0||properties.quality>1||properties.freshness<0||properties.freshness>1)throw new PinterestTimingException("Evidence weights are invalid","INVALID_EVIDENCE");this.metrics=Object.freeze({...properties.metrics});Object.freeze(this);}get id(){return this.properties.id;}}
export interface PinterestTimingWindowProperties{localStart:string;localEnd:string;timezone:string;utcStart:Date;utcEnd:Date;rank:PinterestTimingWindowRank;confidence:PinterestTimingConfidence;evidenceReferences:readonly string[];contradictoryEvidence:readonly string[];explanation:string;policyCompatible:boolean;generalization:PinterestTimingGeneralization;}
export class PinterestTimingWindow{readonly evidenceReferences;readonly contradictoryEvidence;constructor(readonly properties:PinterestTimingWindowProperties){assertIanaTimezone(properties.timezone);this.evidenceReferences=frozen(properties.evidenceReferences);this.contradictoryEvidence=frozen(properties.contradictoryEvidence);Object.freeze(this);}get rank(){return this.properties.rank;}get utcStart(){return new Date(this.properties.utcStart);}get utcEnd(){return new Date(this.properties.utcEnd);}get policyCompatible(){return this.properties.policyCompatible;}}
export class PinterestTimingRecommendation{readonly windows;readonly warnings;constructor(readonly evaluationId:PinterestTimingEvaluationId,readonly version:PinterestTimingRecommendationVersion,windows:readonly PinterestTimingWindow[],readonly confidence:PinterestTimingConfidence,readonly evidenceState:PinterestTimingEvidenceState,readonly evidenceCount:number,readonly generalization:PinterestTimingGeneralization,warnings:readonly string[],readonly configuredMinimumIntervalMinutes:number,readonly lineage:PinterestTimingLineage,readonly language="Observed associations support these windows; timing is not proven causal."){this.windows=frozen(windows);this.warnings=frozen(warnings);Object.freeze(this);}}
export class PinterestCadenceEvaluation{constructor(readonly evidenceCount:number,readonly independentObservationCount:number,readonly currentMinimumIntervalMinutes:number,readonly observedIntervals:readonly number[]){Object.freeze(this);}}
export class PinterestCadenceRecommendation{readonly evidenceReferences;readonly contradictoryEvidence;readonly warnings;constructor(readonly currentMinimumIntervalMinutes:number,readonly recommendedMinimumIntervalMinutes:number|undefined,readonly confidence:PinterestTimingConfidence,readonly evidenceCount:number,evidenceReferences:readonly string[],readonly rationale:string,contradictoryEvidence:readonly string[],warnings:readonly string[],readonly status:PinterestCadenceRecommendationStatus){this.evidenceReferences=frozen(evidenceReferences);this.contradictoryEvidence=frozen(contradictoryEvidence);this.warnings=frozen(warnings);Object.freeze(this);}}
export interface PinterestTimingOutcomeTrace{timingRecommendationId:string;recommendedWindowReference:string;scheduledTimestamp?:Date;actualPublicationTimestamp?:Date;timingDeviationMinutes?:number;cadenceAtPublicationMinutes?:number;subsequentPerformanceReference?:string;}
export class PinterestTimingEvaluationResult{constructor(readonly recommendation:PinterestTimingRecommendation|undefined,readonly cadenceEvaluation:PinterestCadenceEvaluation,readonly cadenceRecommendation:PinterestCadenceRecommendation,readonly timezoneAmbiguity:readonly string[]=[],readonly outcomeTraceTemplate?:PinterestTimingOutcomeTrace){Object.freeze(this);}}
export interface PinterestTimingReadModel{businessPackageId:string;channel:string;enabled:boolean;mode:PinterestTimingMode;minimumPublicationIntervalMinutes:number;timezoneMode:PinterestTimezoneMode;fixedTimezone?:string;fixedWindows:readonly PinterestFixedWindow[];learningState:PinterestTimingLearningState;confidence?:number;nextRecommendedWindow?:PinterestTimingWindow;alternativeWindow?:PinterestTimingWindow;cadenceRecommendation?:PinterestCadenceRecommendation;evidenceSummary:string;}
export function assertIanaTimezone(value:string){try{new Intl.DateTimeFormat("en",{timeZone:value}).format(new Date());}catch{throw new PinterestTimingException("Timezone must be a valid IANA identifier","INVALID_TIMEZONE");}if(/^[-+]?\d{1,2}:\d{2}$/.test(value))throw new PinterestTimingException("Fixed UTC offsets are not timezone identities","INVALID_TIMEZONE");}
export function intervalCompatible(first:Date,second:Date,minimumMinutes:number){return Math.abs(second.getTime()-first.getTime())>=minimumMinutes*60_000;}
