const { app, BrowserWindow, ipcMain, safeStorage, shell } = require("electron");
const path = require("node:path");
const fs = require("node:fs/promises");
const { configurePersistentDataPath } = require("./paths.cjs");
const { createRuntimeHost } = require("./runtime-host.cjs");
const { startPinterestOAuth, REDIRECT_URI } = require("./pinterest-oauth.cjs");
const { createPinterestDataCollector } = require("./pinterest-data.cjs");
const { createPinterestPublisher } = require("./pinterest-publisher.cjs");
const { createPinterestScheduler } = require("./pinterest-scheduler.cjs");
configurePersistentDataPath(app);
const onboardingFile=()=>path.join(app.getPath("userData"),"state","onboarding.json");
async function isInitialized(){try{const state=JSON.parse(await fs.readFile(onboardingFile(),"utf8"));return state.schemaVersion===1&&state.completed===true;}catch{return false;}}
ipcMain.handle("onboarding:complete",async()=>{const target=onboardingFile(),temporary=`${target}.tmp`;await fs.mkdir(path.dirname(target),{recursive:true});await fs.writeFile(temporary,JSON.stringify({schemaVersion:1,completed:true,completedAt:new Date().toISOString()}),{mode:0o600});await fs.rename(temporary,target);return true;});
app.whenReady().then(async()=>{
 const runtime=createRuntimeHost(app,safeStorage); await runtime.initialize();
 const pinterestData=createPinterestDataCollector(()=>runtime.getPinterestAccessToken());
 const pinterestPublisher=createPinterestPublisher({getSandboxAccessToken:()=>runtime.getPinterestSandboxAccessToken(),getProductionAccessToken:()=>runtime.getPinterestAccessToken(),productionWriteEnabled:false});
 const pinterestScheduler=createPinterestScheduler(app,pinterestPublisher,{defaultIntervalMinutes:90}); await pinterestScheduler.initialize();
 const initialized=await isInitialized();
 const window=new BrowserWindow({title:"ALIVO OS",width:1280,height:800,minWidth:760,minHeight:600,backgroundColor:"#9c1c31",webPreferences:{contextIsolation:true,nodeIntegration:false,sandbox:true,preload:path.join(__dirname,"preload.cjs")}});
 let authWindow;
 async function openAuth(request){const result=await runtime.openAuthentication(request?.integration);if(result.state!=="Opened")return result;if(authWindow&&!authWindow.isDestroyed()){authWindow.focus();return result;}authWindow=new BrowserWindow({parent:window,modal:true,width:720,height:650,resizable:false,backgroundColor:"#9c1c31",webPreferences:{contextIsolation:true,nodeIntegration:false,sandbox:true,preload:path.join(__dirname,"auth-preload.cjs")}});authWindow.on("closed",()=>{authWindow=undefined;window.webContents.send("integration:changed");});await authWindow.loadFile(path.join(__dirname,"../ui/auth.html"),{query:{integration:result.integration}});return result;}
 ipcMain.handle("runtime:status",()=>runtime.status()); ipcMain.handle("system:integrations",()=>runtime.integrations()); ipcMain.handle("system:open-authentication",(_e,r)=>openAuth(r)); ipcMain.handle("system:command",(_e,r)=>runtime.systemCommand(r)); ipcMain.handle("settings:read",(_e,r)=>runtime.settingsRead(r)); ipcMain.handle("settings:command",(_e,r)=>runtime.settingsCommand(r)); ipcMain.handle("settings:open-authentication",(_e,r)=>openAuth(r)); ipcMain.handle("auth:verify",(_e,r)=>runtime.verifyAuthentication(r)); ipcMain.handle("auth:pinterest-oauth-info",()=>({redirectUri:REDIRECT_URI}));
 ipcMain.handle("auth:pinterest-oauth",async(_e,request={})=>{const appId=String(request.appId||"").trim(),appSecret=String(request.appSecret||"").trim();if(!appId||!appSecret)return{state:"Configuration Invalid",message:"Pinterest App ID and App secret are required."};const result=await startPinterestOAuth({appId,appSecret,openExternal:(url)=>shell.openExternal(url),complete:(payload)=>runtime.completePinterestOAuth(payload)});window.webContents.send("integration:changed");return result;});
 ipcMain.handle("pinterest:workspace",()=>null); ipcMain.handle("pinterest:data",()=>pinterestData.snapshot()); ipcMain.handle("pinterest:publisher-capabilities",()=>pinterestPublisher.capabilities());
 ipcMain.handle("pinterest:publish-test",async(_e,r)=>{const result=await pinterestPublisher.create(r,"sandbox");if(result?.state==="Published")window.webContents.send("pinterest:data-changed");return result;}); ipcMain.handle("pinterest:publish-production",async(_e,r)=>pinterestPublisher.create(r,"production"));
 ipcMain.handle("pinterest:scheduler:list",()=>pinterestScheduler.list()); ipcMain.handle("pinterest:scheduler:next-slot",(_e,from)=>pinterestScheduler.nextSlot(from));
 ipcMain.handle("pinterest:scheduler:schedule",async(_e,r)=>{const result=await pinterestScheduler.schedule(r);window.webContents.send("pinterest:scheduler-changed");return result;});
 ipcMain.handle("pinterest:scheduler:reschedule",async(_e,r={})=>{const result=await pinterestScheduler.reschedule(r.jobId,r.scheduledFor,{autoNextSlot:r.autoNextSlot===true});window.webContents.send("pinterest:scheduler-changed");return result;});
 ipcMain.handle("pinterest:scheduler:cancel",async(_e,id)=>{const result=await pinterestScheduler.cancel(id);window.webContents.send("pinterest:scheduler-changed");return result;}); ipcMain.handle("pinterest:scheduler:enable",async(_e,enabled)=>{const result=await pinterestScheduler.setEnabled(enabled);window.webContents.send("pinterest:scheduler-changed");return result;}); ipcMain.handle("pinterest:scheduler:set-cadence",async(_e,minutes)=>{const result=await pinterestScheduler.setCadence(minutes);window.webContents.send("pinterest:scheduler-changed");return result;}); ipcMain.handle("pinterest:scheduler:run-due",async()=>{const result=await pinterestScheduler.executeDue();window.webContents.send("pinterest:scheduler-changed");return result;});
 ipcMain.on("auth:close",()=>{if(authWindow&&!authWindow.isDestroyed())authWindow.close();});
 await window.loadFile(path.join(__dirname,`../ui/${initialized?"index.html":"onboarding.html"}`));
 if(initialized){for(const file of ["integration-runtime.js","pinterest-runtime.js","pinterest-scheduler-runtime.js"]){const projection=await fs.readFile(path.join(__dirname,`../ui/${file}`),"utf8");await window.webContents.executeJavaScript(projection);}await window.webContents.insertCSS(`[hidden]{display:none!important}:root{--bg:rgb(156,28,49);--panel:#7f182b;--panel2:#8f1a30;--line:rgba(255,255,255,.24);--text:#fffaf7;--muted:#f1dfe2}body{background:rgb(156,28,49)!important;color:var(--text)}header,aside,footer{background:rgba(92,10,29,.82)!important}.card,.kpi{background:rgba(93,13,31,.48)!important;border-color:rgba(255,255,255,.24)!important}nav button{color:#f5e8ea!important}nav button.selected{background:rgba(76,8,24,.58)!important;color:#fff4d2!important}.kpi span,.metric span,small,.quiet,.freshness,.sidebar-footer small{color:#f1dfe2!important}.chart,.data-table,.view-tabs,.periods,input,select,textarea{background:rgba(78,8,25,.38)!important}`);}
 runtime.maintainPinterestOAuth(false).then(r=>{if(r?.refreshed)window.webContents.send("integration:changed");}).catch(()=>{});const oauthMaintenance=setInterval(()=>{runtime.maintainPinterestOAuth(false).then(r=>{if(r?.refreshed)window.webContents.send("integration:changed");}).catch(()=>{});},6*60*60*1000);oauthMaintenance.unref?.();
});
app.on("window-all-closed",()=>{if(process.platform!=="darwin")app.quit();});
