export type SettingsCategory="general"|"pinterest"|"blogs"|"sources"|"business-package"|"publishing"|"trust"|"integrations"|"application"|"history";
export type SettingsActionState="Idle"|"Editing"|"Saving"|"Succeeded"|"Failed"|"Conflict"|"ValidationFailed"|"AuthorizationDenied";
export type CredentialStatus="Configured"|"Missing"|"Invalid"|"Expired"|"ReauthorizationRequired"|"PermissionDenied";
export interface PinterestSettingsView {readonly minimumPublicationIntervalMinutes:number;readonly timingMode:"Adaptive"|"Manual";readonly adaptiveTiming:boolean;readonly adaptiveTimezone:boolean;readonly manualTimezone?:string;readonly resolvedTimezone:string;readonly targetQueueBuffer:number;readonly minimumQueueBuffer:number;readonly blogPinterestPromotion:boolean;readonly minimumPinsPerPublishedBlog:number;readonly cadenceRecommendation?:{readonly minutes:number;readonly evidence:string};}
export interface BlogSettingsView {readonly workflowEnabled:boolean;readonly publishingAuthority:"CEOApprovalRequired"|"ConditionalAutonomy"|"Autonomous"|"Disabled";readonly defaultMarket:string;readonly defaultLanguage:string;}
export interface ResearchSourceSettingsView {readonly id:string;readonly name:string;readonly enabled:boolean;readonly capability:string;readonly market:string;readonly language:string;readonly health:string;readonly authenticationState:string;readonly disableImpact?:string;readonly version:string;}
export interface BusinessPackageSettingsView {readonly id:string;readonly name:string;readonly defaultMarkets:readonly string[];readonly defaultLanguages:readonly string[];readonly authorReference:string;readonly channels:readonly string[];readonly contentPolicyReference:string;}
export interface PublishingSettingsView {readonly wordpressReference:string;readonly pinterestReference:string;readonly publicationMode:string;readonly credentials:readonly {name:string;status:CredentialStatus}[];}
export interface IntegrationSettingsSummary {readonly name:string;readonly capability:string;readonly state:string;readonly credentialStatus:CredentialStatus;}
export interface ApplicationPreferencesView {readonly startWorkspace:string;readonly sidebarCollapsed:boolean;readonly displayDensity:"Comfortable"|"Compact";readonly defaultPerformancePeriod:string;}
export interface ConfigurationHistoryView {readonly category:string;readonly setting:string;readonly oldValue:string;readonly newValue:string;readonly changedBy:string;readonly timestamp:string;readonly reason?:string;}
export interface SettingsWorkspaceReadModel {readonly businessPackageId:string;readonly version:string;readonly stale:boolean;readonly pinterest:PinterestSettingsView;readonly blog:BlogSettingsView;readonly sources:readonly ResearchSourceSettingsView[];readonly businessPackage:BusinessPackageSettingsView;readonly publishing:PublishingSettingsView;readonly integrations:readonly IntegrationSettingsSummary[];readonly application:ApplicationPreferencesView;readonly history:readonly ConfigurationHistoryView[];}
export interface SettingsWorkspaceGateway {read(query:{businessPackageId:string}):Promise<SettingsWorkspaceReadModel>;preview(input:{command:string;businessPackageId:string;expectedVersion:string;changes:Readonly<Record<string,unknown>>}):Promise<{impact:readonly string[];rebalanceRequired:boolean}>;command(input:{command:string;businessPackageId:string;expectedVersion:string;reason:string;changes:Readonly<Record<string,unknown>>}):Promise<{state:Exclude<SettingsActionState,"Idle"|"Editing"|"Saving">;version:string;message:string;rebalanceRequired?:boolean}>;}
