import type {CompetitiveAnalysis} from "../market/competitive/CompetitiveIntelligenceDomain.ts";
import type {MarketOpportunity} from "../market/opportunities/OpportunityIntelligenceDomain.ts";
import type {MarketPattern} from "../market/patterns/PatternIntelligenceDomain.ts";
import type {PerformanceEvaluation} from "../market/performance/PerformanceIntelligenceDomain.ts";
import {BusinessPackageId,Confidence,Evidence,FreshnessStatus,Provenance} from "../../intelligence/market/MarketIntelligenceDomain.ts";
import {RecommendationException} from "./RecommendationException.ts";

const required=(v:string,f:string)=>{if(typeof v!=="string"||v.trim()==="")throw new RecommendationException(`${f} must not be empty`,"INVALID_RECOMMENDATION");return v;};
const instant=(v:Date,f:string)=>{const n=v instanceof Date?v.getTime():NaN;if(!Number.isFinite(n))throw new RecommendationException(`${f} must be a valid timestamp`,"INVALID_TIMESTAMP");return n;};
const list=<T>(v:readonly T[])=>Object.freeze([...v]);
export class RecommendationId{readonly #value:string;constructor(value:string){this.#value=required(value,"Recommendation identifier");Object.freeze(this);}get value(){return this.#value;}equals(other:RecommendationId){return other instanceof RecommendationId&&other.value===this.value;}toString(){return this.value;}}
export enum RecommendationType{ContentCreation="ContentCreation",ContentUpdate="ContentUpdate",KeywordOpportunity="KeywordOpportunity",VisualImprovement="VisualImprovement",PublishingOpportunity="PublishingOpportunity",ProductOpportunity="ProductOpportunity",ResearchOpportunity="ResearchOpportunity",WorkflowImprovement="WorkflowImprovement",CapabilityDevelopment="CapabilityDevelopment",MarketExpansion="MarketExpansion",AudienceOpportunity="AudienceOpportunity",PresentationImprovement="PresentationImprovement",StrategicExperiment="StrategicExperiment",Other="Other"}
export enum RecommendationStatus{Candidate="Candidate",Evaluated="Evaluated",Validated="Validated",ReadyForCEOReview="ReadyForCEOReview",ApprovedByCEO="ApprovedByCEO",RejectedByCEO="RejectedByCEO",Deferred="Deferred",Superseded="Superseded",Executed="Executed",OutcomeMeasured="OutcomeMeasured",Archived="Archived"}
export enum RecommendationValue{Unknown="Unknown",Low="Low",Moderate="Moderate",High="High",VeryHigh="VeryHigh"}
export enum RecommendationEffort{Unknown="Unknown",Low="Low",Moderate="Moderate",High="High",VeryHigh="VeryHigh"}
export enum RecommendationRisk{Unknown="Unknown",Low="Low",Moderate="Moderate",High="High",Critical="Critical"}
export enum RecommendationPriority{Unranked="Unranked",Low="Low",Normal="Normal",High="High",Urgent="Urgent"}
export enum StrategicRelevance{Unknown="Unknown",Low="Low",Moderate="Moderate",High="High",Critical="Critical"}
export enum RecommendationEvidenceRole{Supporting="Supporting",Contradicting="Contradicting"}
export enum CEODecision{Approved="Approved",Rejected="Rejected",Deferred="Deferred"}

export class RecommendationObjective{constructor(readonly id:string,readonly type:string,readonly description:string,readonly businessPackageId:BusinessPackageId,readonly strategicContext?:string,readonly measurableTargetReference?:string){required(id,"Objective identifier");required(type,"Objective type");required(description,"Objective description");if(!(businessPackageId instanceof BusinessPackageId))throw new RecommendationException("Objective requires Business Package context");if(strategicContext!==undefined)required(strategicContext,"Strategic context");if(measurableTargetReference!==undefined)required(measurableTargetReference,"Measurable target reference");Object.freeze(this);}}
export class RecommendationEvidenceItem{constructor(readonly evidence:Evidence,readonly origin:string,readonly evidenceType:string,readonly role:RecommendationEvidenceRole,readonly independent:boolean){if(!(evidence instanceof Evidence))throw new RecommendationException("Evidence is required","MISSING_EVIDENCE");required(origin,"Evidence origin");required(evidenceType,"Evidence type");Object.freeze(this);}}
export class RecommendationEvidence{readonly items:readonly RecommendationEvidenceItem[];constructor(items:readonly RecommendationEvidenceItem[]){if(!items.some(i=>i.role===RecommendationEvidenceRole.Supporting))throw new RecommendationException("Recommendation evidence requires supporting evidence","MISSING_EVIDENCE");this.items=list(items);Object.freeze(this);}get supporting(){return list(this.items.filter(i=>i.role===RecommendationEvidenceRole.Supporting));}get contradicting(){return list(this.items.filter(i=>i.role===RecommendationEvidenceRole.Contradicting));}get sourceDiversity(){return new Set(this.items.map(i=>i.evidence.provenance.sourceId.value)).size;}get independentSourceCount(){return new Set(this.items.filter(i=>i.independent).map(i=>i.evidence.provenance.sourceId.value)).size;}}
export interface RecommendationCandidateProperties{id:RecommendationId;type:RecommendationType;objective:RecommendationObjective;businessPackageId:BusinessPackageId;evidence:RecommendationEvidence;relatedOpportunities?:readonly MarketOpportunity[];relatedPatterns?:readonly MarketPattern[];relatedPerformanceEvaluations?:readonly PerformanceEvaluation[];relatedCompetitiveAnalyses?:readonly CompetitiveAnalysis[];relatedBusinessMemory?:readonly string[];provenance:Provenance;createdAt:Date;}
export class RecommendationCandidate{readonly relatedOpportunities;readonly relatedPatterns;readonly relatedPerformanceEvaluations;readonly relatedCompetitiveAnalyses;readonly relatedBusinessMemory;readonly #created:number;constructor(readonly properties:RecommendationCandidateProperties){if(properties.objective.businessPackageId.value!==properties.businessPackageId.value)throw new RecommendationException("Objective and candidate Business Packages must match","PACKAGE_MISMATCH");const refs=[...(properties.relatedOpportunities??[]),...(properties.relatedPatterns??[]),...(properties.relatedPerformanceEvaluations??[]),...(properties.relatedCompetitiveAnalyses??[])];if(refs.some(r=>r.businessPackageId?.value!==properties.businessPackageId.value))throw new RecommendationException("Intelligence cannot cross Business Package boundaries","PACKAGE_MISMATCH");this.relatedOpportunities=list(properties.relatedOpportunities??[]);this.relatedPatterns=list(properties.relatedPatterns??[]);this.relatedPerformanceEvaluations=list(properties.relatedPerformanceEvaluations??[]);this.relatedCompetitiveAnalyses=list(properties.relatedCompetitiveAnalyses??[]);this.relatedBusinessMemory=list(properties.relatedBusinessMemory??[]);this.#created=instant(properties.createdAt,"Candidate creation timestamp");Object.freeze(this);}get id(){return this.properties.id;}get type(){return this.properties.type;}get objective(){return this.properties.objective;}get businessPackageId(){return this.properties.businessPackageId;}get evidence(){return this.properties.evidence;}get provenance(){return this.properties.provenance;}get createdAt(){return new Date(this.#created);}}
export class RecommendationConfidence{readonly factors:readonly EvaluationFactor[];constructor(readonly confidence:Confidence,factors:readonly EvaluationFactor[]){this.factors=Object.freeze(factors.map(f=>Object.freeze({...f})));Object.freeze(this);}get value(){return this.confidence.value;}}
export interface EvaluationFactor{readonly name:string;readonly contribution:number;readonly explanation:string;}
export class RecommendationEvaluation{readonly factors:readonly EvaluationFactor[];constructor(readonly confidence:RecommendationConfidence,readonly value:RecommendationValue,readonly effort:RecommendationEffort,readonly risk:RecommendationRisk,readonly priority:RecommendationPriority,readonly strategicRelevance:StrategicRelevance,readonly readyForCEOReview:boolean,factors:readonly EvaluationFactor[]){this.factors=Object.freeze(factors.map(f=>Object.freeze({...f})));Object.freeze(this);}}
export class RecommendedWorkflowReference{constructor(readonly id:string,readonly purpose:string){required(id,"Workflow reference");required(purpose,"Workflow purpose");Object.freeze(this);}}
export class CEODecisionRecord{readonly #at:number;constructor(readonly decision:CEODecision,readonly authorizingIdentityReference:string,at:Date,readonly recommendationVersion:number,readonly rationale?:string){required(authorizingIdentityReference,"Authorizing identity reference");this.#at=instant(at,"CEO decision timestamp");if(rationale!==undefined)required(rationale,"Decision rationale");Object.freeze(this);}get timestamp(){return new Date(this.#at);}}
export class RecommendationOutcomeReference{readonly #measured?:number;constructor(readonly recommendationId:RecommendationId,readonly expectedOutcomeReference?:string,readonly observedOutcomeReference?:string,readonly performanceEvaluationReference?:string,readonly outcomeStatus="Unmeasured",measurementTimestamp?:Date){if(!expectedOutcomeReference&&!observedOutcomeReference&&!performanceEvaluationReference)throw new RecommendationException("Outcome linkage requires a reference","INVALID_OUTCOME");this.#measured=measurementTimestamp?instant(measurementTimestamp,"Measurement timestamp"):undefined;Object.freeze(this);}get measurementTimestamp(){return this.#measured===undefined?undefined:new Date(this.#measured);}}
export interface BusinessRecommendationProperties{id:RecommendationId;version:number;type:RecommendationType;status:RecommendationStatus;objective:RecommendationObjective;businessPackageId:BusinessPackageId;evidence:RecommendationEvidence;evaluation:RecommendationEvaluation;relatedCapabilities?:readonly string[];relatedPatterns?:readonly MarketPattern[];relatedOpportunities?:readonly MarketOpportunity[];relatedPerformanceEvaluations?:readonly PerformanceEvaluation[];relatedBusinessMemory?:readonly string[];recommendedWorkflow?:RecommendedWorkflowReference;outcomes?:readonly RecommendationOutcomeReference[];decision?:CEODecisionRecord;supersedesVersion?:number;supersessionReason?:string;createdAt:Date;evaluatedAt:Date;provenance:Provenance;}
export class BusinessRecommendation{readonly relatedCapabilities;readonly relatedPatterns;readonly relatedOpportunities;readonly relatedPerformanceEvaluations;readonly relatedBusinessMemory;readonly outcomes;readonly #created:number;readonly #evaluated:number;constructor(readonly properties:BusinessRecommendationProperties){if(!Number.isInteger(properties.version)||properties.version<1)throw new RecommendationException("Recommendation version must be positive","INVALID_VERSION");if(properties.objective.businessPackageId.value!==properties.businessPackageId.value)throw new RecommendationException("Recommendation Business Package mismatch","PACKAGE_MISMATCH");this.#created=instant(properties.createdAt,"Creation timestamp");this.#evaluated=instant(properties.evaluatedAt,"Evaluation timestamp");if(this.#evaluated<this.#created)throw new RecommendationException("Evaluation cannot precede creation","INVALID_TIMESTAMP");this.relatedCapabilities=list(properties.relatedCapabilities??[]);this.relatedPatterns=list(properties.relatedPatterns??[]);this.relatedOpportunities=list(properties.relatedOpportunities??[]);this.relatedPerformanceEvaluations=list(properties.relatedPerformanceEvaluations??[]);this.relatedBusinessMemory=list(properties.relatedBusinessMemory??[]);this.outcomes=list(properties.outcomes??[]);Object.freeze(this);}get id(){return this.properties.id;}get version(){return this.properties.version;}get type(){return this.properties.type;}get status(){return this.properties.status;}get objective(){return this.properties.objective;}get businessPackageId(){return this.properties.businessPackageId;}get evidence(){return this.properties.evidence;}get evaluation(){return this.properties.evaluation;}get provenance(){return this.properties.provenance;}get decision(){return this.properties.decision;}get recommendedWorkflow(){return this.properties.recommendedWorkflow;}get createdAt(){return new Date(this.#created);}get evaluatedAt(){return new Date(this.#evaluated);}}
export function evidenceFreshnessScore(status:FreshnessStatus){return status===FreshnessStatus.Current?1:status===FreshnessStatus.Ageing?.75:status===FreshnessStatus.Stale?.35:0;}
