import {AuthorizationDecision,AuthorizationDecisionValue} from "../../core/platform/AuthorizationDecision.ts";
import {BusinessPackageId,Confidence,FreshnessStatus} from "../../intelligence/market/MarketIntelligenceDomain.ts";
import {BusinessRecommendation,CEODecision,CEODecisionRecord,RecommendationCandidate,RecommendationConfidence,RecommendationEffort,RecommendationEvaluation,RecommendationEvidence,RecommendationEvidenceItem,RecommendationEvidenceRole,RecommendationOutcomeReference,RecommendationPriority,RecommendationRisk,RecommendationStatus,RecommendationValue,StrategicRelevance,evidenceFreshnessScore} from "./RecommendationDomain.ts";
import {RecommendationException} from "./RecommendationException.ts";import {RecommendationRepository} from "./RecommendationRepository.ts";import type {RecommendationQuery} from "./RecommendationRepository.ts";

export interface EvaluationInput{effort?:RecommendationEffort;strategicRelevance?:StrategicRelevance;value?:RecommendationValue;timingSensitive?:boolean;}
const rank=<T extends string>(values:readonly T[],score:number):T=>values[Math.max(0,Math.min(values.length-1,Math.round(score)))]!;
export class RecommendationEngine{
 constructor(readonly repository:RecommendationRepository){}
 registerCandidate(c:RecommendationCandidate){return this.repository.storeCandidate(c);}
 aggregateEvidence(items:readonly RecommendationEvidenceItem[]){return new RecommendationEvidence(items);}
 calculateConfidence(e:RecommendationEvidence){const support=e.supporting,contradictions=e.contradicting,average=support.reduce((n,i)=>n+i.evidence.confidence.value*evidenceFreshnessScore(i.evidence.freshness.status),0)/support.length;const diversity=Math.min(e.sourceDiversity,3)/3,independence=Math.min(e.independentSourceCount,3)/3,penalty=contradictions.reduce((n,i)=>n+i.evidence.confidence.value,0)/(Math.max(1,e.items.length)*2);const value=Math.max(0,Math.min(.95,average*.55+diversity*.25+independence*.2-penalty));const factors=[{name:"support",contribution:average*.55,explanation:"Confidence-weighted fresh supporting evidence"},{name:"source-diversity",contribution:diversity*.25,explanation:"Distinct evidence origins"},{name:"independence",contribution:independence*.2,explanation:"Independently identified sources"},{name:"contradiction",contribution:-penalty,explanation:"Visible contradictory evidence penalty"}];return new RecommendationConfidence(new Confidence(Number(value.toFixed(4))),factors);}
 evaluateValue(c:RecommendationCandidate,input:EvaluationInput={}){if(input.value)return input.value;const count=c.relatedOpportunities.length+c.relatedPatterns.length+c.relatedPerformanceEvaluations.length;return count===0?RecommendationValue.Unknown:rank([RecommendationValue.Low,RecommendationValue.Moderate,RecommendationValue.High,RecommendationValue.VeryHigh],Math.min(3,count-1));}
 evaluateEffort(input:EvaluationInput={}){return input.effort??RecommendationEffort.Unknown;}
 evaluateStrategicRelevance(input:EvaluationInput={}){return input.strategicRelevance??StrategicRelevance.Unknown;}
 evaluateRisk(c:RecommendationCandidate,effort:RecommendationEffort){const stale=c.evidence.items.filter(i=>[FreshnessStatus.Stale,FreshnessStatus.Expired].includes(i.evidence.freshness.status)).length,conflicts=c.evidence.contradicting.length;if(!conflicts&&!stale&&effort===RecommendationEffort.Unknown)return RecommendationRisk.Unknown;return rank([RecommendationRisk.Low,RecommendationRisk.Moderate,RecommendationRisk.High,RecommendationRisk.Critical],Math.min(3,conflicts+stale+(effort===RecommendationEffort.VeryHigh?1:0)));}
 evaluatePriority(value:RecommendationValue,effort:RecommendationEffort,risk:RecommendationRisk,confidence:RecommendationConfidence,strategy:StrategicRelevance,timing=false){if(value===RecommendationValue.Unknown||effort===RecommendationEffort.Unknown||strategy===StrategicRelevance.Unknown)return RecommendationPriority.Unranked;const vr=[RecommendationValue.Unknown,RecommendationValue.Low,RecommendationValue.Moderate,RecommendationValue.High,RecommendationValue.VeryHigh].indexOf(value),er=[RecommendationEffort.Unknown,RecommendationEffort.Low,RecommendationEffort.Moderate,RecommendationEffort.High,RecommendationEffort.VeryHigh].indexOf(effort),rr=[RecommendationRisk.Unknown,RecommendationRisk.Low,RecommendationRisk.Moderate,RecommendationRisk.High,RecommendationRisk.Critical].indexOf(risk),sr=[StrategicRelevance.Unknown,StrategicRelevance.Low,StrategicRelevance.Moderate,StrategicRelevance.High,StrategicRelevance.Critical].indexOf(strategy);return rank([RecommendationPriority.Low,RecommendationPriority.Normal,RecommendationPriority.High,RecommendationPriority.Urgent],Math.max(0,Math.min(3,(vr+sr+confidence.value*4-er-rr+(timing?1:0))/3)));}
 evaluateCandidate(c:RecommendationCandidate,input:EvaluationInput={}):RecommendationEvaluation{const confidence=this.calculateConfidence(c.evidence),value=this.evaluateValue(c,input),effort=this.evaluateEffort(input),strategy=this.evaluateStrategicRelevance(input),risk=this.evaluateRisk(c,effort),priority=this.evaluatePriority(value,effort,risk,confidence,strategy,input.timingSensitive);const ready=confidence.value>=.5&&c.evidence.sourceDiversity>=2&&c.evidence.contradicting.length<c.evidence.supporting.length&&risk!==RecommendationRisk.Critical;return new RecommendationEvaluation(confidence,value,effort,risk,priority,strategy,ready,[...confidence.factors,{name:"readiness",contribution:ready?1:0,explanation:"Requires corroboration, diversity, and acceptable contradiction"}]);}
 createRecommendation(c:RecommendationCandidate,evaluation:RecommendationEvaluation,evaluatedAt:Date){return this.repository.store(new BusinessRecommendation({id:c.id,version:1,type:c.type,status:RecommendationStatus.Evaluated,objective:c.objective,businessPackageId:c.businessPackageId,evidence:c.evidence,evaluation,relatedPatterns:c.relatedPatterns,relatedOpportunities:c.relatedOpportunities,relatedPerformanceEvaluations:c.relatedPerformanceEvaluations,relatedBusinessMemory:c.relatedBusinessMemory,createdAt:c.createdAt,evaluatedAt,provenance:c.provenance}));}
 markReadyForCEOReview(r:BusinessRecommendation,tcoReviewReference:string,at:Date){if(!tcoReviewReference.trim())throw new RecommendationException("TCO review routing reference is required","TCO_PATH_REQUIRED");if(!r.evaluation.readyForCEOReview)throw new RecommendationException("Recommendation is not analytically ready","NOT_READY");return this.version(r,{status:RecommendationStatus.ReadyForCEOReview,evaluatedAt:at});}
 attachAdditionalEvidence(r:BusinessRecommendation,item:RecommendationEvidenceItem,at:Date){if(item.role!==RecommendationEvidenceRole.Supporting)throw new RecommendationException("Use contradictory evidence operation","INVALID_EVIDENCE_ROLE");return this.withEvidence(r,item,at);}
 attachContradictoryEvidence(r:BusinessRecommendation,item:RecommendationEvidenceItem,at:Date){if(item.role!==RecommendationEvidenceRole.Contradicting)throw new RecommendationException("Evidence must be contradictory","INVALID_EVIDENCE_ROLE");return this.withEvidence(r,item,at);}
 recordExternallyAuthorizedCEODecision(r:BusinessRecommendation,decision:CEODecision,authorization:AuthorizationDecision,at:Date,rationale?:string){if(r.status!==RecommendationStatus.ReadyForCEOReview)throw new RecommendationException("Only a CEO-review recommendation can receive a decision","INVALID_TRANSITION");if(authorization.decision!==AuthorizationDecisionValue.Allowed||authorization.permission.resourceCategory!=="recommendation"||authorization.permission.action!=="ceo-decision"||authorization.policyIdentifier!=="foundation.ceo-authority")throw new RecommendationException("Explicit CEO authorization is required","UNAUTHORIZED_DECISION");const status=decision===CEODecision.Approved?RecommendationStatus.ApprovedByCEO:decision===CEODecision.Rejected?RecommendationStatus.RejectedByCEO:decision===CEODecision.Deferred?RecommendationStatus.Deferred:RecommendationStatus.AwaitingMoreResearch;return this.version(r,{status,decision:new CEODecisionRecord(decision,authorization.identity.value,at,r.version,rationale),evaluatedAt:at});}
 attachOutcomeReference(r:BusinessRecommendation,outcome:RecommendationOutcomeReference,at:Date){if(!outcome.recommendationId.equals(r.id))throw new RecommendationException("Outcome belongs to another recommendation","OUTCOME_MISMATCH");return this.version(r,{outcomes:[...r.outcomes,outcome],evaluatedAt:at});}
 supersede(r:BusinessRecommendation,reason:string,at:Date){if(!reason.trim())throw new RecommendationException("Supersession reason is required","INVALID_SUPERSESSION");return this.version(r,{status:RecommendationStatus.Superseded,supersedesVersion:r.version,supersessionReason:reason,evaluatedAt:at});}
 retrieve(id:BusinessRecommendation["id"],p:BusinessPackageId){return this.repository.current(id,p);}history(id:BusinessRecommendation["id"],p:BusinessPackageId){return this.repository.history(id,p);}query(q:RecommendationQuery={}){return this.repository.query(q);}
 private withEvidence(r:BusinessRecommendation,item:RecommendationEvidenceItem,at:Date){const evidence=new RecommendationEvidence([...r.evidence.items,item]),candidate=new RecommendationCandidate({...r.properties,id:r.id,evidence,createdAt:r.createdAt});const evaluation=this.evaluateCandidate(candidate,{effort:r.evaluation.effort,strategicRelevance:r.evaluation.strategicRelevance,value:r.evaluation.value});return this.version(r,{evidence,evaluation,status:RecommendationStatus.Evaluated,evaluatedAt:at});}
 private version(r:BusinessRecommendation,changes:Partial<BusinessRecommendation["properties"]>){if(this.repository.current(r.id,r.businessPackageId)!==r)throw new RecommendationException("Changes must apply to the current immutable version","STALE_VERSION");return this.repository.store(new BusinessRecommendation({...r.properties,...changes,version:r.version+1}));}
}
