import type {BusinessPackageId, Freshness, Provenance} from "../../../../intelligence/market/MarketIntelligenceDomain.ts";
import type {ExpectedOutcome, MetricAvailability, PerformanceEvaluation, PerformanceObservation} from "../../performance/PerformanceIntelligenceDomain.ts";

const required=(value:string,name:string)=>{if(!value?.trim())throw new Error(`${name} is required`);return value;};
const immutable=<T>(values:readonly T[]=[]):readonly T[]=>Object.freeze([...values]);
export enum BlogFeedbackSourceCategory {SiteAnalytics="SiteAnalytics",SearchPerformance="SearchPerformance",SearchIndexing="SearchIndexing",ReferralTraffic="ReferralTraffic",BookLinkInteraction="BookLinkInteraction",PinterestReferral="PinterestReferral",ConversionData="ConversionData",AIDiscoveryObservation="AIDiscoveryObservation",ManualObservation="ManualObservation",OtherApprovedSource="OtherApprovedSource"}
export enum BlogFeedbackChannel {Site="Site",Search="Search",Pinterest="Pinterest",Direct="Direct",AIDiscovery="AIDiscovery",BookInteraction="BookInteraction",Conversion="Conversion",Other="Other"}
export enum MeasurementMaturity {Provisional="Provisional",Mature="Mature"}
export enum SearchIndexingState {Indexed="Indexed",NotIndexed="NotIndexed",Discovered="Discovered",Crawled="Crawled",Excluded="Excluded",Unknown="Unknown"}
export enum SearchQueryMatch {ExactCanonicalQuestion="ExactCanonicalQuestion",CloseVariant="CloseVariant",RelatedIntent="RelatedIntent",Unrelated="Unrelated"}
export enum AIDiscoveryResultType {CitedSource="CitedSource",LinkedSource="LinkedSource",ReferencedSource="ReferencedSource",SurfacedResult="SurfacedResult",AnswerSupportingSource="AnswerSupportingSource",NotObservedInThisMeasurement="NotObservedInThisMeasurement",UnavailableToVerify="UnavailableToVerify",Unknown="Unknown"}
export enum BookPlacementType {RelatedBook1="RelatedBook1",RelatedBook2="RelatedBook2",PrimaryBookCTA="PrimaryBookCTA"}
export enum PinterestHeadingSource {H1="H1",H2="H2",H3="H3"}

export interface BlogFeedbackLineageProperties {publishedBlogReference:string;wordpressPostId:string;actualCanonicalUrl:string;draftId:string;draftVersion:number;publicationPackageId:string;publicationPackageVersion:number;contentCreationPlanId:string;contentCreationPlanVersion:number;recommendationId:string;recommendationVersion:number;ceoApprovalReference:string;blogOpportunityId:string;canonicalQuestionId:string;canonicalQuestionText:string;questionClusterId:string;questionPatternId?:string;headings:readonly {headingId:string;level:"H1"|"H2"|"H3";text:string}[];businessPackageId:BusinessPackageId;market:string;language:string;publishedAt:Date;}
export class BlogFeedbackLineage {readonly headings;constructor(readonly properties:BlogFeedbackLineageProperties){for(const [v,n] of [[properties.publishedBlogReference,"Published Blog reference"],[properties.wordpressPostId,"WordPress Post reference"],[properties.actualCanonicalUrl,"Actual canonical URL"],[properties.canonicalQuestionText,"Canonical Question"],[properties.blogOpportunityId,"Blog Opportunity"],[properties.market,"Market"],[properties.language,"Language"]] as const)required(v,n);if(!/^https?:\/\//.test(properties.actualCanonicalUrl))throw new Error("Actual canonical URL must be absolute");if(!Number.isFinite(properties.publishedAt.getTime()))throw new Error("Publication timestamp is invalid");this.headings=immutable(properties.headings);Object.freeze(this);}}
export class BlogMeasurementWindow {constructor(readonly id:string,readonly start:Date,readonly end:Date,readonly maturity:MeasurementMaturity){required(id,"Measurement window");if(!Number.isFinite(start.getTime())||!Number.isFinite(end.getTime())||end<start)throw new Error("Measurement window is invalid");Object.freeze(this);}}
export interface CanonicalMetric {name:string;value?:number;unit:string;availability:MetricAvailability;}
export interface ProviderObservation {provider:string;providerRecordId:string;category:BlogFeedbackSourceCategory;channel:BlogFeedbackChannel;observedAt:Date;window:BlogMeasurementWindow;metrics:readonly CanonicalMetric[];provenance:Provenance;freshness:Freshness;limitations?:readonly string[];}
export class BlogSearchQueryObservation {constructor(readonly originalQuery:string,readonly match:SearchQueryMatch,readonly humanDemandEvidence:boolean,readonly headingId?:string){required(originalQuery,"Observed query");Object.freeze(this);}}
export class BlogSearchDiscoveryObservation {readonly queries;readonly limitations;constructor(readonly provider:string,readonly indexing:SearchIndexingState,queries:readonly BlogSearchQueryObservation[],readonly averagePosition:number|undefined,limitations:readonly string[],readonly observedAt:Date){required(provider,"Search provider");this.queries=immutable(queries);this.limitations=immutable(limitations);Object.freeze(this);}}
export class BlogAIDiscoveryObservation {readonly limitations;constructor(readonly provider:string,readonly observationMethod:string,readonly testedQuestion:string|undefined,readonly result:AIDiscoveryResultType,readonly evidenceReference:string|undefined,readonly observedAt:Date,limitations:readonly string[]){required(provider,"AI discovery provider");required(observationMethod,"Observation method");if(limitations.length===0)throw new Error("AI discovery limitations are required");this.limitations=immutable(limitations);Object.freeze(this);}get humanDemandEvidence(){return false;}}
export class BlogBookLinkInteraction {constructor(readonly bookId:string,readonly editionId:string,readonly placement:BookPlacementType,readonly actualUrl:string,readonly clicks:number|undefined,readonly availability:MetricAvailability,readonly headingId?:string){required(bookId,"Book identifier");required(editionId,"Edition identifier");required(actualUrl,"Book URL");Object.freeze(this);}get sales(){return undefined;}}
export class BlogPinterestReferralObservation {constructor(readonly pinId:string,readonly promotionCandidateId:string,readonly headingSource:PinterestHeadingSource,readonly blogUrl:string,readonly sessions:number|undefined,readonly clicks:number|undefined){required(pinId,"Pin identifier");Object.freeze(this);}}
export interface BlogLearningInput {direction:"Positive"|"Negative"|"Inconclusive"|"Contradictory";performanceEvaluation?:PerformanceEvaluation;questionReference:string;opportunityReference:string;recommendationReference:string;patternReevaluationProposed:boolean;articleUpdateRecommendationProposed:boolean;libraryMutationAllowed:false;blogMutationAllowed:false;trustMutationAllowed:false;}
export interface BlogPerformanceResult {lineage:BlogFeedbackLineage;observations:readonly PerformanceObservation[];search:readonly BlogSearchDiscoveryObservation[];aiDiscovery:readonly BlogAIDiscoveryObservation[];bookInteractions:readonly BlogBookLinkInteraction[];pinterest:readonly BlogPinterestReferralObservation[];expectedOutcome?:ExpectedOutcome;evaluation?:PerformanceEvaluation;learning?:BlogLearningInput;}
export interface BlogSearchDiscoveryReadModel {indexed:SearchIndexingState;impressions:number|undefined;clicks:number|undefined;observedQueries:readonly string[];canonicalQuestionMatches:number;relatedQuestionMatches:number;markets:readonly string[];availability:MetricAvailability;}
export interface BlogAIDiscoveryReadModel {observedProviders:readonly string[];latestObservation?:Date;results:Readonly<Record<string,number>>;queriesTested:readonly string[];evidenceCount:number;limitations:readonly string[];}
export interface BlogBookInteractionReadModel {relatedBook1:number|undefined;relatedBook2:number|undefined;primaryBookCTA:number|undefined;availability:MetricAvailability;}
export interface BlogPerformanceReadModel {publishedUrl:string;publishedAt:Date;search:BlogSearchDiscoveryReadModel;aiDiscovery:BlogAIDiscoveryReadModel;books:BlogBookInteractionReadModel;channels:readonly BlogFeedbackChannel[];measurementMaturity:readonly MeasurementMaturity[];}
export const BLOG_PERFORMANCE_EVENTS=Object.freeze(["BlogPerformanceMeasurementRequested","BlogPerformanceCollectionStarted","BlogPerformanceCollected","BlogSearchDiscoveryObserved","BlogSearchQueryObserved","BlogAIDiscoveryObserved","BlogBookLinkInteractionObserved","BlogPinterestReferralObserved","BlogPerformanceObservationCreated","BlogPerformanceEvaluationCompleted","BlogContinuousLearningTriggered","BlogPerformanceMeasurementFailed"] as const);
