import {Confidence, Evidence, EvidenceId, EvidenceStatus, ObservationId} from "../../../../intelligence/market/MarketIntelligenceDomain.ts";
import {MeasurementWindow, MetricAvailability, PerformanceDimension, PerformanceMetric, PerformanceMetricType, PerformanceObservation, PerformanceRecordId, SubjectReference} from "../../performance/PerformanceIntelligenceDomain.ts";
import {PerformanceIntelligenceService} from "../../performance/PerformanceIntelligenceService.ts";
import {BlogFeedbackChannel, BookPlacementType, MeasurementMaturity, SearchIndexingState, SearchQueryMatch} from "./BlogPerformanceFeedbackDomain.ts";
import type {BlogAIDiscoveryObservation, BlogBookLinkInteraction, BlogFeedbackLineage, BlogPerformanceReadModel, BlogPinterestReferralObservation, BlogSearchDiscoveryObservation, ProviderObservation} from "./BlogPerformanceFeedbackDomain.ts";

export interface BlogFeedbackEventSink {emit(name:string,payload:Readonly<Record<string,string>>):void;}
export interface BlogFeedbackAuditSink {record(action:string,details:Readonly<Record<string,string>>):void;}
export class BlogPerformanceFeedbackService {
 readonly #seen=new Set<string>();readonly #performance:PerformanceObservation[]=[];readonly #search:BlogSearchDiscoveryObservation[]=[];readonly #ai:BlogAIDiscoveryObservation[]=[];readonly #books:BlogBookLinkInteraction[]=[];readonly #pinterest:BlogPinterestReferralObservation[]=[];
 constructor(readonly lineage:BlogFeedbackLineage,private readonly intelligence:PerformanceIntelligenceService,private readonly events?:BlogFeedbackEventSink,private readonly audit?:BlogFeedbackAuditSink){}
 static eligible(state:string,lineage?:BlogFeedbackLineage){return state==="Published"&&!!lineage;}
 collect(input:ProviderObservation):PerformanceObservation|undefined {if(this.#seen.has(`${input.provider}:${input.providerRecordId}`))return undefined;if(input.metrics.length===0)throw new Error("Provider observation must contain explicit available or unavailable metrics");this.#seen.add(`${input.provider}:${input.providerRecordId}`);this.events?.emit("BlogPerformanceCollectionStarted",this.safe(input));const subject=new SubjectReference(this.lineage.properties.publishedBlogReference,PerformanceDimension.Content),window=new MeasurementWindow(input.window.start,input.window.end),confidence=new Confidence(1),evidence=new Evidence(new EvidenceId(`blog-feedback:${input.providerRecordId}`),[new ObservationId(`raw:${input.providerRecordId}`)],input.provenance,input.observedAt,confidence,input.freshness,EvidenceStatus.Active);const metrics=input.metrics.map(metric=>new PerformanceMetric({type:this.metricType(metric.name),customType:this.metricType(metric.name)===PerformanceMetricType.Custom?metric.name:undefined,value:metric.value,unit:metric.unit,measuredAt:input.observedAt,window,provenance:input.provenance,availability:metric.availability,businessPackageId:this.lineage.properties.businessPackageId,subject,confidence}));const observation=new PerformanceObservation({id:new PerformanceRecordId(`blog:${input.provider}:${input.providerRecordId}`),subject,businessPackageId:this.lineage.properties.businessPackageId,metrics,measuredAt:input.observedAt,window,evidence:[evidence],provenance:input.provenance,confidence,freshness:input.freshness});this.intelligence.registerObservation(observation);this.#performance.push(observation);this.events?.emit("BlogPerformanceObservationCreated",this.safe(input));this.audit?.record("Blog performance observation normalized",this.safe(input));return observation;}
 observeSearch(value:BlogSearchDiscoveryObservation){this.#search.push(value);this.events?.emit("BlogSearchDiscoveryObserved",{publishedBlogReference:this.lineage.properties.publishedBlogReference,provider:value.provider});return value;}
 observeAI(value:BlogAIDiscoveryObservation){this.#ai.push(value);this.events?.emit("BlogAIDiscoveryObserved",{publishedBlogReference:this.lineage.properties.publishedBlogReference,provider:value.provider});return value;}
 observeBook(value:BlogBookLinkInteraction){this.#books.push(value);this.events?.emit("BlogBookLinkInteractionObserved",{publishedBlogReference:this.lineage.properties.publishedBlogReference,bookId:value.bookId});return value;}
 observePinterest(value:BlogPinterestReferralObservation){if(value.blogUrl!==this.lineage.properties.actualCanonicalUrl)throw new Error("Pinterest referral Blog URL does not match published canonical URL");this.#pinterest.push(value);this.events?.emit("BlogPinterestReferralObserved",{publishedBlogReference:this.lineage.properties.publishedBlogReference,pinId:value.pinId});return value;}
 matchQuery(original:string,variants:readonly string[]=[],related:readonly string[]=[]){const normalize=(x:string)=>x.trim().toLocaleLowerCase(this.lineage.properties.language).replace(/[?!.]+$/g,"");const q=normalize(original),canonical=normalize(this.lineage.properties.canonicalQuestionText);if(q===canonical)return SearchQueryMatch.ExactCanonicalQuestion;if(variants.some(x=>normalize(x)===q))return SearchQueryMatch.CloseVariant;if(related.some(x=>normalize(x)===q))return SearchQueryMatch.RelatedIntent;return SearchQueryMatch.Unrelated;}
 readModel():BlogPerformanceReadModel {const metric=(name:string)=>this.#performance.flatMap(x=>x.metrics).find(x=>x.customType===name||x.type===this.metricType(name));const total=(placement:BookPlacementType)=>{const values=this.#books.filter(x=>x.placement===placement&&x.clicks!==undefined).map(x=>x.clicks!);return values.length?values.reduce((a,b)=>a+b,0):undefined;};const latest=[...this.#ai].sort((a,b)=>b.observedAt.getTime()-a.observedAt.getTime())[0];const results:Record<string,number>={};for(const x of this.#ai)results[x.result]=(results[x.result]??0)+1;return Object.freeze({publishedUrl:this.lineage.properties.actualCanonicalUrl,publishedAt:this.lineage.properties.publishedAt,search:{indexed:this.#search.at(-1)?.indexing??SearchIndexingState.Unknown,impressions:metric("Impressions")?.value,clicks:metric("SearchClicks")?.value,observedQueries:Object.freeze(this.#search.flatMap(x=>x.queries.map(q=>q.originalQuery))),canonicalQuestionMatches:this.#search.flatMap(x=>x.queries).filter(x=>x.match===SearchQueryMatch.ExactCanonicalQuestion).length,relatedQuestionMatches:this.#search.flatMap(x=>x.queries).filter(x=>x.match===SearchQueryMatch.RelatedIntent).length,markets:[this.lineage.properties.market],availability:metric("Impressions")?.availability??MetricAvailability.Unavailable},aiDiscovery:{observedProviders:Object.freeze([...new Set(this.#ai.map(x=>x.provider))]),latestObservation:latest?.observedAt,results:Object.freeze(results),queriesTested:Object.freeze(this.#ai.flatMap(x=>x.testedQuestion?[x.testedQuestion]:[])),evidenceCount:this.#ai.filter(x=>x.evidenceReference).length,limitations:Object.freeze(this.#ai.flatMap(x=>x.limitations))},books:{relatedBook1:total(BookPlacementType.RelatedBook1),relatedBook2:total(BookPlacementType.RelatedBook2),primaryBookCTA:total(BookPlacementType.PrimaryBookCTA),availability:this.#books.length?MetricAvailability.Available:MetricAvailability.Unavailable},channels:Object.freeze([...new Set([...this.#performance.map(()=>BlogFeedbackChannel.Site),...this.#search.map(()=>BlogFeedbackChannel.Search),...this.#ai.map(()=>BlogFeedbackChannel.AIDiscovery),...this.#books.map(()=>BlogFeedbackChannel.BookInteraction),...this.#pinterest.map(()=>BlogFeedbackChannel.Pinterest)])]),measurementMaturity:Object.freeze([...new Set(this.#performance.map(x=>x.window.durationMilliseconds===0?MeasurementMaturity.Provisional:MeasurementMaturity.Mature))])});}
 private metricType(name:string){return ({PageViews:PerformanceMetricType.Traffic,Impressions:PerformanceMetricType.Impressions,Clicks:PerformanceMetricType.Clicks,SearchClicks:PerformanceMetricType.Clicks,CTR:PerformanceMetricType.CTR,Sessions:PerformanceMetricType.Traffic,Conversions:PerformanceMetricType.Conversions} as Record<string,PerformanceMetricType>)[name]??PerformanceMetricType.Custom;}
 private safe(input:ProviderObservation){return Object.freeze({publishedBlogReference:this.lineage.properties.publishedBlogReference,provider:input.provider,sourceCategory:input.category,measurementWindow:input.window.id,collectionOutcome:"Collected"});}
}
