import {AuditEvent} from "../../core/platform/AuditEvent.ts";
import {AuditEventType} from "../../core/platform/AuditEventType.ts";
import type {AuditRecorder} from "../../core/platform/AuditRecorder.ts";
import {Event} from "../../core/platform/Event.ts";
import type {EventBus} from "../../core/platform/EventBus.ts";
import {EventContext} from "../../core/platform/EventContext.ts";
import {EventId} from "../../core/platform/EventId.ts";
import {EventType} from "../../core/platform/EventType.ts";
import type {BusinessPackageId} from "../../intelligence/market/MarketIntelligenceDomain.ts";
import type {ControlledCredentialMaterial} from "../../security/authentication/ExternalAuthenticationDomain.ts";
import {CredentialId,type CredentialMetadata,CredentialStatus} from "../../security/credentials/CredentialVault.ts";
import {BlogPublicationPackageId,BlogPublicationPackageState,type BlogPublicationPackage} from "../../business/market/blog/publication/BlogPublicationDomain.ts";
import {BlogPublicationPackageRepository} from "../../business/market/blog/publication/BlogPublicationPackageRepository.ts";

const required=(value:string|undefined,name:string)=>{if(!value?.trim())throw new BlogPublishingException(`${name} is required`,WordPressPublishFailureType.InvalidRequest);return value;};
const sanitized=(value:string)=>value.replace(/(?:authorization|application[_ -]?password|access[_ -]?token|refresh[_ -]?token|api[_ -]?key|master[_ -]?password|password)\s*[:=]\s*\S+/gi,"[redacted]");
const immutable=<T>(values:readonly T[])=>Object.freeze([...values]);

export class BlogPublicationId{constructor(readonly value:string){required(value,"Publication identifier");Object.freeze(this);}}
export enum BlogPublishState{Pending="Pending",Claimed="Claimed",Authenticating="Authenticating",Publishing="Publishing",Published="Published",DryRun="DryRun",AuthenticationRequired="AuthenticationRequired",PermissionDenied="PermissionDenied",RateLimited="RateLimited",RetryPending="RetryPending",VerificationRequired="VerificationRequired",CanonicalReviewRequired="CanonicalReviewRequired",Failed="Failed",Cancelled="Cancelled"}
export enum WordPressPublishFailureType{InvalidRequest="InvalidRequest",NotEligible="NotEligible",AuthenticationRequired="AuthenticationRequired",InvalidCredential="InvalidCredential",ReauthorizationRequired="ReauthorizationRequired",PermissionDenied="PermissionDenied",RateLimited="RateLimited",ProviderTemporary="ProviderTemporary",NetworkBeforeWrite="NetworkBeforeWrite",UnknownOutcome="UnknownOutcome",SlugConflict="SlugConflict",RetryLimit="RetryLimit",DuplicatePrevented="DuplicatePrevented",ClaimUnavailable="ClaimUnavailable"}
export class BlogPublishingException extends Error{constructor(message:string,readonly failureType:WordPressPublishFailureType){super(sanitized(message));this.name="BlogPublishingException";}}
export class WordPressPublishFailure{constructor(readonly type:WordPressPublishFailureType,readonly safeMessage:string,readonly providerReference?:string,readonly retryAfter?:Date){required(safeMessage,"Safe failure message");Object.freeze(this);}}
export class BlogExecutionClaim{constructor(readonly publicationId:BlogPublicationId,readonly claimId:string,readonly state:"Claimed"|"Executing"|"Released"|"Completed"|"RecoveryPending",readonly claimedAt:Date){Object.freeze(this);}}
export class PublishedBlogReference{constructor(readonly publicationId:BlogPublicationId,readonly wordpressPostId:string,readonly siteReference:string,readonly proposedCanonicalUrl:string,readonly actualCanonicalUrl:string,readonly publishedAt:Date,readonly providerReference:string){for(const [v,n] of [[wordpressPostId,"WordPress Post identifier"],[actualCanonicalUrl,"Actual canonical URL"],[providerReference,"Provider reference"]] as const)required(v,n);Object.freeze(this);}}
export class BlogPublishRequest{readonly headings;readonly categoryReferences;readonly tagReferences;constructor(readonly publicationId:BlogPublicationId,readonly publicationPackageId:BlogPublicationPackageId,readonly publicationPackageVersion:number,readonly draftId:string,readonly draftVersion:number,readonly businessPackageId:BusinessPackageId,readonly siteReference:string,readonly credentialId:CredentialId,readonly desiredStatus:string,readonly renderedContent:string,readonly h1:string,readonly metadata:Readonly<Record<string,string>>,readonly slug:string,readonly proposedCanonicalUrl:string,readonly structuredData:readonly Readonly<Record<string,unknown>>[],readonly language:string,readonly authorReference:string|undefined,categoryReferences:readonly string[],tagReferences:readonly string[],headings:readonly {headingId:string;level:"H1"|"H2"|"H3";text:string}[],readonly correlationIdentifier:string,readonly executionTimestamp:Date,readonly idempotencyKey:string){this.categoryReferences=immutable(categoryReferences);this.tagReferences=immutable(tagReferences);this.headings=immutable(headings);for(const [v,n] of [[siteReference,"WordPress site"],[renderedContent,"Rendered content"],[h1,"H1"],[slug,"Slug"],[correlationIdentifier,"Correlation identifier"],[idempotencyKey,"Idempotency key"]] as const)required(v,n);Object.freeze(this);}}
export class BlogPublishAttempt{constructor(readonly publicationId:BlogPublicationId,readonly attemptId:string,readonly number:number,readonly state:BlogPublishState,readonly startedAt:Date,readonly completedAt:Date,readonly providerCorrelation:string,readonly failure?:WordPressPublishFailure,readonly publishedReference?:PublishedBlogReference){Object.freeze(this);}}
export class BlogPublishResult{readonly failures;constructor(readonly publicationId:BlogPublicationId,readonly state:BlogPublishState,readonly packageId:BlogPublicationPackageId,readonly packageVersion:number,readonly draftVersion:number,readonly businessPackageId:BusinessPackageId,readonly correlationIdentifier:string,readonly publishedReference:PublishedBlogReference|undefined,failures:readonly WordPressPublishFailure[],readonly providerMetadata:Readonly<Record<string,string>>,readonly preview?:BlogPublishRequest){this.failures=immutable(failures);Object.freeze(this);}}

export type WordPressProviderOutcome=
 |{kind:"Published";postId:string;actualCanonicalUrl:string;providerReference:string;publishedAt?:Date;metadata?:Readonly<Record<string,string>>}
 |{kind:"AuthenticationRequired"|"InvalidCredential"|"ReauthorizationRequired"|"PermissionDenied"|"RateLimited"|"TemporaryFailure"|"NetworkBeforeWrite"|"UnknownOutcome"|"SlugConflict";safeMessage:string;providerReference?:string;retryAfter?:Date;actualCanonicalUrl?:string};
export interface WordPressOfficialWriteTransport{createPost(request:BlogPublishRequest,credential:ControlledCredentialMaterial):Promise<WordPressProviderOutcome>;}
export interface WordPressPublishAuthentication{authorize(credentialId:CredentialId,businessPackageId:BusinessPackageId,siteReference:string,capability:"posts:write",correlationIdentifier:string):Promise<{metadata:CredentialMetadata;credential:ControlledCredentialMaterial}>;reauthorizationRequired(credentialId:CredentialId,publicationId:BlogPublicationId,correlationIdentifier:string):Promise<void>|void;}
export interface BlogPublishingAuthority{authorize(packageValue:BlogPublicationPackage,capability:"BlogPublishing",at:Date):{allowed:boolean;mode:"CEOApprovalRequired"|"ConditionalAutonomy"|"Autonomous";evidenceReference:string};}
export interface WordPressPublicationReconciler{verify(request:BlogPublishRequest):Promise<{status:"Found";postId:string;actualCanonicalUrl:string;providerReference:string;publishedAt:Date}|{status:"Absent"}|{status:"Unknown"}>;}
export interface WordPressSiteConfiguration{businessPackageId:BusinessPackageId;siteReference:string;credentialId:CredentialId;writeCapability:"posts:write";publicationStatus:string;categoryReferences?:readonly string[];tagReferences?:readonly string[];featuredImageRequired?:boolean;featuredImageReference?:string;}

export class BlogPublishingRepository{
 readonly #results=new Map<string,BlogPublishResult>();readonly #attempts=new Map<string,BlogPublishAttempt[]>();readonly #claims=new Map<string,BlogExecutionClaim>();
 claim(id:BlogPublicationId,claimId:string,at:Date){const existing=this.#claims.get(id.value);if(existing&&!["Released"].includes(existing.state))return undefined;const claim=new BlogExecutionClaim(id,claimId,"Claimed",at);this.#claims.set(id.value,claim);return claim;}
 transitionClaim(claim:BlogExecutionClaim,state:BlogExecutionClaim["state"]){if(this.#claims.get(claim.publicationId.value)?.claimId!==claim.claimId)throw new BlogPublishingException("Execution claim is no longer valid",WordPressPublishFailureType.ClaimUnavailable);const next=new BlogExecutionClaim(claim.publicationId,claim.claimId,state,claim.claimedAt);this.#claims.set(claim.publicationId.value,next);return next;}
 claimFor(id:BlogPublicationId){return this.#claims.get(id.value);} result(id:BlogPublicationId){return this.#results.get(id.value);} save(result:BlogPublishResult){this.#results.set(result.publicationId.value,result);return result;} addAttempt(attempt:BlogPublishAttempt){this.#attempts.set(attempt.publicationId.value,[...(this.#attempts.get(attempt.publicationId.value)??[]),attempt]);} attempts(id:BlogPublicationId){return immutable(this.#attempts.get(id.value)??[]);} results(){return immutable([...this.#results.values()]);}
}
export class WordPressBlogPublisher{constructor(private readonly transport:WordPressOfficialWriteTransport){}publish(request:BlogPublishRequest,credential:ControlledCredentialMaterial){return this.transport.createPost(request,credential);}}

export class BlogPublishingService{
 #sequence=0;constructor(private readonly packages:BlogPublicationPackageRepository,private readonly repository:BlogPublishingRepository,private readonly authentication:WordPressPublishAuthentication,private readonly authority:BlogPublishingAuthority,private readonly publisher:WordPressBlogPublisher,private readonly site:WordPressSiteConfiguration,private readonly retryLimit:number,private readonly reconciler?:WordPressPublicationReconciler,private readonly events?:EventBus,private readonly audit?:AuditRecorder,private readonly clock=()=>new Date()){if(retryLimit<1)throw new BlogPublishingException("Retry policy is invalid",WordPressPublishFailureType.InvalidRequest);}
 async execute(publicationId:BlogPublicationId,packageId:BlogPublicationPackageId,packageVersion:number,options:{dryRun?:boolean}={}){const prior=this.repository.result(publicationId);if(prior?.state===BlogPublishState.Published||prior?.state===BlogPublishState.VerificationRequired)return prior;const value=this.eligible(packageId,packageVersion,this.clock());if(this.repository.attempts(publicationId).length>=this.retryLimit)return this.fail(publicationId,value,BlogPublishState.Failed,new WordPressPublishFailure(WordPressPublishFailureType.RetryLimit,"Retry limit reached"));const claim=this.repository.claim(publicationId,`claim-${++this.#sequence}`,this.clock());if(!claim)throw new BlogPublishingException("Publication already has an active execution claim",WordPressPublishFailureType.ClaimUnavailable);this.report("BlogPublishRequested",publicationId,value);this.report("BlogExecutionClaimed",publicationId,value);let auth;try{auth=await this.authentication.authorize(this.site.credentialId,value.businessPackageId,this.site.siteReference,"posts:write",value.correlationIdentifier);this.verifyCredential(auth.metadata,value);}catch(error){this.repository.transitionClaim(claim,"RecoveryPending");await this.authentication.reauthorizationRequired(this.site.credentialId,publicationId,value.correlationIdentifier);return this.fail(publicationId,value,BlogPublishState.AuthenticationRequired,new WordPressPublishFailure(this.authFailure(error),sanitized(error instanceof Error?error.message:"Authentication required")));}const request=this.request(publicationId,value,this.clock());if(options.dryRun){this.repository.transitionClaim(claim,"Released");return this.save(publicationId,value,BlogPublishState.DryRun,undefined,[],{},request);}
  this.eligible(packageId,packageVersion,this.clock());this.repository.transitionClaim(claim,"Executing");this.report("BlogPublishingStarted",publicationId,value);const number=this.repository.attempts(publicationId).length+1,started=this.clock();let outcome:WordPressProviderOutcome;try{outcome=await this.publisher.publish(request,auth.credential);}catch(error){outcome={kind:"UnknownOutcome",safeMessage:sanitized(error instanceof Error?error.message:"Provider outcome is unknown")};}const completed=this.clock();if(outcome.kind==="Published"){if(this.slugFrom(outcome.actualCanonicalUrl)!==value.slug.value)return this.providerFailure(publicationId,value,claim,request,number,started,completed,{kind:"SlugConflict",safeMessage:"WordPress returned a different canonical slug",providerReference:outcome.providerReference,actualCanonicalUrl:outcome.actualCanonicalUrl});const ref=new PublishedBlogReference(publicationId,outcome.postId,this.site.siteReference,value.canonicalURL.preview,outcome.actualCanonicalUrl,outcome.publishedAt??completed,outcome.providerReference);this.repository.addAttempt(new BlogPublishAttempt(publicationId,`attempt-${publicationId.value}-${number}`,number,BlogPublishState.Published,started,completed,request.idempotencyKey,undefined,ref));this.repository.transitionClaim(claim,"Completed");const result=this.save(publicationId,value,BlogPublishState.Published,ref,[],outcome.metadata??{});this.report("BlogPublished",publicationId,value,{postId:ref.wordpressPostId,canonicalUrl:ref.actualCanonicalUrl,h1:value.exactH1,headings:JSON.stringify(value.renderedArticle.headingLineage)});return result;}return this.providerFailure(publicationId,value,claim,request,number,started,completed,outcome);
 }
 async reconcile(id:BlogPublicationId){const current=this.repository.result(id);if(!current||current.state!==BlogPublishState.VerificationRequired||!current.preview||!this.reconciler)throw new BlogPublishingException("Publication cannot be reconciled",WordPressPublishFailureType.InvalidRequest);const verified=await this.reconciler.verify(current.preview);if(verified.status!=="Found")return current;const value=this.eligible(current.packageId,current.packageVersion,this.clock()),ref=new PublishedBlogReference(id,verified.postId,this.site.siteReference,value.canonicalURL.preview,verified.actualCanonicalUrl,verified.publishedAt,verified.providerReference),claim=this.repository.claimFor(id)!;this.repository.transitionClaim(claim,"Completed");const result=this.save(id,value,BlogPublishState.Published,ref,current.failures,{});this.report("BlogPublished",id,value,{postId:ref.wordpressPostId,canonicalUrl:ref.actualCanonicalUrl,h1:value.exactH1,headings:JSON.stringify(value.renderedArticle.headingLineage)});return result;}
 cancel(id:BlogPublicationId,packageId:BlogPublicationPackageId,version:number){const claim=this.repository.claimFor(id);if(claim?.state==="Executing")throw new BlogPublishingException("Cancellation cannot be guaranteed during an external write",WordPressPublishFailureType.UnknownOutcome);const value=this.eligible(packageId,version,this.clock());if(claim)this.repository.transitionClaim(claim,"Released");this.report("BlogPublishCancelled",id,value);return this.save(id,value,BlogPublishState.Cancelled,undefined,[],{});}
 status(){const last=this.repository.results().at(-1);return Object.freeze({currentPublication:last?.publicationId.value,articleH1:last?.preview?.h1,status:last?.state??BlogPublishState.Pending,wordpressSite:this.site.siteReference,authentication:last?.state===BlogPublishState.AuthenticationRequired?"Attention Required":"OK",lastPublication:last?.state===BlogPublishState.Published?"Success":last?"Failure":undefined,canonicalUrl:last?.publishedReference?.actualCanonicalUrl,publisher:last&&![BlogPublishState.Published,BlogPublishState.DryRun].includes(last.state)?"Degraded":"Online"});}
 private eligible(id:BlogPublicationPackageId,version:number,at:Date){const exact=this.packages.get(id,version),current=this.packages.get(id);if(!exact||current!==exact||exact.version.value!==version||exact.state!==BlogPublicationPackageState.ReadyForWordPressPublishing)throw new BlogPublishingException("Exact current Publication Package is not ready",WordPressPublishFailureType.NotEligible);if(exact.businessPackageId.value!==this.site.businessPackageId.value||!this.site.siteReference.trim())throw new BlogPublishingException("Business Package and WordPress site isolation failed",WordPressPublishFailureType.NotEligible);if(!exact.lineage.blogDraftApprovalReference.trim()||exact.exactH1!==exact.lineage.canonicalQuestionText||exact.renderedArticle.headingLineage[0]?.text!==exact.exactH1||exact.renderedArticle.headingLineage[0]?.level!=="H1")throw new BlogPublishingException("Exact Draft approval and H1 lineage are invalid",WordPressPublishFailureType.NotEligible);const decision=this.authority.authorize(exact,"BlogPublishing",at);if(!decision.allowed||decision.mode!=="CEOApprovalRequired"||!decision.evidenceReference.trim())throw new BlogPublishingException("Current CEO Blog publishing authority is required",WordPressPublishFailureType.NotEligible);if(this.site.featuredImageRequired&&!this.site.featuredImageReference)throw new BlogPublishingException("Required approved featured image is unavailable",WordPressPublishFailureType.NotEligible);required(exact.renderedArticle.body,"Rendered content");required(exact.exactH1,"H1");required(exact.slug.value,"Slug");return exact;}
 private request(id:BlogPublicationId,p:BlogPublicationPackage,at:Date){return new BlogPublishRequest(id,p.id,p.version.value,p.draftId,p.draftVersion,p.businessPackageId,this.site.siteReference,this.site.credentialId,this.site.publicationStatus,p.renderedArticle.body,p.exactH1,Object.freeze({title:p.metadata.metaTitle,description:p.metadata.metaDescription}),p.slug.value,p.canonicalURL.preview,p.structuredData.objects,p.language,p.authorReference,this.site.categoryReferences??[],this.site.tagReferences??[],p.renderedArticle.headingLineage,p.correlationIdentifier,at,`blog:${id.value}:${p.id.value}:${p.version.value}`);}
 private verifyCredential(m:CredentialMetadata,p:BlogPublicationPackage){if(m.status!==CredentialStatus.Active)throw new BlogPublishingException("Credential is not active",WordPressPublishFailureType.InvalidCredential);if(!m.businessPackageScopes.includes(p.businessPackageId.value)||m.accountReference!==this.site.siteReference)throw new BlogPublishingException("Credential scope does not match the WordPress site",WordPressPublishFailureType.AuthenticationRequired);if(!m.capabilityScopes.includes("posts:write"))throw new BlogPublishingException("Credential lacks WordPress write permission",WordPressPublishFailureType.PermissionDenied);}
 private authFailure(error:unknown){return error instanceof BlogPublishingException?error.failureType:WordPressPublishFailureType.AuthenticationRequired;}
 private providerFailure(id:BlogPublicationId,p:BlogPublicationPackage,claim:BlogExecutionClaim,request:BlogPublishRequest,number:number,started:Date,completed:Date,o:Exclude<WordPressProviderOutcome,{kind:"Published"}>){const map:Record<typeof o.kind,[BlogPublishState,WordPressPublishFailureType,string]>={AuthenticationRequired:[BlogPublishState.AuthenticationRequired,WordPressPublishFailureType.AuthenticationRequired,"BlogPublishAuthenticationRequired"],InvalidCredential:[BlogPublishState.AuthenticationRequired,WordPressPublishFailureType.InvalidCredential,"BlogPublishAuthenticationRequired"],ReauthorizationRequired:[BlogPublishState.AuthenticationRequired,WordPressPublishFailureType.ReauthorizationRequired,"BlogPublishAuthenticationRequired"],PermissionDenied:[BlogPublishState.PermissionDenied,WordPressPublishFailureType.PermissionDenied,"BlogPublishPermissionDenied"],RateLimited:[BlogPublishState.RateLimited,WordPressPublishFailureType.RateLimited,"BlogPublishRateLimited"],TemporaryFailure:[BlogPublishState.RetryPending,WordPressPublishFailureType.ProviderTemporary,"BlogPublishFailed"],NetworkBeforeWrite:[BlogPublishState.RetryPending,WordPressPublishFailureType.NetworkBeforeWrite,"BlogPublishRetryRequested"],UnknownOutcome:[BlogPublishState.VerificationRequired,WordPressPublishFailureType.UnknownOutcome,"BlogPublishVerificationRequired"],SlugConflict:[BlogPublishState.CanonicalReviewRequired,WordPressPublishFailureType.SlugConflict,"BlogPublishCanonicalReviewRequired"]};const [state,type,event]=map[o.kind],failure=new WordPressPublishFailure(type,sanitized(o.safeMessage),o.providerReference,o.retryAfter);this.repository.addAttempt(new BlogPublishAttempt(id,`attempt-${id.value}-${number}`,number,state,started,completed,request.idempotencyKey,failure));this.repository.transitionClaim(claim,state===BlogPublishState.VerificationRequired?"RecoveryPending":"Released");const result=this.save(id,p,state,undefined,[failure],Object.freeze({...(o.actualCanonicalUrl?{actualCanonicalUrl:o.actualCanonicalUrl}:{})}),request);this.report(event,id,p);return result;}
 private fail(id:BlogPublicationId,p:BlogPublicationPackage,state:BlogPublishState,failure:WordPressPublishFailure){return this.save(id,p,state,undefined,[failure],{});}
 private save(id:BlogPublicationId,p:BlogPublicationPackage,state:BlogPublishState,ref:PublishedBlogReference|undefined,failures:readonly WordPressPublishFailure[],metadata:Readonly<Record<string,string>>,preview?:BlogPublishRequest){return this.repository.save(new BlogPublishResult(id,state,p.id,p.version.value,p.draftVersion,p.businessPackageId,p.correlationIdentifier,ref,failures,metadata,preview));}
 private slugFrom(url:string){try{return new URL(url).pathname.replace(/\/$/,"").split("/").at(-1)??"";}catch{return "";}}
 private report(name:string,id:BlogPublicationId,p:BlogPublicationPackage,extra:Record<string,string>={}){const context={publicationId:id.value,packageId:p.id.value,packageVersion:String(p.version.value),draftId:p.draftId,draftVersion:String(p.draftVersion),businessPackageId:p.businessPackageId.value,correlationIdentifier:p.correlationIdentifier,...extra};this.events?.publish(new Event({id:new EventId(`${id.value}:${name}:${++this.#sequence}`),type:new EventType(name),timestamp:this.clock(),source:"BlogPublishingService",correlationId:p.correlationIdentifier,context:new EventContext(context)}));this.audit?.append(new AuditEvent({id:`${id.value}:${name}:${this.#sequence}`,timestamp:this.clock(),type:AuditEventType.WorkflowEvent,source:"BlogPublishingService",action:name,result:"recorded",responsibleIdentity:"TCO",relatedTaskOrWorkflowId:p.correlationIdentifier,context}));}
}
