import type {BusinessPackageId} from "../../../../intelligence/market/MarketIntelligenceDomain.ts";
import type {BlogContentCreationPlan} from "../planning/BlogContentCreationPlanDomain.ts";
import {BlogHeadingLevel} from "../planning/BlogContentCreationPlanDomain.ts";

const freeze=<T>(items:readonly T[])=>Object.freeze([...items]);
const requireText=(value:string,name:string)=>{if(!value?.trim())throw new BlogWriterException(`${name} is required`,"INVALID_REQUEST");return value;};
export class BlogWriterException extends Error{constructor(message:string,readonly code="BLOG_WRITER_FAILURE"){super(message);this.name="BlogWriterException";}}
export class BlogDraftId{constructor(readonly value:string){requireText(value,"Draft identifier");Object.freeze(this);}}
export class BlogDraftVersion{constructor(readonly value:number){if(!Number.isInteger(value)||value<1)throw new BlogWriterException("Draft version is invalid","INVALID_VERSION");Object.freeze(this);}}
export enum BlogDraftState{ValidationRequired="ValidationRequired",RevisionRequired="RevisionRequired",ReadyForCEOReview="ReadyForCEOReview",KnowledgeGap="KnowledgeGap",ResearchRequired="ResearchRequired"}
export enum BlogDraftPublicationMode{CEOApprovalRequired="CEOApprovalRequired",ConditionalAutonomy="ConditionalAutonomy",Autonomous="Autonomous",Disabled="Disabled"}
export enum BlogTrustCapability{BlogDraftCreation="BlogDraftCreation",BlogPublishing="BlogPublishing",LibraryWrite="LibraryWrite",PinterestPublishing="PinterestPublishing"}
export enum BlogValidationSeverity{Info="Info",Warning="Warning",RevisionRequired="RevisionRequired",Blocking="Blocking"}
export class BlogDraftParagraph{readonly knowledgeReferences;readonly sourceReferences;readonly bookLinkReferences;readonly internalLinkReferences;constructor(readonly id:string,readonly text:string,knowledgeReferences:readonly string[]=[],sourceReferences:readonly string[]=[],bookLinks:readonly string[]=[],internalLinks:readonly string[]=[]){requireText(id,"Paragraph identifier");requireText(text,"Paragraph text");this.knowledgeReferences=freeze(knowledgeReferences);this.sourceReferences=freeze(sourceReferences);this.bookLinkReferences=freeze(bookLinks);this.internalLinkReferences=freeze(internalLinks);Object.freeze(this);}}
export class BlogDraftHeading{constructor(readonly id:string,readonly planHeadingId:string,readonly text:string,readonly level:BlogHeadingLevel,readonly parentHeadingId?:string){requireText(id,"Draft heading identifier");requireText(planHeadingId,"Plan heading identifier");requireText(text,"Heading text");Object.freeze(this);}}
export class BlogDraftBookLink{constructor(readonly bookId:string,readonly editionId:string,readonly title:string,readonly url:string,readonly paragraphId:string,readonly role:"Related1"|"Related2"){Object.freeze(this);}}
export class BlogDraftInternalLink{constructor(readonly contentReference:string,readonly url:string,readonly paragraphId:string){Object.freeze(this);}}
export class BlogDraftCTA{constructor(readonly bookId:string,readonly editionId:string,readonly title:string,readonly url:string,readonly text:string){Object.freeze(this);}}
export class BlogDraftKnowledgeUsage{constructor(readonly reference:string,readonly paragraphIds:readonly string[]){this.paragraphIds=freeze(paragraphIds);Object.freeze(this);}}
export class BlogDraftSourceUsage{constructor(readonly reference:string,readonly paragraphIds:readonly string[]){this.paragraphIds=freeze(paragraphIds);Object.freeze(this);}}
export class BlogDraftContent{readonly headings;readonly paragraphs;readonly bookLinks;readonly internalLinks;constructor(readonly h1:string,headings:readonly BlogDraftHeading[],paragraphs:readonly BlogDraftParagraph[],bookLinks:readonly BlogDraftBookLink[]=[],internalLinks:readonly BlogDraftInternalLink[]=[],readonly cta?:BlogDraftCTA){this.headings=freeze(headings);this.paragraphs=freeze(paragraphs);this.bookLinks=freeze(bookLinks);this.internalLinks=freeze(internalLinks);Object.freeze(this);}}
export class BlogDraftValidationIssue{constructor(readonly code:string,readonly severity:BlogValidationSeverity,readonly message:string){Object.freeze(this);}}
export class BlogDraftValidationResult{readonly issues;constructor(issues:readonly BlogDraftValidationIssue[]){this.issues=freeze(issues);Object.freeze(this);}get passed(){return !this.issues.some(x=>x.severity===BlogValidationSeverity.Blocking||x.severity===BlogValidationSeverity.RevisionRequired);}}
export interface BlogDraftRequestProperties{id:BlogDraftId;version:BlogDraftVersion;businessPackageId:BusinessPackageId;planId:string;planVersion:number;recommendationId:string;recommendationVersion:number;canonicalQuestionReference:string;market:string;language:string;correlationIdentifier:string;requestingAuthority:string;requestedAt:Date;}
export class BlogDraftRequest{constructor(readonly properties:BlogDraftRequestProperties){for(const [v,n] of [[properties.planId,"Plan identifier"],[properties.recommendationId,"Recommendation reference"],[properties.canonicalQuestionReference,"Canonical Question reference"],[properties.market,"Market"],[properties.language,"Language"],[properties.correlationIdentifier,"Correlation identifier"],[properties.requestingAuthority,"Requesting authority"]] as const)requireText(v,n);if(!Number.isFinite(properties.requestedAt.getTime()))throw new BlogWriterException("Request timestamp is invalid","INVALID_REQUEST");Object.freeze(this);}}
export interface BlogWriterMaterial{content:BlogDraftContent;knowledgeGap?:"KnowledgeGap"|"ResearchRequired";nativeLanguageConfirmed:boolean;directAnswerParagraphId?:string;stylePolicyReference:string;searchDiscoverySatisfied:boolean;aiDiscoverySatisfied:boolean;unsupportedClaims?:readonly string[];}
export class BlogDraft{readonly knowledgeUsage;readonly sourceUsage;constructor(readonly id:BlogDraftId,readonly version:BlogDraftVersion,readonly businessPackageId:BusinessPackageId,readonly planId:string,readonly planVersion:number,readonly recommendationId:string,readonly recommendationVersion:number,readonly canonicalQuestionReference:string,readonly market:string,readonly language:string,readonly content:BlogDraftContent,knowledge:readonly BlogDraftKnowledgeUsage[],sources:readonly BlogDraftSourceUsage[],readonly stylePolicyReference:string,readonly state:BlogDraftState,readonly validation:BlogDraftValidationResult,readonly publicationMode:BlogDraftPublicationMode,readonly createdAt:Date){this.knowledgeUsage=freeze(knowledge);this.sourceUsage=freeze(sources);Object.freeze(this);}}
export class BlogWriterExecution{constructor(readonly correlationIdentifier:string,readonly plan:BlogContentCreationPlan,readonly draftId:BlogDraftId,readonly draftVersion:BlogDraftVersion,readonly startedAt:Date,readonly completedAt:Date,readonly outcome:BlogDraftState){Object.freeze(this);}}
export const BLOG_WRITER_EVENTS=Object.freeze(["BlogWriterRequested","BlogWriterStarted","BlogWriterKnowledgeGapDetected","BlogDraftCreated","BlogDraftValidationStarted","BlogDraftValidationFailed","BlogDraftRevisionRequired","BlogDraftReadyForCEOReview","BlogWriterCompleted","BlogWriterFailed"] as const);
