import {LibraryService} from "../../../library/LibraryService.ts";
import {LibraryLinkStatus} from "../../../library/LibraryDomain.ts";
import {CEORecommendationDecisionType} from "../../../recommendations/CEORecommendationReviewDomain.ts";
import {CEODecision,RecommendationStatus} from "../../../recommendations/RecommendationDomain.ts";
import {BlogRecommendationAction} from "../recommendations/BlogRecommendationEvaluationDomain.ts";
import {BlogAIDiscoveryRequirement,BlogBookLinkStatus,BlogBookPlacement,BlogBookPlacementPlan,BlogContentCreationPlan,BlogContentCreationPlanException,BlogContentCreationPlanRequest,BlogContentCreationPlanState,BlogHeadingEvidence,BlogHeadingLevel,BlogKnowledgeReadiness,BlogPinterestPromotionLineage,BlogPrimaryBookCTAPlan} from "./BlogContentCreationPlanDomain.ts";
import type {BlogContentCreationPlanInput} from "./BlogContentCreationPlanDomain.ts";
import {BlogContentCreationPlanRepository} from "./BlogContentCreationPlanRepository.ts";
export interface BlogContentPlanEventSink{emit(type:string,payload:Readonly<Record<string,unknown>>):void;}
export class BlogContentCreationPlanService{constructor(readonly repository:BlogContentCreationPlanRepository,readonly library:Pick<LibraryService,"resolveEdition">,readonly events?:BlogContentPlanEventSink,readonly clock=()=>new Date()){}
 create(request:BlogContentCreationPlanRequest,input:BlogContentCreationPlanInput){const p=request.properties,r=p.recommendation,a=p.ceoApproval;this.events?.emit("BlogContentPlanRequested",{planId:p.id.value,recommendationId:r.id.value,recommendationVersion:p.recommendationVersion});if(r.status!==RecommendationStatus.ApprovedByCEO||r.decision?.decision!==CEODecision.Approved)throw new BlogContentCreationPlanException("Recommendation must be explicitly CEO approved","APPROVAL_REQUIRED");if(r.id.value!==a.recommendationId||r.id.value!==p.ceoApproval.recommendationId||r.version!==p.recommendationVersion||a.recommendationVersion!==p.recommendationVersion||a.decisionType!==CEORecommendationDecisionType.Approve)throw new BlogContentCreationPlanException("CEO approval must bind to the exact Recommendation version","APPROVAL_VERSION_MISMATCH");if(r.businessPackageId.value!==p.businessPackageId.value||a.businessPackageId.value!==p.businessPackageId.value)throw new BlogContentCreationPlanException("Context crosses Business Package boundary","PACKAGE_MISMATCH");const newQuestion=p.action===BlogRecommendationAction.CreateNewArticle||p.action===BlogRecommendationAction.CreateRelatedArticle||p.action===BlogRecommendationAction.AnswerEmergingQuestion;const h1=newQuestion?p.canonicalQuestionText:p.existingApprovedH1??p.canonicalQuestionText;if(newQuestion&&h1!==p.canonicalQuestionText)throw new BlogContentCreationPlanException("Planned H1 must exactly equal Canonical Question text","H1_MISMATCH");if(newQuestion&&(!input.directAnswerObjective.required||!input.directAnswerObjective.answerClearlyAndEarly))throw new BlogContentCreationPlanException("Question-driven article requires an early direct-answer objective","DIRECT_ANSWER_REQUIRED");
 const placements:BlogBookPlacement[]=[];const selected=[input.primaryBookId,...(input.relatedBookIds??[]).slice(0,2)];for(const [index,book] of selected.entries()){if(!book)continue;const resolution=this.library.resolveEdition(p.businessPackageId,book,p.language),role=index===0?"Primary":index===1?"Related1":"Related2",reason=input.bookReasons?.[book.value];if(!reason)throw new BlogContentCreationPlanException("Book selection requires semantic evidence","MISSING_EVIDENCE");const edition=resolution.edition,valid=resolution.state==="Resolved"&&edition?.properties.links.status===LibraryLinkStatus.Verified;const status=valid?BlogBookLinkStatus.Resolved:resolution.state==="EditionUnavailable"?BlogBookLinkStatus.EditionUnavailable:BlogBookLinkStatus.BookRelevantButLinkUnavailable;placements.push(new BlogBookPlacement(role,book.value,edition?.id.value,edition?.properties.publishedTitle,valid?resolution.url:undefined,p.language,reason,role==="Primary"?undefined:input.bookSectionHeadingIds?.[book.value],role==="Primary"?"End-of-article deeper-understanding CTA":"Natural contextual reader connection",status));}
 const bookPlan=new BlogBookPlacementPlan(placements),primary=placements.find(x=>x.role==="Primary"),cta=primary?.linkStatus===BlogBookLinkStatus.Resolved?new BlogPrimaryBookCTAPlan("Planned",primary.bookId,primary.editionId,primary.verifiedDirectUrl):new BlogPrimaryBookCTAPlan("PrimaryBookUnavailable"),ready=input.knowledgeRequirement.readiness===BlogKnowledgeReadiness.Sufficient,state=ready?BlogContentCreationPlanState.Ready:BlogContentCreationPlanState.KnowledgeRequired;const headings=[{headingId:"h1",text:h1,level:BlogHeadingLevel.H1,evidence:BlogHeadingEvidence.PrimaryQuestionExplanation,evidenceReferences:[p.canonicalQuestionReference],defaultCandidate:newQuestion},...input.headingPlan.candidates.map(x=>({headingId:x.headingId,text:x.text,level:x.level,evidence:x.evidence,evidenceReferences:x.evidenceReferences,defaultCandidate:false}))];const plan=new BlogContentCreationPlan(p.id,p.version,p.businessPackageId,r.id.value,r.version,a.decisionId,p.blogOpportunityReference,p.canonicalQuestionReference,p.canonicalQuestionText,h1,p.market,p.language,p.intent,state,input.objective,input.directAnswerObjective,input.scope,input.relatedQuestions,input.headingPlan,input.knowledgeRequirement,input.sourceRequirements,bookPlan,cta,input.internalLinks??[],input.searchDiscovery,new BlogAIDiscoveryRequirement(input.aiDiscovery.requirements,input.aiDiscovery.humanFirst),p.stylePolicyReference,new BlogPinterestPromotionLineage(undefined,headings,p.minimumPinsConfigurationReference),input.warnings??[],this.clock(),p.version>1?p.version-1:undefined);this.repository.save(plan);this.events?.emit(ready?"BlogContentPlanReady":"BlogContentPlanKnowledgeRequired",{planId:p.id.value,version:p.version});return plan;}
}
