import {BusinessPackageId} from "../../../../intelligence/market/MarketIntelligenceDomain.ts";
import type {BusinessRecommendation} from "../../../recommendations/RecommendationDomain.ts";
import type {CEORecommendationDecisionRecord} from "../../../recommendations/CEORecommendationReviewDomain.ts";
import type {LibraryBookId} from "../../../library/LibraryDomain.ts";
import {BlogRecommendationAction} from "../recommendations/BlogRecommendationEvaluationDomain.ts";

export class BlogContentCreationPlanException extends Error{constructor(message:string,readonly code="BLOG_CONTENT_PLAN_FAILURE"){super(message);this.name="BlogContentCreationPlanException";}}
const required=(value:string,name:string)=>{if(typeof value!=="string"||!value.trim())throw new BlogContentCreationPlanException(`${name} is required`,"INVALID_REQUEST");return value;};
const frozen=<T>(values:readonly T[])=>Object.freeze([...values]);
export class BlogContentCreationPlanId{constructor(readonly value:string){required(value,"Plan identifier");Object.freeze(this);}}
export enum BlogContentCreationPlanState{Preparing="Preparing",KnowledgeRequired="KnowledgeRequired",Ready="Ready",Invalidated="Invalidated",Superseded="Superseded",Cancelled="Cancelled",Failed="Failed"}
export enum BlogKnowledgeReadiness{Sufficient="Sufficient",Partial="Partial",ResearchRequired="ResearchRequired",Unavailable="Unavailable",Unknown="Unknown"}
export enum BlogHeadingLevel{H1="H1",H2="H2",H3="H3"}
export enum BlogHeadingEvidence{ObservedRelatedQuestion="ObservedRelatedQuestion",QuestionPattern="QuestionPattern",KnowledgeRequirement="KnowledgeRequirement",ContentGap="ContentGap",ReaderComprehension="ReaderComprehension",CompetitiveGap="CompetitiveGap",PrimaryQuestionExplanation="PrimaryQuestionExplanation",OtherApprovedEvidence="OtherApprovedEvidence"}
export enum BlogBookLinkStatus{Resolved="Resolved",BookRelevantButLinkUnavailable="BookRelevantButLinkUnavailable",EditionUnavailable="EditionUnavailable"}
export class BlogArticleObjective{constructor(readonly description:string,readonly evidenceReferences:readonly string[],readonly humanFirst=true){required(description,"Article objective");this.evidenceReferences=frozen(evidenceReferences);Object.freeze(this);}}
export class BlogDirectAnswerObjective{constructor(readonly required:boolean,readonly answerClearlyAndEarly:boolean,readonly usefulOrientationBeforeAnswer:boolean,readonly prohibitGenericSEOIntroduction=true){Object.freeze(this);}}
export class BlogArticleScope{readonly requiredCoverage;readonly optionalCoverage;readonly excludedOrOutOfScopeCoverage;readonly evidenceReferences;constructor(requiredCoverage:readonly string[],optionalCoverage:readonly string[],excluded:readonly string[],evidence:readonly string[]){this.requiredCoverage=frozen(requiredCoverage);this.optionalCoverage=frozen(optionalCoverage);this.excludedOrOutOfScopeCoverage=frozen(excluded);this.evidenceReferences=frozen(evidence);Object.freeze(this);}}
export class BlogHeadingCandidate{readonly evidenceReferences;constructor(readonly headingId:string,readonly text:string,readonly level:BlogHeadingLevel,readonly evidence:BlogHeadingEvidence,evidenceReferences:readonly string[],readonly parentHeadingId?:string,readonly observedWording=false){required(headingId,"Heading identifier");required(text,"Heading text");if(level===BlogHeadingLevel.H1&&parentHeadingId||level===BlogHeadingLevel.H2&&parentHeadingId||level===BlogHeadingLevel.H3&&!parentHeadingId)throw new BlogContentCreationPlanException("Invalid heading hierarchy","INVALID_HEADING_HIERARCHY");this.evidenceReferences=frozen(evidenceReferences);if(!this.evidenceReferences.length)throw new BlogContentCreationPlanException("Heading evidence is required","MISSING_EVIDENCE");Object.freeze(this);}}
export class BlogHeadingPlan{readonly candidates;constructor(candidates:readonly BlogHeadingCandidate[]){const ids=new Set(candidates.map(x=>x.headingId));for(const h of candidates)if(h.level===BlogHeadingLevel.H3&&(!h.parentHeadingId||!ids.has(h.parentHeadingId)||candidates.find(x=>x.headingId===h.parentHeadingId)?.level!==BlogHeadingLevel.H2))throw new BlogContentCreationPlanException("H3 must have an H2 parent","INVALID_HEADING_HIERARCHY");this.candidates=frozen(candidates);Object.freeze(this);}}
export class BlogKnowledgeRequirement{readonly contextReferences;readonly missingEvidence;constructor(readonly readiness:BlogKnowledgeReadiness,contextReferences:readonly string[],readonly relevantContextOnly:boolean,readonly allowMasterLanguageContext:boolean,missingEvidence:readonly string[]=[]){this.contextReferences=frozen(contextReferences);this.missingEvidence=frozen(missingEvidence);Object.freeze(this);}}
export class BlogSourceRequirement{readonly approvedSourceReferences;constructor(readonly evidenceRequired:boolean,approvedSourceReferences:readonly string[],readonly freshnessRequirement?:string,readonly citationRequired=false,readonly factualReviewRequired=false,readonly sourceDiversityRequired=false){this.approvedSourceReferences=frozen(approvedSourceReferences);Object.freeze(this);}}
export class BlogBookPlacement{constructor(readonly role:"Primary"|"Related1"|"Related2",readonly bookId:string,readonly editionId:string|undefined,readonly publishedTitle:string|undefined,readonly verifiedDirectUrl:string|undefined,readonly targetLanguage:string,readonly semanticReason:string,readonly sectionHeadingId:string|undefined,readonly placementObjective:string,readonly linkStatus:BlogBookLinkStatus){required(bookId,"Book reference");required(semanticReason,"Book semantic reason");if(linkStatus===BlogBookLinkStatus.Resolved&&(!editionId||!publishedTitle||!verifiedDirectUrl))throw new BlogContentCreationPlanException("Resolved placement requires Library title and direct URL","INVALID_BOOK_LINK");Object.freeze(this);}}
export class BlogBookPlacementPlan{readonly placements;constructor(placements:readonly BlogBookPlacement[]){if(new Set(placements.map(x=>x.bookId)).size!==placements.length)throw new BlogContentCreationPlanException("Promotional Books must be distinct","DUPLICATE_BOOK");this.placements=frozen(placements);Object.freeze(this);}}
export class BlogPrimaryBookCTAPlan{constructor(readonly state:"Planned"|"PrimaryBookUnavailable",readonly bookId?:string,readonly editionId?:string,readonly verifiedDirectUrl?:string,readonly intent="Invite the reader to continue into a deeper treatment of the topic",readonly nearArticleEnd=true){if(state==="Planned"&&(!bookId||!editionId||!verifiedDirectUrl))throw new BlogContentCreationPlanException("Primary CTA requires a verified Library destination","INVALID_BOOK_LINK");Object.freeze(this);}}
export class BlogInternalLinkRequirement{constructor(readonly contentReference:string,readonly approvedUrl:string,readonly semanticReason:string){for(const [v,n] of [[contentReference,"Content reference"],[approvedUrl,"Approved internal URL"],[semanticReason,"Internal link reason"]] as const)required(v,n);Object.freeze(this);}}
export class BlogSearchDiscoveryRequirement{readonly requirements;constructor(requirements:readonly string[],readonly humanFirst=true){this.requirements=frozen(requirements);Object.freeze(this);}}
export class BlogAIDiscoveryRequirement{readonly requirements;constructor(requirements:readonly string[],readonly humanFirst=true){this.requirements=frozen(requirements);Object.freeze(this);}}
export interface BlogPinterestHeadingLineage{headingId:string;text:string;level:BlogHeadingLevel;evidence:BlogHeadingEvidence;evidenceReferences:readonly string[];defaultCandidate:boolean;}
export class BlogPinterestPromotionLineage{readonly headings;constructor(readonly futureArticleId:string|undefined,headings:readonly BlogPinterestHeadingLineage[],readonly minimumPinsConfigurationReference:string,readonly videoPinCompatible=true,readonly blogPublishedEventCompatible=true){this.headings=frozen(headings.map(x=>Object.freeze({...x,evidenceReferences:frozen(x.evidenceReferences)})));Object.freeze(this);}}
export interface BlogContentCreationPlanRequestProperties{id:BlogContentCreationPlanId;version:number;businessPackageId:BusinessPackageId;recommendation:BusinessRecommendation;recommendationVersion:number;ceoApproval:CEORecommendationDecisionRecord;blogOpportunityReference:string;canonicalQuestionReference:string;canonicalQuestionText:string;questionClusterReference:string;contentGapReference?:string;market:string;language:string;intent:readonly string[];action:BlogRecommendationAction;existingApprovedH1?:string;requestedAt:Date;correlationIdentifier:string;requestingAuthorityReference:string;stylePolicyReference:string;minimumPinsConfigurationReference:string;}
export class BlogContentCreationPlanRequest{readonly intent;readonly requestedAt:Date;constructor(readonly properties:BlogContentCreationPlanRequestProperties){if(!Number.isInteger(properties.version)||properties.version<1)throw new BlogContentCreationPlanException("Plan version is invalid","INVALID_VERSION");for(const [v,n] of [[properties.blogOpportunityReference,"Blog Opportunity reference"],[properties.canonicalQuestionReference,"Canonical Question reference"],[properties.canonicalQuestionText,"Canonical Question text"],[properties.questionClusterReference,"Question Cluster reference"],[properties.market,"Market"],[properties.language,"Language"],[properties.correlationIdentifier,"Correlation identifier"],[properties.requestingAuthorityReference,"Requesting authority"],[properties.stylePolicyReference,"Style policy reference"],[properties.minimumPinsConfigurationReference,"Minimum Pins configuration reference"]] as const)required(v,n);if(!Number.isFinite(properties.requestedAt.getTime()))throw new BlogContentCreationPlanException("Request timestamp is invalid","INVALID_REQUEST");this.intent=frozen(properties.intent);this.requestedAt=new Date(properties.requestedAt);Object.freeze(this);}}
export interface BlogContentCreationPlanInput{objective:BlogArticleObjective;scope:BlogArticleScope;directAnswerObjective:BlogDirectAnswerObjective;relatedQuestions:readonly string[];headingPlan:BlogHeadingPlan;knowledgeRequirement:BlogKnowledgeRequirement;sourceRequirements:readonly BlogSourceRequirement[];primaryBookId?:LibraryBookId;relatedBookIds?:readonly LibraryBookId[];bookReasons?:Readonly<Record<string,string>>;bookSectionHeadingIds?:Readonly<Record<string,string>>;internalLinks?:readonly BlogInternalLinkRequirement[];searchDiscovery:BlogSearchDiscoveryRequirement;aiDiscovery:BlogAIDiscoveryRequirement;warnings?:readonly string[];}
export class BlogContentCreationPlan{readonly relatedQuestions;readonly sourceRequirements;readonly internalLinks;readonly warnings;readonly #created:number;constructor(readonly id:BlogContentCreationPlanId,readonly version:number,readonly businessPackageId:BusinessPackageId,readonly recommendationId:string,readonly recommendationVersion:number,readonly ceoApprovalReference:string,readonly blogOpportunityReference:string,readonly canonicalQuestionId:string,readonly canonicalQuestionText:string,readonly plannedH1:string,readonly market:string,readonly language:string,readonly intent:readonly string[],readonly state:BlogContentCreationPlanState,readonly objective:BlogArticleObjective,readonly directAnswerObjective:BlogDirectAnswerObjective,readonly scope:BlogArticleScope,relatedQuestions:readonly string[],readonly headingPlan:BlogHeadingPlan,readonly knowledgeRequirement:BlogKnowledgeRequirement,sourceRequirements:readonly BlogSourceRequirement[],readonly bookPlacementPlan:BlogBookPlacementPlan,readonly primaryBookCTAPlan:BlogPrimaryBookCTAPlan,internalLinks:readonly BlogInternalLinkRequirement[],readonly searchDiscovery:BlogSearchDiscoveryRequirement,readonly aiDiscovery:BlogAIDiscoveryRequirement,readonly stylePolicyReference:string,readonly pinterestLineage:BlogPinterestPromotionLineage,warnings:readonly string[],createdAt:Date,readonly supersedesVersion?:number){if(!Number.isInteger(version)||version<1)throw new BlogContentCreationPlanException("Plan version is invalid","INVALID_VERSION");this.#created=createdAt.getTime();this.relatedQuestions=frozen(relatedQuestions);this.sourceRequirements=frozen(sourceRequirements);this.internalLinks=frozen(internalLinks);this.warnings=frozen(warnings);Object.freeze(this);}get createdAt(){return new Date(this.#created);}}
export const BLOG_CONTENT_PLAN_EVENTS=Object.freeze(["BlogContentPlanRequested","BlogContentPlanStarted","BlogContentPlanKnowledgeRequired","BlogContentPlanBookResolved","BlogContentPlanReady","BlogContentPlanInvalidated","BlogContentPlanSuperseded","BlogContentPlanCancelled","BlogContentPlanFailed"] as const);
