import { BusinessPackageId, Confidence, MarketObservation, MarketSource, Provenance } from "../MarketIntelligenceDomain.ts";
import { MarketNormalizationResult, RawMarketRecord } from "../integration/MarketSourceIntegrationDomain.ts";

export class MarketDataQualityException extends Error {
  constructor(message:string, readonly code="INVALID_MARKET_DATA_QUALITY") { super(message); this.name="MarketDataQualityException"; }
}
const required=(v:string,n:string)=>{if(typeof v!=="string"||!v.trim())throw new MarketDataQualityException(`${n} is required`);return v;};
const instant=(v:Date,n:string)=>{const t=v?.getTime();if(!Number.isFinite(t))throw new MarketDataQualityException(`${n} is invalid`);return t;};

export class MarketDataValidationId { readonly #value:string; constructor(value:string){this.#value=required(value,"Validation identifier");Object.freeze(this);} get value(){return this.#value;} }
/** Extensible dimension value with provider-independent baseline constants. */
export class MarketDataQualityDimension { static readonly Completeness=new this("Completeness");static readonly Validity=new this("Validity");static readonly ProvenanceIntegrity=new this("ProvenanceIntegrity");static readonly SourceTraceability=new this("SourceTraceability");static readonly Freshness=new this("Freshness");static readonly Consistency=new this("Consistency");static readonly Duplication=new this("Duplication");static readonly Contradiction=new this("Contradiction");static readonly SchemaCompatibility=new this("SchemaCompatibility");static readonly Other=new this("Other");constructor(readonly value:string){required(value,"Quality dimension");Object.freeze(this);} }
export enum MarketDataQualityStatus { Pass="Pass", Warning="Warning", Fail="Fail", Unknown="Unknown" }
export enum MarketDataQualityGrade { Unknown="Unknown", Low="Low", Moderate="Moderate", High="High", Verified="Verified" }
export enum MarketDataQualitySeverity { Info="Info", Warning="Warning", Error="Error", Critical="Critical" }
export enum MarketDataCompleteness { Complete="Complete", PartiallyComplete="PartiallyComplete", Incomplete="Incomplete", Unknown="Unknown" }
export enum MarketDataValidity { Valid="Valid", ValidWithWarnings="ValidWithWarnings", Invalid="Invalid", Unsupported="Unsupported", Unknown="Unknown" }
export enum MarketDataFreshnessState { Fresh="Fresh", Acceptable="Acceptable", Ageing="Ageing", Stale="Stale", Expired="Expired", Unknown="Unknown" }
export enum MarketDataProvenanceAssessment { Verified="Verified", Partial="Partial", Broken="Broken", Unavailable="Unavailable", Unknown="Unknown" }
export enum MarketSourceTraceability { FullyTraceable="FullyTraceable", PartiallyTraceable="PartiallyTraceable", Untraceable="Untraceable" }
export enum MarketDataConsistency { Consistent="Consistent", Warning="Warning", Inconsistent="Inconsistent", Unknown="Unknown" }
export enum MarketDuplicateAssessment { ExactDuplicate="ExactDuplicate", ProbableDuplicate="ProbableDuplicate", RelatedRecord="RelatedRecord", IndependentRecord="IndependentRecord", Unknown="Unknown" }
export enum MarketDataAcceptanceDecision { Accepted="Accepted", AcceptedWithWarnings="AcceptedWithWarnings", Quarantined="Quarantined", Rejected="Rejected", HistoricalOnly="HistoricalOnly" }
export enum MarketContradictionStatus { Detected="Detected", NeedsReview="NeedsReview", ResolvedExternally="ResolvedExternally", Superseded="Superseded", Archived="Archived" }
export enum DuplicateHandlingPolicy { QuarantineExact="QuarantineExact", AcceptWithMetadata="AcceptWithMetadata" }

export interface MarketDataQualityPolicyProperties { id:string; businessPackageId:BusinessPackageId; capabilityContext?:string; requiredFields:readonly string[]; requireFullProvenance:boolean; freshness:{freshMs:number;acceptableMs:number;ageingMs:number;staleMs:number}; duplicateHandling:DuplicateHandlingPolicy; rejectValidity:readonly MarketDataValidity[]; quarantineSeverities:readonly MarketDataQualitySeverity[]; }
export class MarketDataQualityPolicy { readonly requiredFields:readonly string[];readonly rejectValidity:readonly MarketDataValidity[];readonly quarantineSeverities:readonly MarketDataQualitySeverity[];constructor(readonly properties:MarketDataQualityPolicyProperties){required(properties.id,"Policy identifier");const f=properties.freshness;if([f.freshMs,f.acceptableMs,f.ageingMs,f.staleMs].some(x=>!Number.isFinite(x)||x<0)||!(f.freshMs<=f.acceptableMs&&f.acceptableMs<=f.ageingMs&&f.ageingMs<=f.staleMs))throw new MarketDataQualityException("Freshness thresholds must be ordered");this.requiredFields=Object.freeze([...properties.requiredFields]);this.rejectValidity=Object.freeze([...properties.rejectValidity]);this.quarantineSeverities=Object.freeze([...properties.quarantineSeverities]);Object.freeze(properties.freshness);Object.freeze(properties);Object.freeze(this);}get id(){return this.properties.id;}get businessPackageId(){return this.properties.businessPackageId;} }

export interface MarketDataValidationRequestProperties { id:MarketDataValidationId; normalization:MarketNormalizationResult; observation?:MarketObservation; rawRecord:RawMarketRecord; source:MarketSource; businessPackageId:BusinessPackageId; policy:MarketDataQualityPolicy; requestedAt:Date; correlationId:string; provenance:Provenance; adapterReference?:string; collectionRequestReference?:string; collectionResultReference?:string; }
export class MarketDataValidationRequest { readonly #at:number;constructor(readonly properties:MarketDataValidationRequestProperties){this.#at=instant(properties.requestedAt,"Request timestamp");required(properties.correlationId,"Correlation identifier");if(properties.normalization.rawRecord.id!==properties.rawRecord.id||properties.normalization.observation!==properties.observation)throw new MarketDataQualityException("Normalization references do not match request");if(properties.businessPackageId.value!==properties.policy.businessPackageId.value)throw new MarketDataQualityException("Policy crosses Business Package boundary");Object.freeze(properties);Object.freeze(this);}get id(){return this.properties.id;}get requestedAt(){return new Date(this.#at);} }

export class MarketDataQualityIssue { readonly #at:number;constructor(readonly id:string,readonly dimension:MarketDataQualityDimension,readonly code:string,readonly description:string,readonly severity:MarketDataQualitySeverity,readonly affectedReference:string,readonly provenance:Provenance,at:Date){required(id,"Issue identifier");required(code,"Issue code");required(description,"Issue description");this.#at=instant(at,"Issue timestamp");Object.freeze(this);}get timestamp(){return new Date(this.#at);} }
export class MarketDataFreshnessAssessment { readonly #age:number;constructor(readonly state:MarketDataFreshnessState,ageMs:number){if(!Number.isFinite(ageMs)||ageMs<0)throw new MarketDataQualityException("Freshness age is invalid");this.#age=ageMs;Object.freeze(this);}get ageMs(){return this.#age;} }
export interface SourceTraceabilityDetail { sourceKnown:boolean;adapterKnown:boolean;rawRecordKnown:boolean;collectionRequestKnown:boolean;collectionResultKnown:boolean; }
export class MarketDuplicateGroup { readonly memberReferences:readonly string[];readonly #at:number;constructor(readonly id:string,members:readonly string[],readonly canonicalReference:string,readonly classification:MarketDuplicateAssessment,readonly rationale:string,readonly confidence:Confidence,readonly provenance:Provenance,readonly businessPackageId:BusinessPackageId,at:Date){required(id,"Duplicate group identifier");if(members.length<2||!members.includes(canonicalReference))throw new MarketDataQualityException("Duplicate group requires members and canonical record");this.memberReferences=Object.freeze([...new Set(members)].sort());this.#at=instant(at,"Duplicate evaluation timestamp");Object.freeze(this);}get evaluatedAt(){return new Date(this.#at);}get independentObservationCount(){return 1;} }
export class MarketContradiction { readonly involvedReferences:readonly string[];readonly sourceReferences:readonly string[];readonly #at:number;constructor(readonly id:string,involved:readonly string[],readonly conflictingClaim:string,sources:readonly string[],readonly confidence:Confidence,readonly provenance:Provenance,readonly status:MarketContradictionStatus,readonly businessPackageId:BusinessPackageId,at:Date){required(id,"Contradiction identifier");if(involved.length<2)throw new MarketDataQualityException("Contradiction requires involved records");this.involvedReferences=Object.freeze([...involved]);this.sourceReferences=Object.freeze([...sources]);this.#at=instant(at,"Contradiction timestamp");Object.freeze(this);}get timestamp(){return new Date(this.#at);} }
export interface DimensionResult { dimension:MarketDataQualityDimension;status:MarketDataQualityStatus; }
export class MarketDataValidationResult { readonly dimensions:readonly DimensionResult[];readonly issues:readonly MarketDataQualityIssue[];readonly contradictionReferences:readonly string[];readonly #at:number;constructor(readonly id:MarketDataValidationId,readonly request:MarketDataValidationRequest,dimensions:readonly DimensionResult[],readonly completeness:MarketDataCompleteness,readonly validity:MarketDataValidity,readonly provenanceAssessment:MarketDataProvenanceAssessment,readonly sourceTraceability:MarketSourceTraceability,readonly freshness:MarketDataFreshnessAssessment,readonly duplicateAssessment:MarketDuplicateAssessment,readonly consistency:MarketDataConsistency,contradictions:readonly string[],issues:readonly MarketDataQualityIssue[],readonly grade:MarketDataQualityGrade,readonly acceptance:MarketDataAcceptanceDecision,at:Date,readonly provenance:Provenance){this.dimensions=Object.freeze(dimensions.map(x=>Object.freeze({...x})));this.issues=Object.freeze([...issues]);this.contradictionReferences=Object.freeze([...contradictions]);this.#at=instant(at,"Evaluation timestamp");Object.freeze(this);}get evaluatedAt(){return new Date(this.#at);} }
