export type SystemView="overview"|"agents"|"workflows"|"sources"|"integrations"|"trust"|"attention"|"audit";
export type SystemState="Operational"|"Working"|"AttentionRequired"|"Degraded"|"Paused"|"Offline";
export type AgentState="Working"|"Idle"|"Waiting"|"Blocked"|"AttentionRequired"|"Paused"|"Unavailable"|"Failed";
export type WorkflowState="Pending"|"Running"|"Waiting"|"WaitingForCEO"|"RetryPending"|"Paused"|"Completed"|"Failed"|"Cancelled"|"VerificationRequired"|"AuthenticationRequired";
export type TrustMode="Disabled"|"CEOOnly"|"CEOApprovalRequired"|"ConditionalAutonomy"|"Autonomous"|"ReadOnly";
export interface GovernedAction {readonly command:string;readonly allowed:boolean;readonly confirmationRequired:boolean;readonly reason?:string}
export interface AgentOperationsItem {readonly id:string;readonly role:string;readonly status:AgentState;readonly businessPackageId:string;readonly currentTask?:string;readonly lastAction?:string;readonly lastSuccessfulAction?:string;readonly health:string;readonly authoritySummary:string;readonly attention?:string;readonly workflowId?:string;readonly startedAt?:string;readonly dependencies:readonly string[];readonly recentActions:readonly string[];readonly correlationId?:string}
export interface WorkflowOperationsItem {readonly id:string;readonly name:string;readonly businessPackageId:string;readonly type:string;readonly status:WorkflowState;readonly currentStage:string;readonly startedAt:string;readonly updatedAt:string;readonly nextAction?:string;readonly attention?:string;readonly correlationId:string;readonly attempt:number;readonly actions:readonly GovernedAction[];readonly artifact?:{readonly type:"Question"|"Blog"|"Pin"|"Library"|"Performance";readonly id:string;readonly route:string}}
export interface SystemOperationsReadModel {readonly businessPackageId:string;readonly scope:"Global"|"BusinessPackage";readonly state:SystemState;readonly stale:boolean;readonly updatedAt:string;readonly summary:Readonly<Record<string,string|number>>;readonly agents:readonly AgentOperationsItem[];readonly workflows:readonly WorkflowOperationsItem[];readonly sources:readonly unknown[];readonly integrations:readonly unknown[];readonly trust:readonly unknown[];readonly attention:readonly unknown[];readonly audit:readonly unknown[];readonly nextCursor?:string}
export interface SystemOperationsGateway {read(query:{businessPackageId:string;view:SystemView;cursor?:string;pageSize:number}):Promise<SystemOperationsReadModel>;command(input:{command:string;businessPackageId:string;targetId:string;expectedVersion?:string;reason:string}):Promise<{accepted:boolean;auditId:string}>}
