import { AuditEvent } from "../../core/platform/AuditEvent.ts";
import { AuditEventType } from "../../core/platform/AuditEventType.ts";
import type { AuditRecorder } from "../../core/platform/AuditRecorder.ts";
import { AuthorizationDecisionValue } from "../../core/platform/AuthorizationDecision.ts";
import { AuthorizationRequest } from "../../core/platform/AuthorizationRequest.ts";
import type { AuthorizationService } from "../../core/platform/AuthorizationService.ts";
import { Event } from "../../core/platform/Event.ts";
import type { EventBus } from "../../core/platform/EventBus.ts";
import { EventContext } from "../../core/platform/EventContext.ts";
import { EventId } from "../../core/platform/EventId.ts";
import { EventType } from "../../core/platform/EventType.ts";
import { Permission } from "../../core/platform/Permission.ts";
import type { SystemIdentity } from "../../core/platform/SystemIdentity.ts";

const FORMAT = "ALIVO-CREDENTIAL-VAULT";
const VERSION = 1;
const ITERATIONS = 310_000;
const encoder = new TextEncoder();
const decoder = new TextDecoder(undefined, { fatal: true });

export enum AuthenticationType { UsernamePassword = "UsernamePassword", ApiKey = "ApiKey", AccessToken = "AccessToken", RefreshToken = "RefreshToken", OAuthCredentialReference = "OAuthCredentialReference", ClientCredential = "ClientCredential", SessionCredential = "SessionCredential", Other = "Other" }
export enum CredentialStatus { Active = "Active", Revoked = "Revoked", Expired = "Expired", Unavailable = "Unavailable" }
export enum CredentialAuthenticationFailure { InvalidUsername = "InvalidUsername", InvalidPassword = "InvalidPassword", ExpiredPassword = "ExpiredPassword", ExpiredCredential = "ExpiredCredential", ExpiredToken = "ExpiredToken", MFARequired = "MFARequired", AccountLocked = "AccountLocked", PermissionDenied = "PermissionDenied", ReauthorizationRequired = "ReauthorizationRequired", UnknownAuthenticationFailure = "UnknownAuthenticationFailure" }
export enum CredentialOperationalState { CredentialAvailable = "CredentialAvailable", CredentialUnavailable = "CredentialUnavailable", CredentialExpired = "CredentialExpired", CredentialCorrectionRequired = "CredentialCorrectionRequired", CredentialLocked = "CredentialLocked", AuthenticationFailure = "AuthenticationFailure" }
export enum VaultStatus { Uninitialized = "Uninitialized", Locked = "Locked", Unlocked = "Unlocked" }

export class CredentialId { readonly value: string; constructor(value: string) { required(value); this.value = value; Object.freeze(this); } equals(other: CredentialId): boolean { return other instanceof CredentialId && other.value === this.value; } toString(): string { return this.value; } }

export interface InterruptedOperationReference { readonly workflowRunReference?: string; readonly tcoTaskReference?: string; readonly sourceRequestReference?: string; readonly correlationIdentifier: string }
export interface CredentialFailureRecord { readonly credentialId: string; readonly failure: CredentialAuthenticationFailure; readonly recoverable: boolean; readonly correctionRequired: boolean; readonly interruptedOperation: InterruptedOperationReference; readonly recordedAt: string }
export interface CredentialMetadata { readonly credentialId: string; readonly displayName: string; readonly serviceReference: string; readonly accountReference: string; readonly username?: string; readonly authenticationType: AuthenticationType; readonly businessPackageScopes: readonly string[]; readonly sharedScopeApproved: boolean; readonly capabilityScopes: readonly string[]; readonly status: CredentialStatus; readonly createdAt: string; readonly updatedAt: string; readonly lastSuccessfulUse?: string; readonly expiresAt?: string; readonly notes?: string }
export interface AddCredentialInput extends Omit<CredentialMetadata, "createdAt" | "updatedAt" | "status" | "sharedScopeApproved"> { readonly secret: string; readonly status?: CredentialStatus; readonly sharedScopeApproved?: boolean }
export interface UpdateCredentialInput { readonly displayName?: string; readonly accountReference?: string; readonly username?: string; readonly secret?: string; readonly businessPackageScopes?: readonly string[]; readonly sharedScopeApproved?: boolean; readonly capabilityScopes?: readonly string[]; readonly status?: CredentialStatus; readonly expiresAt?: string; readonly notes?: string }

interface StoredCredential extends CredentialMetadata { secret: string }
interface VaultPayload { credentials: StoredCredential[]; failures: CredentialFailureRecord[]; automaticLockMinutes?: number }
export interface EncryptedVaultDocument { readonly format: typeof FORMAT; readonly version: typeof VERSION; readonly kdf: { readonly name: "PBKDF2"; readonly hash: "SHA-256"; readonly iterations: number; readonly salt: string }; readonly cipher: { readonly name: "AES-GCM"; readonly nonce: string; readonly ciphertext: string } }

/** Dedicated persistence boundary: implementations store only an encrypted vault document. */
export interface CredentialVaultStorage { load(): Promise<string | undefined>; save(encryptedDocument: string): Promise<void> }
export class InMemoryCredentialVaultStorage implements CredentialVaultStorage {
  #document?: string;
  async load(): Promise<string | undefined> { return this.#document; }
  async save(encryptedDocument: string): Promise<void> { this.#document = encryptedDocument; }
}

export class CredentialVaultError extends Error { constructor(readonly category: "InvalidInput" | "AuthenticationFailure" | "Locked" | "Unauthorized" | "NotFound" | "IntegrityFailure" | "AlreadyInitialized") { super(`Credential vault operation failed: ${category}`); this.name = "CredentialVaultError"; } }

export const CredentialVaultPermissions = Object.freeze({
  manage: new Permission({ identifier: "credentials.manage", resourceCategory: "credential-vault", action: "manage" }),
  reveal: new Permission({ identifier: "credentials.reveal", resourceCategory: "credential-vault", action: "reveal" }),
  list: new Permission({ identifier: "credentials.list", resourceCategory: "credential-vault", action: "list" }),
});

function encode(bytes: Uint8Array): string { return Array.from(bytes, (byte) => byte.toString(16).padStart(2, "0")).join(""); }
function decode(value: string): Uint8Array<ArrayBuffer> { if (!/^(?:[0-9a-f]{2})+$/i.test(value)) throw new CredentialVaultError("IntegrityFailure"); const pairs = value.match(/../g) ?? []; const bytes = new Uint8Array(pairs.length); pairs.forEach((pair, index) => { bytes[index] = Number.parseInt(pair, 16); }); return bytes; }
function required(value: string): void { if (typeof value !== "string" || value.trim().length === 0) throw new CredentialVaultError("InvalidInput"); }
function validateScopes(scopes: readonly string[], shared: boolean): void { if (!Array.isArray(scopes) || scopes.length === 0 || scopes.some((scope) => typeof scope !== "string" || scope.trim().length === 0)) throw new CredentialVaultError("InvalidInput"); if (new Set(scopes).size !== scopes.length) throw new CredentialVaultError("InvalidInput"); if (scopes.length > 1 && !shared) throw new CredentialVaultError("Unauthorized"); }
async function key(password: string, salt: Uint8Array<ArrayBuffer>, iterations: number): Promise<CryptoKey> { const material = await crypto.subtle.importKey("raw", encoder.encode(password), "PBKDF2", false, ["deriveKey"]); return crypto.subtle.deriveKey({ name: "PBKDF2", salt, iterations, hash: "SHA-256" }, material, { name: "AES-GCM", length: 256 }, false, ["encrypt", "decrypt"]); }
async function seal(payload: VaultPayload, password: string): Promise<EncryptedVaultDocument> { const salt = crypto.getRandomValues(new Uint8Array(16)); const nonce = crypto.getRandomValues(new Uint8Array(12)); const ciphertext = await crypto.subtle.encrypt({ name: "AES-GCM", iv: nonce }, await key(password, salt, ITERATIONS), encoder.encode(JSON.stringify(payload))); return { format: FORMAT, version: VERSION, kdf: { name: "PBKDF2", hash: "SHA-256", iterations: ITERATIONS, salt: encode(salt) }, cipher: { name: "AES-GCM", nonce: encode(nonce), ciphertext: encode(new Uint8Array(ciphertext)) } }; }
function parse(document: string): EncryptedVaultDocument { try { const value = JSON.parse(document) as EncryptedVaultDocument; if (value.format !== FORMAT || value.version !== VERSION || value.kdf?.name !== "PBKDF2" || value.kdf.hash !== "SHA-256" || value.kdf.iterations !== ITERATIONS || value.cipher?.name !== "AES-GCM" || decode(value.kdf.salt).length !== 16 || decode(value.cipher.nonce).length !== 12 || decode(value.cipher.ciphertext).length < 16) throw new Error(); return value; } catch { throw new CredentialVaultError("IntegrityFailure"); } }
async function open(document: string, password: string): Promise<VaultPayload> { const envelope = parse(document); try { const plaintext = await crypto.subtle.decrypt({ name: "AES-GCM", iv: decode(envelope.cipher.nonce) }, await key(password, decode(envelope.kdf.salt), envelope.kdf.iterations), decode(envelope.cipher.ciphertext)); const payload = JSON.parse(decoder.decode(plaintext)) as VaultPayload; if (!Array.isArray(payload.credentials) || !Array.isArray(payload.failures)) throw new Error(); return payload; } catch { throw new CredentialVaultError("AuthenticationFailure"); } }

/** Encrypted, provider-independent credential boundary. Plaintext is held only while unlocked. */
export class CredentialVault {
  #payload?: VaultPayload;
  #password?: string;
  constructor(private readonly storage: CredentialVaultStorage, private readonly authorization: AuthorizationService, private readonly audit: AuditRecorder, private readonly events?: EventBus, private readonly now: () => Date = () => new Date()) {}
  async status(): Promise<VaultStatus> { return this.#payload ? VaultStatus.Unlocked : await this.storage.load() === undefined ? VaultStatus.Uninitialized : VaultStatus.Locked; }
  async initialize(password: string, confirmation: string, actor: SystemIdentity): Promise<void> { this.authorize(actor, CredentialVaultPermissions.manage, "vault"); if (await this.storage.load() !== undefined) throw new CredentialVaultError("AlreadyInitialized"); required(password); if (password !== confirmation) throw new CredentialVaultError("AuthenticationFailure"); const payload: VaultPayload = { credentials: [], failures: [] }; await this.storage.save(JSON.stringify(await seal(payload, password))); this.#payload = payload; this.#password = password; this.record(actor, "VaultInitialized", "success"); }
  async unlock(password: string, actor: SystemIdentity): Promise<void> { this.authorize(actor, CredentialVaultPermissions.manage, "vault"); required(password); const document = await this.storage.load(); if (!document) throw new CredentialVaultError("IntegrityFailure"); try { this.#payload = await open(document, password); this.#password = password; this.record(actor, "VaultUnlocked", "success"); } catch { this.record(actor, "VaultUnlockFailed", "failure"); throw new CredentialVaultError("AuthenticationFailure"); } }
  lock(actor: SystemIdentity): void { this.authorize(actor, CredentialVaultPermissions.manage, "vault"); this.#payload = undefined; this.#password = undefined; this.record(actor, "VaultLocked", "success"); }
  async addCredential(input: AddCredentialInput, actor: SystemIdentity): Promise<CredentialMetadata> { this.authorize(actor, CredentialVaultPermissions.manage, "vault"); const payload = this.unlocked(); required(input.credentialId); required(input.secret); required(input.displayName); required(input.serviceReference); required(input.accountReference); validateScopes(input.businessPackageScopes, input.sharedScopeApproved ?? false); if (payload.credentials.some((item) => item.credentialId === input.credentialId)) throw new CredentialVaultError("InvalidInput"); const timestamp = this.now().toISOString(); const stored: StoredCredential = { ...input, businessPackageScopes: [...input.businessPackageScopes], capabilityScopes: [...input.capabilityScopes], status: input.status ?? CredentialStatus.Active, sharedScopeApproved: input.sharedScopeApproved ?? false, createdAt: timestamp, updatedAt: timestamp }; payload.credentials.push(stored); await this.persist(); this.record(actor, "CredentialCreated", "success", stored.credentialId); return this.metadata(stored); }
  listMetadata(actor: SystemIdentity, businessPackageScope?: string): readonly CredentialMetadata[] { this.authorize(actor, CredentialVaultPermissions.list, "vault"); return Object.freeze(this.unlocked().credentials.filter((item) => businessPackageScope === undefined || item.businessPackageScopes.includes(businessPackageScope)).sort((a, b) => a.serviceReference.localeCompare(b.serviceReference) || a.accountReference.localeCompare(b.accountReference) || a.credentialId.localeCompare(b.credentialId)).map((item) => this.metadata(item))); }
  searchMetadata(query: string, actor: SystemIdentity, businessPackageScope?: string): readonly CredentialMetadata[] { required(query); const normalized = query.toLocaleLowerCase(); return this.listMetadata(actor, businessPackageScope).filter((item) => [item.displayName, item.serviceReference, item.accountReference, item.username ?? ""].some((value) => value.toLocaleLowerCase().includes(normalized))); }
  getMetadata(credentialId: string, actor: SystemIdentity, businessPackageScope: string): CredentialMetadata { this.authorize(actor, CredentialVaultPermissions.list, credentialId); return this.metadata(this.scoped(credentialId, businessPackageScope)); }
  revealSecret(credentialId: string, actor: SystemIdentity, businessPackageScope: string): string { this.authorize(actor, CredentialVaultPermissions.reveal, credentialId); const secret = this.scoped(credentialId, businessPackageScope).secret; this.record(actor, "CredentialSecretRevealed", "success", credentialId); return secret; }
  async updateCredential(credentialId: string, update: UpdateCredentialInput, actor: SystemIdentity): Promise<CredentialMetadata> { this.authorize(actor, CredentialVaultPermissions.manage, credentialId); const stored = this.requiredCredential(credentialId); const scopes = update.businessPackageScopes ?? stored.businessPackageScopes; const shared = update.sharedScopeApproved ?? stored.sharedScopeApproved; validateScopes(scopes, shared); if (update.secret !== undefined) required(update.secret); Object.assign(stored, update, { businessPackageScopes: [...scopes], capabilityScopes: [...(update.capabilityScopes ?? stored.capabilityScopes)], sharedScopeApproved: shared, updatedAt: this.now().toISOString() }); await this.persist(); this.record(actor, "CredentialUpdated", "success", credentialId); return this.metadata(stored); }
  async revokeCredential(credentialId: string, actor: SystemIdentity): Promise<void> { await this.updateCredential(credentialId, { status: CredentialStatus.Revoked }, actor); this.record(actor, "CredentialRevoked", "success", credentialId); }
  async deleteCredential(credentialId: string, actor: SystemIdentity): Promise<void> { this.authorize(actor, CredentialVaultPermissions.manage, credentialId); const payload = this.unlocked(); const index = payload.credentials.findIndex((item) => item.credentialId === credentialId); if (index < 0) throw new CredentialVaultError("NotFound"); payload.credentials.splice(index, 1); await this.persist(); this.record(actor, "CredentialDeleted", "success", credentialId); }
  async changeMasterPassword(current: string, replacement: string, confirmation: string, actor: SystemIdentity): Promise<void> { this.authorize(actor, CredentialVaultPermissions.manage, "vault"); required(current); required(replacement); if (replacement !== confirmation) throw new CredentialVaultError("AuthenticationFailure"); const original = await this.storage.load(); if (!original) throw new CredentialVaultError("IntegrityFailure"); await open(original, current); const candidate = JSON.stringify(await seal(this.unlocked(), replacement)); await open(candidate, replacement); await this.storage.save(candidate); this.#password = replacement; this.record(actor, "MasterPasswordChanged", "success"); }
  async exportEncryptedBackup(actor: SystemIdentity): Promise<string> { this.authorize(actor, CredentialVaultPermissions.manage, "vault"); const document = await this.storage.load(); if (!document) throw new CredentialVaultError("IntegrityFailure"); parse(document); this.record(actor, "EncryptedBackupCreated", "success"); return document; }
  validateEncryptedBackup(backup: string): boolean { parse(backup); return true; }
  async restoreEncryptedBackup(backup: string, password: string, actor: SystemIdentity): Promise<void> { this.authorize(actor, CredentialVaultPermissions.manage, "vault"); required(password); const candidate = await open(backup, password); await this.storage.save(backup); this.#payload = candidate; this.#password = password; this.record(actor, "CredentialRestoreCompleted", "success"); }
  async recordAuthenticationFailure(credentialId: string, failure: CredentialAuthenticationFailure, interruptedOperation: InterruptedOperationReference, actor: SystemIdentity): Promise<CredentialFailureRecord> { this.authorize(actor, CredentialVaultPermissions.manage, credentialId); required(interruptedOperation.correlationIdentifier); const recoverable = failure !== CredentialAuthenticationFailure.UnknownAuthenticationFailure; const record: CredentialFailureRecord = Object.freeze({ credentialId, failure, recoverable, correctionRequired: recoverable, interruptedOperation: Object.freeze({ ...interruptedOperation }), recordedAt: this.now().toISOString() }); this.requiredCredential(credentialId); this.unlocked().failures.push(record); await this.persist(); this.record(actor, recoverable ? "CredentialCorrectionRequired" : "CredentialAuthenticationFailed", "recorded", credentialId); return record; }
  async setAutomaticLockPolicy(minutes: number | undefined, actor: SystemIdentity): Promise<void> { this.authorize(actor, CredentialVaultPermissions.manage, "vault"); if (minutes !== undefined && (!Number.isInteger(minutes) || minutes <= 0)) throw new CredentialVaultError("InvalidInput"); this.unlocked().automaticLockMinutes = minutes; await this.persist(); }
  private authorize(actor: SystemIdentity, permission: Permission, resource: string): void { try { const decision = this.authorization.evaluate(new AuthorizationRequest({ identity: actor, permission, protectedResourceId: resource })); if (decision.decision !== AuthorizationDecisionValue.Allowed) throw new Error(); } catch { throw new CredentialVaultError("Unauthorized"); } }
  private unlocked(): VaultPayload { if (!this.#payload || !this.#password) throw new CredentialVaultError("Locked"); return this.#payload; }
  private requiredCredential(id: string): StoredCredential { const item = this.unlocked().credentials.find((candidate) => candidate.credentialId === id); if (!item) throw new CredentialVaultError("NotFound"); return item; }
  private scoped(id: string, scope: string): StoredCredential { required(scope); const item = this.requiredCredential(id); if (!item.businessPackageScopes.includes(scope)) throw new CredentialVaultError("Unauthorized"); return item; }
  private metadata({ secret: _secret, ...metadata }: StoredCredential): CredentialMetadata { return Object.freeze({ ...metadata, businessPackageScopes: Object.freeze([...metadata.businessPackageScopes]), capabilityScopes: Object.freeze([...metadata.capabilityScopes]) }); }
  private async persist(): Promise<void> { await this.storage.save(JSON.stringify(await seal(this.unlocked(), this.#password!))); }
  private record(actor: SystemIdentity, action: string, result: string, credentialId?: string): void { const timestamp = this.now(); const context: Record<string, string> = { action }; if (credentialId !== undefined) context.resourceId = credentialId; this.audit.append(new AuditEvent({ timestamp, type: AuditEventType.SecurityEvent, source: "CredentialVault", action, result, responsibleIdentity: actor.id.value, context })); this.events?.publish(new Event({ id: new EventId(crypto.randomUUID()), type: new EventType(action), timestamp, source: "CredentialVault", correlationId: crypto.randomUUID(), context: new EventContext(context) })); }
}
