import { AuditEvent } from "../../../core/platform/AuditEvent.ts";
import { AuditEventType } from "../../../core/platform/AuditEventType.ts";
import type { AuditRecorder } from "../../../core/platform/AuditRecorder.ts";
import { Event } from "../../../core/platform/Event.ts";
import type { EventBus } from "../../../core/platform/EventBus.ts";
import { EventId } from "../../../core/platform/EventId.ts";
import { EventType } from "../../../core/platform/EventType.ts";
import { AcquisitionCapability, ObservationOrigin, ObservedQuestion, ObservedQuestionId, QuestionDetection, QuestionSourceCategory } from "../../../business/market/questions/QuestionIntelligenceDomain.ts";
import { QuestionIntelligenceService } from "../../../business/market/questions/QuestionIntelligenceService.ts";
import { Confidence, Evidence, EvidenceId, EvidenceStatus, Freshness, FreshnessStatus, MarketObservation, MarketSourceId, ObservationId } from "../MarketIntelligenceDomain.ts";
import { MarketSourceAdapterId, MarketSourceAvailability, MarketSourceHealthState, MarketSourceState } from "../integration/MarketSourceIntegrationDomain.ts";
import type { MarketSourceIntegrationService } from "../integration/MarketSourceIntegrationService.ts";
import { DiscoveryRawObservation, QuestionDiscoveryProfile, QuestionDiscoveryRequest, QuestionDiscoveryRun, QuestionDiscoveryRunId, QuestionDiscoveryRunState, QuestionDiscoverySourceCategory, QuestionDiscoverySourceResult, QuestionDiscoverySourceState } from "./QuestionDiscoveryDomain.ts";
import type { QuestionDiscoveryAdapter, QuestionDiscoverySourceRequest, QuestionDiscoverySummary, QuestionSourceHealthReadModel, QuestionSourceManagementReadModel } from "./QuestionDiscoveryDomain.ts";

const questionCategory=(category:QuestionDiscoverySourceCategory):QuestionSourceCategory=>({
 [QuestionDiscoverySourceCategory.SearchEngine]:QuestionSourceCategory.SearchEngine,[QuestionDiscoverySourceCategory.SearchSuggestion]:QuestionSourceCategory.QuerySuggestion,[QuestionDiscoverySourceCategory.RelatedQuestion]:QuestionSourceCategory.SearchEngine,[QuestionDiscoverySourceCategory.RelatedSearch]:QuestionSourceCategory.RelatedSearch,[QuestionDiscoverySourceCategory.QuestionAnswerPlatform]:QuestionSourceCategory.QuestionAnswer,[QuestionDiscoverySourceCategory.Forum]:QuestionSourceCategory.Forum,[QuestionDiscoverySourceCategory.Community]:QuestionSourceCategory.Community,[QuestionDiscoverySourceCategory.DiscussionPlatform]:QuestionSourceCategory.Discussion,[QuestionDiscoverySourceCategory.VideoDiscovery]:QuestionSourceCategory.VideoDiscovery,[QuestionDiscoverySourceCategory.TopicPortal]:QuestionSourceCategory.PublicPortal,[QuestionDiscoverySourceCategory.AuthorizedAnalytics]:QuestionSourceCategory.Other,[QuestionDiscoverySourceCategory.ManualImport]:QuestionSourceCategory.Other,[QuestionDiscoverySourceCategory.OtherApprovedPublicSource]:QuestionSourceCategory.Other,
}[category]);
const attention=new Set([QuestionDiscoverySourceState.AuthenticationRequired,QuestionDiscoverySourceState.InvalidCredential,QuestionDiscoverySourceState.ReauthorizationRequired,QuestionDiscoverySourceState.PermissionDenied,QuestionDiscoverySourceState.RateLimited,QuestionDiscoverySourceState.Failed]);
const failures=new Set([QuestionDiscoverySourceState.Failed,QuestionDiscoverySourceState.AuthenticationRequired,QuestionDiscoverySourceState.InvalidCredential,QuestionDiscoverySourceState.ReauthorizationRequired,QuestionDiscoverySourceState.PermissionDenied,QuestionDiscoverySourceState.RateLimited]);

/** TCO-facing coordinator. It selects registered adapters by capability and never names a provider. */
export class QuestionDiscoveryService {
 #sequence=0; readonly #lastResults=new Map<string,QuestionDiscoverySourceResult>();
 constructor(private readonly sources:MarketSourceIntegrationService,private readonly intelligence=new QuestionIntelligenceService(),private readonly audit?:AuditRecorder,private readonly clock=()=>new Date(),private readonly events?:EventBus){}

 async discover(request:QuestionDiscoveryRequest,profile:QuestionDiscoveryProfile,signal?:AbortSignal):Promise<QuestionDiscoveryRun>{
  this.ensureScope(request,profile);this.record("QuestionDiscoveryRequested",request,"Requested");this.record("QuestionDiscoveryStarted",request,QuestionDiscoveryRunState.Running);const results:QuestionDiscoverySourceResult[]=[];
  for(const sourceRequest of request.sourceRequests){
   if(signal?.aborted)break;
   const descriptors=this.sources.registry.all().filter(d=>d.supports(sourceRequest.capability)&&d.authorized(request.scope.businessPackageId,sourceRequest.capability)&&d.state===MarketSourceState.Available&&d.availability===MarketSourceAvailability.Available&&d.health.state!==MarketSourceHealthState.Unhealthy&&!profile.disabledProviders.includes(d.adapterId.value)&&(profile.enabledProviders.length===0||profile.enabledProviders.includes(d.adapterId.value))&&d.supportedMarkets.some(x=>x===request.scope.market||x==="*")&&d.supportedLanguages.some(x=>x===request.scope.language||x==="*"));
   if(descriptors.length===0){results.push(new QuestionDiscoverySourceResult(new MarketSourceAdapterId("unresolved"),new MarketSourceId("unresolved"),sourceRequest.categories[0],sourceRequest.capability,QuestionDiscoverySourceState.Unsupported,[],this.clock(),"No approved adapter supports this scope"));continue;}
   for(const descriptor of descriptors){if(results.reduce((n,x)=>n+x.observations.length,0)>=request.maximumObservations)break;const adapter=this.sources.registry.adapter(descriptor.adapterId) as QuestionDiscoveryAdapter;if(typeof adapter?.discover!=="function")continue;results.push(await this.collect(adapter,request,sourceRequest,signal));}
  }
  const cancelled=signal?.aborted===true,raw=results.flatMap(x=>x.observations).slice(0,request.maximumObservations),handoff=this.handoff(raw,request),summary=this.summarize(request,results,raw),hasAttention=results.some(x=>attention.has(x.state)),hasSuccess=results.some(x=>[QuestionDiscoverySourceState.Succeeded,QuestionDiscoverySourceState.Partial,QuestionDiscoverySourceState.NoData].includes(x.state));
  const state=cancelled?QuestionDiscoveryRunState.Cancelled:hasAttention&&hasSuccess?QuestionDiscoveryRunState.Partial:hasAttention?QuestionDiscoveryRunState.AttentionRequired:QuestionDiscoveryRunState.Completed;
  this.record(cancelled?"QuestionDiscoveryCancelled":"QuestionDiscoveryCompleted",request,state);return new QuestionDiscoveryRun(new QuestionDiscoveryRunId(`run-${request.id.value}`),request,state,results,raw,handoff,summary,this.clock());
 }

 async retry(run:QuestionDiscoveryRun,adapterId:string,profile:QuestionDiscoveryProfile,signal?:AbortSignal){const prior=run.sourceResults.find(x=>x.adapterId.value===adapterId);if(!prior||[QuestionDiscoverySourceState.Succeeded,QuestionDiscoverySourceState.NoData].includes(prior.state))return run;const sourceRequest=run.request.sourceRequests.find(x=>x.capability.equals(prior.capability));const adapter=this.sources.registry.adapter(prior.adapterId) as QuestionDiscoveryAdapter;if(!sourceRequest||typeof adapter?.discover!=="function")return run;const replacement=await this.collect(adapter,run.request,sourceRequest,signal),results=run.sourceResults.map(x=>x===prior?replacement:x),raw=results.flatMap(x=>x.observations).slice(0,run.request.maximumObservations),handoff=this.handoff(raw,run.request),summary=this.summarize(run.request,results,raw),state=results.some(x=>failures.has(x.state))?QuestionDiscoveryRunState.Partial:QuestionDiscoveryRunState.Completed;return new QuestionDiscoveryRun(run.id,run.request,state,results,raw,handoff,summary,this.clock());}

 sourceHealth():readonly QuestionSourceHealthReadModel[]{return Object.freeze(this.sources.registry.all().map(d=>{const last=this.#lastResults.get(d.adapterId.value);return Object.freeze({provider:d.adapterId.value,capability:d.capabilities.map(x=>x.value).join(","),status:last?.state??QuestionDiscoverySourceState.Pending,lastChecked:last?.attemptedAt??d.health.evaluatedAt,lastSuccess:last&&[QuestionDiscoverySourceState.Succeeded,QuestionDiscoverySourceState.NoData].includes(last.state)?last.attemptedAt:d.health.lastSuccessfulInteraction,lastError:last&&!([QuestionDiscoverySourceState.Succeeded,QuestionDiscoverySourceState.NoData].includes(last.state))?last.safeMessage:undefined,authentication:d.properties.credentialId?"Configured":"NotRequired",rateLimitRetryAt:last?.retryAfter,markets:d.supportedMarkets,languages:d.supportedLanguages});}));}
 sourceManagement():readonly QuestionSourceManagementReadModel[]{const health=this.sourceHealth();return Object.freeze(this.sources.registry.all().map((d,i)=>Object.freeze({...health[i],source:d.source.name,type:d.source.kind,enabled:d.state===MarketSourceState.Available})));}

 private async collect(adapter:QuestionDiscoveryAdapter,request:QuestionDiscoveryRequest,sourceRequest:QuestionDiscoverySourceRequest,signal?:AbortSignal){const at=this.clock();this.record("QuestionSourceCollectionStarted",request,QuestionDiscoverySourceState.Running,adapter.id.value);let output;try{output=await adapter.discover(request,sourceRequest,signal);}catch(error){output={state:QuestionDiscoverySourceState.Failed,observations:[],safeMessage:error instanceof Error?error.message:"Source collection failed"};}const category=output.observations[0]?.properties.sourceCategory??sourceRequest.categories[0],result=new QuestionDiscoverySourceResult(adapter.id,adapter.descriptor().source.id,category,sourceRequest.capability,signal?.aborted?QuestionDiscoverySourceState.Cancelled:output.state,output.observations,at,output.safeMessage,output.retryAfter),eventName=({[QuestionDiscoverySourceState.Succeeded]:"QuestionSourceCollectionSucceeded",[QuestionDiscoverySourceState.Partial]:"QuestionSourceCollectionPartial",[QuestionDiscoverySourceState.AuthenticationRequired]:"QuestionSourceAuthenticationRequired",[QuestionDiscoverySourceState.InvalidCredential]:"QuestionSourceAuthenticationRequired",[QuestionDiscoverySourceState.ReauthorizationRequired]:"QuestionSourceAuthenticationRequired",[QuestionDiscoverySourceState.PermissionDenied]:"QuestionSourceAuthenticationRequired",[QuestionDiscoverySourceState.RateLimited]:"QuestionSourceRateLimited",[QuestionDiscoverySourceState.Unavailable]:"QuestionSourceUnavailable",[QuestionDiscoverySourceState.Failed]:"QuestionSourceCollectionFailed"} as Partial<Record<QuestionDiscoverySourceState,string>>)[result.state]??"QuestionSourceCollectionPartial";this.#lastResults.set(adapter.id.value,result);this.record(eventName,request,result.state,adapter.id.value);return result;}
 private handoff(raw:readonly DiscoveryRawObservation[],request:QuestionDiscoveryRequest){const seen=new Set<string>();return Object.freeze(raw.map((item,index)=>{const p=item.properties,observedAt=item.observedAt??item.collectedAt,oid=new ObservationId(`${request.id.value}-${index}`),freshness=new Freshness(FreshnessStatus.Current,item.collectedAt),observation=new MarketObservation(oid,p.rawRecord.properties.sourceId,observedAt,p.market,request.scope.businessPackageId,p.observedText,"QuestionDiscoveryObservation",p.rawRecord.properties.payloadReference,p.rawRecord.provenance,freshness,new Confidence(.5)),evidence=new Evidence(new EvidenceId(`evidence-${request.id.value}-${index}`),[oid],p.rawRecord.provenance,item.collectedAt,new Confidence(.5),freshness,EvidenceStatus.Active),normalized=this.intelligence.normalize(p.observedText),independence=p.independenceReference??`${p.provider}:${p.rawRecord.properties.providerRecordReference??p.rawRecord.id}`,key=`${normalized}|${independence}`;const origin=seen.has(key)?ObservationOrigin.Synthetic:ObservationOrigin.Human;seen.add(key);return new ObservedQuestion({id:new ObservedQuestionId(`question-${request.id.value}-${index}`),version:1,observation,evidence,originalText:p.observedText,normalizedText:normalized,semanticKey:normalized,detection:this.intelligence.detect(p.observedText),sourceCategory:questionCategory(p.sourceCategory),acquisitionCapability:AcquisitionCapability.AuthorizedResource,sourceReference:p.sourceReference,independenceKey:independence,language:p.language,market:p.market,freshness,sourceQuality:new Confidence(.5),origin,context:p.context??p.featureType});}));}
 private summarize(request:QuestionDiscoveryRequest,results:readonly QuestionDiscoverySourceResult[],raw:readonly DiscoveryRawObservation[]):QuestionDiscoverySummary {return Object.freeze({sourcesRequested:request.sourceRequests.length,sourcesAttempted:results.filter(x=>x.adapterId.value!=="unresolved").length,sourcesSucceeded:results.filter(x=>x.state===QuestionDiscoverySourceState.Succeeded).length,sourcesPartial:results.filter(x=>x.state===QuestionDiscoverySourceState.Partial).length,sourcesUnavailable:results.filter(x=>[QuestionDiscoverySourceState.Unavailable,QuestionDiscoverySourceState.Unsupported].includes(x.state)).length,sourcesFailed:results.filter(x=>failures.has(x.state)).length,rawObservations:raw.length,questionCandidates:raw.filter(x=>this.intelligence.detect(x.properties.observedText)===QuestionDetection.ExplicitQuestion).length,searchIntentCandidates:raw.filter(x=>this.intelligence.detect(x.properties.observedText)===QuestionDetection.SearchIntentPhrase).length,sourceCategoryCoverage:new Set(raw.map(x=>x.properties.sourceCategory)).size,market:request.scope.market,language:request.scope.language,freshnessWindowMs:request.freshnessWindowMs});}
 private ensureScope(request:QuestionDiscoveryRequest,profile:QuestionDiscoveryProfile){const a=request.scope,b=profile.scope;if(a.businessPackageId.value!==b.businessPackageId.value||a.market!==b.market||a.language!==b.language||a.channel!==b.channel||a.purpose!==b.purpose)throw new Error("Discovery request and Business Package profile scope differ");}
 private record(action:string,request:QuestionDiscoveryRequest,result:string,provider?:string){const sequence=++this.#sequence,at=this.clock(),safeContext={businessPackageId:request.scope.businessPackageId.value,market:request.scope.market,language:request.scope.language,seedType:request.seed.type,capability:provider??"multi-source"};if(this.audit)this.audit.append(new AuditEvent({id:`question-discovery-${sequence}`,timestamp:at,type:AuditEventType.WorkflowEvent,source:"QuestionDiscovery",action,result,responsibleIdentity:"TCO",relatedTaskOrWorkflowId:request.id.value,context:safeContext}));if(this.events)this.events.publish(new Event({id:new EventId(`question-discovery-event-${sequence}`),type:new EventType(action),timestamp:at,source:"QuestionDiscovery",correlationId:request.correlationId.value}));}
}
