import { BusinessPackageId, MarketSourceId } from "../MarketIntelligenceDomain.ts";
import { MarketSourceAdapterId, MarketSourceCapability, MarketSourceDescriptor, RawMarketRecord } from "../integration/MarketSourceIntegrationDomain.ts";
import type { MarketSourceAdapter } from "../integration/MarketSourceIntegrationDomain.ts";
import type { CredentialId } from "../../../security/credentials/CredentialVault.ts";
import type { ObservedQuestion } from "../../../business/market/questions/QuestionIntelligenceDomain.ts";

export class QuestionDiscoveryException extends Error { constructor(message:string){super(message);this.name="QuestionDiscoveryException";} }
const required=(value:string,field:string)=>{if(typeof value!=="string"||value.trim()==="")throw new QuestionDiscoveryException(`${field} is required`);return value;};
const date=(value:Date,field:string)=>{if(!(value instanceof Date)||!Number.isFinite(value.getTime()))throw new QuestionDiscoveryException(`${field} is invalid`);return new Date(value);};
const frozen=<T>(values:readonly T[])=>Object.freeze([...values]);

export enum QuestionDiscoverySourceCategory { SearchEngine="SearchEngine",SearchSuggestion="SearchSuggestion",RelatedQuestion="RelatedQuestion",RelatedSearch="RelatedSearch",QuestionAnswerPlatform="QuestionAnswerPlatform",Forum="Forum",Community="Community",DiscussionPlatform="DiscussionPlatform",VideoDiscovery="VideoDiscovery",TopicPortal="TopicPortal",AuthorizedAnalytics="AuthorizedAnalytics",ManualImport="ManualImport",OtherApprovedPublicSource="OtherApprovedPublicSource" }
export enum QuestionDiscoverySeedType { TopicSeed="TopicSeed",QuestionSeed="QuestionSeed",IntentSeed="IntentSeed",PatternSeed="PatternSeed",ExistingContentSeed="ExistingContentSeed",BusinessMemorySeed="BusinessMemorySeed",ApprovedManualSeed="ApprovedManualSeed" }
export enum QuestionDiscoveryDepth { Shallow="Shallow",Standard="Standard",Deep="Deep" }
export enum QuestionDiscoverySourceState { Pending="Pending",Running="Running",Succeeded="Succeeded",Partial="Partial",NoData="NoData",Unavailable="Unavailable",AuthenticationRequired="AuthenticationRequired",InvalidCredential="InvalidCredential",ReauthorizationRequired="ReauthorizationRequired",PermissionDenied="PermissionDenied",RateLimited="RateLimited",Failed="Failed",Unsupported="Unsupported",Cancelled="Cancelled" }
export enum QuestionDiscoveryRunState { Pending="Pending",Running="Running",Completed="Completed",Partial="Partial",AttentionRequired="AttentionRequired",Cancelled="Cancelled" }
export enum DiscoveryFeatureType { SearchResultQuestion="SearchResultQuestion",QuerySuggestion="QuerySuggestion",RelatedQuestion="RelatedQuestion",RelatedSearch="RelatedSearch",PostTitle="PostTitle",ThreadTitle="ThreadTitle",QuestionAnswer="QuestionAnswer",VideoTitle="VideoTitle",PortalQuestion="PortalQuestion",SearchIntentPhrase="SearchIntentPhrase" }

export class QuestionDiscoveryRequestId { constructor(readonly value:string){required(value,"Discovery request identifier");Object.freeze(this);} }
export class QuestionDiscoveryRunId { constructor(readonly value:string){required(value,"Discovery run identifier");Object.freeze(this);} }
export class QuestionDiscoveryCorrelationId { constructor(readonly value:string){required(value,"Discovery correlation identifier");Object.freeze(this);} }
export class QuestionDiscoverySeed { constructor(readonly type:QuestionDiscoverySeedType,readonly value:string){required(value,"Discovery seed");Object.freeze(this);} }
export class QuestionDiscoveryScope { constructor(readonly businessPackageId:BusinessPackageId,readonly channel:string,readonly purpose:string,readonly market:string,readonly language:string){if(!(businessPackageId instanceof BusinessPackageId))throw new QuestionDiscoveryException("Business Package is required");[channel,purpose,market,language].forEach((x,i)=>required(x,["Channel","Purpose","Market","Language"][i]));Object.freeze(this);} }
export interface QuestionDiscoverySourceRequest {readonly capability:MarketSourceCapability;readonly categories:readonly QuestionDiscoverySourceCategory[];readonly required?:boolean;}
export class QuestionDiscoveryRequest { readonly sourceRequests:readonly QuestionDiscoverySourceRequest[];readonly requestedAt:Date;constructor(readonly id:QuestionDiscoveryRequestId,readonly correlationId:QuestionDiscoveryCorrelationId,readonly scope:QuestionDiscoveryScope,readonly seed:QuestionDiscoverySeed,readonly depth:QuestionDiscoveryDepth,readonly freshnessWindowMs:number|undefined,sources:readonly QuestionDiscoverySourceRequest[],readonly maximumObservations:number,requestedAt:Date){if(sources.length===0||sources.some(x=>!(x.capability instanceof MarketSourceCapability)||x.categories.length===0))throw new QuestionDiscoveryException("At least one source capability is required");if(!Number.isInteger(maximumObservations)||maximumObservations<1)throw new QuestionDiscoveryException("Maximum observations must be positive");if(freshnessWindowMs!==undefined&&(!Number.isFinite(freshnessWindowMs)||freshnessWindowMs<0))throw new QuestionDiscoveryException("Freshness window is invalid");this.sourceRequests=frozen(sources.map(x=>Object.freeze({...x,categories:frozen(x.categories)})));this.requestedAt=date(requestedAt,"Request timestamp");Object.freeze(this);} }

export class QuestionDiscoveryProfile {readonly enabledSourceCategories:readonly QuestionDiscoverySourceCategory[];readonly enabledProviders:readonly string[];readonly disabledProviders:readonly string[];readonly credentialReferences:ReadonlyMap<string,CredentialId>;constructor(readonly scope:QuestionDiscoveryScope,categories:readonly QuestionDiscoverySourceCategory[],enabled:readonly string[],disabled:readonly string[],readonly depth:QuestionDiscoveryDepth,readonly freshnessWindowMs:number|undefined,readonly maximumObservations:number,readonly targetSourceCategories:number,credentials:ReadonlyMap<string,CredentialId>=new Map()){if(targetSourceCategories<1||!Number.isInteger(targetSourceCategories))throw new QuestionDiscoveryException("Diversity target must be positive");this.enabledSourceCategories=frozen(categories);this.enabledProviders=frozen(enabled);this.disabledProviders=frozen(disabled);this.credentialReferences=new Map(credentials);Object.freeze(this);} }

export interface DiscoveryObservationProperties {readonly rawRecord:RawMarketRecord;readonly provider:string;readonly sourceCategory:QuestionDiscoverySourceCategory;readonly featureType:DiscoveryFeatureType;readonly observedText:string;readonly sourceReference:string;readonly market:string;readonly language:string;readonly seed:QuestionDiscoverySeed;readonly context?:string;readonly independenceReference?:string;}
/** Technical adapter output. Wording is retained verbatim; semantic classification is downstream. */
export class DiscoveryRawObservation {constructor(readonly properties:DiscoveryObservationProperties){required(properties.provider,"Provider");required(properties.observedText,"Observed text");required(properties.sourceReference,"Source reference");required(properties.market,"Market");required(properties.language,"Language");if(properties.rawRecord.properties.sourceId.value!==properties.rawRecord.provenance.sourceId.value)throw new QuestionDiscoveryException("Source provenance is inconsistent");Object.freeze(this);}get collectedAt(){return new Date(this.properties.rawRecord.properties.collectedAt);}get observedAt(){return this.properties.rawRecord.properties.observedAt&&new Date(this.properties.rawRecord.properties.observedAt);} }
export interface QuestionDiscoveryAdapterResult {readonly state:QuestionDiscoverySourceState;readonly observations:readonly DiscoveryRawObservation[];readonly safeMessage?:string;readonly retryAfter?:Date;}
export interface QuestionDiscoveryAdapter extends MarketSourceAdapter {readonly id:MarketSourceAdapterId;descriptor():MarketSourceDescriptor;discover(request:QuestionDiscoveryRequest,sourceRequest:QuestionDiscoverySourceRequest,signal?:AbortSignal):Promise<QuestionDiscoveryAdapterResult>;}
export class QuestionDiscoverySourceResult {readonly observations:readonly DiscoveryRawObservation[];readonly attemptedAt:Date;constructor(readonly adapterId:MarketSourceAdapterId,readonly sourceId:MarketSourceId,readonly category:QuestionDiscoverySourceCategory,readonly capability:MarketSourceCapability,readonly state:QuestionDiscoverySourceState,observations:readonly DiscoveryRawObservation[],attemptedAt:Date,readonly safeMessage?:string,readonly retryAfter?:Date){this.observations=frozen(observations);this.attemptedAt=date(attemptedAt,"Attempt timestamp");Object.freeze(this);} }
export interface QuestionDiscoverySummary {readonly sourcesRequested:number;readonly sourcesAttempted:number;readonly sourcesSucceeded:number;readonly sourcesPartial:number;readonly sourcesUnavailable:number;readonly sourcesFailed:number;readonly rawObservations:number;readonly questionCandidates:number;readonly searchIntentCandidates:number;readonly sourceCategoryCoverage:number;readonly market:string;readonly language:string;readonly freshnessWindowMs:number|undefined;}
export class QuestionDiscoveryRun {readonly sourceResults:readonly QuestionDiscoverySourceResult[];readonly observations:readonly DiscoveryRawObservation[];readonly questionIntelligenceHandoff:readonly ObservedQuestion[];constructor(readonly id:QuestionDiscoveryRunId,readonly request:QuestionDiscoveryRequest,readonly state:QuestionDiscoveryRunState,results:readonly QuestionDiscoverySourceResult[],observations:readonly DiscoveryRawObservation[],handoff:readonly ObservedQuestion[],readonly summary:QuestionDiscoverySummary,readonly completedAt:Date){this.sourceResults=frozen(results);this.observations=frozen(observations);this.questionIntelligenceHandoff=frozen(handoff);date(completedAt,"Completion timestamp");Object.freeze(this);} }
export interface QuestionSourceHealthReadModel {readonly provider:string;readonly capability:string;readonly status:QuestionDiscoverySourceState;readonly lastChecked:Date;readonly lastSuccess?:Date;readonly lastError?:string;readonly authentication:string;readonly rateLimitRetryAt?:Date;readonly markets:readonly string[];readonly languages:readonly string[];}
export interface QuestionSourceManagementReadModel extends QuestionSourceHealthReadModel {readonly source:string;readonly type:string;readonly enabled:boolean;}
export const QUESTION_DISCOVERY_EVENTS=Object.freeze(["QuestionDiscoveryRequested","QuestionDiscoveryStarted","QuestionSourceCollectionStarted","QuestionSourceCollectionSucceeded","QuestionSourceCollectionPartial","QuestionSourceAuthenticationRequired","QuestionSourceRateLimited","QuestionSourceUnavailable","QuestionSourceCollectionFailed","QuestionDiscoveryCompleted","QuestionDiscoveryCancelled"] as const);
