/** UI projections only: backend services supply every classification, explanation, and rank. */
export type IntelligenceView="questions"|"opportunities"|"recommendations"|"sources";
export interface QuestionWorkspaceQuery{businessPackageId:string;view:IntelligenceView;page:number;pageSize:number;search?:string;status?:string;market?:string;language?:string;sort?:string}
export interface QuestionListItemView{id:string;businessPackageId:string;canonicalQuestion:string;language:string;market:string;intent:string;trend:string;confidence:number|string|undefined;observationCount:number|undefined;independentObservations:number|undefined;sourceDiversity:number|undefined;coverage:string;opportunityStatus:string;recommendationStatus:string;freshness:string}
export interface QuestionSourceBreakdownView{category:string;count:number}
export interface QuestionEvidenceView{id:string;position:"Supporting"|"Contradictory";text:string;sourceCategory:string;provider?:string;safeReference?:string;observedAt:string}
export interface RelatedQuestionView{id:string;canonicalQuestion:string;relationship:string}
export interface QuestionDetailView extends QuestionListItemView{variants:readonly string[];sourceCategoryCount:number;sourceBreakdown:readonly QuestionSourceBreakdownView[];sourceReferences:readonly QuestionEvidenceView[];supportingEvidence:readonly string[];contradictoryEvidence:readonly string[];trendHistory:readonly {period:string;count:number}[];contentGap:string;relatedBlogs:readonly {id:string;title:string;coverage:string;publicationState:string}[];relatedBooks:readonly {id:string;title:string}[];production:readonly {title:string;state:string}[];opportunityType?:string;opportunityConfidence?:number|string;duplicateRisk?:string;knowledgeReadiness?:string;relatedQuestions:readonly RelatedQuestionView[];history:readonly string[];pipelineStage:string}
export interface BlogOpportunityListView{id:string;businessPackageId:string;canonicalQuestion:string;opportunityType:string;status:string;confidence:number|string|undefined;trend:string;coverage:string;duplicateRisk:string;knowledgeReadiness:string;market:string;language:string;priority:string;lastEvaluated:string}
export interface BlogOpportunityDetailView extends BlogOpportunityListView{whyThis:readonly string[];questionEvidence:readonly string[];competitiveContext:readonly string[];evidenceGaps:readonly string[];value:string;effort:string;risk:string;strategicRelevance:string;projectedTraffic:number|"Unknown";recommendedNextStep:string;history:readonly string[]}
export interface BlogRecommendationListView{id:string;version:number;businessPackageId:string;canonicalQuestion:string;recommendedAction:string;confidence:number|string|undefined;value:string;effort:string;risk:string;priority:string;knowledgeReadiness:string;market:string;language:string;status:string;created:string}
export interface BlogRecommendationDetailView extends BlogRecommendationListView{whyThis:readonly string[];whyNow:readonly string[];questionEvidence:readonly string[];sourceDiversity:number|undefined;trend:string;coverage:string;duplicateRisk:string;competitiveContext:readonly string[];searchDiscoveryRelevance:string;aiDiscoveryRelevance:string;unknowns:readonly string[];history:readonly string[];staleVersion:boolean;newVersionId?:string}
export interface QuestionWorkspaceReadModel<T=QuestionListItemView|BlogOpportunityListView|BlogRecommendationListView|QuestionEvidenceView>{businessPackageId:string;items:readonly T[];total:number;page:number;pageSize:number;readyForCEOReview:number;sourceHealth:readonly {label:string;state:string}[]}
export interface RecommendationReviewCommand{businessPackageId:string;recommendationId:string;version:number;decision:"Approve"|"Reject"|"Defer"|"RequestMoreResearch";note?:string}
export type CEOActionState="Submitting"|"Succeeded"|"Failed"|"Conflict"|"AuthorizationDenied"|"StaleVersion";
export interface QuestionWorkspaceGateway{read(query:QuestionWorkspaceQuery):Promise<QuestionWorkspaceReadModel>;detail(query:{businessPackageId:string;view:IntelligenceView;id:string}):Promise<QuestionDetailView|BlogOpportunityDetailView|BlogRecommendationDetailView>;reviewRecommendation(command:RecommendationReviewCommand):Promise<{state:CEOActionState}>}
