import type {AuthorizationDecision} from "../../../../core/platform/AuthorizationDecision.ts";
import type {BusinessPackageId,Provenance} from "../../../../intelligence/market/MarketIntelligenceDomain.ts";
import type {BlogContentCreationPlan} from "../planning/BlogContentCreationPlanDomain.ts";
import type {BlogDraft,BlogDraftBookLink,BlogDraftCTA,BlogDraftInternalLink,BlogDraftValidationIssue} from "../writing/BlogWriterDomain.ts";
import {BlogDraftReviewException} from "./BlogDraftReviewException.ts";

const required=(value:string,name:string)=>{if(!value?.trim())throw new BlogDraftReviewException(`${name} is required`,"INVALID_REVIEW");};
const frozen=<T>(values:readonly T[])=>Object.freeze([...values]);
export class BlogDraftReviewId { constructor(readonly value:string){required(value,"Review identifier");Object.freeze(this);} }
export enum BlogDraftReviewState {Requested="Requested",Prepared="Prepared",ApprovedForPublishing="ApprovedForPublishing",RevisionRequired="RevisionRequired",Rejected="Rejected",DeletedFromActiveProduction="DeletedFromActiveProduction",Deferred="Deferred",ReviewNoLongerCurrent="ReviewNoLongerCurrent",Failed="Failed"}
export enum BlogDraftDecisionType {Approve="Approve",ReturnForRevision="ReturnForRevision",Reject="Reject",Delete="Delete",Defer="Defer"}
export enum BlogValidationSummaryState {Pass="PASS",Warn="WARN"}
export enum BlogReviewSort {Newest="newest",Oldest="oldest",Priority="priority",Language="language",Market="market",Status="status"}
export interface BlogDraftReviewRequestProperties {id:BlogDraftReviewId;draftId:string;draftVersion:number;businessPackageId:BusinessPackageId;requestingAuthorityReference:string;correlationIdentifier:string;requestedAt:Date;}
export class BlogDraftReviewRequest {readonly #at:number;constructor(readonly properties:BlogDraftReviewRequestProperties){for(const [v,n] of [[properties.draftId,"Draft identifier"],[properties.requestingAuthorityReference,"Requesting authority"],[properties.correlationIdentifier,"Correlation identifier"]] as const)required(v,n);if(!Number.isInteger(properties.draftVersion)||properties.draftVersion<1||!Number.isFinite(properties.requestedAt.getTime()))throw new BlogDraftReviewException("Draft version or request timestamp is invalid","INVALID_REVIEW");this.#at=properties.requestedAt.getTime();Object.freeze(this);}get id(){return this.properties.id;}get requestedAt(){return new Date(this.#at);}}
export interface BlogValidationFactor {state:BlogValidationSummaryState;factors:readonly string[];}
export interface BlogValidationSummary {structural:BlogValidationFactor;knowledgeFactual:BlogValidationFactor;style:BlogValidationFactor;searchDiscovery:BlogValidationFactor;aiDiscovery:BlogValidationFactor;links:BlogValidationFactor;businessPackageRules:BlogValidationFactor;}
export interface BlogReaderPreview {h1:string;headings:readonly {level:string;text:string}[];paragraphs:readonly string[];bookLinks:readonly BlogDraftBookLink[];internalLinks:readonly BlogDraftInternalLink[];primaryBookCTA?:BlogDraftCTA;}
export interface BlogStructuredReviewDetail {h1:string;canonicalQuestion:string;h1MatchesCanonicalQuestion:boolean;planId:string;planVersion:number;draftVersion:number;recommendationId:string;recommendationVersion:number;ceoRecommendationApprovalReference:string;market:string;language:string;intent:readonly string[];knowledgeSources:readonly {reference:string;usedInParagraphs:readonly string[]}[];sourceReferences:readonly {reference:string;usedInParagraphs:readonly string[]}[];relatedBooks:readonly BlogDraftBookLink[];primaryBook?:BlogDraftCTA;internalLinks:readonly BlogDraftInternalLink[];validation:BlogValidationSummary;warnings:readonly BlogDraftValidationIssue[];unresolvedNonBlockingIssues:readonly string[];pinterestHeadingLineage:BlogContentCreationPlan["pinterestLineage"];}
export class BlogDraftReviewPacket {constructor(readonly reviewId:BlogDraftReviewId,readonly draft:BlogDraft,readonly plan:BlogContentCreationPlan,readonly readerPreview:BlogReaderPreview,readonly detail:BlogStructuredReviewDetail){Object.freeze(this);} }
export class BlogDraftDecision {readonly #at:number;readonly #revisit?:number;constructor(readonly type:BlogDraftDecisionType,readonly authorization:AuthorizationDecision,at:Date,readonly note?:string,revisitAfter?:Date,readonly previousDecisionId?:string){if(note!==undefined)required(note,"CEO note");this.#at=at.getTime();this.#revisit=revisitAfter?.getTime();if(!Number.isFinite(this.#at)||this.#revisit!==undefined&&!Number.isFinite(this.#revisit))throw new BlogDraftReviewException("Decision timestamp is invalid","INVALID_DECISION");Object.freeze(this);}get timestamp(){return new Date(this.#at);}get revisitAfter(){return this.#revisit===undefined?undefined:new Date(this.#revisit);}}
export class BlogDraftDecisionRecord {readonly #at:number;readonly #revisit?:number;constructor(readonly decisionId:string,readonly reviewId:BlogDraftReviewId,readonly draftId:string,readonly draftVersion:number,readonly businessPackageId:BusinessPackageId,readonly decisionType:BlogDraftDecisionType,readonly ceoAuthorityReference:string,at:Date,readonly correlationIdentifier:string,readonly provenance:Provenance,readonly note?:string,revisitAfter?:Date,readonly supersedesDecisionId?:string){required(decisionId,"Decision identifier");this.#at=at.getTime();this.#revisit=revisitAfter?.getTime();Object.freeze(this);}get decisionTimestamp(){return new Date(this.#at);}get revisitAfter(){return this.#revisit===undefined?undefined:new Date(this.#revisit);}}
export interface BlogPublishingEligibilityHandoff {draftId:string;draftVersion:number;decisionId:string;businessPackageId:BusinessPackageId;planId:string;planVersion:number;recommendationId:string;recommendationVersion:number;canonicalQuestion:string;}
export class BlogDraftReviewResult {constructor(readonly state:BlogDraftReviewState,readonly packet:BlogDraftReviewPacket,readonly decision?:BlogDraftDecisionRecord,readonly publishingEligibility?:BlogPublishingEligibilityHandoff){Object.freeze(this);} }
export interface BlogReviewFilter {states?:readonly BlogDraftReviewState[];language?:string;market?:string;from?:Date;to?:Date;includeDeleted?:boolean;sort?:BlogReviewSort;}
export interface BlogReviewQueueRow {reviewId:string;title:string;language:string;market:string;status:BlogDraftReviewState;draftVersion:number;createdAt:Date;validationStatus:"PASS"|"WARN";priority?:string;recommendation:string;decisionState?:BlogDraftDecisionType;}
export const BLOG_DRAFT_REVIEW_EVENTS=Object.freeze(["BlogDraftReviewRequested","BlogDraftReviewPrepared","BlogDraftApproved","BlogDraftRevisionRequested","BlogDraftRejected","BlogDraftDeleted","BlogDraftDeferred","BlogDraftDecisionChanged","BlogDraftReviewFailed"] as const);
