import { Confidence, Freshness, FreshnessStatus } from "../../../intelligence/market/MarketIntelligenceDomain.ts";
import { PatternId } from "../patterns/PatternIntelligenceDomain.ts";
import { CanonicalQuestion, CanonicalQuestionH1Contract, ObservationOrigin, ObservedQuestion, QuestionCluster, QuestionClusterId, QuestionClusterStatus, QuestionContentGap, QuestionCoverage, QuestionCoverageState, QuestionDetection, QuestionTrend } from "./QuestionIntelligenceDomain.ts";
import type { QuestionCoverageEvidence, QuestionDetailReadModel, QuestionEvidenceSummary, QuestionIntent, QuestionListReadModel, RelatedQuestion } from "./QuestionIntelligenceDomain.ts";

export class QuestionIntelligenceService {
 normalize(text:string):string{return text.normalize("NFKC").toLocaleLowerCase().replace(/[\p{P}\p{S}]+/gu," ").replace(/\s+/g," ").trim();}
 detect(text:string):QuestionDetection {const value=text.trim();if(value==="")return QuestionDetection.Unknown;if(/[?？]$/.test(value)||/^(who|what|when|where|why|how|which|is|are|can|could|should|does|do|did|wer|was|wann|wo|warum|wieso|wie|welche|ist|sind|kann)\b/i.test(value))return QuestionDetection.ExplicitQuestion;if(/\b(help|problem|issue|need advice|brauche hilfe)\b/i.test(value))return QuestionDetection.ImplicitQuestion;if(value.split(/\s+/).length>=2)return QuestionDetection.SearchIntentPhrase;return QuestionDetection.NonQuestion;}
 classifyIntent(question:ObservedQuestion,types:readonly string[],explanation:string,confidence:Confidence):QuestionIntent {if(types.length===0||types.some(x=>x.trim()==="")||explanation.trim()==="")throw new Error("Intent requires extensible types and explanation");return Object.freeze({types:Object.freeze([...types]),explanation,evidenceReferences:Object.freeze([question.properties.evidence.id.value]),confidence,version:1});}
 summarize(observations:readonly ObservedQuestion[],contradicting:readonly ObservedQuestion[]=[]):QuestionEvidenceSummary {const human=observations.filter(x=>x.origin===ObservationOrigin.Human),unique=(values:readonly string[])=>new Set(values).size,latest=Math.max(...observations.map(x=>x.observedAt.getTime())),avg=human.length?human.reduce((n,x)=>n+x.properties.sourceQuality.value,0)/human.length:0,independent=unique(human.map(x=>x.properties.independenceKey)),categories=[...new Set(human.map(x=>x.properties.sourceCategory))],diversity=Math.min(1,categories.length/4),independence=Math.min(1,independent/4),contradictionPenalty=Math.min(.3,contradicting.length*.1),score=Math.max(0,Math.min(1,.1+avg*.35+diversity*.25+independence*.3-contradictionPenalty));return Object.freeze({observationCount:observations.length,humanObservationCount:human.length,independentObservationCount:independent,sourceCount:unique(human.map(x=>x.sourceId.value)),sourceCategoryCount:categories.length,marketCount:unique(human.map(x=>x.properties.market)),sourceCategories:Object.freeze(categories),supportingEvidence:Object.freeze(human.map(x=>x.properties.evidence)),contradictingEvidence:Object.freeze(contradicting.map(x=>x.properties.evidence)),freshness:new Freshness(FreshnessStatus.Current,new Date(latest)),confidence:new Confidence(Number(score.toFixed(4)))});}
 trend(monthlyCounts:readonly number[]):QuestionTrend {if(monthlyCounts.length<3||monthlyCounts.reduce((a,b)=>a+b,0)<4)return QuestionTrend.InsufficientEvidence;const [a,b,c]=monthlyCounts.slice(-3);if(a===0&&b===0&&c>0)return QuestionTrend.Emerging;if(a>0&&b===0&&c>0)return QuestionTrend.Reappearing;if(a<b&&b<c)return QuestionTrend.Growing;if(a>b&&b>c)return QuestionTrend.Declining;if(Math.max(a,b,c)-Math.min(a,b,c)<=1)return QuestionTrend.Stable;return QuestionTrend.InsufficientEvidence;}
 evaluateCoverage(evidence:readonly QuestionCoverageEvidence[]):QuestionCoverage {if(evidence.length===0)return new QuestionCoverage(QuestionCoverageState.NoCoverage,[]);const max=Math.max(...evidence.map(x=>x.semanticSimilarity));if(max<0||max>1)throw new Error("Semantic similarity must be between zero and one");return new QuestionCoverage(max>=.8?QuestionCoverageState.StrongCoverage:max>=.55?QuestionCoverageState.PartialCoverage:QuestionCoverageState.WeakCoverage,evidence);}
 cluster(id:string,observations:readonly ObservedQuestion[],intent:QuestionIntent,monthlyCounts:readonly number[],coverage:QuestionCoverage,options:{contradicting?:readonly ObservedQuestion[];related?:readonly RelatedQuestion[];patternId?:PatternId;now?:Date}={}):QuestionCluster {if(observations.length===0)throw new Error("Cluster requires observations");const humanExplicit=observations.filter(x=>x.origin===ObservationOrigin.Human&&x.properties.detection===QuestionDetection.ExplicitQuestion);if(humanExplicit.length===0)throw new Error("Cluster requires an explicit observed human question for canonical selection");const summary=this.summarize(observations,options.contradicting);const counts=new Map<string,number>();for(const x of humanExplicit)counts.set(x.originalText,(counts.get(x.originalText)??0)+1);const selected=[...humanExplicit].sort((a,b)=>(counts.get(b.originalText)!-counts.get(a.originalText)!)||(b.properties.sourceQuality.value-a.properties.sourceQuality.value)||(b.observedAt.getTime()-a.observedAt.getTime())||a.id.value.localeCompare(b.id.value))[0];const canonical=new CanonicalQuestion(selected,`Selected observed variant using frequency, source quality, freshness and deterministic identifier ordering; evidence ${selected.properties.evidence.id.value}.`);const gap=[QuestionCoverageState.NoCoverage,QuestionCoverageState.WeakCoverage].includes(coverage.state)&&summary.confidence.value>=.5?new QuestionContentGap(new QuestionClusterId(id),coverage,"Evidence-backed question pattern has inadequate Business Package coverage."):undefined;return new QuestionCluster(new QuestionClusterId(id),1,selected.businessPackageId,selected.properties.language,selected.properties.market,selected.semanticKey,observations,canonical,intent,summary,this.trend(monthlyCounts),QuestionClusterStatus.Observed,options.patternId,coverage,gap,options.related??[],`Variants share the declared semantic need '${selected.semanticKey}'; grouping is package, language and market scoped.`,options.now??new Date());}
 h1Contract(cluster:QuestionCluster){return new CanonicalQuestionH1Contract(cluster.canonical);}
 toListReadModel(c:QuestionCluster):QuestionListReadModel{return Object.freeze({clusterId:c.id.value,question:c.canonical.text,canonicalQuestion:c.canonical.text,language:c.language,market:c.market,intent:c.intent.types,observationCount:c.evidence.observationCount,independentObservationCount:c.evidence.independentObservationCount,sourceCount:c.evidence.sourceCount,sourceCategories:c.evidence.sourceCategories,trend:c.trend,confidence:c.evidence.confidence.value,coverage:c.coverage.state,contentGap:c.contentGap!==undefined,freshness:c.evidence.freshness.status});}
 toDetailReadModel(c:QuestionCluster):QuestionDetailReadModel{return Object.freeze({...this.toListReadModel(c),variants:Object.freeze(c.variants),sources:Object.freeze(c.observations.map(x=>Object.freeze({sourceId:x.sourceId.value,reference:x.properties.sourceReference,category:x.properties.sourceCategory,observedAt:x.observedAt,capability:x.properties.acquisitionCapability}))),intentExplanation:c.intent.explanation,supportingEvidence:Object.freeze(c.evidence.supportingEvidence.map(x=>x.id.value)),contradictingEvidence:Object.freeze(c.evidence.contradictingEvidence.map(x=>x.id.value)),relatedQuestions:c.relatedQuestions,coverageEvidence:c.coverage.evidence,canonicalSelectionExplanation:c.canonical.selectionExplanation});}
}

export const QUESTION_INTELLIGENCE_EVENTS=Object.freeze(["QuestionObservationReceived","QuestionDetected","QuestionClusterCreated","QuestionClusterUpdated","CanonicalQuestionSelected","QuestionIntentClassified","QuestionPatternEvidenceUpdated","QuestionCoverageEvaluated","QuestionContentGapDetected","QuestionIntelligenceInsufficientEvidence","QuestionIntelligenceFailed"] as const);
