import { BusinessPackageId, Confidence, Evidence, Freshness, MarketObservation, MarketSourceId } from "../../../intelligence/market/MarketIntelligenceDomain.ts";
import { PatternId } from "../patterns/PatternIntelligenceDomain.ts";

export class QuestionIntelligenceException extends Error { constructor(message:string, readonly code="INVALID_QUESTION_INTELLIGENCE") { super(message); this.name="QuestionIntelligenceException"; } }
const required=(v:string,f:string)=>{if(typeof v!=="string"||v.trim()==="")throw new QuestionIntelligenceException(`${f} is required`);return v;};
const frozen=<T>(v:readonly T[])=>Object.freeze([...v]);
const instant=(v:Date,f:string)=>{const n=v instanceof Date?v.getTime():NaN;if(!Number.isFinite(n))throw new QuestionIntelligenceException(`${f} is invalid`);return n;};

export class ObservedQuestionId { readonly #value:string; constructor(value:string){this.#value=required(value,"Observed question identifier");Object.freeze(this);} get value(){return this.#value;} }
export class QuestionClusterId { readonly #value:string; constructor(value:string){this.#value=required(value,"Question cluster identifier");Object.freeze(this);} get value(){return this.#value;} }
export enum QuestionDetection { ExplicitQuestion="ExplicitQuestion",ImplicitQuestion="ImplicitQuestion",SearchIntentPhrase="SearchIntentPhrase",NonQuestion="NonQuestion",Unknown="Unknown" }
export enum QuestionSourceCategory { SearchEngine="SearchEngine",RelatedSearch="RelatedSearch",QuerySuggestion="QuerySuggestion",QuestionAnswer="QuestionAnswer",Forum="Forum",Community="Community",Discussion="Discussion",VideoDiscovery="VideoDiscovery",PublicPortal="PublicPortal",Other="Other" }
export enum AcquisitionCapability { OfficialAPI="OfficialAPI",PublicFeed="PublicFeed",ApprovedSearchInterface="ApprovedSearchInterface",ManualImport="ManualImport",AuthorizedResource="AuthorizedResource",Other="Other" }
export enum ObservationOrigin { Human="Human",Synthetic="Synthetic" }
export enum QuestionTrend { Emerging="Emerging",Growing="Growing",Stable="Stable",Declining="Declining",Reappearing="Reappearing",InsufficientEvidence="InsufficientEvidence" }
export enum QuestionCoverageState { NoCoverage="NoCoverage",WeakCoverage="WeakCoverage",PartialCoverage="PartialCoverage",StrongCoverage="StrongCoverage",Unknown="Unknown" }
export enum QuestionRelationshipType { VariantOf="VariantOf",RelatedTo="RelatedTo",FollowUpTo="FollowUpTo",BroaderThan="BroaderThan",NarrowerThan="NarrowerThan",ContrastsWith="ContrastsWith" }
export enum QuestionClusterStatus { Candidate="Candidate",Observed="Observed",Verified="Verified",Archived="Archived" }

export interface ObservedQuestionProperties { id:ObservedQuestionId;version:number;observation:MarketObservation;evidence:Evidence;originalText:string;normalizedText:string;semanticKey:string;detection:QuestionDetection;sourceCategory:QuestionSourceCategory;acquisitionCapability:AcquisitionCapability;sourceReference:string;independenceKey:string;language:string;market:string;freshness:Freshness;sourceQuality:Confidence;origin?:ObservationOrigin;context?:string; }
/** Immutable evidence preserving observed wording separately from comparison data. */
export class ObservedQuestion {
 readonly #originalText:string; readonly properties:ObservedQuestionProperties;
 constructor(p:ObservedQuestionProperties){if(!Number.isInteger(p.version)||p.version<1)throw new QuestionIntelligenceException("Version must be positive");if(p.observation.businessPackageId===undefined)throw new QuestionIntelligenceException("A Business Package is required");for(const [v,f] of [[p.originalText,"Original text"],[p.normalizedText,"Normalized text"],[p.semanticKey,"Semantic key"],[p.sourceReference,"Source reference"],[p.independenceKey,"Independence key"],[p.language,"Language"],[p.market,"Market"]] as const)required(v,f);if(p.observation.sourceId.value!==p.evidence.provenance.sourceId.value||!p.evidence.observationIds.some(x=>x.value===p.observation.id.value))throw new QuestionIntelligenceException("Observation, evidence and provenance must remain linked");this.#originalText=p.originalText;this.properties=Object.freeze({...p,origin:p.origin??ObservationOrigin.Human});Object.freeze(this);}
 get id(){return this.properties.id;} get originalText(){return this.#originalText;} get normalizedText(){return this.properties.normalizedText;} get semanticKey(){return this.properties.semanticKey;} get businessPackageId(){return this.properties.observation.businessPackageId!;} get observedAt(){return this.properties.observation.observedAt;} get sourceId():MarketSourceId{return this.properties.observation.sourceId;} get origin(){return this.properties.origin!;}
}
export interface QuestionIntent { readonly types:readonly string[];readonly explanation:string;readonly evidenceReferences:readonly string[];readonly confidence:Confidence;readonly version:number; }
export interface QuestionEvidenceSummary {readonly observationCount:number;readonly humanObservationCount:number;readonly independentObservationCount:number;readonly sourceCount:number;readonly sourceCategoryCount:number;readonly marketCount:number;readonly sourceCategories:readonly QuestionSourceCategory[];readonly supportingEvidence:readonly Evidence[];readonly contradictingEvidence:readonly Evidence[];readonly freshness:Freshness;readonly confidence:Confidence;}
export class CanonicalQuestion { readonly text:string;constructor(readonly selectedObservation:ObservedQuestion,readonly selectionExplanation:string){if(selectedObservation.origin!==ObservationOrigin.Human||selectedObservation.properties.detection!==QuestionDetection.ExplicitQuestion)throw new QuestionIntelligenceException("Canonical question must be an observed explicit human question");this.text=selectedObservation.originalText;required(selectionExplanation,"Canonical selection explanation");Object.freeze(this);} get provenance(){return this.selectedObservation.properties.evidence.provenance;} }
/** The sole downstream H1 authority; no mutation or alternate wording API is exposed. */
export class CanonicalQuestionH1Contract { readonly canonicalQuestionText:string;constructor(canonical:CanonicalQuestion){this.canonicalQuestionText=canonical.text;Object.freeze(this);} }
export interface RelatedQuestion {readonly questionId:ObservedQuestionId;readonly relationship:QuestionRelationshipType;readonly explanation:string;}
export interface QuestionCoverageEvidence {readonly contentReference:string;readonly semanticSimilarity:number;readonly explanation:string;}
export class QuestionCoverage {readonly evidence:readonly QuestionCoverageEvidence[];constructor(readonly state:QuestionCoverageState,evidence:readonly QuestionCoverageEvidence[]){this.evidence=frozen(evidence.map(x=>Object.freeze({...x})));Object.freeze(this);}}
export class QuestionContentGap {constructor(readonly clusterId:QuestionClusterId,readonly coverage:QuestionCoverage,readonly explanation:string){if(![QuestionCoverageState.NoCoverage,QuestionCoverageState.WeakCoverage].includes(coverage.state))throw new QuestionIntelligenceException("Content gap requires weak or absent coverage");required(explanation,"Content gap explanation");Object.freeze(this);}}
export class QuestionCluster {readonly observations:readonly ObservedQuestion[];readonly relatedQuestions:readonly RelatedQuestion[];readonly #created:number;constructor(readonly id:QuestionClusterId,readonly version:number,readonly businessPackageId:BusinessPackageId,readonly language:string,readonly market:string,readonly semanticKey:string,observations:readonly ObservedQuestion[],readonly canonical:CanonicalQuestion,readonly intent:QuestionIntent,readonly evidence:QuestionEvidenceSummary,readonly trend:QuestionTrend,readonly status:QuestionClusterStatus,readonly patternId:PatternId|undefined,readonly coverage:QuestionCoverage,readonly contentGap:QuestionContentGap|undefined,relatedQuestions:readonly RelatedQuestion[],readonly groupingExplanation:string,createdAt:Date){if(observations.length===0||observations.some(x=>x.businessPackageId.value!==businessPackageId.value||x.properties.language!==language||x.properties.market!==market||x.semanticKey!==semanticKey))throw new QuestionIntelligenceException("Cluster observations must share package, language, market and semantic need");if(!observations.includes(canonical.selectedObservation))throw new QuestionIntelligenceException("Canonical question must originate from a cluster variant");this.observations=frozen(observations);this.relatedQuestions=frozen(relatedQuestions.map(x=>Object.freeze({...x})));this.#created=instant(createdAt,"Cluster creation timestamp");required(groupingExplanation,"Grouping explanation");Object.freeze(this);}get createdAt(){return new Date(this.#created);}get variants(){return this.observations.map(x=>x.originalText);} }
export interface QuestionListReadModel {readonly clusterId:string;readonly question:string;readonly canonicalQuestion:string;readonly language:string;readonly market:string;readonly intent:readonly string[];readonly observationCount:number;readonly independentObservationCount:number;readonly sourceCount:number;readonly sourceCategories:readonly QuestionSourceCategory[];readonly trend:QuestionTrend;readonly confidence:number;readonly coverage:QuestionCoverageState;readonly contentGap:boolean;readonly freshness:string;}
export interface QuestionDetailReadModel extends QuestionListReadModel {readonly variants:readonly string[];readonly sources:readonly {sourceId:string;reference:string;category:QuestionSourceCategory;observedAt:Date;capability:AcquisitionCapability}[];readonly intentExplanation:string;readonly supportingEvidence:readonly string[];readonly contradictingEvidence:readonly string[];readonly relatedQuestions:readonly RelatedQuestion[];readonly coverageEvidence:readonly QuestionCoverageEvidence[];readonly canonicalSelectionExplanation:string;}
