import { BusinessPackageId, Confidence, Evidence, Freshness, Provenance } from "../../../intelligence/market/MarketIntelligenceDomain.ts";
import { PerformanceIntelligenceException } from "./PerformanceIntelligenceException.ts";

function text(value:string,field:string):string { if(typeof value!=="string"||value.trim()==="") throw new PerformanceIntelligenceException(`${field} must not be empty`,"INVALID_PERFORMANCE_RECORD"); return value; }
function instant(value:Date,field:string):number { const time=value instanceof Date?value.getTime():NaN;if(!Number.isFinite(time))throw new PerformanceIntelligenceException(`${field} must be a valid timestamp`,"INVALID_TIMESTAMP");return time; }
function list<T>(values:readonly T[]):readonly T[]{return Object.freeze([...values]);}

export class PerformanceRecordId { readonly #value:string;constructor(value:string){this.#value=text(value,"Performance record identifier");Object.freeze(this);}get value():string{return this.#value;}toString():string{return this.value;} }
export enum PerformanceMetricType { Traffic="Traffic",Impressions="Impressions",Reach="Reach",Engagement="Engagement",Clicks="Clicks",CTR="CTR",Saves="Saves",Shares="Shares",Comments="Comments",Reactions="Reactions",Conversions="Conversions",ConversionRate="ConversionRate",Sales="Sales",Revenue="Revenue",CampaignPerformance="CampaignPerformance",ContentPerformance="ContentPerformance",CapabilityPerformance="CapabilityPerformance",WorkflowPerformance="WorkflowPerformance",RecommendationAccuracy="RecommendationAccuracy",Custom="Custom" }
export enum MetricAvailability { Available="Available",Unavailable="Unavailable",NotApplicable="NotApplicable",Unknown="Unknown",Estimated="Estimated" }
export enum PerformanceDimension { Content="Content",Campaign="Campaign",Product="Product",Workflow="Workflow",Capability="Capability",Recommendation="Recommendation",Other="Other" }
export class SubjectReference { constructor(readonly id:string,readonly dimension:PerformanceDimension){text(id,"Subject reference");if(!Object.values(PerformanceDimension).includes(dimension))throw new PerformanceIntelligenceException("Performance dimension is invalid","INVALID_SUBJECT");Object.freeze(this);} }
export class OriginReference { constructor(readonly id:string,readonly type:string){text(id,"Origin reference");text(type,"Origin reference type");Object.freeze(this);} }

export class MeasurementWindow { readonly #start:number;readonly #end:number;constructor(start:Date,end:Date,readonly timezone="UTC"){this.#start=instant(start,"Measurement window start");this.#end=instant(end,"Measurement window end");text(timezone,"Measurement window timezone");if(this.#end<this.#start)throw new PerformanceIntelligenceException("Measurement window end cannot precede start","INVALID_MEASUREMENT_WINDOW");Object.freeze(this);}get start():Date{return new Date(this.#start);}get end():Date{return new Date(this.#end);}get durationMilliseconds():number{return this.#end-this.#start;} }

export interface PerformanceMetricProperties { type:PerformanceMetricType;value?:number;unit:string;measuredAt:Date;window?:MeasurementWindow;provenance:Provenance;availability:MetricAvailability;businessPackageId:BusinessPackageId;subject:SubjectReference;confidence?:Confidence;customType?:string; }
export class PerformanceMetric { readonly #measured:number;readonly type;readonly value;readonly unit;readonly window;readonly provenance;readonly availability;readonly businessPackageId;readonly subject;readonly confidence;readonly customType;
 constructor(p:PerformanceMetricProperties){if(!Object.values(PerformanceMetricType).includes(p.type))throw new PerformanceIntelligenceException("Metric type is invalid","INVALID_METRIC");if(!Object.values(MetricAvailability).includes(p.availability))throw new PerformanceIntelligenceException("Metric availability is invalid","INVALID_METRIC");text(p.unit,"Metric unit");if(!(p.provenance instanceof Provenance))throw new PerformanceIntelligenceException("Metric provenance is required","INVALID_PROVENANCE");if(!(p.businessPackageId instanceof BusinessPackageId)||!(p.subject instanceof SubjectReference))throw new PerformanceIntelligenceException("Metric context is required","INVALID_METRIC");if((p.availability===MetricAvailability.Available||p.availability===MetricAvailability.Estimated)!== (p.value!==undefined))throw new PerformanceIntelligenceException("Available and Estimated metrics require a value; other states must not contain one","INVALID_METRIC_VALUE");if(p.value!==undefined&&!Number.isFinite(p.value))throw new PerformanceIntelligenceException("Metric value must be finite","INVALID_METRIC_VALUE");if(p.type===PerformanceMetricType.Custom)text(p.customType??"","Custom metric type");this.#measured=instant(p.measuredAt,"Metric measurement timestamp");this.type=p.type;this.value=p.value;this.unit=p.unit;this.window=p.window;this.provenance=p.provenance;this.availability=p.availability;this.businessPackageId=p.businessPackageId;this.subject=p.subject;this.confidence=p.confidence;this.customType=p.customType;Object.freeze(this);}get measuredAt():Date{return new Date(this.#measured);} }

interface ObservationProperties { id:PerformanceRecordId;subject:SubjectReference;businessPackageId:BusinessPackageId;metrics:readonly PerformanceMetric[];measuredAt:Date;window:MeasurementWindow;evidence:readonly Evidence[];provenance:Provenance;confidence:Confidence;freshness:Freshness; }
export class PerformanceObservation { readonly #measured:number;readonly metrics;readonly evidence;readonly properties:ObservationProperties;constructor(properties:ObservationProperties){this.#measured=instant(properties.measuredAt,"Observation timestamp");validateMetrics(properties.metrics,properties.businessPackageId,properties.subject);this.metrics=list(properties.metrics);this.evidence=list(properties.evidence);this.properties=Object.freeze({...properties,metrics:this.metrics,evidence:this.evidence});Object.freeze(this);}get id(){return this.properties.id;}get subject(){return this.properties.subject;}get businessPackageId(){return this.properties.businessPackageId;}get window(){return this.properties.window;}get provenance(){return this.properties.provenance;}get confidence(){return this.properties.confidence;}get freshness(){return this.properties.freshness;}get measuredAt():Date{return new Date(this.#measured);} }
export interface ExpectedOutcomeProperties { id:PerformanceRecordId;subject:SubjectReference;businessPackageId:BusinessPackageId;metrics:readonly PerformanceMetric[];window:MeasurementWindow;expectedAt:Date;origin?:OriginReference;confidence:Confidence;provenance:Provenance; }
export class ExpectedOutcome { readonly #at:number;readonly metrics;readonly properties:ExpectedOutcomeProperties;constructor(properties:ExpectedOutcomeProperties){this.#at=instant(properties.expectedAt,"Expectation timestamp");if(this.#at>=properties.window.start.getTime())throw new PerformanceIntelligenceException("Expected outcome must be established before its measured period begins","LATE_EXPECTATION");validateMetrics(properties.metrics,properties.businessPackageId,properties.subject);this.metrics=list(properties.metrics);this.properties=Object.freeze({...properties,metrics:this.metrics});Object.freeze(this);}get id(){return this.properties.id;}get subject(){return this.properties.subject;}get businessPackageId(){return this.properties.businessPackageId;}get window(){return this.properties.window;}get origin(){return this.properties.origin;}get confidence(){return this.properties.confidence;}get provenance(){return this.properties.provenance;}get expectedAt():Date{return new Date(this.#at);} }
export interface ObservedOutcomeProperties { id:PerformanceRecordId;subject:SubjectReference;businessPackageId:BusinessPackageId;observationIds:readonly PerformanceRecordId[];metrics:readonly PerformanceMetric[];window:MeasurementWindow;evidence:readonly Evidence[];provenance:Provenance;confidence:Confidence; }
export class ObservedOutcome { readonly observationIds;readonly metrics;readonly evidence;readonly properties:ObservedOutcomeProperties;constructor(properties:ObservedOutcomeProperties){validateMetrics(properties.metrics,properties.businessPackageId,properties.subject);this.observationIds=list(properties.observationIds);this.metrics=list(properties.metrics);this.evidence=list(properties.evidence);this.properties=Object.freeze({...properties,observationIds:this.observationIds,metrics:this.metrics,evidence:this.evidence});Object.freeze(this);}get id(){return this.properties.id;}get subject(){return this.properties.subject;}get businessPackageId(){return this.properties.businessPackageId;}get window(){return this.properties.window;}get provenance(){return this.properties.provenance;}get confidence(){return this.properties.confidence;} }
function validateMetrics(metrics:readonly PerformanceMetric[],pkg:BusinessPackageId,subject:SubjectReference):void {if(metrics.length===0)throw new PerformanceIntelligenceException("At least one performance metric is required","MISSING_METRICS");if(metrics.some(m=>m.businessPackageId.value!==pkg.value||m.subject.id!==subject.id||m.subject.dimension!==subject.dimension))throw new PerformanceIntelligenceException("Metrics must share their record's Business Package and subject","CONTEXT_MISMATCH");}

export enum OutcomeClassification { Exceeded="Exceeded",Met="Met",BelowExpected="BelowExpected",Failed="Failed",Neutral="Neutral",Inconclusive="Inconclusive",Unavailable="Unavailable" }
export enum ComparisonStatus { Exceeded="Exceeded",Met="Met",BelowExpected="BelowExpected",Failed="Failed",Neutral="Neutral",Inconclusive="Inconclusive",Unavailable="Unavailable" }
export class OutcomeComparison { readonly evidence;constructor(readonly metricType:PerformanceMetricType,readonly expectedValue:number|undefined,readonly observedValue:number|undefined,readonly unit:string,readonly absoluteDifference:number|undefined,readonly relativeDifference:number|undefined,readonly status:ComparisonStatus,readonly availability:MetricAvailability,readonly confidence:Confidence,evidence:readonly Evidence[]){this.evidence=list(evidence);Object.freeze(this);} }
export interface PerformanceEvaluationProperties { id:PerformanceRecordId;expectedOutcomeId?:PerformanceRecordId;observedOutcomeId:PerformanceRecordId;comparisons:readonly OutcomeComparison[];classification:OutcomeClassification;evidence:readonly Evidence[];confidence:Confidence;evaluatedAt:Date;businessPackageId:BusinessPackageId;provenance:Provenance; }
export class PerformanceEvaluation { readonly #at:number;readonly comparisons;readonly evidence;readonly properties:PerformanceEvaluationProperties;constructor(properties:PerformanceEvaluationProperties){this.#at=instant(properties.evaluatedAt,"Evaluation timestamp");this.comparisons=list(properties.comparisons);this.evidence=list(properties.evidence);this.properties=Object.freeze({...properties,comparisons:this.comparisons,evidence:this.evidence});Object.freeze(this);}get id(){return this.properties.id;}get expectedOutcomeId(){return this.properties.expectedOutcomeId;}get observedOutcomeId(){return this.properties.observedOutcomeId;}get classification(){return this.properties.classification;}get confidence(){return this.properties.confidence;}get businessPackageId(){return this.properties.businessPackageId;}get provenance(){return this.properties.provenance;}get evaluatedAt():Date{return new Date(this.#at);} }
