import { Confidence } from "../../../intelligence/market/MarketIntelligenceDomain.ts";
import { ComparisonStatus, ExpectedOutcome, MetricAvailability, ObservedOutcome, OutcomeClassification, OutcomeComparison, PerformanceEvaluation, PerformanceObservation, PerformanceRecordId } from "./PerformanceIntelligenceDomain.ts";
import { PerformanceRepository } from "./PerformanceRepository.ts";
import type { PerformanceHistory, PerformanceHistoryFilter } from "./PerformanceRepository.ts";
import { PerformanceIntelligenceException } from "./PerformanceIntelligenceException.ts";

export class PerformanceIntelligenceService {
 constructor(private readonly repository:PerformanceRepository){}
 registerObservation(value:PerformanceObservation):PerformanceObservation{this.repository.storeObservation(value);return value;}
 registerExpectedOutcome(value:ExpectedOutcome):ExpectedOutcome{this.repository.storeExpectedOutcome(value);return value;}
 registerObservedOutcome(value:ObservedOutcome):ObservedOutcome{for(const id of value.observationIds){const observation=this.repository.observation(id);if(!observation)throw new PerformanceIntelligenceException(`Performance observation is not registered: ${id.value}`,"UNKNOWN_OBSERVATION");if(observation.businessPackageId.value!==value.businessPackageId.value)throw new PerformanceIntelligenceException("Observed outcome cannot reference another Business Package","PACKAGE_MISMATCH");}this.repository.storeObservedOutcome(value);return value;}
 compare(expected:ExpectedOutcome,observed:ObservedOutcome):readonly OutcomeComparison[]{if(expected.businessPackageId.value!==observed.businessPackageId.value||expected.subject.id!==observed.subject.id||expected.subject.dimension!==observed.subject.dimension)throw new PerformanceIntelligenceException("Expected and observed outcome contexts do not match","CONTEXT_MISMATCH");const comparisons=expected.metrics.map(e=>{const o=observed.metrics.find(metric=>metric.type===e.type);if(!o)return new OutcomeComparison(e.type,e.value,undefined,e.unit,undefined,undefined,ComparisonStatus.Inconclusive,MetricAvailability.Unknown,new Confidence(0),observed.evidence);if(e.unit!==o.unit)throw new PerformanceIntelligenceException(`Cannot compare incompatible units for ${e.type}`,"INCOMPATIBLE_UNITS");const confidence=new Confidence(Math.min(e.confidence?.value??expected.confidence.value,o.confidence?.value??observed.confidence.value));if(!this.comparable(e.availability)||!this.comparable(o.availability)){const unavailable=[MetricAvailability.Unavailable,MetricAvailability.NotApplicable].includes(e.availability)||[MetricAvailability.Unavailable,MetricAvailability.NotApplicable].includes(o.availability);return new OutcomeComparison(e.type,e.value,o.value,e.unit,undefined,undefined,unavailable?ComparisonStatus.Unavailable:ComparisonStatus.Inconclusive,unavailable?MetricAvailability.Unavailable:MetricAvailability.Unknown,confidence,observed.evidence);}const expectedValue=e.value as number,observedValue=o.value as number,difference=observedValue-expectedValue,relative=expectedValue===0?undefined:difference/Math.abs(expectedValue);let status:ComparisonStatus;if(expectedValue===0&&observedValue===0)status=ComparisonStatus.Neutral;else if(observedValue>expectedValue)status=ComparisonStatus.Exceeded;else if(observedValue===expectedValue)status=ComparisonStatus.Met;else if(observedValue===0&&expectedValue>0)status=ComparisonStatus.Failed;else status=ComparisonStatus.BelowExpected;return new OutcomeComparison(e.type,expectedValue,observedValue,e.unit,difference,relative,status,o.availability,confidence,observed.evidence);});return Object.freeze(comparisons);}
 evaluate(id:PerformanceRecordId,expected:ExpectedOutcome|undefined,observed:ObservedOutcome,evaluatedAt:Date):PerformanceEvaluation{const comparisons=expected?this.compare(expected,observed):Object.freeze(observed.metrics.map(metric=>new OutcomeComparison(metric.type,undefined,metric.value,metric.unit,undefined,undefined,ComparisonStatus.Inconclusive,metric.availability,new Confidence(0),observed.evidence)));const classification=this.classify(comparisons);const evaluation=new PerformanceEvaluation({id,expectedOutcomeId:expected?.id,observedOutcomeId:observed.id,comparisons,classification,evidence:observed.evidence,confidence:new Confidence(comparisons.length===0?0:Math.min(...comparisons.map(c=>c.confidence.value))),evaluatedAt,businessPackageId:observed.businessPackageId,provenance:observed.provenance});this.repository.storeEvaluation(evaluation);return evaluation;}
 history(filter:PerformanceHistoryFilter={}):PerformanceHistory{return this.repository.history(filter);}
 evaluations(filter:PerformanceHistoryFilter={}):readonly PerformanceEvaluation[]{return this.repository.evaluations(filter);}
 private comparable(value:MetricAvailability):boolean{return value===MetricAvailability.Available||value===MetricAvailability.Estimated;}
 private classify(values:readonly OutcomeComparison[]):OutcomeClassification{if(values.length===0||values.some(v=>v.status===ComparisonStatus.Inconclusive))return OutcomeClassification.Inconclusive;if(values.every(v=>v.status===ComparisonStatus.Unavailable))return OutcomeClassification.Unavailable;if(values.some(v=>v.status===ComparisonStatus.Failed))return OutcomeClassification.Failed;if(values.some(v=>v.status===ComparisonStatus.BelowExpected))return OutcomeClassification.BelowExpected;if(values.some(v=>v.status===ComparisonStatus.Exceeded))return OutcomeClassification.Exceeded;if(values.every(v=>v.status===ComparisonStatus.Neutral||v.status===ComparisonStatus.Unavailable))return OutcomeClassification.Neutral;return OutcomeClassification.Met;}
}
