import { AuditEvent } from "../../../core/platform/AuditEvent.ts";import { AuditEventType } from "../../../core/platform/AuditEventType.ts";import { AuditRecorder } from "../../../core/platform/AuditRecorder.ts";import { Event } from "../../../core/platform/Event.ts";import { EventBus } from "../../../core/platform/EventBus.ts";import { EventContext } from "../../../core/platform/EventContext.ts";import { EventId } from "../../../core/platform/EventId.ts";import { EventType } from "../../../core/platform/EventType.ts";import { OperationalTask } from "../../../core/platform/OperationalTask.ts";import { TechnicalChiefOfOperations } from "../../../core/platform/TechnicalChiefOfOperations.ts";
import { MarketIntelligenceCapability,MarketIntelligenceCapabilityMode,MarketIntelligenceCycleDefinition,MarketIntelligenceCycleRun,MarketIntelligenceCycleState,MarketIntelligenceCycleType,MarketIntelligenceOrchestrationException,MarketIntelligenceRunId,MarketIntelligenceSchedule } from "./MarketIntelligenceOrchestrationDomain.ts";import { MarketIntelligenceRunRepository } from "./MarketIntelligenceRunRepository.ts";

export interface TcoMarketIntelligenceBoundary { request(task:OperationalTask):string; }
/** The only adapter allowed to submit prepared orchestration requests to TCO. */
export class TechnicalChiefMarketIntelligenceBoundary implements TcoMarketIntelligenceBoundary {constructor(private readonly tco:TechnicalChiefOfOperations,capability="market-intelligence-workflow"){this.tco.registerCapability(capability);this.capability=capability;}private readonly capability:string;request(task:OperationalTask){task.assignCapability(this.capability);this.tco.coordinate(task);return task.taskIdentifier;}}
const transitions:Readonly<Record<MarketIntelligenceCycleState,readonly MarketIntelligenceCycleState[]>>={
 [MarketIntelligenceCycleState.Configured]:[MarketIntelligenceCycleState.Scheduled,MarketIntelligenceCycleState.OnHold,MarketIntelligenceCycleState.Cancelled],
 [MarketIntelligenceCycleState.Scheduled]:[MarketIntelligenceCycleState.Queued,MarketIntelligenceCycleState.OnHold,MarketIntelligenceCycleState.Cancelled],
 [MarketIntelligenceCycleState.Queued]:[MarketIntelligenceCycleState.Running,MarketIntelligenceCycleState.Paused,MarketIntelligenceCycleState.OnHold,MarketIntelligenceCycleState.Failed,MarketIntelligenceCycleState.Cancelled],
 [MarketIntelligenceCycleState.Running]:[MarketIntelligenceCycleState.Waiting,MarketIntelligenceCycleState.Paused,MarketIntelligenceCycleState.OnHold,MarketIntelligenceCycleState.Completed,MarketIntelligenceCycleState.Failed,MarketIntelligenceCycleState.Cancelled],
 [MarketIntelligenceCycleState.Waiting]:[MarketIntelligenceCycleState.Running,MarketIntelligenceCycleState.Paused,MarketIntelligenceCycleState.OnHold,MarketIntelligenceCycleState.Failed,MarketIntelligenceCycleState.Cancelled],
 [MarketIntelligenceCycleState.Paused]:[MarketIntelligenceCycleState.Queued,MarketIntelligenceCycleState.OnHold,MarketIntelligenceCycleState.Cancelled],
 [MarketIntelligenceCycleState.OnHold]:[MarketIntelligenceCycleState.Scheduled,MarketIntelligenceCycleState.Queued,MarketIntelligenceCycleState.Cancelled],
 [MarketIntelligenceCycleState.Completed]:[],[MarketIntelligenceCycleState.Failed]:[],[MarketIntelligenceCycleState.Cancelled]:[]};
export class MarketIntelligenceOrchestrator {readonly #states=new Map<string,MarketIntelligenceCycleState>();readonly #enabled=new Map<string,boolean>();readonly #schedules=new Map<string,MarketIntelligenceSchedule>();readonly #packageHolds=new Set<string>();readonly #typeHolds=new Set<string>();readonly #capabilityHolds=new Set<string>();#sequence=0;
 constructor(private readonly repository:MarketIntelligenceRunRepository,private readonly tco:TcoMarketIntelligenceBoundary,private readonly events:EventBus,private readonly audit:AuditRecorder){}
 create(definition:MarketIntelligenceCycleDefinition,authority:string,at=definition.createdAt){this.repository.storeDefinition(definition);this.#states.set(definition.id.value,MarketIntelligenceCycleState.Configured);this.#enabled.set(definition.id.value,definition.enabled);this.#schedules.set(definition.id.value,definition.schedule);this.report("MarketIntelligenceCycleCreated",definition.scope.businessPackageId.value,definition.id.value,authority,at,"cycle creation");}
 state(cycleId:string){return this.#states.get(cycleId);}
 currentSchedule(cycleId:string){this.required(cycleId);return this.#schedules.get(cycleId)!;}
 setEnabled(cycleId:string,enabled:boolean,authority:string,at:Date){const d=this.required(cycleId);this.#enabled.set(cycleId,enabled);this.report(enabled?"MarketIntelligenceCycleEnabled":"MarketIntelligenceCycleDisabled",d.scope.businessPackageId.value,cycleId,authority,at,enabled?"enable":"disable");}
 changeSchedule(cycleId:string,schedule:MarketIntelligenceSchedule,authority:string,at:Date){const d=this.required(cycleId);this.#schedules.set(cycleId,schedule);this.report("MarketIntelligenceCycleScheduled",d.scope.businessPackageId.value,cycleId,authority,at,"schedule change");}
 schedule(cycleId:string,authority:string,at:Date){const d=this.required(cycleId);if(this.#enabled.get(cycleId)!==true||!this.currentSchedule(cycleId).enabled)throw new MarketIntelligenceOrchestrationException("Disabled cycle cannot be scheduled");this.moveCycle(d,MarketIntelligenceCycleState.Scheduled,authority,at,"schedule change","MarketIntelligenceCycleScheduled");}
 setPackageHold(packageId:string,hold:boolean,authority:string,at:Date){hold?this.#packageHolds.add(packageId):this.#packageHolds.delete(packageId);this.report(hold?"MarketIntelligenceCycleOnHold":"MarketIntelligenceCycleResumed",packageId,packageId,authority,at,hold?"HOLD":"resume");}
 setTypeHold(packageId:string,type:MarketIntelligenceCycleType,hold:boolean,authority:string,at:Date){const key=`${packageId}:${type}`;hold?this.#typeHolds.add(key):this.#typeHolds.delete(key);this.report(hold?"MarketIntelligenceCycleOnHold":"MarketIntelligenceCycleResumed",packageId,key,authority,at,hold?"HOLD":"resume");}
 setCapabilityHold(packageId:string,capability:MarketIntelligenceCapability,hold:boolean,authority:string,at:Date){const key=`${packageId}:${capability}`;hold?this.#capabilityHolds.add(key):this.#capabilityHolds.delete(key);this.report(hold?"MarketIntelligenceCycleOnHold":"MarketIntelligenceCycleResumed",packageId,key,authority,at,hold?"HOLD":"resume");}
 requestScheduled(cycleId:string,authority:string,at:Date,runId:string,correlationId:string){const d=this.required(cycleId);const mode=d.scope.mode(d.requiredCapability);if(this.#enabled.get(cycleId)!==true||!this.currentSchedule(cycleId).enabled||mode!==MarketIntelligenceCapabilityMode.Active)throw new MarketIntelligenceOrchestrationException("Cycle is not eligible for automatic execution","NOT_AUTOMATIC");const planned=this.currentSchedule(cycleId).nextPlannedExecution;if(planned&&planned.getTime()>at.getTime())throw new MarketIntelligenceOrchestrationException("Cycle is not due","NOT_DUE");if(this.held(d))throw new MarketIntelligenceOrchestrationException("Cycle is on HOLD","ON_HOLD");return this.request(d,authority,at,runId,correlationId,false);}
 requestManual(cycleId:string,authority:string,at:Date,runId:string,correlationId:string){const d=this.required(cycleId);const run=this.request(d,authority,at,runId,correlationId,true);this.emit("MarketIntelligenceManualRunRequested",run,at);this.record("manual run",d.scope.businessPackageId.value,run.id.value,authority,at);return run;}
 transition(runId:string,next:MarketIntelligenceCycleState,authority:string,at:Date,details:{workflowInstanceReference?:string;failureReference?:string;evidenceLimitations?:readonly string[]}={}){const current=this.repository.run(runId);if(!current)throw new MarketIntelligenceOrchestrationException("Run not found","NOT_FOUND");if(!transitions[current.state].includes(next))throw new MarketIntelligenceOrchestrationException(`Invalid cycle transition: ${current.state} -> ${next}`,"INVALID_TRANSITION");if(next===MarketIntelligenceCycleState.Failed&&!details.failureReference)throw new MarketIntelligenceOrchestrationException("Failure reference is required");const run=new MarketIntelligenceCycleRun({...current.properties,...details,state:next,version:current.version+1,startedAt:next===MarketIntelligenceCycleState.Running?at:current.startedAt,completedAt:[MarketIntelligenceCycleState.Completed,MarketIntelligenceCycleState.Failed,MarketIntelligenceCycleState.Cancelled].includes(next)?at:current.completedAt});this.repository.storeRun(run);const event:Partial<Record<MarketIntelligenceCycleState,string>>={Running:"MarketIntelligenceCycleStarted",Paused:"MarketIntelligenceCyclePaused",OnHold:"MarketIntelligenceCycleOnHold",Queued:"MarketIntelligenceCycleQueued",Completed:"MarketIntelligenceCycleCompleted",Failed:"MarketIntelligenceCycleFailed"};if(event[next])this.emit(event[next]!,run,at);if([MarketIntelligenceCycleState.Paused,MarketIntelligenceCycleState.OnHold,MarketIntelligenceCycleState.Completed,MarketIntelligenceCycleState.Failed,MarketIntelligenceCycleState.Cancelled].includes(next))this.record(next===MarketIntelligenceCycleState.Failed?"failure":next.toLowerCase(),run.businessPackageId.value,run.id.value,authority,at);return run;}
 requestRetry(runId:string,authority:string,at:Date,failureReference:string){const current=this.repository.run(runId);if(!current||current.state!==MarketIntelligenceCycleState.Failed)throw new MarketIntelligenceOrchestrationException("Only a failed run can request retry");const run=new MarketIntelligenceCycleRun({...current.properties,retryCount:current.retryCount+1,failureReference,version:current.version+1});this.repository.storeRun(run);this.emit("MarketIntelligenceCycleRetryRequested",run,at);this.record("retry request",run.businessPackageId.value,run.id.value,authority,at);return run;}
 private request(d:MarketIntelligenceCycleDefinition,authority:string,at:Date,runId:string,correlationId:string,manual:boolean){if(!manual&&this.state(d.id.value)!==MarketIntelligenceCycleState.Scheduled)throw new MarketIntelligenceOrchestrationException("Cycle is not scheduled");const id=new MarketIntelligenceRunId(runId);const task=new OperationalTask(`mi:${id.value}`,"MarketIntelligenceWorkflowRequest",0,at,d.workflowReference);const taskReference=this.tco.request(task);const run=new MarketIntelligenceCycleRun({id,cycleId:d.id,businessPackageId:d.scope.businessPackageId,requestedAt:at,queuedAt:at,state:MarketIntelligenceCycleState.Queued,workflowReference:d.workflowReference,tcoTaskReference:taskReference,retryCount:0,correlationId,provenance:d.provenance,requestingAuthority:authority});this.repository.storeRun(run);this.emit("MarketIntelligenceCycleQueued",run,at);return run;}
 private held(d:MarketIntelligenceCycleDefinition){const pkg=d.scope.businessPackageId.value;return this.#packageHolds.has(pkg)||this.#typeHolds.has(`${pkg}:${d.type}`)||this.#capabilityHolds.has(`${pkg}:${d.requiredCapability}`)||d.scope.mode(d.requiredCapability)===MarketIntelligenceCapabilityMode.Hold;}
 private required(id:string){const value=this.repository.definition(id);if(!value)throw new MarketIntelligenceOrchestrationException("Cycle definition not found","NOT_FOUND");return value;}
 private moveCycle(d:MarketIntelligenceCycleDefinition,next:MarketIntelligenceCycleState,authority:string,at:Date,action:string,event:string){const current=this.state(d.id.value)!;if(!transitions[current].includes(next))throw new MarketIntelligenceOrchestrationException(`Invalid cycle transition: ${current} -> ${next}`);this.#states.set(d.id.value,next);this.report(event,d.scope.businessPackageId.value,d.id.value,authority,at,action);}
 private emit(type:string,run:MarketIntelligenceCycleRun,at:Date){this.events.publish(new Event({id:new EventId(`mi-event-${++this.#sequence}`),type:new EventType(type),timestamp:at,source:"MarketIntelligenceOrchestrator",correlationId:run.properties.correlationId,context:new EventContext({businessPackageId:run.businessPackageId.value,cycleId:run.cycleId.value,runId:run.id.value,state:run.state})}));}
 private report(type:string,pkg:string,subject:string,authority:string,at:Date,action:string){this.events.publish(new Event({id:new EventId(`mi-event-${++this.#sequence}`),type:new EventType(type),timestamp:at,source:"MarketIntelligenceOrchestrator",correlationId:subject,context:new EventContext({businessPackageId:pkg,subject})}));this.record(action,pkg,subject,authority,at);}
 private record(action:string,pkg:string,subject:string,authority:string,at:Date){this.audit.append(new AuditEvent({id:`mi-audit-${++this.#sequence}`,timestamp:at,type:AuditEventType.WorkflowEvent,source:"MarketIntelligenceOrchestrator",action,result:"recorded",responsibleIdentity:authority,relatedTaskOrWorkflowId:subject,context:{businessPackageId:pkg,subject}}));}
}
