import { BusinessPackageId, Provenance } from "../MarketIntelligenceDomain.ts";

export class MarketIntelligenceOrchestrationException extends Error {
  constructor(message: string, readonly code = "INVALID_ORCHESTRATION") { super(message); this.name = "MarketIntelligenceOrchestrationException"; }
}
function text(value: string, field: string): string { if (typeof value !== "string" || value.trim() === "") throw new MarketIntelligenceOrchestrationException(`${field} is required`); return value; }
function instant(value: Date, field: string): number { const result=value?.getTime(); if(!Number.isFinite(result))throw new MarketIntelligenceOrchestrationException(`${field} is invalid`);return result; }

export class MarketIntelligenceCycleId { readonly #value:string; constructor(value:string){this.#value=text(value,"Cycle identifier");Object.freeze(this);}get value(){return this.#value;} equals(other:MarketIntelligenceCycleId){return other instanceof MarketIntelligenceCycleId&&other.value===this.value;} }
export class MarketIntelligenceRunId { readonly #value:string; constructor(value:string){this.#value=text(value,"Run identifier");Object.freeze(this);}get value(){return this.#value;} }
export enum MarketIntelligenceCycleType { MarketObservation="MarketObservation",CompetitiveReview="CompetitiveReview",PatternEvaluation="PatternEvaluation",PerformanceReview="PerformanceReview",OpportunityReview="OpportunityReview",RecommendationReview="RecommendationReview",LearningReview="LearningReview",FullMarketIntelligenceCycle="FullMarketIntelligenceCycle" }
export enum MarketIntelligenceCycleState { Configured="Configured",Scheduled="Scheduled",Queued="Queued",Running="Running",Waiting="Waiting",Paused="Paused",OnHold="OnHold",Completed="Completed",Failed="Failed",Cancelled="Cancelled" }
export enum MarketIntelligenceCapability { MarketObservation="MarketObservation",CompetitiveIntelligence="CompetitiveIntelligence",PatternIntelligence="PatternIntelligence",PerformanceIntelligence="PerformanceIntelligence",OpportunityIntelligence="OpportunityIntelligence",RecommendationEngine="RecommendationEngine",ContinuousLearning="ContinuousLearning" }
export enum MarketIntelligenceCapabilityMode { Active="ACTIVE",Hold="HOLD",ManualOnly="MANUAL_ONLY" }
export class MarketIntelligenceScope { readonly capabilities:ReadonlyMap<MarketIntelligenceCapability,MarketIntelligenceCapabilityMode>; constructor(readonly businessPackageId:BusinessPackageId, capabilities:ReadonlyMap<MarketIntelligenceCapability,MarketIntelligenceCapabilityMode>){if(!(businessPackageId instanceof BusinessPackageId)||capabilities.size===0)throw new MarketIntelligenceOrchestrationException("Scope requires a Business Package and capability");this.capabilities=new Map(capabilities);Object.freeze(this);} mode(capability:MarketIntelligenceCapability){return this.capabilities.get(capability);} }
export class MarketIntelligenceSchedule { static readonly DEFAULT_INTERVAL_DAYS=30; readonly #next?:number;readonly #last?:number; constructor(readonly intervalDays=MarketIntelligenceSchedule.DEFAULT_INTERVAL_DAYS,nextPlannedExecution?:Date,lastExecution?:Date,readonly enabled=true){if(!Number.isInteger(intervalDays)||intervalDays<1)throw new MarketIntelligenceOrchestrationException("Schedule interval must be a positive whole number");this.#next=nextPlannedExecution===undefined?undefined:instant(nextPlannedExecution,"Next execution");this.#last=lastExecution===undefined?undefined:instant(lastExecution,"Last execution");Object.freeze(this);}get nextPlannedExecution(){return this.#next===undefined?undefined:new Date(this.#next);}get lastExecution(){return this.#last===undefined?undefined:new Date(this.#last);} afterExecution(at:Date){const time=instant(at,"Execution timestamp");return new MarketIntelligenceSchedule(this.intervalDays,new Date(time+this.intervalDays*86_400_000),new Date(time),this.enabled);} }
export interface CycleDefinitionProperties { id:MarketIntelligenceCycleId;name:string;type:MarketIntelligenceCycleType;scope:MarketIntelligenceScope;enabled:boolean;schedule:MarketIntelligenceSchedule;workflowReference:string;requiredCapability:MarketIntelligenceCapability;createdAt:Date;provenance:Provenance; }
export class MarketIntelligenceCycleDefinition { readonly #created:number; constructor(readonly properties:CycleDefinitionProperties){if(!(properties.id instanceof MarketIntelligenceCycleId)||!(properties.scope instanceof MarketIntelligenceScope)||!(properties.schedule instanceof MarketIntelligenceSchedule)||!(properties.provenance instanceof Provenance))throw new MarketIntelligenceOrchestrationException("Cycle definition dependencies are invalid");text(properties.name,"Cycle name");text(properties.workflowReference,"Approved workflow reference");if(properties.scope.mode(properties.requiredCapability)===undefined)throw new MarketIntelligenceOrchestrationException("Required capability must be in cycle scope");this.#created=instant(properties.createdAt,"Creation timestamp");Object.freeze(properties);Object.freeze(this);}get id(){return this.properties.id;}get name(){return this.properties.name;}get type(){return this.properties.type;}get scope(){return this.properties.scope;}get enabled(){return this.properties.enabled;}get schedule(){return this.properties.schedule;}get workflowReference(){return this.properties.workflowReference;}get requiredCapability(){return this.properties.requiredCapability;}get createdAt(){return new Date(this.#created);}get provenance(){return this.properties.provenance;} }
export interface CycleRunProperties { id:MarketIntelligenceRunId;cycleId:MarketIntelligenceCycleId;businessPackageId:BusinessPackageId;requestedAt:Date;queuedAt?:Date;startedAt?:Date;completedAt?:Date;state:MarketIntelligenceCycleState;workflowReference:string;workflowInstanceReference?:string;tcoTaskReference?:string;retryCount:number;failureReference?:string;correlationId:string;provenance:Provenance;requestingAuthority:string;version?:number;evidenceLimitations?:readonly string[]; }
export class MarketIntelligenceCycleRun { readonly #requested:number;readonly #queued?:number;readonly #started?:number;readonly #completed?:number;readonly evidenceLimitations:readonly string[]; constructor(readonly properties:CycleRunProperties){if(!(properties.id instanceof MarketIntelligenceRunId)||!(properties.cycleId instanceof MarketIntelligenceCycleId)||!(properties.businessPackageId instanceof BusinessPackageId)||!(properties.provenance instanceof Provenance))throw new MarketIntelligenceOrchestrationException("Run context is invalid");this.#requested=instant(properties.requestedAt,"Requested timestamp");this.#queued=properties.queuedAt&&instant(properties.queuedAt,"Queued timestamp");this.#started=properties.startedAt&&instant(properties.startedAt,"Started timestamp");this.#completed=properties.completedAt&&instant(properties.completedAt,"Completion timestamp");text(properties.workflowReference,"Workflow reference");text(properties.correlationId,"Correlation identifier");text(properties.requestingAuthority,"Requesting authority");if(!Number.isInteger(properties.retryCount)||properties.retryCount<0)throw new MarketIntelligenceOrchestrationException("Retry count is invalid");this.evidenceLimitations=Object.freeze([...(properties.evidenceLimitations??[])]);Object.freeze(properties);Object.freeze(this);}get id(){return this.properties.id;}get state(){return this.properties.state;}get cycleId(){return this.properties.cycleId;}get businessPackageId(){return this.properties.businessPackageId;}get requestedAt(){return new Date(this.#requested);}get queuedAt(){return this.#queued===undefined?undefined:new Date(this.#queued);}get startedAt(){return this.#started===undefined?undefined:new Date(this.#started);}get completedAt(){return this.#completed===undefined?undefined:new Date(this.#completed);}get retryCount(){return this.properties.retryCount;}get version(){return this.properties.version??1;} }
export const FULL_MARKET_INTELLIGENCE_SEQUENCE=Object.freeze([MarketIntelligenceCapability.MarketObservation,MarketIntelligenceCapability.CompetitiveIntelligence,MarketIntelligenceCapability.PatternIntelligence,MarketIntelligenceCapability.PerformanceIntelligence,MarketIntelligenceCapability.OpportunityIntelligence,MarketIntelligenceCapability.RecommendationEngine,MarketIntelligenceCapability.ContinuousLearning]);
