import type {BusinessPackageId,Provenance} from "../../../../intelligence/market/MarketIntelligenceDomain.ts";
import type {BlogDraftBookLink,BlogDraftCTA,BlogDraftInternalLink} from "../writing/BlogWriterDomain.ts";

const required=(value:string,name:string)=>{if(!value?.trim())throw new BlogPublicationPackagingException(`${name} is required`,"INVALID_REQUEST");return value;};
const frozen=<T>(values:readonly T[])=>Object.freeze([...values]);
export class BlogPublicationPackagingException extends Error{constructor(message:string,readonly code="PUBLICATION_PACKAGING_FAILURE"){super(message);this.name="BlogPublicationPackagingException";}}
export class BlogPublicationPackageId{constructor(readonly value:string){required(value,"Publication Package identifier");Object.freeze(this);}}
export class BlogPublicationPackageVersion{constructor(readonly value:number){if(!Number.isInteger(value)||value<1)throw new BlogPublicationPackagingException("Publication Package version is invalid","INVALID_VERSION");Object.freeze(this);}}
export enum BlogPublicationPackageState{Preparing="Preparing",ValidationRequired="ValidationRequired",ValidationFailed="ValidationFailed",ReevaluationRequired="ReevaluationRequired",ReadyForWordPressPublishing="ReadyForWordPressPublishing",Superseded="Superseded",Cancelled="Cancelled",Failed="Failed"}
export enum BlogPublicationIssueType{DraftVersionMismatch="DraftVersionMismatch",ApprovalMismatch="ApprovalMismatch",H1Mismatch="H1Mismatch",HeadingHierarchyInvalid="HeadingHierarchyInvalid",LanguageMismatch="LanguageMismatch",BookLinkInvalid="BookLinkInvalid",InternalLinkInvalid="InternalLinkInvalid",MetadataMismatch="MetadataMismatch",SlugInvalid="SlugInvalid",CanonicalURLInvalid="CanonicalURLInvalid",SearchDiscoveryViolation="SearchDiscoveryViolation",AIDiscoveryViolation="AIDiscoveryViolation",FactualValidationFailure="FactualValidationFailure",StructuredDataInvalid="StructuredDataInvalid",DuplicateContentConcern="DuplicateContentConcern",StaleOpportunity="StaleOpportunity",MaterialContentChange="MaterialContentChange",BusinessPackageMismatch="BusinessPackageMismatch",Other="Other"}
export enum BlogPublicationIssueSeverity{Info="Info",Warning="Warning",Blocking="Blocking",ReevaluationRequired="ReevaluationRequired"}
export enum BlogValidationStatus{Pass="PASS",Warn="WARN",Fail="FAIL"}
export enum BlogLinkState{ValidReference="ValidReference",Unverified="Unverified",Missing="Missing",Invalid="Invalid",Stale="Stale",Unknown="Unknown"}
export class BlogPublicationValidationIssue{constructor(readonly type:BlogPublicationIssueType,readonly severity:BlogPublicationIssueSeverity,readonly message:string,readonly factor:string){required(message,"Validation issue message");required(factor,"Validation factor");Object.freeze(this);}}
export class BlogPublicationValidationResult{readonly issues;constructor(issues:readonly BlogPublicationValidationIssue[]){this.issues=frozen(issues);Object.freeze(this);}get status(){return this.issues.some(x=>x.severity===BlogPublicationIssueSeverity.Blocking||x.severity===BlogPublicationIssueSeverity.ReevaluationRequired)?BlogValidationStatus.Fail:this.issues.some(x=>x.severity===BlogPublicationIssueSeverity.Warning)?BlogValidationStatus.Warn:BlogValidationStatus.Pass;}get blocking(){return this.status===BlogValidationStatus.Fail;}}
export interface BlogPublicationPackageRequestProperties{id:BlogPublicationPackageId;version:BlogPublicationPackageVersion;draftId:string;draftVersion:number;reviewId:string;approvalDecisionId:string;businessPackageId:BusinessPackageId;correlationIdentifier:string;requestedAt:Date;}
export class BlogPublicationPackageRequest{constructor(readonly properties:BlogPublicationPackageRequestProperties){for(const [v,n] of [[properties.draftId,"Draft identifier"],[properties.reviewId,"Review identifier"],[properties.approvalDecisionId,"Approval decision identifier"],[properties.correlationIdentifier,"Correlation identifier"]] as const)required(v,n);if(!Number.isInteger(properties.draftVersion)||properties.draftVersion<1||!Number.isFinite(properties.requestedAt.getTime()))throw new BlogPublicationPackagingException("Draft version or request timestamp is invalid","INVALID_REQUEST");Object.freeze(this);}}
export interface BlogPublicationSitePolicy{businessPackageId:BusinessPackageId;siteBaseUrl:string;languagePath?:string;authorReference?:string;metaTitleMustEqualH1?:boolean;citationsRequired?:boolean;primaryBookCTARequired?:boolean;structuredDataTypes?:readonly ("Article"|"BlogPosting"|"FAQPage"|"BreadcrumbList")[];minimumPinsPerPublishedBlog?:number;}
export class BlogRenderedArticle{readonly headingLineage;constructor(readonly format:"html",readonly body:string,readonly visibleTextFingerprint:string,headingLineage:readonly {headingId:string;level:"H1"|"H2"|"H3";text:string}[]){this.headingLineage=frozen(headingLineage);Object.freeze(this);}}
export class BlogMetadataPackage{constructor(readonly metaTitle:string,readonly metaDescription:string,readonly language:string){Object.freeze(this);}}
export class BlogSlugProposal{constructor(readonly value:string,readonly initialProposal=true){Object.freeze(this);}}
export class BlogCanonicalURLContext{constructor(readonly siteBaseUrl:string,readonly languagePath:string|undefined,readonly preview:string){Object.freeze(this);}}
export class BlogStructuredDataPackage{readonly objects;constructor(objects:readonly Readonly<Record<string,unknown>>[]){this.objects=frozen(objects);Object.freeze(this);}}
export class BlogSearchDiscoveryValidation{readonly factors;constructor(readonly status:BlogValidationStatus,factors:readonly {name:string;status:BlogValidationStatus;explanation:string}[]){this.factors=frozen(factors);Object.freeze(this);}}
export class BlogAIDiscoveryValidation{readonly factors;constructor(readonly status:BlogValidationStatus,factors:readonly {name:string;status:BlogValidationStatus;explanation:string}[]){this.factors=frozen(factors);Object.freeze(this);}}
export interface BlogPublicationLineage{planId:string;planVersion:number;recommendationId:string;recommendationVersion:number;ceoRecommendationDecisionReference:string;blogDraftApprovalReference:string;canonicalQuestionId:string;canonicalQuestionText:string;knowledgeReferences:readonly string[];libraryReferences:readonly string[];}
export class BlogPublicationPackage{readonly bookLinks;readonly internalLinks;readonly sourceReferences;readonly warnings;constructor(readonly id:BlogPublicationPackageId,readonly version:BlogPublicationPackageVersion,readonly state:BlogPublicationPackageState,readonly businessPackageId:BusinessPackageId,readonly draftId:string,readonly draftVersion:number,readonly exactH1:string,readonly renderedArticle:BlogRenderedArticle,readonly language:string,readonly market:string,readonly authorReference:string|undefined,readonly publicationStatusTarget:"Draft",readonly metadata:BlogMetadataPackage,readonly slug:BlogSlugProposal,readonly canonicalURL:BlogCanonicalURLContext,readonly structuredData:BlogStructuredDataPackage,bookLinks:readonly BlogDraftBookLink[],internalLinks:readonly BlogDraftInternalLink[],readonly primaryBookCTA:BlogDraftCTA|undefined,sourceReferences:readonly string[],readonly searchDiscovery:BlogSearchDiscoveryValidation,readonly aiDiscovery:BlogAIDiscoveryValidation,readonly factualStatus:BlogValidationStatus,readonly styleStatus:BlogValidationStatus,readonly validation:BlogPublicationValidationResult,readonly lineage:BlogPublicationLineage,readonly pinterestPromotionLineage:{articleReference:string;headings:readonly {headingId:string;level:"H1"|"H2"|"H3";text:string}[];minimumPinsPerPublishedBlog:number;videoCompatible:boolean},readonly correlationIdentifier:string,readonly provenance:Provenance,readonly createdAt:Date){this.bookLinks=frozen(bookLinks);this.internalLinks=frozen(internalLinks);this.sourceReferences=frozen(sourceReferences);this.warnings=frozen(validation.issues.filter(x=>x.severity===BlogPublicationIssueSeverity.Warning));Object.freeze(this);}}
export const BLOG_PUBLICATION_EVENTS=Object.freeze(["BlogPublicationPackageRequested","BlogPublicationPackageStarted","BlogPublicationPackageRendered","BlogSearchDiscoveryValidationStarted","BlogSearchDiscoveryValidationCompleted","BlogAIDiscoveryValidationStarted","BlogAIDiscoveryValidationCompleted","BlogPublicationPackageValidationFailed","BlogPublicationPackageReevaluationRequired","BlogPublicationPackageReady","BlogPublicationPackageFailed"] as const);
