import {AuditEvent} from "../../../../core/platform/AuditEvent.ts";import {AuditEventType} from "../../../../core/platform/AuditEventType.ts";import type {AuditRecorder} from "../../../../core/platform/AuditRecorder.ts";import {Event} from "../../../../core/platform/Event.ts";import type {EventBus} from "../../../../core/platform/EventBus.ts";import {EventContext} from "../../../../core/platform/EventContext.ts";import {EventId} from "../../../../core/platform/EventId.ts";import {EventType} from "../../../../core/platform/EventType.ts";import {MarketSourceId,Provenance} from "../../../../intelligence/market/MarketIntelligenceDomain.ts";
import type {BlogContentCreationPlan} from "../planning/BlogContentCreationPlanDomain.ts";import {BlogHeadingLevel} from "../planning/BlogContentCreationPlanDomain.ts";import {BlogDraftDecisionType,BlogDraftReviewId} from "../review/BlogDraftReviewDomain.ts";import {BlogDraftDecisionRepository} from "../review/BlogDraftDecisionRepository.ts";import {BlogDraftReviewRepository} from "../review/BlogDraftReviewRepository.ts";import {BlogDraftId,BlogDraftPublicationMode,BlogDraftState,BlogValidationSeverity} from "../writing/BlogWriterDomain.ts";import type {BlogDraft,BlogDraftContent} from "../writing/BlogWriterDomain.ts";import {BlogDraftRepository} from "../writing/BlogDraftRepository.ts";
import {BlogAIDiscoveryValidation,BlogCanonicalURLContext,BlogMetadataPackage,BlogPublicationIssueSeverity,BlogPublicationIssueType,BlogPublicationPackage,BlogPublicationPackagingException,BlogPublicationPackageState,BlogPublicationValidationIssue,BlogPublicationValidationResult,BlogRenderedArticle,BlogSearchDiscoveryValidation,BlogSlugProposal,BlogStructuredDataPackage,BlogValidationStatus} from "./BlogPublicationDomain.ts";import type {BlogPublicationPackageRequest,BlogPublicationSitePolicy} from "./BlogPublicationDomain.ts";import {BlogPublicationPackageRepository} from "./BlogPublicationPackageRepository.ts";

const escape=(v:string)=>v.replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;");
const fingerprint=(c:BlogDraftContent)=>JSON.stringify({h1:c.h1,headings:c.headings.map(x=>[x.id,x.text,x.level,x.parentHeadingId]),paragraphs:c.paragraphs.map(x=>[x.id,x.text]),books:c.bookLinks.map(x=>[x.bookId,x.editionId,x.title,x.url,x.paragraphId]),links:c.internalLinks.map(x=>[x.contentReference,x.url,x.paragraphId]),cta:c.cta&&[c.cta.bookId,c.cta.editionId,c.cta.title,c.cta.url,c.cta.text]});
export interface BlogPublicationPackagingInput{metaTitle?:string;metaDescription:string;duplicateIntentDetected?:boolean;staleIntelligence?:boolean;materialContentFingerprint?:string;factualGroundingPassed?:boolean;citationReadinessPassed?:boolean;humanFirstPassed?:boolean;aiStyleRhythmWarning?:boolean;}
export class BlogPublicationPackagingService{
 readonly #events:string[]=[];
 constructor(readonly drafts:BlogDraftRepository,readonly reviews:BlogDraftReviewRepository,readonly decisions:BlogDraftDecisionRepository,readonly packages:BlogPublicationPackageRepository,private readonly eventBus?:EventBus,private readonly audit?:AuditRecorder,private readonly clock=()=>new Date()){}
 package(request:BlogPublicationPackageRequest,plan:BlogContentCreationPlan,policy:BlogPublicationSitePolicy,input:BlogPublicationPackagingInput){this.emit("BlogPublicationPackageRequested",request);this.emit("BlogPublicationPackageStarted",request);this.record("packaging-request",request);const issues:BlogPublicationValidationIssue[]=[];const add=(type:BlogPublicationIssueType,severity:BlogPublicationIssueSeverity,message:string,factor:string)=>issues.push(new BlogPublicationValidationIssue(type,severity,message,factor));
  const draft=this.drafts.get(new BlogDraftId(request.properties.draftId),request.properties.draftVersion),current=this.drafts.get(new BlogDraftId(request.properties.draftId));if(!draft)throw this.failure(request,"Exact Draft version was not found","DRAFT_NOT_FOUND");if(current!==draft)add(BlogPublicationIssueType.DraftVersionMismatch,BlogPublicationIssueSeverity.Blocking,"Requested Draft is not the current exact version","exact Draft version");
  const reviewId=new BlogDraftReviewId(request.properties.reviewId),packet=this.reviews.packet(reviewId),decision=this.decisions.history(reviewId).find(x=>x.decisionId===request.properties.approvalDecisionId);if(!packet||packet.draft!==draft||!decision||decision.decisionType!==BlogDraftDecisionType.Approve||decision.draftVersion!==draft.version.value)add(BlogPublicationIssueType.ApprovalMismatch,BlogPublicationIssueSeverity.Blocking,"Explicit CEO approval does not bind the exact Draft version","CEO approval binding");
  const latestDecision=this.decisions.latest(reviewId);if(latestDecision?.decisionId!==request.properties.approvalDecisionId||latestDecision?.decisionType!==BlogDraftDecisionType.Approve)add(BlogPublicationIssueType.ApprovalMismatch,BlogPublicationIssueSeverity.Blocking,"CEO approval is no longer the current decision","current approval");
  if(draft.state!==BlogDraftState.ReadyForCEOReview||draft.publicationMode!==BlogDraftPublicationMode.CEOApprovalRequired)add(BlogPublicationIssueType.ApprovalMismatch,BlogPublicationIssueSeverity.Blocking,"Draft is not eligible under CEOApprovalRequired policy","publication authority");
  if(draft.businessPackageId.value!==request.properties.businessPackageId.value||policy.businessPackageId.value!==draft.businessPackageId.value||plan.businessPackageId.value!==draft.businessPackageId.value)add(BlogPublicationIssueType.BusinessPackageMismatch,BlogPublicationIssueSeverity.Blocking,"Business Package isolation failed","Business Package");
  if(plan.id.value!==draft.planId||plan.version!==draft.planVersion||plan.recommendationId!==draft.recommendationId||plan.recommendationVersion!==draft.recommendationVersion)add(BlogPublicationIssueType.DraftVersionMismatch,BlogPublicationIssueSeverity.Blocking,"Exact Plan and Recommendation versions do not match","version lineage");
  if(draft.content.h1!==plan.canonicalQuestionText||draft.content.h1!==plan.plannedH1)add(BlogPublicationIssueType.H1Mismatch,BlogPublicationIssueSeverity.Blocking,"H1 must exactly equal the approved Canonical Question","H1 equality");
  if(draft.language!==plan.language)add(BlogPublicationIssueType.LanguageMismatch,BlogPublicationIssueSeverity.Blocking,"Publication language does not match the Plan","language consistency");
  const h2=new Set<string>();for(const heading of draft.content.headings){if(heading.level===BlogHeadingLevel.H2)h2.add(heading.id);if(heading.level===BlogHeadingLevel.H1||heading.level===BlogHeadingLevel.H3&&(!heading.parentHeadingId||!h2.has(heading.parentHeadingId)))add(BlogPublicationIssueType.HeadingHierarchyInvalid,BlogPublicationIssueSeverity.Blocking,"Article must have one protected H1 and correctly nested H2/H3 headings","heading hierarchy");}
  for(const link of draft.content.bookLinks){const approved=plan.bookPlacementPlan.placements.find(x=>x.bookId===link.bookId&&x.editionId===link.editionId&&x.publishedTitle===link.title&&x.verifiedDirectUrl===link.url&&x.targetLanguage===draft.language);if(!approved)add(BlogPublicationIssueType.BookLinkInvalid,BlogPublicationIssueSeverity.Blocking,"Book link is not the exact approved Library edition reference","Book link");}
  const ctaPlan=plan.primaryBookCTAPlan,cta=draft.content.cta;if((policy.primaryBookCTARequired||ctaPlan.state==="Planned")&&(!cta||cta.bookId!==ctaPlan.bookId||cta.editionId!==ctaPlan.editionId||cta.url!==ctaPlan.verifiedDirectUrl))add(BlogPublicationIssueType.BookLinkInvalid,BlogPublicationIssueSeverity.Blocking,"Primary Book CTA must use the exact approved direct link","Primary Book CTA");
  for(const link of draft.content.internalLinks)if(!plan.internalLinks.some(x=>x.contentReference===link.contentReference&&x.approvedUrl===link.url))add(BlogPublicationIssueType.InternalLinkInvalid,BlogPublicationIssueSeverity.Blocking,"Internal link is unresolved or not approved","internal link");
  if(input.materialContentFingerprint&&input.materialContentFingerprint!==fingerprint(draft.content))add(BlogPublicationIssueType.MaterialContentChange,BlogPublicationIssueSeverity.Blocking,"Rendered visible content diverges from the CEO-reviewed Draft","content preservation");
  if(input.duplicateIntentDetected)add(BlogPublicationIssueType.DuplicateContentConcern,BlogPublicationIssueSeverity.ReevaluationRequired,"Another current article owns the authoritative intent","duplicate intent");if(input.staleIntelligence)add(BlogPublicationIssueType.StaleOpportunity,BlogPublicationIssueSeverity.ReevaluationRequired,"Opportunity or Plan intelligence is materially stale","freshness");
  const rendered=this.render(draft);this.emit("BlogPublicationPackageRendered",request);const title=input.metaTitle??draft.content.h1;if(policy.metaTitleMustEqualH1&&title!==draft.content.h1)add(BlogPublicationIssueType.MetadataMismatch,BlogPublicationIssueSeverity.Blocking,"Meta title policy requires exact H1","meta title");if(!input.metaDescription.trim()||!draft.content.paragraphs.some(x=>input.metaDescription.toLocaleLowerCase(draft.language).split(/\s+/).filter(w=>w.length>4).some(w=>x.text.toLocaleLowerCase(draft.language).includes(w))))add(BlogPublicationIssueType.MetadataMismatch,BlogPublicationIssueSeverity.Blocking,"Meta description is not aligned with visible article content","metadata alignment");
  const slug=this.slug(draft.content.h1);if(!slug)add(BlogPublicationIssueType.SlugInvalid,BlogPublicationIssueSeverity.Blocking,"Slug proposal is invalid","slug policy");let base:string;try{base=new URL(policy.siteBaseUrl).toString().replace(/\/$/,"");}catch{base="";add(BlogPublicationIssueType.CanonicalURLInvalid,BlogPublicationIssueSeverity.Blocking,"Configured canonical site base is invalid","canonical URL");}const path=[policy.languagePath?.replace(/^\/+|\/+$/g,""),slug].filter(Boolean).join("/");const canonical=base?`${base}/${path}`:"";
  const early=draft.content.paragraphs[0]?.text.trim().length>20;this.emit("BlogSearchDiscoveryValidationStarted",request);if(!early)add(BlogPublicationIssueType.SearchDiscoveryViolation,BlogPublicationIssueSeverity.Blocking,"Article does not provide a meaningful answer near the beginning","direct answer");const words=draft.content.paragraphs.flatMap(x=>x.text.toLocaleLowerCase(draft.language).match(/[\p{L}]+/gu)??[]),counts=new Map<string,number>();for(const w of words)if(w.length>4)counts.set(w,(counts.get(w)??0)+1);if(words.length>20&&[...counts.values()].some(n=>n/words.length>.18))add(BlogPublicationIssueType.SearchDiscoveryViolation,BlogPublicationIssueSeverity.Warning,"Term repetition may reduce human readability","natural terminology");this.emit("BlogSearchDiscoveryValidationCompleted",request);
  this.emit("BlogAIDiscoveryValidationStarted",request);if(input.factualGroundingPassed===false||!draft.sourceUsage.length)add(BlogPublicationIssueType.FactualValidationFailure,BlogPublicationIssueSeverity.Blocking,"Factual claims lack approved source lineage","factual grounding");if((policy.citationsRequired||plan.sourceRequirements.some(x=>x.citationRequired))&&input.citationReadinessPassed!==true)add(BlogPublicationIssueType.AIDiscoveryViolation,BlogPublicationIssueSeverity.Blocking,"Required reader-visible citations are not ready","citation readiness");if(input.humanFirstPassed===false)add(BlogPublicationIssueType.AIDiscoveryViolation,BlogPublicationIssueSeverity.Blocking,"Article does not pass the human-first reading check","human-first");if(input.aiStyleRhythmWarning)add(BlogPublicationIssueType.AIDiscoveryViolation,BlogPublicationIssueSeverity.Warning,"Repetitive machine-oriented rhythm requires human review","natural rhythm");this.emit("BlogAIDiscoveryValidationCompleted",request);
  const status=(subset:readonly BlogPublicationValidationIssue[])=>subset.some(x=>x.severity===BlogPublicationIssueSeverity.Blocking||x.severity===BlogPublicationIssueSeverity.ReevaluationRequired)?BlogValidationStatus.Fail:subset.some(x=>x.severity===BlogPublicationIssueSeverity.Warning)?BlogValidationStatus.Warn:BlogValidationStatus.Pass,searchIssues=issues.filter(x=>x.type===BlogPublicationIssueType.SearchDiscoveryViolation||[BlogPublicationIssueType.H1Mismatch,BlogPublicationIssueType.MetadataMismatch,BlogPublicationIssueType.SlugInvalid,BlogPublicationIssueType.CanonicalURLInvalid].includes(x.type)),aiIssues=issues.filter(x=>x.type===BlogPublicationIssueType.AIDiscoveryViolation||x.type===BlogPublicationIssueType.FactualValidationFailure);
  const search=new BlogSearchDiscoveryValidation(status(searchIssues),[{name:"question and direct answer",status:early?BlogValidationStatus.Pass:BlogValidationStatus.Fail,explanation:"The exact question is protected and the opening provides the answer."},{name:"metadata and canonical policy",status:status(searchIssues),explanation:"Metadata, slug, canonical context, language, structure, and approved links were checked separately."}]);const ai=new BlogAIDiscoveryValidation(status(aiIssues),[{name:"extractable grounded answer",status:status(aiIssues),explanation:"Clear concepts, source lineage, citation readiness, qualifications, and human readability were checked without provider assumptions."}]);
  const schemaTypes=policy.structuredDataTypes??["Article"];const objects:Readonly<Record<string,unknown>>[]=[];for(const type of schemaTypes){if(type==="FAQPage"){if(plan.relatedQuestions.length&&plan.relatedQuestions.every(q=>draft.content.headings.some(h=>h.text===q)))objects.push(Object.freeze({"@type":"FAQPage",questions:Object.freeze([...plan.relatedQuestions])}));}else if(type==="Article"||type==="BlogPosting")objects.push(Object.freeze({"@type":type,headline:draft.content.h1,inLanguage:draft.language,url:canonical,...(policy.authorReference?{author:policy.authorReference}:{})}));}
  const validation=new BlogPublicationValidationResult(issues),state=issues.some(x=>x.severity===BlogPublicationIssueSeverity.ReevaluationRequired)?BlogPublicationPackageState.ReevaluationRequired:validation.blocking?BlogPublicationPackageState.ValidationFailed:BlogPublicationPackageState.ReadyForWordPressPublishing;const headings=rendered.headingLineage;const result=new BlogPublicationPackage(request.properties.id,request.properties.version,state,draft.businessPackageId,draft.id.value,draft.version.value,draft.content.h1,rendered,draft.language,draft.market,policy.authorReference,"Draft",new BlogMetadataPackage(title,input.metaDescription,draft.language),new BlogSlugProposal(slug),new BlogCanonicalURLContext(base,policy.languagePath,canonical),new BlogStructuredDataPackage(objects),draft.content.bookLinks,draft.content.internalLinks,draft.content.cta,draft.sourceUsage.map(x=>x.reference),search,ai,input.factualGroundingPassed===false?BlogValidationStatus.Fail:BlogValidationStatus.Pass,draft.validation.issues.some(x=>x.severity===BlogValidationSeverity.Warning)?BlogValidationStatus.Warn:BlogValidationStatus.Pass,validation,Object.freeze({planId:draft.planId,planVersion:draft.planVersion,recommendationId:draft.recommendationId,recommendationVersion:draft.recommendationVersion,ceoRecommendationDecisionReference:plan.ceoApprovalReference,blogDraftApprovalReference:request.properties.approvalDecisionId,canonicalQuestionId:plan.canonicalQuestionId,canonicalQuestionText:plan.canonicalQuestionText,knowledgeReferences:Object.freeze(draft.knowledgeUsage.map(x=>x.reference)),libraryReferences:Object.freeze(draft.content.bookLinks.map(x=>`${x.bookId}:${x.editionId}`))}),Object.freeze({articleReference:`publication-package:${request.properties.id.value}`,headings,minimumPinsPerPublishedBlog:Math.max(3,policy.minimumPinsPerPublishedBlog??3),videoCompatible:true}),request.properties.correlationIdentifier,new Provenance("CEO-approved Blog publication packaging",this.clock(),new MarketSourceId("blog-publication-packaging"),[draft.id.value,request.properties.approvalDecisionId]),this.clock());this.packages.save(result);this.emit(state===BlogPublicationPackageState.ReadyForWordPressPublishing?"BlogPublicationPackageReady":state===BlogPublicationPackageState.ReevaluationRequired?"BlogPublicationPackageReevaluationRequired":"BlogPublicationPackageValidationFailed",request);this.record(state,request);return result;
 }
 eventNames(){return Object.freeze([...this.#events]);}
 private render(draft:BlogDraft){const headings=[{headingId:"h1",level:"H1" as const,text:draft.content.h1},...draft.content.headings.map(x=>({headingId:x.id,level:x.level,text:x.text}))];let body=`<h1>${escape(draft.content.h1)}</h1>`;for(const heading of draft.content.headings)body+=`<${heading.level.toLowerCase()} id="${escape(heading.id)}">${escape(heading.text)}</${heading.level.toLowerCase()}>`;for(const p of draft.content.paragraphs)body+=`<p id="${escape(p.id)}">${escape(p.text)}</p>`;if(draft.content.cta)body+=`<p><a href="${escape(draft.content.cta.url)}">${escape(draft.content.cta.text)}</a></p>`;return new BlogRenderedArticle("html",body,fingerprint(draft.content),headings);}
 private slug(value:string){return value.normalize("NFKD").replace(/[\u0300-\u036f]/g,"").toLocaleLowerCase("de").replace(/ß/g,"ss").replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");}
 private emit(name:string,r:BlogPublicationPackageRequest){this.#events.push(name);this.eventBus?.publish(new Event({id:new EventId(`${r.properties.id.value}:${name}:${this.#events.length}`),type:new EventType(name),timestamp:this.clock(),source:"BlogPublicationPackagingService",correlationId:r.properties.correlationIdentifier,context:new EventContext({packageId:r.properties.id.value,draftId:r.properties.draftId,draftVersion:r.properties.draftVersion,businessPackageId:r.properties.businessPackageId.value})}));}
 private record(action:string,r:BlogPublicationPackageRequest){this.audit?.append(new AuditEvent({id:`${r.properties.id.value}:${action}:${this.audit.getEvents().length}`,timestamp:this.clock(),type:AuditEventType.WorkflowEvent,source:"BlogPublicationPackagingService",action,result:"recorded",responsibleIdentity:"TCO",relatedTaskOrWorkflowId:r.properties.correlationIdentifier,context:{packageId:r.properties.id.value,draftId:r.properties.draftId,draftVersion:r.properties.draftVersion,approvalDecisionId:r.properties.approvalDecisionId,businessPackageId:r.properties.businessPackageId.value}}));}
 private failure(r:BlogPublicationPackageRequest,message:string,code:string){this.emit("BlogPublicationPackageFailed",r);this.record("Failed",r);return new BlogPublicationPackagingException(message,code);}
}
