import { createHash, randomUUID } from "node:crypto";
import { chmod, copyFile, mkdir, open, readFile, readdir, rename, rm, stat } from "node:fs/promises";
import { dirname, join, parse, resolve } from "node:path";
import { BackupState, DEFAULT_RECOVERY_POLICY, RecoveryPhase, RecoverySourceState, type BackupManifest, type PersistentArtifact, type RecoveryHistoryEntry, type RecoveryPlan, type RecoveryPolicy, type RecoveryReport, type RecoverySource } from "./RecoveryContracts.ts";
import { readZip, writeZip } from "./ZipArchive.ts";

const SECRET_KEYS=/password|api.?key|access.?token|refresh.?token|master.?password|vault|credential|secret|authorization|private.?key/i;
const sha=(data:string|Buffer)=>createHash("sha256").update(data).digest("hex");
const stable=(value:unknown)=>JSON.stringify(value,(_k,v)=>v&&typeof v==="object"&&!Array.isArray(v)?Object.fromEntries(Object.entries(v).sort(([a],[b])=>a.localeCompare(b))):v);
function assertArtifact(value:unknown):asserts value is PersistentArtifact { const a=value as PersistentArtifact;if(!a||typeof a.stableId!=="string"||!a.stableId||!Number.isInteger(a.version)||a.version<1||typeof a.businessPackageId!=="string"||typeof a.type!=="string"||!Number.isFinite(Date.parse(a.updatedAt)))throw new Error("Invalid persistent artifact schema");if(SECRET_KEYS.test(stable(a.payload)))throw new Error("Protected credential material is outside ordinary backup scope"); }
async function atomicWrite(path:string,data:string|Buffer){await mkdir(dirname(path),{recursive:true});const temporary=`${path}.${randomUUID()}.tmp`;const handle=await open(temporary,"wx",0o600);try{await handle.writeFile(data);await handle.sync();}finally{await handle.close();}await rename(temporary,path);}

/** Governed backup, integrity, deterministic salvage and clean-target activation service. */
export class RecoveryManager {
  readonly history:RecoveryHistoryEntry[]=[]; readonly phases:RecoveryPhase[]=[]; private failures=new Map<string,number>();
  constructor(readonly activeState:string,readonly snapshots:string,readonly applicationVersion="1.0.0",readonly databaseSchemaVersion=1,readonly policy:RecoveryPolicy=DEFAULT_RECOVERY_POLICY,private readonly clock=()=>new Date()){
    if(policy.retentionGenerations<2)throw new Error("Backup retention must preserve at least two generations");
  }

  async commit(artifact:PersistentArtifact):Promise<void>{assertArtifact(artifact);const target=join(this.activeState,`${encodeURIComponent(artifact.stableId)}.json`),body=stable(artifact);await atomicWrite(target,body);await atomicWrite(`${target}.integrity`,stable({stableId:artifact.stableId,version:artifact.version,checksum:sha(body),schemaVersion:this.databaseSchemaVersion,updatedAt:artifact.updatedAt,businessPackageId:artifact.businessPackageId,provenance:artifact.provenance??"application-command"}));await this.snapshot(artifact);}
  async snapshot(artifact:PersistentArtifact):Promise<string>{assertArtifact(artifact);await mkdir(this.snapshots,{recursive:true});const name=`${encodeURIComponent(artifact.stableId)}--v${artifact.version}--${this.clock().toISOString().replaceAll(":","-")}.json`,path=join(this.snapshots,name),body=stable(artifact);await atomicWrite(path,body);await atomicWrite(`${path}.sha256`,sha(body));await this.prune(this.snapshots,this.policy.snapshotRetention,p=>p.endsWith(".json"));return path;}
  async validateActive():Promise<{healthy:string[];missing:string[];corrupt:string[]}>{const result={healthy:[] as string[],missing:[] as string[],corrupt:[] as string[]};await mkdir(this.activeState,{recursive:true});for(const name of await readdir(this.activeState)){if(!name.endsWith(".integrity"))continue;const registryPath=join(this.activeState,name),target=join(this.activeState,name.slice(0,-10));try{const registry=JSON.parse(await readFile(registryPath,"utf8"));try{const body=await readFile(target),artifact=JSON.parse(body.toString());assertArtifact(artifact);(sha(body)===registry.checksum&&artifact.version===registry.version&&registry.schemaVersion===this.databaseSchemaVersion?result.healthy:result.corrupt).push(registry.stableId);}catch(error){((error as NodeJS.ErrnoException).code==="ENOENT"?result.missing:result.corrupt).push(registry.stableId);}}catch{result.corrupt.push(decodeURIComponent(name.slice(0,-15)));}}return result;}

  async createBackup(artifacts:readonly PersistentArtifact[],destination=this.policy.backupLocation):Promise<{path:string;state:BackupState;manifest:BackupManifest}>{
    for(const artifact of artifacts)assertArtifact(artifact);await mkdir(destination,{recursive:true});const createdAt=this.clock().toISOString(),id=`backup-${createdAt}-${randomUUID().slice(0,8)}`,inventory:Record<string,number>={},files=new Map<string,Buffer>();
    for(const artifact of artifacts){inventory[artifact.type]=(inventory[artifact.type]??0)+1;files.set(`state/${encodeURIComponent(artifact.stableId)}.json`,Buffer.from(stable(artifact)));}
    const artifactInventory=[...files].map(([path,data])=>{const artifact=artifacts.find(a=>path===`state/${encodeURIComponent(a.stableId)}.json`)!;return{path,stableId:artifact.stableId,version:artifact.version,businessPackageId:artifact.businessPackageId,type:artifact.type,checksum:sha(data)};});
    const manifest:BackupManifest={backupId:id,createdAt,applicationVersion:this.applicationVersion,backupSchemaVersion:1,databaseSchemaVersion:this.databaseSchemaVersion,backupFormatVersion:1,sourceInstallationIdentity:sha(this.policy.installationIdentity??"local-installation").slice(0,24),businessPackageScope:[...new Set(artifacts.map(a=>a.businessPackageId))].sort(),contentInventory:inventory,artifacts:artifactInventory,completionState:"Complete",verificationState:"Verified",verification:{algorithm:"SHA-256",verifiedAt:createdAt}};
    files.set("manifest.json",Buffer.from(stable(manifest)));const name=`ALIVO-OS-BACKUP-${createdAt.slice(0,10)}-${createdAt.slice(11,16).replace(":","")}-${id.slice(-8)}.zip`,final=join(destination,name),temporary=`${final}.${randomUUID()}.incomplete`;
    await atomicWrite(temporary,writeZip(files));const verification=await this.verifyBackup(temporary);if(verification.state!==BackupState.Verified){await rm(temporary,{force:true});throw new Error(`Backup verification failed: ${verification.reason}`);}await rename(temporary,final);await this.prune(destination,this.policy.retentionGenerations,p=>/^ALIVO-OS-BACKUP-.*\.zip$/.test(p));return{path:final,state:BackupState.Verified,manifest};
  }
  async verifyBackup(path:string):Promise<{state:BackupState;manifest?:BackupManifest;artifacts?:PersistentArtifact[];reason?:string}>{try{const files=readZip(await readFile(path)),manifestFile=files.get("manifest.json");if(!manifestFile)throw new Error("Backup manifest is missing");const manifest=JSON.parse(manifestFile.toString()) as BackupManifest;if(manifest.backupFormatVersion!==1||manifest.backupSchemaVersion!==1||manifest.databaseSchemaVersion<1)return{state:BackupState.Unsupported,reason:"Unsupported backup or schema metadata"};if(manifest.verificationState!=="Verified"||manifest.verification?.algorithm!=="SHA-256")throw new Error("Backup is not verified");const artifacts:PersistentArtifact[]=[];for(const item of manifest.artifacts){const body=files.get(item.path);if(!body)throw new Error(`Missing ${item.path}`);if(sha(body)!==item.checksum)throw new Error(`Checksum mismatch: ${item.path}`);const artifact=JSON.parse(body.toString());assertArtifact(artifact);if(artifact.stableId!==item.stableId||artifact.version!==item.version||artifact.businessPackageId!==item.businessPackageId||artifact.type!==item.type)throw new Error(`Manifest mismatch: ${item.path}`);artifacts.push(artifact);}if(stable([...new Set(artifacts.map(a=>a.businessPackageId))].sort())!==stable([...manifest.businessPackageScope].sort()))throw new Error("Business Package scope mismatch");return{state:BackupState.Verified,manifest,artifacts};}catch(error){return{state:BackupState.Corrupt,reason:(error as Error).message};}}
  async listBackups(destination=this.policy.backupLocation){const paths=(await readdir(destination).catch(()=>[])).filter(name=>/^ALIVO-OS-BACKUP-.*\.zip$/.test(name)).sort().reverse();return Promise.all(paths.map(async name=>{const path=join(destination,name),verification=await this.verifyBackup(path);return{path,size:(await stat(path)).size,state:verification.state,manifest:verification.manifest};}));}
  async inspectBackup(path:string){return this.verifyBackup(path);}
  async deleteBackup(path:string,authorized:boolean):Promise<void>{if(!authorized)throw new Error("CEO recovery authority is required");const backups=await this.listBackups(dirname(path)),selected=backups.find(item=>resolve(item.path)===resolve(path));if(!selected)throw new Error("Backup is outside the governed backup set");if(backups.filter(item=>item.state===BackupState.Verified).length<=2&&selected.state===BackupState.Verified)throw new Error("At least two verified generations must remain");await rm(path);}
  sameStorageWarning(destination=this.policy.backupLocation):boolean{return parse(resolve(destination)).root===parse(resolve(this.activeState)).root;}
  shouldCatchUp(lastVerified?:Date):boolean{return this.policy.monthlyBackupEnabled&&(!lastVerified||lastVerified<this.previousSchedule());}
  nextScheduledBackup(last?:Date):Date{const base=last??this.clock();return new Date(Date.UTC(base.getUTCFullYear(),base.getUTCMonth()+1,1,0));}

  async scan(approvedPaths:readonly string[]):Promise<RecoverySource[]>{this.phases.push(RecoveryPhase.Scanning);const sources:RecoverySource[]=[];for(const approved of [...new Set(approvedPaths.map(path=>resolve(path)))]){try{const info=await stat(approved),candidates=info.isDirectory()?(await readdir(approved)).filter(x=>x.endsWith(".zip")).map(x=>join(approved,x)):[approved];for(const location of candidates){const checked=await this.verifyBackup(location);sources.push({type:"Backup",location,date:checked.manifest?.createdAt,applicationVersion:checked.manifest?.applicationVersion,schemaVersion:checked.manifest?.databaseSchemaVersion,state:checked.state===BackupState.Verified?RecoverySourceState.Verified:checked.state===BackupState.Unsupported?RecoverySourceState.Unsupported:RecoverySourceState.Corrupt,newestRecordAt:checked.artifacts?.map(a=>a.updatedAt).sort().at(-1),recoverable:checked.state===BackupState.Verified});}}catch{sources.push({type:"Persistent State",location:approved,state:RecoverySourceState.Unknown,recoverable:false});}}return sources;}
  plan(baseLocation:string,base:readonly PersistentArtifact[],newer:readonly PersistentArtifact[]):RecoveryPlan{this.phases.push(RecoveryPhase.SelectingBase,RecoveryPhase.Salvaging);const byId=new Map(base.map(a=>[a.stableId,a])),recoverable:PersistentArtifact[]=[],rejected:{artifact?:PersistentArtifact;reason:string}[]=[],conflicts:RecoveryPlan["conflicts"][number][]=[];for(const candidate of [...newer].sort((a,b)=>a.updatedAt.localeCompare(b.updatedAt))){try{assertArtifact(candidate);}catch(error){rejected.push({artifact:candidate,reason:(error as Error).message});continue;}const current=byId.get(candidate.stableId);if(current&&candidate.version===current.version){if(stable(candidate)!==stable(current))conflicts.push({stableId:candidate.stableId,base:current,candidate,reason:"Same stable ID and version contain different valid content"});continue;}if(current&&candidate.version<current.version){rejected.push({artifact:candidate,reason:"Older than verified base"});continue;}const missing=(candidate.dependencies??[]).filter(id=>!byId.has(id));if(missing.length){rejected.push({artifact:candidate,reason:`Missing dependencies: ${missing.join(", ")}`});continue;}recoverable.push(candidate);byId.set(candidate.stableId,candidate);}return{selectedBase:baseLocation,recoverable,rejected,conflicts,migrationRequired:false,safe:conflicts.length===0};}
  async restore(source:string,plan:RecoveryPlan,target:string,authorized=true):Promise<RecoveryReport>{if(!authorized)throw new Error("CEO recovery authority is required");this.phases.push(RecoveryPhase.ForensicCopy);await mkdir(`${target}-forensic`,{recursive:true});const forensic=join(`${target}-forensic`,`${randomUUID()}-${parse(source).base}`);await copyFile(source,forensic);await chmod(forensic,0o444);const verified=await this.verifyBackup(source);if(verified.state!==BackupState.Verified)throw new Error("Recovery source is not verified");const merged=new Map(verified.artifacts!.map(a=>[a.stableId,a]));for(const artifact of plan.recoverable)merged.set(artifact.stableId,artifact);this.phases.push(RecoveryPhase.Validating);if(plan.conflicts.length||!plan.safe)return this.report([],plan,"FAIL","Not Activated",0);const clean=`${target}.${randomUUID()}.reconstructing`;await mkdir(clean,{recursive:true});for(const artifact of merged.values()){assertArtifact(artifact);await atomicWrite(join(clean,`${encodeURIComponent(artifact.stableId)}.json`),stable(artifact));}const previous=`${target}.${randomUUID()}.previous`;this.phases.push(RecoveryPhase.Activating);let preserved=false;try{await rename(target,previous);preserved=true;}catch(error){if((error as NodeJS.ErrnoException).code!=="ENOENT"){await rm(clean,{recursive:true,force:true});throw error;}}try{await rename(clean,target);}catch(error){if(preserved)await rename(previous,target);throw error;}if(preserved)await rm(previous,{recursive:true,force:true});this.phases.push(RecoveryPhase.Completed);const report=this.report([],plan,"PASS","Activated",merged.size);await atomicWrite(join(target,"recovery-history",`${report.timestamp.replaceAll(":","-")}.json`),stable(report));return report;}
  async selfHeal(artifactId:string):Promise<boolean>{const count=(this.failures.get(artifactId)??0)+1;this.failures.set(artifactId,count);if(count>=3){this.history.push({problem:"Repeated corruption; Recovery Attention Required",artifactId,validation:"FAIL",timestamp:this.clock().toISOString()});return false;}const prefix=`${encodeURIComponent(artifactId)}--`,names=(await readdir(this.snapshots).catch(()=>[])).filter(x=>x.startsWith(prefix)&&x.endsWith(".json")).sort().reverse();for(const name of names){try{const path=join(this.snapshots,name),body=await readFile(path);if(sha(body)!==(await readFile(`${path}.sha256`,"utf8")))continue;const artifact=JSON.parse(body.toString());assertArtifact(artifact);await this.commit(artifact);this.history.push({problem:"Missing or corrupt artifact",artifactId,source:path,sourceVersion:artifact.version,recoveredVersion:artifact.version,validation:"PASS",timestamp:this.clock().toISOString()});this.failures.delete(artifactId);return true;}catch{continue;}}this.history.push({problem:"Recovery Attention Required",artifactId,validation:"FAIL",timestamp:this.clock().toISOString()});return false;}
  private previousSchedule():Date{const now=this.clock();return new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),1,0));}
  private report(sources:RecoverySource[],plan:RecoveryPlan,validation:"PASS"|"FAIL",activation:"Activated"|"Not Activated",recovered:number):RecoveryReport{return{sources,selectedBase:plan.selectedBase,recordsInspected:recovered+plan.rejected.length+plan.conflicts.length,recordsRecovered:recovered,rejected:plan.rejected,conflicts:plan.conflicts,migrations:[],validation,activation,timestamp:this.clock().toISOString()};}
  private async prune(directory:string,retain:number,predicate:(path:string)=>boolean){const files=(await readdir(directory)).filter(predicate).sort();for(const name of files.slice(0,Math.max(0,files.length-retain)))await rm(resolve(directory,name),{force:true});}
}
