import { createHash, randomUUID } from "node:crypto";
import { chmod, copyFile, mkdir, open, readFile, readdir, rename, rm, stat, writeFile } from "node:fs/promises";
import { dirname, join, parse, resolve } from "node:path";
import { BackupState, DEFAULT_RECOVERY_POLICY, RecoveryPhase, RecoverySourceState, type BackupManifest, type PersistentArtifact, type RecoveryHistoryEntry, type RecoveryPlan, type RecoveryPolicy, type RecoveryReport, type RecoverySource } from "./RecoveryContracts.ts";

const SECRET_KEYS=/password|api.?key|access.?token|refresh.?token|master.?password|vault|credential|secret/i;
const sha=(data:string|Buffer)=>createHash("sha256").update(data).digest("hex");
const stable=(value:unknown)=>JSON.stringify(value,(_k,v)=>v&&typeof v==="object"&&!Array.isArray(v)?Object.fromEntries(Object.entries(v).sort(([a],[b])=>a.localeCompare(b))):v);
function assertArtifact(value:unknown):asserts value is PersistentArtifact { const a=value as PersistentArtifact;if(!a||typeof a.stableId!=="string"||!a.stableId||!Number.isInteger(a.version)||a.version<1||typeof a.businessPackageId!=="string"||typeof a.type!=="string"||!Number.isFinite(Date.parse(a.updatedAt)))throw new Error("Invalid persistent artifact schema");if(SECRET_KEYS.test(stable(a.payload)))throw new Error("Protected credential material is outside ordinary backup scope"); }
async function atomicWrite(path:string,data:string|Buffer){await mkdir(dirname(path),{recursive:true});const temporary=`${path}.${randomUUID()}.tmp`;const handle=await open(temporary,"wx");try{await handle.writeFile(data);await handle.sync();}finally{await handle.close();}await rename(temporary,path);}

/** Four-level survivability manager. Application code remains independent of every path it manages. */
export class RecoveryManager {
  readonly history:RecoveryHistoryEntry[]=[]; readonly phases:RecoveryPhase[]=[]; private failures=new Map<string,number>();
  constructor(readonly activeState:string, readonly snapshots:string, readonly applicationVersion="1.0.0", readonly databaseSchemaVersion=1, readonly policy:RecoveryPolicy=DEFAULT_RECOVERY_POLICY, private readonly clock=()=>new Date()){}

  async commit(artifact:PersistentArtifact):Promise<void>{assertArtifact(artifact);const target=join(this.activeState,`${encodeURIComponent(artifact.stableId)}.json`);await atomicWrite(target,stable(artifact));await atomicWrite(`${target}.integrity`,stable({stableId:artifact.stableId,version:artifact.version,checksum:sha(stable(artifact)),schemaVersion:this.databaseSchemaVersion,updatedAt:artifact.updatedAt,businessPackageId:artifact.businessPackageId,provenance:artifact.provenance??"application-command"}));await this.snapshot(artifact);}
  async snapshot(artifact:PersistentArtifact):Promise<string>{assertArtifact(artifact);await mkdir(this.snapshots,{recursive:true});const name=`${encodeURIComponent(artifact.stableId)}--v${artifact.version}--${this.clock().toISOString().replaceAll(":","-")}.json`;const path=join(this.snapshots,name);await atomicWrite(path,stable(artifact));await atomicWrite(`${path}.sha256`,sha(stable(artifact)));await this.prune(this.snapshots,this.policy.snapshotRetention,p=>p.endsWith(".json"));return path;}
  async validateActive():Promise<{healthy:string[];missing:string[];corrupt:string[]}>{const result={healthy:[] as string[],missing:[] as string[],corrupt:[] as string[]};await mkdir(this.activeState,{recursive:true});for(const name of await readdir(this.activeState)){if(!name.endsWith(".integrity"))continue;const target=join(this.activeState,name.slice(0,-10));try{const [body,registry]=await Promise.all([readFile(target),readFile(join(this.activeState,name),"utf8")]);const meta=JSON.parse(registry);const artifact=JSON.parse(body.toString());assertArtifact(artifact);(sha(body)===meta.checksum&&artifact.version===meta.version?result.healthy:result.corrupt).push(meta.stableId);}catch(error){const meta=JSON.parse(await readFile(join(this.activeState,name),"utf8"));((error as NodeJS.ErrnoException).code==="ENOENT"?result.missing:result.corrupt).push(meta.stableId);}}return result;}
  async createBackup(artifacts:readonly PersistentArtifact[],destination=this.policy.backupLocation):Promise<{path:string;state:BackupState;manifest:BackupManifest}>{for(const a of artifacts)assertArtifact(a);await mkdir(destination,{recursive:true});const createdAt=this.clock().toISOString(),id=`backup-${createdAt}-${randomUUID().slice(0,8)}`;const entries=artifacts.map(a=>({path:`state/${encodeURIComponent(a.stableId)}.json`,data:Buffer.from(stable(a)),artifact:a}));const inventory:Record<string,number>={};for(const a of artifacts)inventory[a.type]=(inventory[a.type]??0)+1;let manifest:BackupManifest={backupId:id,createdAt,applicationVersion:this.applicationVersion,backupSchemaVersion:1,databaseSchemaVersion:this.databaseSchemaVersion,backupFormatVersion:1,businessPackageScope:[...new Set(artifacts.map(a=>a.businessPackageId))].sort(),contentInventory:inventory,artifacts:entries.map(e=>({path:e.path,stableId:e.artifact.stableId,version:e.artifact.version,businessPackageId:e.artifact.businessPackageId,type:e.artifact.type,checksum:sha(e.data)})),completionState:"Complete",verificationState:"Pending"};const name=`ALIVO-OS-BACKUP-${createdAt.slice(0,7)}-${createdAt.slice(8,19).replaceAll(":","")}.zip`,final=join(destination,name),temporary=`${final}.${randomUUID()}.tmp`;await writeFile(temporary,stable({format:"ALIVO-OS-RECOVERY-1",manifest,files:Object.fromEntries(entries.map(e=>[e.path,e.data.toString("base64")]))}),{flag:"wx"});const verification=await this.verifyBackup(temporary);if(verification.state!==BackupState.Verified){await rm(temporary,{force:true});throw new Error(`Backup verification failed: ${verification.reason}`);}manifest={...manifest,verificationState:"Verified"};await writeFile(temporary,stable({format:"ALIVO-OS-RECOVERY-1",manifest,files:Object.fromEntries(entries.map(e=>[e.path,e.data.toString("base64")]))}));await rename(temporary,final);await this.prune(destination,this.policy.retentionGenerations,p=>p.endsWith(".zip"));return{path:final,state:BackupState.Verified,manifest};}
  async verifyBackup(path:string):Promise<{state:BackupState;manifest?:BackupManifest;artifacts?:PersistentArtifact[];reason?:string}>{try{const archive=JSON.parse(await readFile(path,"utf8"));if(archive.format!=="ALIVO-OS-RECOVERY-1"||!archive.manifest||archive.manifest.backupSchemaVersion!==1||archive.manifest.databaseSchemaVersion<1)return{state:BackupState.Unsupported,reason:"Unsupported backup or schema metadata"};const artifacts:PersistentArtifact[]=[];for(const item of archive.manifest.artifacts){const encoded=archive.files[item.path];if(typeof encoded!=="string")throw new Error(`Missing ${item.path}`);const body=Buffer.from(encoded,"base64");if(sha(body)!==item.checksum)throw new Error(`Checksum mismatch: ${item.path}`);const artifact=JSON.parse(body.toString());assertArtifact(artifact);if(artifact.stableId!==item.stableId||artifact.version!==item.version||artifact.businessPackageId!==item.businessPackageId||artifact.type!==item.type)throw new Error(`Manifest mismatch: ${item.path}`);artifacts.push(artifact);}if(stable([...new Set(artifacts.map(a=>a.businessPackageId))].sort())!==stable([...archive.manifest.businessPackageScope].sort()))throw new Error("Business Package scope mismatch");return{state:BackupState.Verified,manifest:archive.manifest,artifacts};}catch(error){return{state:BackupState.Corrupt,reason:(error as Error).message};}}
  async scan(approvedPaths:readonly string[]):Promise<RecoverySource[]>{this.phases.push(RecoveryPhase.Scanning);const sources:RecoverySource[]=[];for(const approved of approvedPaths){try{const info=await stat(approved);const candidates=info.isDirectory()?(await readdir(approved)).filter(x=>x.endsWith(".zip")).map(x=>join(approved,x)):[approved];for(const location of candidates){const checked=await this.verifyBackup(location);sources.push({type:"Backup",location,date:checked.manifest?.createdAt,applicationVersion:checked.manifest?.applicationVersion,schemaVersion:checked.manifest?.databaseSchemaVersion,state:checked.state===BackupState.Verified?RecoverySourceState.Verified:checked.state===BackupState.Unsupported?RecoverySourceState.Unsupported:RecoverySourceState.Corrupt,newestRecordAt:checked.artifacts?.map(a=>a.updatedAt).sort().at(-1),recoverable:checked.state===BackupState.Verified});}}catch{sources.push({type:"Persistent State",location:approved,state:RecoverySourceState.Unknown,recoverable:false});}}return sources;}
  plan(baseLocation:string,base:readonly PersistentArtifact[],newer:readonly PersistentArtifact[]):RecoveryPlan{this.phases.push(RecoveryPhase.SelectingBase,RecoveryPhase.Salvaging);const byId=new Map(base.map(a=>[a.stableId,a])),recoverable:PersistentArtifact[]=[],rejected:{artifact?:PersistentArtifact;reason:string}[]=[],conflicts:RecoveryPlan["conflicts"][number][]=[];const candidates=[...newer].sort((a,b)=>a.updatedAt.localeCompare(b.updatedAt));for(const candidate of candidates){try{assertArtifact(candidate);}catch(error){rejected.push({artifact:candidate,reason:(error as Error).message});continue;}const current=byId.get(candidate.stableId);if(current&&candidate.version===current.version){if(stable(candidate)!==stable(current))conflicts.push({stableId:candidate.stableId,base:current,candidate,reason:"Same stable ID and version contain different valid content"});continue;}if(current&&candidate.version<current.version){rejected.push({artifact:candidate,reason:"Older than verified base"});continue;}const missing=(candidate.dependencies??[]).filter(id=>!byId.has(id)&&!recoverable.some(a=>a.stableId===id));if(missing.length){rejected.push({artifact:candidate,reason:`Missing dependencies: ${missing.join(", ")}`});continue;}recoverable.push(candidate);byId.set(candidate.stableId,candidate);}return{selectedBase:baseLocation,recoverable,rejected,conflicts,migrationRequired:false,safe:conflicts.length===0};}
  async restore(source:string,plan:RecoveryPlan,target:string):Promise<RecoveryReport>{this.phases.push(RecoveryPhase.ForensicCopy);await mkdir(`${target}-forensic`,{recursive:true});const forensic=join(`${target}-forensic`,parse(source).base);await copyFile(source,forensic);await chmod(forensic,0o444);const verified=await this.verifyBackup(source);if(verified.state!==BackupState.Verified)throw new Error("Recovery source is not verified");this.phases.push(RecoveryPhase.Validating);const merged=new Map(verified.artifacts!.map(a=>[a.stableId,a]));for(const a of plan.recoverable)merged.set(a.stableId,a);const clean=`${target}.${randomUUID()}.reconstructing`;await mkdir(clean,{recursive:true});for(const artifact of merged.values()){assertArtifact(artifact);await atomicWrite(join(clean,`${encodeURIComponent(artifact.stableId)}.json`),stable(artifact));}if(plan.conflicts.length){await rm(clean,{recursive:true,force:true});return this.report([],plan,"FAIL","Not Activated",0);}this.phases.push(RecoveryPhase.Activating);await rm(target,{recursive:true,force:true});await rename(clean,target);this.phases.push(RecoveryPhase.Completed);return this.report([],plan,"PASS","Activated",merged.size);}
  async selfHeal(artifactId:string):Promise<boolean>{const count=(this.failures.get(artifactId)??0)+1;this.failures.set(artifactId,count);if(count>=3){this.history.push({problem:"Repeated corruption; Recovery Attention Required",artifactId,validation:"FAIL",timestamp:this.clock().toISOString()});return false;}const prefix=`${encodeURIComponent(artifactId)}--`;const names=(await readdir(this.snapshots).catch(()=>[])).filter(x=>x.startsWith(prefix)&&x.endsWith(".json")).sort().reverse();for(const name of names){try{const path=join(this.snapshots,name),body=await readFile(path);if(sha(body)!==(await readFile(`${path}.sha256`,"utf8")))continue;const artifact=JSON.parse(body.toString());assertArtifact(artifact);await this.commit(artifact);this.history.push({problem:"Missing or corrupt artifact",artifactId,source:path,sourceVersion:artifact.version,recoveredVersion:artifact.version,validation:"PASS",timestamp:this.clock().toISOString()});return true;}catch{continue;}}this.history.push({problem:"Recovery Attention Required",artifactId,validation:"FAIL",timestamp:this.clock().toISOString()});return false;}
  nextScheduledBackup(last?:Date):Date{const base=last??this.clock(),next=new Date(Date.UTC(base.getUTCFullYear(),base.getUTCMonth()+1,1));return next;}
  private report(sources:RecoverySource[],plan:RecoveryPlan,validation:"PASS"|"FAIL",activation:"Activated"|"Not Activated",recovered:number):RecoveryReport{return{sources,selectedBase:plan.selectedBase,recordsInspected:recovered+plan.rejected.length+plan.conflicts.length,recordsRecovered:recovered,rejected:plan.rejected,conflicts:plan.conflicts,migrations:[],validation,activation,timestamp:this.clock().toISOString()};}
  private async prune(directory:string,retain:number,predicate:(path:string)=>boolean){if(retain<1)return;const files=(await readdir(directory)).filter(predicate).sort();for(const name of files.slice(0,Math.max(0,files.length-retain)))await rm(resolve(directory,name),{force:true});}
}
