import { BusinessPackageId, Confidence, Evidence, Freshness, FreshnessStatus } from "../../../intelligence/market/MarketIntelligenceDomain.ts";
import { PatternDecay, PatternStability } from "../patterns/PatternIntelligenceDomain.ts";
import { OutcomeClassification } from "../performance/PerformanceIntelligenceDomain.ts";
import { MarketOpportunity, OpportunityCandidate, OpportunityEffort, OpportunityEvaluation, OpportunityEvidence, OpportunityId, OpportunityPriority, OpportunityRisk, OpportunityStatus, OpportunityValue } from "./OpportunityIntelligenceDomain.ts";
import { OpportunityIntelligenceException } from "./OpportunityIntelligenceException.ts";
import { OpportunityRepository, type OpportunityQuery } from "./OpportunityRepository.ts";

export interface OpportunityEvaluationInput { effort?:OpportunityEffort;strategicRelevance?:number;neutralEvidence?:readonly Evidence[]; }
export class OpportunityIntelligenceService {
 constructor(readonly opportunities:OpportunityRepository){}
 registerCandidate(candidate:OpportunityCandidate):OpportunityCandidate{return this.opportunities.createCandidate(candidate);}
 aggregateOpportunityEvidence(candidate:OpportunityCandidate,at:Date,neutral:readonly Evidence[]=[]):OpportunityEvidence{return new OpportunityEvidence(candidate.supportingEvidence,candidate.contradictingEvidence,neutral,[],[],candidate.competitiveGaps,candidate.patterns,candidate.performanceEvaluations,this.evaluateFreshness(candidate.latestEvidenceAt,at));}
 evaluateFreshness(latest:Date,at:Date):Freshness{const days=(at.getTime()-latest.getTime())/86400000;if(!Number.isFinite(days)||days<0)throw new OpportunityIntelligenceException("Evaluation cannot precede latest evidence","INVALID_EVALUATION_TIME");return new Freshness(days<=30?FreshnessStatus.Current:days<=90?FreshnessStatus.Ageing:days<=180?FreshnessStatus.Stale:FreshnessStatus.Expired,at);}
 evaluateValue(e:OpportunityEvidence):OpportunityValue{if(e.supporting.length===0)return OpportunityValue.Unknown;let score=e.supporting.length+e.competitiveGaps.length+e.patterns.filter(p=>p.decay===PatternDecay.None).length+e.performanceEvaluations.filter(p=>p.classification===OutcomeClassification.Exceeded||p.classification===OutcomeClassification.Met).length-e.contradicting.length;if(e.freshness.status===FreshnessStatus.Stale||e.freshness.status===FreshnessStatus.Expired)score--;return score>=6?OpportunityValue.VeryHigh:score>=4?OpportunityValue.High:score>=2?OpportunityValue.Moderate:OpportunityValue.Low;}
 evaluateEffort(input:OpportunityEvaluationInput={}):OpportunityEffort{return input.effort??OpportunityEffort.Unknown;}
 evaluateRisk(e:OpportunityEvidence):OpportunityRisk{if(e.evidenceCount===0)return OpportunityRisk.Unknown;if(e.freshness.status===FreshnessStatus.Expired)return OpportunityRisk.Critical;const ratio=e.contradicting.length/e.evidenceCount;if(ratio>=.5)return OpportunityRisk.High;if(e.freshness.status===FreshnessStatus.Stale||ratio>0||e.sourceDiversity<2||e.patterns.some(p=>p.stability===PatternStability.Unstable||p.decay===PatternDecay.High))return OpportunityRisk.Moderate;return OpportunityRisk.Low;}
 evaluatePriority(value:OpportunityValue,effort:OpportunityEffort,risk:OpportunityRisk,confidence:Confidence,freshness:Freshness,strategicRelevance=0):OpportunityPriority{if(value===OpportunityValue.Unknown||effort===OpportunityEffort.Unknown||risk===OpportunityRisk.Unknown)return OpportunityPriority.Unranked;const values={[OpportunityValue.Low]:1,[OpportunityValue.Moderate]:2,[OpportunityValue.High]:3,[OpportunityValue.VeryHigh]:4,[OpportunityValue.Unknown]:0},efforts={[OpportunityEffort.Low]:0,[OpportunityEffort.Moderate]:1,[OpportunityEffort.High]:2,[OpportunityEffort.VeryHigh]:3,[OpportunityEffort.Unknown]:2},risks={[OpportunityRisk.Low]:0,[OpportunityRisk.Moderate]:1,[OpportunityRisk.High]:2,[OpportunityRisk.Critical]:4,[OpportunityRisk.Unknown]:2};let score=values[value]-efforts[effort]-risks[risk]+confidence.value*2+Math.max(0,Math.min(1,strategicRelevance));if(freshness.status===FreshnessStatus.Stale)score-=1;if(freshness.status===FreshnessStatus.Expired)score-=3;return score>=5?OpportunityPriority.Urgent:score>=3.5?OpportunityPriority.High:score>=2?OpportunityPriority.Normal:OpportunityPriority.Low;}
 evaluate(candidate:OpportunityCandidate,at:Date,input:OpportunityEvaluationInput={}):OpportunityEvaluation{const evidence=this.aggregateOpportunityEvidence(candidate,at,input.neutralEvidence),freshness=evidence.freshness,total=evidence.evidenceCount,consistency=(evidence.supporting.length-evidence.contradicting.length)/Math.max(1,total);const raw=.1+Math.min(evidence.supporting.length,4)*.1+Math.min(evidence.sourceDiversity,3)*.1+consistency*.2+Math.min(candidate.patterns.length+candidate.competitiveGaps.length+candidate.performanceEvaluations.length,3)*.08+(freshness.status===FreshnessStatus.Current?.1:freshness.status===FreshnessStatus.Ageing?0:-.15);const confidence=new Confidence(Math.max(0,Math.min(1,Number(raw.toFixed(3))))),value=this.evaluateValue(evidence),effort=this.evaluateEffort(input),risk=this.evaluateRisk(evidence),priority=this.evaluatePriority(value,effort,risk,confidence,freshness,input.strategicRelevance);let status=OpportunityStatus.Evaluated;if(freshness.status===FreshnessStatus.Expired)status=OpportunityStatus.Expired;else if(evidence.contradicting.length>=evidence.supporting.length||candidate.patterns.some(p=>p.decay===PatternDecay.High||p.decay===PatternDecay.Expired))status=OpportunityStatus.Weakening;else if(confidence.value>=.6&&value!==OpportunityValue.Unknown&&risk!==OpportunityRisk.Critical)status=OpportunityStatus.Qualified;return new OpportunityEvaluation(confidence,value,effort,risk,priority,freshness,status,[{name:"evidence",contribution:Number((Math.min(evidence.supporting.length,4)*.1).toFixed(3)),explanation:`${evidence.supporting.length} supporting, ${evidence.contradicting.length} contradicting`},{name:"source-diversity",contribution:Math.min(evidence.sourceDiversity,3)*.1,explanation:`${evidence.sourceDiversity} independent sources`},{name:"freshness",contribution:freshness.status===FreshnessStatus.Current?.1:freshness.status===FreshnessStatus.Ageing?0:-.15,explanation:freshness.status}]);}
 evaluateCandidate(candidate:OpportunityCandidate,at:Date,input:OpportunityEvaluationInput={}):MarketOpportunity{const evaluation=this.evaluate(candidate,at,input),evidence=this.aggregateOpportunityEvidence(candidate,at,input.neutralEvidence);return this.opportunities.store(new MarketOpportunity({id:candidate.id,version:1,type:candidate.type,status:evaluation.status,title:candidate.title,description:candidate.description,businessPackageId:candidate.businessPackageId,scope:candidate.scope,evidence,value:evaluation.value,effort:evaluation.effort,risk:evaluation.risk,confidence:evaluation.confidence,freshness:evaluation.freshness,priority:evaluation.priority,createdAt:at,evaluatedAt:at,provenance:candidate.provenance}));}
 qualifyEligible(id:OpportunityId,pkg:BusinessPackageId,at:Date):MarketOpportunity{const current=this.required(id,pkg);if(current.confidence.value<.6||current.value===OpportunityValue.Unknown||current.risk===OpportunityRisk.Critical||current.freshness.status===FreshnessStatus.Expired)throw new OpportunityIntelligenceException("Opportunity does not meet qualification criteria","INELIGIBLE_QUALIFICATION");return this.reEvaluate(current,{status:OpportunityStatus.Qualified},at);}
 createRecommendationCandidate(id:OpportunityId,pkg:BusinessPackageId,at:Date):MarketOpportunity{const current=this.required(id,pkg);if(current.status!==OpportunityStatus.Qualified||current.priority===OpportunityPriority.Unranked)throw new OpportunityIntelligenceException("Qualified evaluated opportunity is required","INELIGIBLE_RECOMMENDATION_CANDIDACY");return this.reEvaluate(current,{status:OpportunityStatus.RecommendationCandidate},at);}
 attachSupportingEvidence(id:OpportunityId,pkg:BusinessPackageId,evidence:Evidence,at:Date):MarketOpportunity{const current=this.required(id,pkg);return this.withEvidence(current,new OpportunityEvidence([...current.evidence.supporting,evidence],current.evidence.contradicting,current.evidence.neutral,current.evidence.marketObservations,current.evidence.competitiveAnalyses,current.evidence.competitiveGaps,current.evidence.patterns,current.evidence.performanceEvaluations,this.evaluateFreshness(evidence.recordedAt,at)),at);}
 attachContradictoryEvidence(id:OpportunityId,pkg:BusinessPackageId,evidence:Evidence,at:Date):MarketOpportunity{const current=this.required(id,pkg);return this.withEvidence(current,new OpportunityEvidence(current.evidence.supporting,[...current.evidence.contradicting,evidence],current.evidence.neutral,current.evidence.marketObservations,current.evidence.competitiveAnalyses,current.evidence.competitiveGaps,current.evidence.patterns,current.evidence.performanceEvaluations,this.evaluateFreshness(evidence.recordedAt,at)),at);}
 reEvaluate(current:MarketOpportunity,changes:Partial<Pick<MarketOpportunity,"status"|"evidence"|"value"|"effort"|"risk"|"confidence"|"freshness"|"priority">>,at:Date):MarketOpportunity{return this.opportunities.store(new MarketOpportunity({...current.properties,...changes,version:current.version+1,evaluatedAt:at}));}
 retrieve(id:OpportunityId,pkg:BusinessPackageId){return this.opportunities.current(id,pkg);}retrieveHistory(id:OpportunityId,pkg:BusinessPackageId){return this.opportunities.history(id,pkg);}query(q:OpportunityQuery={}){return this.opportunities.query(q);}
 private withEvidence(current:MarketOpportunity,evidence:OpportunityEvidence,at:Date):MarketOpportunity{const value=this.evaluateValue(evidence),risk=this.evaluateRisk(evidence),confidence=new Confidence(Math.max(0,Math.min(1,current.confidence.value+(evidence.supporting.length-current.evidence.supporting.length)*.05-(evidence.contradicting.length-current.evidence.contradicting.length)*.12))),status=evidence.freshness.status===FreshnessStatus.Expired?OpportunityStatus.Expired:evidence.contradicting.length>=evidence.supporting.length?OpportunityStatus.Weakening:current.status;return this.reEvaluate(current,{evidence,value,risk,confidence,freshness:evidence.freshness,priority:this.evaluatePriority(value,current.effort,risk,confidence,evidence.freshness),status},at);}
 private required(id:OpportunityId,pkg:BusinessPackageId):MarketOpportunity{const found=this.opportunities.current(id,pkg);if(!found)throw new OpportunityIntelligenceException("Opportunity was not found","OPPORTUNITY_NOT_FOUND");return found;}
}
