import type { CompetitiveAnalysis, CompetitiveGap } from "../competitive/CompetitiveIntelligenceDomain.ts";
import type { MarketPattern } from "../patterns/PatternIntelligenceDomain.ts";
import type { PerformanceEvaluation } from "../performance/PerformanceIntelligenceDomain.ts";
import { BusinessPackageId, Confidence, Evidence, Freshness, MarketObservation, Provenance } from "../../../intelligence/market/MarketIntelligenceDomain.ts";
import { OpportunityIntelligenceException } from "./OpportunityIntelligenceException.ts";

function required(value:string, field:string):string { if(typeof value!=="string"||value.trim()==="") throw new OpportunityIntelligenceException(`${field} must not be empty`,"INVALID_OPPORTUNITY"); return value; }
function time(value:Date,field:string):number { const result=value instanceof Date?value.getTime():NaN;if(!Number.isFinite(result))throw new OpportunityIntelligenceException(`${field} must be a valid timestamp`,"INVALID_TIMESTAMP");return result; }
function list<T>(values:readonly T[]):readonly T[]{return Object.freeze([...values]);}

export class OpportunityId { readonly #value:string;constructor(value:string){this.#value=required(value,"Opportunity identifier");Object.freeze(this);}get value():string{return this.#value;}equals(other:OpportunityId):boolean{return other instanceof OpportunityId&&other.value===this.value;}toString():string{return this.value;} }
export enum OpportunityType { Keyword="Keyword",Topic="Topic",Content="Content",Product="Product",Audience="Audience",Market="Market",Presentation="Presentation",Visual="Visual",SearchIntent="SearchIntent",CompetitiveGap="CompetitiveGap",Performance="Performance",Workflow="Workflow",Capability="Capability",Research="Research",Seasonal="Seasonal",EmergingDemand="EmergingDemand",Other="Other" }
export enum OpportunityStatus { Candidate="Candidate",Evaluated="Evaluated",Qualified="Qualified",Weakening="Weakening",Rejected="Rejected",Expired="Expired",Archived="Archived",RecommendationCandidate="RecommendationCandidate" }
export enum OpportunityValue { Unknown="Unknown",Low="Low",Moderate="Moderate",High="High",VeryHigh="VeryHigh" }
export enum OpportunityEffort { Unknown="Unknown",Low="Low",Moderate="Moderate",High="High",VeryHigh="VeryHigh" }
export enum OpportunityRisk { Unknown="Unknown",Low="Low",Moderate="Moderate",High="High",Critical="Critical" }
export enum OpportunityPriority { Unranked="Unranked",Low="Low",Normal="Normal",High="High",Urgent="Urgent" }
export enum OpportunityEvidenceRole { Supporting="Supporting",Contradicting="Contradicting",Neutral="Neutral" }

export interface OpportunityScopeProperties { market?:string;language?:string;audience?:string;topic?:string;productCategory?:string;contentType?:string;channelCategory?:string;timeWindow?:string;geographicContext?:string; }
export class OpportunityScope {
 readonly market?:string;readonly language?:string;readonly audience?:string;readonly topic?:string;readonly productCategory?:string;readonly contentType?:string;readonly channelCategory?:string;readonly timeWindow?:string;readonly geographicContext?:string;
 constructor(readonly businessPackageId:BusinessPackageId, properties:OpportunityScopeProperties={}){if(!(businessPackageId instanceof BusinessPackageId))throw new OpportunityIntelligenceException("Opportunity scope requires a Business Package","INVALID_SCOPE");const entries=Object.entries(properties);for(const [key,value] of entries)if(value!==undefined)required(value,key);if(entries.every(([,v])=>v===undefined))throw new OpportunityIntelligenceException("Opportunity scope requires an explicit dimension","INVALID_SCOPE");Object.assign(this,properties);Object.freeze(this);}
 matches(other:OpportunityScope):boolean{return this.businessPackageId.value===other.businessPackageId.value&&(["market","language","audience","topic","productCategory","contentType","channelCategory","timeWindow","geographicContext"] as const).every(k=>other[k]===undefined||this[k]===other[k]);}
}

export interface OpportunityCandidateProperties { id:OpportunityId;type:OpportunityType;title:string;description:string;businessPackageId:BusinessPackageId;scope:OpportunityScope;supportingEvidence:readonly Evidence[];contradictingEvidence?:readonly Evidence[];competitiveGaps?:readonly CompetitiveGap[];patterns?:readonly MarketPattern[];performanceEvaluations?:readonly PerformanceEvaluation[];firstDetectedAt:Date;latestEvidenceAt:Date;provenance:Provenance; }
export class OpportunityCandidate { readonly supportingEvidence;readonly contradictingEvidence;readonly competitiveGaps;readonly patterns;readonly performanceEvaluations;readonly #first:number;readonly #latest:number;
 constructor(readonly properties:OpportunityCandidateProperties){required(properties.title,"Opportunity title");required(properties.description,"Opportunity description");if(properties.supportingEvidence.length===0)throw new OpportunityIntelligenceException("Opportunity candidate requires supporting evidence","MISSING_EVIDENCE");if(properties.scope.businessPackageId.value!==properties.businessPackageId.value)throw new OpportunityIntelligenceException("Opportunity scope must retain its Business Package","PACKAGE_MISMATCH");this.#first=time(properties.firstDetectedAt,"First detected timestamp");this.#latest=time(properties.latestEvidenceAt,"Latest evidence timestamp");if(this.#latest<this.#first)throw new OpportunityIntelligenceException("Latest evidence cannot precede first detection","INVALID_WINDOW");this.supportingEvidence=list(properties.supportingEvidence);this.contradictingEvidence=list(properties.contradictingEvidence??[]);this.competitiveGaps=list(properties.competitiveGaps??[]);this.patterns=list(properties.patterns??[]);this.performanceEvaluations=list(properties.performanceEvaluations??[]);for(const reference of [...this.patterns,...this.performanceEvaluations])if(reference.businessPackageId.value!==properties.businessPackageId.value)throw new OpportunityIntelligenceException("Intelligence references must remain in one Business Package","PACKAGE_MISMATCH");Object.freeze(this);}
 get id(){return this.properties.id;}get type(){return this.properties.type;}get title(){return this.properties.title;}get description(){return this.properties.description;}get businessPackageId(){return this.properties.businessPackageId;}get scope(){return this.properties.scope;}get provenance(){return this.properties.provenance;}get firstDetectedAt(){return new Date(this.#first);}get latestEvidenceAt(){return new Date(this.#latest);}
}
export class OpportunityEvidence { readonly supporting;readonly contradicting;readonly neutral;readonly marketObservations;readonly competitiveAnalyses;readonly competitiveGaps;readonly patterns;readonly performanceEvaluations;readonly provenances;
 constructor(supporting:readonly Evidence[],contradicting:readonly Evidence[]=[],neutral:readonly Evidence[]=[],marketObservations:readonly MarketObservation[]=[],competitiveAnalyses:readonly CompetitiveAnalysis[]=[],competitiveGaps:readonly CompetitiveGap[]=[],patterns:readonly MarketPattern[]=[],performanceEvaluations:readonly PerformanceEvaluation[]=[],readonly freshness:Freshness){if(supporting.length===0)throw new OpportunityIntelligenceException("Opportunity evidence requires support","MISSING_EVIDENCE");this.supporting=list(supporting);this.contradicting=list(contradicting);this.neutral=list(neutral);this.marketObservations=list(marketObservations);this.competitiveAnalyses=list(competitiveAnalyses);this.competitiveGaps=list(competitiveGaps);this.patterns=list(patterns);this.performanceEvaluations=list(performanceEvaluations);this.provenances=list([...supporting,...contradicting,...neutral].map(e=>e.provenance));Object.freeze(this);}get sourceDiversity():number{return new Set([...this.supporting,...this.contradicting,...this.neutral].map(e=>e.provenance.sourceId.value)).size;}get evidenceCount():number{return this.supporting.length+this.contradicting.length+this.neutral.length;}
}
export interface EvaluationFactor { readonly name:string;readonly contribution:number;readonly explanation:string; }
export class OpportunityEvaluation { readonly factors:readonly EvaluationFactor[];constructor(readonly confidence:Confidence,readonly value:OpportunityValue,readonly effort:OpportunityEffort,readonly risk:OpportunityRisk,readonly priority:OpportunityPriority,readonly freshness:Freshness,readonly status:OpportunityStatus,factors:readonly EvaluationFactor[]){this.factors=Object.freeze(factors.map(f=>Object.freeze({...f})));Object.freeze(this);} }
export interface MarketOpportunityProperties { id:OpportunityId;version:number;type:OpportunityType;status:OpportunityStatus;title:string;description:string;businessPackageId:BusinessPackageId;scope:OpportunityScope;evidence:OpportunityEvidence;value:OpportunityValue;effort:OpportunityEffort;risk:OpportunityRisk;confidence:Confidence;freshness:Freshness;priority:OpportunityPriority;createdAt:Date;evaluatedAt:Date;provenance:Provenance; }
export class MarketOpportunity { readonly #created:number;readonly #evaluated:number;constructor(readonly properties:MarketOpportunityProperties){if(!Number.isInteger(properties.version)||properties.version<1)throw new OpportunityIntelligenceException("Opportunity version must be positive","INVALID_VERSION");required(properties.title,"Opportunity title");required(properties.description,"Opportunity description");if(properties.scope.businessPackageId.value!==properties.businessPackageId.value)throw new OpportunityIntelligenceException("Opportunity context does not match scope","PACKAGE_MISMATCH");this.#created=time(properties.createdAt,"Creation timestamp");this.#evaluated=time(properties.evaluatedAt,"Evaluation timestamp");if(this.#evaluated<this.#created)throw new OpportunityIntelligenceException("Evaluation cannot precede creation","INVALID_TIMESTAMP");Object.freeze(this);}get id(){return this.properties.id;}get version(){return this.properties.version;}get type(){return this.properties.type;}get status(){return this.properties.status;}get title(){return this.properties.title;}get description(){return this.properties.description;}get businessPackageId(){return this.properties.businessPackageId;}get scope(){return this.properties.scope;}get evidence(){return this.properties.evidence;}get value(){return this.properties.value;}get effort(){return this.properties.effort;}get risk(){return this.properties.risk;}get confidence(){return this.properties.confidence;}get freshness(){return this.properties.freshness;}get priority(){return this.properties.priority;}get provenance(){return this.properties.provenance;}get createdAt(){return new Date(this.#created);}get evaluatedAt(){return new Date(this.#evaluated);}}
