import type {PerformanceEvaluation} from "../../performance/PerformanceIntelligenceDomain.ts";
import type {QuestionCluster} from "../../questions/QuestionIntelligenceDomain.ts";
import {BlogKnowledgeAvailability,BlogOpportunity,BlogOpportunityCoverageAssessment,BlogOpportunityDuplicateAssessment,BlogOpportunityEvidenceGap} from "../BlogOpportunityDomain.ts";
import {BusinessPackageId,Provenance} from "../../../../intelligence/market/MarketIntelligenceDomain.ts";
import {BusinessRecommendation,RecommendationEffort,RecommendationEvidence,RecommendationObjective,RecommendationPriority,RecommendationRisk,RecommendationType,RecommendationValue,RecommendedWorkflowReference,StrategicRelevance} from "../../../recommendations/RecommendationDomain.ts";

export class BlogRecommendationEvaluationException extends Error{constructor(message:string,readonly code="BLOG_RECOMMENDATION_EVALUATION_FAILURE",options?:ErrorOptions){super(message,options);this.name="BlogRecommendationEvaluationException";}}
const required=(v:string,f:string)=>{if(typeof v!=="string"||!v.trim())throw new BlogRecommendationEvaluationException(`${f} is required`,"INVALID_REQUEST");return v;};
const time=(v:Date,f:string)=>{if(!(v instanceof Date)||!Number.isFinite(v.getTime()))throw new BlogRecommendationEvaluationException(`${f} is invalid`,"INVALID_REQUEST");return v.getTime();};
const list=<T>(v:readonly T[])=>Object.freeze([...v]);
export class BlogRecommendationEvaluationId{constructor(readonly value:string){required(value,"Evaluation identifier");Object.freeze(this);}}
export enum BlogRecommendationEvaluationState{Requested="Requested",Started="Started",Completed="Completed",CompletedWithWarnings="CompletedWithWarnings",Failed="Failed"}
export enum BlogRecommendationAction{CreateNewArticle="CreateNewArticle",ExpandExistingArticle="ExpandExistingArticle",UpdateExistingArticle="UpdateExistingArticle",CreateRelatedArticle="CreateRelatedArticle",ResearchBeforeWriting="ResearchBeforeWriting",BuildContentCluster="BuildContentCluster",AnswerEmergingQuestion="AnswerEmergingQuestion",StrategicExperiment="StrategicExperiment",DeferContent="DeferContent",Other="Other"}
export enum BlogRecommendationEvidenceGap{UnknownSearchVolume="UnknownSearchVolume",UnknownMarketSize="UnknownMarketSize",UnknownAIDiscoveryPotential="UnknownAIDiscoveryPotential",InsufficientSourceDiversity="InsufficientSourceDiversity",UnknownCompetitiveCoverage="UnknownCompetitiveCoverage",UnknownKnowledgeReadiness="UnknownKnowledgeReadiness",UnknownContentOverlap="UnknownContentOverlap",Other="Other"}

export interface BlogRecommendationEvaluationRequestProperties{id:BlogRecommendationEvaluationId;businessPackageId:BusinessPackageId;blogOpportunityReference:string;blogOpportunityVersion:number;canonicalQuestionReference:string;questionClusterReference:string;market:string;language:string;intent:readonly string[];strategicContextReference:string;performanceContextReference?:string;correlationIdentifier:string;requestingAuthorityReference:string;requestedAt:Date;}
export class BlogRecommendationEvaluationRequest{readonly intent;readonly #at:number;constructor(readonly properties:BlogRecommendationEvaluationRequestProperties){for(const [v,f] of [[properties.blogOpportunityReference,"Blog Opportunity reference"],[properties.canonicalQuestionReference,"Canonical Question reference"],[properties.questionClusterReference,"Question Cluster reference"],[properties.market,"Market"],[properties.language,"Language"],[properties.strategicContextReference,"Strategic context reference"],[properties.correlationIdentifier,"Correlation identifier"],[properties.requestingAuthorityReference,"Requesting authority"]] as const)required(v,f);if(!Number.isInteger(properties.blogOpportunityVersion)||properties.blogOpportunityVersion<1)throw new BlogRecommendationEvaluationException("Blog Opportunity version is invalid","INVALID_REQUEST");this.intent=list(properties.intent);this.#at=time(properties.requestedAt,"Request timestamp");Object.freeze(this);}get id(){return this.properties.id;}get businessPackageId(){return this.properties.businessPackageId;}get requestedAt(){return new Date(this.#at);}}

export interface BlogRecommendationCandidateInputProperties{opportunity:BlogOpportunity;cluster:QuestionCluster;action:BlogRecommendationAction;objective:RecommendationObjective;evidence:RecommendationEvidence;coverage:BlogOpportunityCoverageAssessment;duplicateAssessment:BlogOpportunityDuplicateAssessment;knowledgeReadiness:BlogKnowledgeAvailability;whyThis:string;whyNow:string;competitiveContext?:readonly string[];relatedQuestionReferences?:readonly string[];businessMemoryReferences?:readonly string[];knowledgeContextReferences?:readonly string[];existingAssetReferences?:readonly string[];performanceEvaluations?:readonly PerformanceEvaluation[];evidenceGaps?:readonly BlogRecommendationEvidenceGap[];contradictoryEvidence?:readonly string[];value?:RecommendationValue;effort?:RecommendationEffort;strategicRelevance?:StrategicRelevance;timingSensitive?:boolean;searchDiscoveryObjective?:boolean;aiDiscoveryObjective?:boolean;crossChannelIntent?:boolean;recommendedWorkflow?:RecommendedWorkflowReference;provenance:Provenance;}
export class BlogRecommendationCandidateInput{readonly competitiveContext;readonly relatedQuestionReferences;readonly businessMemoryReferences;readonly knowledgeContextReferences;readonly existingAssetReferences;readonly performanceEvaluations;readonly evidenceGaps;readonly contradictoryEvidence;constructor(readonly properties:BlogRecommendationCandidateInputProperties){required(properties.whyThis,"Why this");required(properties.whyNow,"Why now");if(properties.objective.businessPackageId.value!==properties.opportunity.businessPackageId.value||properties.cluster.businessPackageId.value!==properties.opportunity.businessPackageId.value)throw new BlogRecommendationEvaluationException("Context crosses Business Package boundary","PACKAGE_MISMATCH");this.competitiveContext=list(properties.competitiveContext??[]);this.relatedQuestionReferences=list(properties.relatedQuestionReferences??[]);this.businessMemoryReferences=list(properties.businessMemoryReferences??[]);this.knowledgeContextReferences=list(properties.knowledgeContextReferences??[]);this.existingAssetReferences=list(properties.existingAssetReferences??[]);this.performanceEvaluations=list(properties.performanceEvaluations??[]);this.evidenceGaps=list(properties.evidenceGaps??[]);this.contradictoryEvidence=list(properties.contradictoryEvidence??[]);Object.freeze(this);}}

export class BlogRecommendationEvidenceSet{readonly sourceCategories;readonly supportingEvidence;readonly contradictoryEvidence;readonly evidenceGaps;readonly provenance;constructor(readonly canonicalQuestionReference:string,readonly canonicalQuestionText:string,readonly questionClusterReference:string,readonly questionPatternReference:string|undefined,readonly questionObservations:readonly string[],readonly independentObservationCount:number,readonly sourceDiversity:number,sourceCategories:readonly string[],readonly intent:readonly string[],readonly freshness:string,readonly trend:string,readonly actualSearchVolume:number|undefined,readonly coverage:BlogOpportunityCoverageAssessment,readonly duplicateAssessment:BlogOpportunityDuplicateAssessment,readonly competitiveContext:readonly string[],readonly knowledgeReadiness:BlogKnowledgeAvailability,readonly performanceReferences:readonly string[],readonly businessMemoryReferences:readonly string[],supportingEvidence:readonly string[],contradictoryEvidence:readonly string[],evidenceGaps:readonly BlogRecommendationEvidenceGap[],provenance:readonly Provenance[]){this.sourceCategories=list(sourceCategories);this.supportingEvidence=list(supportingEvidence);this.contradictoryEvidence=list(contradictoryEvidence);this.evidenceGaps=list(evidenceGaps);this.provenance=list(provenance);Object.freeze(this);}}

export interface BlogRecommendationEvaluationResultProperties{evaluationId:BlogRecommendationEvaluationId;businessPackageId:BusinessPackageId;blogOpportunityReference:string;blogOpportunityVersion:number;canonicalQuestionReference:string;canonicalQuestionText:string;eligible:boolean;recommendation?:BusinessRecommendation;action?:BlogRecommendationAction;state:BlogRecommendationEvaluationState;objective?:RecommendationObjective;confidence?:number;value?:RecommendationValue;effort?:RecommendationEffort;risk?:RecommendationRisk;strategicRelevance?:StrategicRelevance;priority?:RecommendationPriority;coverage:BlogOpportunityCoverageAssessment;duplicateAssessment:BlogOpportunityDuplicateAssessment;knowledgeReadiness:BlogKnowledgeAvailability;evidenceSet:BlogRecommendationEvidenceSet;evidenceGaps:readonly BlogRecommendationEvidenceGap[];contradictoryEvidence:readonly string[];recommendedFutureWorkflow?:RecommendedWorkflowReference;whyThis:string;whyNow:string;startedAt:Date;completedAt:Date;correlationIdentifier:string;provenance:readonly Provenance[];}
export class BlogRecommendationEvaluationResult{readonly evidenceGaps;readonly contradictoryEvidence;readonly provenance;readonly #started;readonly #completed;constructor(readonly properties:BlogRecommendationEvaluationResultProperties){if(properties.canonicalQuestionText!==properties.evidenceSet.canonicalQuestionText)throw new BlogRecommendationEvaluationException("Canonical Question and future H1 must remain exact","CANONICAL_QUESTION_MISMATCH");this.#started=time(properties.startedAt,"Start timestamp");this.#completed=time(properties.completedAt,"Completion timestamp");if(this.#completed<this.#started)throw new BlogRecommendationEvaluationException("Completion precedes start","INVALID_REQUEST");this.evidenceGaps=list(properties.evidenceGaps);this.contradictoryEvidence=list(properties.contradictoryEvidence);this.provenance=list(properties.provenance);Object.freeze(properties);Object.freeze(this);}get futureArticleH1(){return this.properties.canonicalQuestionText;}get startedAt(){return new Date(this.#started);}get completedAt(){return new Date(this.#completed);}}
export class BlogRecommendationEvaluationSummary{constructor(readonly blogOpportunitiesEvaluated:number,readonly eligibleOpportunities:number,readonly recommendationCandidates:number,readonly readyForCEOReview:number,readonly createNewArticleRecommendations:number,readonly existingArticleExpansionRecommendations:number,readonly updateRecommendations:number,readonly relatedArticleRecommendations:number,readonly researchBeforeWritingRecommendations:number,readonly insufficientEvidenceCases:number,readonly rejectedRecommendationCandidates:number){Object.freeze(this);}}
export const BLOG_RECOMMENDATION_EVENTS=Object.freeze(["BlogRecommendationEvaluationRequested","BlogRecommendationEvaluationStarted","BlogRecommendationCandidateCreated","BlogRecommendationResearchRequired","BlogRecommendationReadyForCEOReview","BlogRecommendationInsufficientEvidence","BlogRecommendationSuperseded","BlogRecommendationEvaluationCompleted","BlogRecommendationEvaluationFailed"] as const);
export function recommendationType(action:BlogRecommendationAction){return action===BlogRecommendationAction.ResearchBeforeWriting?RecommendationType.ResearchOpportunity:action===BlogRecommendationAction.StrategicExperiment?RecommendationType.StrategicExperiment:action===BlogRecommendationAction.UpdateExistingArticle?RecommendationType.ContentUpdate:action===BlogRecommendationAction.DeferContent?RecommendationType.Other:RecommendationType.ContentCreation;}
