import {AuditEvent} from "../../../../core/platform/AuditEvent.ts";import {AuditEventType} from "../../../../core/platform/AuditEventType.ts";import type {AuditRecorder} from "../../../../core/platform/AuditRecorder.ts";import {Event} from "../../../../core/platform/Event.ts";import type {EventBus} from "../../../../core/platform/EventBus.ts";import {EventContext} from "../../../../core/platform/EventContext.ts";import {EventId} from "../../../../core/platform/EventId.ts";import {EventType} from "../../../../core/platform/EventType.ts";
import {BlogOpportunityState} from "../BlogOpportunityDomain.ts";
import {BusinessRecommendation,RecommendationCandidate,RecommendationId,RecommendationStatus} from "../../../recommendations/RecommendationDomain.ts";import type {RecommendationEngine} from "../../../recommendations/RecommendationEngine.ts";
import {BlogRecommendationAction,BlogRecommendationCandidateInput,BlogRecommendationEvaluationException,BlogRecommendationEvaluationRequest,BlogRecommendationEvaluationResult,BlogRecommendationEvaluationState,BlogRecommendationEvaluationSummary,BlogRecommendationEvidenceSet,recommendationType} from "./BlogRecommendationEvaluationDomain.ts";import {BlogRecommendationEvaluationRepository} from "./BlogRecommendationEvaluationRepository.ts";

/** TCO-invoked advisory boundary. It evaluates supplied evidence but cannot approve, generate content, publish, schedule, or perform network operations. */
export class BlogRecommendationEvaluationWorkflow{
 #sequence=0;
 constructor(private readonly engine:RecommendationEngine,readonly repository=new BlogRecommendationEvaluationRepository(),private readonly events?:EventBus,private readonly audit?:AuditRecorder,private readonly clock=()=>new Date()){}
 evaluate(request:BlogRecommendationEvaluationRequest,input:BlogRecommendationCandidateInput):BlogRecommendationEvaluationResult{
  if(this.repository.result(request.id,request.businessPackageId.value))throw new BlogRecommendationEvaluationException("Evaluation already completed","IMMUTABLE_EVALUATION_RESULT");const started=this.clock();this.transition(request,BlogRecommendationEvaluationState.Requested,"BlogRecommendationEvaluationRequested");this.transition(request,BlogRecommendationEvaluationState.Started,"BlogRecommendationEvaluationStarted");
  try{const opportunity=input.properties.opportunity;if(opportunity.businessPackageId.value!==request.businessPackageId.value)throw new BlogRecommendationEvaluationException("Intelligence crosses Business Package boundary","PACKAGE_MISMATCH");if(opportunity.id.value!==request.properties.blogOpportunityReference||opportunity.version!==request.properties.blogOpportunityVersion)throw new BlogRecommendationEvaluationException("Blog Opportunity reference or version does not match","REFERENCE_MISMATCH");if(opportunity.canonicalQuestionReference!==request.properties.canonicalQuestionReference||opportunity.questionClusterReference!==request.properties.questionClusterReference||opportunity.canonicalQuestionText!==input.properties.cluster.canonical.text)throw new BlogRecommendationEvaluationException("Canonical Question must remain exact","CANONICAL_QUESTION_MISMATCH");
   const evidence=new BlogRecommendationEvidenceSet(opportunity.canonicalQuestionReference,opportunity.canonicalQuestionText,opportunity.questionClusterReference,opportunity.evidence.questionPatternReference,opportunity.evidence.supportingObservations,opportunity.evidence.independentObservationCount,opportunity.evidence.sourceDiversity,opportunity.evidence.sourceCategories,opportunity.evidence.intent,opportunity.evidence.freshness?.status??"Unknown",opportunity.evidence.trend,opportunity.evidence.actualSearchVolume, input.properties.coverage,input.properties.duplicateAssessment,input.competitiveContext,input.properties.knowledgeReadiness,input.performanceEvaluations.map((x:any)=>x.id?.value??x.properties?.id?.value??"Unavailable"),input.businessMemoryReferences,input.properties.evidence.supporting.map(x=>x.evidence.id.value),[...input.contradictoryEvidence,...input.properties.evidence.contradicting.map(x=>x.evidence.id.value)],input.evidenceGaps,input.properties.evidence.items.map(x=>x.evidence.provenance));
   const eligible=[BlogOpportunityState.Qualified,BlogOpportunityState.Emerging,BlogOpportunityState.ResearchRequired].includes(opportunity.state);if(!eligible)return this.finish(request,input,evidence,started,undefined,`Opportunity state ${opportunity.state} is ineligible`);
   if(evidence.contradictoryEvidence.length>=evidence.supportingEvidence.length)return this.finish(request,input,evidence,started,undefined,"Evidence is strongly contradicted");
   let action=input.properties.action;if(opportunity.state===BlogOpportunityState.ResearchRequired||input.properties.knowledgeReadiness===undefined||["ResearchRequired","InsufficientKnowledge","Unknown"].includes(input.properties.knowledgeReadiness)||input.evidenceGaps.length)action=BlogRecommendationAction.ResearchBeforeWriting;
   const id=new RecommendationId(`blog-recommendation:${request.businessPackageId.value}:${opportunity.id.value}:v${opportunity.version}`),candidate=new RecommendationCandidate({id,type:recommendationType(action),objective:input.properties.objective,businessPackageId:request.businessPackageId,evidence:input.properties.evidence,relatedPerformanceEvaluations:input.performanceEvaluations,relatedBusinessMemory:input.businessMemoryReferences,provenance:input.properties.provenance,createdAt:started});this.engine.registerCandidate(candidate);this.report("BlogRecommendationCandidateCreated",request,{recommendationId:id.value,canonicalQuestion:opportunity.canonicalQuestionText});
   const evaluation=this.engine.evaluateCandidate(candidate,{value:input.properties.value,effort:input.properties.effort,strategicRelevance:input.properties.strategicRelevance,timingSensitive:input.properties.timingSensitive});let recommendation=this.engine.createRecommendation(candidate,evaluation,this.clock());if(input.properties.recommendedWorkflow)recommendation=this.engine.repository.store(new BusinessRecommendation({...recommendation.properties,version:recommendation.version+1,recommendedWorkflow:input.properties.recommendedWorkflow,supersedesVersion:recommendation.version,supersessionReason:"Future governed workflow reference attached"}));
   if(action===BlogRecommendationAction.ResearchBeforeWriting)this.report("BlogRecommendationResearchRequired",request,{recommendationId:id.value});if(input.evidenceGaps.length)this.report("BlogRecommendationInsufficientEvidence",request,{recommendationId:id.value});if(evaluation.readyForCEOReview&&!input.evidenceGaps.length){recommendation=this.engine.markReadyForCEOReview(recommendation,`tco-review:${request.id.value}`,this.clock());this.report("BlogRecommendationReadyForCEOReview",request,{recommendationId:id.value});}
   return this.finish(request,input,evidence,started,recommendation,undefined,action);
  }catch(error){this.transition(request,BlogRecommendationEvaluationState.Failed,"BlogRecommendationEvaluationFailed");throw error instanceof BlogRecommendationEvaluationException?error:new BlogRecommendationEvaluationException("Blog Recommendation evaluation failed","BLOG_RECOMMENDATION_EVALUATION_FAILURE",{cause:error});}
 }
 private finish(request:BlogRecommendationEvaluationRequest,input:BlogRecommendationCandidateInput,evidence:BlogRecommendationEvidenceSet,started:Date,recommendation?:BusinessRecommendation,warning?:string,action?:BlogRecommendationAction){const state=warning?BlogRecommendationEvaluationState.CompletedWithWarnings:BlogRecommendationEvaluationState.Completed,result=new BlogRecommendationEvaluationResult({evaluationId:request.id,businessPackageId:request.businessPackageId,blogOpportunityReference:input.properties.opportunity.id.value,blogOpportunityVersion:input.properties.opportunity.version,canonicalQuestionReference:input.properties.opportunity.canonicalQuestionReference,canonicalQuestionText:input.properties.opportunity.canonicalQuestionText,eligible:warning?.startsWith("Opportunity state")!==true,recommendation,action,state,objective:recommendation?.objective,confidence:recommendation?.evaluation.confidence.value,value:recommendation?.evaluation.value,effort:recommendation?.evaluation.effort,risk:recommendation?.evaluation.risk,strategicRelevance:recommendation?.evaluation.strategicRelevance,priority:recommendation?.evaluation.priority,coverage:input.properties.coverage,duplicateAssessment:input.properties.duplicateAssessment,knowledgeReadiness:input.properties.knowledgeReadiness,evidenceSet:evidence,evidenceGaps:input.evidenceGaps,contradictoryEvidence:evidence.contradictoryEvidence,recommendedFutureWorkflow:recommendation?.recommendedWorkflow,whyThis:input.properties.whyThis,whyNow:input.properties.whyNow,startedAt:started,completedAt:this.clock(),correlationIdentifier:request.properties.correlationIdentifier,provenance:evidence.provenance});this.repository.store(result);this.transition(request,state,"BlogRecommendationEvaluationCompleted");return result;}
 summarize(results:readonly BlogRecommendationEvaluationResult[]){const actions=results.map(x=>x.properties.action);return new BlogRecommendationEvaluationSummary(results.length,results.filter(x=>x.properties.eligible).length,results.filter(x=>x.properties.recommendation).length,results.filter(x=>x.properties.recommendation?.status===RecommendationStatus.ReadyForCEOReview).length,actions.filter(x=>x===BlogRecommendationAction.CreateNewArticle).length,actions.filter(x=>x===BlogRecommendationAction.ExpandExistingArticle).length,actions.filter(x=>x===BlogRecommendationAction.UpdateExistingArticle).length,actions.filter(x=>x===BlogRecommendationAction.CreateRelatedArticle).length,actions.filter(x=>x===BlogRecommendationAction.ResearchBeforeWriting).length,results.filter(x=>x.evidenceGaps.length).length,results.filter(x=>!x.properties.recommendation).length);}
  private transition(request:BlogRecommendationEvaluationRequest,state:BlogRecommendationEvaluationState,name:string){this.repository.transition(request.id,state,this.clock());this.report(name,request,{state});}
 private report(name:string,request:BlogRecommendationEvaluationRequest,extra:Record<string,string>){const at=this.clock(),context={evaluationId:request.id.value,businessPackageId:request.businessPackageId.value,blogOpportunityReference:request.properties.blogOpportunityReference,...extra};this.events?.publish(new Event({id:new EventId(`blog-recommendation-${++this.#sequence}`),type:new EventType(name),timestamp:at,source:"BlogRecommendationEvaluationWorkflow",correlationId:request.properties.correlationIdentifier,context:new EventContext(context)}));this.audit?.append(new AuditEvent({id:`blog-recommendation-audit-${++this.#sequence}`,timestamp:at,type:AuditEventType.WorkflowEvent,source:"BlogRecommendationEvaluationWorkflow",action:name,result:extra.state??"Recorded",responsibleIdentity:request.properties.requestingAuthorityReference,relatedTaskOrWorkflowId:request.id.value,context}));}
}
