import type { CompetitiveAnalysis, CompetitiveGap } from "../competitive/CompetitiveIntelligenceDomain.ts";
import { OpportunityEffort, OpportunityId, OpportunityRisk, OpportunityValue } from "../opportunities/OpportunityIntelligenceDomain.ts";
import type { MarketPattern } from "../patterns/PatternIntelligenceDomain.ts";
import { QuestionCluster, QuestionContentGap, QuestionCoverageState, QuestionSourceCategory, QuestionTrend } from "../questions/QuestionIntelligenceDomain.ts";
import { BusinessPackageId, Confidence, Evidence, Freshness, Provenance } from "../../../intelligence/market/MarketIntelligenceDomain.ts";

export class BlogOpportunityException extends Error { constructor(message:string,readonly code="BLOG_OPPORTUNITY_FAILURE"){super(message);this.name="BlogOpportunityException";} }
const required=(value:string,field:string)=>{if(typeof value!=="string"||value.trim()==="")throw new BlogOpportunityException(`${field} is required`,"INVALID_REQUEST");return value;};
const time=(value:Date,field:string)=>{const result=value instanceof Date?value.getTime():NaN;if(!Number.isFinite(result))throw new BlogOpportunityException(`${field} is invalid`,"INVALID_REQUEST");return result;};
const list=<T>(items:readonly T[])=>Object.freeze([...items]);

export class BlogOpportunityEvaluationId { readonly #value:string;constructor(value:string){this.#value=required(value,"Evaluation identifier");Object.freeze(this);}get value(){return this.#value;} }
export enum BlogOpportunityType { NewArticle="NewArticle",ExistingArticleExpansion="ExistingArticleExpansion",ExistingArticleUpdate="ExistingArticleUpdate",ContentUpdate="ExistingArticleUpdate",RelatedArticle="RelatedArticle",ContentClusterExpansion="ContentClusterExpansion",ResearchFirst="ResearchFirst",NoNewArticleOpportunity="NoNewArticleOpportunity",Other="Other" }
export enum BlogOpportunityState { Candidate="Candidate",Emerging="Emerging",Qualified="Qualified",ResearchRequired="ResearchRequired",Weak="Weak",Duplicate="Duplicate",Contradicted="Contradicted",Deferred="Deferred",Rejected="Rejected",Expired="Expired" }
export enum BlogOpportunityRelevance { High="High",Moderate="Moderate",Low="Low",Irrelevant="Irrelevant",Unknown="Unknown" }
export enum BlogOpportunityDuplicateState { NoDuplicateFound="NoDuplicateFound",PossibleOverlap="PossibleOverlap",LikelyDuplicate="LikelyDuplicate",ExistingEquivalentContent="ExistingEquivalentContent",ExistingOpportunity="ExistingOpportunity",Unknown="Unknown" }
export enum BlogKnowledgeAvailability { SufficientKnowledge="SufficientKnowledge",PartialKnowledge="PartialKnowledge",ResearchRequired="ResearchRequired",InsufficientKnowledge="InsufficientKnowledge",Unknown="Unknown" }
export enum BlogTimingRelevance { Immediate="Immediate",Current="Current",Evergreen="Evergreen",Later="Later",SeasonalWindow="SeasonalWindow",Unknown="Unknown" }
export enum BlogTrendContext { Evergreen="Evergreen",Emerging="Emerging",Trending="Trending",Seasonal="Seasonal",Declining="Declining",Reappearing="Reappearing",Unknown="Unknown" }
export enum BlogOpportunityEvidenceGap { InsufficientQuestionEvidence="InsufficientQuestionEvidence",InsufficientSourceDiversity="InsufficientSourceDiversity",UnknownSearchVolume="UnknownSearchVolume",UnknownMarketSize="UnknownMarketSize",UnknownTrend="UnknownTrend",UnknownCoverage="UnknownCoverage",UnknownDuplicateRisk="UnknownDuplicateRisk",InsufficientKnowledge="InsufficientKnowledge",ResearchRequired="ResearchRequired",UnknownCompetitiveCoverage="UnknownCompetitiveCoverage",UnknownAIDiscoveryPotential="UnknownAIDiscoveryPotential",Other="Other" }
export enum BlogOpportunityRejectionReason { InsufficientEvidence="InsufficientEvidence",InsufficientSourceDiversity="InsufficientSourceDiversity",InsufficientBusinessRelevance="InsufficientBusinessRelevance",StrongExistingCoverage="StrongExistingCoverage",LikelyDuplicate="LikelyDuplicate",InsufficientKnowledge="InsufficientKnowledge",QuestionTooNarrow="QuestionTooNarrow",QuestionTooBroad="QuestionTooBroad",StaleEvidence="StaleEvidence",ContradictedEvidence="ContradictedEvidence",UnsupportedMarket="UnsupportedMarket",UnsupportedLanguage="UnsupportedLanguage",Other="Other" }

export class BlogOpportunityCoverageAssessment { readonly evidence;constructor(readonly state:QuestionCoverageState,evidence:readonly {contentReference:string;semanticSimilarity:number;explanation:string}[]=[]){this.evidence=list(evidence.map(x=>Object.freeze({...x})));Object.freeze(this);} }
export class BlogOpportunityDuplicateAssessment { readonly evidenceReferences;constructor(readonly state:BlogOpportunityDuplicateState,evidenceReferences:readonly string[]=[],readonly explanation="No duplicate evidence supplied."){this.evidenceReferences=list(evidenceReferences);Object.freeze(this);} }

export interface BlogOpportunityEvaluationRequestProperties { evaluationId:BlogOpportunityEvaluationId;businessPackageId:BusinessPackageId;questionClusterReference:string;canonicalQuestionReference:string;questionPatternReference?:string;contentGapReference?:string;market:string;language:string;intent:readonly string[];windowStart:Date;windowEnd:Date;correlationIdentifier:string;requestingAuthorityReference:string;requestedAt:Date; }
export class BlogOpportunityEvaluationRequest { readonly intent;readonly #start;readonly #end;readonly #requested;constructor(readonly properties:BlogOpportunityEvaluationRequestProperties){for(const [v,f] of [[properties.questionClusterReference,"Question Cluster reference"],[properties.canonicalQuestionReference,"Canonical Question reference"],[properties.market,"Market"],[properties.language,"Language"],[properties.correlationIdentifier,"Correlation identifier"],[properties.requestingAuthorityReference,"Requesting authority"]] as const)required(v,f);this.#start=time(properties.windowStart,"Window start");this.#end=time(properties.windowEnd,"Window end");this.#requested=time(properties.requestedAt,"Request timestamp");if(this.#end<this.#start)throw new BlogOpportunityException("Evaluation window is invalid","INVALID_REQUEST");this.intent=list(properties.intent);Object.freeze(this);}get evaluationId(){return this.properties.evaluationId;}get businessPackageId(){return this.properties.businessPackageId;}get windowStart(){return new Date(this.#start);}get windowEnd(){return new Date(this.#end);}get requestedAt(){return new Date(this.#requested);} }

export interface BlogOpportunityCandidateInputProperties { cluster:QuestionCluster;pattern?:MarketPattern;contentGap?:QuestionContentGap;relevance:BlogOpportunityRelevance;relevanceEvidence?:readonly Evidence[];coverage?:BlogOpportunityCoverageAssessment;duplicateAssessment:BlogOpportunityDuplicateAssessment;knowledgeAvailability:BlogKnowledgeAvailability;competitiveAnalyses?:readonly CompetitiveAnalysis[];competitiveGaps?:readonly CompetitiveGap[];actualSearchVolume?:number;searchDiscoveryEvidence?:readonly Evidence[];aiDiscoveryContext?:Readonly<Record<string,unknown>>;strategicFit?:boolean;granularity?:"Standalone"|"TooNarrow"|"TooBroad";timingRelevance?:BlogTimingRelevance;trendContext?:BlogTrendContext;existingAssetReferences?:readonly string[];pinterestPromotionLineageReference?:string; }
export class BlogOpportunityCandidateInput { readonly relevanceEvidence;readonly competitiveAnalyses;readonly competitiveGaps;readonly searchDiscoveryEvidence;readonly existingAssetReferences;constructor(readonly properties:BlogOpportunityCandidateInputProperties){if(properties.actualSearchVolume!==undefined&&(!Number.isFinite(properties.actualSearchVolume)||properties.actualSearchVolume<0))throw new BlogOpportunityException("Search volume must be supplied as non-negative source evidence","INVALID_EVIDENCE");const pkg=properties.cluster.businessPackageId.value;if(properties.pattern&&properties.pattern.businessPackageId.value!==pkg||properties.competitiveAnalyses?.some(x=>x.businessPackageId?.value!==pkg))throw new BlogOpportunityException("Evidence cannot cross Business Package boundaries","PACKAGE_MISMATCH");this.relevanceEvidence=list(properties.relevanceEvidence??[]);this.competitiveAnalyses=list(properties.competitiveAnalyses??[]);this.competitiveGaps=list(properties.competitiveGaps??[]);this.searchDiscoveryEvidence=list(properties.searchDiscoveryEvidence??[]);this.existingAssetReferences=list(properties.existingAssetReferences??[]);Object.freeze(this);}get cluster(){return this.properties.cluster;} }

export class BlogOpportunityEvidenceSet { readonly supportingObservations;readonly sourceCategories;readonly contradictoryEvidence;readonly competitiveAnalyses;readonly competitiveGaps;readonly evidenceGaps;readonly provenance;constructor(readonly canonicalQuestionReference:string,readonly canonicalQuestionText:string,readonly questionClusterReference:string,readonly questionPatternReference:string|undefined,readonly contentGapReference:string|undefined,supportingObservations:readonly string[],readonly independentObservationCount:number,readonly sourceDiversity:number,sourceCategories:readonly QuestionSourceCategory[],readonly intent:readonly string[],readonly trend:QuestionTrend,readonly freshness:Freshness,readonly market:string,readonly language:string,readonly relevance:BlogOpportunityRelevance,readonly coverage:BlogOpportunityCoverageAssessment,readonly duplicateAssessment:BlogOpportunityDuplicateAssessment,competitiveAnalyses:readonly CompetitiveAnalysis[],competitiveGaps:readonly CompetitiveGap[],readonly knowledgeAvailability:BlogKnowledgeAvailability,contradictoryEvidence:readonly Evidence[],evidenceGaps:readonly BlogOpportunityEvidenceGap[],readonly actualSearchVolume:number|undefined,provenance:readonly Provenance[]){this.supportingObservations=list(supportingObservations);this.sourceCategories=list(sourceCategories);this.contradictoryEvidence=list(contradictoryEvidence);this.competitiveAnalyses=list(competitiveAnalyses);this.competitiveGaps=list(competitiveGaps);this.evidenceGaps=list(evidenceGaps);this.provenance=list(provenance);Object.freeze(this);} }

export class BlogOpportunity { readonly #createdAt:number;constructor(readonly id:OpportunityId,readonly version:number,readonly businessPackageId:BusinessPackageId,readonly canonicalQuestionReference:string,readonly canonicalQuestionText:string,readonly questionClusterReference:string,readonly contentGapReference:string|undefined,readonly type:BlogOpportunityType,readonly state:BlogOpportunityState,readonly evidence:BlogOpportunityEvidenceSet,readonly confidence:Confidence,readonly value:OpportunityValue,readonly effort:OpportunityEffort,readonly risk:OpportunityRisk,readonly pinterestPromotionLineageReference:string|undefined,createdAt:Date){if(canonicalQuestionText!==evidence.canonicalQuestionText||canonicalQuestionReference!==evidence.canonicalQuestionReference)throw new BlogOpportunityException("Canonical Question wording and reference must remain exact","CANONICAL_QUESTION_MISMATCH");if(!Number.isInteger(version)||version<1)throw new BlogOpportunityException("Version must be positive","INVALID_VERSION");this.#createdAt=time(createdAt,"Creation timestamp");Object.freeze(this);}get futureH1(){return this.canonicalQuestionText;}get createdAt(){return new Date(this.#createdAt);} }

export interface BlogOpportunityEvaluationResultProperties { evaluationId:BlogOpportunityEvaluationId;businessPackageId:BusinessPackageId;canonicalQuestionReference:string;canonicalQuestionText:string;questionClusterReference:string;contentGapReference?:string;opportunity?:BlogOpportunity;opportunityType:BlogOpportunityType;state:BlogOpportunityState;confidence:Confidence;value:OpportunityValue;effort:OpportunityEffort;risk:OpportunityRisk;relevance:BlogOpportunityRelevance;coverage:BlogOpportunityCoverageAssessment;duplicateAssessment:BlogOpportunityDuplicateAssessment;knowledgeAvailability:BlogKnowledgeAvailability;evidenceGaps:readonly BlogOpportunityEvidenceGap[];warnings:readonly string[];rejectionReason?:BlogOpportunityRejectionReason;startedAt:Date;completedAt:Date;correlationIdentifier:string;provenance:readonly Provenance[]; }
export class BlogOpportunityEvaluationResult { readonly evidenceGaps;readonly warnings;readonly provenance;readonly #started;readonly #completed;constructor(readonly properties:BlogOpportunityEvaluationResultProperties){this.#started=time(properties.startedAt,"Start timestamp");this.#completed=time(properties.completedAt,"Completion timestamp");if(this.#completed<this.#started)throw new BlogOpportunityException("Completion precedes start","INVALID_REQUEST");if(properties.opportunity&&properties.opportunity.canonicalQuestionText!==properties.canonicalQuestionText)throw new BlogOpportunityException("Canonical Question text changed","CANONICAL_QUESTION_MISMATCH");this.evidenceGaps=list(properties.evidenceGaps);this.warnings=list(properties.warnings);this.provenance=list(properties.provenance);Object.freeze(properties);Object.freeze(this);}get startedAt(){return new Date(this.#started);}get completedAt(){return new Date(this.#completed);} }
export class BlogOpportunityEvaluationSummary { constructor(readonly questionClustersEvaluated:number,readonly eligibleQuestions:number,readonly candidateOpportunities:number,readonly emergingOpportunities:number,readonly qualifiedOpportunities:number,readonly researchRequired:number,readonly duplicateOrCoveredQuestions:number,readonly weakOpportunities:number,readonly rejectedOpportunities:number,readonly contentUpdateCandidates:number,readonly newArticleCandidates:number){Object.freeze(this);} }

export const BLOG_OPPORTUNITY_EVENTS=Object.freeze(["BlogOpportunityEvaluationRequested","BlogOpportunityEvaluationStarted","BlogOpportunityCandidateCreated","BlogOpportunityQualified","BlogOpportunityResearchRequired","BlogOpportunityDuplicateDetected","BlogOpportunityWeak","BlogOpportunityRejected","BlogOpportunityReevaluationRequired","BlogOpportunityEvaluationCompleted","BlogOpportunityEvaluationFailed"] as const);
