import {
  BusinessPackageId, Freshness, MarketObservation, MarketSource, MarketSourceId, Provenance,
} from "../MarketIntelligenceDomain.ts";
import type { CredentialId } from "../../../security/credentials/CredentialVault.ts";

export class MarketSourceIntegrationException extends Error {
  constructor(message: string, readonly code = "INVALID_MARKET_SOURCE_INTEGRATION") { super(message); this.name = "MarketSourceIntegrationException"; }
}
const text = (value: string, field: string): string => { if (typeof value !== "string" || value.trim() === "") throw new MarketSourceIntegrationException(`${field} is required`); return value; };
const time = (value: Date, field: string): number => { const result = value?.getTime(); if (!Number.isFinite(result)) throw new MarketSourceIntegrationException(`${field} is invalid`); return result; };

export class MarketSourceAdapterId { readonly #value: string; constructor(value: string) { this.#value = text(value, "Adapter identifier"); Object.freeze(this); } get value() { return this.#value; } }

/** Extensible capability value. The constants form the BOS baseline, while custom values remain possible. */
export class MarketSourceCapability {
  static readonly Search = new MarketSourceCapability("Search"); static readonly ContentDiscovery = new MarketSourceCapability("ContentDiscovery");
  static readonly KeywordObservation = new MarketSourceCapability("KeywordObservation"); static readonly CompetitiveObservation = new MarketSourceCapability("CompetitiveObservation");
  static readonly VisualMetadata = new MarketSourceCapability("VisualMetadata"); static readonly EngagementObservation = new MarketSourceCapability("EngagementObservation");
  static readonly PerformanceObservation = new MarketSourceCapability("PerformanceObservation"); static readonly TrendObservation = new MarketSourceCapability("TrendObservation");
  static readonly ProductObservation = new MarketSourceCapability("ProductObservation"); static readonly MarketObservation = new MarketSourceCapability("MarketObservation");
  static readonly AnalyticsObservation = new MarketSourceCapability("AnalyticsObservation"); static readonly Other = new MarketSourceCapability("Other");
  readonly value: string; constructor(value: string) { this.value = text(value, "Capability"); Object.freeze(this); } equals(other: MarketSourceCapability) { return other instanceof MarketSourceCapability && other.value === this.value; }
}
export enum MarketSourceState { Registered="Registered", Available="Available", Unavailable="Unavailable", Maintenance="Maintenance", Degraded="Degraded", OnHold="OnHold", Disabled="Disabled", Retired="Retired" }
export enum MarketSourceAvailability { Available="Available", Unavailable="Unavailable", Unknown="Unknown", Partial="Partial" }
export enum MarketSourceHealthState { Healthy="Healthy", Degraded="Degraded", Unhealthy="Unhealthy", Unknown="Unknown" }
export class MarketSourceHealth {
  readonly #success?: number; readonly #failure?: number; readonly #evaluated: number;
  constructor(readonly state: MarketSourceHealthState, evaluatedAt: Date, readonly consecutiveFailures=0, lastSuccessfulInteraction?: Date, lastFailure?: Date) {
    if (!Object.values(MarketSourceHealthState).includes(state) || !Number.isInteger(consecutiveFailures) || consecutiveFailures < 0) throw new MarketSourceIntegrationException("Source health is invalid");
    this.#evaluated=time(evaluatedAt,"Health evaluation timestamp"); this.#success=lastSuccessfulInteraction&&time(lastSuccessfulInteraction,"Last successful interaction"); this.#failure=lastFailure&&time(lastFailure,"Last failure"); Object.freeze(this);
  }
  get evaluatedAt(){return new Date(this.#evaluated);} get lastSuccessfulInteraction(){return this.#success===undefined?undefined:new Date(this.#success);} get lastFailure(){return this.#failure===undefined?undefined:new Date(this.#failure);}
}
export interface MarketSourceAuthorization { readonly businessPackageId: BusinessPackageId; readonly capabilities: readonly MarketSourceCapability[]; }
export interface MarketSourceDescriptorProperties { adapterId:MarketSourceAdapterId; source:MarketSource; displayName:string; capabilities:readonly MarketSourceCapability[]; state:MarketSourceState; availability:MarketSourceAvailability; health:MarketSourceHealth; authorizations:readonly MarketSourceAuthorization[]; registeredAt:Date; configurationReference?:string; credentialId?:CredentialId; priority?:number; supportedMarkets?:readonly string[]; supportedLanguages?:readonly string[]; }
export class MarketSourceDescriptor {
  readonly registeredAt:Date; readonly capabilities:readonly MarketSourceCapability[]; readonly authorizations:readonly MarketSourceAuthorization[]; readonly supportedMarkets:readonly string[]; readonly supportedLanguages:readonly string[];
  constructor(readonly properties:MarketSourceDescriptorProperties){
    if(!(properties.adapterId instanceof MarketSourceAdapterId)||!(properties.source instanceof MarketSource)||properties.capabilities.length===0)throw new MarketSourceIntegrationException("Descriptor dependencies are invalid"); text(properties.displayName,"Source display name");
    this.registeredAt=new Date(time(properties.registeredAt,"Registration timestamp")); this.capabilities=Object.freeze([...properties.capabilities]); this.authorizations=Object.freeze(properties.authorizations.map(a=>Object.freeze({businessPackageId:a.businessPackageId,capabilities:Object.freeze([...a.capabilities])}))); this.supportedMarkets=Object.freeze([...(properties.supportedMarkets??[])]);this.supportedLanguages=Object.freeze([...(properties.supportedLanguages??[])]); Object.freeze(this);
  }
  get adapterId(){return this.properties.adapterId;} get source(){return this.properties.source;} get state(){return this.properties.state;} get availability(){return this.properties.availability;} get health(){return this.properties.health;} get priority(){return this.properties.priority??0;}
  supports(c:MarketSourceCapability){return this.capabilities.some(x=>x.equals(c));} authorized(p:BusinessPackageId,c:MarketSourceCapability){return this.authorizations.some(a=>a.businessPackageId.value===p.value&&a.capabilities.some(x=>x.equals(c)));}
  with(changes:Partial<Pick<MarketSourceDescriptorProperties,"state"|"availability"|"health"|"authorizations">>){return new MarketSourceDescriptor({...this.properties,...changes});}
}
export interface MarketCollectionRequestProperties { id:string; capability:MarketSourceCapability; businessPackageId:BusinessPackageId; marketContext:string; languageContext?:string; subjectReference?:string; windowStart?:Date; windowEnd?:Date; freshness?:Freshness; correlationId:string; workflowOrTcoReference:string; requestedAt:Date; }
export class MarketCollectionRequest { readonly requestedAt:Date; constructor(readonly properties:MarketCollectionRequestProperties){text(properties.id,"Request identifier");text(properties.marketContext,"Market context");text(properties.correlationId,"Correlation identifier");text(properties.workflowOrTcoReference,"Workflow or TCO reference");if(!(properties.capability instanceof MarketSourceCapability)||!(properties.businessPackageId instanceof BusinessPackageId))throw new MarketSourceIntegrationException("Collection request context is invalid");this.requestedAt=new Date(time(properties.requestedAt,"Request timestamp"));if(properties.windowStart&&properties.windowEnd&&properties.windowStart>properties.windowEnd)throw new MarketSourceIntegrationException("Collection window is invalid");Object.freeze(this);} get id(){return this.properties.id;} }
export enum MarketCollectionResultStatus { Success="Success", Partial="Partial", NoData="NoData", Unavailable="Unavailable", Failed="Failed", RateLimited="RateLimited", Cancelled="Cancelled" }
export enum MarketSourceFailureCategory { Unavailable="Unavailable", AuthenticationFailure="AuthenticationFailure", AuthorizationFailure="AuthorizationFailure", Timeout="Timeout", RateLimited="RateLimited", InvalidResponse="InvalidResponse", NormalizationFailure="NormalizationFailure", ConfigurationFailure="ConfigurationFailure", Unknown="Unknown" }
export class MarketSourceFailure { constructor(readonly category:MarketSourceFailureCategory,readonly message:string,readonly occurredAt:Date){text(message,"Failure message");time(occurredAt,"Failure timestamp");Object.freeze(this);} }
export class MarketSourceRateLimit { constructor(readonly limited:boolean,readonly observedAt:Date,readonly provenance:Provenance,readonly retryAfter?:Date,readonly resetReference?:string){time(observedAt,"Rate-limit timestamp");if(retryAfter)time(retryAfter,"Retry-after timestamp");Object.freeze(this);} }
export interface RawMarketRecordProperties { id:string; sourceId:MarketSourceId; requestId:string; providerRecordReference?:string; collectedAt:Date; observedAt?:Date; payloadReference:string; provenance:Provenance; recordType:string; }
export class RawMarketRecord { constructor(readonly properties:RawMarketRecordProperties){text(properties.id,"Raw record identifier");text(properties.requestId,"Collection request reference");text(properties.payloadReference,"Payload reference");text(properties.recordType,"Record type");time(properties.collectedAt,"Collection timestamp");if(properties.observedAt)time(properties.observedAt,"Observation timestamp");if(properties.sourceId.value!==properties.provenance.sourceId.value)throw new MarketSourceIntegrationException("Raw record provenance must preserve source identity");Object.freeze(this);} get id(){return this.properties.id;} get provenance(){return this.properties.provenance;} }
export class MarketCollectionResult { constructor(readonly requestId:string,readonly adapterId:MarketSourceAdapterId,readonly sourceId:MarketSourceId,readonly status:MarketCollectionResultStatus,readonly rawRecords:readonly RawMarketRecord[],readonly collectedAt:Date,readonly provenance:Provenance,readonly failure?:MarketSourceFailure,readonly rateLimit?:MarketSourceRateLimit){text(requestId,"Request reference");time(collectedAt,"Collection timestamp");if(status===MarketCollectionResultStatus.Failed&&!failure)throw new MarketSourceIntegrationException("Failed result requires a failure");Object.freeze(this);} }
export enum MarketNormalizationStatus { Normalized="Normalized", PartiallyNormalized="PartiallyNormalized", Rejected="Rejected", Unsupported="Unsupported", Failed="Failed" }
export class MarketNormalizationResult { readonly validationFailures:readonly string[]; constructor(readonly rawRecord:RawMarketRecord,readonly observation:MarketObservation|undefined,readonly status:MarketNormalizationStatus,failures:readonly string[],readonly provenance:Provenance,readonly normalizedAt:Date){time(normalizedAt,"Normalization timestamp");this.validationFailures=Object.freeze([...failures]);if((status===MarketNormalizationStatus.Normalized||status===MarketNormalizationStatus.PartiallyNormalized)&&!observation)throw new MarketSourceIntegrationException("Successful normalization requires an observation");if(observation&&(observation.sourceId.value!==rawRecord.properties.sourceId.value||observation.provenance.sourceId.value!==provenance.sourceId.value))throw new MarketSourceIntegrationException("Normalization must preserve source provenance");if(status===MarketNormalizationStatus.Rejected&&observation)throw new MarketSourceIntegrationException("Rejected source data cannot become an observation");Object.freeze(this);} }
export interface MarketSourceRequirementProperties { capability:MarketSourceCapability; businessPackageId:BusinessPackageId; marketContext?:string; languageContext?:string; freshness?:Freshness; minimumAvailability?:MarketSourceAvailability; preferredSourceIds?:readonly MarketSourceId[]; correlationReference?:string; }
export class MarketSourceRequirement { readonly preferredSourceIds:readonly MarketSourceId[];constructor(readonly properties:MarketSourceRequirementProperties){if(!(properties.capability instanceof MarketSourceCapability)||!(properties.businessPackageId instanceof BusinessPackageId))throw new MarketSourceIntegrationException("Source requirement is invalid");this.preferredSourceIds=Object.freeze([...(properties.preferredSourceIds??[])]);Object.freeze(this);} }
export class MarketSourceSelection { constructor(readonly requirement:MarketSourceRequirement,readonly selected:MarketSourceDescriptor|undefined,readonly fallbackCandidates:readonly MarketSourceDescriptor[],readonly evaluatedAt:Date){time(evaluatedAt,"Selection timestamp");Object.freeze(this);} }
export interface MarketSourceAdapter { readonly id:MarketSourceAdapterId; descriptor():MarketSourceDescriptor; collect(request:MarketCollectionRequest):Promise<MarketCollectionResult>; normalize?(record:RawMarketRecord):Promise<MarketNormalizationResult>; }
