import type {MarketPattern} from "../market/patterns/PatternIntelligenceDomain.ts";
import type {ExpectedOutcome,ObservedOutcome,PerformanceEvaluation,MeasurementWindow} from "../market/performance/PerformanceIntelligenceDomain.ts";
import type {BusinessRecommendation,RecommendationOutcomeReference} from "../recommendations/RecommendationDomain.ts";
import {BusinessPackageId,Confidence,Evidence,Freshness,Provenance} from "../../intelligence/market/MarketIntelligenceDomain.ts";
import {ContinuousLearningException} from "./ContinuousLearningException.ts";

const required=(value:string,field:string)=>{if(typeof value!=="string"||value.trim()==="")throw new ContinuousLearningException(`${field} must not be empty`,"INVALID_LEARNING");return value;};
const instant=(value:Date,field:string)=>{const result=value instanceof Date?value.getTime():NaN;if(!Number.isFinite(result))throw new ContinuousLearningException(`${field} must be a valid timestamp`,"INVALID_TIMESTAMP");return result;};
const list=<T>(values:readonly T[]=[]):readonly T[]=>Object.freeze([...values]);

export class LearningId { readonly #value:string;constructor(value:string){this.#value=required(value,"Learning identifier");Object.freeze(this);}get value(){return this.#value;}equals(other:LearningId){return other instanceof LearningId&&other.value===this.value;}toString(){return this.value;} }
export enum LearningType { RecommendationOutcome="RecommendationOutcome",PredictionAccuracy="PredictionAccuracy",PatternValidation="PatternValidation",PatternContradiction="PatternContradiction",CapabilityEffectiveness="CapabilityEffectiveness",WorkflowEffectiveness="WorkflowEffectiveness",MarketResponse="MarketResponse",StrategicLearning="StrategicLearning",NegativeLearning="NegativeLearning",InconclusiveLearning="InconclusiveLearning",Other="Other" }
export enum LearningDirection { Positive="Positive",Negative="Negative",Neutral="Neutral",Inconclusive="Inconclusive",Contradictory="Contradictory" }
export enum LearningStatus { Recorded="Recorded",Evaluated="Evaluated",Validated="Validated",NeedsReevaluation="NeedsReevaluation",BusinessMemoryCandidate="BusinessMemoryCandidate",Superseded="Superseded",Archived="Archived" }
export enum PredictionAccuracyStatus { Unknown="Unknown",Accurate="Accurate",MostlyAccurate="MostlyAccurate",PartiallyAccurate="PartiallyAccurate",Inaccurate="Inaccurate",NotMeasurable="NotMeasurable" }
export enum RecommendationQuality { Strong="Strong",Good="Good",Mixed="Mixed",Weak="Weak",Failed="Failed",Inconclusive="Inconclusive" }

export interface LearningEpisodeProperties { id:LearningId;version:number;type:LearningType;status:LearningStatus;businessPackageId:BusinessPackageId;recommendation:BusinessRecommendation;outcomeReference?:RecommendationOutcomeReference;ceoDecisionReference?:string;workflowExecutionReference?:string;expectedOutcome?:ExpectedOutcome;observedOutcome?:ObservedOutcome;performanceEvaluation?:PerformanceEvaluation;relatedPatterns?:readonly MarketPattern[];relatedOpportunityReferences?:readonly string[];relatedCapabilityReferences?:readonly string[];relatedWorkflowReferences?:readonly string[];createdAt:Date;measurementTimestamp?:Date;provenance:Provenance; }
export class LearningEpisode { readonly relatedPatterns;readonly relatedOpportunityReferences;readonly relatedCapabilityReferences;readonly relatedWorkflowReferences;readonly #created:number;readonly #measured?:number;constructor(readonly properties:LearningEpisodeProperties){if(!Number.isInteger(properties.version)||properties.version<1)throw new ContinuousLearningException("Learning version must be positive","INVALID_VERSION");const pkg=properties.businessPackageId.value;if(properties.recommendation.businessPackageId.value!==pkg||properties.expectedOutcome&&properties.expectedOutcome.businessPackageId.value!==pkg||properties.observedOutcome&&properties.observedOutcome.businessPackageId.value!==pkg||properties.performanceEvaluation&&properties.performanceEvaluation.businessPackageId.value!==pkg||(properties.relatedPatterns??[]).some(x=>x.businessPackageId.value!==pkg))throw new ContinuousLearningException("Learning references cannot cross Business Package boundaries","PACKAGE_MISMATCH");this.#created=instant(properties.createdAt,"Learning creation timestamp");this.#measured=properties.measurementTimestamp?instant(properties.measurementTimestamp,"Learning measurement timestamp"):undefined;if(this.#measured!==undefined&&this.#measured<this.#created)throw new ContinuousLearningException("Measurement cannot precede learning creation","INVALID_TIMESTAMP");this.relatedPatterns=list(properties.relatedPatterns);this.relatedOpportunityReferences=list(properties.relatedOpportunityReferences);this.relatedCapabilityReferences=list(properties.relatedCapabilityReferences);this.relatedWorkflowReferences=list(properties.relatedWorkflowReferences);Object.freeze(this);}get id(){return this.properties.id;}get version(){return this.properties.version;}get type(){return this.properties.type;}get status(){return this.properties.status;}get businessPackageId(){return this.properties.businessPackageId;}get recommendation(){return this.properties.recommendation;}get outcomeReference(){return this.properties.outcomeReference;}get expectedOutcome(){return this.properties.expectedOutcome;}get observedOutcome(){return this.properties.observedOutcome;}get performanceEvaluation(){return this.properties.performanceEvaluation;}get provenance(){return this.properties.provenance;}get createdAt(){return new Date(this.#created);}get measurementTimestamp(){return this.#measured===undefined?undefined:new Date(this.#measured);} }

export class LearningEvidence { readonly supportingEvidence;readonly negativeEvidence;readonly contradictoryEvidence;readonly neutralEvidence;readonly performanceReferences;readonly patternReferences;readonly recommendationReferences;constructor(supporting:readonly Evidence[],negative:readonly Evidence[],contradictory:readonly Evidence[],neutral:readonly Evidence[],performanceReferences:readonly string[],patternReferences:readonly string[],recommendationReferences:readonly string[],readonly provenance:Provenance,readonly freshness:Freshness,readonly confidence:Confidence){this.supportingEvidence=list(supporting);this.negativeEvidence=list(negative);this.contradictoryEvidence=list(contradictory);this.neutralEvidence=list(neutral);this.performanceReferences=list(performanceReferences.map(x=>required(x,"Performance reference")));this.patternReferences=list(patternReferences.map(x=>required(x,"Pattern reference")));this.recommendationReferences=list(recommendationReferences.map(x=>required(x,"Recommendation reference")));Object.freeze(this);} }
export class PredictionAccuracy { constructor(readonly status:PredictionAccuracyStatus,readonly measuredComparisons:number,readonly totalComparisons:number,readonly explanation:string,readonly confidence:Confidence){if(!Number.isInteger(measuredComparisons)||!Number.isInteger(totalComparisons)||measuredComparisons<0||totalComparisons<measuredComparisons)throw new ContinuousLearningException("Prediction accuracy counts are invalid");required(explanation,"Prediction accuracy explanation");Object.freeze(this);} }
export class RecommendationQualityEvaluation { readonly dimensions:Readonly<Record<string,string>>;constructor(readonly quality:RecommendationQuality,dimensions:Readonly<Record<string,string>>,readonly explanation:string){required(explanation,"Recommendation quality explanation");this.dimensions=Object.freeze({...dimensions});Object.freeze(this);} }
export interface LearningOutcomeProperties { learningId:LearningId;version:number;businessPackageId:BusinessPackageId;status:LearningStatus;direction:LearningDirection;summary:string;evidence:LearningEvidence;confidence:Confidence;predictionAccuracy:PredictionAccuracy;recommendationQuality:RecommendationQualityEvaluation;patternImplications?:readonly string[];capabilityImplications?:readonly string[];workflowImplications?:readonly string[];businessMemoryCandidate:boolean;evaluatedAt:Date; }
export class LearningOutcome { readonly patternImplications;readonly capabilityImplications;readonly workflowImplications;readonly #at:number;constructor(readonly properties:LearningOutcomeProperties){if(!Number.isInteger(properties.version)||properties.version<1)throw new ContinuousLearningException("Learning outcome version must be positive","INVALID_VERSION");required(properties.summary,"Learning summary");this.#at=instant(properties.evaluatedAt,"Learning evaluation timestamp");this.patternImplications=list(properties.patternImplications);this.capabilityImplications=list(properties.capabilityImplications);this.workflowImplications=list(properties.workflowImplications);Object.freeze(this);}get learningId(){return this.properties.learningId;}get version(){return this.properties.version;}get businessPackageId(){return this.properties.businessPackageId;}get status(){return this.properties.status;}get direction(){return this.properties.direction;}get evidence(){return this.properties.evidence;}get confidence(){return this.properties.confidence;}get predictionAccuracy(){return this.properties.predictionAccuracy;}get recommendationQuality(){return this.properties.recommendationQuality;}get businessMemoryCandidate(){return this.properties.businessMemoryCandidate;}get evaluatedAt(){return new Date(this.#at);} }
export class ConfidenceAdjustment { readonly supportingEvidence;readonly #at:number;constructor(readonly targetReference:string,readonly previousConfidence:Confidence,readonly proposedConfidence:Confidence,readonly rationale:string,supportingEvidence:readonly Evidence[],at:Date){required(targetReference,"Confidence target");required(rationale,"Confidence adjustment rationale");this.supportingEvidence=list(supportingEvidence);this.#at=instant(at,"Confidence adjustment timestamp");Object.freeze(this);}get adjustmentTimestamp(){return new Date(this.#at);} }
export class PatternReevaluationProposal { readonly supportingLearningEvidence;readonly contradictoryEvidence;readonly #at:number;constructor(readonly pattern:MarketPattern,supporting:readonly Evidence[],contradictory:readonly Evidence[],readonly reason:string,readonly urgency:string,at:Date){required(reason,"Pattern re-evaluation reason");required(urgency,"Pattern re-evaluation urgency");this.supportingLearningEvidence=list(supporting);this.contradictoryEvidence=list(contradictory);this.#at=instant(at,"Pattern re-evaluation timestamp");Object.freeze(this);}get timestamp(){return new Date(this.#at);} }
export class CapabilityLearning { readonly measuredOutcomes;readonly evidence;constructor(readonly learningId:LearningId,readonly capabilityReference:string,measuredOutcomes:readonly string[],readonly direction:LearningDirection,readonly confidence:Confidence,evidence:readonly Evidence[],readonly observationWindow:MeasurementWindow,readonly businessPackageId:BusinessPackageId){required(capabilityReference,"Capability reference");this.measuredOutcomes=list(measuredOutcomes);this.evidence=list(evidence);Object.freeze(this);} }
export class WorkflowLearning { readonly executionReferences;readonly measuredOutcomes;readonly successFailureEvidence;readonly efficiencyEvidence;readonly recommendationOutcomeReferences;constructor(readonly learningId:LearningId,readonly workflowReference:string,executions:readonly string[],outcomes:readonly string[],successFailure:readonly Evidence[],efficiency:readonly Evidence[],recommendations:readonly RecommendationOutcomeReference[],readonly confidence:Confidence,readonly direction:LearningDirection,readonly businessPackageId:BusinessPackageId,readonly reviewProposed:boolean){required(workflowReference,"Workflow reference");this.executionReferences=list(executions);this.measuredOutcomes=list(outcomes);this.successFailureEvidence=list(successFailure);this.efficiencyEvidence=list(efficiency);this.recommendationOutcomeReferences=list(recommendations);Object.freeze(this);} }
export class BusinessMemoryLearningCandidate { readonly contradictoryEvidence;constructor(readonly learningId:LearningId,readonly scope:string,readonly confidence:Confidence,readonly freshness:Freshness,contradictory:readonly Evidence[],readonly businessPackageId:BusinessPackageId,readonly provenance:Provenance,readonly rationale:string){required(scope,"Business Memory candidate scope");required(rationale,"Business Memory candidate rationale");this.contradictoryEvidence=list(contradictory);Object.freeze(this);}get approved(){return false;} }
