export type PerformanceView="overview"|"pinterest"|"blogs"|"search"|"ai"|"books"|"topics"|"paths"|"learning";
export type PerformancePeriod="7D"|"30D"|"90D"|"12M"|"ALL";
export type MetricState="Available"|"Unavailable"|"NotConnected"|"NoDataYet"|"Unknown";
export interface MeasuredMetric {readonly state:MetricState;readonly value?:number;readonly unit?:"count"|"percent"|"position";readonly previousChange?:number}
export interface TrendPoint {readonly at:string;readonly value:number}
export interface HeadingPerformance {readonly level:"H1"|"H2"|"H3";readonly pinCount:number;readonly impressions:number;readonly outboundClicks:number;readonly saves:number;readonly ctr:number;readonly impressionsPerPin:number;readonly clicksPerPin:number;readonly savesPerPin:number;readonly sampleState?:"Sufficient"|"LimitedData"}
export interface PerformancePin {readonly id:string;readonly title:string;readonly sourceHeading:string;readonly headingLevel:"H1"|"H2"|"H3";readonly blogId:string;readonly blogTitle:string;readonly canonicalQuestionId?:string;readonly topic:string;readonly language:string;readonly market:string;readonly publishedAt:string;readonly impressions:MeasuredMetric;readonly outboundClicks:MeasuredMetric;readonly saves:MeasuredMetric;readonly ctr:MeasuredMetric}
export interface BlogPerformance {readonly id:string;readonly title:string;readonly canonicalQuestion?:string;readonly language:string;readonly market:string;readonly publishedAt:string;readonly ageDays:number;readonly visits:MeasuredMetric;readonly searchReferrals:MeasuredMetric;readonly pinterestReferrals:MeasuredMetric;readonly bookInteractions:MeasuredMetric;readonly primaryCtaClicks:MeasuredMetric;readonly relatedBookClicks:MeasuredMetric;readonly visitsPerDay?:MeasuredMetric;readonly clicksPerThousandVisits?:MeasuredMetric}
export interface ContentPath {readonly id:string;readonly canonicalQuestion:string;readonly opportunity?:string;readonly blog?:string;readonly heading?:string;readonly pin?:string;readonly destination?:string;readonly impressions:MeasuredMetric;readonly outboundClicks:MeasuredMetric;readonly blogVisits:MeasuredMetric;readonly bookInteraction:MeasuredMetric;readonly attributionLabel:"Observed"|"Associated"|"Referred"|"Attributed according to tracking model"|"Unknown / Not attributable";readonly language:string;readonly market:string}
export interface LearningItem {readonly id:string;readonly version:number;readonly finding:string;readonly evidence:readonly string[];readonly contradictoryEvidence:readonly string[];readonly scope:string;readonly confidence:"Low"|"Moderate"|"High";readonly observedPeriod:string;readonly sampleSize:number;readonly sampleState:"Sufficient"|"Limited data";readonly capability:string;readonly status:"Observed"|"Emerging"|"Supported"|"Contradicted"|"Superseded"|"Insufficient Evidence"|"Archived";readonly recommendation?:{readonly current:string;readonly proposed:string;readonly status:"Awaiting CEO Decision";readonly settingsRoute:string}}
export interface PerformanceWorkspaceReadModel {readonly businessPackageId:string;readonly view:PerformanceView;readonly period:PerformancePeriod;readonly comparisonLabel?:string;readonly updatedAt:string;readonly providerFreshness:Readonly<Record<string,string|undefined>>;readonly metrics:Readonly<Record<string,MeasuredMetric>>;readonly trends:Readonly<Record<string,readonly TrendPoint[]>>;readonly headingPerformance:readonly HeadingPerformance[];readonly pins:readonly PerformancePin[];readonly blogs:readonly BlogPerformance[];readonly search:{readonly providers:readonly string[];readonly queries:readonly {query:string;blog?:string;classification:"Growing"|"Declining"|"New"|"Lost";impressions:MeasuredMetric;clicks:MeasuredMetric;ctr:MeasuredMetric}[]};readonly aiDiscovery:{readonly state:"Observed"|"Unavailable"|"NotConnected";readonly observations:readonly {provider:string;referencedUrl:string;blog?:string;observedAt:string;context?:string}[]};readonly books:readonly {book:string;edition:string;language:string;market:string;linkClicks:MeasuredMetric;primaryCtaClicks:MeasuredMetric;relatedBookClicks:MeasuredMetric;linkedBlogs:number;topReferrer?:string}[];readonly topics:readonly {topic:string;classification:"Growing"|"Strong"|"Weak"|"Emerging"|"Declining";questions:number;publishedBlogs:number;publishedPins:number;searchImpressions:MeasuredMetric;pinterestImpressions:MeasuredMetric;clicks:MeasuredMetric;blogVisits:MeasuredMetric;bookInteractions:MeasuredMetric}[];readonly paths:readonly ContentPath[];readonly learning:readonly LearningItem[]}
export interface PerformanceWorkspaceGateway {read(query:{businessPackageId:string;view:PerformanceView;period:PerformancePeriod;language?:string;market?:string;topic?:string;bookId?:string;blogId?:string;questionId?:string;sourceChannel?:string;page:number;pageSize:number}):Promise<PerformanceWorkspaceReadModel>}
