import { CredentialId } from "../credentials/CredentialVault.ts";
import { AuthenticationRecoveryRequest, AuthenticationRecoveryState, ExternalAuthenticationException, ExternalAuthenticationFailureType, ExternalAuthenticationId, ExternalAuthenticationRequest, ExternalAuthenticationResult, ExternalAuthenticationState, InterruptedOperationReference } from "./ExternalAuthenticationDomain.ts";

export interface AuthenticationHistoryQuery { authenticationId?:ExternalAuthenticationId; credentialId?:CredentialId; businessPackageId?:string; sourceAdapterReference?:string; workflowRunReference?:string; tcoTaskReference?:string; correlationIdentifier?:string; state?:ExternalAuthenticationState; failureType?:ExternalAuthenticationFailureType }

/** Append-only authentication history with stable timestamp, attempt and identifier ordering. */
export class ExternalAuthenticationRepository {
  readonly #requests=new Map<string,ExternalAuthenticationRequest>(); readonly #results:ExternalAuthenticationResult[]=[]; readonly #recoveries:AuthenticationRecoveryRequest[]=[]; readonly #states=new Map<string,ExternalAuthenticationState>();
  storeRequest(request:ExternalAuthenticationRequest):void { if(this.#requests.has(request.id.value))throw new ExternalAuthenticationException("Authentication request already exists","IMMUTABLE_HISTORY");this.#requests.set(request.id.value,request);this.#states.set(request.id.value,ExternalAuthenticationState.Requested); }
  request(id:ExternalAuthenticationId):ExternalAuthenticationRequest|undefined{return this.#requests.get(id.value);}
  storeResult(result:ExternalAuthenticationResult):void { if(this.#results.some(item=>item.authenticationId.equals(result.authenticationId)&&item.attemptNumber===result.attemptNumber))throw new ExternalAuthenticationException("Authentication attempt already exists","IMMUTABLE_HISTORY");this.#results.push(result);this.#states.set(result.authenticationId.value,result.state); }
  storeRecovery(request:AuthenticationRecoveryRequest):void { this.#recoveries.push(request); this.#states.set(request.authenticationId.value,stateForRecovery(request.state)); }
  transition(id:ExternalAuthenticationId,state:ExternalAuthenticationState):void { if(!this.#requests.has(id.value))throw new ExternalAuthenticationException("Authentication request not found","NOT_FOUND");this.#states.set(id.value,state); }
  currentState(id:ExternalAuthenticationId):ExternalAuthenticationState|undefined{return this.#states.get(id.value);}
  recoveryState(id:ExternalAuthenticationId):AuthenticationRecoveryState|undefined{return this.#recoveries.filter(x=>x.authenticationId.equals(id)).at(-1)?.state;}
  interruptedOperation(id:ExternalAuthenticationId):InterruptedOperationReference|undefined{return this.#requests.get(id.value)?.properties.interruptedOperation;}
  history(id:ExternalAuthenticationId):readonly ExternalAuthenticationResult[]{return this.query({authenticationId:id});}
  recoveries(id:ExternalAuthenticationId):readonly AuthenticationRecoveryRequest[]{return Object.freeze(this.#recoveries.filter(x=>x.authenticationId.equals(id)).sort((a,b)=>a.requestedAt.getTime()-b.requestedAt.getTime()));}
  query(query:AuthenticationHistoryQuery):readonly ExternalAuthenticationResult[]{return Object.freeze(this.#results.filter(result=>{const request=this.#requests.get(result.authenticationId.value);return(!query.authenticationId||result.authenticationId.equals(query.authenticationId))&&(!query.credentialId||result.credentialId.equals(query.credentialId))&&(!query.businessPackageId||result.businessPackageId.value===query.businessPackageId)&&(!query.sourceAdapterReference||request?.properties.sourceAdapterReference?.value===query.sourceAdapterReference)&&(!query.workflowRunReference||request?.properties.workflowRunReference===query.workflowRunReference)&&(!query.tcoTaskReference||request?.properties.tcoTaskReference===query.tcoTaskReference)&&(!query.correlationIdentifier||result.correlationIdentifier===query.correlationIdentifier)&&(!query.state||result.state===query.state)&&(!query.failureType||result.failure?.type===query.failureType);}).sort((a,b)=>a.occurredAt.getTime()-b.occurredAt.getTime()||a.attemptNumber-b.attemptNumber||a.authenticationId.value.localeCompare(b.authenticationId.value)));}
}
function stateForRecovery(state:AuthenticationRecoveryState):ExternalAuthenticationState { switch(state){case AuthenticationRecoveryState.WaitingForCEO:return ExternalAuthenticationState.WaitingForCredentialCorrection;case AuthenticationRecoveryState.RetryRequested:return ExternalAuthenticationState.RetryPending;case AuthenticationRecoveryState.FallbackPending:return ExternalAuthenticationState.FallbackPending;case AuthenticationRecoveryState.ResumeReady:return ExternalAuthenticationState.Completed;case AuthenticationRecoveryState.Cancelled:return ExternalAuthenticationState.Cancelled;default:return ExternalAuthenticationState.Failed;} }
