import { AuditEvent } from "../../core/platform/AuditEvent.ts";
import { AuditEventType } from "../../core/platform/AuditEventType.ts";
import type { AuditRecorder } from "../../core/platform/AuditRecorder.ts";
import { Event } from "../../core/platform/Event.ts";
import type { EventBus } from "../../core/platform/EventBus.ts";
import { EventContext } from "../../core/platform/EventContext.ts";
import { EventId } from "../../core/platform/EventId.ts";
import { EventType } from "../../core/platform/EventType.ts";
import type { SystemIdentity } from "../../core/platform/SystemIdentity.ts";
import { CredentialVault, CredentialVaultError, type UpdateCredentialInput, VaultStatus } from "../credentials/CredentialVault.ts";
import { AuthenticationRecoverability, AuthenticationRecoveryAction, AuthenticationRecoveryPolicy, AuthenticationRecoveryRequest, AuthenticationRecoveryState, AuthenticationRetryReference, CredentialCorrectionRequest, CredentialCorrectionResult, ExternalAuthenticationException, ExternalAuthenticationFailure, ExternalAuthenticationFailureType, ExternalAuthenticationRequest, ExternalAuthenticationResult, ExternalAuthenticationState, recoverabilityFor } from "./ExternalAuthenticationDomain.ts";
import type { ExternalAuthenticationProvider } from "./ExternalAuthenticationDomain.ts";
import { ExternalAuthenticationRepository } from "./ExternalAuthenticationRepository.ts";

export class ExternalAuthenticationService {
  #sequence=0;
  constructor(private readonly vault:CredentialVault,private readonly repository:ExternalAuthenticationRepository,private readonly recovery:AuthenticationRecoveryService,private readonly events?:EventBus,private readonly audit?:AuditRecorder,private readonly now=()=>new Date()){}
  createRequest(request:ExternalAuthenticationRequest,actor:SystemIdentity):void { this.repository.storeRequest(request);this.report("ExternalAuthenticationRequested",request,actor.id.value); }
  async authenticate(request:ExternalAuthenticationRequest,provider:ExternalAuthenticationProvider,actor:SystemIdentity):Promise<ExternalAuthenticationResult|undefined>{
    if(!this.repository.request(request.id))this.createRequest(request,actor);
    if(await this.vault.status()!==VaultStatus.Unlocked){this.repository.transition(request.id,ExternalAuthenticationState.CredentialRequired);this.report("CredentialAccessRequired",request,actor.id.value);return undefined;}
    try { this.vault.getMetadata(request.properties.credentialId.value,actor,request.properties.businessPackageId.value); }
    catch(error){if(error instanceof CredentialVaultError&&error.category==="Unauthorized")throw new ExternalAuthenticationException("Credential is not authorized for this Business Package","CROSS_PACKAGE_CREDENTIAL");throw error;}
    this.repository.transition(request.id,ExternalAuthenticationState.Authenticating);let active=true;const secret=this.vault.revealSecret(request.properties.credentialId.value,actor,request.properties.businessPackageId.value);
    try { const outcome=await provider.authenticate(request,{credentialId:request.properties.credentialId,use:consumer=>{if(!active)throw new ExternalAuthenticationException("Credential access window has closed","CREDENTIAL_BOUNDARY_CLOSED");return consumer(secret);}});const attempt=this.repository.history(request.id).length+1;const failure=outcome.successful?undefined:new ExternalAuthenticationFailure(outcome.failureType??ExternalAuthenticationFailureType.UnknownAuthenticationFailure,outcome.safeMessage??"External authentication failed",outcome.providerReference);const recoverability=failure?recoverabilityFor(failure.type):AuthenticationRecoverability.NonRecoverable;const result=new ExternalAuthenticationResult(request.id,attempt,request.properties.credentialId,request.properties.method,request.properties.businessPackageId,outcome.successful?ExternalAuthenticationState.Authenticated:ExternalAuthenticationState.Failed,outcome.successful,failure,recoverability,!outcome.successful&&recoverability!==AuthenticationRecoverability.NonRecoverable&&failure?.type!==ExternalAuthenticationFailureType.AccountLocked,this.now(),request.properties.correlationIdentifier,{providerReference:outcome.providerReference??"provider-independent"});this.repository.storeResult(result);if(result.successful){this.report(attempt>1?"AuthenticationRetrySucceeded":"ExternalAuthenticationSucceeded",request,actor.id.value);if(attempt>1)this.recovery.markResumeReady(request,actor.id.value);}else{this.report(attempt>1?"AuthenticationRetryFailed":"ExternalAuthenticationFailed",request,actor.id.value,failure?.type);this.recovery.evaluate(request,result,actor.id.value);}return result;
    } finally {active=false;}
  }
  retry(request:ExternalAuthenticationRequest,reference:AuthenticationRetryReference,provider:ExternalAuthenticationProvider,actor:SystemIdentity){if(reference.originalAuthenticationRequest.value!==request.id.value)throw new ExternalAuthenticationException("Retry does not reference original authentication");this.repository.transition(request.id,ExternalAuthenticationState.RetryPending);this.report("AuthenticationRetryRequested",request,actor.id.value);return this.authenticate(request,provider,actor);}
  state(request:ExternalAuthenticationRequest){return this.repository.currentState(request.id);} history(request:ExternalAuthenticationRequest){return this.repository.history(request.id);}
  private report(action:string,r:ExternalAuthenticationRequest,actor:string,failure?:ExternalAuthenticationFailureType){const sequence=++this.#sequence;const context:Record<string,string>={authenticationId:r.id.value,credentialId:r.properties.credentialId.value,businessPackageId:r.properties.businessPackageId.value,state:this.repository.currentState(r.id)??ExternalAuthenticationState.Requested,...(failure&&{failureType:failure})};const at=this.now();this.events?.publish(new Event({id:new EventId(`external-auth-${sequence}`),type:new EventType(action),timestamp:at,source:"ExternalAuthentication",correlationId:r.properties.correlationIdentifier,context:new EventContext(context)}));this.audit?.append(new AuditEvent({id:`external-auth-audit-${sequence}`,timestamp:at,type:AuditEventType.SecurityEvent,source:"ExternalAuthentication",action,result:failure??"Recorded",responsibleIdentity:actor,relatedTaskOrWorkflowId:r.properties.tcoTaskReference??r.properties.workflowRunReference,context}));}
}

export class AuthenticationRecoveryService {
  #sequence=0;
  constructor(private readonly vault:CredentialVault,private readonly repository:ExternalAuthenticationRepository,private readonly events?:EventBus,private readonly audit?:AuditRecorder,private readonly policy=AuthenticationRecoveryPolicy.UserCorrectionFirst,private readonly now=()=>new Date()){}
  evaluate(request:ExternalAuthenticationRequest,result:ExternalAuthenticationResult,actor:string):AuthenticationRecoveryRequest {if(!result.failure)throw new ExternalAuthenticationException("Successful authentication does not require recovery");const type=result.failure.type;let state=AuthenticationRecoveryState.Pending;let correction:CredentialCorrectionRequest|undefined;if(result.recoverability===AuthenticationRecoverability.UserCorrectable){state=AuthenticationRecoveryState.WaitingForCEO;correction=this.correctionRequest(request,type);this.report("CredentialCorrectionRequested",request,actor,type);}const recovery=new AuthenticationRecoveryRequest(request.id,this.policy,state,request.properties.interruptedOperation,this.now(),correction);this.repository.storeRecovery(recovery);if(result.recoverability===AuthenticationRecoverability.MFARequired){this.repository.transition(request.id,ExternalAuthenticationState.WaitingForMFA);this.report("MFARequired",request,actor,type);}else if(result.recoverability===AuthenticationRecoverability.ReauthorizationRequired){this.repository.transition(request.id,ExternalAuthenticationState.WaitingForReauthorization);this.report("ReauthorizationRequired",request,actor,type);}return recovery;}
  correctionRequest(request:ExternalAuthenticationRequest,type:ExternalAuthenticationFailureType):CredentialCorrectionRequest {const metadata={serviceReference:request.properties.sourceAdapterReference?.value??"External service",accountReference:request.properties.businessPackageId.value};return new CredentialCorrectionRequest(request.properties.credentialId,metadata.serviceReference,metadata.accountReference,type,actionsFor(type),request.properties.interruptedOperation,request.properties.businessPackageId,this.now());}
  async correct(request:ExternalAuthenticationRequest,action:AuthenticationRecoveryAction,update:UpdateCredentialInput,actor:SystemIdentity):Promise<CredentialCorrectionResult>{if(![AuthenticationRecoveryAction.ChangeUsername,AuthenticationRecoveryAction.ChangePassword,AuthenticationRecoveryAction.ChangeUsernameAndPassword].includes(action))throw new ExternalAuthenticationException("Action is not a credential correction");const allowed=actionsFor(this.repository.history(request.id).at(-1)?.failure?.type??ExternalAuthenticationFailureType.UnknownAuthenticationFailure);if(!allowed.includes(action))throw new ExternalAuthenticationException("Correction action is not allowed");const metadata=await this.vault.updateCredential(request.properties.credentialId.value,update,actor);const result=new CredentialCorrectionResult(request.id,request.properties.credentialId,action,metadata.updatedAt,this.now());this.report("CredentialCorrected",request,actor.id.value);return result;}
  retryReference(request:ExternalAuthenticationRequest,reason:string,credentialVersionReference:string):AuthenticationRetryReference {const previous=this.repository.history(request.id).at(-1)?.attemptNumber??0;return new AuthenticationRetryReference(request.id,previous,previous,reason,credentialVersionReference,this.now());}
  choose(request:ExternalAuthenticationRequest,action:AuthenticationRecoveryAction,actor:string):AuthenticationRecoveryState {if(action===AuthenticationRecoveryAction.UseFallback){this.repository.storeRecovery(new AuthenticationRecoveryRequest(request.id,this.policy,AuthenticationRecoveryState.FallbackPending,request.properties.interruptedOperation,this.now()));this.report("AuthenticationFallbackRequested",request,actor);return AuthenticationRecoveryState.FallbackPending;}if(action===AuthenticationRecoveryAction.CancelOperation){this.repository.storeRecovery(new AuthenticationRecoveryRequest(request.id,this.policy,AuthenticationRecoveryState.Cancelled,request.properties.interruptedOperation,this.now()));this.report("AuthenticationCancelled",request,actor);return AuthenticationRecoveryState.Cancelled;}throw new ExternalAuthenticationException("Recovery choice requires its controlled flow");}
  markResumeReady(request:ExternalAuthenticationRequest,actor:string):void {this.repository.storeRecovery(new AuthenticationRecoveryRequest(request.id,this.policy,AuthenticationRecoveryState.ResumeReady,request.properties.interruptedOperation,this.now()));this.report("AuthenticationRetrySucceeded",request,actor);}
  private report(action:string,r:ExternalAuthenticationRequest,actor:string,failure?:ExternalAuthenticationFailureType){const sequence=++this.#sequence;const context:Record<string,string>={authenticationId:r.id.value,credentialId:r.properties.credentialId.value,businessPackageId:r.properties.businessPackageId.value,...(failure&&{failureType:failure})};const at=this.now();this.events?.publish(new Event({id:new EventId(`auth-recovery-${sequence}`),type:new EventType(action),timestamp:at,source:"AuthenticationRecovery",correlationId:r.properties.correlationIdentifier,context:new EventContext(context)}));this.audit?.append(new AuditEvent({id:`auth-recovery-audit-${sequence}`,timestamp:at,type:AuditEventType.SecurityEvent,source:"AuthenticationRecovery",action,result:"Recorded",responsibleIdentity:actor,relatedTaskOrWorkflowId:r.properties.tcoTaskReference??r.properties.workflowRunReference,context}));}
}
function actionsFor(type:ExternalAuthenticationFailureType):readonly AuthenticationRecoveryAction[]{switch(type){case ExternalAuthenticationFailureType.InvalidUsername:return Object.freeze([AuthenticationRecoveryAction.ChangeUsername,AuthenticationRecoveryAction.Retry,AuthenticationRecoveryAction.UseFallback,AuthenticationRecoveryAction.CancelOperation]);case ExternalAuthenticationFailureType.InvalidPassword:return Object.freeze([AuthenticationRecoveryAction.ChangePassword,AuthenticationRecoveryAction.Retry,AuthenticationRecoveryAction.UseFallback,AuthenticationRecoveryAction.CancelOperation]);case ExternalAuthenticationFailureType.InvalidCredential:return Object.freeze([AuthenticationRecoveryAction.ChangeUsername,AuthenticationRecoveryAction.ChangePassword,AuthenticationRecoveryAction.ChangeUsernameAndPassword,AuthenticationRecoveryAction.Retry,AuthenticationRecoveryAction.UseFallback,AuthenticationRecoveryAction.CancelOperation]);case ExternalAuthenticationFailureType.MFARequired:return Object.freeze([AuthenticationRecoveryAction.ProvideMFA,AuthenticationRecoveryAction.UseFallback,AuthenticationRecoveryAction.CancelOperation]);default:return Object.freeze([AuthenticationRecoveryAction.Retry,AuthenticationRecoveryAction.Reauthorize,AuthenticationRecoveryAction.UseFallback,AuthenticationRecoveryAction.CancelOperation]);}}
