import { CredentialId } from "../credentials/CredentialVault.ts";
import { BusinessPackageId } from "../../intelligence/market/MarketIntelligenceDomain.ts";
import { MarketSourceAdapterId } from "../../intelligence/market/integration/MarketSourceIntegrationDomain.ts";

export class ExternalAuthenticationException extends Error {
  constructor(message: string, readonly code = "EXTERNAL_AUTHENTICATION_FAILURE") { super(message); this.name = "ExternalAuthenticationException"; }
}
const required = (value: string, field: string): string => { if (typeof value !== "string" || value.trim() === "") throw new ExternalAuthenticationException(`${field} is required`, "INVALID_REQUEST"); return value; };
const timestamp = (value: Date): Date => { if (!(value instanceof Date) || !Number.isFinite(value.getTime())) throw new ExternalAuthenticationException("Timestamp is invalid", "INVALID_REQUEST"); return new Date(value); };

export class ExternalAuthenticationId { readonly #value: string; constructor(value: string) { this.#value = required(value, "Authentication identifier"); Object.freeze(this); } get value() { return this.#value; } equals(other: ExternalAuthenticationId) { return other instanceof ExternalAuthenticationId && other.value === this.value; } }
export enum ExternalAuthenticationMethod { UsernamePassword="UsernamePassword", ApiKey="ApiKey", BearerToken="BearerToken", AccessToken="AccessToken", OAuth="OAuth", ClientCredential="ClientCredential", Session="Session", MFAProtected="MFAProtected", Other="Other" }
export enum ExternalAuthenticationState { Requested="Requested", CredentialRequired="CredentialRequired", Ready="Ready", Authenticating="Authenticating", Authenticated="Authenticated", Failed="Failed", WaitingForCredentialCorrection="WaitingForCredentialCorrection", WaitingForMFA="WaitingForMFA", WaitingForReauthorization="WaitingForReauthorization", RetryPending="RetryPending", FallbackPending="FallbackPending", Cancelled="Cancelled", Expired="Expired", Completed="Completed" }
export enum ExternalAuthenticationFailureType { InvalidUsername="InvalidUsername", InvalidPassword="InvalidPassword", InvalidCredential="InvalidCredential", ExpiredPassword="ExpiredPassword", ExpiredCredential="ExpiredCredential", ExpiredToken="ExpiredToken", MFARequired="MFARequired", AccountLocked="AccountLocked", PermissionDenied="PermissionDenied", ReauthorizationRequired="ReauthorizationRequired", AuthenticationUnavailable="AuthenticationUnavailable", RateLimited="RateLimited", ProviderMaintenance="ProviderMaintenance", NetworkUnavailable="NetworkUnavailable", UnsupportedAuthentication="UnsupportedAuthentication", ConfigurationFailure="ConfigurationFailure", UnknownAuthenticationFailure="UnknownAuthenticationFailure" }
export enum AuthenticationRecoverability { UserCorrectable="UserCorrectable", ReauthorizationRequired="ReauthorizationRequired", MFARequired="MFARequired", RetryableTemporary="RetryableTemporary", FallbackEligible="FallbackEligible", NonRecoverable="NonRecoverable", Unknown="Unknown" }
export enum AuthenticationRecoveryPolicy { UserCorrectionFirst="UserCorrectionFirst", AutomaticRetryThenCorrection="AutomaticRetryThenCorrection", AutomaticRetryThenFallback="AutomaticRetryThenFallback", CorrectionThenFallback="CorrectionThenFallback", ManualOnly="ManualOnly" }
export enum AuthenticationRecoveryAction { ChangeUsername="ChangeUsername", ChangePassword="ChangePassword", ChangeUsernameAndPassword="ChangeUsernameAndPassword", Retry="Retry", Reauthorize="Reauthorize", ProvideMFA="ProvideMFA", UseFallback="UseFallback", CancelOperation="CancelOperation" }
export enum AuthenticationRecoveryState { Pending="Pending", WaitingForCEO="WaitingForCEO", RetryRequested="RetryRequested", FallbackPending="FallbackPending", ResumeReady="ResumeReady", Cancelled="Cancelled" }

export interface InterruptedOperationProperties { workflowRunReference?:string; workflowStepReference?:string; tcoTaskReference?:string; marketCollectionRequestReference?:string; sourceAdapterReference?:MarketSourceAdapterId; businessPackageId:BusinessPackageId; correlationIdentifier:string }
export class InterruptedOperationReference { readonly properties: Readonly<InterruptedOperationProperties>; constructor(properties:InterruptedOperationProperties) { required(properties.correlationIdentifier,"Correlation identifier"); if (!(properties.businessPackageId instanceof BusinessPackageId)) throw new ExternalAuthenticationException("Business Package is invalid"); this.properties=Object.freeze({...properties}); Object.freeze(this); } }
export interface ExternalAuthenticationRequestProperties { id:ExternalAuthenticationId; credentialId:CredentialId; method:ExternalAuthenticationMethod; businessPackageId:BusinessPackageId; sourceAdapterReference?:MarketSourceAdapterId; requestedCapability:string; workflowRunReference?:string; tcoTaskReference?:string; sourceRequestReference?:string; correlationIdentifier:string; requestingAuthorityReference:string; requestedAt:Date; interruptedOperation:InterruptedOperationReference }
export class ExternalAuthenticationRequest { readonly requestedAt:Date; constructor(readonly properties:ExternalAuthenticationRequestProperties) { if (!(properties.id instanceof ExternalAuthenticationId)||!(properties.credentialId instanceof CredentialId)||!(properties.businessPackageId instanceof BusinessPackageId)||!(properties.interruptedOperation instanceof InterruptedOperationReference)) throw new ExternalAuthenticationException("Authentication request references are invalid", "INVALID_REQUEST"); required(properties.requestedCapability,"Requested capability"); required(properties.correlationIdentifier,"Correlation identifier"); required(properties.requestingAuthorityReference,"Requesting authority"); this.requestedAt=timestamp(properties.requestedAt); Object.freeze(this); } get id(){return this.properties.id;} }

export class ExternalAuthenticationFailure { constructor(readonly type:ExternalAuthenticationFailureType, readonly safeMessage:string, readonly providerReference?:string) { if (!Object.values(ExternalAuthenticationFailureType).includes(type)) throw new ExternalAuthenticationException("Failure classification is invalid"); required(safeMessage,"Safe failure message"); Object.freeze(this); } }
export class ExternalAuthenticationResult { readonly occurredAt:Date; readonly provenance:Readonly<Record<string,string>>; constructor(readonly authenticationId:ExternalAuthenticationId,readonly attemptNumber:number,readonly credentialId:CredentialId,readonly method:ExternalAuthenticationMethod,readonly businessPackageId:BusinessPackageId,readonly state:ExternalAuthenticationState,readonly successful:boolean,readonly failure:ExternalAuthenticationFailure|undefined,readonly recoverability:AuthenticationRecoverability,readonly retryEligible:boolean,occurredAt:Date,readonly correlationIdentifier:string,provenance:Record<string,string>={}) { if(!Number.isInteger(attemptNumber)||attemptNumber<1||successful===Boolean(failure)||successful&&state!==ExternalAuthenticationState.Authenticated) throw new ExternalAuthenticationException("Authentication result is inconsistent"); this.occurredAt=timestamp(occurredAt);required(correlationIdentifier,"Correlation identifier");this.provenance=Object.freeze({...provenance});Object.freeze(this); } }

export interface ProviderAuthenticationOutcome { readonly successful:boolean; readonly failureType?:ExternalAuthenticationFailureType; readonly safeMessage?:string; readonly providerReference?:string; readonly sessionReference?:AuthenticationSessionReference }
/** Material is visible only within this provider call and must never be retained or returned. */
export interface ControlledCredentialMaterial { readonly credentialId:CredentialId; readonly use:<T>(consumer:(secret:string)=>T)=>T }
export interface ExternalAuthenticationProvider { authenticate(request:ExternalAuthenticationRequest, credential:ControlledCredentialMaterial):Promise<ProviderAuthenticationOutcome> }
export class CredentialCorrectionRequest { readonly requestedAt:Date; readonly allowedActions:readonly AuthenticationRecoveryAction[]; constructor(readonly credentialId:CredentialId,readonly serviceReference:string,readonly accountReference:string,readonly failureType:ExternalAuthenticationFailureType,actions:readonly AuthenticationRecoveryAction[],readonly interruptedOperation:InterruptedOperationReference,readonly businessPackageId:BusinessPackageId,requestedAt:Date) { required(serviceReference,"Service reference");required(accountReference,"Account reference");this.allowedActions=Object.freeze([...actions]);this.requestedAt=timestamp(requestedAt);Object.freeze(this); } }
export class CredentialCorrectionResult { readonly correctedAt:Date; constructor(readonly authenticationId:ExternalAuthenticationId,readonly credentialId:CredentialId,readonly action:AuthenticationRecoveryAction,readonly credentialVersionReference:string,correctedAt:Date){required(credentialVersionReference,"Credential version reference");this.correctedAt=timestamp(correctedAt);Object.freeze(this);} }
export class AuthenticationRetryReference { readonly requestedAt:Date; constructor(readonly originalAuthenticationRequest:ExternalAuthenticationId,readonly previousAttempt:number,readonly retryNumber:number,readonly reason:string,readonly credentialVersionReference:string,requestedAt:Date){if(!Number.isInteger(previousAttempt)||!Number.isInteger(retryNumber)||retryNumber<1)throw new ExternalAuthenticationException("Retry reference is invalid");required(reason,"Retry reason");required(credentialVersionReference,"Credential version reference");this.requestedAt=timestamp(requestedAt);Object.freeze(this);} }
export class AuthenticationSessionReference { readonly expiresAt?:Date; constructor(readonly opaqueReference:string,readonly providerReference:string,readonly businessPackageId:BusinessPackageId,expiresAt?:Date){required(opaqueReference,"Opaque session reference");required(providerReference,"Provider reference");this.expiresAt=expiresAt&&timestamp(expiresAt);Object.freeze(this);} }
export class AuthenticationRecoveryRequest { readonly requestedAt:Date; constructor(readonly authenticationId:ExternalAuthenticationId,readonly policy:AuthenticationRecoveryPolicy,readonly state:AuthenticationRecoveryState,readonly interruptedOperation:InterruptedOperationReference,requestedAt:Date,readonly correctionRequest?:CredentialCorrectionRequest){this.requestedAt=timestamp(requestedAt);Object.freeze(this);} }

export function recoverabilityFor(type:ExternalAuthenticationFailureType):AuthenticationRecoverability { if([ExternalAuthenticationFailureType.InvalidUsername,ExternalAuthenticationFailureType.InvalidPassword,ExternalAuthenticationFailureType.InvalidCredential,ExternalAuthenticationFailureType.ExpiredPassword,ExternalAuthenticationFailureType.ExpiredCredential].includes(type))return AuthenticationRecoverability.UserCorrectable;if(type===ExternalAuthenticationFailureType.MFARequired)return AuthenticationRecoverability.MFARequired;if([ExternalAuthenticationFailureType.ExpiredToken,ExternalAuthenticationFailureType.ReauthorizationRequired,ExternalAuthenticationFailureType.PermissionDenied].includes(type))return AuthenticationRecoverability.ReauthorizationRequired;if([ExternalAuthenticationFailureType.AuthenticationUnavailable,ExternalAuthenticationFailureType.RateLimited,ExternalAuthenticationFailureType.ProviderMaintenance,ExternalAuthenticationFailureType.NetworkUnavailable].includes(type))return AuthenticationRecoverability.RetryableTemporary;if(type===ExternalAuthenticationFailureType.AccountLocked)return AuthenticationRecoverability.FallbackEligible;if([ExternalAuthenticationFailureType.UnsupportedAuthentication,ExternalAuthenticationFailureType.ConfigurationFailure].includes(type))return AuthenticationRecoverability.NonRecoverable;return AuthenticationRecoverability.Unknown; }
