import assert from "node:assert/strict";
import test from "node:test";
import {Event} from "../../src/core/platform/Event.ts";
import {EventContext} from "../../src/core/platform/EventContext.ts";
import {EventId} from "../../src/core/platform/EventId.ts";
import {EventType} from "../../src/core/platform/EventType.ts";
import {BusinessPackageId} from "../../src/intelligence/market/MarketIntelligenceDomain.ts";
import {BlogPinterestCandidateSourceType,BlogPinterestPromotionId,BlogPinterestPromotionPolicyRepository,BlogPinterestPromotionService,BlogPinterestPromotionState,BlogPublishedPinterestPromotionListener,type BlogPinterestCreationPlanDemand,type PublishedBlogPromotionSource} from "../../src/integrations/pinterest/BlogPinterestPromotionWorkflow.ts";
import {PinterestContentIntent,PinterestDestinationType} from "../../src/integrations/pinterest/PinterestCreationPlanningDomain.ts";

const at=new Date("2026-08-09T12:00:00Z"),url="https://alivo.example/de/blog/muedigkeit-nach-dem-essen";
function source(overrides:Partial<PublishedBlogPromotionSource>={}):PublishedBlogPromotionSource{return {publishedBlogReference:"published-blog-42",actualCanonicalUrl:url,businessPackageId:new BusinessPackageId("ALIVO"),language:"de",market:"DE",h1:"Warum bin ich nach dem Essen immer müde?",headings:[{headingId:"h1",level:"H1",text:"Warum bin ich nach dem Essen immer müde?",sectionReference:"section:h1",evidenceReferences:["question-1"]},{headingId:"h2-insulin",level:"H2",text:"Welche Rolle spielt Insulin?",sectionReference:"section:insulin",evidenceReferences:["source-insulin"]},{headingId:"h3-carbs",level:"H3",text:"Warum schnelle Kohlenhydrate Müdigkeit verstärken können",sectionReference:"section:carbs",evidenceReferences:["source-carbs"]},{headingId:"h2-nav",level:"H2",text:"Inhalt",sectionReference:"section:contents",evidenceReferences:[]},{headingId:"h2-duplicate",level:"H2",text:"Welche Rolle spielt Insulin!",sectionReference:"section:insulin-2",evidenceReferences:["source-insulin"]},{headingId:"h2-energy",level:"H2",text:"Wie stabiler Blutzucker die Energie beeinflusst",sectionReference:"section:energy",evidenceReferences:["source-energy"]}],draftId:"draft-1",draftVersion:4,publicationPackageId:"package-1",publicationPackageVersion:2,recommendationId:"recommendation-1",recommendationVersion:3,opportunityReferences:["opportunity-1"],canonicalQuestionId:"question-1",publishedAt:at,...overrides};}
function setup(s=source()){const demands:BlogPinterestCreationPlanDemand[]=[],events:string[]=[];const policies=new BlogPinterestPromotionPolicyRepository(),service=new BlogPinterestPromotionService(policies,{request:d=>{demands.push(d);return "Accepted";}},undefined,{publish:(event:any)=>{events.push(event.type.value);return [];}} as any,undefined,()=>at);return {s,demands,events,policies,service};}
function event(name:string){return new Event({id:new EventId(`event:${name}`),type:new EventType(name),timestamp:at,source:"test",correlationId:"correlation-56",context:new EventContext({})});}

test("only confirmed BlogPublished creates governed, idempotent promotion demand",()=>{const x=setup();let resolves=0;const listener=new BlogPublishedPinterestPromotionListener(()=>{resolves++;return x.s;},x.service);for(const name of ["Draft","ApprovedForPublishing","ReadyForWordPressPublishing","DryRun","VerificationRequired","BlogPublishFailed","Cancelled"])listener.handle(event(name));assert.equal(resolves,0);listener.handle(event("BlogPublished"));listener.handle(event("BlogPublished"));assert.equal(resolves,2);assert.equal(x.service.repository.all().length,1);assert.equal(x.demands.length,3);assert.ok(x.events.includes("BlogPinterestPromotionRequested"));assert.ok(x.events.includes("BlogPinterestPromotionReady"));});

test("preserves actual destination, package, locale, lineage, authority, and existing production pipeline",()=>{const x=setup();const original=structuredClone({headings:x.s.headings,h1:x.s.h1});const result=x.service.promote(x.s,"correlation-56");assert.equal(result.state,BlogPinterestPromotionState.ReadyForPinterestPlanning);for(const demand of x.demands){assert.equal(demand.destination.type,PinterestDestinationType.ExistingArticle);assert.equal(demand.destination.canonicalUrl,url);assert.notEqual(demand.destination.canonicalUrl,"https://alivo.example/books");assert.equal(demand.businessPackageId.value,"ALIVO");assert.equal(demand.language,"de");assert.equal(demand.market,"DE");assert.equal(demand.publishedBlogReference,"published-blog-42");assert.equal(demand.draftVersion,4);assert.equal(demand.publicationPackageVersion,2);assert.equal(demand.recommendationId,"recommendation-1");assert.equal(demand.contentIntent,PinterestContentIntent.ArticleDiscovery);assert.equal(demand.authorization.channel,"Pinterest");assert.equal(demand.authorization.destinationUrl,url);assert.deepEqual(demand.pipeline,["PinterestCreationPlan","PinterestCopyProduction","PinterestVisualProduction","PinterestCreativeAssembly","PinterestPrePublishValidation","PinterestQueue","PinterestTimingIntelligence","PinterestScheduler","PinterestPublisher","PinterestPerformanceLearning"]);}assert.deepEqual({headings:x.s.headings,h1:x.s.h1},original);});

test("H1 is mandatory while H2/H3 are ranked, diverse angle sources and extras remain reserved",()=>{const x=setup(),result=x.service.promote(x.s,"correlation-56"),plan=result.plan!;assert.equal(plan.selected[0]?.heading.sourceType,BlogPinterestCandidateSourceType.H1);assert.equal(plan.selected[0]?.heading.headingId,"h1");assert.equal(plan.selected[0]?.heading.headingText,x.s.h1);assert.ok(plan.selected.some(x=>x.heading.sourceType===BlogPinterestCandidateSourceType.H2));assert.ok(plan.selected.some(x=>x.heading.sourceType===BlogPinterestCandidateSourceType.H3));assert.ok(plan.remainingCandidates.some(x=>x.heading.headingId==="h2-energy"));assert.ok(plan.diversity.explanations.every(Boolean));assert.equal(x.demands.length,3);assert.equal(new Set(x.demands.map(x=>x.candidate.heading.headingText)).size,3);});

test("quality and semantic diversity outrank quota without filler",()=>{const sparse=source({headings:[{headingId:"h1",level:"H1",text:"Warum bin ich nach dem Essen immer müde?",sectionReference:"s1",evidenceReferences:["q"]},{headingId:"nav",level:"H2",text:"Inhalt",sectionReference:"s2",evidenceReferences:[]},{headingId:"copy",level:"H2",text:"Warum bin ich nach dem Essen immer müde!",sectionReference:"s3",evidenceReferences:["q"]}]});const x=setup(sparse),result=x.service.promote(sparse,"correlation-56");assert.equal(result.state,BlogPinterestPromotionState.PartiallyReady);assert.equal(result.plan?.selected.length,1);assert.equal(result.plan?.diversity.sufficient,false);assert.ok(result.plan?.diversity.rejectedCandidateIds.includes("heading:copy"));assert.ok(x.events.includes("BlogPinterestCreativeDiversityInsufficient"));});

test("disabled and held policies leave Blog publication successful and create no planning demand",()=>{for(const mode of ["disabled","held"]){const x=setup();x.policies.set({businessPackageId:new BusinessPackageId("ALIVO"),channel:"Pinterest",enabled:mode!=="disabled",minimumPinsPerPublishedBlog:3,authorityReference:"ceo:56",heldPublishedBlogReferences:mode==="held"?[x.s.publishedBlogReference]:[]},{role:"CEO",authorityReference:"ceo:settings"},at);const result=x.service.promote(x.s,"correlation-56");assert.equal(result.state,mode==="held"?BlogPinterestPromotionState.Held:BlogPinterestPromotionState.Disabled);assert.equal(x.demands.length,0);}});

test("ALIVO minimum is persisted channel configuration, configurable only by CEO",()=>{const policies=new BlogPinterestPromotionPolicyRepository();assert.equal(policies.get(new BusinessPackageId("ALIVO"))?.minimumPinsPerPublishedBlog,3);assert.throws(()=>policies.set({businessPackageId:new BusinessPackageId("ALIVO"),channel:"Pinterest",enabled:true,minimumPinsPerPublishedBlog:4,authorityReference:"ceo",heldPublishedBlogReferences:[]},{role:"Agent",authorityReference:"agent"}),/CEO authority/);policies.set({businessPackageId:new BusinessPackageId("ALIVO"),channel:"Pinterest",enabled:true,minimumPinsPerPublishedBlog:4,authorityReference:"ceo",heldPublishedBlogReferences:[]},{role:"CEO",authorityReference:"ceo:change"},at);const x=setup();const service=new BlogPinterestPromotionService(policies,{request:d=>{x.demands.push(d);return "Accepted";}});const result=service.promote(x.s,"correlation-56");assert.equal(result.request.configuredMinimumPins,4);assert.equal(result.plan?.selected.length,4);assert.equal(policies.changes()[0]?.authority,"ceo:change");});

test("fallbacks require published grounding and preserve source type",()=>{const s=source({headings:[source().headings[0]!],relatedQuestions:[{id:"answered",text:"Wie hängt Verdauung mit Energie zusammen?",answeredInArticle:true,sectionReference:"s-answer",evidenceReferences:["paragraph-4"]},{id:"unanswered",text:"Hilft ein Medikament?",answeredInArticle:false,sectionReference:"none",evidenceReferences:[]}],articleInsights:[{id:"grounded",text:"Protein verändert den Verlauf der Energiekurve",groundedInArticle:true,sectionReference:"p-8",evidenceReferences:["paragraph-8"]},{id:"invented",text:"Eine unbelegte Behauptung",groundedInArticle:false,sectionReference:"none",evidenceReferences:[]}]});const x=setup(s),result=x.service.promote(s,"correlation-56");const sources=result.plan?.selected.map(x=>x.heading.sourceType);assert.ok(sources?.includes(BlogPinterestCandidateSourceType.RelatedQuestion));assert.ok(sources?.includes(BlogPinterestCandidateSourceType.PublishedArticleInsight));assert.equal(result.plan?.selected.some(x=>x.heading.headingId==="unanswered"||x.heading.headingId==="invented"),false);});

test("queue pressure is partial but retains candidates for the authoritative scheduler",()=>{const statuses:("Accepted"|"WaitingForQueueCapacity")[]=["Accepted","WaitingForQueueCapacity","Accepted"],x=setup();const service=new BlogPinterestPromotionService(x.policies,{request:d=>{x.demands.push(d);return statuses.shift()!;}}),result=service.promote(x.s,"correlation-56");assert.equal(result.state,BlogPinterestPromotionState.PartiallyReady);assert.equal(result.plan?.selected.length,3);assert.ok(result.planningStatuses.includes("WaitingForQueueCapacity"));assert.equal("publish" in service,false);assert.equal("schedule" in service,false);assert.equal(new BlogPinterestPromotionId("trace").value,"trace");});
