import assert from "node:assert/strict";
import {test} from "node:test";
import {InMemoryRepository} from "../../src/core/platform/Repository.ts";
import {BusinessPackageId, Freshness, FreshnessStatus, MarketSourceId, Provenance} from "../../src/intelligence/market/MarketIntelligenceDomain.ts";
import {MetricAvailability} from "../../src/business/market/performance/PerformanceIntelligenceDomain.ts";
import {PerformanceRepository} from "../../src/business/market/performance/PerformanceRepository.ts";
import {PerformanceIntelligenceService} from "../../src/business/market/performance/PerformanceIntelligenceService.ts";
import {AIDiscoveryResultType, BlogAIDiscoveryObservation, BlogBookLinkInteraction, BlogFeedbackChannel, BlogFeedbackLineage, BlogFeedbackSourceCategory, BlogMeasurementWindow, BlogPinterestReferralObservation, BlogSearchDiscoveryObservation, BlogSearchQueryObservation, BookPlacementType, MeasurementMaturity, PinterestHeadingSource, SearchIndexingState, SearchQueryMatch} from "../../src/business/market/blog/feedback/BlogPerformanceFeedbackDomain.ts";
import {BlogPerformanceFeedbackService} from "../../src/business/market/blog/feedback/BlogPerformanceFeedbackService.ts";

const at=new Date("2026-08-09T12:00:00Z"),pkg=new BusinessPackageId("ALIVO"),source=new MarketSourceId("fake-analytics"),provenance=new Provenance("deterministic fake provider",at,source,["fixture:57"]),freshness=new Freshness(FreshnessStatus.Current,at);
const lineage=new BlogFeedbackLineage({publishedBlogReference:"published:57",wordpressPostId:"wp-57",actualCanonicalUrl:"https://alivo.example/de/wie-schläft-man-besser",draftId:"draft-57",draftVersion:4,publicationPackageId:"package-57",publicationPackageVersion:3,contentCreationPlanId:"plan-57",contentCreationPlanVersion:2,recommendationId:"recommendation-57",recommendationVersion:5,ceoApprovalReference:"ceo:57",blogOpportunityId:"opportunity-57",canonicalQuestionId:"question-57",canonicalQuestionText:"Wie schläft man besser?",questionClusterId:"cluster-sleep",questionPatternId:"pattern-how",headings:[{headingId:"h1",level:"H1",text:"Wie schläft man besser?"},{headingId:"h2",level:"H2",text:"Welche Abendroutine hilft?"},{headingId:"h3",level:"H3",text:"Wann sollte man lesen?"}],businessPackageId:pkg,market:"DE",language:"de",publishedAt:new Date("2026-08-01T08:00:00Z")});
function setup(){const events:string[]=[],audits:string[]=[];const performance=new PerformanceIntelligenceService(new PerformanceRepository(new InMemoryRepository()));return{events,audits,performance,service:new BlogPerformanceFeedbackService(lineage,performance,{emit:n=>events.push(n)},{record:a=>audits.push(a)})};}
const window=(id="Early",maturity=MeasurementMaturity.Provisional)=>new BlogMeasurementWindow(id,new Date("2026-08-01T08:00:00Z"),at,maturity);
const provider=(record="site-1",metrics=[{name:"PageViews",value:0,unit:"count",availability:MetricAvailability.Available}])=>({provider:"VendorNeutralAnalytics",providerRecordId:record,category:BlogFeedbackSourceCategory.SiteAnalytics,channel:BlogFeedbackChannel.Site,observedAt:at,window:window(),metrics,provenance,freshness});

test("only confirmed Published Blogs are eligible and exact immutable lineage survives",()=>{assert.equal(BlogPerformanceFeedbackService.eligible("Published",lineage),true);for(const state of ["DryRun","Failed","VerificationRequired","Cancelled","Draft"])assert.equal(BlogPerformanceFeedbackService.eligible(state,lineage),false);assert.equal(lineage.properties.actualCanonicalUrl,"https://alivo.example/de/wie-schläft-man-besser");assert.equal(lineage.properties.draftVersion,4);assert.equal(lineage.properties.publicationPackageVersion,3);assert.equal(lineage.properties.canonicalQuestionText,"Wie schläft man besser?");assert.equal(lineage.headings.length,3);assert.equal(Object.isFrozen(lineage.headings),true);});
test("site observations normalize through existing Performance Intelligence, keep zero distinct from unavailable, lag and immutable windows",()=>{const x=setup(),zero=x.service.collect(provider())!,unavailable=x.service.collect(provider("site-2",[{name:"Sessions",unit:"count",availability:MetricAvailability.Unavailable}]))!;assert.equal(zero.metrics[0].value,0);assert.equal(unavailable.metrics[0].value,undefined);assert.equal(unavailable.metrics[0].availability,MetricAvailability.Unavailable);assert.equal(x.performance.history().observations.length,2);assert.equal(zero.window.start.toISOString(),"2026-08-01T08:00:00.000Z");assert.ok(x.events.includes("BlogPerformanceObservationCreated"));assert.equal(x.audits.length,2);});
test("multiple measurement windows accumulate and duplicate provider records do not inflate evidence",()=>{const x=setup();x.service.collect(provider("daily"));assert.equal(x.service.collect(provider("daily")),undefined);x.service.collect({...provider("month"),window:new BlogMeasurementWindow("30Day",new Date("2026-08-01"),new Date("2026-08-31"),MeasurementMaturity.Mature)});assert.equal(x.performance.history().observations.length,2);});
test("search sources are provider-independent, preserve original queries and explicit indexing states",()=>{const x=setup();for(const [providerName,state] of [["SearchEngineA",SearchIndexingState.Indexed],["SearchEngineB",SearchIndexingState.NotIndexed],["FutureSearch",SearchIndexingState.Unknown]] as const)x.service.observeSearch(new BlogSearchDiscoveryObservation(providerName,state,[new BlogSearchQueryObservation("Wie schläft man BESSER?",SearchQueryMatch.ExactCanonicalQuestion,true)],undefined,["position not supplied"],at));assert.equal(x.service.readModel().search.observedQueries[0],"Wie schläft man BESSER?");assert.equal(x.service.readModel().search.indexed,SearchIndexingState.Unknown);assert.equal(x.service.readModel().search.canonicalQuestionMatches,3);assert.equal(x.service.matchQuery("Wie schläft man besser?"),SearchQueryMatch.ExactCanonicalQuestion);assert.equal(x.service.matchQuery("Besser schlafen",["Besser schlafen"]),SearchQueryMatch.CloseVariant);assert.equal(x.service.matchQuery("Welche Abendroutine hilft?",[],["Welche Abendroutine hilft?"]),SearchQueryMatch.RelatedIntent);assert.equal(x.service.matchQuery("Kaffee kaufen"),SearchQueryMatch.Unrelated);});
test("search ranking is never inferred from traffic and genuine search demand remains explicit",()=>{const x=setup();x.service.collect(provider());const q=new BlogSearchQueryObservation("echte Suchanfrage",SearchQueryMatch.RelatedIntent,true,"h2");const search=x.service.observeSearch(new BlogSearchDiscoveryObservation("IndependentSearch",SearchIndexingState.Discovered,[q],undefined,["indexing only"],at));assert.equal(search.averagePosition,undefined);assert.equal(search.queries[0].humanDemandEvidence,true);assert.equal(search.queries[0].headingId,"h2");});
test("AI discovery is observation-only, provider-independent, fresh, limited, and never human demand",()=>{const x=setup();for(const [providerName,result,evidence] of [["AnswerEngineA",AIDiscoveryResultType.CitedSource,"citation:1"],["AnswerEngineB",AIDiscoveryResultType.NotObservedInThisMeasurement,undefined],["FutureEngine",AIDiscoveryResultType.UnavailableToVerify,undefined]] as const){const observation=x.service.observeAI(new BlogAIDiscoveryObservation(providerName,"controlled manual sample","Wie schläft man besser?",result,evidence,at,[result===AIDiscoveryResultType.UnavailableToVerify?"provider unavailable":"query set limited"]));assert.equal(observation.humanDemandEvidence,false);}const read=x.service.readModel().aiDiscovery;assert.deepEqual(read.observedProviders,["AnswerEngineA","AnswerEngineB","FutureEngine"]);assert.equal(read.latestObservation?.toISOString(),at.toISOString());assert.equal(read.evidenceCount,1);assert.ok(!Object.keys(read).some(x=>/score|probability|authority|trust/i.test(x)));assert.throws(()=>new BlogAIDiscoveryObservation("x","sample",undefined,AIDiscoveryResultType.Unknown,undefined,at,[]),/limitations/);});
test("book placements preserve exact lineage, clicks are not sales, and unavailable conversion is unknown",()=>{const x=setup();for(const [placement,clicks,heading] of [[BookPlacementType.RelatedBook1,2,"h2"],[BookPlacementType.RelatedBook2,0,"h3"],[BookPlacementType.PrimaryBookCTA,5,undefined]] as const){const interaction=x.service.observeBook(new BlogBookLinkInteraction(`book-${placement}`,"edition-de",placement,`https://books.example/${placement}`,clicks,MetricAvailability.Available,heading));assert.equal(interaction.sales,undefined);}const read=x.service.readModel().books;assert.deepEqual([read.relatedBook1,read.relatedBook2,read.primaryBookCTA],[2,0,5]);assert.equal(setup().service.readModel().books.availability,MetricAvailability.Unavailable);});
test("Pinterest referrals preserve Pin, candidate, H1/H2/H3 lineage and stay distinct from Search",()=>{const x=setup();for(const heading of [PinterestHeadingSource.H1,PinterestHeadingSource.H2,PinterestHeadingSource.H3])x.service.observePinterest(new BlogPinterestReferralObservation(`pin-${heading}`,`candidate-${heading}`,heading,lineage.properties.actualCanonicalUrl,3,2));x.service.observeSearch(new BlogSearchDiscoveryObservation("Search",SearchIndexingState.Indexed,[],undefined,["query data unavailable"],at));assert.ok(x.service.readModel().channels.includes(BlogFeedbackChannel.Pinterest));assert.ok(x.service.readModel().channels.includes(BlogFeedbackChannel.Search));assert.throws(()=>x.service.observePinterest(new BlogPinterestReferralObservation("pin","candidate",PinterestHeadingSource.H1,"https://other.example",1,1)),/does not match/);});
test("Business Package, market and language remain isolated and public service has no mutation authority",()=>{const x=setup(),read=x.service.readModel();assert.equal(lineage.properties.businessPackageId.value,"ALIVO");assert.deepEqual(read.search.markets,["DE"]);assert.equal(lineage.properties.language,"de");assert.deepEqual(Object.getOwnPropertyNames(BlogPerformanceFeedbackService.prototype).filter(x=>/rewrite|publish|unpublish|delete|library|trust|credential|password/i.test(x)),[]);});
test("deterministic fakes require no network and events/audit contain no secret-bearing provider payload",()=>{const x=setup();x.service.collect(provider());const serialized=JSON.stringify({events:x.events,audits:x.audits});assert.doesNotMatch(serialized,/authorization|credential|secret|token/i);assert.ok(x.events.includes("BlogPerformanceCollectionStarted"));});
