import assert from "node:assert/strict";import test from "node:test";
import {BusinessPackageId} from "../../src/intelligence/market/MarketIntelligenceDomain.ts";
import {CEODecision,RecommendationStatus} from "../../src/business/recommendations/RecommendationDomain.ts";
import {CEORecommendationDecisionType} from "../../src/business/recommendations/CEORecommendationReviewDomain.ts";
import {BlogRecommendationAction} from "../../src/business/market/blog/recommendations/BlogRecommendationEvaluationDomain.ts";
import {LibraryBookId,LibraryContentEquivalence,LibraryEdition,LibraryEditionId,LibraryEditionLanguage,LibraryEditionLinkSet,LibraryEditionStatus,LibraryLinkStatus} from "../../src/business/library/LibraryDomain.ts";
import {BlogAIDiscoveryRequirement,BlogArticleObjective,BlogArticleScope,BlogBookLinkStatus,BlogContentCreationPlanId,BlogContentCreationPlanRequest,BlogContentCreationPlanState,BlogDirectAnswerObjective,BlogHeadingCandidate,BlogHeadingEvidence,BlogHeadingLevel,BlogHeadingPlan,BlogInternalLinkRequirement,BlogKnowledgeReadiness,BlogKnowledgeRequirement,BlogSearchDiscoveryRequirement,BlogSourceRequirement} from "../../src/business/market/blog/planning/BlogContentCreationPlanDomain.ts";
import {BlogContentCreationPlanRepository} from "../../src/business/market/blog/planning/BlogContentCreationPlanRepository.ts";import {BlogContentCreationPlanService} from "../../src/business/market/blog/planning/BlogContentCreationPlanService.ts";

const at=new Date("2026-08-09T12:00:00Z"),pkg=new BusinessPackageId("ALIVO"),question="Why am I tired after eating?";
const books=["primary","related-1","related-2"].map(x=>new LibraryBookId(x));
function edition(book:LibraryBookId,language="de",url:string|undefined=`https://alivo.example/${book.value}`){return new LibraryEdition({id:new LibraryEditionId(`edition-${book.value}-${language}`),bookId:book,language:new LibraryEditionLanguage(language),publishedTitle:`Published ${book.value}`,status:LibraryEditionStatus.Published,links:new LibraryEditionLinkSet(url,undefined,undefined,url?LibraryLinkStatus.Verified:LibraryLinkStatus.Missing),contentEquivalence:LibraryContentEquivalence.EquivalentToMaster,updatedAt:at});}
const library={resolveEdition(_p:BusinessPackageId,b:LibraryBookId,l:string){const e=edition(b,l);return {state:"Resolved" as const,edition:e,url:e.properties.links.alivoProductUrl};}};
function recommendation(status=RecommendationStatus.ApprovedByCEO,version=7,decision=CEODecision.Approved){return {id:{value:"recommendation-1"},version,status,businessPackageId:pkg,decision:{decision,recommendationVersion:version}} as any;}
function request(overrides:Record<string,unknown>={}){const rec=(overrides.recommendation as any)??recommendation(),version=(overrides.recommendationVersion as number)??rec.version,approval=(overrides.ceoApproval as any)??{decisionId:"ceo-approval-1",recommendationId:rec.id.value,recommendationVersion:version,businessPackageId:pkg,decisionType:CEORecommendationDecisionType.Approve};return new BlogContentCreationPlanRequest({id:new BlogContentCreationPlanId((overrides.planId as string)??"plan-1"),version:(overrides.version as number)??1,businessPackageId:(overrides.businessPackageId as BusinessPackageId)??pkg,recommendation:rec,recommendationVersion:version,ceoApproval:approval,blogOpportunityReference:"opportunity-1",canonicalQuestionReference:"question-1",canonicalQuestionText:question,questionClusterReference:"cluster-1",contentGapReference:"gap-1",market:"DE",language:"de",intent:["Informational","Cause"],action:(overrides.action as BlogRecommendationAction)??BlogRecommendationAction.CreateNewArticle,existingApprovedH1:overrides.existingApprovedH1 as string|undefined,requestedAt:at,correlationIdentifier:"IMPLEMENTATION-051",requestingAuthorityReference:"TCO",stylePolicyReference:"business-package:ALIVO:writing-style:v1",minimumPinsConfigurationReference:"business-package:ALIVO:minimumPinsPerPublishedBlog"});}
function input(readiness=BlogKnowledgeReadiness.Sufficient){const h2=new BlogHeadingCandidate("h2-related","Warum macht Verdauung müde?",BlogHeadingLevel.H2,BlogHeadingEvidence.ObservedRelatedQuestion,["related-question-1"],undefined,true),h3=new BlogHeadingCandidate("h3-mechanism","Welche Mechanismen sind beteiligt?",BlogHeadingLevel.H3,BlogHeadingEvidence.KnowledgeRequirement,["knowledge:master-energy:v3"],h2.headingId);return {objective:new BlogArticleObjective("Directly answer the observed question and explain why the answer makes sense.",["recommendation-1","question-1"]),directAnswerObjective:new BlogDirectAnswerObjective(true,true,true),scope:new BlogArticleScope(["direct answer","physiological context"],["practical context"],["diagnosis","unrelated diets"],["question-1","gap-1"]),relatedQuestions:["Warum macht Verdauung müde?"],headingPlan:new BlogHeadingPlan([h2,h3]),knowledgeRequirement:new BlogKnowledgeRequirement(readiness,["library:master-energy:v3"],true,true,readiness===BlogKnowledgeReadiness.Sufficient?[]:["clinical evidence"]),sourceRequirements:[new BlogSourceRequirement(true,["library:master-energy:v3"],"current",true,true,true)],primaryBookId:books[0],relatedBookIds:[books[1]!,books[2]!],bookReasons:{primary:"Most directly explains the main mechanism","related-1":"Supports the digestion section","related-2":"Supports the energy section"},bookSectionHeadingIds:{"related-1":"h2-related","related-2":"h3-mechanism"},internalLinks:[new BlogInternalLinkRequirement("article:energy","https://alivo.example/blog/energy","Useful background")],searchDiscovery:new BlogSearchDiscoveryRequirement(["exact question H1","clear early answer","meaningful evidence-backed headings"]),aiDiscovery:new BlogAIDiscoveryRequirement(["clear question/answer relationship","explicit concepts","citation readiness"]),warnings:["Competitor intelligence informs gaps only; never copy prose, wording, CTA, hierarchy, or structure."]};}
function service(lib:any=library){return new BlogContentCreationPlanService(new BlogContentCreationPlanRepository(),lib,undefined,()=>new Date(at));}

test("only an exact explicitly CEO-approved Recommendation version can create a Plan",()=>{for(const r of [request({recommendation:recommendation(RecommendationStatus.ReadyForCEOReview)}),request({recommendation:recommendation(RecommendationStatus.RejectedByCEO)}),request({recommendationVersion:8}),request({ceoApproval:{decisionId:"x",recommendationId:"recommendation-1",recommendationVersion:7,businessPackageId:pkg,decisionType:CEORecommendationDecisionType.Reject}})])assert.throws(()=>service().create(r,input()),/CEO approved|exact Recommendation version/);});
test("question-driven H1 preserves the Canonical Question exactly and authority is immutable",()=>{const plan=service().create(request(),input());assert.equal(plan.plannedH1,question);assert.equal(plan.canonicalQuestionText,question);assert.equal(Reflect.set(plan,"plannedH1","SEO, Writer, or AI improved H1"),false);assert.equal(plan.directAnswerObjective.answerClearlyAndEarly,true);assert.equal(plan.directAnswerObjective.prohibitGenericSEOIntroduction,true);});
test("existing article actions preserve an existing approved H1 distinction",()=>{const plan=service().create(request({action:BlogRecommendationAction.UpdateExistingArticle,existingApprovedH1:"Existing authoritative heading"}),input());assert.equal(plan.plannedH1,"Existing authoritative heading");assert.equal(plan.canonicalQuestionText,question);});
test("scope, related questions, heading evidence, hierarchy, and no quota are preserved",()=>{const plan=service().create(request(),input());assert.deepEqual(plan.scope.requiredCoverage,["direct answer","physiological context"]);assert.deepEqual(plan.scope.excludedOrOutOfScopeCoverage,["diagnosis","unrelated diets"]);assert.equal(plan.headingPlan.candidates.length,2);assert.equal(plan.headingPlan.candidates[0]?.observedWording,true);assert.equal(plan.headingPlan.candidates[1]?.level,BlogHeadingLevel.H3);assert.throws(()=>new BlogHeadingPlan([new BlogHeadingCandidate("bad","Bad",BlogHeadingLevel.H3,BlogHeadingEvidence.ContentGap,["gap"],"missing")]),/H2 parent/);});
test("missing knowledge blocks readiness and identifies research without invoking a Writer",()=>{for(const readiness of [BlogKnowledgeReadiness.Partial,BlogKnowledgeReadiness.ResearchRequired,BlogKnowledgeReadiness.Unavailable,BlogKnowledgeReadiness.Unknown]){const plan=service().create(request({planId:`plan-${readiness}`}),input(readiness));assert.equal(plan.state,BlogContentCreationPlanState.KnowledgeRequired);assert.ok(plan.knowledgeRequirement.missingEvidence.length);assert.equal(Object.keys(service()).some(x=>/writer|publish/i.test(x)),false);}});
test("English master context can support German without duplicate ingestion and only relevant references pass",()=>{const plan=service().create(request(),input());assert.equal(plan.language,"de");assert.equal(plan.knowledgeRequirement.allowMasterLanguageContext,true);assert.equal(plan.knowledgeRequirement.relevantContextOnly,true);assert.deepEqual(plan.knowledgeRequirement.contextReferences,["library:master-energy:v3"]);assert.doesNotThrow(()=>edition(books[0]!,"de"));});
test("Library resolutions preserve actual target-language titles, verified URLs, contextual placement, and CTA intent",()=>{const plan=service().create(request(),input());assert.equal(plan.bookPlacementPlan.placements.length,3);assert.deepEqual(plan.bookPlacementPlan.placements.map(x=>x.publishedTitle),["Published primary","Published related-1","Published related-2"]);assert.ok(plan.bookPlacementPlan.placements.every(x=>x.targetLanguage==="de"&&x.verifiedDirectUrl?.startsWith("https://")));assert.equal(plan.bookPlacementPlan.placements[1]?.sectionHeadingId,"h2-related");assert.equal(plan.primaryBookCTAPlan.state,"Planned");assert.match(plan.primaryBookCTAPlan.intent,/deeper treatment/);assert.equal(JSON.stringify(plan.primaryBookCTAPlan).includes("Wenn Sie"),false);});
test("relevance precedes quota, unavailable links are explicit, and URLs are never invented",()=>{const missing={resolveEdition(_p:BusinessPackageId,b:LibraryBookId,l:string){return {state:"LinkUnavailable" as const,edition:edition(b,l,undefined)};}};const sparse=input();sparse.relatedBookIds=[books[1]!];const plan=service(missing).create(request(),sparse);assert.equal(plan.bookPlacementPlan.placements.length,2);assert.ok(plan.bookPlacementPlan.placements.every(x=>x.linkStatus===BlogBookLinkStatus.BookRelevantButLinkUnavailable&&x.verifiedDirectUrl===undefined));assert.equal(plan.primaryBookCTAPlan.state,"PrimaryBookUnavailable");});
test("duplicate promotion, language fallback, invented links, and package crossover are rejected",()=>{const duplicate=input();duplicate.relatedBookIds=[books[0]!];assert.throws(()=>service().create(request(),duplicate),/distinct/);const fallback={resolveEdition(){return {state:"EditionUnavailable" as const};}};const unavailable=service(fallback).create(request(),input());assert.ok(unavailable.bookPlacementPlan.placements.every(x=>x.linkStatus===BlogBookLinkStatus.EditionUnavailable));assert.throws(()=>service().create(request({businessPackageId:new BusinessPackageId("BEST-FINDS")}),input()),/Business Package/);});
test("Search and AI remain one human-first contract with style, factual, internal-link, and non-copy constraints",()=>{const plan=service().create(request(),input());assert.equal(plan.searchDiscovery.humanFirst,true);assert.equal(plan.aiDiscovery.humanFirst,true);assert.equal(plan.stylePolicyReference,"business-package:ALIVO:writing-style:v1");assert.equal(plan.sourceRequirements[0]?.factualReviewRequired,true);assert.equal(plan.internalLinks[0]?.approvedUrl,"https://alivo.example/blog/energy");assert.match(plan.warnings[0]!,/never copy/);});
test("Ready Plans are immutable and material changes require versioned supersession",()=>{const repo=new BlogContentCreationPlanRepository(),s=new BlogContentCreationPlanService(repo,library,undefined,()=>at);const first=s.create(request(),input());const second=s.create(request({version:2}),input());assert.equal(first.state,BlogContentCreationPlanState.Ready);assert.equal(second.supersedesVersion,1);assert.equal(repo.history(first.id).length,2);assert.throws(()=>repo.save(first),/already exists/);});
test("Pinterest lineage includes H1/H2/H3, mandatory H1 candidacy, configurable minimum, video and BlogPublished compatibility without Pins",()=>{const plan=service().create(request(),input());assert.deepEqual(plan.pinterestLineage.headings.map(x=>x.level),[BlogHeadingLevel.H1,BlogHeadingLevel.H2,BlogHeadingLevel.H3]);assert.equal(plan.pinterestLineage.headings[0]?.defaultCandidate,true);assert.match(plan.pinterestLineage.minimumPinsConfigurationReference,/minimumPinsPerPublishedBlog/);assert.equal(plan.pinterestLineage.videoPinCompatible,true);assert.equal(plan.pinterestLineage.blogPublishedEventCompatible,true);assert.equal(JSON.stringify(plan).includes("pinCopy"),false);});
test("Plan contains governed blueprint only: no prose, metadata, images, publishing, network, or secrets",()=>{const plan=service().create(request(),input()),serialized=JSON.stringify(plan);for(const forbidden of ["articleBody","introductionProse","ctaProse","metaTitle","metaDescription","pinCopy","imagePrompt","wordpress","credential","secret"])assert.equal(serialized.toLowerCase().includes(forbidden.toLowerCase()),false);assert.equal(Object.keys(plan).some(x=>/publish|network|generate/i.test(x)),false);});
