import assert from "node:assert/strict";
import { test } from "node:test";
import { InMemoryRepository } from "../../src/core/platform/Repository.ts";
import { BusinessPackageId, Confidence, Evidence, EvidenceId, EvidenceStatus, Freshness, FreshnessStatus, MarketObservation, MarketSourceId, ObservationId, Provenance } from "../../src/intelligence/market/MarketIntelligenceDomain.ts";
import { CompetitiveAnalysis, CompetitiveAnalysisId, CompetitiveContentProfile, CompetitiveGap, CompetitiveGapCategory, CompetitiveObservation, CompetitiveObservationId, CompetitiveSubject, CompetitiveSubjectType, ContentStructureAnalysis, EngagementAvailability, EngagementSignal, KeywordAnalysis, SearchIntent, SearchIntentAnalysis, VisualAnalysis } from "../../src/business/market/competitive/CompetitiveIntelligenceDomain.ts";
import { RepositoryCompetitiveIntelligenceService } from "../../src/business/market/competitive/CompetitiveIntelligenceService.ts";

const at = new Date("2026-02-01T00:00:00Z"); const source = new MarketSourceId("generic-public-source");
const packageOne = new BusinessPackageId("alivo"); const packageTwo = new BusinessPackageId("best-finds");
function fixture(id:string, pkg=packageOne) {
  const provenance=new Provenance("public-record",at,source,[`record:${id}`]);
  const market=new MarketObservation(new ObservationId(`market-${id}`),source,at,"market",pkg,"public subject","content","payload",provenance,new Freshness(FreshnessStatus.Current,at),new Confidence(.8));
  const evidence=new Evidence(new EvidenceId(`evidence-${id}`),[market.id],provenance,at,new Confidence(.8),new Freshness(FreshnessStatus.Current,at),EvidenceStatus.Active);
  const subject=new CompetitiveSubject("subject",CompetitiveSubjectType.PublicContent,"Observed content");
  const observation=new CompetitiveObservation(new CompetitiveObservationId(id),market,subject,"article","characteristics",pkg,[evidence]);
  return {provenance,market,evidence,subject,observation,pkg};
}
function analysis(id:string, f=fixture(`observation-${id}`), timestamp=at) {
  return new CompetitiveAnalysis({id:new CompetitiveAnalysisId(id),subject:f.subject,businessPackageId:f.pkg,sourceObservations:[f.observation],contentProfile:new CompetitiveContentProfile({title:"Public title",contentLength:42,publicationTimestamp:at,freshness:new Freshness(FreshnessStatus.Current,at)}),keywordAnalysis:new KeywordAnalysis({keywords:["observable"],evidence:[f.evidence]}),searchIntentAnalysis:new SearchIntentAnalysis(SearchIntent.Informational,[f.evidence],new Confidence(.7),"The public title explains a subject"),visualAnalysis:new VisualAnalysis({imagePresence:true,visualHierarchy:"headline first"}),contentStructureAnalysis:new ContentStructureAnalysis({informationOrder:"overview then detail"}),engagementSignals:[new EngagementSignal("views",10,source,at,new Confidence(.9),EngagementAvailability.Available)],competitiveGaps:[new CompetitiveGap(CompetitiveGapCategory.InformationGap,"A factual section is absent",[f.evidence])],confidence:new Confidence(.8),provenance:f.provenance,analysisTimestamp:timestamp});
}

test("competitive observations are immutable, traceable, and retain MarketObservation context",()=>{ const f=fixture("one"); assert.equal(Object.isFrozen(f.observation),true); assert.equal(Object.isFrozen(f.observation.evidence),true); assert.equal(f.observation.marketObservation,f.market); assert.equal(f.observation.businessPackageId?.value,"alivo"); assert.throws(()=>new CompetitiveSubject("",CompetitiveSubjectType.PublicPage,"page"),/must not be empty/); });
test("normalised descriptive models preserve unavailable fields and evidence",()=>{ const f=fixture("models"); const profile=new CompetitiveContentProfile({headline:"Headline"}); assert.equal(profile.title,undefined); assert.equal(new KeywordAnalysis({topicTerms:["topic"],evidence:[f.evidence]}).evidence[0],f.evidence); assert.equal(new VisualAnalysis({graphicStyle:"minimal"}).graphicStyle,"minimal"); assert.equal(new ContentStructureAnalysis({contentDepth:"summary"}).contentDepth,"summary"); });
test("search intent falls back to Unknown without evidence and retains rationale and confidence",()=>{ const result=new SearchIntentAnalysis(SearchIntent.Commercial,[],new Confidence(.2),"Insufficient public evidence"); assert.equal(result.intent,SearchIntent.Unknown); assert.equal(result.confidence.value,.2); assert.equal(result.rationale,"Insufficient public evidence"); });
test("engagement signals validate availability without fabricating values",()=>{ const unavailable=new EngagementSignal("clicks",undefined,source,at,new Confidence(.5),EngagementAvailability.Unavailable); assert.equal(unavailable.observedValue,undefined); assert.throws(()=>new EngagementSignal("clicks",2,source,at,new Confidence(.5),EngagementAvailability.Unavailable),/must not contain/); assert.throws(()=>new EngagementSignal("views",undefined,source,at,new Confidence(.5),EngagementAvailability.Available),/requires/); });
test("gaps require evidence and completed analyses are immutable with provenance",()=>{ const f=fixture("gap"); assert.throws(()=>new CompetitiveGap(CompetitiveGapCategory.IntentGap,"missing",[]),/requires supporting evidence/); const result=analysis("immutable",f); assert.equal(Object.isFrozen(result),true); assert.equal(Object.isFrozen(result.sourceObservations),true); assert.equal(result.provenance,f.provenance); assert.deepEqual(Object.keys(result).filter(key=>/recommend|pattern/i.test(key)),[]); });
test("service isolates Business Packages and retrieves deterministically across generic sources",()=>{ const service=new RepositoryCompetitiveIntelligenceService(new InMemoryRepository()); const a=fixture("a",packageOne), b=fixture("b",packageTwo), c=fixture("c",packageOne); service.registerObservation(c.observation); service.registerObservation(b.observation); service.registerObservation(a.observation); const later=new Date("2026-02-02T00:00:00Z"); service.analyse(c.subject,packageOne,analysis("z",c,later)); service.analyse(a.subject,packageOne,analysis("a",a,at)); service.analyse(b.subject,packageTwo,analysis("b",b,at)); assert.deepEqual(service.observations(packageOne).map(o=>o.id.value),["a","c"]); assert.deepEqual(service.analyses({businessPackageId:packageOne}).map(a=>a.id.value),["a","z"]); assert.equal(service.analyses({businessPackageId:packageTwo}).length,1); assert.equal(service.analyses({sourceId:source,subjectType:CompetitiveSubjectType.PublicContent}).length,3); assert.throws(()=>service.analyse(a.subject,packageTwo,analysis("wrong",a)),/context does not match/); });
