import assert from "node:assert/strict";import { test } from "node:test";
import { AuditRecorder } from "../../src/core/platform/AuditRecorder.ts";import { EventBus } from "../../src/core/platform/EventBus.ts";import { IdentityId } from "../../src/core/platform/IdentityId.ts";import { IdentityType } from "../../src/core/platform/IdentityType.ts";import { SystemIdentity } from "../../src/core/platform/SystemIdentity.ts";import { BusinessPackageId } from "../../src/intelligence/market/MarketIntelligenceDomain.ts";
import { LibraryAuthorizationException,LibraryBook,LibraryBookId,LibraryBookStatus,LibraryContentEquivalence,LibraryEdition,LibraryEditionId,LibraryEditionLanguage,LibraryEditionLinkSet,LibraryEditionStatus,LibraryKnowledgeSource,LibraryKnowledgeSourceId,LibraryKnowledgeSourceStatus,LibraryLinkStatus,LibraryValidationException } from "../../src/business/library/LibraryDomain.ts";import { InMemoryLibraryRepository,LibraryService } from "../../src/business/library/LibraryService.ts";
const ceo=new SystemIdentity({id:new IdentityId("ceo"),type:IdentityType.CEO,displayName:"CEO",enabled:true});const agent=new SystemIdentity({id:new IdentityId("agent"),type:IdentityType.AIWorker,displayName:"Agent",enabled:true});const alivo=new BusinessPackageId("ALIVO"),best=new BusinessPackageId("BEST-FINDS"),en=new LibraryEditionLanguage("en"),de=new LibraryEditionLanguage("de");let clock=0;const now=()=>new Date(++clock*1000);
const setup=()=>{const audit=new AuditRecorder(),repo=new InMemoryLibraryRepository();return {audit,repo,service:new LibraryService(repo,audit,new EventBus(),now)};};
const book=(pkg=alivo,id="BOOK-001",title="Insulin Resistance")=>new LibraryBook({id:new LibraryBookId(id),businessPackageId:pkg,canonicalTopic:"insulin resistance",canonicalTitle:title,masterLanguage:en,topics:["metabolism"],relatedTopics:["blood sugar"],concepts:["insulin"],status:LibraryBookStatus.Active,updatedAt:now()});
const source=(id="KS-1",version=1,status=LibraryKnowledgeSourceStatus.Ready,language=en)=>new LibraryKnowledgeSource({id:new LibraryKnowledgeSourceId(id),bookId:new LibraryBookId("BOOK-001"),language,sourceType:"KnowledgeDocumentReference",sourceReference:`document:${id}`,status,version,fingerprint:`sha256:${id}`,createdAt:now(),updatedAt:now(),ceoProvenance:"CEO import"});
const edition=(id:string,language:LibraryEditionLanguage,title:string,url?:string,equivalence=LibraryContentEquivalence.EquivalentToMaster,sourceId?:string)=>new LibraryEdition({id:new LibraryEditionId(id),bookId:new LibraryBookId("BOOK-001"),language,publishedTitle:title,status:LibraryEditionStatus.Published,links:new LibraryEditionLinkSet(url,"https://amazon.example/books/actual",undefined,url?LibraryLinkStatus.Verified:LibraryLinkStatus.Unverified),contentEquivalence:equivalence,editionKnowledgeSourceId:sourceId?new LibraryKnowledgeSourceId(sourceId):undefined,updatedAt:now()});

test("CEO creates a canonical Book while every non-CEO mutation is rejected",()=>{const {service}=setup();service.createBook(ceo,book());assert.equal(service.findBookByTopic(alivo,"insulin resistance")[0].id.value,"BOOK-001");for(const action of [()=>service.createBook(agent,book(alivo,"BOOK-002")),()=>service.updateBook(agent,alivo,new LibraryBookId("BOOK-001"),{...book().properties,updatedAt:now()}),()=>service.retireBook(agent,alivo,new LibraryBookId("BOOK-001")),()=>service.bulkImportEditions(agent,alivo,[])])assert.throws(action,LibraryAuthorizationException);});
test("master content remains a versioned Knowledge Engine document reference and may be missing",()=>{const {service}=setup();service.createBook(ceo,book());assert.equal(service.query({businessPackageId:alivo}).rows[0].knowledgeSourceStatus,LibraryKnowledgeSourceStatus.Missing);service.attachKnowledgeSource(ceo,alivo,source());service.attachKnowledgeSource(ceo,alivo,source("KS-2",2,LibraryKnowledgeSourceStatus.Indexing));const detail=service.detail(alivo,new LibraryBookId("BOOK-001"));assert.equal(detail.knowledgeHistory.length,2);assert.equal(detail.masterKnowledgeSource?.properties.sourceReference,"document:KS-2");assert.equal(detail.masterKnowledgeSource?.status,LibraryKnowledgeSourceStatus.Indexing);assert.throws(()=>service.attachKnowledgeSource(ceo,alivo,source("KS-old",1)),/advance/);});
test("multiple editions preserve actual titles, languages, statuses, and direct links",()=>{const {service}=setup();service.createBook(ceo,book());service.attachKnowledgeSource(ceo,alivo,source());service.createEdition(ceo,alivo,edition("ED-EN",en,"Insulin Resistance","https://alivo.example/en/real"));service.createEdition(ceo,alivo,edition("ED-DE",de,"Insulinresistenz","https://alivo.example/de/tatsaechlich"));const resolved=service.resolveEdition(alivo,new LibraryBookId("BOOK-001"),"de");assert.equal(resolved.state,"Resolved");assert.equal(resolved.edition?.properties.publishedTitle,"Insulinresistenz");assert.equal(resolved.url,"https://alivo.example/de/tatsaechlich");assert.equal(resolved.knowledgeSource?.properties.language.value,"en");assert.equal(resolved.edition?.properties.links.amazonUrl,"https://amazon.example/books/actual");});
test("missing target language and missing links are explicit without fallback or invention",()=>{const {service}=setup();service.createBook(ceo,book());service.createEdition(ceo,alivo,edition("ED-DE",de,"Insulinresistenz"));assert.equal(service.resolveEdition(alivo,new LibraryBookId("BOOK-001"),"de").state,"LinkUnavailable");assert.equal(service.resolveEdition(alivo,new LibraryBookId("BOOK-001"),"fr").state,"EditionUnavailable");assert.equal(service.findEdition(alivo,new LibraryBookId("BOOK-001"),"fr"),undefined);});
test("URL validation is local and never performs network verification",()=>{assert.throws(()=>new LibraryEditionLinkSet("not a url",undefined,undefined,LibraryLinkStatus.Invalid),LibraryValidationException);assert.doesNotThrow(()=>new LibraryEditionLinkSet("https://does-not-need-to-exist.invalid/direct",undefined,undefined,LibraryLinkStatus.Verified));});
test("equivalent translations need no duplicate content; exceptions reference an approved source",()=>{const {service}=setup();service.createBook(ceo,book());service.attachKnowledgeSource(ceo,alivo,source());assert.doesNotThrow(()=>service.createEdition(ceo,alivo,edition("ED-DE",de,"Insulinresistenz")));assert.throws(()=>edition("ED-X",de,"Different",undefined,LibraryContentEquivalence.EditionSpecific),/required/);service.attachEditionKnowledgeSource(ceo,alivo,source("KS-DE",2,LibraryKnowledgeSourceStatus.Ready,de));const separate=edition("ED-SEPARATE",new LibraryEditionLanguage("fr"),"Different",undefined,LibraryContentEquivalence.EditionSpecific,"KS-DE");assert.equal(service.createEdition(ceo,alivo,separate).properties.editionKnowledgeSourceId?.value,"KS-DE");});
test("Business Packages are isolated and identifiers and active editions stay unique",()=>{const {service}=setup();service.createBook(ceo,book());service.createBook(ceo,book(best));service.createEdition(ceo,alivo,edition("ED-DE",de,"Insulinresistenz"));assert.equal(service.findPublishedEditions(best,"de").length,0);assert.throws(()=>service.createBook(ceo,book()),/already exists/);assert.throws(()=>service.createEdition(ceo,alivo,edition("ED-DE-2",de,"Duplicate")),/Duplicate active/);});
test("editor model supports search, filter, sorting, pagination, grouping and detail",()=>{const {service}=setup();service.createBook(ceo,book());service.createEdition(ceo,alivo,edition("ED-DE",de,"Insulinresistenz","https://alivo.example/de/direct"));const model=service.query({businessPackageId:alivo,search:"Insulin",language:"de",publicationStatus:LibraryEditionStatus.Published,linkStatus:LibraryLinkStatus.Verified,sortBy:"publishedTitle",limit:10});assert.equal(model.total,1);assert.equal(model.rows[0].contentEquivalentToMaster,true);assert.equal(model.grouped.get("BOOK-001")?.length,1);assert.equal(service.detail(alivo,new LibraryBookId("BOOK-001")).editions.length,1);});
test("topics provide related-book selection foundation and retirement preserves records",()=>{const {service,repo}=setup();service.createBook(ceo,book());service.createBook(ceo,new LibraryBook({id:new LibraryBookId("BOOK-002"),businessPackageId:alivo,canonicalTopic:"heart",canonicalTitle:"Heart",masterLanguage:en,topics:["blood sugar"],relatedTopics:[],concepts:[],status:LibraryBookStatus.Active,updatedAt:now()}));assert.deepEqual(service.findRelatedBooks(alivo,new LibraryBookId("BOOK-001")).map(x=>x.id.value),["BOOK-002"]);service.retireBook(ceo,alivo,new LibraryBookId("BOOK-001"));assert.equal(repo.books.get("ALIVO:BOOK-001")?.properties.status,LibraryBookStatus.Retired);});
test("link changes and content replacement are audited without full content",()=>{const {service,audit}=setup();service.createBook(ceo,book());service.attachKnowledgeSource(ceo,alivo,source());service.createEdition(ceo,alivo,edition("ED-DE",de,"Insulinresistenz","https://alivo.example/old"));const old=service.findEdition(alivo,new LibraryBookId("BOOK-001"),"de")!;service.updateEdition(ceo,alivo,old.id,{...old.properties,links:new LibraryEditionLinkSet("https://alivo.example/new",undefined,undefined,LibraryLinkStatus.Verified),updatedAt:now()});assert.ok(audit.getEvents().some(x=>x.action==="LibraryLinkUpdated"&&x.context?.previous==="https://alivo.example/old"));assert.ok(audit.getEvents().every(x=>!JSON.stringify(x.context).includes("document body")));});
