import assert from "node:assert/strict";
import { test } from "node:test";
import { DesktopApplication, sanitizeForDesktop } from "../../src/ui/desktop/DesktopApplication.ts";
import { desktopDestinations, type DesktopCommandGateway, type DesktopStatusQuery, type DesktopSystemStatus } from "../../src/ui/desktop/DesktopContracts.ts";

const status: DesktopSystemStatus = { businessPackageId: "ALIVO", overallState: "Operational", activeWorkflows: 0, attentionCount: 0, integrationWarnings: [], authenticationWarnings: [], lastUpdated: "2026-08-09T12:00:00Z", stale: false };
test("desktop navigation contains every primary destination with Dashboard first", () => assert.deepEqual(desktopDestinations, ["Dashboard", "Questions", "Blogs", "Pinterest", "Library", "Performance", "System", "Settings"]));
test("status query is scoped to ALIVO and exposes global status", async () => { let scope = ""; const query: DesktopStatusQuery = { async execute(input) { scope = input.businessPackageId; return status; } }; const app = new DesktopApplication(query, { async execute(command) { return { businessPackageId: command.businessPackageId, state: "Succeeded" }; } }); assert.equal((await app.loadStatus()).overallState, "Operational"); assert.equal(scope, "ALIVO"); assert.equal(app.activeBusinessPackage, "ALIVO"); });
test("cross-package status cannot render in the active workspace", async () => { const query: DesktopStatusQuery = { async execute() { return { ...status, businessPackageId: "OTHER" }; } }; await assert.rejects(new DesktopApplication(query, {} as DesktopCommandGateway).loadStatus(), /different Business Package/); });
test("commands use the application gateway, preserve scope and report async state", async () => { let received = ""; const gateway: DesktopCommandGateway = { async execute(command) { received = command.businessPackageId; return { businessPackageId: received, state: "CommandAccepted", correlationId: "corr-1", workflowId: "flow-1" }; } }; const app = new DesktopApplication({ async execute() { return status; } }, gateway); const pending = app.send("RefreshDesktopStatus"); assert.equal(app.commandState, "Submitting"); const result = await pending; assert.equal(received, "ALIVO"); assert.equal(app.commandState, "CommandAccepted"); assert.equal(result.correlationId, "corr-1"); });
test("command failures and cross-package results are explicit", async () => { const app = new DesktopApplication({ async execute() { return status; } }, { async execute() { return { businessPackageId: "ALIVO", state: "ValidationFailed", message: "Invalid request" }; } }); await app.send("SampleCEOAction"); assert.equal(app.commandState, "ValidationFailed"); const unsafe = new DesktopApplication({ async execute() { return status; } }, { async execute() { return { businessPackageId: "OTHER", state: "Succeeded" }; } }); await assert.rejects(unsafe.send("SampleCEOAction"), /different Business Package/); assert.equal(unsafe.commandState, "Failed"); });
test("desktop sanitization recursively redacts sensitive fields", () => assert.deepEqual(sanitizeForDesktop({ message: "safe", accessToken: "private", nested: { Authorization: "Bearer private", count: 1 } }), { message: "safe", accessToken: "[REDACTED]", nested: { Authorization: "[REDACTED]", count: 1 } }));
