import assert from "node:assert/strict";
import { test } from "node:test";
import { AuditRecorder } from "../../src/core/platform/AuditRecorder.ts";
import { AuthorizationService } from "../../src/core/platform/AuthorizationService.ts";
import { CEOAuthorityPolicy } from "../../src/core/platform/CEOAuthorityPolicy.ts";
import { EventBus } from "../../src/core/platform/EventBus.ts";
import { EventSubscription } from "../../src/core/platform/EventSubscription.ts";
import { EventType } from "../../src/core/platform/EventType.ts";
import { IdentityId } from "../../src/core/platform/IdentityId.ts";
import { IdentityType } from "../../src/core/platform/IdentityType.ts";
import { SystemIdentity } from "../../src/core/platform/SystemIdentity.ts";
import { BusinessPackageId } from "../../src/intelligence/market/MarketIntelligenceDomain.ts";
import { MarketSourceAdapterId } from "../../src/intelligence/market/integration/MarketSourceIntegrationDomain.ts";
import { AuthenticationType, CredentialId, CredentialVault, CredentialVaultPermissions, InMemoryCredentialVaultStorage } from "../../src/security/credentials/CredentialVault.ts";
import { AuthenticationRecoverability, AuthenticationRecoveryAction, AuthenticationRecoveryState, ExternalAuthenticationFailureType, ExternalAuthenticationId, ExternalAuthenticationMethod, ExternalAuthenticationRequest, ExternalAuthenticationState, InterruptedOperationReference, recoverabilityFor } from "../../src/security/authentication/ExternalAuthenticationDomain.ts";
import type { ExternalAuthenticationProvider, ProviderAuthenticationOutcome } from "../../src/security/authentication/ExternalAuthenticationDomain.ts";
import { ExternalAuthenticationRepository } from "../../src/security/authentication/ExternalAuthenticationRepository.ts";
import { AuthenticationRecoveryService, ExternalAuthenticationService } from "../../src/security/authentication/ExternalAuthenticationService.ts";

const NOW=new Date("2026-08-09T12:00:00.000Z"), MATERIAL="SYNTHETIC-AUTH-MATERIAL", MASTER="SYNTHETIC-VAULT-PROTECTION";
class FakeProvider implements ExternalAuthenticationProvider { calls=0; constructor(readonly outcomes:ProviderAuthenticationOutcome[]){} async authenticate(_request:ExternalAuthenticationRequest,credential:Parameters<ExternalAuthenticationProvider["authenticate"]>[1]){this.calls++;credential.use(value=>assert.ok(value.length>0));return this.outcomes.shift()??{successful:true};} }
async function setup(scope="PACKAGE-ALPHA") {const authorization=new AuthorizationService();authorization.registerPolicy(new CEOAuthorityPolicy());const ceo=new SystemIdentity({id:new IdentityId("ceo-auth"),type:IdentityType.CEO,displayName:"CEO",enabled:true,permissions:Object.values(CredentialVaultPermissions)});const audit=new AuditRecorder(),events=new EventBus(),vault=new CredentialVault(new InMemoryCredentialVaultStorage(),authorization,audit,events,()=>NOW);await vault.initialize(MASTER,MASTER,ceo);await vault.addCredential({credentialId:"credential-auth",displayName:"External account",serviceReference:"service-neutral",accountReference:"account-neutral",secret:MATERIAL,authenticationType:AuthenticationType.UsernamePassword,businessPackageScopes:[scope],capabilityScopes:["market.read"]},ceo);const repository=new ExternalAuthenticationRepository(),recovery=new AuthenticationRecoveryService(vault,repository,events,audit,undefined,()=>NOW),service=new ExternalAuthenticationService(vault,repository,recovery,events,audit,()=>NOW);return{ceo,audit,events,vault,repository,recovery,service};}
function request(packageId="PACKAGE-ALPHA",id="authentication-1"){const businessPackageId=new BusinessPackageId(packageId),adapter=new MarketSourceAdapterId("adapter-neutral");const interruptedOperation=new InterruptedOperationReference({workflowRunReference:"RUN-1042",workflowStepReference:"STEP-3",tcoTaskReference:"TCO-9",marketCollectionRequestReference:"COLLECT-2",sourceAdapterReference:adapter,businessPackageId,correlationIdentifier:`correlation-${id}`});return new ExternalAuthenticationRequest({id:new ExternalAuthenticationId(id),credentialId:new CredentialId("credential-auth"),method:ExternalAuthenticationMethod.UsernamePassword,businessPackageId,sourceAdapterReference:adapter,requestedCapability:"market.read",workflowRunReference:"RUN-1042",tcoTaskReference:"TCO-9",sourceRequestReference:"COLLECT-2",correlationIdentifier:`correlation-${id}`,requestingAuthorityReference:"ceo-auth",requestedAt:NOW,interruptedOperation});}

test("authentication request identity is immutable, traceable, and contains CredentialId but no secret",()=>{const value=request();assert.equal(Object.isFrozen(value),true);assert.equal(Object.isFrozen(value.id),true);assert.ok(value.properties.credentialId instanceof CredentialId);assert.equal(JSON.stringify(value).includes(MATERIAL),false);assert.equal("secret" in value.properties,false);});

test("credential scope is accepted for its Business Package and cross-package use is rejected",async()=>{const context=await setup();assert.equal((await context.service.authenticate(request(),new FakeProvider([{successful:true}]),context.ceo))?.successful,true);await assert.rejects(context.service.authenticate(request("PACKAGE-BETA","authentication-cross"),new FakeProvider([{successful:true}]),context.ceo),/Business Package/);});

test("fake provider succeeds without network or a real adapter and history is immutable and deterministic",async()=>{const context=await setup();const one=request("PACKAGE-ALPHA","authentication-b"),two=request("PACKAGE-ALPHA","authentication-a");await context.service.authenticate(one,new FakeProvider([{successful:true,providerReference:"fake"}]),context.ceo);await context.service.authenticate(two,new FakeProvider([{successful:true}]),context.ceo);assert.equal(context.service.state(one),ExternalAuthenticationState.Authenticated);assert.deepEqual(context.repository.query({businessPackageId:"PACKAGE-ALPHA"}).map(x=>x.authenticationId.value),["authentication-a","authentication-b"]);assert.throws(()=>context.repository.storeResult(context.repository.history(one.id)[0]),/already exists/);});

test("failure classifications have deterministic recoverability and lifecycle states",async()=>{const correctable=[ExternalAuthenticationFailureType.InvalidUsername,ExternalAuthenticationFailureType.InvalidPassword,ExternalAuthenticationFailureType.InvalidCredential,ExternalAuthenticationFailureType.ExpiredPassword];for(const type of correctable)assert.equal(recoverabilityFor(type),AuthenticationRecoverability.UserCorrectable);assert.equal(recoverabilityFor(ExternalAuthenticationFailureType.ExpiredToken),AuthenticationRecoverability.ReauthorizationRequired);assert.equal(recoverabilityFor(ExternalAuthenticationFailureType.MFARequired),AuthenticationRecoverability.MFARequired);for(const type of [ExternalAuthenticationFailureType.AuthenticationUnavailable,ExternalAuthenticationFailureType.RateLimited,ExternalAuthenticationFailureType.ProviderMaintenance,ExternalAuthenticationFailureType.NetworkUnavailable])assert.equal(recoverabilityFor(type),AuthenticationRecoverability.RetryableTemporary);assert.notEqual(recoverabilityFor(ExternalAuthenticationFailureType.PermissionDenied),AuthenticationRecoverability.UserCorrectable);
  for(const [index,type] of [ExternalAuthenticationFailureType.ExpiredToken,ExternalAuthenticationFailureType.MFARequired,ExternalAuthenticationFailureType.AccountLocked,ExternalAuthenticationFailureType.PermissionDenied,ExternalAuthenticationFailureType.ReauthorizationRequired,ExternalAuthenticationFailureType.AuthenticationUnavailable,ExternalAuthenticationFailureType.RateLimited,ExternalAuthenticationFailureType.ProviderMaintenance,ExternalAuthenticationFailureType.NetworkUnavailable].entries()){const context=await setup(),value=request("PACKAGE-ALPHA",`failure-${index}`),provider=new FakeProvider([{successful:false,failureType:type,safeMessage:`Safe ${type}`}]);const result=await context.service.authenticate(value,provider,context.ceo);assert.equal(result?.failure?.type,type);if(type===ExternalAuthenticationFailureType.AccountLocked)assert.equal(result?.retryEligible,false);}}
);

test("correctable failures offer CEO correction first and never silently fallback",async()=>{for(const type of [ExternalAuthenticationFailureType.InvalidUsername,ExternalAuthenticationFailureType.InvalidPassword,ExternalAuthenticationFailureType.InvalidCredential]){const context=await setup(),value=request("PACKAGE-ALPHA",`correct-${type}`);await context.service.authenticate(value,new FakeProvider([{successful:false,failureType:type,safeMessage:"Credentials were rejected"}]),context.ceo);assert.equal(context.service.state(value),ExternalAuthenticationState.WaitingForCredentialCorrection);assert.equal(context.repository.recoveryState(value.id),AuthenticationRecoveryState.WaitingForCEO);const correction=context.repository.recoveries(value.id)[0].correctionRequest!;assert.equal(JSON.stringify(correction).includes(MATERIAL),false);assert.ok(correction.allowedActions.includes(AuthenticationRecoveryAction.UseFallback));assert.notEqual(context.service.state(value),ExternalAuthenticationState.FallbackPending);}}
);

test("username, password, and combined correction use the vault, retry, and preserve resume context",async()=>{for(const [index,action,update] of [[0,AuthenticationRecoveryAction.ChangeUsername,{username:"corrected-user"}],[1,AuthenticationRecoveryAction.ChangePassword,{secret:"SYNTHETIC-CORRECTED-MATERIAL"}],[2,AuthenticationRecoveryAction.ChangeUsernameAndPassword,{username:"corrected-both",secret:"SYNTHETIC-CORRECTED-BOTH"}]] as const){const context=await setup(),value=request("PACKAGE-ALPHA",`retry-${index}`),provider=new FakeProvider([{successful:false,failureType:index===0?ExternalAuthenticationFailureType.InvalidUsername:index===1?ExternalAuthenticationFailureType.InvalidPassword:ExternalAuthenticationFailureType.InvalidCredential,safeMessage:"Rejected"},{successful:true}]);await context.service.authenticate(value,provider,context.ceo);const corrected=await context.recovery.correct(value,action,update,context.ceo);const retry=context.recovery.retryReference(value,"CEO corrected credential",corrected.credentialVersionReference);const result=await context.service.retry(value,retry,provider,context.ceo);assert.equal(result?.successful,true);assert.equal(context.repository.recoveryState(value.id),AuthenticationRecoveryState.ResumeReady);assert.equal(context.repository.interruptedOperation(value.id)?.properties.workflowRunReference,"RUN-1042");assert.equal(context.repository.history(value.id).length,2);}}
);

test("failed retry remains traceable, explicit fallback is pending for TCO, and cancellation is governed",async()=>{const context=await setup(),value=request();const provider=new FakeProvider([{successful:false,failureType:ExternalAuthenticationFailureType.InvalidPassword,safeMessage:"Rejected"},{successful:false,failureType:ExternalAuthenticationFailureType.InvalidPassword,safeMessage:"Still rejected"}]);await context.service.authenticate(value,provider,context.ceo);const retry=context.recovery.retryReference(value,"CEO requested retry","credential-version-1");assert.equal((await context.service.retry(value,retry,provider,context.ceo))?.successful,false);assert.equal(context.repository.history(value.id).length,2);assert.equal(context.recovery.choose(value,AuthenticationRecoveryAction.UseFallback,context.ceo.id.value),AuthenticationRecoveryState.FallbackPending);assert.equal(context.service.state(value),ExternalAuthenticationState.FallbackPending);assert.equal(context.repository.interruptedOperation(value.id)?.properties.tcoTaskReference,"TCO-9");});

test("locked vault waits for controlled access and safe events and audit never contain credential material",async()=>{const context=await setup();const received:unknown[]=[];for(const name of ["CredentialAccessRequired","ExternalAuthenticationFailed","CredentialCorrectionRequested"])context.events.subscribe(new EventSubscription({handle:event=>received.push(event)},[new EventType(name)]));context.vault.lock(context.ceo);const value=request();assert.equal(await context.service.authenticate(value,new FakeProvider([{successful:true}]),context.ceo),undefined);assert.equal(context.service.state(value),ExternalAuthenticationState.CredentialRequired);await context.vault.unlock(MASTER,context.ceo);await context.service.authenticate(value,new FakeProvider([{successful:false,failureType:ExternalAuthenticationFailureType.InvalidPassword,safeMessage:"Rejected"}]),context.ceo);const reporting=JSON.stringify({events:received,audit:context.audit.getEvents()});assert.equal(reporting.includes(MATERIAL),false);assert.equal(reporting.includes(MASTER),false);assert.equal(reporting.includes("SYNTHETIC-CORRECTED"),false);});
