import assert from "node:assert/strict";
import { mkdtemp, readFile, rm } from "node:fs/promises";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { afterEach, test } from "node:test";
import { ALIVO_PACKAGE, FileOnboardingStateStorage, FirstRunOnboarding, type ConnectionState, type GovernedDefaults, type OnboardingState, type RecoveryHandoff, type StateStorage } from "../../src/deployment/FirstRunOnboarding.ts";

const roots:string[]=[]; afterEach(async()=>Promise.all(roots.splice(0).map(root=>rm(root,{recursive:true,force:true}))));
const defaults: GovernedDefaults={language:"English",market:"United States",blogPublishingAuthority:"CEO Approval Required",libraryWriteAuthority:"CEO Only",pinterestMinimumIntervalMinutes:90,minimumPinsPerBlog:3,blogPinterestPromotionEnabled:true};
class MemoryStorage implements StateStorage { value?:OnboardingState; async load(){return this.value?structuredClone(this.value):undefined} async save(value:OnboardingState){this.value=structuredClone(value)} }
const verifier=(state:ConnectionState,safeIdentity?:string)=>({verify:async()=>({state,safeIdentity})});
function recovery(historical=false,credentialsAvailable=true):RecoveryHandoff{return{discover:async()=>historical?[{location:"approved-backup.zip",kind:"Backup Archive" as const}]:[],open:async()=>({restored:true,credentialsAvailable,defaults})}}
async function setup(options:{historical?:boolean;credentials?:boolean;wp?:ConnectionState;pin?:ConnectionState}={}){const root=await mkdtemp(join(tmpdir(),"alivo-onboarding-"));roots.push(root);const storage=new MemoryStorage(),vaultCalls:string[][]=[];const flow=new FirstRunOnboarding(storage,{initialize:async(...input)=>{vaultCalls.push(input)}},verifier(options.wp??"Connected","ALIVO WordPress"),verifier(options.pin??"Connected","ALIVO Pinterest"),recovery(options.historical,options.credentials),join(root,"application"),join(root,"data"));return{root,storage,vaultCalls,flow}}
async function localReady(flow:FirstRunOnboarding,root:string){await flow.startNew(defaults);await flow.initializeVault("A-Strong-Synthetic-Master","A-Strong-Synthetic-Master");await flow.configureWordPress({site:"https://example.invalid",credential:"synthetic"});await flow.configurePinterest({credential:"synthetic"});await flow.configureSources([]);await flow.configureAnalytics(false);await flow.configureLibrary({state:"Initialized",knowledge:"Add Later",starterImported:false});await flow.configureBackup(join(root,"backup"));}

test("fresh state opens onboarding and a completed installation skips it",async()=>{const {flow}=await setup();assert.equal((await flow.start()).showOnboarding,true);const {root,flow:ready,storage}=await setup();await localReady(ready,root);await ready.finish();const resumed=new FirstRunOnboarding(storage,{initialize:async()=>{}},verifier("Connected"),verifier("Connected"),recovery(),join(root,"application"),join(root,"data"));assert.equal((await resumed.start()).showOnboarding,false)});
test("start new establishes governed ALIVO identity and distinct language and market",async()=>{const {flow}=await setup();await flow.startNew(defaults);assert.deepEqual(flow.state().businessPackage,{id:ALIVO_PACKAGE,name:"ALIVO"});assert.equal(flow.state().defaults?.language,"English");assert.equal(flow.state().defaults?.market,"United States")});
test("historical data blocks conflicting clean initialization and recovery preserves restored policy",async()=>{const {flow}=await setup({historical:true});assert.equal((await flow.detectHistoricalData()).length,1);await assert.rejects(flow.startNew(defaults),/Existing ALIVO OS data found/);await flow.recover();assert.equal(flow.state().recovered,true);assert.equal(flow.state().defaults?.pinterestMinimumIntervalMinutes,90)});
test("recovery without credentials returns to validation flow with authentication required and no trust elevation",async()=>{const {flow}=await setup({credentials:false});await flow.recover("approved-backup.zip");assert.equal(flow.state().wordpress.state,"Authentication Required");assert.equal(flow.state().pinterest.state,"Authentication Required");assert.equal(flow.state().defaults?.blogPublishingAuthority,"CEO Approval Required")});
test("master password confirmation is required and plaintext never enters onboarding persistence",async()=>{const {flow,storage,vaultCalls}=await setup();await flow.startNew(defaults);await assert.rejects(flow.initializeVault("A-Strong-Synthetic-Master","different-value"),/does not match/);await flow.initializeVault("A-Strong-Synthetic-Master","A-Strong-Synthetic-Master");assert.equal(vaultCalls.length,1);assert.equal(JSON.stringify(storage.value).includes("A-Strong-Synthetic-Master"),false)});
test("connection tests retain safe identity and explicit provider states without publication commands",async()=>{const {flow}=await setup({wp:"Permission Denied",pin:"Rate Limited"});await flow.startNew(defaults);assert.equal((await flow.configureWordPress({credential:"synthetic"})).state,"Permission Denied");assert.equal((await flow.configurePinterest({credential:"synthetic"})).state,"Rate Limited");assert.equal(JSON.stringify(flow.state()).includes("synthetic"),false)});
test("required source failure blocks while optional failure and offline integrations only warn",async()=>{const {root,flow}=await setup({wp:"Site Unreachable",pin:"Unavailable"});await localReady(flow,root);await flow.configureSources([{id:"required",name:"Required Research",requirement:"Required",enabled:true,authenticationRequired:false,state:"Unavailable",markets:["US"],languages:["en"]},{id:"optional",name:"Optional Research",requirement:"Optional",enabled:true,authenticationRequired:false,state:"Unavailable",markets:["US"],languages:["en"]}]);assert.equal((await flow.readiness()).category,"Blocked");await flow.configureSources([{id:"optional",name:"Optional Research",requirement:"Optional",enabled:true,authenticationRequired:false,state:"Unavailable",markets:["US"],languages:["en"]}]);assert.equal((await flow.readiness()).category,"Ready with Warnings")});
test("verified backup uses an actual write/read probe, initializes recovery location, and warns on same disk",async()=>{const {root,flow}=await setup();await flow.startNew(defaults);await flow.configureBackup(join(root,"backup"));assert.equal(flow.state().backup.verified,true);assert.equal(flow.state().backup.sameDiskWarning,true);assert.equal(await readFile(join(root,"data","recovery","snapshots")).catch(()=>"directory"),"directory")});
test("interrupted onboarding resumes its separately persisted current step",async()=>{const {root,storage,flow}=await setup();await flow.startNew(defaults);await flow.cancelAt("WordPress");const resumed=new FirstRunOnboarding(storage,{initialize:async()=>{}},verifier("Connected"),verifier("Connected"),recovery(),join(root,"application"),join(root,"data"));assert.equal((await resumed.start()).state.currentStep,"WordPress")});
test("atomic file storage persists only non-secret state with restrictive intent",async()=>{const root=await mkdtemp(join(tmpdir(),"alivo-onboarding-file-"));roots.push(root);const location=join(root,"state","onboarding.json"),storage=new FileOnboardingStateStorage(location),state={...(await setup()).flow.state(),currentStep:"Welcome" as const};await storage.save(state);assert.equal((await storage.load())?.schemaVersion,1);assert.doesNotMatch(await readFile(location,"utf8"),/master.*password|access.*token|application.*password/i)});
