import assert from "node:assert/strict";
import { test } from "node:test";
import { AuditRecorder } from "../../src/core/platform/AuditRecorder.ts";
import { BusinessPackageId,Confidence,Freshness,FreshnessStatus,MarketObservation,MarketSource,MarketSourceId,ObservationId,Provenance } from "../../src/intelligence/market/MarketIntelligenceDomain.ts";
import { MarketCollectionRequest,MarketCollectionResult,MarketCollectionResultStatus,MarketNormalizationResult,MarketNormalizationStatus,MarketSourceAdapterId,MarketSourceAvailability,MarketSourceCapability,MarketSourceDescriptor,MarketSourceFailure,MarketSourceFailureCategory,MarketSourceHealth,MarketSourceHealthState,MarketSourceRateLimit,MarketSourceRequirement,MarketSourceState,RawMarketRecord } from "../../src/intelligence/market/integration/MarketSourceIntegrationDomain.ts";
import type { MarketSourceAdapter } from "../../src/intelligence/market/integration/MarketSourceIntegrationDomain.ts";
import { MarketSourceIntegrationService } from "../../src/intelligence/market/integration/MarketSourceIntegrationService.ts";

const now=new Date("2026-08-08T00:00:00Z"), pkg=new BusinessPackageId("ALIVO"), other=new BusinessPackageId("BEST-FINDS");
const cap=MarketSourceCapability.TrendObservation;
function adapter(id:string,priority=0,authorized=pkg):MarketSourceAdapter{const sourceId=new MarketSourceId(`source-${id}`);const provenance=new Provenance("adapter-registration",now,sourceId);const descriptor=new MarketSourceDescriptor({adapterId:new MarketSourceAdapterId(id),source:new MarketSource(sourceId,`Source ${id}`,"external-market-source"),displayName:`Adapter ${id}`,capabilities:[cap,new MarketSourceCapability("CustomObservation")],state:MarketSourceState.Registered,availability:MarketSourceAvailability.Unknown,health:new MarketSourceHealth(MarketSourceHealthState.Unknown,now),authorizations:[{businessPackageId:authorized,capabilities:[cap]}],registeredAt:now,priority,configurationReference:"config:market-source"});return{id:descriptor.adapterId,descriptor:()=>descriptor,async collect(request){return new MarketCollectionResult(request.id,this.id,sourceId,MarketCollectionResultStatus.NoData,[],now,provenance);}};}

test("validates adapter identity, capabilities, registration, and duplicate rejection",()=>{assert.throws(()=>new MarketSourceAdapterId(" "),/required/);assert.equal(new MarketSourceCapability("FutureCapability").value,"FutureCapability");const service=new MarketSourceIntegrationService();const a=adapter("generic");service.register(a,"CEO");assert.equal(service.registry.adapter(a.id),a);assert.deepEqual(service.registry.discover({capability:cap}).map(d=>d.adapterId.value),["generic"]);assert.throws(()=>service.register(a,"CEO"),/already registered/);});

test("enforces package authorization and deterministic operational selection with fallbacks",()=>{const service=new MarketSourceIntegrationService(undefined,undefined,undefined,()=>now);for(const a of [adapter("third",3),adapter("first",1),adapter("second",2),adapter("isolated",0,other)]){service.register(a,"CEO");service.enable(a.id,"CEO");}const requirement=new MarketSourceRequirement({capability:cap,businessPackageId:pkg,preferredSourceIds:[new MarketSourceId("source-second")]});let selection=service.select(requirement);assert.equal(selection.selected?.adapterId.value,"second");assert.deepEqual(selection.fallbackCandidates.map(x=>x.adapterId.value),["first","third"]);assert.equal(service.select(new MarketSourceRequirement({capability:cap,businessPackageId:new BusinessPackageId("UNKNOWN")})).selected,undefined);service.unavailable(new MarketSourceAdapterId("second"),"TCO");selection=service.select(requirement);assert.equal(selection.selected?.adapterId.value,"first");});

test("keeps unavailable, maintenance, HOLD, disabled, and retired lifecycle states distinct and supports recovery",()=>{const audit=new AuditRecorder(),service=new MarketSourceIntegrationService(undefined,undefined,audit,()=>now),a=adapter("lifecycle");service.register(a,"CEO");assert.equal(service.enable(a.id,"CEO").state,MarketSourceState.Available);assert.equal(service.unavailable(a.id,"TCO").state,MarketSourceState.Unavailable);assert.equal(service.restore(a.id,"TCO").health.state,MarketSourceHealthState.Healthy);assert.equal(service.maintenance(a.id,"TCO").state,MarketSourceState.Maintenance);assert.equal(service.select(new MarketSourceRequirement({capability:cap,businessPackageId:pkg})).selected,undefined);assert.equal(service.restore(a.id,"TCO").state,MarketSourceState.Available);assert.equal(service.hold(a.id,"CEO").state,MarketSourceState.OnHold);assert.equal(service.resume(a.id,"CEO").state,MarketSourceState.Available);assert.equal(service.disable(a.id,"CEO").state,MarketSourceState.Disabled);assert.equal(service.enable(a.id,"CEO").state,MarketSourceState.Available);assert.equal(service.retire(a.id,"CEO").state,MarketSourceState.Retired);assert.ok(service.registry.descriptor(a.id));assert.throws(()=>service.enable(a.id,"CEO"),/Retired/);assert.equal(audit.getEvents().length,11);});

test("keeps registration separate from package authorization",()=>{const service=new MarketSourceIntegrationService(),a=adapter("authorization",1,other);service.register(a,"CEO");service.enable(a.id,"CEO");assert.equal(service.select(new MarketSourceRequirement({capability:cap,businessPackageId:pkg})).selected,undefined);service.authorize(a.id,{businessPackageId:pkg,capabilities:[cap]},"CEO");assert.equal(service.select(new MarketSourceRequirement({capability:cap,businessPackageId:pkg})).selected?.adapterId.value,"authorization");});

test("validates provider-independent collection contracts and distinct outcomes",()=>{assert.throws(()=>new MarketCollectionRequest({id:"",capability:cap,businessPackageId:pkg,marketContext:"global",correlationId:"c",workflowOrTcoReference:"workflow:1",requestedAt:now}),/required/);const request=new MarketCollectionRequest({id:"request-1",capability:cap,businessPackageId:pkg,marketContext:"global",languageContext:"en",subjectReference:"subject:1",freshness:new Freshness(FreshnessStatus.Current,now),correlationId:"c",workflowOrTcoReference:"tco-task:1",requestedAt:now});const a=adapter("contracts"),p=a.descriptor().source.id,prov=new Provenance("collected",now,p,[request.id]);assert.notEqual(MarketCollectionResultStatus.NoData,MarketCollectionResultStatus.Failed);assert.notEqual(MarketCollectionResultStatus.Unavailable,MarketCollectionResultStatus.NoData);assert.throws(()=>new MarketCollectionResult(request.id,a.id,p,MarketCollectionResultStatus.Failed,[],now,prov),/requires a failure/);assert.equal(new MarketCollectionResult(request.id,a.id,p,MarketCollectionResultStatus.Failed,[],now,prov,new MarketSourceFailure(MarketSourceFailureCategory.Timeout,"Timed out",now)).status,MarketCollectionResultStatus.Failed);});

test("preserves raw and normalized provenance and rejects invalid normalization",()=>{const a=adapter("normalization"),sourceId=a.descriptor().source.id,prov=new Provenance("provider-record",now,sourceId,["request-1"]),raw=new RawMarketRecord({id:"raw-1",sourceId,requestId:"request-1",providerRecordReference:"record-1",collectedAt:now,observedAt:now,payloadReference:"object-store:raw-1",provenance:prov,recordType:"trend"});const observation=new MarketObservation(new ObservationId("observation-1"),sourceId,now,"global",pkg,"subject","trend","normalized:1",prov,new Freshness(FreshnessStatus.Current,now),new Confidence(.7));const result=new MarketNormalizationResult(raw,observation,MarketNormalizationStatus.Normalized,[],prov,now);assert.equal(result.rawRecord.provenance,result.observation?.provenance);assert.throws(()=>new MarketNormalizationResult(raw,observation,MarketNormalizationStatus.Rejected,["invalid"],prov,now),/cannot become/);assert.equal(new MarketNormalizationResult(raw,undefined,MarketNormalizationStatus.Rejected,["invalid"],prov,now).status,MarketNormalizationStatus.Rejected);});

test("represents generic rate limits without retry execution",()=>{const sourceId=new MarketSourceId("rate-source"),prov=new Provenance("response-metadata",now,sourceId),retry=new Date("2026-08-08T00:01:00Z"),state=new MarketSourceRateLimit(true,now,prov,retry,"window:1");assert.equal(state.limited,true);assert.equal(state.retryAfter?.toISOString(),retry.toISOString());});

test("allows provider replacement and recovery through unchanged capability contracts",()=>{const service=new MarketSourceIntegrationService(),old=adapter("old",1),replacement=adapter("replacement",2);service.register(old,"CEO");service.register(replacement,"CEO");service.enable(old.id,"CEO");service.enable(replacement.id,"CEO");service.maintenance(old.id,"TCO");assert.equal(service.select(new MarketSourceRequirement({capability:cap,businessPackageId:pkg})).selected?.adapterId.value,"replacement");service.restore(old.id,"TCO");assert.equal(service.select(new MarketSourceRequirement({capability:cap,businessPackageId:pkg})).selected?.adapterId.value,"old");});
