import assert from "node:assert/strict";import {test} from "node:test";
import {AuditRecorder} from "../../src/core/platform/AuditRecorder.ts";import {EventBus} from "../../src/core/platform/EventBus.ts";import {InMemoryRepository} from "../../src/core/platform/Repository.ts";import {OperationalTask} from "../../src/core/platform/OperationalTask.ts";
import {BusinessPackageId,MarketSourceId,Provenance} from "../../src/intelligence/market/MarketIntelligenceDomain.ts";
import {FULL_MARKET_INTELLIGENCE_SEQUENCE,MarketIntelligenceCapability,MarketIntelligenceCapabilityMode,MarketIntelligenceCycleDefinition,MarketIntelligenceCycleId,MarketIntelligenceCycleState,MarketIntelligenceCycleType,MarketIntelligenceSchedule,MarketIntelligenceScope} from "../../src/intelligence/market/orchestration/MarketIntelligenceOrchestrationDomain.ts";
import {MarketIntelligenceOrchestrator} from "../../src/intelligence/market/orchestration/MarketIntelligenceOrchestrator.ts";import type {TcoMarketIntelligenceBoundary} from "../../src/intelligence/market/orchestration/MarketIntelligenceOrchestrator.ts";import {MarketIntelligenceRunRepository} from "../../src/intelligence/market/orchestration/MarketIntelligenceRunRepository.ts";
const at=new Date("2026-01-01T00:00:00Z"),due=new Date("2026-01-31T00:00:00Z"),pkg=new BusinessPackageId("ALIVO"),other=new BusinessPackageId("BEST-FINDS"),provenance=new Provenance("CEO-approved",at,new MarketSourceId("governance"),["ARCHITECTURE-003"]);
class Boundary implements TcoMarketIntelligenceBoundary {readonly requests:OperationalTask[]=[];request(task:OperationalTask){this.requests.push(task);return `tco-${task.taskIdentifier}`;}}
function definition(id="cycle",businessPackageId=pkg,mode=MarketIntelligenceCapabilityMode.Active,type=MarketIntelligenceCycleType.CompetitiveReview){const capability=MarketIntelligenceCapability.CompetitiveIntelligence;return new MarketIntelligenceCycleDefinition({id:new MarketIntelligenceCycleId(id),name:"Governed market review",type,scope:new MarketIntelligenceScope(businessPackageId,new Map([[capability,mode]])),enabled:true,schedule:new MarketIntelligenceSchedule(30,due),workflowReference:"approved-workflow-v1",requiredCapability:capability,createdAt:at,provenance});}
function setup(...definitions:MarketIntelligenceCycleDefinition[]){const repository=new MarketIntelligenceRunRepository(new InMemoryRepository()),boundary=new Boundary(),audit=new AuditRecorder(),orchestrator=new MarketIntelligenceOrchestrator(repository,boundary,new EventBus(),audit);for(const d of definitions)orchestrator.create(d,"CEO",at);return{repository,boundary,audit,orchestrator};}
test("cycle identity, definition, scope and configurable default schedule are immutable",()=>{const id=new MarketIntelligenceCycleId("stable"),schedule=new MarketIntelligenceSchedule();assert.ok(id.equals(new MarketIntelligenceCycleId("stable")));assert.ok(Object.isFrozen(id));assert.equal(schedule.intervalDays,30);assert.equal(new MarketIntelligenceSchedule(7).intervalDays,7);assert.throws(()=>new MarketIntelligenceCycleId(""),/required/);assert.throws(()=>new MarketIntelligenceCycleDefinition({...definition().properties,workflowReference:""}),/workflow reference/i);assert.equal(definition().scope.businessPackageId.value,"ALIVO");});
test("CEO-authorized enable, disable and cadence changes control scheduling",()=>{const d=definition(),{orchestrator,audit}=setup(d);orchestrator.setEnabled(d.id.value,false,"CEO",at);assert.throws(()=>orchestrator.schedule(d.id.value,"CEO",at),/Disabled/);orchestrator.setEnabled(d.id.value,true,"CEO",at);orchestrator.changeSchedule(d.id.value,new MarketIntelligenceSchedule(7,due),"CEO",at);orchestrator.schedule(d.id.value,"CEO",at);assert.equal(orchestrator.currentSchedule(d.id.value).intervalDays,7);assert.ok(audit.getEvents().some(e=>e.action==="disable")&&audit.getEvents().some(e=>e.action==="schedule change"));});
test("scheduled runs cross only the TCO boundary and preserve approved workflow and package",()=>{const d=definition(),{orchestrator,boundary}=setup(d);orchestrator.schedule(d.id.value,"CEO",at);const run=orchestrator.requestScheduled(d.id.value,"scheduler",due,"run-1","correlation-1");assert.equal(run.state,MarketIntelligenceCycleState.Queued);assert.equal(run.businessPackageId.value,"ALIVO");assert.equal(run.properties.workflowReference,"approved-workflow-v1");assert.equal(boundary.requests.length,1);assert.equal(boundary.requests[0].relatedWorkflow,"approved-workflow-v1");assert.equal(boundary.requests[0].assignedAgent,undefined);assert.deepEqual(Object.keys(orchestrator).filter(k=>/execute|collect|analyse|agent/i.test(k)),[]);});
test("MANUAL_ONLY blocks automatic work but permits an attributable manual request",()=>{const d=definition("manual",pkg,MarketIntelligenceCapabilityMode.ManualOnly),{orchestrator,boundary}=setup(d);orchestrator.schedule(d.id.value,"CEO",at);assert.throws(()=>orchestrator.requestScheduled(d.id.value,"scheduler",due,"auto","c-auto"),/automatic/);const run=orchestrator.requestManual(d.id.value,"CEO",due,"manual-run","c-manual");assert.equal(run.properties.requestingAuthority,"CEO");assert.equal(boundary.requests.length,1);});
test("package and capability HOLD stop automatic execution without deleting schedule or history",()=>{const d=definition(),{orchestrator,repository}=setup(d);orchestrator.schedule(d.id.value,"CEO",at);orchestrator.setCapabilityHold(pkg.value,d.requiredCapability,true,"CEO",at);assert.throws(()=>orchestrator.requestScheduled(d.id.value,"scheduler",due,"held","c"),/HOLD/);orchestrator.setCapabilityHold(pkg.value,d.requiredCapability,false,"CEO",due);const run=orchestrator.requestScheduled(d.id.value,"scheduler",due,"after-hold","c2");orchestrator.setPackageHold(pkg.value,true,"CEO",due);assert.equal(repository.run(run.id.value),run);assert.equal(d.schedule.nextPlannedExecution?.toISOString(),due.toISOString());});
test("HOLD is isolated by Business Package",()=>{const a=definition("a",pkg),b=definition("b",other),{orchestrator}=setup(a,b);orchestrator.schedule(a.id.value,"CEO",at);orchestrator.schedule(b.id.value,"CEO",at);orchestrator.setPackageHold(pkg.value,true,"CEO",at);assert.throws(()=>orchestrator.requestScheduled(a.id.value,"scheduler",due,"ra","ca"),/HOLD/);assert.equal(orchestrator.requestScheduled(b.id.value,"scheduler",due,"rb","cb").businessPackageId.value,other.value);});
test("run versions preserve deterministic lifecycle, failure, retry, correlation and limitations",()=>{const d=definition(),{orchestrator,repository}=setup(d);orchestrator.schedule(d.id.value,"CEO",at);const queued=orchestrator.requestScheduled(d.id.value,"scheduler",due,"run-history","correlation"),started=orchestrator.transition(queued.id.value,MarketIntelligenceCycleState.Running,"TCO",due,{workflowInstanceReference:"workflow-instance"}),failed=orchestrator.transition(queued.id.value,MarketIntelligenceCycleState.Failed,"TCO",due,{failureReference:"failure-1",evidenceLimitations:["competitive evidence unavailable"]}),retry=orchestrator.requestRetry(queued.id.value,"TCO",due,"failure-1");assert.ok([queued,started,failed,retry].every(Object.isFrozen));assert.deepEqual(repository.history(queued.id.value),[queued,started,failed,retry]);assert.equal(retry.retryCount,1);assert.equal(retry.properties.correlationId,"correlation");assert.deepEqual(failed.evidenceLimitations,["competitive evidence unavailable"]);assert.throws(()=>orchestrator.transition(queued.id.value,MarketIntelligenceCycleState.Completed,"TCO",due),/Invalid cycle transition/);});
test("pause and resume semantics append state and retain run identity",()=>{const d=definition(),{orchestrator,repository}=setup(d);orchestrator.schedule(d.id.value,"CEO",at);const q=orchestrator.requestScheduled(d.id.value,"scheduler",due,"continuity","cc"),paused=orchestrator.transition(q.id.value,MarketIntelligenceCycleState.Paused,"TCO",due),resumed=orchestrator.transition(q.id.value,MarketIntelligenceCycleState.Queued,"TCO",due);assert.equal(paused.id.value,resumed.id.value);assert.equal(repository.history(q.id.value).length,3);});
test("repository queries are deterministic, isolated and audit actions are attributable",()=>{const a=definition("z",pkg),b=definition("a",other),{repository,audit}=setup(a,b);assert.deepEqual(repository.definitions().map(d=>d.id.value),["a","z"]);assert.deepEqual(repository.definitions({businessPackageId:pkg.value}).map(d=>d.id.value),["z"]);assert.ok(audit.getEvents().every(e=>e.responsibleIdentity==="CEO"&&e.context?.businessPackageId));});
test("full cycle is metadata-only and preserves conditional learning boundary",()=>{assert.deepEqual(FULL_MARKET_INTELLIGENCE_SEQUENCE,[MarketIntelligenceCapability.MarketObservation,MarketIntelligenceCapability.CompetitiveIntelligence,MarketIntelligenceCapability.PatternIntelligence,MarketIntelligenceCapability.PerformanceIntelligence,MarketIntelligenceCapability.OpportunityIntelligence,MarketIntelligenceCapability.RecommendationEngine,MarketIntelligenceCapability.ContinuousLearning]);assert.ok(Object.isFrozen(FULL_MARKET_INTELLIGENCE_SEQUENCE));});
