import assert from "node:assert/strict";import {test} from "node:test";
import {InMemoryRepository} from "../../src/core/platform/Repository.ts";
import {BusinessPackageId,Confidence,Evidence,EvidenceId,EvidenceStatus,Freshness,FreshnessStatus,MarketSourceId,ObservationId,Provenance} from "../../src/intelligence/market/MarketIntelligenceDomain.ts";
import {MarketOpportunity,OpportunityCandidate,OpportunityEffort,OpportunityId,OpportunityPriority,OpportunityRisk,OpportunityScope,OpportunityStatus,OpportunityType,OpportunityValue} from "../../src/business/market/opportunities/OpportunityIntelligenceDomain.ts";
import {OpportunityRepository} from "../../src/business/market/opportunities/OpportunityRepository.ts";import {OpportunityIntelligenceService} from "../../src/business/market/opportunities/OpportunityIntelligenceService.ts";
const pkg=new BusinessPackageId("alivo"),other=new BusinessPackageId("best-finds"),first=new Date("2026-01-01T00:00:00Z"),now=new Date("2026-01-02T00:00:00Z");
function evidence(id:string,source=id,at=first){const sid=new MarketSourceId(source),p=new Provenance("verified",at,sid,[id]);return new Evidence(new EvidenceId(id),[new ObservationId(`observation-${id}`)],p,at,new Confidence(.8),new Freshness(FreshnessStatus.Current,at),EvidenceStatus.Active);}
function candidate(id="b",businessPackageId=pkg,support=[evidence(`e-${id}`)]){return new OpportunityCandidate({id:new OpportunityId(id),type:OpportunityType.Keyword,title:"Evidence-backed keyword gap",description:"A possible area of market value",businessPackageId,scope:new OpportunityScope(businessPackageId,{language:"de",topic:"topic-x"}),supportingEvidence:support,firstDetectedAt:first,latestEvidenceAt:first,provenance:(support[0]??evidence("required-provenance")).provenance});}
function setup(c=candidate()){const repository=new OpportunityRepository(new InMemoryRepository()),service=new OpportunityIntelligenceService(repository);service.registerCandidate(c);return{repository,service,c};}
test("identity, generic types, scope and evidence-backed candidate are immutable",()=>{const id=new OpportunityId("stable");assert.ok(id.equals(new OpportunityId("stable")));assert.equal(Object.isFrozen(id),true);assert.throws(()=>new OpportunityId(""),/empty/);assert.throws(()=>candidate("none",pkg,[]),/supporting evidence/);assert.throws(()=>new OpportunityScope(pkg,{}),/explicit dimension/);assert.ok([OpportunityType.Keyword,OpportunityType.Content,OpportunityType.Visual,OpportunityType.EmergingDemand].every(x=>Object.values(OpportunityType).includes(x)));});
test("deterministic evaluation preserves uncertainty and produces inspectable qualitative results",()=>{const {service,c}=setup(),evaluation=service.evaluate(c,now,{effort:OpportunityEffort.Low});assert.equal(evaluation.value,OpportunityValue.Low);assert.equal(evaluation.effort,OpportunityEffort.Low);assert.equal(evaluation.risk,OpportunityRisk.Moderate);assert.notEqual(evaluation.priority,OpportunityPriority.Unranked);assert.ok(evaluation.factors.length>0);assert.equal(service.evaluateEffort(),OpportunityEffort.Unknown);});
test("support and contradiction append immutable opportunity versions",()=>{const {service,repository,c}=setup(),one=service.evaluateCandidate(c,now,{effort:OpportunityEffort.Low}),conflict=evidence("conflict","other",now),two=service.attachContradictoryEvidence(one.id,pkg,conflict,now);assert.equal(one.version,1);assert.equal(two.version,2);assert.equal(one.evidence.contradicting.length,0);assert.equal(two.evidence.supporting[0],c.supportingEvidence[0]);assert.equal(two.evidence.contradicting[0],conflict);assert.deepEqual(repository.history(one.id,pkg),[one,two]);assert.ok(Object.isFrozen(one));});
test("stale evidence expires while emerging evidence remains eligible for evaluation",()=>{const emerging=candidate("emerging"),{service}=setup(emerging),fresh=service.evaluateCandidate(emerging,now,{effort:OpportunityEffort.Low});assert.notEqual(fresh.status,OpportunityStatus.Rejected);const staleCandidate=candidate("stale"),staleSetup=setup(staleCandidate),expired=staleSetup.service.evaluateCandidate(staleCandidate,new Date("2027-01-01"),{effort:OpportunityEffort.Low});assert.equal(expired.freshness.status,FreshnessStatus.Expired);assert.equal(expired.status,OpportunityStatus.Expired);});
test("declining evidence is retained and explicitly weakens the opportunity",()=>{const support=[evidence("a","one"),evidence("b","two")],c=candidate("decline",pkg,support),{service}=setup(c),initial=service.evaluateCandidate(c,now,{effort:OpportunityEffort.Low}),one=service.attachContradictoryEvidence(initial.id,pkg,evidence("x","three",now),now),two=service.attachContradictoryEvidence(one.id,pkg,evidence("y","four",now),now);assert.equal(two.status,OpportunityStatus.Weakening);assert.equal(two.evidence.contradicting.length,2);});
test("repository ordering and Business Package isolation are deterministic",()=>{const repository=new OpportunityRepository(new InMemoryRepository()),service=new OpportunityIntelligenceService(repository),z=candidate("z",pkg),a=candidate("a",other);for(const c of [z,a]){service.registerCandidate(c);service.evaluateCandidate(c,now,{effort:OpportunityEffort.Low});}assert.deepEqual(service.query().map(o=>`${o.businessPackageId.value}:${o.id.value}`),["alivo:z","best-finds:a"]);assert.deepEqual(service.query({businessPackageId:pkg}).map(o=>o.id.value),["z"]);assert.equal(service.retrieve(z.id,other),undefined);});
test("RecommendationCandidate is advisory state and exposes no recommendation, workflow, or publishing authority",()=>{const {service,c}=setup(),evaluated=service.evaluateCandidate(c,now,{effort:OpportunityEffort.Low});const qualified=service.reEvaluate(evaluated,{status:OpportunityStatus.Qualified,priority:OpportunityPriority.Normal},now),advisory=service.createRecommendationCandidate(qualified.id,pkg,now);assert.equal(advisory.status,OpportunityStatus.RecommendationCandidate);assert.deepEqual(Object.keys(service).filter(k=>/recommendation$|workflow|publish/i.test(k)),[]);});
test("MarketOpportunity validates immutable version history",()=>{const {service,c}=setup(),o=service.evaluateCandidate(c,now,{effort:OpportunityEffort.Low});assert.ok(o instanceof MarketOpportunity);assert.ok(Object.isFrozen(o));assert.throws(()=>new MarketOpportunity({...o.properties,version:0}),/version/);});
