import assert from "node:assert/strict";import {test} from "node:test";
import {InMemoryRepository} from "../../src/core/platform/Repository.ts";
import {BusinessPackageId,Confidence,Evidence,EvidenceId,EvidenceStatus,Freshness,FreshnessStatus,MarketObservation,MarketSourceId,ObservationId,Provenance} from "../../src/intelligence/market/MarketIntelligenceDomain.ts";
import {CrossMarketValidationResult,PatternCandidate,PatternDecay,PatternDirection,PatternEvidenceRole,PatternId,PatternStability,PatternStatus,PatternType,PatternWindow} from "../../src/business/market/patterns/PatternIntelligenceDomain.ts";
import {PatternRepository} from "../../src/business/market/patterns/PatternRepository.ts";import {PatternIntelligenceService} from "../../src/business/market/patterns/PatternIntelligenceService.ts";
const pkg=new BusinessPackageId("alivo"),other=new BusinessPackageId("best-finds"),start=new Date("2026-01-01T00:00:00Z"),now=new Date("2026-01-03T00:00:00Z");
function item(id:string,source:string,day:number,p=pkg,context="market-a"){const at=new Date(Date.UTC(2026,0,day)),sid=new MarketSourceId(source),provenance=new Provenance("public",at,sid,[id]),observation=new MarketObservation(new ObservationId(`o-${id}`),sid,at,context,p,"subject","behaviour","payload",provenance,new Freshness(FreshnessStatus.Current,at),new Confidence(.8)),evidence=new Evidence(new EvidenceId(`e-${id}`),[observation.id],provenance,at,new Confidence(.8),new Freshness(FreshnessStatus.Current,at),EvidenceStatus.Active);return{observation,evidence};}
function setup(entries=[item("a","one",1),item("b","two",2)],p=pkg){const candidate=new PatternCandidate(new PatternId("repeat"),PatternType.Behavioural,"Repeated observable behaviour",p,entries.map(x=>x.evidence),entries.map(x=>x.observation),[],start,new Date(Math.max(...entries.map(x=>x.observation.observedAt.getTime()))));const repository=new PatternRepository(new InMemoryRepository()),service=new PatternIntelligenceService(repository);service.registerCandidate(candidate);return{candidate,repository,service};}
test("PatternId and candidate snapshots are immutable, validated, linked, and package isolated",()=>{const {candidate}=setup();assert.equal(Object.isFrozen(candidate),true);assert.equal(new PatternId("x").equals(new PatternId("x")),true);assert.throws(()=>new PatternId(""),/empty/);assert.throws(()=>new PatternWindow(now,start,2,2),/invalid/);assert.throws(()=>setup([item("foreign","x",1,other)]),/Business Package/);});
test("directions represent positive, negative, neutral and contradictory patterns",()=>{for(const direction of Object.values(PatternDirection)){const {candidate,service}=setup();assert.equal(service.evaluateCandidate(candidate,direction,new Map(),now).direction,direction);}});
test("duplicates and same-source observations cannot manufacture independent verification",()=>{const a=item("a","same",1),copy=item("copy","same",1),{candidate,service}=setup([a,a,copy]);const observed=service.evaluateCandidate(candidate,PatternDirection.Positive,new Map(),now);assert.equal(observed.window.independentObservationCount,1);assert.equal(observed.evidence.evidenceCount,2);assert.throws(()=>service.verifyEligible(observed.id,pkg,now),/multiple independent/);});
test("independent evidence verifies, preserves provenance, and confidence is deterministic and explainable",()=>{const {candidate,service}=setup(),one=service.evaluateCandidate(candidate,PatternDirection.Positive,new Map(),now);const verified=service.verifyEligible(one.id,pkg,now);assert.equal(verified.status,PatternStatus.Verified);assert.equal(verified.evidence.provenances[0],candidate.evidence[0].provenance);assert.equal(service.evaluateConfidence(one.evidence,one.freshness,one.crossMarketValidation).value,one.confidence.value);assert.ok(one.confidence.factors.length>0);});
test("contradictions create weakening immutable history without discarding either side",()=>{const {candidate,service,repository}=setup(),first=service.evaluateCandidate(candidate,PatternDirection.Positive,new Map(),now),conflict=item("c","three",3).evidence,second=service.attachContradictoryEvidence(first.id,pkg,conflict,new Date("2026-01-04"));assert.equal(second.direction,PatternDirection.Contradictory);assert.equal(second.status,PatternStatus.Weakening);assert.equal(second.evidence.supporting.length,2);assert.equal(second.evidence.contradicting[0],conflict);assert.equal(repository.history(first.id,pkg)[0],first);assert.equal(first.evidence.contradicting.length,0);});
test("freshness, stability, decay and cross-market support are deterministic",()=>{const entries=[item("a","one",1,pkg,"a"),item("b","two",2,pkg,"b"),item("c","three",3,pkg,"b"),item("d","four",3,pkg,"a")],{candidate,service}=setup(entries),pattern=service.evaluateCandidate(candidate,PatternDirection.Positive,new Map(),now);assert.equal(pattern.stability,PatternStability.Stable);assert.equal(pattern.decay,PatternDecay.None);assert.equal(pattern.crossMarketValidation.result,CrossMarketValidationResult.MultiContextSupported);assert.equal(service.evaluateFreshness(candidate.latestObservedAt,new Date("2026-08-01")).status,FreshnessStatus.Expired);assert.equal(service.evaluateDecay(new Freshness(FreshnessStatus.Expired,now),pattern.evidence),PatternDecay.Expired);});
test("repository queries are deterministic and isolate packages",()=>{const a=setup(),b=setup([item("x","x",1,other),item("y","y",2,other)],other);a.service.evaluateCandidate(a.candidate,PatternDirection.Negative,new Map([["e-a",PatternEvidenceRole.Supporting]]),now);b.service.evaluateCandidate(b.candidate,PatternDirection.Neutral,new Map(),now);assert.equal(a.repository.query({businessPackageId:pkg,direction:PatternDirection.Negative}).length,1);assert.equal(a.repository.query({businessPackageId:other}).length,0);assert.deepEqual(a.repository.query().map(x=>x.id.value),["repeat"]);});
test("Business Memory candidacy is explicit state only and no opportunity or recommendation is created",()=>{const {candidate,service}=setup(),observed=service.evaluateCandidate(candidate,PatternDirection.Positive,new Map(),now),verified=service.verifyEligible(observed.id,pkg,now),candidateState=service.createBusinessMemoryCandidate(verified.id,pkg,now);assert.equal(candidateState.status,PatternStatus.BusinessMemoryCandidate);assert.deepEqual(Object.keys(candidateState).filter(k=>/approval|opportunity|recommendation/i.test(k)),[]);});
