import assert from "node:assert/strict";
import { test } from "node:test";
import { InMemoryRepository } from "../../src/core/platform/Repository.ts";
import { BusinessPackageId, Confidence, Evidence, EvidenceId, EvidenceStatus, Freshness, FreshnessStatus, MarketSourceId, ObservationId, Provenance } from "../../src/intelligence/market/MarketIntelligenceDomain.ts";
import { ComparisonStatus, ExpectedOutcome, MeasurementWindow, MetricAvailability, ObservedOutcome, OriginReference, OutcomeClassification, PerformanceDimension, PerformanceEvaluation, PerformanceMetric, PerformanceMetricType, PerformanceObservation, PerformanceRecordId, SubjectReference } from "../../src/business/market/performance/PerformanceIntelligenceDomain.ts";
import { PerformanceRepository } from "../../src/business/market/performance/PerformanceRepository.ts";
import { PerformanceIntelligenceService } from "../../src/business/market/performance/PerformanceIntelligenceService.ts";

const pkg=new BusinessPackageId("alivo"),other=new BusinessPackageId("best-finds"),subject=new SubjectReference("content-1",PerformanceDimension.Content),source=new MarketSourceId("measurement-source"),at=new Date("2026-03-02T00:00:00Z"),window=new MeasurementWindow(new Date("2026-03-01"),new Date("2026-03-02"));
const provenance=new Provenance("supplied measurement",at,source,["measurement-context:daily"]),confidence=new Confidence(.8),freshness=new Freshness(FreshnessStatus.Current,at);
const evidence=new Evidence(new EvidenceId("e-1"),[new ObservationId("market-1")],provenance,at,confidence,freshness,EvidenceStatus.Active);
function metric(value:number|undefined,availability=MetricAvailability.Available,type=PerformanceMetricType.Clicks,unit="count",businessPackageId=pkg){return new PerformanceMetric({type,value,unit,measuredAt:at,window,provenance,availability,businessPackageId,subject,confidence});}
function expected(value?:number,availability=MetricAvailability.Available,id="expected",businessPackageId=pkg){const resolved=arguments.length===0?10:value;return new ExpectedOutcome({id:new PerformanceRecordId(id),subject,businessPackageId,metrics:[metric(resolved,availability,PerformanceMetricType.Clicks,"count",businessPackageId)],window,expectedAt:new Date("2026-02-28"),origin:new OriginReference("future-recommendation-1","Recommendation"),confidence,provenance});}
function observation(id="observation",value=10,businessPackageId=pkg){return new PerformanceObservation({id:new PerformanceRecordId(id),subject,businessPackageId,metrics:[metric(value,MetricAvailability.Available,PerformanceMetricType.Clicks,"count",businessPackageId)],measuredAt:at,window,evidence:[evidence],provenance,confidence,freshness});}
function observed(value?:number,availability=MetricAvailability.Available,id="observed",businessPackageId=pkg,observationIds:readonly PerformanceRecordId[]=[]){const resolved=arguments.length===0?10:value;return new ObservedOutcome({id:new PerformanceRecordId(id),subject,businessPackageId,observationIds,metrics:[metric(resolved,availability,PerformanceMetricType.Clicks,"count",businessPackageId)],window,evidence:[evidence],provenance,confidence});}
function setup(){const repository=new PerformanceRepository(new InMemoryRepository());return{repository,service:new PerformanceIntelligenceService(repository)};}

test("metrics validate values, explicit availability, custom names, context and provenance",()=>{assert.equal(metric(0).value,0);assert.equal(metric(undefined,MetricAvailability.Unavailable).value,undefined);assert.notEqual(metric(0).availability,MetricAvailability.Unavailable);assert.equal(metric(3,MetricAvailability.Estimated).availability,MetricAvailability.Estimated);assert.throws(()=>metric(undefined,MetricAvailability.Available),/require a value/);assert.throws(()=>metric(1,MetricAvailability.Unknown),/must not contain/);assert.throws(()=>new PerformanceMetric({...metric(1),provenance:undefined as never}),/provenance is required/);assert.throws(()=>new PerformanceMetric({type:PerformanceMetricType.Custom,value:1,unit:"score",measuredAt:at,provenance,availability:MetricAvailability.Available,businessPackageId:pkg,subject}),/Custom metric type/);});
test("measurement windows are immutable, derive duration and reject invalid timestamps",()=>{assert.equal(window.durationMilliseconds,86400000);assert.equal(Object.isFrozen(window),true);assert.throws(()=>new MeasurementWindow(at,new Date("2026-01-01")),/cannot precede/);assert.throws(()=>new MeasurementWindow(new Date("invalid"),at),/valid timestamp/);});
test("observations and outcomes preserve immutable raw measurements, provenance, evidence and recommendation origins",()=>{const input=[metric(10)],o=new PerformanceObservation({id:new PerformanceRecordId("immutable"),subject,businessPackageId:pkg,metrics:input,measuredAt:at,window,evidence:[evidence],provenance,confidence,freshness});input.push(metric(20));assert.equal(o.metrics.length,1);assert.equal(Object.isFrozen(o),true);assert.equal(o.provenance,provenance);const ex=expected();assert.equal(ex.origin?.type,"Recommendation");assert.equal(Object.isFrozen(ex),true);const actual=observed(7);assert.equal(actual.metrics[0].value,7);assert.equal(actual.evidence[0],evidence);assert.equal(Object.isFrozen(actual),true);assert.throws(()=>new ExpectedOutcome({...ex.properties,expectedAt:window.start}),/before/);});
test("compatible comparisons are deterministic and division by zero never manufactures a ratio",()=>{const {service}=setup(),above=service.compare(expected(10),observed(15))[0],zero=service.compare(expected(0),observed(0))[0];assert.equal(above.status,ComparisonStatus.Exceeded);assert.equal(above.absoluteDifference,5);assert.equal(above.relativeDifference,.5);assert.equal(zero.status,ComparisonStatus.Neutral);assert.equal(zero.relativeDifference,undefined);assert.throws(()=>service.compare(expected(10),new ObservedOutcome({...observed(10).properties,metrics:[metric(10,MetricAvailability.Available,PerformanceMetricType.Clicks,"percent")]})),/incompatible units/);});
test("unavailable and unknown comparisons do not calculate, while estimated remains explicit",()=>{const {service}=setup(),unavailable=service.compare(expected(10),observed(undefined,MetricAvailability.Unavailable))[0],unknown=service.compare(expected(10),observed(undefined,MetricAvailability.Unknown))[0],estimated=service.compare(expected(10),observed(12,MetricAvailability.Estimated))[0];assert.equal(unavailable.status,ComparisonStatus.Unavailable);assert.equal(unavailable.absoluteDifference,undefined);assert.equal(unknown.status,ComparisonStatus.Inconclusive);assert.equal(estimated.availability,MetricAvailability.Estimated);});
test("evaluation rules cover every classification without inference",()=>{const cases:[[number|undefined,MetricAvailability,number|undefined,MetricAvailability,OutcomeClassification],...Array<[number|undefined,MetricAvailability,number|undefined,MetricAvailability,OutcomeClassification]>]=[[10,MetricAvailability.Available,11,MetricAvailability.Available,OutcomeClassification.Exceeded],[10,MetricAvailability.Available,10,MetricAvailability.Available,OutcomeClassification.Met],[10,MetricAvailability.Available,5,MetricAvailability.Available,OutcomeClassification.BelowExpected],[10,MetricAvailability.Available,0,MetricAvailability.Available,OutcomeClassification.Failed],[0,MetricAvailability.Available,0,MetricAvailability.Available,OutcomeClassification.Neutral],[10,MetricAvailability.Available,undefined,MetricAvailability.Unknown,OutcomeClassification.Inconclusive],[undefined,MetricAvailability.Unavailable,undefined,MetricAvailability.Unavailable,OutcomeClassification.Unavailable]];for(const [ev,ea,ov,oa,result] of cases){const {service}=setup(),actual=observed(ov,oa,`o-${result}`);service.registerObservedOutcome(actual);const evaluation=service.evaluate(new PerformanceRecordId(`evaluation-${result}`),expected(ev,ea,`e-${result}`),actual,at);assert.equal(evaluation.classification,result);assert.equal(Object.isFrozen(evaluation),true);}});
test("repository preserves histories, deterministic order and Business Package isolation",()=>{const {repository,service}=setup(),later=observation("z",20),earlier=new PerformanceObservation({...observation("a").properties,measuredAt:new Date("2026-03-01T12:00:00Z")});service.registerObservation(later);service.registerObservation(earlier);service.registerObservation(observation("foreign",1,other));const actual=observed(10,MetricAvailability.Available,"actual",pkg,[earlier.id]);service.registerObservedOutcome(actual);const first=service.evaluate(new PerformanceRecordId("eval-b"),expected(),actual,new Date("2026-03-04")),second=service.evaluate(new PerformanceRecordId("eval-a"),expected(10,MetricAvailability.Available,"expected-2"),actual,new Date("2026-03-03"));assert.deepEqual(repository.history({businessPackageId:pkg}).observations.map(x=>x.id.value),["a","z"]);assert.equal(repository.history({businessPackageId:other}).observations.length,1);assert.deepEqual(service.evaluations({businessPackageId:pkg,subjectId:subject.id,metricType:PerformanceMetricType.Clicks}).map(x=>x.id.value),["eval-a","eval-b"]);assert.equal(first.provenance,provenance);assert.equal(second.observedOutcomeId.value,"actual");assert.throws(()=>service.registerObservation(later),/already exists/);});
test("cross-package outcome links are rejected and service has no higher-level mutation operations",()=>{const {service}=setup(),record=observation();service.registerObservation(record);assert.throws(()=>service.registerObservedOutcome(observed(1,MetricAvailability.Available,"wrong",other,[record.id])),/another Business Package/);assert.deepEqual(Object.getOwnPropertyNames(PerformanceIntelligenceService.prototype).filter(x=>/opportunity|recommend|pattern|memory|workflow|publish|optim/i.test(x)),[]);});
