import assert from "node:assert/strict";
import test from "node:test";
import { BusinessPackageId } from "../../src/intelligence/market/MarketIntelligenceDomain.ts";
import { MarketCollectionRequest, MarketCollectionResultStatus, MarketNormalizationStatus, MarketSourceCapability, MarketSourceFailureCategory, MarketSourceState } from "../../src/intelligence/market/integration/MarketSourceIntegrationDomain.ts";
import { MarketSourceIntegrationService } from "../../src/intelligence/market/integration/MarketSourceIntegrationService.ts";
import { AuthenticationSessionReference, ExternalAuthenticationFailureType } from "../../src/security/authentication/ExternalAuthenticationDomain.ts";
import { CredentialId } from "../../src/security/credentials/CredentialVault.ts";
import { PinterestAccessTier, PinterestEnvironment, PinterestMarketSourceAdapter, PinterestOwnership, PinterestTimeoutError, PinterestValueState } from "../../src/integrations/pinterest/PinterestMarketSourceAdapter.ts";
import type { PinterestAuthenticationBoundary, PinterestOperationalReporter, PinterestQualityGate, PinterestTransport, PinterestTransportResponse } from "../../src/integrations/pinterest/PinterestMarketSourceAdapter.ts";

const at=new Date("2026-08-09T12:00:00.000Z"),pkg=new BusinessPackageId("ALIVO"),credential=new CredentialId("credential:pinterest:alivo");
const capabilities=[MarketSourceCapability.ContentDiscovery,MarketSourceCapability.VisualMetadata,MarketSourceCapability.MarketObservation,MarketSourceCapability.TrendObservation,MarketSourceCapability.PerformanceObservation];
class Auth implements PinterestAuthenticationBoundary { failure?:ExternalAuthenticationFailureType;reported?:ExternalAuthenticationFailureType;requests:any[]=[];async authenticate(request:any){this.requests.push(request);return this.failure?{successful:false as const,failure:this.failure}:{successful:true as const,session:new AuthenticationSessionReference("opaque-session","Pinterest",request.properties.businessPackageId)};}async reportProviderFailure(_request:any,failure:ExternalAuthenticationFailureType){this.reported=failure;} }
class Transport implements PinterestTransport { calls:any[]=[];responses:Array<PinterestTransportResponse|Error>=[];async execute(request:any){this.calls.push(request);const response=this.responses.shift();if(response instanceof Error)throw response;return response??{status:200,body:{items:[]}};} }
class Quality implements PinterestQualityGate { accepted=true;calls:any[]=[];validate(input:any){this.calls.push(input);return {accepted:this.accepted};} }
class Reporter implements PinterestOperationalReporter { entries:Array<{name:string;context:Readonly<Record<string,string>>}>=[];report(name:string,context:Readonly<Record<string,string>>){this.entries.push({name,context});} }
function fixture(options:{transport?:Transport;auth?:Auth;quality?:Quality;reporter?:Reporter;maximumPages?:number;businessPackage?:BusinessPackageId}={}){const transport=options.transport??new Transport(),auth=options.auth??new Auth(),quality=options.quality??new Quality(),reporter=options.reporter??new Reporter(),businessPackage=options.businessPackage??pkg;const adapter=new PinterestMarketSourceAdapter(credential,businessPackage,{environment:PinterestEnvironment.Sandbox,apiBaseUrl:"https://sandbox-api.pinterest.test",accessTier:PinterestAccessTier.Trial,approvedCapabilities:capabilities,requestedScopes:["pins:read","boards:read","analytics:read"],pageSize:2,maximumPages:options.maximumPages??3,timeoutMs:2500,adapterVersion:"1.0.0"},auth,transport,quality,reporter,()=>new Date(at));return {adapter,transport,auth,quality,reporter};}
function request(capability=MarketSourceCapability.MarketObservation,overrides:Record<string,unknown>={}){return new MarketCollectionRequest({id:"collection-1",capability,businessPackageId:pkg,marketContext:"US",languageContext:"en",subjectReference:"summer",correlationId:"correlation-1",workflowOrTcoReference:"tco-task-1",requestedAt:at,...overrides});}

test("registers a separate stable Pinterest source and adapter with explicit read capabilities and CredentialId",()=>{const {adapter}=fixture(),service=new MarketSourceIntegrationService();const descriptor=service.register(adapter,"tester");assert.equal(adapter.id.value,"PinterestMarketSourceAdapter");assert.equal(descriptor.source.id.value,"Pinterest");assert.notEqual(descriptor.source.id.value,adapter.id.value);assert.equal(descriptor.properties.credentialId,credential);assert.deepEqual(descriptor.capabilities.map(x=>x.value),capabilities.map(x=>x.value));assert.equal(descriptor.authorized(pkg,MarketSourceCapability.TrendObservation),true);assert.equal(Object.keys(adapter).some(key=>/token|secret|password|cookie/i.test(key)),false);assert.equal(service.hold(adapter.id,"tester").state,MarketSourceState.OnHold);});

test("uses External Authentication and normalizes an allowlisted production Pin response through quality",async()=>{const f=fixture();f.transport.responses.push({status:200,body:{items:[{id:"pin-1",created_at:"2026-08-09T11:00:00Z",title:"Summer",description:"Ideas",link:"https://example.test/item",board_id:"board-1",media:{type:"image",width:800,height:600,url:"https://images.example.test/pin.jpg"},is_owner:true,unknown_provider_field:"discard"}]}});const result=await f.adapter.collect(request());assert.equal(result.status,MarketCollectionResultStatus.Success);assert.equal(result.rawRecords[0].properties.providerRecordReference,"pin:pin-1");assert.equal(result.rawRecords[0].properties.observedAt?.toISOString(),"2026-08-09T11:00:00.000Z");assert.equal(f.auth.requests[0].properties.credentialId,credential);assert.equal(f.auth.requests[0].properties.businessPackageId.value,"ALIVO");assert.equal(f.transport.calls[0].session.opaqueReference,"opaque-session");assert.deepEqual(f.transport.calls[0].query,{page_size:"2"});const normalized=await f.adapter.normalize(result.rawRecords[0]);assert.equal(normalized.status,MarketNormalizationStatus.Normalized);const payload=JSON.parse(normalized.observation!.payloadReference);assert.equal(payload.resourceType,"pin");assert.equal(payload.ownership,PinterestOwnership.OwnedAuthorizedResource);assert.equal(payload.createdAt,"2026-08-09T11:00:00.000Z");assert.equal(payload.boardReference,"board-1");assert.deepEqual(payload.media,{type:"image",width:800,height:600,url:"https://images.example.test/pin.jpg"});assert.equal("unknown_provider_field" in payload,false);assert.equal(payload.competitorPrivateMetrics.clicks,PinterestValueState.Unavailable);assert.notEqual(payload.competitorPrivateMetrics.clicks,0);assert.equal(payload.dataState,PinterestValueState.Observed);assert.equal(normalized.observation!.businessPackageId?.value,"ALIVO");assert.equal(normalized.provenance.sourceId.value,"Pinterest");assert.equal(f.quality.calls.length,1);});

test("does not synthesize Pin creation evidence when Pinterest omits created_at",async()=>{const f=fixture();f.transport.responses.push({status:200,body:{items:[{id:"pin-without-created-at",title:"Undated",is_owner:true}]}});const result=await f.adapter.collect(request()),normalized=await f.adapter.normalize(result.rawRecords[0]),payload=JSON.parse(normalized.observation!.payloadReference);assert.equal(normalized.status,MarketNormalizationStatus.Normalized);assert.equal("createdAt" in payload,false);});

test("preserves owned analytics, metric zero, measurement window, and ownership without business conclusions",async()=>{const f=fixture();f.transport.responses.push({status:200,body:{items:[{id:"analytics-pin-1",type:"analytics",ownership:PinterestOwnership.OwnedAuthorizedResource,metric:"IMPRESSION",value:0,windowStart:"2026-08-01",windowEnd:"2026-08-08",observedAt:"2026-08-09T11:00:00Z"}]}});const result=await f.adapter.collect(request(MarketSourceCapability.PerformanceObservation));const normalized=await f.adapter.normalize(result.rawRecords[0]),payload=JSON.parse(normalized.observation!.payloadReference);assert.equal(payload.ownership,PinterestOwnership.OwnedAuthorizedResource);assert.equal(payload.analytics.value,0);assert.equal(payload.analytics.metric,"IMPRESSION");assert.equal(payload.analytics.windowStart,"2026-08-01");assert.equal(payload.competitorPrivateMetrics.ctr,PinterestValueState.Unavailable);});

test("normalizes board and trend observations while preserving rank, region, and returned growth",async()=>{const f=fixture();f.transport.responses.push({status:200,body:{items:[{id:"board-1",type:"board",ownership:PinterestOwnership.PublicExternalResource,title:"Public board"},{id:"trend-1",type:"trend",ownership:PinterestOwnership.UnknownOwnership,keyword:"summer shoes",rank:2,region:"US",growth:1.25}]}});const result=await f.adapter.collect(request(MarketSourceCapability.TrendObservation));const board=JSON.parse((await f.adapter.normalize(result.rawRecords[0])).observation!.payloadReference),trend=JSON.parse((await f.adapter.normalize(result.rawRecords[1])).observation!.payloadReference);assert.equal(board.resourceType,"board");assert.equal(trend.keyword,"summer shoes");assert.equal(trend.rank,2);assert.equal(trend.region,"US");assert.equal(trend.growth,1.25);});

test("routes initial and provider 401 failures safely through External Authentication",async()=>{const initial=fixture();initial.auth.failure=ExternalAuthenticationFailureType.ExpiredToken;assert.equal((await initial.adapter.collect(request())).status,MarketCollectionResultStatus.Failed);assert.equal(initial.reporter.entries.at(-1)?.name,"PinterestAuthenticationRequired");const provider=fixture();provider.transport.responses.push({status:401,body:{}});const result=await provider.adapter.collect(request());assert.equal(result.failure?.category,"AuthenticationFailure");assert.equal(provider.auth.reported,ExternalAuthenticationFailureType.ReauthorizationRequired);assert.equal(provider.auth.requests[0].properties.interruptedOperation.properties.marketCollectionRequestReference,"collection-1");});

test("keeps permission, rate limit, no-data, timeout, network, and malformed responses distinct",async()=>{for(const [response,status,category] of [[{status:403,body:{}},MarketCollectionResultStatus.Failed,"AuthorizationFailure"],[{status:429,body:{},headers:{"retry-after":"30","x-ratelimit-reset":"reset-1"}},MarketCollectionResultStatus.RateLimited,undefined],[{status:200,body:{items:[]}},MarketCollectionResultStatus.NoData,undefined],[{status:200,body:{wrong:[]}},MarketCollectionResultStatus.Failed,"InvalidResponse"]] as const){const f=fixture();f.transport.responses.push(response);const result=await f.adapter.collect(request());assert.equal(result.status,status);assert.equal(result.failure?.category,category);if(status===MarketCollectionResultStatus.RateLimited){assert.equal(result.rateLimit?.limited,true);assert.equal(result.rateLimit?.retryAfter?.toISOString(),"2026-08-09T12:00:30.000Z");}}for(const error of [new PinterestTimeoutError(),new Error("socket details")]){const f=fixture();f.transport.responses.push(error);const result=await f.adapter.collect(request());assert.equal(result.status,MarketCollectionResultStatus.Failed);assert.equal(result.failure?.message.includes("socket details"),false);}});

test("rejects malformed Pin IDs and pagination envelopes",async()=>{for(const body of [{items:[{created_at:"2026-08-09T11:00:00Z"}]},{items:[{id:"   "}]},{items:[],bookmark:{unexpected:true}}]){const f=fixture();f.transport.responses.push({status:200,body});const result=await f.adapter.collect(request());assert.equal(result.status,MarketCollectionResultStatus.Failed);assert.equal(result.failure?.category,MarketSourceFailureCategory.InvalidResponse);}});

test("paginates deterministically with an actual bookmark query, deduplicates Pins, and retains prior pages on later-page failure",async()=>{const f=fixture();f.transport.responses.push({status:200,body:{items:[{id:"pin-1"}],bookmark:"next"}},{status:503,body:{}});const result=await f.adapter.collect(request());assert.equal(result.status,MarketCollectionResultStatus.Partial);assert.equal(result.rawRecords.length,1);assert.deepEqual(f.transport.calls[1].query,{page_size:"2",bookmark:"next"});const d=fixture();d.transport.responses.push({status:200,body:{items:[{id:"same"}],bookmark:"two"}},{status:200,body:{items:[{id:"same"}]}});assert.equal((await d.adapter.collect(request())).rawRecords.length,1);});

test("quality rejection never forwards an accepted MarketObservation",async()=>{const f=fixture();f.quality.accepted=false;f.transport.responses.push({status:200,body:{items:[{id:"pin-rejected",type:"pin",ownership:PinterestOwnership.PublicExternalResource}]}});const result=await f.adapter.collect(request()),normalized=await f.adapter.normalize(result.rawRecords[0]);assert.equal(normalized.status,MarketNormalizationStatus.Rejected);assert.equal(normalized.observation,undefined);assert.equal(f.reporter.entries.at(-1)?.name,"PinterestNormalizationFailed");});

test("enforces Business Package isolation and emits only safe operational metadata",async()=>{const f=fixture(),other=request(MarketSourceCapability.MarketObservation,{businessPackageId:new BusinessPackageId("BEST-FINDS")});const result=await f.adapter.collect(other);assert.equal(result.status,MarketCollectionResultStatus.Unavailable);assert.equal(f.transport.calls.length,0);const safe=JSON.stringify(f.reporter.entries);assert.equal(/opaque-session|Bearer|credential:pinterest/i.test(safe),false);});

test("configuration rejects write scopes and adapter exposes no publishing or autonomous scheduling surface",()=>{assert.throws(()=>new PinterestMarketSourceAdapter(credential,pkg,{environment:PinterestEnvironment.Production,apiBaseUrl:"https://api.pinterest.com",accessTier:PinterestAccessTier.Standard,approvedCapabilities:capabilities,requestedScopes:["pins:write"],pageSize:10,maximumPages:2,timeoutMs:1000,adapterVersion:"1"},new Auth(),new Transport(),new Quality()),/read scopes/);const {adapter}=fixture();for(const operation of ["createPin","updatePin","deletePin","savePin","schedule","startPolling","loginWithPassword","collectSessionCookie"])assert.equal(operation in adapter,false);});
