import test from "node:test";import assert from "node:assert/strict";
import {BusinessPackageId} from "../../src/intelligence/market/MarketIntelligenceDomain.ts";
import {CredentialId,CredentialStatus} from "../../src/security/credentials/CredentialVault.ts";
import {PinterestCreativeCandidateVersion,PinterestCreativeReadiness,PinterestDestinationValidation} from "../../src/integrations/pinterest/PinterestCreativeAssemblyDomain.ts";
import {PinterestQueueItem,PinterestQueueItemId,PinterestQueueItemVersion,PinterestQueuePriority,PinterestQueueRepository,PinterestQueueState,PinterestScheduledPublication,PinterestScheduleStatus} from "../../src/integrations/pinterest/PinterestSchedulingQueue.ts";
import {PinterestExecutionClaimState,PinterestPublicationId,PinterestPublisher,PinterestPublishingEnvironment,PinterestPublishingException,PinterestPublishingRepository,PinterestPublishingService,PinterestPublishState,type PinterestOfficialWriteTransport,type PinterestProviderOutcome} from "../../src/integrations/pinterest/PinterestPublisher.ts";

const at=new Date("2026-08-09T19:40:00Z"),pkg=new BusinessPackageId("ALIVO"),credentialId=new CredentialId("pinterest-alivo"),material={credentialId,use:<T>(consumer:(secret:string)=>T)=>consumer("test-value")};
function fixture(changes:any={}){const repository=new PinterestQueueRepository(),lineage={planId:"plan",planVersion:3,copyArtifactId:"copy",copyArtifactVersion:4,visualArtifactId:"visual",visualArtifactVersion:5,recommendationId:"recommendation",recommendationVersion:6,ceoDecisionId:changes.decision??"ceo-approved",opportunityReferences:["opportunity"],patternReferences:["pattern"],evidenceReferences:["evidence"]},candidate:any={id:"candidate",version:new PinterestCreativeCandidateVersion(changes.candidateVersion??2),readiness:changes.readiness??PinterestCreativeReadiness.ReadyForPublishing,businessPackageId:changes.candidatePackage??pkg,destination:{type:"Article"},destinationUrl:"https://example.invalid/approved",destinationValidation:changes.destinationValidation??PinterestDestinationValidation.Validated,title:"Exact approved title",description:"Exact approved description",accessibilityText:"Exact approved alt text",visualAssetReference:"asset://visual:5",language:"en",market:"US",experiment:{id:"experiment",variant:"A"},correlationIdentifier:"correlation",provenance:{authority:"CEO"},lineage};const item=new PinterestQueueItem(new PinterestQueueItemId("queue"),new PinterestQueueItemVersion(1),candidate,changes.itemPackage??pkg,changes.channel??"Pinterest","US","en",PinterestQueuePriority.Normal,changes.queueState??PinterestQueueState.Scheduled,0,"correlation",{publishingCandidateId:"candidate",publishingCandidateVersion:2,creationPlanId:"plan",creationPlanVersion:3,copyArtifactId:"copy",copyArtifactVersion:changes.copyVersion??4,visualArtifactId:"visual",visualArtifactVersion:5,recommendationId:"recommendation",recommendationVersion:6,ceoDecision:changes.decision??"ceo-approved",opportunityReferences:["opportunity"],patternReferences:["pattern"],evidenceReferences:["evidence"],provenance:{authority:"CEO"}},{title:candidate.title,description:candidate.description,destination:candidate.destination,freshnessState:"Current",variant:"A"},at,at);repository.insert(item);const schedule=new PinterestScheduledPublication("schedule",item.id,item.version,"candidate",changes.scheduleCandidateVersion??2,changes.schedulePackage??pkg,changes.channel??"Pinterest","US","UTC",undefined,"2026-08-09 19:40",changes.time??at,90,PinterestQueuePriority.Normal,changes.scheduleStatus??PinterestScheduleStatus.ExecutionPending,"correlation",{source:"scheduler"},at,at,0);repository.reserve("request",schedule);return{repository,item,schedule};}
function harness(changes:any={}){const f=fixture(changes),publishing=new PinterestPublishingRepository(),calls:{requests:any[]}={requests:[]},outcomes:PinterestProviderOutcome[]=changes.outcomes??[{kind:"Published",pinId:"pin-123",providerReference:"provider-123",publishedAt:at,metadata:{request:"safe"}}],transport:PinterestOfficialWriteTransport={environment:changes.transportEnvironment??PinterestPublishingEnvironment.Sandbox,async createPin(request){calls.requests.push(request);return outcomes.shift()!;}},auth={async authorize(){if(changes.authError)throw new Error(changes.authError);return{metadata:{credentialId:credentialId.value,displayName:"Pinterest",serviceReference:"Pinterest",accountReference:changes.account??"account-alivo",authenticationType:"OAuth",businessPackageScopes:changes.scopes??["ALIVO"],sharedScopeApproved:false,capabilityScopes:changes.capabilities??["pins:write"],status:changes.credentialStatus??CredentialStatus.Active,createdAt:at.toISOString(),updatedAt:at.toISOString()} as any,credential:material};},async reauthorizationRequired(){changes.reauthorized&&(changes.reauthorized.value=true);}},handoff={publishedCalls:[] as any[],failedCalls:[] as any[],published(...args:any[]){this.publishedCalls.push(args);},executionFailed(...args:any[]){this.failedCalls.push(args);}},clock=changes.clock??(()=>at),service=new PinterestPublishingService(f.repository,publishing,auth,new PinterestPublisher(transport),PinterestPublishingEnvironment.Sandbox,"account-alivo",changes.board===undefined?"board-approved":changes.board,changes.tolerance??60000,changes.retryLimit??3,handoff,changes.intervalPolicy,changes.reconciler,changes.events,changes.audit,clock);return{...f,publishing,calls,outcomes,auth,handoff,service};}

test("eligible publication uses exact scheduled creative versions and preserves result lineage",async()=>{const h=harness(),result=await h.service.execute("schedule",credentialId);assert.equal(result.state,PinterestPublishState.Published);assert.equal(result.pinReference?.pinId,"pin-123");assert.equal(result.actualPublicationTime?.toISOString(),at.toISOString());assert.equal(result.timingDeviationMilliseconds,0);assert.equal(h.calls.requests.length,1);assert.deepEqual([h.calls.requests[0].title,h.calls.requests[0].visualAssetReference],["Exact approved title","asset://visual:5"]);assert.equal((result.provenance as any).lineage.creationPlanVersion,3);assert.deepEqual((result.provenance as any).experiment,{id:"experiment",variant:"A"});assert.equal(h.handoff.publishedCalls.length,1);});

test("unscheduled, held, cancelled, rebalanced, stale, superseded and lineage-invalid items fail before write",async()=>{const cases=[{queueState:PinterestQueueState.Queued},{queueState:PinterestQueueState.Held},{scheduleStatus:PinterestScheduleStatus.Cancelled},{scheduleStatus:PinterestScheduleStatus.RebalanceRequired},{destinationValidation:PinterestDestinationValidation.Unvalidated},{readiness:PinterestCreativeReadiness.Superseded},{candidateVersion:3},{copyVersion:9},{decision:""},{schedulePackage:new BusinessPackageId("BEST-FINDS")}];for(const changes of cases){const h=harness(changes);await assert.rejects(h.service.execute("schedule",credentialId),PinterestPublishingException);assert.equal(h.calls.requests.length,0);}});

test("execution window prevents early and late writes but permits configured tolerance",async()=>{await assert.rejects(harness({clock:()=>new Date(at.getTime()-1)}).service.execute("schedule",credentialId),/has not arrived/);await assert.rejects(harness({clock:()=>new Date(at.getTime()+60001)}).service.execute("schedule",credentialId),/window was missed/);assert.equal((await harness({clock:()=>new Date(at.getTime()+60000)}).service.execute("schedule",credentialId)).state,PinterestPublishState.Published);});

test("missing board and current hard interval conflict block the official transport",async()=>{await assert.rejects(harness({board:""}).service.execute("schedule",credentialId),/Board is required/);await assert.rejects(harness({intervalPolicy:{allows:()=>false}}).service.execute("schedule",credentialId),/hard publication interval/);});

test("write credential must be active and isolated to package, account and pins:write",async()=>{for(const changes of [{capabilities:["pins:read"]},{scopes:["BEST-FINDS"]},{account:"other"},{credentialStatus:CredentialStatus.Revoked}]){const marker={value:false},h=harness({...changes,reauthorized:marker});const result=await h.service.execute("schedule",credentialId);assert.equal(result.state,PinterestPublishState.AuthenticationRecoveryRequired);assert.equal(marker.value,true);assert.equal(h.calls.requests.length,0);assert.equal(result.publicationId.value,"publication-schedule");}});

test("atomic claim and completed result prevent concurrent or repeated duplicate publication",async()=>{const h=harness(),id=new PinterestPublicationId("publication");assert.ok(h.publishing.claim("schedule",id,"worker-one",at));assert.equal(h.publishing.claim("schedule",id,"worker-two",at),undefined);h.publishing.transitionClaim(h.publishing.claimFor("schedule")!,PinterestExecutionClaimState.Released);await h.service.execute("schedule",credentialId,{publicationId:id});const repeated=await h.service.execute("schedule",credentialId,{publicationId:id});assert.equal(repeated.pinReference?.pinId,"pin-123");assert.equal(h.calls.requests.length,1);});

test("401, 403, 429, maintenance and definite pre-write network outcomes remain distinct",async()=>{const cases:[PinterestProviderOutcome,PinterestPublishState][]=[[{kind:"AuthenticationRequired",safeMessage:"expired"},PinterestPublishState.AuthenticationRecoveryRequired],[{kind:"PermissionDenied",safeMessage:"scope denied"},PinterestPublishState.PermissionDenied],[{kind:"RateLimited",safeMessage:"later"},PinterestPublishState.RateLimited],[{kind:"TemporaryFailure",safeMessage:"maintenance"},PinterestPublishState.RetryPending],[{kind:"NetworkBeforeWrite",safeMessage:"not sent"},PinterestPublishState.RetryPending]];for(const [outcome,state] of cases){const result=await harness({outcomes:[outcome]}).service.execute("schedule",credentialId);assert.equal(result.state,state);assert.equal(result.failures.length,1);}});

test("ambiguous outcome requires verification and never blindly retries",async()=>{const h=harness({outcomes:[{kind:"UnknownOutcome",safeMessage:"Authorization: secret-value connection lost"},{kind:"Published",pinId:"duplicate",providerReference:"duplicate"}]});const first=await h.service.execute("schedule",credentialId),second=await h.service.execute("schedule",credentialId);assert.equal(first.state,PinterestPublishState.VerificationRequired);assert.equal(second.state,PinterestPublishState.VerificationRequired);assert.equal(h.calls.requests.length,1);assert.doesNotMatch(first.failures[0].safeMessage,/secret-value/);});

test("official reconciliation can confirm found Pin or absence while preserving publication identity",async()=>{const found=harness({outcomes:[{kind:"UnknownOutcome",safeMessage:"lost"}],reconciler:{async verify(){return{status:"Found",pin:{pinId:"pin-found",providerReference:"verified",publishedAt:at}};}}}),id=new PinterestPublicationId("stable");await found.service.execute("schedule",credentialId,{publicationId:id});const verified=await found.service.reconcile(id,credentialId);assert.equal(verified.pinReference?.pinId,"pin-found");assert.equal(found.calls.requests.length,1);const absent=harness({outcomes:[{kind:"UnknownOutcome",safeMessage:"lost"},{kind:"Published",pinId:"pin-retry",providerReference:"provider"}],reconciler:{async verify(){return{status:"Absent"};}}});await absent.service.execute("schedule",credentialId,{publicationId:id});const retried=await absent.service.reconcile(id,credentialId);assert.equal(retried.publicationId.value,"stable");assert.equal(absent.calls.requests.length,2);assert.equal(absent.publishing.attempts(id).length,2);});

test("attempt history is append-only and retry limit is bounded",async()=>{const h=harness({outcomes:[{kind:"NetworkBeforeWrite",safeMessage:"offline"},{kind:"NetworkBeforeWrite",safeMessage:"offline"}],retryLimit:2}),id=new PinterestPublicationId("retry");await h.service.execute("schedule",credentialId,{publicationId:id});await h.service.execute("schedule",credentialId,{publicationId:id});const stopped=await h.service.execute("schedule",credentialId,{publicationId:id});assert.equal(stopped.state,PinterestPublishState.Failed);assert.equal(h.publishing.attempts(id).length,2);assert.equal(h.calls.requests.length,2);});

test("dry run authenticates and constructs preview without write, publish handoff, or Published state",async()=>{const h=harness(),result=await h.service.execute("schedule",credentialId,{dryRun:true});assert.equal(result.state,PinterestPublishState.DryRun);assert.equal(result.dryRunRequest?.environment,PinterestPublishingEnvironment.Sandbox);assert.equal(h.calls.requests.length,0);assert.equal(h.handoff.publishedCalls.length,0);assert.equal(h.publishing.attempts(result.publicationId).length,0);});

test("cancellation before write blocks while cancellation after confirmed write cannot erase publication",async()=>{await assert.rejects(harness({scheduleStatus:PinterestScheduleStatus.Cancelled}).service.execute("schedule",credentialId));const h=harness(),published=await h.service.execute("schedule",credentialId);h.repository.replaceSchedule(new PinterestScheduledPublication(h.schedule.id,h.schedule.queueItemId,h.schedule.queueItemVersion,h.schedule.publishingCandidateId,h.schedule.publishingCandidateVersion,h.schedule.businessPackageId,h.schedule.channel,h.schedule.market,h.schedule.timezone,h.schedule.recommendedWindow,h.schedule.selectedLocalTimestamp,h.schedule.selectedNormalizedInstant,h.schedule.minimumIntervalPolicyUsed,h.schedule.priority,PinterestScheduleStatus.Cancelled,h.schedule.correlationIdentifier,h.schedule.provenance,h.schedule.createdAt,h.schedule.scheduledAt,0));assert.equal((await h.service.execute("schedule",credentialId)).pinReference?.pinId,published.pinReference?.pinId);assert.equal(h.calls.requests.length,1);});

test("publisher status is UI-ready and boundary exposes create only",async()=>{const h=harness();assert.equal(h.service.status().status,"Scheduled");await h.service.execute("schedule",credentialId);assert.deepEqual(h.service.status(),{nextPublication:at,status:"Published",lastPublication:"Success",authentication:"OK",publisher:"Online"});assert.deepEqual(Object.getOwnPropertyNames(PinterestPublisher.prototype).filter(x=>/delete|update|schedule|generate/i.test(x)),[]);assert.doesNotMatch(`${PinterestPublisher}`,/fetch\(|browser|captcha/i);});
