import assert from "node:assert/strict";
import test from "node:test";
import { BusinessPackageId } from "../../src/intelligence/market/MarketIntelligenceDomain.ts";
import { InMemoryMarketIntelligenceService } from "../../src/intelligence/market/MarketIntelligenceService.ts";
import { MarketSourceAdapterId, MarketSourceAvailability, MarketSourceCapability, MarketSourceHealth, MarketSourceHealthState, MarketSourceState } from "../../src/intelligence/market/integration/MarketSourceIntegrationDomain.ts";
import { MarketSourceIntegrationService } from "../../src/intelligence/market/integration/MarketSourceIntegrationService.ts";
import { DuplicateHandlingPolicy, MarketDataQualityPolicy, MarketDataQualitySeverity, MarketDataValidity } from "../../src/intelligence/market/quality/MarketDataQualityDomain.ts";
import { MarketDataQualityService } from "../../src/intelligence/market/quality/MarketDataQualityService.ts";
import { PinterestCapabilityState, PinterestCapabilityUnavailableReason, PinterestConnectionState } from "../../src/integrations/pinterest/PinterestConnectionVerificationDomain.ts";
import { PinterestAccessTier, PinterestEnvironment, PinterestMarketSourceAdapter } from "../../src/integrations/pinterest/PinterestMarketSourceAdapter.ts";
import { PinterestObservationCollectionScope, PinterestObservationWorkflowId, PinterestObservationWorkflowRequest, PinterestObservationWorkflowResult, PinterestObservationWorkflowState } from "../../src/integrations/pinterest/PinterestObservationWorkflowDomain.ts";
import { PinterestObservationWorkflow } from "../../src/integrations/pinterest/PinterestObservationWorkflow.ts";
import { AuthenticationSessionReference, ExternalAuthenticationFailureType } from "../../src/security/authentication/ExternalAuthenticationDomain.ts";
import { CredentialId } from "../../src/security/credentials/CredentialVault.ts";

const now=new Date("2026-08-09T12:00:00.000Z"),pkg=new BusinessPackageId("ALIVO"),credential=new CredentialId("credential:pinterest:alivo"),capability=new MarketSourceCapability("OwnPins");
class Authentication { failure?:ExternalAuthenticationFailureType;async authenticate(request:any){return this.failure?{successful:false as const,failure:this.failure}:{successful:true as const,session:new AuthenticationSessionReference("session-reference","Pinterest",request.properties.businessPackageId)};}async reportProviderFailure(){} }
class Transport { responses:any[]=[];calls:any[]=[];async execute(request:any){this.calls.push(request);const response=this.responses.shift();if(response instanceof Error)throw response;return response??{status:200,body:{items:[]}};} }
class NormalizationGate { validate(){return {accepted:true};} }
class Verification { state:PinterestObservationWorkflowState|undefined;calls=0;async verify(request:any){this.calls++;const auth=this.state===PinterestObservationWorkflowState.WaitingForCredentialCorrection?"CredentialCorrectionRequired":this.state===PinterestObservationWorkflowState.WaitingForReauthorization?"ReauthorizationRequired":"Authenticated";const capabilityState=this.state===PinterestObservationWorkflowState.RateLimited?PinterestCapabilityState.RateLimited:PinterestCapabilityState.Available;return {id:request.id,state:this.state===PinterestObservationWorkflowState.RateLimited?PinterestConnectionState.RateLimited:auth==="Authenticated"?PinterestConnectionState.Available:PinterestConnectionState.AuthenticationRequired,properties:{authenticationState:auth},capabilities:[{state:capabilityState,reason:PinterestCapabilityUnavailableReason.None}]};} }
let sequence=0;
function setup(){const auth=new Authentication(),transport=new Transport(),adapter=new PinterestMarketSourceAdapter(credential,pkg,{environment:PinterestEnvironment.Sandbox,apiBaseUrl:"https://unused.test",accessTier:PinterestAccessTier.Trial,approvedCapabilities:[capability],requestedScopes:["pins:read"],pageSize:2,maximumPages:3,timeoutMs:100,adapterVersion:"1.0"},auth,transport,new NormalizationGate());const integration=new MarketSourceIntegrationService();integration.register(adapter,"TCO");integration.enable(adapter.id,"TCO");const intelligence=new InMemoryMarketIntelligenceService();intelligence.registerSource(adapter.descriptor().source);const verification=new Verification(),quality=new MarketDataQualityService(undefined,undefined,undefined,()=>new Date(now));const policy=new MarketDataQualityPolicy({id:"pinterest-workflow-policy",businessPackageId:pkg,requiredFields:["subject","payloadReference"],requireFullProvenance:true,freshness:{freshMs:1000,acceptableMs:2000,ageingMs:3000,staleMs:4000},duplicateHandling:DuplicateHandlingPolicy.QuarantineExact,rejectValidity:[MarketDataValidity.Invalid,MarketDataValidity.Unsupported],quarantineSeverities:[MarketDataQualitySeverity.Critical]});const workflow=new PinterestObservationWorkflow(integration.registry,verification as any,quality,()=>policy,intelligence,undefined,undefined,undefined,()=>new Date(now));return {auth,transport,adapter,integration,intelligence,verification,workflow};}
function request(overrides:Record<string,any>={}){return new PinterestObservationWorkflowRequest({id:new PinterestObservationWorkflowId(`workflow-31-${++sequence}`),businessPackageId:pkg,adapterId:new MarketSourceAdapterId("PinterestMarketSourceAdapter"),credentialId:credential,capability,scope:PinterestObservationCollectionScope.OwnedPins,marketContext:"US",maximumPages:3,maximumRecords:10,correlationIdentifier:"correlation-31",requestingAuthorityReference:"TCO-task-31",requestedAt:now,...overrides});}

test("validates governed requests and rejects unsupported scopes before collection",async()=>{assert.throws(()=>request({maximumPages:0}));const f=setup(),r=request({scope:PinterestObservationCollectionScope.Trends});const result=await f.workflow.run(r);assert.ok(result instanceof PinterestObservationWorkflowResult);assert.equal(result.finalState,PinterestObservationWorkflowState.Failed);assert.equal(f.transport.calls.length,0);});

test("collects raw records, normalizes, validates, and registers accepted observations",async()=>{const f=setup();f.transport.responses.push({status:200,body:{items:[{id:"pin-1",created_at:now.toISOString(),title:"Owned pin",is_owner:true}]}});const result=await f.workflow.run(request());assert.ok(result instanceof PinterestObservationWorkflowResult);assert.equal(result.finalState,PinterestObservationWorkflowState.Completed);assert.deepEqual(result.summary.properties,{requestedPages:3,requestedItems:10,rawRecordsCollected:1,normalizedRecords:1,acceptedObservations:1,acceptedWithWarningObservations:0,quarantinedObservations:0,rejectedObservations:0,historicalOnlyObservations:0,duplicatesDetected:0,noDataResults:0,providerFailures:0,normalizationFailures:0,validationFailures:0});assert.equal(f.intelligence.observation(result.acceptedObservations[0].id),result.acceptedObservations[0]);assert.match(result.acceptedObservations[0].payloadReference,/OwnedAuthorizedResource/);assert.match(result.acceptedObservations[0].payloadReference,/"clicks":"Unavailable"/);});

test("preserves NoData as a successful terminal outcome",async()=>{const f=setup();f.transport.responses.push({status:200,body:{items:[]}});const result=await f.workflow.run(request());assert.ok(result instanceof PinterestObservationWorkflowResult);assert.equal(result.finalState,PinterestObservationWorkflowState.NoData);assert.equal(result.summary.properties.noDataResults,1);});

test("preserves partial pages and rate-limit metadata without classifying authentication failure",async()=>{const f=setup();f.transport.responses.push({status:200,body:{items:[{id:"pin-1",created_at:now.toISOString()}],bookmark:"next"}},{status:429,body:{},headers:{"retry-after":"30"}});const result=await f.workflow.run(request());assert.ok(result instanceof PinterestObservationWorkflowResult);assert.equal(result.finalState,PinterestObservationWorkflowState.CompletedWithWarnings);assert.equal(result.summary.properties.rawRecordsCollected,1);assert.equal(result.properties.rateLimit?.limited,true);assert.match(result.acceptedObservations[0].payloadReference,/UnknownOwnership/);});

test("credential correction resumes the same immutable workflow history",async()=>{const f=setup(),r=request();f.verification.state=PinterestObservationWorkflowState.WaitingForCredentialCorrection;assert.equal(await f.workflow.run(r),PinterestObservationWorkflowState.WaitingForCredentialCorrection);f.verification.state=undefined;f.transport.responses.push({status:200,body:{items:[]}});const result=await f.workflow.resume(r);assert.ok(result instanceof PinterestObservationWorkflowResult);assert.equal(result.workflowId.value,r.id.value);assert.ok(f.workflow.repository.history(r.id).some(x=>x.state===PinterestObservationWorkflowState.WaitingForCredentialCorrection));assert.ok(f.workflow.repository.history(r.id).some(x=>x.state===PinterestObservationWorkflowState.NoData));assert.throws(()=>f.workflow.repository.store(result));assert.equal(JSON.stringify(result).includes("session-reference"),false);});

test("source HOLD and cross-package credentials fail before verification or network use",async()=>{const held=setup();held.integration.hold(held.adapter.id,"TCO");const heldResult=await held.workflow.run(request());assert.ok(heldResult instanceof PinterestObservationWorkflowResult);assert.equal(held.verification.calls,0);const cross=setup(),crossResult=await cross.workflow.run(request({businessPackageId:new BusinessPackageId("BEST-FINDS")}));assert.ok(crossResult instanceof PinterestObservationWorkflowResult);assert.equal(cross.transport.calls.length,0);});

test("manual runs use the same read-only pipeline and expose no publishing surface",async()=>{const f=setup(),r=request({manual:true});f.transport.responses.push({status:200,body:{items:[]}});assert.ok(await f.workflow.manualRun(r) instanceof PinterestObservationWorkflowResult);for(const operation of ["publish","createPin","deletePin","schedule"])assert.equal(operation in f.workflow,false);assert.equal(f.transport.calls.every(call=>call.path.startsWith("/v5/")&&call.session instanceof AuthenticationSessionReference),true);});
