import assert from "node:assert/strict";
import test from "node:test";
import { BusinessPackageId } from "../../src/intelligence/market/MarketIntelligenceDomain.ts";
import { MarketSourceAdapterId, MarketSourceCapability } from "../../src/intelligence/market/integration/MarketSourceIntegrationDomain.ts";
import { MarketSourceIntegrationService } from "../../src/intelligence/market/integration/MarketSourceIntegrationService.ts";
import { PinterestAccessTier, PinterestEnvironment, PinterestMarketSourceAdapter, PinterestTimeoutError } from "../../src/integrations/pinterest/PinterestMarketSourceAdapter.ts";
import { PinterestCapabilityState, PinterestCapabilityUnavailableReason, PinterestConnectionState, PinterestConnectionVerificationId, PinterestConnectionVerificationRequest } from "../../src/integrations/pinterest/PinterestConnectionVerificationDomain.ts";
import { PinterestConnectionVerificationRepository } from "../../src/integrations/pinterest/PinterestConnectionVerificationRepository.ts";
import { PinterestConnectionVerifier } from "../../src/integrations/pinterest/PinterestConnectionVerifier.ts";
import { AuthenticationSessionReference, ExternalAuthenticationFailureType } from "../../src/security/authentication/ExternalAuthenticationDomain.ts";
import { AuthenticationType, CredentialId, CredentialStatus } from "../../src/security/credentials/CredentialVault.ts";

const at=new Date("2026-08-09T12:00:00.000Z"),pkg=new BusinessPackageId("ALIVO"),credential=new CredentialId("credential:pinterest:alivo");
const ownPins=new MarketSourceCapability("OwnPins"),ownBoards=new MarketSourceCapability("OwnBoards"),analytics=MarketSourceCapability.AnalyticsObservation,trends=MarketSourceCapability.TrendObservation,competitorCtr=new MarketSourceCapability("CompetitorCTR");
class Auth { failure?:ExternalAuthenticationFailureType;calls=0;async authenticate(request:any){this.calls++;return this.failure?{successful:false as const,failure:this.failure}:{successful:true as const,session:new AuthenticationSessionReference("opaque","Pinterest",request.properties.businessPackageId)};}async reportProviderFailure(){} }
class Transport { calls:any[]=[];responses:Array<any|Error>=[];async execute(request:any){this.calls.push(request);const value=this.responses.shift();if(value instanceof Error)throw value;return value??{status:200,body:{items:[{id:"one"}]}};} }
class Quality {validate(){return {accepted:true};}}
function setup(scopes=["ALIVO"],capabilities=[ownPins,ownBoards,analytics,trends]){const auth=new Auth(),transport=new Transport(),adapter=new PinterestMarketSourceAdapter(credential,pkg,{environment:PinterestEnvironment.Sandbox,apiBaseUrl:"https://unused.test",accessTier:PinterestAccessTier.Trial,approvedCapabilities:capabilities,requestedScopes:["pins:read","boards:read","analytics:read"],pageSize:1,maximumPages:1,timeoutMs:250,adapterVersion:"1.0"},auth,transport,new Quality());const integration=new MarketSourceIntegrationService(),repository=new PinterestConnectionVerificationRepository();integration.register(adapter,"TCO");integration.enable(adapter.id,"TCO");const metadata={credentialId:credential.value,displayName:"Pinterest ALIVO",serviceReference:"Pinterest",accountReference:"ALIVO",authenticationType:AuthenticationType.OAuthCredentialReference,businessPackageScopes:scopes,sharedScopeApproved:false,capabilityScopes:["pins:read"],status:CredentialStatus.Active,createdAt:at.toISOString(),updatedAt:at.toISOString()};const verifier=new PinterestConnectionVerifier(integration.registry,{metadata:id=>id===credential.value?metadata:undefined},repository,undefined,undefined,()=>new Date(at));return {auth,transport,integration,repository,verifier};}
let sequence=0;function request(capabilities=[ownPins,ownBoards,analytics,trends],overrides:Record<string,any>={}){return new PinterestConnectionVerificationRequest({id:new PinterestConnectionVerificationId(`verify-${++sequence}`),adapterId:new MarketSourceAdapterId("PinterestMarketSourceAdapter"),credentialId:credential,businessPackageId:pkg,requestedCapabilities:capabilities,requestingAuthorityReference:"TCO-task-30",correlationIdentifier:"correlation-30",requestedAt:at,...overrides});}

test("validates registration, source lifecycle, CredentialId, and Business Package before network use",async()=>{const missing=setup();const absent=request([ownPins],{credentialId:new CredentialId("missing")});assert.equal((await missing.verifier.verify(absent)).state,PinterestConnectionState.NotConfigured);assert.equal(missing.auth.calls,0);const wrong=setup(["BEST-FINDS"]);assert.match((await wrong.verifier.verify(request([ownPins]))).failures[0],/Business Package/);assert.equal(wrong.transport.calls.length,0);for(const transition of ["disable","hold","retire"] as const){const f=setup();f.integration[transition](new MarketSourceAdapterId("PinterestMarketSourceAdapter"),"TCO");assert.equal((await f.verifier.verify(request([ownPins]))).state,PinterestConnectionState.NotConfigured);assert.equal(f.auth.calls,0);}});

test("verifies available capabilities independently and preserves NoData",async()=>{const f=setup();f.transport.responses.push({status:200,body:{items:[{id:"pin"}]}},{status:200,body:{items:[]}},{status:403,body:{}},{status:429,body:{},headers:{"retry-after":"30"}});const result=await f.verifier.verify(request());assert.equal(result.state,PinterestConnectionState.PartiallyAvailable);assert.deepEqual(result.capabilities.map(x=>x.state),[PinterestCapabilityState.Available,PinterestCapabilityState.Available,PinterestCapabilityState.PermissionRequired,PinterestCapabilityState.RateLimited]);assert.equal(result.capabilities[1].reason,PinterestCapabilityUnavailableReason.NoData);assert.equal(result.properties.rateLimit?.limited,true);assert.equal(result.properties.authenticationState,"Authenticated");assert.equal(f.transport.calls.every(call=>call.query.page_size==="1"&&call.timeoutMs===250),true);});

test("never makes unsupported competitor private metrics available or probes them",async()=>{const f=setup();const result=await f.verifier.verify(request([competitorCtr,ownPins]));assert.equal(result.capabilities[0].state,PinterestCapabilityState.NotSupported);assert.equal(result.capabilities[0].reason,PinterestCapabilityUnavailableReason.PrivateCompetitorMetric);assert.equal(result.capabilities[1].state,PinterestCapabilityState.Available);assert.equal(f.transport.calls.length,1);});

test("classifies authentication recovery states without capability probes",async()=>{for(const [failure,state] of [[ExternalAuthenticationFailureType.InvalidCredential,"CredentialCorrectionRequired"],[ExternalAuthenticationFailureType.ReauthorizationRequired,"ReauthorizationRequired"],[ExternalAuthenticationFailureType.MFARequired,"MFARequired"],[ExternalAuthenticationFailureType.PermissionDenied,"PermissionDenied"],[ExternalAuthenticationFailureType.NetworkUnavailable,"TemporaryFailure"]] as const){const f=setup();f.auth.failure=failure;const result=await f.verifier.verify(request([ownPins]));assert.equal(result.properties.authenticationState,state);assert.equal(result.capabilities[0].state,PinterestCapabilityState.AuthenticationRequired);assert.equal(f.transport.calls.length,0);}});

test("keeps 401, 403, 429, provider failure, and finite timeout classifications distinct",async()=>{for(const [response,state] of [[{status:401,body:{}},PinterestCapabilityState.AuthenticationRequired],[{status:403,body:{}},PinterestCapabilityState.PermissionRequired],[{status:429,body:{},headers:{}},PinterestCapabilityState.RateLimited],[{status:503,body:{}},PinterestCapabilityState.TemporarilyUnavailable],[new PinterestTimeoutError(),PinterestCapabilityState.TemporarilyUnavailable]] as const){const f=setup();f.transport.responses.push(response);assert.equal((await f.verifier.verify(request([ownPins]))).capabilities[0].state,state);}});

test("stores immutable deterministic history, supports re-verification, and isolates Business Packages",async()=>{const f=setup();const first=request([ownPins]);await f.verifier.verify(first);const second=request([ownPins],{reverificationOf:first.id});await f.verifier.reverify(second);assert.deepEqual(f.repository.history(pkg).map(x=>x.id.value),[first.id.value,second.id.value]);assert.equal(f.repository.current(pkg)?.id.value,second.id.value);assert.throws(()=>f.repository.store(f.repository.get(first.id)!));assert.equal(f.repository.history(new BusinessPackageId("BEST-FINDS")).length,0);assert.equal(Object.isFrozen(f.repository.get(first)!.capabilities),true);});

test("verification surface is read-only, safe, and contains no scheduling or publishing operations",async()=>{const f=setup();const result=await f.verifier.verify(request([ownPins]));const serialized=JSON.stringify(result);assert.equal(/opaque|secret|Bearer/i.test(serialized),false);for(const operation of ["publish","createPin","deletePin","schedule","startPolling"])assert.equal(operation in f.verifier,false);assert.equal(f.transport.calls[0].provenance,undefined);});
