import assert from "node:assert/strict";
import {test} from "node:test";
import {InMemoryRepository} from "../../src/core/platform/Repository.ts";
import {LearningDirection} from "../../src/business/learning/ContinuousLearningDomain.ts";
import {MetricAvailability,OutcomeClassification,PerformanceMetricType} from "../../src/business/market/performance/PerformanceIntelligenceDomain.ts";
import {PerformanceIntelligenceService} from "../../src/business/market/performance/PerformanceIntelligenceService.ts";
import {PerformanceRepository} from "../../src/business/market/performance/PerformanceRepository.ts";
import {BusinessPackageId} from "../../src/intelligence/market/MarketIntelligenceDomain.ts";
import {PinterestPublicationId,PinterestPublishedPinReference,PinterestPublishResult,PinterestPublishState} from "../../src/integrations/pinterest/PinterestPublisher.ts";
import {PinterestAnalyticsCollectionState,PinterestMeasurementMaturity,PinterestMeasurementWindowPolicy,PinterestPerformanceCollectionRequest,PinterestPerformanceResourceClassification,PinterestPerformanceSubject,PinterestRawAnalyticsRecord,type PinterestAnalyticsOutcome} from "../../src/integrations/pinterest/PinterestPerformanceFeedbackDomain.ts";
import {PinterestPerformanceFeedbackRepository,PinterestPerformanceFeedbackWorkflow} from "../../src/integrations/pinterest/PinterestPerformanceFeedbackWorkflow.ts";

const publishedAt=new Date("2026-08-01T18:00:00Z"),collectedAt=new Date("2026-08-01T20:00:00Z"),pkg=new BusinessPackageId("alivo");
function publication(state=PinterestPublishState.Published){const pin=state===PinterestPublishState.Published?new PinterestPublishedPinReference("pin-1","provider-publication-1",publishedAt):undefined;return new PinterestPublishResult(new PinterestPublicationId(`publication-${state}`),"schedule-1","candidate-1",pkg,1,state,pin,pin?.publishedAt,{},[],0,"correlation-1",Object.freeze({source:"publisher"}));}
function subject(state=PinterestPublishState.Published,minimum=90){return new PinterestPerformanceSubject(publication(state),{scheduledPublicationId:"schedule-1",publishingCandidateId:"candidate-1",publishingCandidateVersion:4,copyArtifactId:"copy-1",copyArtifactVersion:7,visualArtifactId:"visual-1",visualArtifactVersion:3,creationPlanId:"plan-1",creationPlanVersion:2,recommendationId:"recommendation-1",recommendationVersion:5,ceoDecisionReference:"decision-1",opportunityReferences:["opportunity-1"],patternReferences:["pattern-1"],businessPackageId:pkg,market:"DE",language:"de",channel:"Pinterest",experiment:{hypothesis:"evening association",variant:"B",controlledVariable:"publication time",baseline:"A",measurementWindow:"Early"}},{recommendationId:"timing-1",recommendationVersion:6,recommendedWindow:"19:00-20:00",confidence:.7,scheduledTimestamp:publishedAt,actualPublicationTimestamp:publishedAt,timezone:"Europe/Berlin",timingDeviationMinutes:0,dayOfWeek:6,localPublicationTime:"20:00",normalizedPublicationInstant:publishedAt},{minimumPublicationIntervalMinutes:minimum,intervalSincePreviousMinutes:95,recentPublishedPins:3,analysisWindowMinutes:1440,queueContext:"confirmed-at-publication",cadenceRecommendationReference:"cadence-1"},{topic:"summer",contentIntent:"inspire",destinationType:"article",creativeType:"static"});}
const early=new PinterestMeasurementWindowPolicy("Early",2*60*60*1000,false),mature=new PinterestMeasurementWindowPolicy("LongTerm",7*24*60*60*1000,true);
function request(s=subject(),window=early){return new PinterestPerformanceCollectionRequest(s,["Impressions","Clicks","OutboundClicks"],window,"correlation-1","tco-workflow-44",collectedAt);}
function raw(id="raw-1",impressions=0){return new PinterestRawAnalyticsRecord(id,"pin-1",publishedAt,collectedAt,collectedAt,collectedAt,[{providerName:"IMPRESSION",value:impressions,availability:MetricAvailability.Available,unit:"count"},{providerName:"PIN_CLICK",availability:MetricAvailability.Unavailable,unit:"count"},{providerName:"OUTBOUND_CLICK",value:2,availability:MetricAvailability.Available,unit:"count"}]);}
function setup(outcome:PinterestAnalyticsOutcome={kind:"Collected",record:raw()}){const repo=new PinterestPerformanceFeedbackRepository(),recoveries:PinterestPerformanceCollectionRequest[]=[];return{repo,recoveries,workflow:new PinterestPerformanceFeedbackWorkflow({collect:async()=>outcome},new PerformanceIntelligenceService(new PerformanceRepository(new InMemoryRepository())),repo,{requestRecovery:r=>{recoveries.push(r);}},undefined,{evaluate:()=>({direction:LearningDirection.Positive})},()=>collectedAt)};}

test("only verified successful publications are eligible for analytics measurement",async()=>{for(const state of [PinterestPublishState.DryRun,PinterestPublishState.Failed,PinterestPublishState.Cancelled,PinterestPublishState.VerificationRequired]){const {workflow}=setup();await assert.rejects(()=>workflow.collect(request(subject(state))),/Only a verified published Pin/);}const {workflow}=setup();assert.equal("observation" in await workflow.collect(request()),true);});
test("exact publication, creative, recommendation, timing, cadence, content and experiment lineage remains immutable",async()=>{const s=subject(),{workflow}=setup(),result=await workflow.collect(request(s));assert.ok("observation" in result);assert.equal(result.request.subject.lineage.copyArtifactVersion,7);assert.equal(result.request.subject.lineage.visualArtifactVersion,3);assert.equal(result.request.subject.lineage.recommendationVersion,5);assert.equal(result.request.subject.timing.recommendationVersion,6);assert.equal(result.request.subject.cadence.minimumPublicationIntervalMinutes,90);assert.equal(result.request.subject.content.topic,"summer");assert.equal(result.request.subject.lineage.experiment?.variant,"B");assert.equal(Object.isFrozen(result.request.subject.lineage),true);});
test("normalization preserves zero, unavailable, owned provenance, outcomes and governed learning inputs",async()=>{const {workflow}=setup(),result=await workflow.collect(request());assert.ok("observation" in result);assert.equal(result.raw.classification,PinterestPerformanceResourceClassification.OwnedAuthorizedResource);assert.equal(result.observation.metrics[0].type,PerformanceMetricType.Impressions);assert.equal(result.observation.metrics[0].value,0);assert.equal(result.observation.metrics[1].availability,MetricAvailability.Unavailable);assert.equal(result.observation.metrics[1].value,undefined);assert.equal(result.observedOutcome.observationIds[0].value,result.observation.id.value);assert.equal(result.expectedOutcome,undefined);assert.equal(result.evaluation.classification,OutcomeClassification.Inconclusive);assert.equal(result.timingLearningInput.channel,"Pinterest");assert.equal(result.cadenceLearningInput.cadence.minimumPublicationIntervalMinutes,90);assert.equal(result.learning?.direction,LearningDirection.Positive);});
test("configurable windows append immutable provisional and mature observations",async()=>{const {workflow,repo}=setup();const first=await workflow.collect(request(subject(),early));assert.ok("observation" in first);const second=workflow.ingest(request(subject(),mature),raw("raw-2",20));assert.ok("observation" in second);assert.equal(first.maturity,PinterestMeasurementMaturity.Provisional);assert.equal(second.maturity,PinterestMeasurementMaturity.Mature);assert.equal(repo.all().length,2);assert.notEqual(first.observation.id.value,second.observation.id.value);});
test("retroactive revisions append history while exact duplicates do not inflate evidence",async()=>{const {workflow,repo}=setup();await workflow.collect(request());const duplicate=workflow.ingest(request(),raw());assert.equal("state" in duplicate&&duplicate.state,PinterestAnalyticsCollectionState.Duplicate);const revised=workflow.ingest(request(),raw("raw-revised",10));assert.ok("observation" in revised);assert.equal(revised.revision,2);assert.equal(repo.all().length,2);});
test("authentication recovery, rate limits and no data preserve TCO workflow identity",async()=>{const auth=setup({kind:"AuthenticationRequired",safeMessage:"reauthorization required"}),authResult=await auth.workflow.collect(request());assert.equal("state" in authResult&&authResult.state,PinterestAnalyticsCollectionState.AuthenticationRequired);assert.equal(auth.recoveries[0].workflowReference,"tco-workflow-44");const rate=await setup({kind:"RateLimited",safeMessage:"later",retryAfter:new Date("2026-08-01T21:00:00Z")}).workflow.collect(request());assert.equal("state" in rate&&rate.state,PinterestAnalyticsCollectionState.RateLimited);const noData=await setup({kind:"NoData"}).workflow.collect(request());assert.equal("state" in noData&&noData.state,PinterestAnalyticsCollectionState.NoData);});
test("malformed and mismatched provider analytics are rejected before Performance Intelligence",()=>{assert.throws(()=>new PinterestRawAnalyticsRecord("bad","pin-1",collectedAt,publishedAt,collectedAt,collectedAt,[{providerName:"IMPRESSION",value:Number.NaN,availability:MetricAvailability.Available,unit:"count"}]),/malformed/);const {workflow}=setup();assert.throws(()=>workflow.ingest(request(),new PinterestRawAnalyticsRecord("wrong","other-pin",publishedAt,collectedAt,collectedAt,collectedAt,[{providerName:"IMPRESSION",value:1,availability:MetricAvailability.Available,unit:"count"}])),/does not match/);});
test("read models retain package, channel and market isolation without changing historical policy",async()=>{const s=subject(),{workflow}=setup();await workflow.collect(request(s));const read=workflow.performanceReadModel(s.publication.publicationId.value)!;assert.equal(read.measurements.length,1);assert.equal(read.intervalSincePreviousMinutes,95);assert.equal(workflow.timingAnalysis()[0].market,"DE");assert.equal(workflow.timingAnalysis()[0].channel,"Pinterest");assert.equal(workflow.cadenceAnalysis()[0].currentMinimumIntervalMinutes,90);assert.equal(s.cadence.minimumPublicationIntervalMinutes,90);});
test("workflow surface has no publishing, content mutation, queue mutation or policy mutation operation",()=>{assert.deepEqual(Object.getOwnPropertyNames(PinterestPerformanceFeedbackWorkflow.prototype).filter(x=>/publish|rewrite|delete|update|reorder|minimumPublicationInterval|timingMode|timezoneMode/i.test(x)),[]);});
