import test from "node:test";import assert from "node:assert/strict";
import {RecommendationStatus} from "../../src/business/recommendations/RecommendationDomain.ts";import {BusinessPackageId} from "../../src/intelligence/market/MarketIntelligenceDomain.ts";
import {PinterestCreationPlanRepository} from "../../src/integrations/pinterest/PinterestCreationPlanRepository.ts";import {PinterestCTAObjective,PinterestCreationPlanId,PinterestCreationPlanState,PinterestCreationPlanVersion} from "../../src/integrations/pinterest/PinterestCreationPlanningDomain.ts";
import {PinterestCopyArtifactId,PinterestCopyProductionException,PinterestCopyProductionRequest,PinterestCopyStatus,type PinterestCopyProductionContext,type PinterestCopyWriter} from "../../src/integrations/pinterest/PinterestCopyProductionDomain.ts";import {PinterestCopyProductionWorkflow} from "../../src/integrations/pinterest/PinterestCopyProductionWorkflow.ts";

const pkg=new BusinessPackageId("ALIVO"),at=new Date("2026-08-09T00:00:00Z");
function plan(state=PinterestCreationPlanState.ReadyForProduction,version=1,language:string|undefined="de",experiment:object|undefined=undefined){return {id:new PinterestCreationPlanId("plan-38"),version:new PinterestCreationPlanVersion(version),state,businessPackageId:pkg,recommendation:{status:RecommendationStatus.ApprovedByCEO,version:7},decision:{recommendationVersion:7},contentDirection:{language,keywords:{primaryTopicTerm:"sleep routine"},supportingTerms:["better sleep"],observedPhrases:["evening routine"]},copyDirection:{topic:"sleep routine",ctaObjective:PinterestCTAObjective.ReadArticle,prohibitedClaims:["guaranteed cure"]},destination:{assetReference:"article-17"},experiment,correlationIdentifier:"corr-38",learningTrace:{recommendationId:"rec-7",recommendationVersion:7,ceoDecisionId:"decision-7",opportunityReferences:["opp-1"],patternReferences:["pattern-1"],evidenceReferences:["evidence-1"],creationHypothesis:experiment?"approved hypothesis":undefined}} as never;}
function request(overrides:Partial<{version:number;packageId:BusinessPackageId;research:readonly string[];variants:number}>= {}){const packageId=overrides.packageId??pkg;return new PinterestCopyProductionRequest(new PinterestCopyArtifactId("copy-38"),"plan-38",overrides.version??1,packageId,"corr-38","TCO",["title","description","cta","accessibilityText"],{reference:"knowledge-1",businessPackageId:packageId,facts:["approved fact"],requiredResearch:overrides.research},{reference:"voice-1",businessPackageId:packageId,instructions:["human first"]},overrides.variants??1);}
class FakeWriter implements PinterestCopyWriter{calls:PinterestCopyProductionContext[]=[];valid=true;generate(context:PinterestCopyProductionContext){this.calls.push(context);return{copy:{title:this.valid?"Eine bessere Schlafroutine":"",description:"Eine praktische Abendroutine für den Artikel.",cta:"Artikel lesen",language:"de",topic:"sleep routine",destinationReference:"article-17",ctaObjective:PinterestCTAObjective.ReadArticle,originalExpression:true,usedKnowledgeReferences:["knowledge-1"],usedKeywordTerms:["sleep routine","better sleep"]},provenance:{capabilityReference:"writer",configurationReference:"deterministic-test",generatedAt:at}};}}
function setup(value=plan()){const plans=new PinterestCreationPlanRepository();plans.store(value);const writer=new FakeWriter();return{writer,workflow:new PinterestCopyProductionWorkflow(plans,writer,{supportedFields:["title","description","cta","accessibilityText"],maximumLengths:{title:100,description:500}},undefined,undefined,()=>at)};}

test("current ReadyForProduction plan produces validated immutable copy with exact lineage",()=>{const {workflow,writer}=setup(),artifact=workflow.produce(request()).artifacts[0];assert.equal(artifact.status,PinterestCopyStatus.ReadyForCreativeAssembly);assert.equal(artifact.lineage.planVersion,1);assert.equal(artifact.lineage.ceoDecisionId,"decision-7");assert.deepEqual(artifact.lineage.opportunityReferences,["opp-1"]);assert.equal(writer.calls[0].plan.copyDirection.ctaObjective,PinterestCTAObjective.ReadArticle);assert.deepEqual(writer.calls[0].request.knowledgeContext.facts,["approved fact"]);assert.ok(Object.isFrozen(artifact)&&Object.isFrozen(artifact.drafts));assert.equal(artifact.drafts[0].copy.accessibilityText,undefined);});
for(const state of [PinterestCreationPlanState.Draft,PinterestCreationPlanState.Superseded,PinterestCreationPlanState.Invalidated,PinterestCreationPlanState.Cancelled])test(`${state} plan is rejected`,()=>assert.throws(()=>setup(plan(state)).workflow.produce(request()),PinterestCopyProductionException));
test("exact current plan version and Business Package are enforced",()=>{assert.throws(()=>setup().workflow.produce(request({version:2})),/exact current Plan version/);const other=new BusinessPackageId("BEST-FINDS");assert.throws(()=>setup().workflow.produce(request({packageId:other})),/Business Package/);});
test("missing language fails rather than guessing",()=>{const missing={...plan(),contentDirection:{...plan().contentDirection,language:undefined}};assert.throws(()=>setup(missing as never).workflow.produce(request()),/language is required/);});
test("unresolved factual context returns AdditionalResearchRequired without invoking Writer",()=>{const {workflow,writer}=setup(),result=workflow.produce(request({research:["source needed"]}));assert.equal(result.artifacts[0].status,PinterestCopyStatus.AdditionalResearchRequired);assert.equal(writer.calls.length,0);});
test("validation failure preserves Draft and governed revision preserves history",()=>{const {workflow,writer}=setup();writer.valid=false;const failed=workflow.produce(request()).artifacts[0];assert.equal(failed.status,PinterestCopyStatus.ValidationFailed);assert.equal(failed.drafts.length,1);writer.valid=true;const ready=workflow.revise(request());assert.equal(ready.status,PinterestCopyStatus.ReadyForCreativeAssembly);assert.equal(ready.drafts.length,2);assert.equal(ready.drafts[0],failed.drafts[0]);assert.equal(ready.drafts[1].revision,2);});
test("configured provider limits, originality, claims and fields fail deterministically",()=>{const {workflow,writer}=setup();writer.generate=(context)=>({copy:{title:"x".repeat(101),description:"copy",cta:"read",language:"de",topic:"sleep routine",destinationReference:"article-17",ctaObjective:PinterestCTAObjective.ReadArticle,originalExpression:false,usedKnowledgeReferences:["knowledge-1"],usedKeywordTerms:["invented metric"],unsupportedClaims:["guaranteed cure"],providerFields:["unknown"]},provenance:{capabilityReference:"fake",generatedAt:at}});const artifact=workflow.produce(request()).artifacts[0];assert.equal(artifact.status,PinterestCopyStatus.ValidationFailed);assert.ok(artifact.validation!.reasons.length>=5);});
test("variants require explicit experiment and retain independent identity and hypothesis",()=>{assert.throws(()=>setup().workflow.produce(request({variants:2})),/approved experiment/);const result=setup(plan(PinterestCreationPlanState.ReadyForProduction,1,"de",{})).workflow.produce(request({variants:2}));assert.deepEqual(result.artifacts.map(x=>x.variantId),["variant-1","variant-2"]);assert.ok(result.artifacts.every(x=>x.lineage.hypothesis==="approved hypothesis"));});
test("workflow exposes no image, publishing, scheduling, or network operation",()=>{const methods=Object.getOwnPropertyNames(PinterestCopyProductionWorkflow.prototype);assert.deepEqual(methods.filter(x=>/image|prompt|publish|schedule|network/i.test(x)),[]);});
