import assert from "node:assert/strict";import test from "node:test";
import {OpportunityEffort,OpportunityEvidence,OpportunityId,OpportunityPriority,OpportunityRisk,OpportunityScope,OpportunityStatus,OpportunityType,OpportunityValue,MarketOpportunity} from "../../src/business/market/opportunities/OpportunityIntelligenceDomain.ts";
import {RecommendationEffort,RecommendationEvidence,RecommendationEvidenceItem,RecommendationEvidenceRole,RecommendationObjective,RecommendationStatus,RecommendationType,RecommendationValue,RecommendedWorkflowReference,StrategicRelevance} from "../../src/business/recommendations/RecommendationDomain.ts";import {RecommendationEngine} from "../../src/business/recommendations/RecommendationEngine.ts";import {RecommendationRepository} from "../../src/business/recommendations/RecommendationRepository.ts";import {InMemoryRepository} from "../../src/core/platform/Repository.ts";
import {BusinessPackageId,Confidence,Evidence,EvidenceId,EvidenceStatus,Freshness,FreshnessStatus,MarketSourceId,ObservationId,Provenance} from "../../src/intelligence/market/MarketIntelligenceDomain.ts";
import {PinterestRecommendationCandidateInput,PinterestRecommendationEvaluationId,PinterestRecommendationEvaluationRequest,PinterestRecommendationEvidenceGap} from "../../src/integrations/pinterest/PinterestRecommendationEvaluationDomain.ts";import {PinterestRecommendationEvaluationWorkflow} from "../../src/integrations/pinterest/PinterestRecommendationEvaluationWorkflow.ts";
const at=new Date("2026-08-09T12:00:00Z"),pkg=new BusinessPackageId("ALIVO"),other=new BusinessPackageId("BEST-FINDS");let sequence=0;
function evidence(id:string,source:string,role=RecommendationEvidenceRole.Supporting){const provenance=new Provenance("public observable metadata",at,new MarketSourceId(source),[id]),value=new Evidence(new EvidenceId(id),[new ObservationId(`ob-${id}`)],provenance,at,new Confidence(.85),new Freshness(FreshnessStatus.Current,at),EvidenceStatus.Active);return new RecommendationEvidenceItem(value,source,"market signal",role,true);}
function opportunity(id:string,status=OpportunityStatus.Qualified,p=pkg){const support=evidence(`${id}-e`,`${id}-source`).evidence,provenance=support.provenance;return new MarketOpportunity({id:new OpportunityId(id),version:1,type:OpportunityType.Content,status,title:`Opportunity ${id}`,description:"qualified Pinterest-derived opportunity",businessPackageId:p,scope:new OpportunityScope(p,{market:"Pinterest"}),evidence:new OpportunityEvidence([support],[],[],[],[],[],[],[],new Freshness(FreshnessStatus.Current,at)),value:OpportunityValue.High,effort:OpportunityEffort.Low,risk:OpportunityRisk.Low,confidence:new Confidence(.8),freshness:new Freshness(FreshnessStatus.Current,at),priority:OpportunityPriority.High,createdAt:at,evaluatedAt:at,provenance});}
function request(opportunities:readonly MarketOpportunity[],p=pkg){return new PinterestRecommendationEvaluationRequest({id:new PinterestRecommendationEvaluationId(`evaluation-${++sequence}`),businessPackageId:p,opportunityReferences:opportunities.map(x=>x.id.value),patternReferences:[],performanceEvaluationReferences:[],strategicContextReference:"approved-strategy",approvedCEOPreferenceContext:["explicit-preference"],correlationIdentifier:"IMPLEMENTATION-035",requestingAuthorityReference:"TCO",requestedAt:at});}
function input(opportunities:readonly MarketOpportunity[],options:{gaps?:PinterestRecommendationEvidenceGap[];type?:RecommendationType;conflict?:boolean;pkg?:BusinessPackageId}={}){const p=options.pkg??pkg,items=[evidence("support-a","source-a"),evidence("support-b","source-b")];if(options.conflict)items.push(evidence("conflict-a","source-c",RecommendationEvidenceRole.Contradicting),evidence("conflict-b","source-d",RecommendationEvidenceRole.Contradicting));return new PinterestRecommendationCandidateInput({opportunities,objective:new RecommendationObjective("traffic","Growth","Increase qualified traffic",p,"approved-strategy","traffic-measure"),type:options.type??RecommendationType.ContentCreation,evidence:new RecommendationEvidence(items),businessMemoryReferences:["memory-read-only"],knowledgeContextReferences:["knowledge-approved"],existingAssetReferences:["asset-existing-article"],evidenceGaps:options.gaps,estimatedValue:RecommendationValue.High,estimatedEffort:RecommendationEffort.Low,strategicRelevance:StrategicRelevance.High,recommendedWorkflow:new RecommendedWorkflowReference("CreateNewContent","Prepare original content in a later governed workflow"),provenance:items[0]!.evidence.provenance});}
function workflow(){return new PinterestRecommendationEvaluationWorkflow(new RecommendationEngine(new RecommendationRepository(new InMemoryRepository())),undefined,undefined,undefined,()=>new Date(at));}

test("request validation is immutable, explicit-context only, and secret free",()=>{assert.throws(()=>new PinterestRecommendationEvaluationId(""));assert.throws(()=>new PinterestRecommendationEvaluationRequest({...request([opportunity("valid")]).properties,opportunityReferences:[]}));const r=request([opportunity("request")]);assert.ok(Object.isFrozen(r));assert.deepEqual(r.approvedCEOPreferenceContext,["explicit-preference"]);assert.equal(/password|token|secret/i.test(JSON.stringify(r)),false);});
test("qualified Opportunities remain distinct and can fuse into one deterministic Recommendation",()=>{const a=opportunity("a"),b=opportunity("b"),service=workflow(),result=service.evaluate(request([a,b]),[input([b,a])]),recommendation=result.recommendations[0]!;assert.equal(result.summary.opportunitiesEvaluated,2);assert.equal(result.summary.recommendationCandidatesCreated,1);assert.deepEqual(recommendation.relatedOpportunities.map(x=>x.id.value),["b","a"]);assert.equal(recommendation.status,RecommendationStatus.ReadyForCEOReview);assert.equal(recommendation.decision,undefined);assert.equal(result.evidenceSets[0]!.businessMemoryReferences[0],"memory-read-only");assert.equal(result.evidenceSets[0]!.knowledgeContextReferences[0],"knowledge-approved");assert.equal(result.evidenceSets[0]!.existingAssetReferences[0],"asset-existing-article");assert.equal(recommendation.recommendedWorkflow?.id,"CreateNewContent");});
test("unsupported, rejected, and cross-package Opportunities cannot silently become Recommendations",()=>{const unsupported=opportunity("unsupported",OpportunityStatus.Rejected),result=workflow().evaluate(request([unsupported]),[input([unsupported])]);assert.equal(result.recommendations.length,0);assert.equal(result.summary.rejectedCandidates,1);const foreign=opportunity("foreign",OpportunityStatus.Qualified,other);assert.throws(()=>workflow().evaluate(request([foreign]),[input([foreign])]),/Business Package/);});
test("contradictions and gaps remain visible rather than becoming zero",()=>{const o=opportunity("contradicted"),contradicted=workflow().evaluate(request([o]),[input([o],{conflict:true})]);assert.equal(contradicted.recommendations.length,0);assert.equal(contradicted.evidenceSets[0]!.contradicting.length,2);const research=workflow().evaluate(request([o]),[input([o],{gaps:[PinterestRecommendationEvidenceGap.UnknownPerformance,PinterestRecommendationEvidenceGap.UnknownAssetFit]})]);assert.equal(research.recommendations[0]!.type,RecommendationType.ResearchOpportunity);assert.equal(research.recommendations[0]!.status,RecommendationStatus.Evaluated);assert.deepEqual(research.evidenceGaps,[PinterestRecommendationEvidenceGap.UnknownAssetFit,PinterestRecommendationEvidenceGap.UnknownPerformance]);});
test("experiment remains advisory and evaluation is immutable with version history",()=>{const o=opportunity("experiment"),service=workflow(),r=request([o]),result=service.evaluate(r,[input([o],{type:RecommendationType.StrategicExperiment})]),recommendation=result.recommendations[0]!;assert.equal(recommendation.type,RecommendationType.StrategicExperiment);assert.equal(result.summary.experimentRecommendations,1);assert.ok(recommendation.version>=2);assert.ok(Object.isFrozen(result));assert.throws(()=>service.evaluate(r,[input([o])]),/already completed/);assert.equal(JSON.stringify(result).includes("competitorCTR"),false);assert.equal(Object.keys(service).some(x=>/execute|publish|generate|network|approve/i.test(x)),false);});
