import test from "node:test";import assert from "node:assert/strict";
import {RecommendationStatus} from "../../src/business/recommendations/RecommendationDomain.ts";import {BusinessPackageId} from "../../src/intelligence/market/MarketIntelligenceDomain.ts";
import {PinterestCreationPlanRepository} from "../../src/integrations/pinterest/PinterestCreationPlanRepository.ts";import {PinterestCreationPlanId,PinterestCreationPlanState,PinterestCreationPlanVersion} from "../../src/integrations/pinterest/PinterestCreationPlanningDomain.ts";
import {PinterestCopyArtifact,PinterestCopyArtifactId,PinterestCopyArtifactVersion,PinterestCopyStatus} from "../../src/integrations/pinterest/PinterestCopyProductionDomain.ts";
import {PinterestVisualArtifactId,PinterestVisualProductionException,PinterestVisualProductionRequest,PinterestVisualStatus,PinterestVisualType,type PinterestVisualDesigner,type PinterestVisualProductionContext} from "../../src/integrations/pinterest/PinterestVisualProductionDomain.ts";import {PinterestVisualProductionWorkflow} from "../../src/integrations/pinterest/PinterestVisualProductionWorkflow.ts";

const pkg=new BusinessPackageId("ALIVO"),at=new Date("2026-08-09T00:00:00Z");
function plan(state=PinterestCreationPlanState.ReadyForProduction,version=1,experiment?:object){return{id:new PinterestCreationPlanId("plan-39"),version:new PinterestCreationPlanVersion(version),state,businessPackageId:pkg,recommendation:{status:RecommendationStatus.ApprovedByCEO,version:7},decision:{recommendationVersion:7},contentDirection:{language:"de"},destination:{assetReference:"book-17"},visualDirection:{mediaType:"image/png",aspectRatio:"2:3",textOverlayAllowed:true},constraints:[{type:"NeverCopy",value:"ReproduceCompetitorVisualComposition"}],patternGuidance:[{reference:"pattern-1",description:"abstract hierarchy"}],experiment,correlationIdentifier:"corr-39",learningTrace:{recommendationId:"rec-7",recommendationVersion:7,ceoDecisionId:"decision-7",opportunityReferences:["opp-1"],patternReferences:["pattern-1"],evidenceReferences:["evidence-1"]}} as never;}
const lineage={planId:"plan-39",planVersion:1,recommendationId:"rec-7",recommendationVersion:7,ceoDecisionId:"decision-7",businessPackageId:"ALIVO",opportunityReferences:["opp-1"],patternReferences:["pattern-1"],evidenceReferences:["evidence-1"],correlationIdentifier:"corr-39"};
const copy=new PinterestCopyArtifact(new PinterestCopyArtifactId("copy-38"),new PinterestCopyArtifactVersion(2),PinterestCopyStatus.ReadyForCreativeAssembly,"variant-1",[],undefined,lineage);
function request(overrides:Partial<{version:number;packageId:BusinessPackageId;assets:readonly string[];variants:number;withCopy:boolean}>= {}){const packageId=overrides.packageId??pkg;return new PinterestVisualProductionRequest(new PinterestVisualArtifactId("visual-39"),"plan-39",overrides.version??1,packageId,"corr-39","TCO",PinterestVisualType.BookCreative,{reference:"visual-rules-1",businessPackageId:packageId,instructions:["human readable"],prohibitedTreatments:["competitor imitation"],approvedAssets:[{reference:"book-17",businessPackageId:packageId,available:true,provenanceReference:"licensed-1"}]},overrides.assets??["book-17"],overrides.withCopy===false?undefined:{artifact:copy,textOverlay:"Besser schlafen",title:"Schlaf",cta:"Lesen",language:"de",destinationReference:"book-17"},overrides.variants??1);}
class FakeDesigner implements PinterestVisualDesigner{calls:PinterestVisualProductionContext[]=[];valid=true;generate(context:PinterestVisualProductionContext){this.calls.push(context);return{visual:{assetReference:`synthetic-${context.variantId}.png`,mediaType:"image/png",width:this.valid?1000:999,height:1500,aspectRatio:"2:3",visibleText:"Besser\n schlafen",language:"de",destinationReference:"book-17",usedAssetReferences:["book-17"],appliedRuleReferences:["visual-rules-1"],originalBusinessCreative:true,changedDimensions:context.experiment?[context.experiment.controlledVariable]:[]},provenance:{designerCapabilityReference:"designer-port",providerReference:"deterministic-fake",renderEngineReference:"none",generatedAt:at}};}}
function setup(value=plan()){const plans=new PinterestCreationPlanRepository();plans.store(value);const designer=new FakeDesigner();return{designer,workflow:new PinterestVisualProductionWorkflow(plans,designer,{supportedMediaTypes:["image/png"],allowedDimensions:[{width:1000,height:1500}],allowedAspectRatios:["2:3"],maximumVariants:3},undefined,undefined,()=>at)};}

test("eligible plan produces an immutable validated visual with exact learning and copy lineage",()=>{const {workflow,designer}=setup(),artifact=workflow.produce(request()).artifacts[0];assert.equal(artifact.status,PinterestVisualStatus.ReadyForCreativeAssembly);assert.equal(artifact.lineage.planVersion,1);assert.equal(artifact.lineage.ceoDecisionId,"decision-7");assert.equal(artifact.lineage.copyArtifactId,"copy-38");assert.equal(artifact.lineage.copyArtifactVersion,2);assert.deepEqual(artifact.lineage.evidenceReferences,["evidence-1"]);assert.equal(designer.calls[0].plan.visualDirection.aspectRatio,"2:3");assert.equal((designer.calls[0].patternGuidance[0] as {reference:string}).reference,"pattern-1");assert.ok(Object.isFrozen(artifact)&&Object.isFrozen(artifact.drafts[0].visual));});
for(const state of [PinterestCreationPlanState.Draft,PinterestCreationPlanState.Superseded,PinterestCreationPlanState.Invalidated,PinterestCreationPlanState.Cancelled])test(`${state} plan cannot produce a visual`,()=>assert.throws(()=>setup(plan(state)).workflow.produce(request()),PinterestVisualProductionException));
test("exact plan version, CEO approval, and Business Package isolation are enforced",()=>{assert.throws(()=>setup().workflow.produce(request({version:2})),/exact current Plan version/);assert.throws(()=>setup().workflow.produce(request({packageId:new BusinessPackageId("BEST-FINDS")})),/Business Package/);const stale=plan() as any;stale.decision.recommendationVersion=6;assert.throws(()=>setup(stale).workflow.produce(request()),/approval/);});
test("Never Copy governance is mandatory and provider receives only abstract pattern guidance",()=>{const value=plan() as any;value.constraints=[];assert.throws(()=>setup(value).workflow.produce(request()),/Never Copy/);const {designer,workflow}=setup();workflow.produce(request());assert.equal("competitiveImage" in designer.calls[0],false);assert.equal(designer.calls[0].patternGuidance.length,1);});
test("missing approved asset is explicit and Designer is not invoked",()=>{const {workflow,designer}=setup(),artifact=workflow.produce(request({assets:["missing-cover"]})).artifacts[0];assert.equal(artifact.status,PinterestVisualStatus.RequiredAssetMissing);assert.deepEqual(artifact.missingAssetReferences,["missing-cover"]);assert.equal(designer.calls.length,0);});
test("Draft validation covers configured dimensions and preserves failed output through revision",()=>{const {workflow,designer}=setup();designer.valid=false;const failed=workflow.produce(request()).artifacts[0];assert.equal(failed.status,PinterestVisualStatus.ValidationFailed);assert.match(failed.validation!.reasons.join(" "),/Dimensions/);designer.valid=true;const ready=workflow.revise(request());assert.equal(ready.status,PinterestVisualStatus.ReadyForCreativeAssembly);assert.equal(ready.drafts.length,2);assert.equal(ready.drafts[0],failed.drafts[0]);assert.equal(ready.drafts[1].revision,2);});
test("copy is not materially rewritten and language, destination, aspect ratio, originality, and brand rules validate",()=>{const {workflow,designer}=setup();designer.generate=context=>({visual:{assetReference:"synthetic.png",mediaType:"image/png",width:1000,height:1500,aspectRatio:"1:1",visibleText:"A different claim",language:"en",destinationReference:"another-product",usedAssetReferences:[],appliedRuleReferences:[],originalBusinessCreative:false,prohibitedTreatments:["competitor imitation"]},provenance:{designerCapabilityReference:"fake",generatedAt:at}});const failed=workflow.produce(request()).artifacts[0];assert.equal(failed.status,PinterestVisualStatus.ValidationFailed);for(const expected of ["Aspect ratio","Required approved asset","destination","visual rules","Prohibited","Originality","approved copy","language"])assert.match(failed.validation!.reasons.join(" "),new RegExp(expected,"i"));});
test("variants require authorization and preserve only the controlled experiment variable",()=>{assert.throws(()=>setup().workflow.produce(request({variants:2})),/approved visual experiment/);const experiment={hypothesis:"hierarchy improves clarity",variableUnderTest:"hierarchy",successMetric:"save rate",evidenceReferences:[]};const result=setup(plan(PinterestCreationPlanState.ReadyForProduction,1,experiment)).workflow.produce(request({variants:2}));assert.deepEqual(result.artifacts.map(x=>x.variantId),["variant-1","variant-2"]);assert.ok(result.artifacts.every(x=>x.lineage.controlledVariable==="hierarchy"));});
test("workflow has no publishing, scheduling, credential, or network boundary",()=>{const source=[PinterestVisualProductionWorkflow,PinterestVisualProductionRequest].map(x=>x.toString()).join(" ");assert.doesNotMatch(source,/createPin|publishPin|schedulePin|password=|api_key=|access_token=/i);assert.deepEqual(Object.getOwnPropertyNames(PinterestVisualProductionWorkflow.prototype).filter(x=>/publish|schedule|network/i.test(x)),[]);});
