import assert from "node:assert/strict";import {test} from "node:test";
import {BusinessPackageId,Confidence,Evidence,EvidenceId,EvidenceStatus,Freshness,FreshnessStatus,MarketObservation,MarketSourceId,ObservationId,Provenance} from "../../src/intelligence/market/MarketIntelligenceDomain.ts";
import {PatternId} from "../../src/business/market/patterns/PatternIntelligenceDomain.ts";
import {AcquisitionCapability,ObservationOrigin,ObservedQuestion,ObservedQuestionId,QuestionCoverageState,QuestionDetection,QuestionRelationshipType,QuestionSourceCategory,QuestionTrend} from "../../src/business/market/questions/QuestionIntelligenceDomain.ts";
import {QUESTION_INTELLIGENCE_EVENTS,QuestionIntelligenceService} from "../../src/business/market/questions/QuestionIntelligenceService.ts";
import {QuestionIntelligenceRepository} from "../../src/business/market/questions/QuestionIntelligenceRepository.ts";
const service=new QuestionIntelligenceService(),pkg=new BusinessPackageId("alivo"),otherPkg=new BusinessPackageId("best-finds");
function observed(id:string,text:string,source=id,category=QuestionSourceCategory.SearchEngine,options:{pkg?:BusinessPackageId;language?:string;market?:string;semantic?:string;independence?:string;origin?:ObservationOrigin;day?:number;quality?:number;detection?:QuestionDetection;capability?:AcquisitionCapability}={}){const day=options.day??1,at=new Date(Date.UTC(2026,0,day)),sid=new MarketSourceId(source),provenance=new Provenance("approved-public-source",at,sid,[`ref-${id}`]),observation=new MarketObservation(new ObservationId(`ob-${id}`),sid,at,options.market??"DE",options.pkg??pkg,text,"QuestionSignal",`payload-${id}`,provenance,new Freshness(FreshnessStatus.Current,at)),evidence=new Evidence(new EvidenceId(`ev-${id}`),[observation.id],provenance,at,new Confidence(options.quality??.8),new Freshness(FreshnessStatus.Current,at),EvidenceStatus.Active);return new ObservedQuestion({id:new ObservedQuestionId(id),version:1,observation,evidence,originalText:text,normalizedText:service.normalize(text),semanticKey:options.semantic??"tired-after-eating-cause",detection:options.detection??service.detect(text),sourceCategory:category,acquisitionCapability:options.capability??AcquisitionCapability.ApprovedSearchInterface,sourceReference:`ref-${id}`,independenceKey:options.independence??`thread-${id}`,language:options.language??"de",market:options.market??"DE",freshness:observation.freshness,sourceQuality:new Confidence(options.quality??.8),origin:options.origin});}
const q1=()=>observed("one","Warum bin ich nach dem Essen immer müde?","bing",QuestionSourceCategory.SearchEngine,{day:1});
function build(items:readonly ObservedQuestion[]=[q1(),observed("two","Wieso bin ich nach dem Essen so müde?","quora",QuestionSourceCategory.QuestionAnswer,{day:2})]){const intent=service.classifyIntent(items[0],["Cause","Understanding"],"The wording asks for an explanation of a cause.",new Confidence(.8));return service.cluster("cluster",items,intent,[1,2,3],service.evaluateCoverage([]),{patternId:new PatternId("question-pattern"),now:new Date("2026-01-04")});}

test("detection distinguishes explicit, implicit, search-intent, non-question and unknown observations",()=>{assert.equal(service.detect("Why am I tired after eating?"),QuestionDetection.ExplicitQuestion);assert.equal(service.detect("I have a problem after eating"),QuestionDetection.ImplicitQuestion);assert.equal(service.detect("tired after eating"),QuestionDetection.SearchIntentPhrase);assert.equal(service.detect("fatigue"),QuestionDetection.NonQuestion);assert.equal(service.detect(""),QuestionDetection.Unknown);});
test("original human wording is immutable and normalization remains separate",()=>{const q=observed("case","Warum BIN ich müde?!");assert.equal(q.originalText,"Warum BIN ich müde?!");assert.equal(q.normalizedText,"warum bin ich müde");assert.notEqual(q.originalText,q.normalizedText);assert.equal(Object.isFrozen(q),true);assert.equal(Reflect.set(q,"originalText","beautified"),false);assert.equal(q.originalText,"Warum BIN ich müde?!");});
test("semantic clustering preserves variants but rejects unrelated semantic needs",()=>{const cluster=build();assert.deepEqual(cluster.variants,["Warum bin ich nach dem Essen immer müde?","Wieso bin ich nach dem Essen so müde?"]);assert.throws(()=>build([q1(),observed("dizzy","Warum bin ich nach dem Essen schwindelig?","forum",QuestionSourceCategory.Forum,{semantic:"dizzy-after-eating-cause"})]),/semantic need/);});
test("canonical wording and provenance always originate from an observed explicit human variant",()=>{const one=q1(),frequent=observed("popular","Warum werde ich nach dem Essen immer müde?","forum",QuestionSourceCategory.Forum,{day:2}),copy=observed("popular-copy",frequent.originalText,"community",QuestionSourceCategory.Community,{day:3}),cluster=build([one,frequent,copy]);assert.equal(cluster.canonical.text,frequent.originalText);assert.ok(cluster.observations.includes(cluster.canonical.selectedObservation));assert.equal(cluster.canonical.provenance.sourceId.value,cluster.canonical.selectedObservation.sourceId.value);assert.notEqual(cluster.canonical.text,"Postprandiale Müdigkeit verstehen");assert.equal(service.h1Contract(cluster).canonicalQuestionText,frequent.originalText);assert.equal(Object.keys(service.h1Contract(cluster)).includes("rewrite"),false);assert.throws(()=>build([observed("ai","Why tired?","ai",QuestionSourceCategory.Other,{origin:ObservationOrigin.Synthetic,language:"en",market:"US"})]),/explicit observed human/);});
test("source diversity and independence are deterministic; same thread and synthetic evidence cannot inflate human demand",()=>{const same1=q1(),same2=observed("copy","Warum bin ich nach dem Essen immer müde?","bing",QuestionSourceCategory.SearchEngine,{independence:"thread-one"}),ai=observed("ai","Warum bin ich nach dem Essen immer müde?","ai",QuestionSourceCategory.Other,{origin:ObservationOrigin.Synthetic}),summary=service.summarize([same1,same2,ai]);assert.equal(summary.observationCount,3);assert.equal(summary.humanObservationCount,2);assert.equal(summary.independentObservationCount,1);assert.equal(summary.sourceCount,1);assert.equal(summary.sourceCategoryCount,1);const diverse=service.summarize([q1(),observed("qa","Wieso bin ich nach dem Essen so müde?","qa",QuestionSourceCategory.QuestionAnswer),observed("forum","Warum macht mich Essen müde?","forum",QuestionSourceCategory.Forum),observed("video","Warum werde ich nach dem Essen müde?","video",QuestionSourceCategory.VideoDiscovery)]);assert.equal(diverse.sourceCount,4);assert.equal(diverse.sourceCategoryCount,4);assert.ok(diverse.confidence.value>summary.confidence.value);assert.equal("searchVolume" in diverse,false);});
test("multi-provider observations preserve category, capability, quality and freshness without a Google dependency",()=>{const bing=q1(),other=observed("engine","Why tired after eating?","duck",QuestionSourceCategory.SearchEngine,{language:"en",market:"US"}),qa=observed("qa","Warum müde?","qa",QuestionSourceCategory.QuestionAnswer),forum=observed("forum","Warum müde?","forum",QuestionSourceCategory.Community),video=observed("video","Warum müde?","video",QuestionSourceCategory.VideoDiscovery,{capability:AcquisitionCapability.OfficialAPI,quality:.6});for(const item of [bing,other,qa,forum,video])assert.ok(item.properties.freshness instanceof Freshness);assert.equal(video.properties.acquisitionCapability,AcquisitionCapability.OfficialAPI);assert.equal(video.properties.sourceQuality.value,.6);assert.equal([bing,other].every(x=>x.sourceId.value!=="google"),true);});
test("clusters enforce Business Package, language and market isolation",()=>{assert.throws(()=>build([q1(),observed("en","Why am I tired after eating?","source",QuestionSourceCategory.Forum,{language:"en"})]),/language/);assert.throws(()=>build([q1(),observed("us","Warum bin ich müde?","source",QuestionSourceCategory.Forum,{market:"US"})]),/market/);assert.throws(()=>build([q1(),observed("other","Warum bin ich müde?","source",QuestionSourceCategory.Forum,{pkg:otherPkg})]),/package/);});
test("intent is separate, extensible and explainable, and question is not keyword/topic/pattern",()=>{const cluster=build();assert.deepEqual(cluster.intent.types,["Cause","Understanding"]);assert.match(cluster.intent.explanation,/cause/);assert.notEqual(cluster.canonical,cluster.intent);assert.equal("keyword" in cluster,false);assert.equal("topic" in cluster,false);assert.ok(cluster.patternId instanceof PatternId);});
test("trends cover emerging, growing, stable, declining, reappearing and insufficient evidence",()=>{assert.equal(service.trend([0,0,4]),QuestionTrend.Emerging);assert.equal(service.trend([1,2,3]),QuestionTrend.Growing);assert.equal(service.trend([2,2,2]),QuestionTrend.Stable);assert.equal(service.trend([3,2,1]),QuestionTrend.Declining);assert.equal(service.trend([2,0,2]),QuestionTrend.Reappearing);assert.equal(service.trend([0,1,1]),QuestionTrend.InsufficientEvidence);});
test("contradictory evidence is preserved and deterministically lowers confidence",()=>{const items=[q1(),observed("two","Wieso bin ich nach dem Essen so müde?","qa",QuestionSourceCategory.QuestionAnswer)],against=observed("against","Interest is declining","analytics",QuestionSourceCategory.Other,{detection:QuestionDetection.NonQuestion}),positive=service.summarize(items),mixed=service.summarize(items,[against]);assert.deepEqual(mixed.contradictingEvidence,[against.properties.evidence]);assert.ok(mixed.confidence.value<positive.confidence.value);assert.equal(mixed.confidence.value,service.summarize(items,[against]).confidence.value);});
test("semantic coverage states and content gaps support duplicate prevention",()=>{assert.equal(service.evaluateCoverage([]).state,QuestionCoverageState.NoCoverage);assert.equal(service.evaluateCoverage([{contentReference:"weak",semanticSimilarity:.3,explanation:"Related only"}]).state,QuestionCoverageState.WeakCoverage);assert.equal(service.evaluateCoverage([{contentReference:"partial",semanticSimilarity:.65,explanation:"Answers part"}]).state,QuestionCoverageState.PartialCoverage);const strong=service.evaluateCoverage([{contentReference:"article-1",semanticSimilarity:.9,explanation:"Different wording answers the same intent"}]);assert.equal(strong.state,QuestionCoverageState.StrongCoverage);const gap=build();assert.ok(gap.contentGap);const covered=service.cluster("covered",gap.observations,gap.intent,[1,2,3],strong,{now:new Date()});assert.equal(covered.contentGap,undefined);});
test("related questions remain distinct and UI read models expose source visibility",()=>{const main=q1(),related=observed("related","Ist Müdigkeit nach dem Essen normal?"),intent=service.classifyIntent(main,["Cause"],"Asks why.",new Confidence(.7)),cluster=service.cluster("detail",[main],intent,[1,2,3],service.evaluateCoverage([]),{related:[{questionId:related.id,relationship:QuestionRelationshipType.RelatedTo,explanation:"Same topic, distinct normality intent"}]});const list=service.toListReadModel(cluster),detail=service.toDetailReadModel(cluster);assert.equal(list.canonicalQuestion,main.originalText);assert.equal(detail.variants[0],main.originalText);assert.equal(detail.sources[0].reference,"ref-one");assert.equal(detail.relatedQuestions[0].questionId,related.id);assert.match(detail.canonicalSelectionExplanation,/evidence/);});
test("foundation is advisory: safe events contain no article generation, publication, approval or memory mutation",()=>{assert.ok(QUESTION_INTELLIGENCE_EVENTS.includes("QuestionCoverageEvaluated"));const serialized=JSON.stringify({service,events:QUESTION_INTELLIGENCE_EVENTS});assert.doesNotMatch(serialized,/article|publish|approve|businessmemory/i);assert.deepEqual(Object.keys(service).filter(x=>/writer|seo|publish|memory/i.test(x)),[]);});
test("repository preserves immutable version history and Business Package isolation",()=>{const repository=new QuestionIntelligenceRepository(),question=q1(),cluster=build([question]);repository.saveObservation(question);repository.saveCluster(cluster);assert.deepEqual(repository.observationHistory(question.id,pkg),[question]);assert.deepEqual(repository.clusterHistory(cluster.id,pkg),[cluster]);assert.deepEqual(repository.clusters(otherPkg),[]);assert.throws(()=>repository.saveObservation(question),/version already exists/);});
