import assert from "node:assert/strict";
import { test } from "node:test";
import { AuditRecorder } from "../../src/core/platform/AuditRecorder.ts";
import { BusinessPackageId, MarketSource, MarketSourceId, Provenance } from "../../src/intelligence/market/MarketIntelligenceDomain.ts";
import { MarketCollectionResult, MarketCollectionResultStatus, MarketSourceAdapterId, MarketSourceAvailability, MarketSourceCapability, MarketSourceDescriptor, MarketSourceHealth, MarketSourceHealthState, MarketSourceState, RawMarketRecord } from "../../src/intelligence/market/integration/MarketSourceIntegrationDomain.ts";
import { MarketSourceIntegrationService } from "../../src/intelligence/market/integration/MarketSourceIntegrationService.ts";
import { DiscoveryFeatureType, DiscoveryRawObservation, QuestionDiscoveryDepth, QuestionDiscoveryProfile, QuestionDiscoveryRequest, QuestionDiscoveryRequestId, QuestionDiscoveryCorrelationId, QuestionDiscoveryRunState, QuestionDiscoveryScope, QuestionDiscoverySeed, QuestionDiscoverySeedType, QuestionDiscoverySourceCategory, QuestionDiscoverySourceState } from "../../src/intelligence/market/questions/QuestionDiscoveryDomain.ts";
import type { QuestionDiscoveryAdapter, QuestionDiscoveryAdapterResult, QuestionDiscoverySourceRequest } from "../../src/intelligence/market/questions/QuestionDiscoveryDomain.ts";
import { QuestionDiscoveryService } from "../../src/intelligence/market/questions/QuestionDiscoveryService.ts";
import { ObservationOrigin, QuestionDetection, QuestionSourceCategory } from "../../src/business/market/questions/QuestionIntelligenceDomain.ts";

const now=new Date("2026-08-09T10:00:00Z"),pkg=new BusinessPackageId("ALIVO"),other=new BusinessPackageId("BEST-FINDS");
const capabilities={search:MarketSourceCapability.SearchQuestionEvidence,community:MarketSourceCapability.CommunityQuestionEvidence,qa:MarketSourceCapability.QuestionAnswerEvidence,video:MarketSourceCapability.VideoDiscoveryEvidence,related:MarketSourceCapability.RelatedQuestionEvidence};
const categories={search:QuestionDiscoverySourceCategory.SearchEngine,community:QuestionDiscoverySourceCategory.Community,qa:QuestionDiscoverySourceCategory.QuestionAnswerPlatform,video:QuestionDiscoverySourceCategory.VideoDiscovery,related:QuestionDiscoverySourceCategory.RelatedQuestion};

class ScriptedAdapter implements QuestionDiscoveryAdapter {
 readonly id:MarketSourceAdapterId;readonly sourceId:MarketSourceId;calls=0;
 constructor(readonly name:string,readonly capability:MarketSourceCapability,readonly category:QuestionDiscoverySourceCategory,private readonly scripts:QuestionDiscoveryAdapterResult[],readonly businessPackage=pkg){this.id=new MarketSourceAdapterId(name);this.sourceId=new MarketSourceId(`source-${name}`);}
 descriptor(){return new MarketSourceDescriptor({adapterId:this.id,source:new MarketSource(this.sourceId,this.name,"approved-test-source"),displayName:this.name,capabilities:[this.capability],state:MarketSourceState.Registered,availability:MarketSourceAvailability.Unknown,health:new MarketSourceHealth(MarketSourceHealthState.Unknown,now),authorizations:[{businessPackageId:this.businessPackage,capabilities:[this.capability]}],registeredAt:now,supportedMarkets:["DE","US"],supportedLanguages:["de","en"]});}
 async collect(request:any){return new MarketCollectionResult(request.id,this.id,this.sourceId,MarketCollectionResultStatus.NoData,[],now,new Provenance("test-transport",now,this.sourceId));}
 async discover(){return this.scripts[Math.min(this.calls++,this.scripts.length-1)];}
 observation(text:string,feature:DiscoveryFeatureType,reference=`public:${this.name}:1`,independenceReference?:string){const provenance=new Provenance("approved-test-transport",now,this.sourceId,[reference]),raw=new RawMarketRecord({id:`raw-${this.name}-${text}`,sourceId:this.sourceId,requestId:"request-1",providerRecordReference:reference,collectedAt:now,observedAt:now,payloadReference:`payload:${this.name}`,provenance,recordType:"question-discovery"});return new DiscoveryRawObservation({rawRecord:raw,provider:this.name,sourceCategory:this.category,featureType:feature,observedText:text,sourceReference:reference,market:"DE",language:"de",seed:new QuestionDiscoverySeed(QuestionDiscoverySeedType.TopicSeed,"metabolism"),context:"minimum public title context",independenceReference});}
}
function success(adapter:ScriptedAdapter,text:string,feature:DiscoveryFeatureType,independenceReference?:string):QuestionDiscoveryAdapterResult{return{state:QuestionDiscoverySourceState.Succeeded,observations:[adapter.observation(text,feature,undefined,independenceReference)]};}
function sourceRequest(capability:MarketSourceCapability,category:QuestionDiscoverySourceCategory):QuestionDiscoverySourceRequest{return{capability,categories:[category]};}
function request(sourceRequests:readonly QuestionDiscoverySourceRequest[],scope=new QuestionDiscoveryScope(pkg,"blog-research","question-intelligence","DE","de"),seed=new QuestionDiscoverySeed(QuestionDiscoverySeedType.TopicSeed,"metabolism")){return new QuestionDiscoveryRequest(new QuestionDiscoveryRequestId("request-1"),new QuestionDiscoveryCorrelationId("correlation-1"),scope,seed,QuestionDiscoveryDepth.Standard,86_400_000,sourceRequests,50,now);}
function profile(scope=new QuestionDiscoveryScope(pkg,"blog-research","question-intelligence","DE","de"),providers:readonly string[]=[]){return new QuestionDiscoveryProfile(scope,Object.values(QuestionDiscoverySourceCategory),providers,[],QuestionDiscoveryDepth.Standard,86_400_000,50,4);}
function setup(adapters:ScriptedAdapter[]){const registry=new MarketSourceIntegrationService(undefined,undefined,undefined,()=>now);for(const adapter of adapters){registry.register(adapter,"CEO");registry.enable(adapter.id,"CEO");}return{service:new QuestionDiscoveryService(registry,undefined,undefined,()=>now),registry};}

test("request and profile preserve package, market, language, purpose, freshness, depth and seeds without treating a seed as evidence",async()=>{const adapter=new ScriptedAdapter("engine-a",capabilities.search,categories.search,[]);adapter["scripts"].push(success(adapter,"müde nach dem essen",DiscoveryFeatureType.SearchIntentPhrase));const {service}=setup([adapter]),topic=request([sourceRequest(capabilities.search,categories.search)]),run=await service.discover(topic,profile());assert.equal(topic.scope.businessPackageId.value,"ALIVO");assert.equal(run.summary.market,"DE");assert.equal(run.summary.language,"de");assert.equal(run.summary.freshnessWindowMs,86_400_000);assert.equal(run.observations.length,1);assert.notEqual(run.observations[0].properties.observedText,topic.seed.value);assert.equal(run.questionIntelligenceHandoff[0].originalText,"müde nach dem essen");assert.equal(run.questionIntelligenceHandoff[0].properties.detection,QuestionDetection.SearchIntentPhrase);const question=request([sourceRequest(capabilities.search,categories.search)],undefined,new QuestionDiscoverySeed(QuestionDiscoverySeedType.QuestionSeed,"Warum müde?"));assert.equal(question.seed.type,QuestionDiscoverySeedType.QuestionSeed);});

test("capability selection supports two independent search engines and has no privileged provider",async()=>{const a=new ScriptedAdapter("engine-a",capabilities.search,categories.search,[]),b=new ScriptedAdapter("engine-b",capabilities.search,categories.search,[]);a["scripts"].push(success(a,"Warum bin ich nach dem Essen müde?",DiscoveryFeatureType.SearchResultQuestion));b["scripts"].push(success(b,"Wieso werde ich nach dem Essen müde?",DiscoveryFeatureType.QuerySuggestion));const {service}=setup([a,b]),run=await service.discover(request([sourceRequest(capabilities.search,categories.search)]),profile());assert.equal(run.summary.sourcesSucceeded,2);assert.deepEqual(run.sourceResults.map(x=>x.adapterId.value),["engine-a","engine-b"]);assert.equal(run.questionIntelligenceHandoff[0].properties.sourceCategory,QuestionSourceCategory.SearchEngine);assert.equal(run.observations[1].properties.featureType,DiscoveryFeatureType.QuerySuggestion);});

test("community, Q&A, video, related-question and topic portal observations retain exact wording, feature, provenance and timestamps",async()=>{const specs:[[string,MarketSourceCapability,QuestionDiscoverySourceCategory,DiscoveryFeatureType,string],...Array<[string,MarketSourceCapability,QuestionDiscoverySourceCategory,DiscoveryFeatureType,string]>]=[["community",capabilities.community,categories.community,DiscoveryFeatureType.ThreadTitle,"Warum bin ich nach dem Essen müde?"],["qa",capabilities.qa,categories.qa,DiscoveryFeatureType.QuestionAnswer,"Ist Müdigkeit nach dem Essen normal?"],["video",capabilities.video,categories.video,DiscoveryFeatureType.VideoTitle,"Müde nach dem Essen – was hilft?"],["related",capabilities.related,categories.related,DiscoveryFeatureType.RelatedQuestion,"Warum macht Zucker müde?"]];const adapters=specs.map(([n,c,k,f,t])=>{const a=new ScriptedAdapter(n,c,k,[]);a["scripts"].push(success(a,t,f));return a;}),portalCapability=new MarketSourceCapability("TopicPortalQuestionEvidence"),portal=new ScriptedAdapter("portal",portalCapability,QuestionDiscoverySourceCategory.TopicPortal,[]);portal["scripts"].push(success(portal,"Wie beeinflusst Schlaf den Stoffwechsel?",DiscoveryFeatureType.PortalQuestion));adapters.push(portal);const {service}=setup(adapters),run=await service.discover(request(adapters.map(a=>sourceRequest(a.capability,a.category))),profile());assert.equal(run.summary.sourceCategoryCoverage,5);assert.deepEqual(run.observations.map(x=>x.properties.observedText),specs.map(x=>x[4]).concat("Wie beeinflusst Schlaf den Stoffwechsel?"));for(const item of run.observations){assert.equal(item.observedAt?.toISOString(),now.toISOString());assert.equal(item.collectedAt.toISOString(),now.toISOString());assert.equal(item.properties.rawRecord.provenance.sourceId.value,item.properties.rawRecord.properties.sourceId.value);}assert.equal(run.observations[3].properties.featureType,DiscoveryFeatureType.RelatedQuestion);});

test("partial outcomes keep NoData, unavailable, unsupported, authentication, authorization and rate limits distinct",async()=>{const ok=new ScriptedAdapter("ok",capabilities.search,categories.search,[]),empty=new ScriptedAdapter("empty",capabilities.community,categories.community,[{state:QuestionDiscoverySourceState.NoData,observations:[]}]),auth=new ScriptedAdapter("auth",capabilities.qa,categories.qa,[{state:QuestionDiscoverySourceState.AuthenticationRequired,observations:[],safeMessage:"Credential reference required"}]),denied=new ScriptedAdapter("denied",capabilities.video,categories.video,[{state:QuestionDiscoverySourceState.PermissionDenied,observations:[],safeMessage:"Scope denied"}]),limited=new ScriptedAdapter("limited",capabilities.related,categories.related,[{state:QuestionDiscoverySourceState.RateLimited,observations:[],safeMessage:"Provider limit",retryAfter:new Date(now.getTime()+60_000)}]);ok["scripts"].push(success(ok,"Warum müde?",DiscoveryFeatureType.SearchResultQuestion));const {service}=setup([ok,empty,auth,denied,limited]),unknown=new MarketSourceCapability("UnsupportedQuestionEvidence"),run=await service.discover(request([sourceRequest(capabilities.search,categories.search),sourceRequest(capabilities.community,categories.community),sourceRequest(capabilities.qa,categories.qa),sourceRequest(capabilities.video,categories.video),sourceRequest(capabilities.related,categories.related),sourceRequest(unknown,QuestionDiscoverySourceCategory.TopicPortal)]),profile());assert.equal(run.state,QuestionDiscoveryRunState.Partial);assert.deepEqual(run.sourceResults.map(x=>x.state),[QuestionDiscoverySourceState.Succeeded,QuestionDiscoverySourceState.NoData,QuestionDiscoverySourceState.AuthenticationRequired,QuestionDiscoverySourceState.PermissionDenied,QuestionDiscoverySourceState.RateLimited,QuestionDiscoverySourceState.Unsupported]);assert.equal(run.summary.rawObservations,1);assert.equal(run.summary.sourcesUnavailable,1);assert.equal(run.summary.sourcesFailed,3);});

test("retry is source-specific, leaves successful sources untouched, and permits credential correction recovery",async()=>{const ok=new ScriptedAdapter("ok",capabilities.search,categories.search,[]),recovering=new ScriptedAdapter("recover",capabilities.qa,categories.qa,[{state:QuestionDiscoverySourceState.InvalidCredential,observations:[],safeMessage:"Credential correction required"}]);ok["scripts"].push(success(ok,"Warum müde?",DiscoveryFeatureType.SearchResultQuestion));recovering["scripts"].push(success(recovering,"Was hilft gegen Müdigkeit?",DiscoveryFeatureType.QuestionAnswer));const {service}=setup([ok,recovering]),run=await service.discover(request([sourceRequest(capabilities.search,categories.search),sourceRequest(capabilities.qa,categories.qa)]),profile()),retried=await service.retry(run,"recover",profile());assert.equal(ok.calls,1);assert.equal(recovering.calls,2);assert.equal(retried.state,QuestionDiscoveryRunState.Completed);assert.equal(retried.summary.rawObservations,2);});

test("cancellation preserves completed partial evidence and does not start later sources",async()=>{const controller=new AbortController(),first=new ScriptedAdapter("first",capabilities.search,categories.search,[]),later=new ScriptedAdapter("later",capabilities.community,categories.community,[]);first["scripts"].push({state:QuestionDiscoverySourceState.Succeeded,observations:[first.observation("Warum müde?",DiscoveryFeatureType.SearchResultQuestion)]});const original=first.discover.bind(first);first.discover=async(...args)=>{const result=await original(...args);controller.abort();return result;};later["scripts"].push(success(later,"Wer kann helfen?",DiscoveryFeatureType.ThreadTitle));const {service}=setup([first,later]),run=await service.discover(request([sourceRequest(capabilities.search,categories.search),sourceRequest(capabilities.community,categories.community)]),profile(),controller.signal);assert.equal(run.state,QuestionDiscoveryRunState.Cancelled);assert.equal(run.observations.length,1);assert.equal(later.calls,0);});

test("duplicate independence evidence cannot inflate human observations and adapters never rewrite or choose downstream output",async()=>{const a=new ScriptedAdapter("a",capabilities.search,categories.search,[]),b=new ScriptedAdapter("b",capabilities.community,categories.community,[]),wording="müde nach dem essen";a["scripts"].push(success(a,wording,DiscoveryFeatureType.QuerySuggestion,"syndicated-item"));b["scripts"].push(success(b,wording,DiscoveryFeatureType.ThreadTitle,"syndicated-item"));const {service}=setup([a,b]),run=await service.discover(request([sourceRequest(capabilities.search,categories.search),sourceRequest(capabilities.community,categories.community)]),profile());assert.equal(run.questionIntelligenceHandoff[0].originalText,wording);assert.equal(run.questionIntelligenceHandoff[1].originalText,wording);assert.equal(run.questionIntelligenceHandoff[0].origin,ObservationOrigin.Human);assert.equal(run.questionIntelligenceHandoff[1].origin,ObservationOrigin.Synthetic);assert.equal("canonical" in run.observations[0],false);assert.equal("h1" in run,false);assert.equal("article" in run,false);});

test("Business Package and language isolation are enforced, with UI-safe health, management and audit models",async()=>{const adapter=new ScriptedAdapter("managed",capabilities.search,categories.search,[]);adapter["scripts"].push(success(adapter,"Warum müde?",DiscoveryFeatureType.SearchResultQuestion));const audit=new AuditRecorder(),{registry}=setup([adapter]),service=new QuestionDiscoveryService(registry,undefined,audit,()=>now);await assert.rejects(()=>service.discover(request([sourceRequest(capabilities.search,categories.search)]),profile(new QuestionDiscoveryScope(other,"blog-research","question-intelligence","DE","de"))),/scope differ/);const run=await service.discover(request([sourceRequest(capabilities.search,categories.search)]),profile());assert.equal(run.request.scope.language,"de");assert.equal(service.sourceHealth()[0].status,QuestionDiscoverySourceState.Succeeded);assert.equal(service.sourceManagement()[0].enabled,true);assert.equal(service.sourceManagement()[0].source,"managed");const serialized=JSON.stringify({run,health:service.sourceHealth(),management:service.sourceManagement(),audit:audit.getEvents()});assert.doesNotMatch(serialized,/secret-value|credential-value/);assert.ok(audit.getEvents().length>=3);});
