import assert from "node:assert/strict";import {test} from "node:test";
import {AuthorizationDecision,AuthorizationDecisionValue} from "../../src/core/platform/AuthorizationDecision.ts";import {InMemoryRepository} from "../../src/core/platform/Repository.ts";import {IdentityId} from "../../src/core/platform/IdentityId.ts";import {Permission} from "../../src/core/platform/Permission.ts";
import {BusinessPackageId,Confidence,Evidence,EvidenceId,EvidenceStatus,Freshness,FreshnessStatus,MarketSourceId,ObservationId,Provenance} from "../../src/intelligence/market/MarketIntelligenceDomain.ts";
import {BusinessRecommendation,CEODecision,RecommendationCandidate,RecommendationEffort,RecommendationEvidence,RecommendationEvidenceItem,RecommendationEvidenceRole,RecommendationId,RecommendationObjective,RecommendationOutcomeReference,RecommendationPriority,RecommendationStatus,RecommendationType,RecommendationValue,RecommendedWorkflowReference,StrategicRelevance} from "../../src/business/recommendations/RecommendationDomain.ts";import {RecommendationEngine} from "../../src/business/recommendations/RecommendationEngine.ts";import {RecommendationRepository} from "../../src/business/recommendations/RecommendationRepository.ts";
const at=new Date("2026-01-01T00:00:00Z"),later=new Date("2026-01-02T00:00:00Z"),pkg=new BusinessPackageId("alivo"),other=new BusinessPackageId("best-finds");
function item(id:string,source:string,role=RecommendationEvidenceRole.Supporting,fresh=FreshnessStatus.Current){const provenance=new Provenance("verified",at,new MarketSourceId(source),[id]),evidence=new Evidence(new EvidenceId(id),[new ObservationId(`ob-${id}`)],provenance,at,new Confidence(.8),new Freshness(fresh,at),EvidenceStatus.Active);return new RecommendationEvidenceItem(evidence,"Market Intelligence","signal",role,true);}
function candidate(id="r",businessPackageId=pkg,items=[item("one","source-a"),item("two","source-b")]){const evidence=new RecommendationEvidence(items),objective=new RecommendationObjective("growth","Strategic","Grow qualified audience",businessPackageId,"approved strategy","target-1");return new RecommendationCandidate({id:new RecommendationId(id),type:RecommendationType.AudienceOpportunity,objective,businessPackageId,evidence,relatedBusinessMemory:["memory-approved-1"],provenance:items[0]!.evidence.provenance,createdAt:at});}
function setup(c=candidate()){const engine=new RecommendationEngine(new RecommendationRepository(new InMemoryRepository()));engine.registerCandidate(c);const evaluation=engine.evaluateCandidate(c,{value:RecommendationValue.High,effort:RecommendationEffort.Low,strategicRelevance:StrategicRelevance.High}),recommendation=engine.createRecommendation(c,evaluation,later);return{engine,evaluation,recommendation};}
const permission=new Permission({identifier:"recommendation.ceo-decision",resourceCategory:"recommendation",action:"ceo-decision",scope:"alivo"});
function authorization(allowed=true){return new AuthorizationDecision({decision:allowed?AuthorizationDecisionValue.Allowed:AuthorizationDecisionValue.Denied,reason:"external authority result",identity:new IdentityId("ceo"),permission,policyIdentifier:"foundation.ceo-authority",timestamp:later});}
test("identity, generic type and objective are immutable and validated",()=>{const id=new RecommendationId("stable");assert.ok(id.equals(new RecommendationId("stable")));assert.ok(Object.isFrozen(id));assert.throws(()=>new RecommendationId(""),/empty/);assert.equal(RecommendationType.ProductOpportunity,"ProductOpportunity");assert.throws(()=>new RecommendationObjective("","type","description",pkg),/identifier/);});
test("candidate requires supporting evidence and preserves support, contradictions, provenance and source diversity",()=>{assert.throws(()=>new RecommendationEvidence([item("x","a",RecommendationEvidenceRole.Contradicting)]),/supporting/);const conflict=item("conflict","source-c",RecommendationEvidenceRole.Contradicting),c=candidate("mixed",pkg,[item("a","source-a"),item("b","source-b"),conflict]);assert.equal(c.evidence.supporting.length,2);assert.equal(c.evidence.contradicting[0],conflict);assert.equal(c.evidence.sourceDiversity,3);assert.ok(Object.isFrozen(c));});
test("evaluation is deterministic, explainable and handles qualitative fields and Unknown",()=>{const c=candidate(),engine=new RecommendationEngine(new RecommendationRepository(new InMemoryRepository())),a=engine.evaluateCandidate(c,{value:RecommendationValue.High,effort:RecommendationEffort.Low,strategicRelevance:StrategicRelevance.High}),b=engine.evaluateCandidate(c,{value:RecommendationValue.High,effort:RecommendationEffort.Low,strategicRelevance:StrategicRelevance.High});assert.deepEqual(a,b);assert.ok(a.confidence.value<1);assert.equal(a.value,RecommendationValue.High);assert.equal(a.effort,RecommendationEffort.Low);assert.equal(a.strategicRelevance,StrategicRelevance.High);assert.notEqual(a.priority,RecommendationPriority.Unranked);assert.equal(engine.evaluateEffort(),RecommendationEffort.Unknown);assert.equal(engine.evaluateStrategicRelevance(),StrategicRelevance.Unknown);});
test("contradiction remains visible, lowers confidence, raises risk and can block readiness",()=>{const clean=candidate(),conflicted=candidate("conflicted",pkg,[item("a","one"),item("x","two",RecommendationEvidenceRole.Contradicting),item("y","three",RecommendationEvidenceRole.Contradicting)]),engine=new RecommendationEngine(new RecommendationRepository(new InMemoryRepository())),a=engine.evaluateCandidate(clean,{effort:RecommendationEffort.Low}),b=engine.evaluateCandidate(conflicted,{effort:RecommendationEffort.Low});assert.ok(b.confidence.value<a.confidence.value);assert.equal(b.readyForCEOReview,false);assert.equal(b.evidence,undefined);assert.equal(conflicted.evidence.contradicting.length,2);});
test("TCO path is required for ReadyForCEOReview and engine cannot self-approve",()=>{const{engine,recommendation}=setup();assert.throws(()=>engine.markReadyForCEOReview(recommendation,"",later),/TCO/);const ready=engine.markReadyForCEOReview(recommendation,"tco-review-1",later);assert.equal(ready.status,RecommendationStatus.ReadyForCEOReview);assert.equal(Object.keys(engine).some(k=>/approve|execute|publish/i.test(k)),false);});
test("externally authorized CEO decisions append immutable versions and preserve history",()=>{for(const [decision,status] of [[CEODecision.Approved,RecommendationStatus.ApprovedByCEO],[CEODecision.Rejected,RecommendationStatus.RejectedByCEO],[CEODecision.Deferred,RecommendationStatus.Deferred]] as const){const{engine,recommendation}=setup(candidate(`decision-${decision}`)),ready=engine.markReadyForCEOReview(recommendation,"tco-review",later),decided=engine.recordExternallyAuthorizedCEODecision(ready,decision,authorization(),later,"CEO rationale");assert.equal(decided.status,status);assert.equal(decided.decision?.authorizingIdentityReference,"ceo");assert.deepEqual(engine.history(decided.id,pkg),[recommendation,ready,decided]);assert.ok(Object.isFrozen(decided));}});
test("unauthorized decision is rejected",()=>{const{engine,recommendation}=setup(),ready=engine.markReadyForCEOReview(recommendation,"tco",later);assert.throws(()=>engine.recordExternallyAuthorizedCEODecision(ready,CEODecision.Approved,authorization(false),later),/authorization/);});
test("evidence, workflow, outcome and supersession changes version without executing anything",()=>{const{engine,recommendation}=setup(),withEvidence=engine.attachContradictoryEvidence(recommendation,item("new-conflict","third",RecommendationEvidenceRole.Contradicting),later),workflow=new BusinessRecommendation({...withEvidence.properties,version:withEvidence.version+1,recommendedWorkflow:new RecommendedWorkflowReference("approved-workflow","research topic")});engine.repository.store(workflow);const outcome=engine.attachOutcomeReference(workflow,new RecommendationOutcomeReference(workflow.id,"expected-1"),later),superseded=engine.supersede(outcome,"new market evidence",later);assert.equal(recommendation.evidence.contradicting.length,0);assert.equal(withEvidence.evidence.contradicting.length,1);assert.equal(workflow.recommendedWorkflow?.id,"approved-workflow");assert.equal(outcome.outcomes.length,1);assert.equal(superseded.status,RecommendationStatus.Superseded);assert.equal(engine.repository.superseded(workflow.id,pkg).length,1);});
test("repository ordering and Business Package isolation are deterministic",()=>{const repository=new RecommendationRepository(new InMemoryRepository()),engine=new RecommendationEngine(repository);for(const c of [candidate("z",pkg),candidate("a",other)]){engine.registerCandidate(c);engine.createRecommendation(c,engine.evaluateCandidate(c),later);}assert.deepEqual(engine.query().map(r=>`${r.businessPackageId.value}:${r.id.value}`),["alivo:z","best-finds:a"]);assert.deepEqual(engine.query({businessPackageId:pkg}).map(r=>r.id.value),["z"]);assert.equal(engine.retrieve(new RecommendationId("z"),other),undefined);});
