import assert from "node:assert/strict";
import { mkdtemp, readFile, rm, unlink, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { afterEach, test } from "node:test";
import { BackupState, DEFAULT_RECOVERY_POLICY } from "../../src/recovery/RecoveryContracts.ts";
import { RecoveryManager } from "../../src/recovery/RecoveryManager.ts";

const roots:string[]=[];afterEach(async()=>{await Promise.all(roots.splice(0).map(x=>rm(x,{recursive:true,force:true})))});
const artifact=(stableId:string,version=1,dependencies:string[]=[]):any=>({stableId,version,businessPackageId:"PACKAGE-ALIVO",type:stableId.split("-")[0],updatedAt:`2026-0${Math.min(version,9)}-01T00:00:00.000Z`,payload:{title:stableId,value:version},dependencies,provenance:"governed-command"});
async function setup(retention=12){const root=await mkdtemp(join(tmpdir(),"alivo-recovery-"));roots.push(root);const clock=()=>new Date("2026-08-09T12:34:56.000Z");return{root,manager:new RecoveryManager(join(root,"active"),join(root,"snapshots"),"1.0.0",1,{...DEFAULT_RECOVERY_POLICY,backupLocation:join(root,"backups"),retentionGenerations:retention},clock)}}

test("transactional writes create version-aware integrity metadata and legitimate updates remain healthy",async()=>{const {manager}=await setup();await manager.commit(artifact("Books-one"));await manager.commit(artifact("Books-one",2));assert.deepEqual(await manager.validateActive(),{healthy:["Books-one"],missing:[],corrupt:[]});});
test("missing and corrupt artifacts are detected and surgically self-healed from the newest valid snapshot",async()=>{const {root,manager}=await setup();await manager.commit(artifact("Library-one"));const active=join(root,"active","Library-one.json");await unlink(active);assert.deepEqual((await manager.validateActive()).missing,["Library-one"]);assert.equal(await manager.selfHeal("Library-one"),true);await writeFile(active,"tampered");assert.deepEqual((await manager.validateActive()).corrupt,["Library-one"]);assert.equal(await manager.selfHeal("Library-one"),true);assert.equal(manager.history.every(x=>x.validation==="PASS"),true);});
test("backup creation is atomic, verified, multi-generation, and detects tampering",async()=>{const {manager}=await setup();const first=await manager.createBackup([artifact("Books-one"),artifact("Pins-one")]);assert.equal(first.state,BackupState.Verified);assert.equal(first.manifest.businessPackageScope[0],"PACKAGE-ALIVO");const checked=await manager.verifyBackup(first.path);assert.equal(checked.state,BackupState.Verified);await writeFile(first.path,(await readFile(first.path,"utf8")).replace("PACKAGE-ALIVO","PACKAGE-TAMPER"));assert.equal((await manager.verifyBackup(first.path)).state,BackupState.Corrupt);});
test("ordinary backup refuses credential-shaped content",async()=>{const {manager}=await setup();await assert.rejects(manager.createBackup([{...artifact("Configuration-one"),payload:{apiKey:"PLAINTEXT-PROTECTED-MATERIAL"}}]),/credential material/);});
test("approved-path discovery classifies verified, corrupt, and unknown sources without disk scraping",async()=>{const {root,manager}=await setup();const backup=await manager.createBackup([artifact("Books-one")]);const bad=join(root,"bad.zip");await writeFile(bad,"broken");const sources=await manager.scan([backup.path,bad,join(root,"CEO-selected-missing")]);assert.deepEqual(sources.map(x=>x.state),["Verified","Corrupt","Unknown"]);});
test("salvage deduplicates stable identity, imports newer valid records, rejects orphans, and stops conflicts",async()=>{const {manager}=await setup();const base=[artifact("Books-one"),artifact("Knowledge-parent")];const plan=manager.plan("verified.zip",base,[artifact("Books-one"),artifact("Books-one",2),artifact("Blogs-new",2,["Knowledge-parent"]),artifact("Pins-orphan",2,["missing"]),{...artifact("Knowledge-parent"),payload:{title:"conflict"}}]);assert.deepEqual(plan.recoverable.map(x=>x.stableId),["Books-one","Blogs-new"]);assert.equal(plan.rejected[0].reason.startsWith("Missing dependencies"),true);assert.equal(plan.conflicts.length,1);assert.equal(plan.safe,false);});
test("fresh-install restore creates forensic evidence and activates only a safe clean target",async()=>{const {root,manager}=await setup();const backup=await manager.createBackup([artifact("Books-one"),artifact("Knowledge-one"),artifact("Blogs-one",1,["Knowledge-one"]),artifact("Pins-one"),artifact("Learning-one"),artifact("Decision-one")]);const plan=manager.plan(backup.path,(await manager.verifyBackup(backup.path)).artifacts!,[artifact("Questions-new",2)]);const target=join(root,"fresh-install-state"),report=await manager.restore(backup.path,plan,target);assert.equal(report.validation,"PASS");assert.equal(report.activation,"Activated");assert.equal(JSON.parse(await readFile(join(target,"Questions-new.json"),"utf8")).version,2);assert.equal(manager.phases.at(-1),"Completed");});
test("ambiguous restore never activates and repeated corruption escalates without a recovery loop",async()=>{const {root,manager}=await setup();const backup=await manager.createBackup([artifact("Books-one")]);const base=artifact("Books-one"),plan=manager.plan(backup.path,[base],[{...base,payload:{title:"independent valid conflict"}}]);const report=await manager.restore(backup.path,plan,join(root,"target"));assert.equal(report.activation,"Not Activated");assert.equal(await manager.selfHeal("never-existed"),false);assert.equal(await manager.selfHeal("never-existed"),false);assert.equal(await manager.selfHeal("never-existed"),false);assert.match(manager.history.at(-1)!.problem,/Repeated corruption/);});
test("monthly policy has a deterministic first-of-month schedule and governed defaults",async()=>{const {manager}=await setup();assert.equal(manager.policy.monthlyBackupEnabled,true);assert.equal(manager.policy.retentionGenerations,12);assert.equal(manager.nextScheduledBackup(new Date("2026-08-09T20:00:00Z")).toISOString(),"2026-09-01T00:00:00.000Z");});
