const $=selector=>document.querySelector(selector),packageId="ALIVO",pageSize=25;
const actionStates=new Set(["Submitting","Succeeded","Failed","Conflict","AuthorizationDenied","StaleVersion"]),promotionStates=new Set(["Enabled","Held","Disabled","Candidates","Produced","Queued","Published","Partial","Creative Diversity Insufficient"]);
let view="pipeline",page=1,selected,model={businessPackageId:packageId,items:[],total:0,page:1,pageSize,counts:{},pipeline:[]};
const escapeHtml=value=>String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[char]);
const words=value=>String(value??"Unavailable").replace(/([a-z])([A-Z])/g,"$1 $2").replaceAll("_"," ");
const safeUrl=value=>{try{const url=new URL(value);return ["https:","http:"].includes(url.protocol)?url.href:"#"}catch{return "#"}};
const external=(url,label)=>`<a class="external-link" href="${escapeHtml(safeUrl(url))}" target="_blank" rel="noopener noreferrer">${escapeHtml(label)} ↗</a>`;
const badge=value=>`<span class="state ${String(value).toLowerCase().replaceAll(" ","-")}">${escapeHtml(words(value))}</span>`;
function query(){return{businessPackageId:packageId,view,page,pageSize,search:$("#blog-search").value,status:$("#blog-status").value,language:$("#blog-language").value,market:$("#blog-market").value,date:$("#blog-date").value,sort:$("#blog-sort").value}}
async function load(){$("#blog-loading").hidden=false;$("#blog-error").hidden=true;try{const result=await window.alivoBlogs?.read?.(query());model=result||model;if(model.businessPackageId!==packageId)throw Error("Cross-package response blocked");render()}catch{$("#blog-error").hidden=false}finally{$("#blog-loading").hidden=true}}
function render(){const names=["In Planning","Writing","Awaiting CEO Review","Revision Required","Approved","Publishing","Published","Attention Required"];$("#blog-pipeline-summary").innerHTML=names.map(label=>`<button data-summary="${escapeHtml(label)}" class="pipeline-metric ${label==="Awaiting CEO Review"?"awaiting":""}"><span>${label}</span><strong>${model.counts[label]??0}</strong></button>`).join("");$("#blog-review-count").textContent=model.counts["Awaiting CEO Review"]??0;$("#pipeline-board").hidden=view!=="pipeline";$("#pipeline-board").innerHTML=model.pipeline.map(x=>`<div><span>${escapeHtml(words(x.state))}</span><strong>${x.count}</strong></div>`).join("");const publishing=view==="publishing",published=view==="published",approved=view==="approved";const headers=publishing?["H1","Status","Site / attempt","Authentication","Post ID","Canonical URL","Last update"]:published?["H1","Language / market","Published","Canonical URL","Primary Book","Pinterest Promotion","Performance"]:approved?["H1","Language","Approved at","Package status","Publishing status"]:["H1 / Blog Title","Language / Market","CanonicalQuestion","Draft Version","Validation","Primary Book","Created","Priority","Status"];
$("#blog-table").innerHTML=`<div class="blog-row blog-head">${headers.map(x=>`<span>${x}</span>`).join("")}</div>`+model.items.map(item=>row(item,publishing,published,approved)).join("");$("#blog-page").textContent=`Page ${model.page} · ${model.total} Blogs`;$("#blog-previous").disabled=model.page<=1;$("#blog-next").disabled=model.page*model.pageSize>=model.total;document.querySelectorAll("[data-blog-id]").forEach(x=>x.onclick=()=>openDetail(x.dataset.blogId));history.replaceState({},"",`#blogs?${new URLSearchParams({view,page:String(page)})}`)}
function row(x,publishing,published,approved){if(publishing)return `<button class="blog-row publishing-row" data-blog-id="${x.id}"><strong>${escapeHtml(x.h1)}</strong>${badge(x.publishingStatus||x.status)}<span>${escapeHtml(x.site||"—")} · ${x.attempt??"—"}</span>${badge(x.authenticationState||"Not Required")}<span>${escapeHtml(x.postId||"—")}</span><span>${x.canonicalUrl?external(x.canonicalUrl,"Open"):"—"}</span><span>${escapeHtml(x.updated||x.created)}</span></button>`;if(published)return `<button class="blog-row published-row" data-blog-id="${x.id}"><strong>${escapeHtml(x.h1)}</strong><span>${escapeHtml(x.language)} · ${escapeHtml(x.market)}</span><span>${escapeHtml(x.publishedAt||"—")}</span><span>${x.canonicalUrl?external(x.canonicalUrl,"Open published Blog"):"—"}</span><span>${escapeHtml(x.primaryBook)}</span>${badge(x.promotionStatus||"Disabled")}<span>${escapeHtml(x.performanceSummary||"Unavailable")}</span></button>`;if(approved)return `<button class="blog-row approved-row" data-blog-id="${x.id}"><strong>${escapeHtml(x.h1)}</strong><span>${escapeHtml(x.language)}</span><span>${escapeHtml(x.approvedAt||"—")}</span>${badge(x.packageStatus||"Preparing")}${badge(x.publishingStatus||"Not Started")}</button>`;return `<button class="blog-row" data-blog-id="${x.id}"><strong>${escapeHtml(x.h1)}</strong><span>${escapeHtml(x.language)}<small>${escapeHtml(x.market)}</small></span><span>${escapeHtml(x.canonicalQuestion)}</span><span>v${x.draftVersion}</span>${badge(x.validationState)}<span>${escapeHtml(x.primaryBook)}</span><span>${escapeHtml(x.created)}</span><span>${escapeHtml(x.priority)}</span>${badge(x.status)}</button>`}
async function openDetail(id,version){selected=await window.alivoBlogs?.detail?.({businessPackageId:packageId,blogId:id,version});if(!selected||selected.businessPackageId!==packageId)return;renderDetail(selected)}
function renderArticle(blocks){return blocks.map(block=>{const text=escapeHtml(block.text);if(block.type==="h1")return `<h1>${text}</h1>`;if(block.type==="h2")return `<h2>${text}</h2>`;if(block.type==="h3")return `<h3>${text}</h3>`;if(block.type==="link"||block.type==="book-link")return `<p>${external(block.url,text)}</p>`;if(block.type==="primary-cta")return `<aside class="reader-cta"><strong>Primary Book</strong><p>${text}</p>${external(block.url,"Open Book")}</aside>`;return `<p>${text}</p>`}).join("")}
function renderDetail(d){const stale=d.staleVersion||d.supersededByVersion;const findings=d.validations.map(v=>`<details class="validation ${v.state.toLowerCase()}"><summary><span>${escapeHtml(v.label)}</span>${badge(v.state)}</summary>${v.issues.length?v.issues.map(i=>`<div class="finding"><strong>${escapeHtml(i.severity)}</strong><p>${escapeHtml(i.explanation)}</p><small>${escapeHtml(i.section||"")}</small>${i.nextAction?`<em>Next: ${escapeHtml(i.nextAction)}</em>`:""}</div>`).join(""):'<p class="validation-clear">No findings reported.</p>'}</details>`).join("");
$("#blog-detail").classList.add("open");$("#blog-detail").innerHTML=`<button class="detail-close" aria-label="Close">×</button>${stale?`<div class="stale-warning"><strong>Newer Version Available</strong><span>This review is no longer current.</span><button class="link" data-latest>Refresh / Open latest version →</button></div>`:""}<div class="review-top"><div><p class="eyebrow">Reader Preview · Draft v${d.draftVersion}</p><span class="h1-lock">⌑ H1 locked to Canonical Question · read-only</span></div>${badge(d.status)}</div><div class="review-layout"><article class="reader-preview">${renderArticle(d.article)}</article><div class="review-sidebar">
<section><h3>Validation</h3><div class="validation-summary">${findings}</div></section>
<details open><summary>Structure</summary><div class="heading-tree">${d.headings.map(h=>`<div class="${h.level.toLowerCase()}"><b>${h.level}</b>${escapeHtml(h.text)}${h.lineage?`<small>${escapeHtml(h.lineage)}</small>`:""}</div>`).join("")}</div><h4>Required coverage</h4><ul>${d.requiredCoverage.map(x=>`<li>${escapeHtml(x)}</li>`).join("")}</ul></details>
<details open><summary>Books &amp; Links</summary>${d.books.map(book=>`<article class="book-link"><strong>${book.role}</strong><h4>${escapeHtml(book.title)}</h4>${external(book.url,"Inspect direct Book URL")}<small>Link: ${escapeHtml(book.linkStatus)} · Placement: ${escapeHtml(book.placement)}</small>${book.ctaText?`<p>CTA text: ${escapeHtml(book.ctaText)}</p>`:""}<button class="link" data-library>Open read-only Library detail →</button></article>`).join("")}</details>
<details open><summary>Knowledge Sources</summary>${d.knowledgeGap?`<div class="blocking"><strong>Knowledge Gap</strong><p>${escapeHtml(d.knowledgeGap)}</p></div>`:""}<p><strong>Knowledge Source:</strong> ${d.knowledgeSources.some(x=>x.language==="English")?"English Master":"Reader language"}<br><strong>Reader Edition:</strong> ${escapeHtml(d.language)}</p>${d.knowledgeSources.map(x=>`<div class="knowledge"><strong>${escapeHtml(x.title)}</strong><span>${escapeHtml(x.sourceType)} · ${escapeHtml(x.language)} · ${escapeHtml(x.version)}</span><small>${escapeHtml(x.status)} · ${escapeHtml(x.reference)}</small></div>`).join("")}</details>
<details><summary>Why this Blog?</summary><p><strong>CanonicalQuestion</strong><br>${escapeHtml(d.canonicalQuestion)}</p>${Object.entries(d.recommendation).map(([k,v])=>`<p><strong>${escapeHtml(words(k))}</strong><br>${escapeHtml(v)}</p>`).join("")}<button class="link" data-question>Open Question / Opportunity detail →</button></details>
<details><summary>History &amp; Versions</summary><p>Current version: <strong>v${d.draftVersion}</strong>${d.previousReviewedVersion?` · Previous reviewed: <button class="link" data-version="${d.previousReviewedVersion}">v${d.previousReviewedVersion}</button> · <button class="link" data-compare>Compare Versions</button>`:""}</p>${d.revisionNote?`<p>Revision note: ${escapeHtml(d.revisionNote)}</p>`:""}<ol>${d.history.map(x=>`<li><strong>${escapeHtml(x.event)}</strong> ${x.version?`· v${x.version}`:""}<small>${escapeHtml(x.at)}${x.note?` · ${escapeHtml(x.note)}`:""}</small></li>`).join("")}</ol></details>
${publication(d)}${promotion(d)}</div></div>${actions(d,stale)}`;bindDetail(d)}
function publication(d){if(!d.publication&&!d.wordpress)return"";return `<details open><summary>Publishing</summary>${d.publication?`<h4>Publication Package · ${badge(d.publication.packageStatus)}</h4><dl><dt>Meta Title</dt><dd>${escapeHtml(d.publication.metaTitle)}</dd><dt>Meta Description</dt><dd>${escapeHtml(d.publication.metaDescription)}</dd><dt>Proposed slug</dt><dd>${escapeHtml(d.publication.slug)}</dd><dt>Canonical URL preview</dt><dd>${escapeHtml(d.publication.canonicalUrlPreview)}</dd><dt>Structured Data</dt><dd>${escapeHtml(d.publication.structuredDataSummary)}</dd><dt>Search / AI validation</dt><dd>${escapeHtml(d.publication.searchValidation)} / ${escapeHtml(d.publication.aiValidation)}</dd></dl>`:""}${d.wordpress?`<h4>WordPress · ${badge(d.wordpress.status)}</h4><p>Site: ${escapeHtml(d.wordpress.site)} · Attempt ${d.wordpress.attempt}<br>Authentication: ${escapeHtml(d.wordpress.authenticationState)}<br>Post ID: ${escapeHtml(d.wordpress.postId||"Unavailable")}</p>${d.wordpress.authenticationState==="AuthenticationRequired"?'<button class="link" data-system>Open System / Authentication →</button>':""}${d.wordpress.status==="VerificationRequired"?'<div class="blocking"><strong>Verification Required</strong><p>The write result is ambiguous; it is not shown as Failed or Published.</p></div>':""}`:""}</details>`}
function promotion(d){if(!d.promotion&&!d.performance)return"";return `<details open><summary>Pinterest Promotion</summary>${d.promotion?`<p>${badge(d.promotion.state)} · Target: <strong>${d.promotion.target} ${escapeHtml(d.promotion.targetLabel)}</strong></p><div class="pin-lineage">${d.promotion.lineage.map(x=>`<div><b>${escapeHtml(x.headingLevel)}</b><span>${escapeHtml(x.heading)} → ${escapeHtml(x.pin)}</span>${badge(x.state)}</div>`).join("")}</div><button class="secondary" data-promotion="${d.promotion.state==="Held"?"ResumePinterestPromotion":"HoldPinterestPromotion"}">${d.promotion.state==="Held"?"Release / Resume Promotion":"Hold Pinterest Promotion"}</button><button class="link" data-pinterest>Open Pinterest workspace →</button>`:""}${d.performance?`<h4>Performance summary</h4><div class="performance-summary">${Object.entries({"Blog Visits":d.performance.blogVisits,"Search Clicks":d.performance.searchClicks,"Pinterest Referrals":d.performance.pinterestReferrals,"Primary Book CTA clicks":d.performance.primaryBookCtaClicks,"Related Book clicks":d.performance.relatedBookClicks,"AI Discovery observations":d.performance.aiDiscoveryObservations}).map(([k,v])=>`<div><span>${k}</span><strong>${v===null||v===undefined?"Unavailable":v}</strong></div>`).join("")}</div><button class="link" data-performance>View Performance →</button>`:""}</details>`}
function actions(d,stale){if(!["ReadyForCEOReview","RevisionRequired"].includes(d.status))return"";return `<div class="blog-actions"><span id="blog-action-state" aria-live="polite">Ready for CEO decision</span><button class="primary" data-decision="Approve" ${!d.eligibleForApproval||stale?"disabled":""}>Approve</button><button data-decision="ReturnForRevision">Return for Revision</button><button data-decision="Defer">Defer / Hold</button><div class="more-actions"><button data-decision="Reject">Reject</button><button class="destructive" data-decision="Delete">Delete</button></div></div>`}
function bindDetail(d){$("#blog-detail .detail-close").onclick=()=>$("#blog-detail").classList.remove("open");$("[data-latest]")?.addEventListener("click",()=>openDetail(d.id));document.querySelectorAll("[data-version]").forEach(x=>x.onclick=()=>openDetail(d.id,Number(x.dataset.version)));$("[data-question]")?.addEventListener("click",()=>window.alivoSelect?.("Questions"));$("[data-system]")?.addEventListener("click",()=>window.alivoSelect?.("System"));$("[data-performance]")?.addEventListener("click",()=>window.alivoSelect?.("Performance"));$("[data-pinterest]")?.addEventListener("click",()=>window.alivoSelect?.("Pinterest"));document.querySelectorAll("[data-decision],[data-promotion]").forEach(x=>x.onclick=()=>decide(x.dataset.decision||x.dataset.promotion,d))}
async function decide(decision,d){let instructions="",note="";if(decision==="ReturnForRevision"){instructions=prompt("Revision instructions (required)","")||"";if(!instructions.trim())return}else if(["Reject","Defer"].includes(decision))note=prompt(`${words(decision)} — optional CEO note`,"")??"";const destructive=decision==="Delete";const message=decision==="Approve"?`H1: ${d.h1}\nLanguage: ${d.language}\nMarket: ${d.market}\nDraft Version: v${d.draftVersion}\nPrimary Book: ${d.primaryBook}\nValidation: ${d.validationState}\n\nAction: Approve for Publishing`:destructive?"Remove this Draft from active production. Preserved governance/audit history may remain.":`${words(decision)} this exact Draft version?`;if(!confirm(message))return;const state=$("#blog-action-state");state.textContent="Submitting";document.querySelectorAll("[data-decision]").forEach(x=>x.disabled=true);try{const result=await window.alivoBlogs?.decide?.({businessPackageId:packageId,blogId:d.id,draftVersion:d.draftVersion,decision,instructions,note});const resultState=actionStates.has(result?.state)?result.state:"Failed";state.textContent=words(resultState);if(resultState==="Succeeded")await load()}catch(error){state.textContent=words(actionStates.has(error?.code)?error.code:"Failed")}}
function changeView(next){view=next;page=1;selected=undefined;$("#blog-detail").classList.remove("open");document.querySelectorAll("[data-blog-view]").forEach(x=>x.setAttribute("aria-selected",String(x.dataset.blogView===view)));load()}
document.querySelectorAll("[data-blog-view]").forEach(x=>x.onclick=()=>changeView(x.dataset.blogView));let timer;$("#blog-search").oninput=()=>{clearTimeout(timer);timer=setTimeout(load,250)};document.querySelectorAll(".blog-controls select,.blog-controls input[type=date]").forEach(x=>x.onchange=load);$("#blog-previous").onclick=()=>{page--;load()};$("#blog-next").onclick=()=>{page++;load()};window.addEventListener("alivo:blogs:open",()=>changeView(view));
if(location.hash.startsWith("#blogs")){const params=new URLSearchParams(location.hash.split("?")[1]||"");view=params.get("view")||"pipeline";page=Math.max(1,Number(params.get("page"))||1);document.querySelectorAll("[data-blog-view]").forEach(x=>x.setAttribute("aria-selected",String(x.dataset.blogView===view)));load()}
