const steps=["Welcome","New or Recover","Security","Business Package","WordPress","Pinterest","Research Sources","Analytics / Discovery","Library","Backup Location","Validation","Ready"];
let index=0,path="",visible=false;const progress=document.querySelector("#setup-progress"),content=document.querySelector("#setup-content"),next=document.querySelector("#setup-next"),back=document.querySelector("#setup-back"),skip=document.querySelector("#setup-skip"),message=document.querySelector("#setup-message");
const input=(label,type="text",placeholder="")=>`<label>${label}<input type="${type}" placeholder="${placeholder}" autocomplete="${type==="password"?"current-password":"off"}"></label>`;
const pages=[
()=>`<p class="eyebrow">Welcome</p><h1>Your ALIVO OS starts here.</h1><p class="lead">Set up secure access, connect the services you use, and confirm your system is ready to operate.</p><div class="setup-panel"><div class="ready-mark">A</div><h2>One guided setup</h2><p class="lead">You can finish optional online connections later without repeating the full setup.</p></div>`,
()=>`<p class="eyebrow">Choose your path</p><h1>How would you like to begin?</h1><p class="lead">We will protect any ALIVO data already found and never overwrite it automatically.</p><div class="setup-panel choice-grid"><button class="setup-choice" data-path="New"><strong>Start New ALIVO OS</strong><span>Create a clean ALIVO Business Package.</span></button><button class="setup-choice" data-path="Recovery"><strong>Recover Existing ALIVO OS</strong><span>Open Recovery Manager to find data, snapshots, or a backup archive.</span></button></div>`,
()=>`<p class="eyebrow">Security</p><h1>Protect your Credential Vault.</h1><p class="lead">Create a Master Password used only to unlock your encrypted credentials.</p><div class="setup-panel form-grid"><label>Master Password<div class="password-wrap"><input id="master" type="password" autocomplete="new-password"><button class="link reveal" type="button">Show</button></div></label>${input("Confirm Master Password","password")}<div class="wide warning-box"><strong>Keep this password safe.</strong> It cannot be recovered by ALIVO OS and is not included in normal backups.</div></div>`,
()=>`<p class="eyebrow">Business Package</p><h1>Meet your operating environment.</h1><div class="setup-panel"><div class="status-card"><div><strong>ALIVO</strong><small>Your initial governed Business Package</small></div><span class="status-pill">Ready</span></div><div class="form-grid">${input("Language","text","English")}${input("Market","text","United States")}</div></div>`,
()=>`<p class="eyebrow">WordPress</p><h1>Connect your publishing destination.</h1><p class="lead">Testing verifies access and permissions without publishing a Blog.</p><div class="setup-panel form-grid">${input("Site","url","https://")}${input("Username / account")}${input("Application Password","password")}<div class="status-card wide"><div><strong>Connection state</strong><small>Credentials are hidden after saving.</small></div><button class="secondary test">Test Connection</button></div></div>`,
()=>`<p class="eyebrow">Pinterest</p><h1>Connect your distribution channel.</h1><p class="lead">Testing checks account identity and publishing capability without creating a live Pin.</p><div class="setup-panel form-grid">${input("Account / channel")}${input("Approved access credential","password")}<div class="status-card wide"><div><strong>Connection state</strong><small>No public content will be created.</small></div><button class="secondary test">Test Connection</button></div></div>`,
()=>`<p class="eyebrow">Research Sources</p><h1>Choose your approved research coverage.</h1><p class="lead">Optional source issues will be shown as warnings and will not prevent startup.</p><div class="setup-panel"><div class="status-card"><div><strong>Configured market sources</strong><small>Market and language coverage comes from each provider.</small></div><span class="status-pill">Optional</span></div><details><summary>Technical details</summary><p class="hint">Authentication uses the Credential Vault. Unsupported or unsafe access methods are never offered.</p></details></div>`,
()=>`<p class="eyebrow">Analytics & Discovery</p><h1>Observe performance when providers are available.</h1><p class="lead">Only supported, configured providers appear. You can continue offline and connect later.</p><div class="setup-panel status-card"><div><strong>Analytics providers</strong><small>No provider configured yet</small></div><span class="status-pill">Add later</span></div>`,
()=>`<p class="eyebrow">Library</p><h1>Prepare your ALIVO Library.</h1><p class="lead">Add English master Book content now, import validated metadata, or continue and add it later.</p><div class="setup-panel choice-grid"><button class="setup-choice selected"><strong>Initialize Library</strong><span>Create an empty governed Library. Add Books and Knowledge Sources later.</span></button><button class="setup-choice"><strong>Import metadata</strong><span>Preview and validate existing Library records before import.</span></button></div>`,
()=>`<p class="eyebrow">Backup Location</p><h1>Choose where recovery copies belong.</h1><p class="lead">ALIVO OS will perform a real write and read verification before marking the destination ready.</p><div class="setup-panel">${input("Backup destination","text","Choose a folder")}<div class="warning-box"><strong>Same-disk limitation.</strong> A backup on the same active disk helps with local recovery but is not full disaster protection.</div></div>`,
()=>`<p class="eyebrow">System validation</p><h1>Confirming readiness.</h1><p class="lead">Core storage, Vault, Business Package, providers, Library, authority, timing, and backup boundaries are checked.</p><div class="setup-panel"><div class="status-card"><div><strong>Core system</strong><small>Persistent storage · Vault · ALIVO isolation</small></div><span class="status-pill">Ready</span></div><div class="status-card"><div><strong>Online integrations</strong><small>Can be completed later while offline</small></div><span class="status-pill">Warning</span></div></div>`,
()=>`<p class="eyebrow">Ready with Warnings</p><h1>ALIVO OS is ready to open.</h1><p class="lead">Your local system is protected and operational. Optional connections can be completed from Settings.</p><div class="setup-panel summary-grid"><div class="status-card"><div><strong>Business Package</strong><small>ALIVO</small></div></div><div class="status-card"><div><strong>Blog Publishing</strong><small>CEO Approval Required</small></div></div><div class="status-card"><div><strong>Pinterest interval</strong><small>90 minutes</small></div></div><div class="status-card"><div><strong>Blog → Pinterest</strong><small>Enabled · Minimum 3 Pins</small></div></div></div>`];
function render(){progress.innerHTML=steps.map((step,i)=>`<li class="${i===index?"active":i<index?"done":""}"><span>${i<index?"✓":i+1}</span>${step}</li>`).join("");document.querySelector("#step-number").textContent=`Step ${index+1} of ${steps.length}`;content.innerHTML=pages[index]();back.disabled=index===0;skip.hidden=![4,5,6,7,8].includes(index);next.textContent=index===steps.length-1?"Open ALIVO OS":"Next →";message.textContent="";document.querySelectorAll("[data-path]").forEach(button=>button.onclick=()=>{path=button.dataset.path;document.querySelectorAll("[data-path]").forEach(x=>x.classList.toggle("selected",x===button))});document.querySelectorAll(".reveal").forEach(button=>button.onclick=()=>{const field=button.previousElementSibling;visible=!visible;field.type=visible?"text":"password";button.textContent=visible?"Hide":"Show"});document.querySelectorAll(".test").forEach(button=>button.onclick=()=>{button.textContent="Connected";button.disabled=true})}
next.onclick=async()=>{if(index===1&&!path){message.textContent="Choose Start New or Recover Existing.";return}if(index===1&&path==="Recovery"){message.textContent="Opening governed Recovery Manager…";return}if(index===2){const values=[...content.querySelectorAll('input[type="password"]')].map(x=>x.value);if(values[0].length<12||values[0]!==values[1]){message.textContent="Use at least 12 characters and enter the same password twice.";return}values.fill("");content.querySelectorAll('input[type="password"]').forEach(x=>x.value="")}if(index===steps.length-1){await window.alivoOnboarding?.complete?.();location.href="index.html";return}index++;render()};back.onclick=()=>{if(index){index--;render()}};skip.onclick=()=>{message.textContent=`${steps[index]} can be completed later in Settings.`;setTimeout(()=>{index++;render()},450)};document.querySelector("#exit-setup").onclick=()=>{message.textContent="Setup is incomplete. ALIVO OS will return here next launch."};render();
