const destinations = {
  Dashboard: "Your operational overview", Questions: "Question intelligence and CEO decision context", Blogs: "Blog pipeline, review and publication state", Pinterest: "Static Pin pipeline, queue and timing", Library: "CEO-managed business content library", Performance: "Channel-separated performance visibility", System: "Workflows, agents, integrations and audit visibility", Settings: "CEO-controlled operational configuration"
};
const nav = document.querySelector("nav"), main = document.querySelector("main"), dashboard = document.querySelector("#dashboard"), placeholder = document.querySelector("#placeholder");
for (const [name, copy] of Object.entries(destinations)) { const button = document.createElement("button"); button.textContent = name; button.dataset.destination = name; button.addEventListener("click", () => select(name, copy)); nav.append(button); }
function select(name, copy) { document.querySelectorAll("nav button").forEach(button => { const selected = button.dataset.destination === name; button.classList.toggle("selected", selected); button.setAttribute("aria-current", selected ? "page" : "false"); }); document.querySelector("#title").textContent = name; document.querySelector("#subtitle").textContent = copy; dashboard.hidden = name !== "Dashboard"; placeholder.hidden = name === "Dashboard"; document.querySelector("#empty-title").textContent = `${name} workspace is ready`; document.querySelector("#empty-copy").textContent = `No ${name.toLowerCase()} data is loaded yet. This workspace is prepared for its governed application read model.`; history.replaceState({}, "", `#${name.toLowerCase()}`); main.focus(); }
select(Object.keys(destinations).find(name => `#${name.toLowerCase()}` === location.hash) ?? "Dashboard", destinations[Object.keys(destinations).find(name => `#${name.toLowerCase()}` === location.hash) ?? "Dashboard"]);
const updateClock = () => document.querySelector("#clock").textContent = new Intl.DateTimeFormat(undefined, { dateStyle: "medium", timeStyle: "short" }).format(new Date()); updateClock(); setInterval(updateClock, 60000);
document.querySelector("#refresh").addEventListener("click", event => { event.currentTarget.textContent = "Refreshing…"; setTimeout(() => event.currentTarget.textContent = "Refresh status", 500); });
